### ISSUE TITLE
Modul AJAX TOP NAVIGATION

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#1002]
Bei freigegebenen Modul wird bei Klick auf den Mannschaftsspielplan, Mannschaftsinfo einer Mannschaft  Fehlermeldungen ausgegeben. Dies tritt auch auf, wenn z.B. bei einer Tabelle, die nicht explizit vom Modul geöffnet wird auf:
Fehlermeldung Mannschaftsspielplan
![Mod_ajax_top_navigation_01](https://user-images.githubusercontent.com/5115688/76633669-5f0c1e80-6545-11ea-8045-1b3cd808c326.jpg)

Seite wie gehabt: demo.jsm-help.de

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
OK! Läuft! 👍
