### ISSUE TITLE
Backend-View: projectreferees Layout: default

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1005]
Hallo,
ich versuche gerade ein Update unsere Webseite von Joomla 2.5 mit installiertem Joomleague auf Joomla 3.9.16 mit JSM durchzuführen.
Ich habe die bestehenden Daten importiert und wollte nun ein neues Projekt anlegen und erhalte bei der Zuweisung der Schiedsrichter folgende Fehlermeldung:
Es ist ein Fehler aufgetreten!

    404 View nicht gefunden [Name, Typ, Präfix]: persons, html, sportsmanagementView
    /var/www/web262/html/libraries/src/MVC/Controller/BaseController.php:847 

Call stack
# 	Function 	Location
1 	() 	JROOT/libraries/src/MVC/Controller/BaseController.php:847
2 	Joomla\CMS\MVC\Controller\BaseController->getView() 	JROOT/libraries/src/MVC/Controller/BaseController.php:621
3 	Joomla\CMS\MVC\Controller\BaseController->display() 	JROOT/administrator/components/com_sportsmanagement/controller.php:57
4 	SportsManagementController->display() 	JROOT/libraries/src/MVC/Controller/BaseController.php:710
5 	Joomla\CMS\MVC\Controller\BaseController->execute() 	JROOT/administrator/components/com_sportsmanagement/sportsmanagement.php:295
6 	require_once() 	JROOT/libraries/src/Component/ComponentHelper.php:402
7 	Joomla\CMS\Component\ComponentHelper::executeComponent() 	JROOT/libraries/src/Component/ComponentHelper.php:377
8 	Joomla\CMS\Component\ComponentHelper::renderComponent() 	JROOT/libraries/src/Application/AdministratorApplication.php:101
9 	Joomla\CMS\Application\AdministratorApplication->dispatch() 	JROOT/libraries/src/Application/AdministratorApplication.php:159
10 	Joomla\CMS\Application\AdministratorApplication->doExecute() 	JROOT/libraries/src/Application/CMSApplication.php:196
11 	Joomla\CMS\Application\CMSApplication->execute() 	JROOT/administrator/index.php:51 

Was kann ich hier machen?

**Comment by diddipoeler** [comment]
Mach mal bitte ein Update der Komponente.

**Comment by ortwin20000** [comment]
Danke das war es. Dachte ich hätte das aktuellste Package installiert aber dass ich es noch über das Repository aktualisieren sollte, daran habe ich nicht gedacht.
