### ISSUE TITLE
Nach Migration funktionieren Frontend-Links nicht

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1006]
Hallo,
ich versuche gerade ein Update unsere Webseite http://www.noefbv.at von Joomla 2.5 mit installiertem Joomleague auf Joomla 3.9.16 mit JSM durchzuführen.
Ich habe die bestehenden Daten importiert und wollte nun die bestehenden Menüeinträge auf die von JSM umstellen.
Dafür verwende ich normalerweise die Ergebnis-Tabellen-View aber bei einem Aufruf der geänderten Menüeinträge erhalte ich folgende Fehlermeldung:
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3

Call stack
# 	Function 	Location
1 	() 	JROOT/libraries/joomla/database/driver/mysqli.php:665
2 	JDatabaseDriverMysqli->execute() 	JROOT/libraries/joomla/database/driver.php:1740
3 	JDatabaseDriver->loadResult() 	JROOT/components/com_sportsmanagement/models/project.php:250
4 	sportsmanagementModelProject::getProject() 	JROOT/components/com_sportsmanagement/models/project.php:354
5 	sportsmanagementModelProject::increaseRound() 	JROOT/components/com_sportsmanagement/models/project.php:312
6 	sportsmanagementModelProject::getCurrentRound() 	JROOT/components/com_sportsmanagement/models/ranking.php:105
7 	sportsmanagementModelRanking->__construct() 	JROOT/libraries/src/MVC/Model/BaseDatabaseModel.php:202
8 	Joomla\CMS\MVC\Model\BaseDatabaseModel::getInstance() 	JROOT/libraries/src/MVC/Controller/BaseController.php:549
9 	Joomla\CMS\MVC\Controller\BaseController->createModel() 	JROOT/libraries/src/MVC/Controller/BaseController.php:736
10 	Joomla\CMS\MVC\Controller\BaseController->getModel() 	JROOT/libraries/src/MVC/Controller/BaseController.php:624
11 	Joomla\CMS\MVC\Controller\BaseController->display() 	JROOT/components/com_sportsmanagement/controller.php:44
12 	sportsmanagementController->display() 	JROOT/libraries/src/MVC/Controller/BaseController.php:710
13 	Joomla\CMS\MVC\Controller\BaseController->execute() 	JROOT/components/com_sportsmanagement/sportsmanagement.php:292
14 	require_once() 	JROOT/libraries/src/Component/ComponentHelper.php:402
15 	Joomla\CMS\Component\ComponentHelper::executeComponent() 	JROOT/libraries/src/Component/ComponentHelper.php:377
16 	Joomla\CMS\Component\ComponentHelper::renderComponent() 	JROOT/libraries/src/Application/SiteApplication.php:194
17 	Joomla\CMS\Application\SiteApplication->dispatch() 	JROOT/libraries/src/Application/SiteApplication.php:233
18 	Joomla\CMS\Application\SiteApplication->doExecute() 	JROOT/libraries/src/Application/CMSApplication.php:196
19 	Joomla\CMS\Application\CMSApplication->execute() 	JROOT/index.php:49

Hängt das mit den "alten" Templates von Joomleague zusammen?

**Comment by ortwin20000** [comment]
Es dürfte irgendwie mit den Templates zusammenhängen. Die meisten Projekte verwenden ein Master-Template. Ich habe nun in einem Projekt das Master-Template entfernt und wieder hinzugefügt und nun wird mir die Seite angezeigt. Es kommt dann aber noch die Fehlermeldung "Achtung, ungültige Tabellenauswahl".
Im Master-Template ist als Tabelle "Normale Tabelle" ausgewählt. Ein Ändern auf eine andere Tabelle ändert nichts an der Fehlermeldung.

**Comment by sigal** [comment]
Kann man das auch online sehen?
Die Fehlermeldung sagt aus, dass im Template ranking (Tabelle) unter Optionen eine falsche Einstellung getätigt wurde. Die Fehlermeldung "Achtung, ungültige Tabellenauswahl" ist zugegebenermaßen ein wenig unglücklich formuliert. (werde ich ändern)
Also im zuständigen Mastertemplate das Template ranking (Tabelle) öffnen und die Einstellungen kontrollieren.
In einer meiner Mastertemplates hab ich folgende Einstellung:

![template_ranking](https://user-images.githubusercontent.com/5115688/76760409-e4820f80-678d-11ea-887d-65ea60f5f154.jpg)

Zu sehen unter: https://demo.jsm-help.de/results-ranking/ranking/0/0/4192/0/0/0/0/0

**Comment by ortwin20000** [comment]
Im Frontend sieht das so aus:
http://www.noefbv.at/index.php/feld-19/ll-frauen-19/resultsranking.html

Im Backend habe ich derzeit nur das Master-Template ohne Overrides zugewiesen.
![jsm_template](https://user-images.githubusercontent.com/15192502/76761260-6a528a80-678f-11ea-9ed0-6c5dc6fc922a.JPG)

**Comment by sigal** [comment]
Sehe jetzt, das es sich um Faustball handelt. Welche Sportart wurde im Projekt gewählt?
Und da ich dieser Sportart nicht ganz eingelesen bin, wäre es hilfreich zu wissen, welche Kriterien zum Sortieren der Tabellen in dieser Sportart zum Tragen kommen?

**Comment by ortwin20000** [comment]
Faustball habe ich als Sportart angelegt und im Projekt hinterlegt. Altersgruppen habe ich keine angelegt.
Die Kriterien unterscheiden sich manchmal pro Liga. Dies kann jeder Verband selber definieren.
Derzeit habe ich die Sortierung nach Punkte, Balldifferenz, Satzdifferenz und gewonnene Sätze.
Es könnte aber auch anders sein: z.B. Gewonnene Sätze, Balldifferenz
Ich verwende hier das Satzsystem der Projekte.
Faustball wird ja so ähnlich zu pflegen sein wie Volleyball oder andere Sportarten mit Sätzen.

**Comment by sigal** [comment]
Ok. Bitte ein Projekt zum Testen an stony@sport4u.at senden.
Die Ausgabe der Fehlermeldung hab ich schon eruiert, aber nicht den Grund dafür.
Bei Fußball wird mir das nicht ausgegeben.

**Comment by ortwin20000** [comment]
Ich hoffe das ist so richtig.
[sportsmanagement.zip](https://github.com/diddipoeler/sportsmanagement/files/4338783/sportsmanagement.zip)

**Comment by ortwin20000** [comment]
E-Mail habe ich geschickt. Ich hoffe es ist angekommen.

**Comment by ortwin20000** [comment]
Ich vermute dass es irgendwie mit den alten Templates von Joomleague zu tun hat.
Kann man diese irgendwie komplett entfernen und nur die von JSM behalten?

**Comment by sigal** [comment]
Das gibt es. Aber bitte wie immer bei solchen Aktionen **vorher die Datenbank sichern**.

![installtools-db-tools-01](https://user-images.githubusercontent.com/5115688/76889469-efb86680-6885-11ea-819e-63b08662d3af.jpg)

Dann:

![installtools-db-tools-02](https://user-images.githubusercontent.com/5115688/76889533-08c11780-6886-11ea-9f3a-a124d6d5fa87.jpg)

Das ganze Prozedere kann sich jeder ersparen, wenn mal für Projekte **_ein Mastertemplate_** verwendet wird, das man für alle Projekte verwenden kann.

Wie das ganz einfach geht?
Mehr morgen dazu.

**Comment by sigal** [comment]
Datei erhalten und installiert. Hier ohne Fehler zu sehen -> https://test.jsm-help.de/faustball-noe/frauen-landesliga-2019/resultsranking

Fehler? 

![Import-01](https://user-images.githubusercontent.com/5115688/77116338-537e9300-6a30-11ea-9119-c1b23b5688bb.jpg)

**Comment by ortwin20000** [comment]
Da dürfte bei der Übernahme die falsche Liga gewählt worden sein. Ich habe dies korrigiert aber der Fehler bleibt auf der Seite bestehen.
Wie kann ich dies debuggen um festzustellen wo der Fehler auftritt?

**Comment by sigal** [comment]
Bitte mal das Template ranking (Tabelle) öffnen und speichern.

**Comment by ortwin20000** [comment]
Das hab ich schon einige Mal versucht.
Ich habe auch das Master-Template weggenommen und Ranking des Master-Template überschrieben.
Wäre es sinnvoll dir auch einen Zugang zur Webseite einzurichten?

**Comment by sigal** [comment]
Ist wirklich nur diese Liga betroffen?
Wenn ja, bitte mal einen Zugang an meine Mail Adresse.

**Comment by diddipoeler** [comment]
Wenn ich mich hier https://www.noefbv.at/administrator anmelden möchte erhalte ich folgende Fehlermeldung:
Forbidden
You don't have permission to access /administrator on this server.

Unterstützen kann ich also nicht.

**Comment by ortwin20000** [comment]
Bitte jetzt noch einmal versuchen. Ich hatte eine Absicherung eingebaut. Diese habe ich jetzt vorübergehend mal deaktiviert.

**Comment by ortwin20000** [comment]
@sigal auch dir habe ich jetzt einen Zugang eingerichtet und die Zugangsdaten per E-Mail geschickt.

Vielen herzlichen Dank an euch beide für eure Mühe.

**Comment by diddipoeler** [comment]
Den Server schon mal auf PHP 7.2 updaten.

**Comment by ortwin20000** [comment]
Hallo,
ist in Planung von meinem Hosting-Provider. Die migrieren seit dieser 
Woche auf neue Server und dieser Account wurde noch nicht umgestellt. 
Das höchste ist hier PHP 7.1
Auf den neuen Servern läuft dann PHP 7.3

lg
Andreas

------ Originalnachricht ------
Von: "diddipoeler" <notifications@github.com>
An: "diddipoeler/sportsmanagement" <sportsmanagement@noreply.github.com>
Cc: "ortwin20000" <andreas@haunold.co.at>; "Author" 
<author@noreply.github.com>
Gesendet: 20.03.2020 18:56:20
Betreff: Re: [diddipoeler/sportsmanagement] Nach Migration funktionieren 
Frontend-Links nicht (#1006)

**Comment by diddipoeler** [comment]
Ein Template mit Bootstrap wäre auch nicht schlecht.

**Comment by ortwin20000** [comment]
Ist in Planung aber wichtiger ist für uns die Migration auf JSM.
Die Webseite war zuvor noch auf Joomla 2.5 
Bin froh dass jetzt endlich wieder ein aktuelles Joomla darauf läuft.

**Comment by diddipoeler** [comment]
Im Template Ranking, Feld Kriterien für Rangfolge steht das:""POINTS, DIFF, LEGS_DIFF, LEGS_WIN,"
Habe ich geändert auf das "POINTS, DIFF, LEGS_DIFF, LEGS_WIN"

**Comment by diddipoeler** [comment]
Ich benötige Superadminrechte, da ich nichts installieren kann.

**Comment by ortwin20000** [comment]
Das mit dem "-Zeichen dürfte durch die Migration entstanden sein. Hatte ich aber auch schon in anderen Projekten entfernt und hat keine Verbesserung gebracht.
Superadmin hast du jetzt.

**Comment by diddipoeler** [comment]
So Fehler ist weg.
Du hattest das eingetragen "POINTS, DIFF, LEGS_DIFF, LEGS_WIN,"
Hinter LEGS_WIN musste nur das Komma weg.
JSM geht davon aus, wenn da noch ein Komma steht, dass auch
noch ein Eintrag kommt.

**Comment by ortwin20000** [comment]
Autsch.
Da wäre ich nie darauf gekommen. In Joomleague dürfte das kein Problem verursacht haben.
Vielen vielen herzlichen Dank für eure Bemühungen.
Wenn ich wo helfen kann, gebt mir bitte Bescheid.

**Comment by diddipoeler** [comment]
Klar das aus deiner MAIL:
Ich habe zum Beispiel für Spielberichte ein PDF hinzugefügt welches mir anhand der Begegnungen das PDF vorbefüllt.
Sieht man schön z.B. hier: http://www.noefbv.at/index.php/2016-08-10-10-01-17/u10-m%C3%A4nnlich.html

**Comment by ortwin20000** [comment]
Ich werde mich daran versuchen ;-)
