### ISSUE TITLE
Aktuelle Saison listet zu viele Projekte auf

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1007]
Hallo,
in meiner Ansicht für die aktuelle Saison werden 20 Projekte angezeigt.
![jsm_currentsaison](https://user-images.githubusercontent.com/15192502/76763331-34afa080-6793-11ea-964e-0585fdcb5e0e.JPG)

Wo kann ich die Saison für die korrekte Ansicht konfigurieren?
Ich habe nur im Bereich "Ligen" eine Option "Aktueller Saison zuordnen" gefunden aber da eine Liga wie z.B. 1. Landesliga in mehreren Saisonen verwendet wird, ergibt das so für mich keinen Sinn.

![jsm_ligen](https://user-images.githubusercontent.com/15192502/76763357-3f6a3580-6793-11ea-9e7e-6d642b5cb400.JPG)

Gibt es die Möglichkeit z.B. die Saison "Feldmeisterschaft 2020" als aktuelle Saison auszuwählen und in der Ansicht "Aktuelle Saison" alle Projekte dieser Saison anzuzeigen?
Oder ist dieser Bereich für etwas anderes gedacht?

**Comment by sigal** [comment]
Unter Optionen im BE einstellbar.

![Optionen-aktuelle-saison](https://user-images.githubusercontent.com/5115688/76770735-ab9e6680-679e-11ea-974d-394599f3e0c5.jpg)

Viel Spass!

**Comment by sigal** [comment]
Anzuzeigende Ligen müssen der aktuellen Saison zugeordnet werden, da sonst keine Ansicht im Backend!
Merke: Ligen die der aktuellen Saison zugeordnet wurden, aber schon einer älteren Saison angehören, werden natürlich nicht in der Ansicht aktuelle Saison angezeigt.
