### ISSUE TITLE
Aufruf von Vereinsinformation über Ergebnis-Tabellen-View

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1008]
Hallo,
wenn ich die Vereinsinformation über die Ergebnis-Tabellen-View aufrufe erhalte ich diesen Fehler:
Notice: Trying to get property of non-object in /var/www/web262/html/components/com_sportsmanagement/models/clubinfo.php on line 461 Notice: Trying to get property of non-object in /var/www/web262/html/components/com_sportsmanagement/models/clubinfo.php on line 462 Notice: Trying to get property of non-object in /var/www/web262/html/components/com_sportsmanagement/models/clubinfo.php on line 463 Notice: Trying to get property of non-object in /var/www/web262/html/components/com_sportsmanagement/models/clubinfo.php on line 464

`                   $team->ptid = $result->ptid;
                    $team->project_team_picture = $result->project_team_picture;
                    $team->trikot_home = $result->trikot_home;
                    $team->trikot_away = $result->trikot_away;
`
Ich habe den Mannschaften die Platzhalter-Bilder zugewiesen. Im Backend werden sie auch angezeigt. Im Template ClubInfo habe ich die Mannschaftsbilder und Trikots deaktiviert.

http://www.noefbv.at/index.php/feld-19/ll-frauen-19/clubinfo/0/0/120:frauen-landesliga/9:sv-wuerth-boeheimkirchen.html

**Comment by ortwin20000** [comment]
Ich habe jetzt auch das Modul zur Anzeige der Vereine von Joomleague mit dem von JSM ausgetauscht. Interessant ist, dass der Fehler bei jedem Verein auftritt bis auf diesen hier:
http://www.noefbv.at/index.php/component/sportsmanagement/clubinfo/0/0/7:vereine/1:atv-kottingbrunn.html

Ich hätte nun versucht die Daten im Backend zu vergleichen, habe aber in den Stammdaten des Vereins keinen Unterschied festgestellt. Ich denke es dürfte irgendwie mit den zugewiesenen Mannschaften zusammenhängen.

**Comment by diddipoeler** [comment]
Kannst Du mir mal bitte einen Adminzugang mit allen Rechten auf Deiner seite einrichten ?

**Comment by ortwin20000** [comment]
E-Mail mit den Zugangsdaten ist unterwegs.

**Comment by ortwin20000** [comment]
Ich habe nun festgestellt, dass es mit ziemlicher Sicherheit mit den "alten" Templates aus Joomleague zusammenhängt. Ich hab jetzt das Master-Template neu gespeichert und in den Projekten Überschreibungen weggenommen. Nun werden mir die Vereins-Seiten korrekt angezeigt.

Derzeit tritt nur noch ein Fehler mit folgender Meldung auf:
Fehler
Achtung, ungültige Tabellenauswahl
Aber dafür gibt es ja bereits einen anderen Eintrag im GitHub.

Ich werde wohl bei neuen Projekten die Templates neu einrichten um auf Nummer sicher zu gehen.
Gibt es eine Möglichkeit alle Templates zurückzusetzen, damit keine Reste von Joomleague vorhanden sind?
