### ISSUE TITLE
Frontend Ergebniss Eingabe

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1013]
Hallo

Es wäre eine tolle Sache wenn sich ein Trainer selber einloggen könnte im Frontend und das Spiel Verschieben könnte. Uhrzeit und Ergebniss funktionieren da schon. Nur das Datum geht nicht.

**Comment by ortwin20000** [comment]
Ist dieser Punkt noch aktuell? Ich kann im Frontend das Datum in der Ergebniseingabe ändern.

**Comment by Karntner** [comment]
Eigentlich nicht mehr. Wenn man das Modul anpasst kann man das Datum ändern






mit freundlichen Grüßen

Franz Karntner
Waschenberger Strasse 4c
4651 Stadl Paura
0676 97 36 036
franz.karntner@gmail.com

________________________________

**Comment by Karntner** [comment]
Die Spalte zur Eingabe der Uhrzeit könnte man noch ein wenig breiter machen. 

![image](https://user-images.githubusercontent.com/59525415/78458289-735cba80-76b0-11ea-9903-71197934e8c2.png)

**Comment by ortwin20000** [comment]
Also bei mir ist das Popup nicht leer aber es ist kein Popup sondern eine eigene Seite.
Wenn ich dann auf Abbrechen klicke lande ich in einer Dauerschleife.

**Comment by ortwin20000** [comment]
Zu deinem anderen Problem: Ich möchte gerne den Trainern die Ergebniseingabe freischalten. Leider kann nur der ersteller des Projektes was eintragen!

Du kannst in Joomla Gruppen definieren. Ich habe hier zum Beispiel eine neue mit dem Namen "JSM" angelegt.
![grafik](https://user-images.githubusercontent.com/15192502/78499247-cfc2e700-774f-11ea-9cd8-97261e05fed1.png)

Diese Gruppe kannst du dann in den Projekteinstellungen eintragen:
![grafik](https://user-images.githubusercontent.com/15192502/78499257-df423000-774f-11ea-8abc-6f3337cd359d.png)

Jeder Joomla-Benutzer der in dieser Gruppe eingetragen ist, sollte dann auch im Frontend die Spielergebnisse eintragen können.
![grafik](https://user-images.githubusercontent.com/15192502/78499288-0dc00b00-7750-11ea-99e9-74f4d9845266.png)

Den Hinweistext könnte man vielleicht noch entfernen.

**Comment by ortwin20000** [comment]
Ich denke dass einiges am verwendeten Template liegt. Bei mir wird das Popup mit der Klasse print geladen und es wird alles in einem angezeigt. Bei Kantner aber korrekt mit Tabs angezeigt. Sobald man bei ihm die Tabs anklickt verschwindet das zuvor ausgewählte Tab. Möglich das ein Konflikt mit Bootstrap des Templates vorhanden ist.

**Comment by ortwin20000** [comment]
Ich habe jetzt bei mir das Template Helix3 installiert und damit wird mir nun auch das Popup mit Tabs angezeigt. Die Tabs verschwinden auch nicht mehr.
Meine Einstellungen im overall-Template:
![grafik](https://user-images.githubusercontent.com/15192502/78538271-06047300-77f1-11ea-9f2d-cda7557cf092.png)

Einziges Problem ist noch der Button "Abbrechen". Bei diesem lande ich in einer Endlosschleife und muss das Browser-Tab schließen.

**Comment by sigal** [comment]
Das mit den verschwindenden TABs hatten wir schon mal. Einige Templates werden ohne der bootstrap-tab.js Datei ausgeliefert
Diddi hat dafür ein Plugin kreiert, mit der man auch diese Datei nachladen kann. **JSM Plugin - Bootstrap**

Bitte mal testen.

![plugin_bootstrap](https://user-images.githubusercontent.com/5115688/78565325-0b2be700-781e-11ea-8f05-2c65c146c1ba.jpg)

**Comment by Karntner** [comment]
Ich habe da jetzt ein neues Problem. 
Wenn ich im Frontend die Spiedetails bearbeiten will lande ich beim Schliessen in einer Endlosschleife.

**Comment by ortwin20000** [comment]
Eine Endlosschleife hatte ich auch mal beim Drücken auf den Button Abbrechen aber nicht beim Speichern.
