### ISSUE TITLE
Modul Matches

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1014]
Hallo

Im Modul Matches wird nicht angezeigt das ein Spiel absagt, abgebrochen oder dgl ist, 
![image](https://user-images.githubusercontent.com/59525415/77314279-a17fe900-6d05-11ea-8d67-2c28ca3c569e.png)

**Comment by sigal** [comment]
Nach PR #1026 fehlt Ausgabe von -:-

![#1014_01](https://user-images.githubusercontent.com/5115688/77752696-54af5180-7028-11ea-803b-27462af2b883.jpg)

-----------------------------------------------------------------------
![#1014_02](https://user-images.githubusercontent.com/5115688/77752726-67298b00-7028-11ea-8382-67cda62d7e12.jpg)
