### ISSUE TITLE
Alternativer Text für Sätze

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1016]
In dem Template ranking gibt es die Möglichkeit einen alternativen Text für Sätze zu definieren.
Hier hätte ich Bälle eingetragen.
Nun wird mir aber in der Tabellenansicht der alternative Text nicht angezeigt. Weder im Header als Tooltip noch in der Spaltenbeschreibung.

Ich hätte mich daran versucht die Codestellen in der Datei default_rankingheading.php entsprechend zu erweitern:
`        case 'LEGS':
            echo '<th class="headers">';
            if ($this->config['alternative_legs']) {
				echo '<span class="hasTip" title="' . $toolTipTitle . '::' . $this->config['alternative_legs'] . '">';
            }
			else {
				echo '<span class="hasTip" title="' . $toolTipTitle . '::' . $toolTipText . '">';
			}
			echo $column_names[$k];
			echo '</span></th>';
            break;
`
und in der Datei default_explanation.php:
`            foreach ($columns as $k => $column) {
                if (empty($column_names[$k])) {
                    $column_names[$k] = '???';
                }
                $c = strtoupper(trim($column));
                $c = "COM_SPORTSMANAGEMENT_" . $c;
                echo "<td class=\"\">";
				if (strtoupper(trim($column)) == "LEGS" && !empty($config['alternative_legs'])) {
					echo $column_names[$k] . " = " . $config['alternative_legs']; 
				}
				else {
					echo $column_names[$k] . " = " . Text::_($c);
				}
                
                echo "</td>";
                //$d=(1-$d);
            }
`

Das Ergebnis sieht man auf dieser Seite:
http://www.noefbv.at/index.php/ligaverwaltung-2/aktuelle-saison/resultsranking/0/0/136:feld-1-landesliga-maenner/0/0.html?type=0&from=0&to=0

**Comment by sigal** [comment]
Eine schlechte Idee.
Für solche Sachen stellt Joomla alles zur Verfügung.
Warum nicht ein Override des Sprachschlüssel angelegt?

![Override-01](https://user-images.githubusercontent.com/5115688/77354925-e75ba200-6d43-11ea-82c2-6ff500bde54d.jpg)

Ist auch für:
`COM_SPORTSMANAGEMENT_SCOREFOR="Erzielte Tore"
COM_SPORTSMANAGEMENT_SCOREAGAINST="Erhaltene Tore"`

usw. zu empfehlen

**Comment by ortwin20000** [comment]
Guter Einwand. Diesen Punkt kannte ich so noch nicht.
Dann ist der Punkt alternative Bezeichnung für Sätze in dem Template eigentlich unnötig und könnte entfernt werden.
Nur wenn jemand mehr als eine Sportart im Einsatz hat wäre dieser Punkt vielleicht trotzdem wichtig.
