### ISSUE TITLE
mod_sportsmanagement_google_calendar API-Key

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1022]
In diesem Modul gibt es ein Feld zur Auswahl des API-Keys.
Hier ist die Liste leer und es kann kein Wert ausgewählt oder eingetragen werden.

**Comment by sigal** [comment]
Kann ich nicht nachvollziehen. 
Auswahl erst nach Anlage eines GKalender im BE möglich!

![gcalendar_01](https://user-images.githubusercontent.com/5115688/77579017-d93f8a00-6ed9-11ea-8185-352f12b21331.jpg)

**Comment by ortwin20000** [comment]
Ich habe einige Kalender im Backend importiert. Fehlt hier vielleicht der Google Developer Key noch?

**Comment by sigal** [comment]
Diesen braucht man nicht!

**Comment by ortwin20000** [comment]
Es geht nicht um das Modul gcalender sondern um google_calendar
![grafik](https://user-images.githubusercontent.com/15192502/77621090-0c1a6a00-6f3c-11ea-8b22-9af809146368.png)

Dort kann ich keinen API-Key auswählen.
![grafik](https://user-images.githubusercontent.com/15192502/77621158-32d8a080-6f3c-11ea-85e2-bbaa7c1a48c3.png)

Es wird mir auch im Frontend nichts angezeigt.

**Comment by sigal** [comment]
Dieses Modul wird doch im derzeitigen Release nicht installiert.
Mal in der sportsmanagement.xml nachlesen.
ab Zeile 170

**Comment by ortwin20000** [comment]
Mir ist dieses Modul in der Ordnerstruktur aufgefallen und Joomla hat es dann beim Überprüfen in den Erweiterungen gefunden und so habe ich es installiert und ausprobiert.

**Comment by sigal** [comment]
Nicht bei einer Neuinstallation und jetzt bin ich raus

**Comment by ortwin20000** [comment]
Kann ich verstehen.
Ist das Modul noch nicht offiziell oder ist geplant dieses zu entfernen? Grundsätzlich sollten ja die beiden anderen Kalender-Module ausreichend sein.
Macht es hier noch Sinn wenn ich hier weiter nach Fehlern suche?
