### ISSUE TITLE
Kalender Import

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1028]
Ich kann keine Kalender mehr importieren.  Hat eigentlich immer geklappt. Aber jetzt kommt folgende Fehlermeldung. 

Error: redirect_uri_mismatch
The redirect URI in the request, union-steinerkirchen.at/administrator/in...alendarimport.import , does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: console.developers.google.com/apis/crede...project=930483257682

Learn more
Request Detailsresponse_type=codeaccess_type=offlineclient_id=930483257682-bp4lth1h9fb9pklpdd166ckupthqjrpd.apps.googleusercontent.comredirect_uri=https://union-steinerkirchen.at/administrator/index.php?option=com_sportsmanagement&task=jsmgcalendarimport.importstate=scope=https://www.googleapis.com/auth/calendarapproval_prompt=force

**Comment by sigal** [comment]
Der Teufel liegt im Detail.

Die Homepage läuft auf:
`https://www.union-steinerkirchen.at/` beachte das **www** `www.union-steinerkirchen.at`

Die Redirct URI lautet aber auf:

`https://union-steinerkirchen.at/` beachte kein www in der URI und das macht den Unterschied.
Das **WWW** wird als **Subdomain** interpretiert und daher die Fehlermeldung von der Google API.

Einfach die URI **mit WWW** zusätzlich hinzufügen:

`https://www.union-steinerkirchen.at/administrator/index.php?option=com_sportsmanagement&task=jsmgcalendarimport`

![#1028](https://user-images.githubusercontent.com/5115688/77758639-9e516980-7033-11ea-94f2-6beeaa35a555.jpg)

**Comment by Karntner** [comment]
Ja danke. 

Jetzt bin ich ein Stück weiter.
Jetzt bekomme ich beim Import folgende Fehlermeldung. 

Es ist ein Fehler aufgetreten!
0 Invalid token format
 Zurück zum Kontrollzentrum

Irgendwas muss ich da noch ändern.

**Comment by sigal** [comment]
https://stackoverflow.com/questions/54297489/google-api-php-authentication-invalid-token-format-the-question-and-the-answer

**Comment by Karntner** [comment]
Irgendwie weis ich trotzdem nicht was ich machen soll

**Comment by Karntner** [comment]
Alles klappt jetzt

**Comment by Karntner** [comment]
Leider habe ich wieder das Problem das der Kalender Import nicht funktioniert. 
Hat Google da was geändert?
