### ISSUE TITLE
Kalender export

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1030]
Hallo

Ich kann genau einen Kalender nicht exportieren. Da kommt diese Fehlermeldung. 
404 { "error": { "errors": [ { "domain": "global", "reason": "notFound", "message": "Not Found" } ], "code": 404, "message": "Not Found" } }

Alle anderen Spiele in anderen Projekten klappen einwandfrei. 

Komischerweise ist das eine Projekt das ich von euch bereit gestellt bekommen habe.

**Comment by sigal** [comment]
Welches Projekt? Hab meine Glaskugel dem Gesundheitsminister geborgt.

**Comment by Karntner** [comment]
Hallo hilft dir das weiter.

Ich hab das Projekt exportiert.












mit freundlichen Grüßen

Franz Karntner
Waschenberger Strasse 4c
4651 Stadl Paura
0676 97 36 036
franz.karntner@gmail.com




------ Originalnachricht ------
Von: "stony" <notifications@github.com>
An: "diddipoeler/sportsmanagement" <sportsmanagement@noreply.github.com>
Cc: "Karntner" <franz.karntner@gmail.com>; "Author" 
<author@noreply.github.com>
Gesendet: 27.03.2020 20:50:52
Betreff: Re: [diddipoeler/sportsmanagement] Kalender export (#1030)

**Comment by Karntner** [comment]
Leider kann ich das exportierte Projekt hier nicht einfügen

**Comment by sigal** [comment]
E-Mail? und von wem ist das Projekt?

**Comment by Karntner** [comment]
Ich habe dir eine Mail gesendet. Das ist von Didi

ich versuchs mal neu zu importieren. vl hat sich wo ein Fehler eingeschlichen.

**Comment by Karntner** [comment]
Ich habe das original Projekt von euch jetzt noch mal importiert.

Jetzt passt es. Da dürfte sich irgendwo ein Fehler eingeschlichen haben.
