### ISSUE TITLE
Wunsch - Mannschaften als Schiedsrichter

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1034]
Im Faustball werden in den Landesligen und Jugendligen keine eigenen Schiedsrichter gestellt.
Das bedeutet das pro Runde mindestens drei Mannschaften am Platz sind. Die Mannschaft die nicht spielt hat Schiedsgericht.

Derzeit löse ich es so, dass ich für jede Mannschaft eine Person anlege, welche ich dann als Schiedsrichter gebrauche. Gibt es eine Möglichkeit gleich eine der Mannschaften die dem Projekt zugeordnet sind als Schiedsrichter auszuwählen?

**Comment by ortwin20000** [comment]
Ich finde nirgendwo einen Punkt wo ich Schiedsrichter einem Spiel zuordnen kann. Früher ging das noch in Joomleague.
Wie ist das jetzt in JSM gelöst?

**Comment by ortwin20000** [comment]
Ich hätte mich jetzt mal daran versucht und folgendes Ergebnis erzielt:
![grafik](https://user-images.githubusercontent.com/15192502/77885066-93324f80-7266-11ea-969d-d4dffd17ec6a.png)
Ich habe bei mir den Code so abgeändert, dass ich zwar noch die Schiedsrichter-Position im Projekt anlegen muss, aber keine Schiedsrichter als Personen definieren muss. Zusätzlich habe ich die Liste der ausgewählten Schiedsrichter so geändert, dass bereits hinzugefügte Mannschaften nicht mehr in der Liste der auszuwählenden Mannschaften aufscheint. Der Code sollte noch kontrolliert werden.
In der Datenbank gibt es noch das Feld "teams_as_referees" von früher und in ein paar Views im Frontend ist auch noch Code vorhanden. Deswegen habe ich im Projekt ein neues Feld "teams_as_referees" definiert und in der Sprachdatei den Text ergänzt. Damit kann dies dann im Projekt definiert werden.
In der View "results" sieht das dann so aus:
![grafik](https://user-images.githubusercontent.com/15192502/77885393-41d69000-7267-11ea-9174-56f5f5635869.png)
Soll ich die Änderungen bei mir einfach einchecken und dann einen Pull-Request erstellen oder wie soll ich da weiter vorgehen?

**Comment by ortwin20000** [comment]
Ich habe bei mir mal einen Branch erstellt und die Änderungen dort eingecheckt.

**Comment by diddipoeler** [comment]
Das können wir ruhig übernehmen, wenn auch die normale Zuordnung der
Schiedsrichter erhalten bleibt.
