### ISSUE TITLE
ICal mit aktiviertem Joomla SEO

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1039]
Wenn ich im Spielplan die Funktion ICal aktiviere erhalte ich im Frontend das Icon für den Kalender-Export.

Aktiviere ich in Joomla SEO funktioniert der Link für den Export nicht und ich werde auf die Projektseite geleitet:
![grafik](https://user-images.githubusercontent.com/15192502/77900638-a224fc00-727e-11ea-8868-1eb936ace6a5.png)

Wenn ich SEO deaktiviere funktioniert der Export ohne Probleme.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by ortwin20000** [comment]
Funktioniert. Danke für die schnelle Behebung. :-)
