### ISSUE TITLE
Modal von Bildern wird nicht korrekt angezeigt

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1040]
Auf meiner Seite http://www.noefbv.at/ligaverwaltung-2/aktuelle-saison/allprojects.html
werden die Projekte der aktuellen Saison angezeigt. Den Projekten habe ich auch Bilder hinzugefügt.
Nun ist mir aufgefallen, dass ein Klick auf das Bild ein Modal öffnen sollte. Der Bildschirm verdunkelt sich aber das Modal ist nicht sichtbar.

In der Datei /helpers/html.php wird der dafür verantwortliche Code erzeugt.
Die Variable $use_jquery_modal ist standardmässig auf 0 gesetzt, wenn kein Wert der Funktion übergeben wurde.
Der Code 
`$modaltext .= HTMLHelper::_('bootstrap.renderModal', $target, array(
                    'title' => $text,
                    'url' => $url,
                    'height' => $height,
                    'width' => $width,
                    'footer' => '<button type="button" class="btn btn-default" data-dismiss="modal">'.Text::_('JCANCEL').'</button>'
                        )
        );`
generiert bei mir dann ein verstecktes <div>
<div id="allproject145" tabindex="-1" class="modal hide fade">

Wenn ich nun auf das Bild klicke wird daraus
<div id="allproject145" tabindex="-1" class="modal hide fade in" style="display: block; padding-right: 17px;">

Um das Bild dann wirklich anzuzeigen, muss ich in der class den Wert "hide" entfernen.
Zwei Fragen:
Ist das ein Fehler von JSM oder Joomla mit meinem Template (wo auch bootstrap eingesetzt wird)?
Wo kann ich die Variable $use_jquery_modal konfigurieren?

**Comment by diddipoeler** [comment]
Bitte die Menüeinträge aufrufen und sichern.
Danach noch einmal testen.

**Comment by sigal** [comment]
Von mir 💯 OK!

**Comment by ortwin20000** [comment]
Danke für das Hinzufügen der Variable. Mit JCE Modal und Window open funktioniert es jetzt. Bei Bootstrap ist das Verhalten gleich wie zuvor.
class="modal hide fade"
und nach dem Klick darauf
class="modal hide fade in"

Sobald ich das "hide" entferne wird es mir dargestellt.

**Comment by ortwin20000** [comment]
Bei meinem neuen Template Astroid funktioniert es auch nicht mit Bootstrap. Ich vermute dass es ein Problem mit den Templates und den unterschiedlichen Bootstrap Versionen ist.

**Comment by sigal** [comment]
Mit Bootstrap4 sind einige Anpassungen im Code von Nöten.

Ist so: "einen jeden Recht getan, ist eine Kunst die niemand kann."

https://www.joomla.de/wissen/joomla-event-videos/joomla-day-deutschland/442-jd17de-bootstrap-4-mit-joomla-programmierung-trifft-auf-design
