### ISSUE TITLE
ICal wird von Google nicht erkannt

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1042]
Die Ical-Datei von JSM kann zwar von Outlook importiert werden aber von Google nicht.
Die Ursache sind die 4 Leerzeichen ganz am Anfang der Datei:
    BEGIN:VCALENDAR
diese dürfen dort nicht stehen also es muss heißen:
BEGIN:VCALENDAR

Dann lässt sich die Datei auch in Google importieren.

**Comment by Karntner** [comment]
Super!

Eine kleine Anmerkung habe ich da noch. Ist es Absicht das der Spielort bei der Beschreibung importiert wird und nicht beim Ort?

**Comment by ortwin20000** [comment]
Bei mir wird der Wert korrekt im Segment eingetragen:
LOCATION:Doktor-Josef-Jecel-Straße\, 3071 Böheimkirchen
Wie hast du deine Spielorte angelegt?

**Comment by Karntner** [comment]
Das muss ich mir genauer ansehen. Ev ist da was falsch. Danke für den Tipp






mit freundlichen Grüßen

Franz Karntner
Waschenberger Strasse 4c
4651 Stadl Paura
0676 97 36 036
franz.karntner@gmail.com

________________________________

**Comment by Karntner** [comment]
Ja da hab ich einen Fehler gemacht. 
Jetzt passt es
