### ISSUE TITLE
Modul Matches

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1047]
Bei mir wird bei diesem Modul jetzt zwar angezeigt das Spiele abgesagt oder verschoben sind. 
Dafür wird die Gastmannschaft nicht mehr angezeigt. 
https://www.union-steinerkirchen.at

**Comment by Karntner** [comment]
Hab grad was probiert. 
Es funktioniert nur beim Template result_right-tableless nicht. Bei den anderen funktioniert es.

**Comment by sigal** [comment]
Bitte einmal testen!

**Comment by Karntner** [comment]
Danke Sigal

Schaut super aus!
