### ISSUE TITLE
Wunsch - Kalender Export abgesagte Spiele

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1048]
Kann man das irgendwie einstellen das beim Kalender Export das Spiel als abgesagt, verschoben usw. angezeigt wird?

**Comment by ortwin20000** [comment]
Wo soll das im Kalender dann angezeigt werden?

**Comment by ortwin20000** [comment]
Damit sollte es nun funktionieren. Ich habe auch die "(" und ")" entfernt, wenn kein Ergebnis eingetragen ist und es keine Absage gibt.

**Comment by ortwin20000** [comment]
@Karntner Bitte Testen ob es auch bei dir so passt.

**Comment by Karntner** [comment]
Sehr gut. Schaut super aus.

Danke
