### ISSUE TITLE
Wunsch

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1049]
Wäre es möglich das die Spiele auch im Vereinsspielplan und im Kalender als abgesagt angezeigt werden?

https://www.union-steinerkirchen.at/index.php/spielplan-verein/kal/clubplan

![image](https://user-images.githubusercontent.com/59525415/78422793-54373c00-7662-11ea-9c9a-0761e2b8ae2e.png)

**Comment by ortwin20000** [comment]
Da der Text im Kalender meist begrenzt ist, wie soll hier die Absage dargestellt werden?
Im Vereinsspielplan würde ich einfach "Abgesagt" (oder was auch immer als Grund genannt wurde) anstatt des Ergebnisses ausgeben.

**Comment by Karntner** [comment]
Der Exportierte Kalender gibt ja auch das Ergebniss aus.
Da könnte das dann anstelle des Ergebnisses stehen.

Beim Verinskalender wäre das die beste Lösung.






mit freundlichen Grüßen

Franz Karntner
Waschenberger Strasse 4c
4651 Stadl Paura
0676 97 36 036
franz.karntner@gmail.com

________________________________

**Comment by ortwin20000** [comment]
Änderung wurde eingepflegt. Bitte testen.

**Comment by Karntner** [comment]
Peferkt.

Danke

**Comment by ortwin20000** [comment]
Ich habe mit diesem Code ein komisches Verhalten:
Ein Spiel von drei ist abgesagt aber die Query liefert mir für m.cancel immer den Wert 1 zurück.
Im Vereinsspielplan funktioniert es aber im Kalender-Modul nicht. Das gleiche Problem habe ich jetzt auch bei #1048 
Wo liegt hier der Fehler?
