### ISSUE TITLE
Joomla Coding Standard

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1053]
Aufgrund des berechtigten Einwands von Stony habe ich mich mal ein wenig umgesehen, wie der Coding-Standard in Joomla aussieht und es gibt da auch ein Ruleset was mit Hilfe von PHP CodeSniffer überprüft werden kann.

Ich habe das bei mir mal eingerichtet und es werden mir sehr sehr viele Styling-Probleme ausgegeben.
![grafik](https://user-images.githubusercontent.com/15192502/78498926-e36d4e00-774d-11ea-88f0-dd2067b69b17.png)

Ist es in Ordnung wenn ich die Einwände durchgehe und korrigiere soweit ich kann oder wäre eine andere Arbeitsweise gewünscht?

**Comment by diddipoeler** [comment]
Aus meiner Sicht wäre das in Ordnung und außerdem sind wir für jede Hilfe dankbar.
Vielleicht könntest du, @ortwin20000,  noch ein bißchen Werbung für die JSM Komponente machen.

**Comment by ortwin20000** [comment]
Wenn ich mit meinen Anpassungen fertig bin, werde ich die dem NÖ und Wiener Faustballverband präsentieren. Wichtig wäre mir derzeit noch der externe Datenbankzugriff, damit ich mit der zweiten Verbandsseite fertig werden kann. Aktiver Spielbetrieb wird aufgrund Corona eh noch ein wenig dauern.

**Comment by diddipoeler** [comment]
Wem die Komponente gefällt kann auch gerne etwas spenden :-)

**Comment by diddipoeler** [comment]
Werde dich noch in das Entwicklerteam aufnehmen :-)

**Comment by sigal** [comment]
Die Überprüfung mit dem Codesniffer ist schon mal der erste Weg. 👍 
https://developer.joomla.org/coding-standards/html.html

Zur Überprüfing der gesamten Komponente soll mit diesem Tool (Komponete - JEDchecker) geprüft werden.
Die Komponente am Besten auf einer Testumgebung installieren.
Der Link: https://compojoom.com/downloads/official-releases-stable/jedchecker

Happy coding 🥇

**Comment by ortwin20000** [comment]
Ich habe bei mir einen neuen Branch erstellt "Code-Formatting".
Darin habe ich alle Dateien auf UTF-8 konvertiert und mit Hilfe von PHPCS die Dateien überprüft und soweit es mir möglich war bereinigt. Leider bekomme ich die Leerzeichen noch nicht umgewandelt in Tabs. Werde versuchen diese auch noch umzuwandeln. Die Komponenten JEDchecker werde ich später auch noch einmal drüberlaufen lassen. Sollten keine Fehler auftreten werde ich dann einen PullRequest erstellen.

**Comment by ortwin20000** [comment]
Ich habe jetzt den letzten Teil mit Tabs und die Anordnung in den DocBlocks angepasst und in meinem Branch hochgeladen.
Zur Sicherheit habe noch den JED Checker drüberlaufen lassen und dort erhalte ich diese Meldungen:
![grafik](https://user-images.githubusercontent.com/15192502/78673580-9ff81880-78e2-11ea-846c-fda142013c29.png)
Das betrifft base64-Aufrufe bei Bildern usw. Muss das noch korrigiert werden?

Zusätzlich erhalte ich noch diese Meldung:
![grafik](https://user-images.githubusercontent.com/15192502/78673668-c1590480-78e2-11ea-9ca9-746e2955ac39.png)
Das betrifft meine Erweiterung Scoresheet. In einigen Dateien steht "Licensed under the Apache License". In den anderen steht nichts drin. Wie muss das erweitert werden?

Warnungen erhalte ich auch:
![grafik](https://user-images.githubusercontent.com/15192502/78673865-0b41ea80-78e3-11ea-8f65-546d9f89057f.png)
und viele Warnung zu den GIF-Bildern:
![grafik](https://user-images.githubusercontent.com/15192502/78673968-2dd40380-78e3-11ea-8c53-b6e92984db31.png)
Was ist hier zu tun?

**Comment by diddipoeler** [comment]
Gif Bilder ignorieren.
Das bitte auch ignorieren: $text = intval($_GET['text']);
base64-Aufrufe ignorieren.

**Comment by ortwin20000** [comment]
Ok. Muss ich dann einen DocBlock bei meinen zusätzlich verwendeten Dateien von fpdf einbauen und ist die Apache License in Ordnung?

**Comment by diddipoeler** [comment]
Ich würde es so lassen.
