### ISSUE TITLE
Schema.org hinzufügen 

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1063]
Ich würde bei meiner Seite die Beschreibungen der Felder anhand von schema.org hinzufügen für einzelne Bereiche wie Spieler, Verein und Spielort usw.

Diese Informationen werden von den Suchmaschinen gerne zum besseren Verständnis der indexierten Seiten verwendet was dann auch dem SEO der Seite zugutekommen sollte.

Wäre es auch für das Projekt von Interesse? Ich würde es dann hier per PullRequest zur Verfügung stellen.

**Comment by sigal** [comment]
Müssen da alle Sprachdateien neu aufgebaut werden?

**Comment by ortwin20000** [comment]
Das hat mit den Sprachdateien nichts zu tun soweit ich es verstanden habe. In den HTML-Tags werden nur zusätzliche Attribute wie itemscope und itemprop hinzugefügt.
Siehe auch https://schema.org/docs/gs.html

Grundsätzlich sind diese Attribute in Englisch gehalten.

**Comment by diddipoeler** [comment]
Gibt es hierzu etwas neues ?

**Comment by ortwin20000** [comment]
Leider noch nicht. Bin derzeit mit anderen Projekten voll. Hab es aber noch vor umzusetzen.

**Comment by diddipoeler** [comment]
https://search.google.com/structured-data/testing-tool?hl=de

**Comment by diddipoeler** [comment]
https://schema.org/SportsClub

**Comment by diddipoeler** [comment]
Mache gerade mal mit dem Template clubinfo Experimente.
Ich glaube, dass ich das ganze jetzt langsam verstehe.

**Comment by diddipoeler** [comment]
https://www.w3.org/wiki/images/8/87/Schema-sports-vocabulary-final_20120301.pdf

**Comment by diddipoeler** [comment]
Das ist aber ein ganz schönes gebastel.

**Comment by diddipoeler** [comment]
https://search.google.com/test/rich-results?utm_campaign=sdtt&utm_medium=message

**Comment by ortwin20000** [comment]
Ich habe mir die Sache nach längerer Abwesenheit (neuer Job) angesehen und finde die von dir durchgeführten Arbeiten super :-)

Ich denke das kann man so erst mal lassen. Danke
