### ISSUE TITLE
View ClubInfo: Datum und Verbandsinfo

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1065]
In den Vereinsinformationen wird mir das Datum mit 1-1-1922 angezeigt und bei dem Logo für den Verband wird mir der Text des Bildes und der normale Text überlappend angezeigt.
![grafik](https://user-images.githubusercontent.com/15192502/79368868-606ba500-7f50-11ea-9d75-05958d9e59b8.png)

Ich finde es sollte das Datum mit 1.1.1922 dargestellt werden und beim Logo kann der Text des Bildes auch weg.
![grafik](https://user-images.githubusercontent.com/15192502/79369034-9f99f600-7f50-11ea-8cc7-17a477a66549.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
