### ISSUE TITLE
Sprache

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1071]
Hallo

Die Sprache im Backend ist plötzlich auf Englisch. Wo kann ich das umstellen?

**Comment by sigal** [comment]
So lange die Administrator-Backend Sprrache von Joomla Deutsch als Standard eingestellt ist, wird auch die Backend-Sprache von JSM auf Deutsch bereitgestellt.
Wird das gesamte Backend von Joomla inklusiver der installierten Komponenten auf Englisch angezeigt?

**Comment by Karntner** [comment]
Nein nur die JSM Komponente. Alles andere passt

**Comment by sigal** [comment]
Kann das nicht nachvollziehen, da im GitHub die deutschen BE Sprachdateien auf DEUTSCH sind.

Bitte mal ein JSM GitHub Update machen.

**Comment by Karntner** [comment]
Es ist alles richtig eingestellt. 
Kann eine Neuinstallation der Komponente helfen?
Sind dann alle Projekte weg?

**Comment by Karntner** [comment]
Ich habe den Fehler gefunden. Es lag an der Spracheinstellung beim Anmelden ins Backend.
