### ISSUE TITLE
Erweiterung Bilder Upload Drag&Drop Projekt und Spiele

### ISSUE THREAD

**Issue by diddipoeler** [diddipoeler/sportsmanagement#1072]

**Comment by sigal** [comment]
Hab das mal getestet. Wenn in den Ordnern kein Unterordner angelegt wurde, passt alles perfekt. Ich habe in einigen Ordner Unterordner zur leichteren Arbeit zum Einfügen von Logos, Bilder etc angelegt.
Mit dem Joomla Media-Tool funktioniert das. Das Sports Management Tool gibt bei der Auswahl eines Bildes folgenden Fehler: 
Es ist ein Fehler aufgetreten!
 0 Call to undefined method sportsmanagementModelimagelist::dirIisEmpty()

![#1072_01](https://user-images.githubusercontent.com/5115688/84437666-a8980280-ac35-11ea-969d-7ced827fc724.jpg)

**Comment by diddipoeler** [comment]
Bitte einmal mit Vorsicht testen.
