### ISSUE TITLE
Backend-View: joomleagueimports Layout: default

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#1076]
Joomla 3.9.19, PHP 7.3
Fresh install, Joomla + JSM
DB-Präfix der zu importierenden JL- Tabellen wird aus den Optionen nur für erste zu verarbeiteten Tabelle übernommen.
Bei der zweiten ein Abbruch
Bei gleichen Präfix läuft der Import durch :+1:
-----------------------------------------------------------------------
Joomla 4.0 Beta 1, PHP 7.3
Fresh install, Joomla + JSM

DB-Präfix der zu importierenden JL- Tabellen wird aus den Optionen nicht übernommen.

Bei gleichen Präfix stoppt das script beim 1. Schritt. Man muß sich händisch (Kick Button "Import starten) weiterhangeln - ich hab abgebrochen

**Comment by diddipoeler** [comment]
Bitte einmal mit Vorsicht testen :-)

**Comment by diddipoeler** [comment]
Bitte einmal mit Vorsicht testen :-)

**Comment by sigal** [comment]
Hallo hab mit Joomla 4 und Joomla 3 gestestet - mit keiner Version ein positives Ergebnis.

Auf Joomla 3: Bei Anfang

![DB-Error](https://user-images.githubusercontent.com/5115688/86252402-77b34980-bbb3-11ea-936b-5f9b317c6388.jpg)


Die Tabelle sportsmanagement_jl_tables wird angelegt; Einträge bis _joomleague_prediction_result, aber ohne Werte

**Comment by diddipoeler** [comment]
Ignoriere mal bitte die Hinweise und starte den Import.

**Comment by sigal** [comment]
Hab ich doch. :+1: 
Den Link für das Video mußt du als E-Mail auf deinem Gmail-Konto erhalten haben
