### ISSUE TITLE
Dynamischer Filter

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1079]
Beim Anlegen der Spiele mit Spielort wäre es hilfreich wenn man da einen Filter hat zum Spielort suchen.

**Comment by diddipoeler** [comment]
Bitte einmal testen !

**Comment by Karntner** [comment]
Bei mir werden nur die ersten 3 Anfangsbuchstaben erkannt beim filtern. 
Muss ich da noch wo ein Update machen?

**Comment by diddipoeler** [comment]
Ein Update der Komponente machen.
Ansonsten mir mal die Adminzugangsdaten zusenden.

**Comment by diddipoeler** [comment]
Bitte einmal testen !

**Comment by Karntner** [comment]
Danke. Funktionier

**Comment by Karntner** [comment]
Beim Anlegen der Spielstätte der Mannschaft wäre das auch noch super

**Comment by diddipoeler** [comment]
Bitte einmal testen !

**Comment by Karntner** [comment]
Super Danke!!!

**Comment by Karntner** [comment]
Hallo

Könnte man bei der Startaufstellung auch noch einen Filter einbauen. Bei unserem 30 Mann Kader ist das ein wenig mühsam. :-)

![image](https://user-images.githubusercontent.com/59525415/87849413-baca2800-c8e8-11ea-9308-62433b558f79.png)

**Comment by diddipoeler** [comment]
Welchen Filter denn ?

**Comment by Karntner** [comment]
Ich meinte hier wenn man die Startaufstellung eingibt!


Das Problem ist das wir einen 30 Mann Kader haben und da wird das dann Mühsam. 
Es würde auch schon helfen wenn ich die Namen Alphabetisch sortiert hätte. 

![image](https://user-images.githubusercontent.com/59525415/88295371-9f528900-ccfd-11ea-82b5-08271338e570.png)

**Comment by diddipoeler** [comment]
Die sind doch sortiert !

**Comment by Karntner** [comment]
Sorry stimmt. Ich muss mich erst daran gewöhnen das es so viele sind.
