### ISSUE TITLE
Vereinswappen

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1090]
Ich kann keine Vereinswappen mehr übernehmen. 
Es funktioniert nur mehr wenn ich sie hochlade.

**Comment by diddipoeler** [comment]
Bitte einmal mit Vorsicht testen.

**Comment by Karntner** [comment]
Funktioniert leider nicht

**Comment by diddipoeler** [comment]
Zur Übernahme bitte auf den grünen Button neben dem Bild klicken !

**Comment by Karntner** [comment]
Ich habe keinen grünen Button. 
Du hast bei mir Admin Zugang. Vl. Kannst du dir selber kurz ein Bild machen

**Comment by diddipoeler** [comment]
Doch der ist da.
![Unbenannt](https://user-images.githubusercontent.com/1028107/87145226-46b8d000-c2a9-11ea-8ae2-89ee2b8f0b58.png)

**Comment by Karntner** [comment]
Ja sorry. Ich hab was anderes gemeint. Geht super

**Comment by Karntner** [comment]
Ich würde gerne noch einen Wunsch äussern bezüglich der Vereinswappen. Kann man beim Einfügen ein Suchfeld einbauen?

**Comment by diddipoeler** [comment]
Ist schon vorhanden. Bitte ein Update der Komponente machen.

**Comment by diddipoeler** [comment]
Wenn du mit der Komponente so zu frieden bist, dann mach mal richtig Reklame dafür.

**Comment by Karntner** [comment]
Würde ich gerne machen. Ich denke die beste Werbung wäre wenn ich die Tabellen und Spiele der Topligen bei uns einbauen würde. 
Geht das irgendwie?

**Comment by diddipoeler** [comment]
Welche Topligen ?

**Comment by Karntner** [comment]
Deutschland
England
Italien
Spanien
Natürlich Österreich 1.+2. Liga
In Österreich ist mir aufgefallen das ich nur den Grunddurchgang finde.

**Comment by sigal** [comment]
Genau so, wie ich dir die geamten Ligen mit Logos für deinen Verein zur Verfügung gestellt habe?

**Comment by svdoldie** [comment]
Moin :-)
Ich habe zu den Vereinswappen noch eine Frage.
Wäre es nicht einfacher, wenn man nur das große Wappen dem Verein zuordnet
und die kleineren softwaremäßig verkleinert werden? 
Wenn ich mich recht erinnere, war das auch mal so angedacht.
Oder ist das programiertechnisch zu aufwendig?

**Comment by Karntner** [comment]
Das wäre natürlich der Hammer!

**Comment by diddipoeler** [comment]
Müsste man natürlich programmieren. Mir ist es sowieso ein Dorn im Auge, warum man noch zusätzliche
mittlere und kleine Wappen dem Verein zuordnen soll/muss.
Mit dem großen Wappen kann man doch alles darstellen oder nicht ?
Dann bräuchte der User auch nicht soviel einstellen großes, mittleres oder kleines Wappen für die Darstellung.

**Comment by Karntner** [comment]
Wenn mann bei den Modulen und Views die Anzeige auf ein gewisses Format einstellen kann braucht man nur 1 Logo.

**Comment by diddipoeler** [comment]
Das ist natürlich ein enormer Änderungswunsch, aber ich gehe das mal langsam an.
Ist ja alles nur Freizeit :-)

**Comment by svdoldie** [comment]
😀👍

**Comment by sigal** [comment]
Noch ein kurzes Statement.
Wenn verkleinert wird, dann die Höhe. Momentan werden bei den Einstellungen die Breite zur Verkleinerung genommen. Bei hohen Wappen hat mann dadurch verschieden hohe Zeilenhöhen, dass dem Auge auch nicht gut tut.

**Comment by diddipoeler** [comment]
Backend Vereine wurden angepasst. Bildgrößedarstellung wurde angepasst.

**Comment by Karntner** [comment]
Wahnsinn wie das schnell geht.

Wenn es Möglichkeiten zur Unterstützung gibt dann melde  dich. Werde auf jeden Fall mal ein Logo von deiner Komponente einbauen suf der Startseite. 
Hast du da ein gutes?

**Comment by diddipoeler** [comment]
![fussballineuropa](https://user-images.githubusercontent.com/1028107/87678688-871dbf80-c77b-11ea-98a5-fde320f149a5.png)

**Comment by sigal** [comment]
> 
> 
> Wahnsinn wie das schnell geht.
> 
> Wenn es Möglichkeiten zur Unterstützung gibt dann melde dich. Werde auf jeden Fall mal ein Logo von deiner Komponente einbauen suf der Startseite.
> Hast du da ein gutes?

Es würde uns freuen, wenn du einen positiven Kommentar zur Sports Management Komponente auf JED (**J**oomla **E**xtension **D**irectory) posten würdest.
Hier der Link zur Komponente: [Sports Management](https://extensions.joomla.org/extension/sports-management/)

Ich glaube du musst dich dort auch registrieren, wenn du kein Konto hast.

**_Das ganze JSM-Team_** freut sich auf jede positve Bewertung der Komponente.

Danke schon im Vorhinein!  :green_heart:

**Comment by Karntner** [comment]
Erledigt
