### ISSUE TITLE
Kaderansicht

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1091]
Ich schaffe es nicht mehr das bei der Kaderansicht die Spieler angezeigt werden.

**Comment by diddipoeler** [comment]
Gibt es dazu einen Link ?

**Comment by Karntner** [comment]
https://www.union-steinerkirchen.at/index.php/mannschaften/kampfmannschaft/kader/rosterVon meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: diddipoeler <notifications@github.com> Datum: 12.07.20  09:45  (GMT+01:00) An: diddipoeler/sportsmanagement <sportsmanagement@noreply.github.com> Cc: Karntner <franz.karntner@gmail.com>, Author <author@noreply.github.com> Betreff: Re: [diddipoeler/sportsmanagement] Kaderansicht (#1091) 
Gibt es dazu einen Link ?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/diddipoeler/sportsmanagement/issues/1091#issuecomment-657187449",
"url": "https://github.com/diddipoeler/sportsmanagement/issues/1091#issuecomment-657187449",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sigal** [comment]
Kann ich nicht nachvollziehen.
[Demoseite Roster:](https://demo.jsm-help.de/spieler-mitarbeiter-statistik/kader-roster/roster)

**Comment by Karntner** [comment]
Was muss bei den Spielern,Projekten Saisonen alles ausgewählt damit das 
angezeigt wird?

**Comment by Karntner** [comment]
Sorry ich brings einfach nicht hin

**Comment by diddipoeler** [comment]
Was hast du jetzt gemacht ?
Gestern hatte ich es korrigiert !

**Comment by Karntner** [comment]
Ich hatte gestern Probleme und ein Backup vom Vortag eingespielt!

Was war drr Fehler?

**Comment by diddipoeler** [comment]
Au man, jetzt kann ich wieder von vorne anfangen.
Schau dir als erstes mal in den Stammdaten die Positionen an. Die sind alle 3fach vorhanden.
Sag mir bescheid, wenn ich mit der Korrektur anfangen kann.

**Comment by diddipoeler** [comment]
Ich fang jetzt einfach mal an :-)

**Comment by diddipoeler** [comment]
Erledigt :-)

**Comment by Karntner** [comment]
Danke. Ich hätt erst am Abend Zeit gehabt

**Comment by Karntner** [comment]
Kader wird jetzt angezeigt. Aber ich bekomme keine Spieler in die Aufstellung einrs Spieles.

**Comment by diddipoeler** [comment]
Bei welchem Projekt und Spiel soll welcher Spieler in welche Position zugeordnet werden ?

**Comment by Karntner** [comment]
Im Prjekt Freundschaftsspiele. Aber da dürfte es das selbe Problem geben wie beim anderen. Kannst du mir sagen was dort falsch war dsnn kann ich das selber korrigieren.

**Comment by diddipoeler** [comment]
Probier jetzt mal :-)

**Comment by Karntner** [comment]
Danke funktioniert

**Comment by Karntner** [comment]
Entschuldigung das ich dich nerve aber 2 Sachen habe ich da noch.
Wie kann ich die Positionen sortieren? Und wie kann man die Spieler auf die linke Seite bekommen.

**Comment by diddipoeler** [comment]
Unter Positionen habe ich die mal sortiert.

**Comment by Karntner** [comment]
Und noch was. Ich schaff es nicht ein Ereignis zum Projekt hinzu zu fügen. Ich habe wirklich alles verlernt

**Comment by Karntner** [comment]
Habs wieder das muss man bei den Positionen eingeben!

**Comment by diddipoeler** [comment]
jetzt sieht die Ansicht besser aus oder ?

**Comment by Karntner** [comment]
Mah super! Danke

**Comment by Karntner** [comment]
Ein kleines Problem habe ich noch. 
Die Mitarbeiter ( Trainer usw.) bekomm ich auch nicht rein.
