### ISSUE TITLE
Spielbericht

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1095]
Kann man die Anzeig des Spielberichtes abändern. Aktuell finde ich das sehr unübersichtlich. 
![image](https://user-images.githubusercontent.com/59525415/87585243-10cb7f80-c6df-11ea-9e92-66147e7627f8.png)

So würde es besser aussehen:
![image](https://user-images.githubusercontent.com/59525415/87585280-204ac880-c6df-11ea-8100-a0580ba5d5a8.png)

Das Profil auf dem Trainer Tab würde ich auch links machen so wie bei den Spielern. 
Bei den Spielern gebe es die Möglichkeit das man die in mehr Spalten anzeigt. Das funktioniert aber nicht.

**Comment by diddipoeler** [comment]
Ein Link wäre sehr hilfreich !

**Comment by Karntner** [comment]
Sorry den hat mir nicht reinkopiert.

https://www.union-steinerkirchen.at/index.php/component/sportsmanagement/matchreport/0/0/77:freundschaftsspiele/12677:steinerkirchen_spg-lambach-edt

**Comment by diddipoeler** [comment]
Sieht es jetzt besser aus ?

**Comment by Karntner** [comment]
Nicht ganz. Der Abstand ist sehr gross.

**Comment by Karntner** [comment]
![15948917216194417096902499317971](https://user-images.githubusercontent.com/59525415/87654679-925ef400-c757-11ea-919b-d85cb159cb73.jpg)
Der Abdtsnd ist sehr grosd

**Comment by diddipoeler** [comment]
Das kannst du im overall Template einstellen :-)
![overall](https://user-images.githubusercontent.com/1028107/87655768-f46c2900-c758-11ea-9a60-8775c5427491.PNG)

**Comment by Karntner** [comment]
Ok. Danke
