### ISSUE TITLE
Tippspiel

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1098]
Kann man den Text bei den Tippspiel Regeln Anpassen?
Möchte den Teil mit den Sonderpunkten rausnehmen das der Meistertipp bei mir nicht funktioniert.

**Comment by sigal** [comment]
Der Text kann mittels Sprachen:Overrides überschrieben werden.

Die Texte für das Tippspiel Frontend findet man in der Datei /language/de-DE/de-DE.com_sportsmanagement.ini von Zeile 1333-1596


Jeder Schlüssel kann per Override nachhaltig überschrieben werden.

z.B.
**COM_SPORTSMANAGEMENT_XML_PREDICTIONGAME_VIEW_TITLE**="Tippspiel"

Änderungen im Sprachfile werden beim nächsten Update wieder uberschrieben!

Die Overrides findet man unter Erweiterungen->Sprachen->Overrides (Joomla)

**Comment by Karntner** [comment]
Danke

Da hätt ich eigentlich selber auf drauf kommen können.

**Comment by sigal** [comment]
Bitte schließen  :pray:
