### ISSUE TITLE
Bildanzeige

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1101]
Ich vermute da ist ein Fehler drinnen. 
Im Backend kann man da die Bildbreite einstellen. Tatsächlich wird aber dann die Höhe angepasst. 
Beim Mannschaftsfoto ist es das gleiche. 

![image](https://user-images.githubusercontent.com/59525415/87817777-db9f6880-c869-11ea-918b-ea31c4fb3642.png)
![image](https://user-images.githubusercontent.com/59525415/87817810-e659fd80-c869-11ea-8360-c21252f05e90.png)

https://www.union-steinerkirchen.at/index.php/mannschaften/kampfmannschaft/kader/roster

**Comment by diddipoeler** [comment]
Das ist die Änderung die ich einbaue und stony vorgeschlagen hatte.
Ich muss da ja natürlich auch noch viel änden.
Z.B. Programmcode und natürlich die Texte in den Templates, damit die User nicht verwirrt werden. Da wird dann zukünftig Höhe stehen.

**Comment by Karntner** [comment]
Dachte ich mir schon.

Meine Bilder haben dadurch ein wenig komisch ausgesehen
:-D

**Comment by Karntner** [comment]
Eine kleine optische Korrektur würde ich gerne noch vornehmen. Ich weis aber nicht an was das liegt. 
Die Bilder sind versetzt und ich hätte diese gerne schön untereinander. 

![image](https://user-images.githubusercontent.com/59525415/87846137-d3791480-c8cd-11ea-9557-8953c72ec9c8.png)
