### ISSUE TITLE
Kaderansicht Symbole

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1102]
Könnte man die Symbole grösser anzeigen?

![image](https://user-images.githubusercontent.com/59525415/87850128-19de6b80-c8ee-11ea-9afe-65c2b08d58ea.png)

So ungefähr
![image](https://user-images.githubusercontent.com/59525415/87850183-89ecf180-c8ee-11ea-8249-6f35ea1a4fc9.png)

https://www.union-steinerkirchen.at/index.php/mannschaften/kampfmannschaft/kader/roster

**Comment by diddipoeler** [comment]
Das kann man jetzt auch im Template roster einstellen.

**Comment by Karntner** [comment]
Ich finde leider nichts zum einstellen

**Comment by Karntner** [comment]
Problem gelöst. Ich hatte ein Override vom Template Roster drinnen!
Die Höhe kann ich ändern aber die Breite nicht. Das schaut jetzt ein bischen besch. aus. 

![image](https://user-images.githubusercontent.com/59525415/87870531-41ded500-c9a9-11ea-9988-2c1cc2802101.png)

**Comment by diddipoeler** [comment]
Die Breite wird auch nicht eingegeben, sonder errechnet sich automatisch.
Bei mir sieht es top aus:
https://www.fussballineuropa.de/index.php/component/sportsmanagement/roster/0/0/89036:1-bundesliga-2019-20/9:fc-gelsenkirchen-schalke-04-e-v-i/1360828:fc-gelsenkirchen-schalke-04-e-v-i

**Comment by Karntner** [comment]
VL liegt das auch an meinen Template!

Welches verwendest du?

**Comment by Karntner** [comment]
Hast du Purity III?

**Comment by Karntner** [comment]
Ja es liegt am Template. So schaut das super aus


![image](https://user-images.githubusercontent.com/59525415/87877506-0828c100-c9df-11ea-9b51-f4209aac52be.png)

**Comment by Karntner** [comment]
Leider  muss ich das noch mal aufmachen. 
Kann mir jemand helfen wie man den Abstand zw. Name und Ereignissen kleiner macht. 
Das dürfte wirklich an meinen Einstellungen liegen. 
https://www.union-steinerkirchen.at/index.php/mannschaften/kampfmannschaft/kader/roster

**Comment by Karntner** [comment]
Ich habe den Fehler im Template gefunden. 
Jetzt schaun die Symbole so aus wie bei euch.

Jetzt habe ich noch eine Frage. Wie bekomme ich die Fairplay Symbole weg?
https://www.union-steinerkirchen.at/index.php/mannschaften/kampfmannschaft/kader/roster

**Comment by sigal** [comment]
Nicht benötigte Ereignise entfernen:

 Sports Management: Positionen / Funktionen aufrufen.
Benötigte Position/Funktion aufrufen. Dann siehe Bild:

![#1102_01](https://user-images.githubusercontent.com/5115688/88333204-1c96f180-cd30-11ea-8adc-ba9b7f500a33.jpg)

**Comment by Karntner** [comment]
Ja das hätt ich eigentlich schon gemacht. 
Vl habe ich da wo was übersehen

**Comment by sigal** [comment]
Das glaub ich nicht. Momentan wurde das nur beim Mittelfeldspieler gemacht.!!!
Es müssen **alle nicht benötigte Ereignisse von Funktioen** (Spieler) enfernt werden.
Speichern nicht vergessen!!!

**Comment by Karntner** [comment]
Irgendwas stimmt da bei mir nicht. 
Ich habe die Fairplay Ereignisse gar nicht zur Auswahl

![image](https://user-images.githubusercontent.com/59525415/88335879-4fdb7f80-cd34-11ea-87c6-9d36d5489f07.png)

**Comment by Karntner** [comment]
Ich vermute mal hier liegt der Fehler
Bei den Statistiken
![image](https://user-images.githubusercontent.com/59525415/88336014-8d400d00-cd34-11ea-8cdd-7e639252c431.png)

**Comment by sigal** [comment]
JA!!!! Gewonnen!!
Das sind die Spieler und die haben Funktionen (Angreifer, Verteidiger etc.) und Ereignisse (Gelbe Karte, Rote Karte, Tor etc.)

![#1102_02](https://user-images.githubusercontent.com/5115688/88336309-0ccddc00-cd35-11ea-94af-bdc14adbbd22.jpg)

**Comment by sigal** [comment]
Ein schlichtes "Danke stony" würde mir auch genügen.  :wink:

**Comment by Karntner** [comment]
Sorry. Ich habe das Issue über die App geschlossen. Und vergessen mich bei dir für deine Hilfe zu bedanken. 

Vielen Dank
