### ISSUE TITLE
Spielerstatistik

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1105]
Mir wird da folgender Fehler angezeigt. 

STAT sumstats/2 WRONG CONFIGURATION
pergame: METHOD NOT IMPLEMENTED IN THIS STATISTIC INSTANCE

https://www.union-steinerkirchen.at/index.php/component/sportsmanagement/player/0/0/77:freundschaftsspiele/215:steinerkirchen/1:lukas-laher

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Karntner** [comment]
Danke Fehler ist weg
