### ISSUE TITLE
Im Spielfeld werden nur Placeholder angezeigt

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1106]
Im Spielfeld des Matchreports werden momentan die Placeholder angezeigt, statt der Bilder der einzelnen Spieler.
siehe http://svdoerpum.de/senioren/1-herren/spielplan/matchreport/0/7/60:verbandsliga-nord-2019-2020/5688:sv-doerpum_tsv-rot-weiss-niebuell

**Comment by Karntner** [comment]
@svdoldie : Welches Template verwendest du? Du hast eine so schöne Anordnung und Tabs.

Hast du dir ein eigenes gebaut?

**Comment by svdoldie** [comment]
@Karntner : Das Template ist dieses hier https://www.themexpert.com/joomla-templates/fitness

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Läuft :+1:  Danke :-)
