### ISSUE TITLE
Teamplan Fehlermeldung

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#1108]
Im Backend wird erscheint beim Speichern des Teamplan Templates folgende Fehlermeldung
Edit: Erscheint bei jedem Template
![image](https://user-images.githubusercontent.com/9608697/88033660-eb57cf00-cb3f-11ea-8d92-a3115f5d0b32.png)

Im Frontend folgender.
![image](https://user-images.githubusercontent.com/9608697/88033885-34a81e80-cb40-11ea-9b66-797325580057.png)

https://www.rhein-main-player-league.de/ligen/bezirksliga-f1/ergebnisse-bf1/teamplan/0/2/10:bezirksliga-frankfurt-1-2019-2020/48:sebastian-staudt/0/1/109:sebastian-staudt

**Comment by diddipoeler** [comment]
Mach mal ein Update der Komponente.

**Comment by sigal** [comment]
Die gleiche Fehlermeldung hab ich beim Speichern im Backend.
Fur mich hab ich die Zeile 132 in helpers/sportsmanagment ausdokumentiert.
Da du momentan ausgelastest bist, wollte ich kein Issue aufmachen.
Bin am letzen Stand aus dem GitHub.

**Comment by PhantoSGE** [comment]
Habe ein Update gemacht, aber die Fehlermeldung im Backend und Frontend sind noch vorhanden

**Comment by diddipoeler** [comment]
Mach mal ein Update der Komponente und das Backend testen.

**Comment by PhantoSGE** [comment]
Wenn ich die Komponente im Backend aufrufe kommt sofort
![image](https://user-images.githubusercontent.com/9608697/88047680-485c8080-cb52-11ea-8ee7-30ef01d99395.png)

**Comment by diddipoeler** [comment]
Bitte einmal die Adminzugangsdaten zusenden. Mit allen Berechtigungen.

**Comment by PhantoSGE** [comment]
Habe sie an gmx geschickt

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Backend Fehlermeldung 
Call to a member function addLog() on boolean
erscheint immernoch

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Backend und Frontend getestet und sieht gut aus.
Danke

**Comment by PhantoSGE** [comment]
Hallo zusammen,
die Fehlermeldung im Teamplan erscheint nun wieder.
![image](https://user-images.githubusercontent.com/9608697/88385497-bdc48d00-cdae-11ea-8f0d-94592f8e5a1a.png)

**Comment by diddipoeler** [comment]
Bitte wieder einmal die Adminzugangsdaten zusenden. Mit allen Berechtigungen.

**Comment by PhantoSGE** [comment]
per gmx geschickt

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Danke. Funktioniert wieder
