### ISSUE TITLE
Some ideas for playground ticker module

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#1109]
is it possible add some filter fields in order to show only playgrounds...
in a project
or in a season
or in a league?

thanks

**Comment by llambion72** [comment]
I've almost finished some improvements to this module.
Now, 
we can filter stadiums by project
we can enable/disable display some fields such as gps coordinates, address, website and max visitors.

![playground_ticker_01](https://user-images.githubusercontent.com/20923398/88485994-b81ba280-cf7a-11ea-8d61-13a33f34017a.png)
![playground_ticker_02](https://user-images.githubusercontent.com/20923398/88485997-ba7dfc80-cf7a-11ea-8719-f591b3a68f88.png)

**Comment by diddipoeler** [comment]
Das sieht gut aus :-)

**Comment by llambion72** [comment]
I've finished
