### ISSUE TITLE
JSM - Modul Vereins Icons Vereinswappen wird nicht angezeigt

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1110]
Hallo

Erst mal kompliment. Das ist ein tolles Modul!
Mir wird nur ein Logo nicht angezeigt. wenn ich auf kleine oder Mittlere Vereinswappen stelle.
Bei den grossen gehts. Nur da sind alle unterschiedlich hoch. Das gefällt mir nicht. 

https://www.union-steinerkirchen.at/index.php

**Comment by diddipoeler** [comment]
Kleine und mittlere Vereinswappen wird es nicht mehr geben.

**Comment by diddipoeler** [comment]
Die Bildhöhe wird vom css des Templates überschrieben :-(

**Comment by Karntner** [comment]
Jetzt sind die Logos riesig!
Sieht das bei euch auch so aus das die so gross sind?

**Comment by Karntner** [comment]
ok das muss ich mir ansehen. Dürfte das selbe Problem sein wie bei der Kaderansicht.

**Comment by Karntner** [comment]
Ich habe den Fehler gefunden. Nur muss ich das jetzt so machen das es die Bilder nur bei diesem Modul ändert.

**Comment by diddipoeler** [comment]
Bei mir sieht alles top aus.
https://www.fussballineuropa.de/index.php

**Comment by Karntner** [comment]
ja ich muss mein Template anpassen

**Comment by Karntner** [comment]
So Fehler gefunden und behoben. Jetzt übernimmt es die Einstellungen von JSM

**Comment by diddipoeler** [comment]
Wir nähern uns langsam zu einer perfekten Komponente :-)

**Comment by Karntner** [comment]
Ja sehr gut.
