### ISSUE TITLE
Matchreport - Wunsch

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1111]
Ich würde es schön finden, wenn im Abschnitt Spieler die Bezeichnungen der Mannschaften als Sprchvariable angezeigt wird.
Momentan steht da Guest Team und Home Team. Die gleiche Ansicht würde ich mir beim Staff auch wünschen

**Comment by diddipoeler** [comment]
Wo genau ?

**Comment by svdoldie** [comment]
Bei den Reitern Spieler und Trainer, siehe http://svdoerpum.de/senioren/1-herren/spielplan/matchreport/0/7/60:verbandsliga-nord-2019-2020/5702:sv-doerpum_buedelsdorfer-tsv

**Comment by diddipoeler** [comment]
Bitte einmal testen.

**Comment by svdoldie** [comment]
Sieht viel besser aus :+1:

**Comment by diddipoeler** [comment]
Bitte noch mal testen.

**Comment by svdoldie** [comment]
Bei den Spielern sieht das top aus :+1: 
Beim Staff sehe ich keine Veränderung

**Comment by diddipoeler** [comment]
Bei den Mitarbeitern kannst du das auch nicht sehen, da das gar nicht programmiert wurde :-(
Muss ich erst alles entwickeln.

**Comment by svdoldie** [comment]
Kein Problem, ich völlig geduldig :-)

**Comment by svdoldie** [comment]
Funktioniert ja schon :+1:

**Comment by diddipoeler** [comment]
Bei mir sieht das richt beschi....en aus wenn ich auf den Reiter Spieler klicke:
https://www.fussballineuropa.de/index.php/component/sportsmanagement/matchreport/0/0/89036:1-bundesliga-2019-20/16512448:sc-freiburg_fc-gelsenkirchen-schalke-04-e-v-i

**Comment by svdoldie** [comment]
Hmm, bei mir sieht es besser aus http://svdoerpum.de/senioren/1-herren/spielplan/matchreport/0/7/60:verbandsliga-nord-2019-2020/5702:sv-doerpum_buedelsdorfer-tsv
Vielleicht Joomla-Template abhängig?

**Comment by svdoldie** [comment]
Was evtl. noch beim Staff geändert werden muss,
ist das die Anzeige des Link zur Person noch aus den Einstellungen Personen Optionen gezgen werden muss

**Comment by diddipoeler** [comment]
Jetzt gibt es noch eine neue Darstellungsform für den Kader der Spieler:
https://www.fussballineuropa.de/index.php/component/sportsmanagement/matchreport/0/0/89036:1-bundesliga-2019-20/16512448:sc-freiburg_fc-gelsenkirchen-schalke-04-e-v-i

![Ashampoo_Snap_2020 07 25_18h31m55s_002_](https://user-images.githubusercontent.com/1028107/88461622-589f9300-cea5-11ea-8668-35339eff9bb1.png)

**Comment by svdoldie** [comment]
Sieht sehr gut aus :+1:

**Comment by Karntner** [comment]
Ich habe mir mal erlaubt ein Override zu machen. 
Bei mir sind unsere Spieler jetzt immer links!  Dann muss ich nur unsere Spieler eintragen

https://www.union-steinerkirchen.at/index.php/component/sportsmanagement/matchreport/0/0/77:freundschaftsspiele/12679:eberstalzell_steinerkirchen
