### ISSUE TITLE
Spieldetails

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1113]
Es wäre super wenn man bei der Eingabe der Spieldetails das Datum und die Uhrzeit ändern könnte. 
Mein Vorschlag wäre gleich oberhalb des Austragungsortes
![image](https://user-images.githubusercontent.com/59525415/88375462-eabb7480-cd9b-11ea-8fd7-4a524abb9f11.png)

**Comment by diddipoeler** [comment]
Verstehe ich jetzt nicht so ganz.
Meinst Du das Datum und die Uhrzeit des Spiels ?
Das kann man doch in der Übersicht der Spiele zu einer Runde ändern ?

**Comment by sigal** [comment]
So sehe ich das auch.
