### ISSUE TITLE
Eingabe Statistik

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#1121]
Hallo zusammen,

bei der Eingabe der Statistiken ist die Anzeige der Images für das Auswärtsteam verutscht.

Heim:
![image](https://user-images.githubusercontent.com/9608697/88683553-3a7ba200-d0f4-11ea-837c-26afe0e0af7a.png)

Auswärts:
![image](https://user-images.githubusercontent.com/9608697/88683621-4ebf9f00-d0f4-11ea-816c-a09c4635ffce.png)

**Comment by Karntner** [comment]
@PhantoSGE : wo wendest du das an?

**Comment by PhantoSGE** [comment]
Sorry, im Backend. Spiele bearbeiten. In der Eingabemaske der Statistiken

![image](https://user-images.githubusercontent.com/9608697/88764368-2330c900-d175-11ea-8bbe-c7aceb2afec9.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Super. Sieht gut aus.
Danke dir
