### ISSUE TITLE
Spiele bearbeiten: Bilder zum Spiel hinterlegen

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#1122]
Guten morgen zusammen,

Der Bilder upload funktioniert nicht. Nachdem ich auf hochladen klicke ist der Ordner immernoch leer.

![image](https://user-images.githubusercontent.com/9608697/88765304-9129c000-d176-11ea-824b-12939ad0ec20.png)
![image](https://user-images.githubusercontent.com/9608697/88765344-a3a3f980-d176-11ea-8b7e-8f6a91e75390.png)
![image](https://user-images.githubusercontent.com/9608697/88765449-ca623000-d176-11ea-89df-cddabe8c546f.png)

Gruß
Sven

**Comment by PhantoSGE** [comment]
Ich habe ein falsches Bild hochgeladen.

Wenn ich ein Bild ausgewählt habe und es hochladen möchte sieht es erst so aus als hätte er es akzeptiert.
![image](https://user-images.githubusercontent.com/9608697/89019721-0b487900-d31e-11ea-8f01-091546e9b3f9.png)


Allerdings ist der Ordner dannach leer.
![image](https://user-images.githubusercontent.com/9608697/89019762-1a2f2b80-d31e-11ea-8f4b-24f3be8d2f31.png)

Gruß
Sven

**Comment by diddipoeler** [comment]
Bitte einmal testen.

**Comment by PhantoSGE** [comment]
Funktionier. Danke dir 👍
