### ISSUE TITLE
Teaminfo - Historietabelle

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#1124]
Momentan wird für den Platz einer Saison immer **1** ausgegeben

Siehe: [Schalke 04](https://fussballineuropa.de/index.php/component/sportsmanagement/teaminfo/0/0/89036:1-bundesliga-2019-20/9:fc-gelsenkirchen-schalke-04-e-v-i/1360828:fc-gelsenkirchen-schalke-04-e-v-i)

oder für den Absteiger der Saison 2019/20: [Paderborn](https://fussballineuropa.de/index.php/component/sportsmanagement/teaminfo/0/0/89036:1-bundesliga-2019-20/33:sc-paderborn-1907-e-v/1360833:sc-paderborn-1907-e-v)

Wobei noch zum Anfügen ist, dass eigenartigerweise bei älteren Saisonen der Rang passt?

**Comment by diddipoeler** [comment]
Sehe ich gerade nicht.

**Comment by sigal** [comment]
over Austria:

![#1124_01](https://user-images.githubusercontent.com/5115688/89009245-6cffe780-d30c-11ea-9800-c823506a7a98.jpg)


![#1124_02](https://user-images.githubusercontent.com/5115688/89009253-74bf8c00-d30c-11ea-92e9-d3da1ee6de6b.jpg)

**Comment by sigal** [comment]
https://www.svdoerpum.de/senioren/1-herren/tabelle/teaminfo/0/0/60:verbandsliga-nord-2019-2020/13:sv-doerpum/850:sv-doerpum

https://fussballineuropa.de/index.php/component/sportsmanagement/teaminfo/0/0/101350:premier-league-2020-21/167:arsenal-fc/1556560:arsenal-fc

https://fussballineuropa.de/index.php/component/sportsmanagement/teaminfo/0/0/99508:ligue-2-2020-21/3546:paris-fc/1531608:paris-fc

https://demo.jsm-help.de/jsm-alle-projekte/teaminfo/0/0/4190:st-oberliga-nord-2019-20/3661:esv-knittelfeld/56794:esv-knittelfeld
