### ISSUE TITLE
Spielleiter in einem Prjoekt

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1125]
Hallo @diddipoeler !

Könntest du dir ein Projekt von mir ansehen? 
Hier werden 3 Spielleiter angezeigt. 
![image](https://user-images.githubusercontent.com/59525415/88934728-43e64500-d281-11ea-870d-f72d4667d38a.png)

Aber wenn ich einen einfügen möchte geht das nicht. Und es wird auch keiner angezeigt. 
![image](https://user-images.githubusercontent.com/59525415/88934849-624c4080-d281-11ea-8bc9-4cf09c29e2ba.png)

Beim bearbeiten des Spieles sind dann aber 3 drinnen. 
![image](https://user-images.githubusercontent.com/59525415/88934983-8d369480-d281-11ea-954f-e449c08d1376.png)

**Comment by Karntner** [comment]
Hab den Fehler gefunden

**Comment by Karntner** [comment]
Ok das war nicht der Fehler. Irgendwas stimmt da nicht!

**Comment by Karntner** [comment]
Ich habe den Fehler gefunden. Wenn ein Schiri schon bei einem Projekt der aktuellen Saison zugeordnet ist dann kann man ihn zwar hinzufügen und in der Datenbank wird ein Dstensatz angelegt. Aber im Projekt scheint er im Backend nicht auf.

**Comment by diddipoeler** [comment]
In welcher Tabelle hast die Daten kopiert ?

**Comment by Karntner** [comment]
bak_jos_sportsmanagement_project_referee

Die Spielleiter sind zwar drinnen und das auch mit Foto. Aber im Prjojekt zeigt es sie nicht an.

**Comment by Karntner** [comment]
Sorry jos_sportsmanagement_project_referee ist die richtige Tabelle

**Comment by Karntner** [comment]
[jos_sportsmanagement_project_referee.zip](https://github.com/diddipoeler/sportsmanagement/files/5006705/jos_sportsmanagement_project_referee.zip)

**Comment by Karntner** [comment]
@diddipoeler : Hast du da was geändert?
Jetzt kann ich die Position auch nicht mehr abspeichern?
![image](https://user-images.githubusercontent.com/59525415/89099062-056d9900-d3ed-11ea-8484-94c452d5fdfc.png)

**Comment by diddipoeler** [comment]
@Karntner Wie du siehst bin ich an der Problembehebung dran. Erst Updates der Komponente machen,
wenn ich hier die Freigabe zum Testen poste !

**Comment by Karntner** [comment]
Super Danke. 
Ist sicher aufwendig sowas. 

Hab mich nur gewundert das es wieder ein wenig anders war.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Karntner** [comment]
Hallo diddi.
Funktioniert ganz gut. Nur bei einer Person geht es nicht. 
Da muss irgendwas bei den Personendaten eingestellt sein was nicht sein soll.

![image](https://user-images.githubusercontent.com/59525415/89101804-d151a280-d403-11ea-9ab2-54af560cf70f.png)

**Comment by Karntner** [comment]
Da ist die Position Schiedsrichter nicht hinterlegt bei dem. Ich hoffe ich bekomme das hin. Den der ist Spieler, Trainer und Schiedsrichter. 
Mal schaun wie ich das anlege.

**Comment by Karntner** [comment]
Dachte ich mir. Jetzt kann ich den als Schiedsrichter einfügen. Dafür aber nicht mehr als Spieler.

**Comment by diddipoeler** [comment]
Wenn er als Spieler schon hinzugefügt wurde, kann man ihn dann als Schiedsrichter hinzufügen ?

**Comment by Karntner** [comment]
Bin grad ein wenig überfordert. Teilweise schon. 
Muss mir ansehen was da bei den Personendaten der Unterschied ist.

**Comment by Karntner** [comment]
Es schaut so aus das es nur bei denen funktioniert die wirklich nirgends zu geordnet sind.

**Comment by Karntner** [comment]
Ich werde mal ein Backup der Datenbank machen. Dann alle Saisonzuordnungen in der Datenbank löschen und dann noch mal testen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Karntner** [comment]
Nein leider nicht erfolgreich. 

Aber meine Bereinung der Datenbank brachte erfolg. Jetzt kann ich die selbe Person als Spieler, Trainer und Schiedsrichter hinzufügen!

**Comment by Karntner** [comment]
Shit jetzt gehts schon wieder nicht. Sobald eine Person schon wo als Schiedsrichter eingetragen ist gehts bei einem anderen Projekt nicht mehr.

**Comment by Karntner** [comment]
Mah i bin so blöd. Der Fehler war jetzt das die Position nicht in dem Prjoekt war.

**Comment by Karntner** [comment]
Ein Problem ist auch das 2 mal die Position Schiedsrichter in den Positionen der Komponente ist. Wenn man da die falsche nimmt dann geht es nicht. 
Ich habe die schon öfter rausgelöscht aber nach jedem Gifthub update wird die wieder reingespielt,

**Comment by Karntner** [comment]
Ich habe jetzt folgendes getestet. 
Ich habe die 3 Projekte auf 3 Saisonen aufgeteilt und die alle unter der aktuellen Saison aktiviert. 
Es hat nicht geklappt. 

Dann habe ich 1 Saison auf aktuell gesetzt und die anderen beiden nicht. Siehe da es hat funktioniert. Es dürfte irgendwas damit zu tun haben das man 1 Person nur 1mal pro aktueller Saison als Schiedsrichter zuordnen kann.

**Comment by Karntner** [comment]
Ich gebs jetzt auf. Jetzt sind wieder alle weg. Angezeigt werden die auch nicht richtig. 
Wäre ein schönes Tool aber so bringt es nichts.

**Comment by Karntner** [comment]
@diddipoeler Mach dir keinen Stress wegen dem.

**Comment by diddipoeler** [comment]
Ich habe das System ausgetrickst.

**Comment by Karntner** [comment]
Echt. Cool

Test es später.

**Comment by Karntner** [comment]
Wahnsinn. Das funktioniert aber super jetzt!

Danke

**Comment by Karntner** [comment]
Das ist jetzt nicht ganz so wichtig. Wenn man es weis ist das kein Problem. 
Kann man hier noch was machen das alle Positionen angezeigt werden. Sonst muss man immer auswählen und dann glaubt man die wurden nicht übernommen.

![image](https://user-images.githubusercontent.com/59525415/89903966-a415a900-dbe8-11ea-9670-3c678f22c562.png)

**Comment by Karntner** [comment]
Es tut mir leid aber irgendwie scheint das schon wieder nicht zu funktionieren. 
Wurde da was zurückgesetzt?

**Comment by Tobsen84** [comment]
Wollte erst einen eigenen Defect einstellen aber dann habe ich diesen hier entdeckt. Bei mir besteht aktuell das identische Problem:

1) Anzahl Schiedsrichter in einem Projekt -> Anzahl = 7

![Spielleiter01](https://user-images.githubusercontent.com/61277544/95251378-bd6b5800-081b-11eb-8c72-7b2231180156.PNG)

2) Im Menü wird mir dann lediglich einer angezeigt

![Spielleiter02](https://user-images.githubusercontent.com/61277544/95251437-d70c9f80-081b-11eb-8bb0-7923b1bd0b43.PNG)

3) Bei der Schiedsrichterzuweisung an einem Spieltag des Projektes werden mir 7 Personen angezeigt (allerdings nur 2 verschiedene Namen und die Position fehlt auch bei fast allen)

![Spielleiter03](https://user-images.githubusercontent.com/61277544/95251565-091e0180-081c-11eb-8984-dc4b8a48961e.PNG)

4) Den bereits zugeordneten Schiedsrichter finde ich weiterhin im Zuordnungsmenü - bei Spielern sind diese nach der Zuweisung nicht mehr zu finden -> mögliche Fehlerquelle?
![Spielleiter04](https://user-images.githubusercontent.com/61277544/95251692-336fbf00-081c-11eb-8a5e-03db9a3aec26.PNG)

Zusatz: Ist es korrekt, dass die Positionszuweisung in rot angezeigt wird?

**Comment by diddipoeler** [comment]
Ich glaube da habe ich blödsinn programmier.
Gebt mir bitte noch ein bisschen Zeit.

**Comment by Tobsen84** [comment]
Hallo Diddi,

wollte mal nachfragen, ob diesbezüglich Retests möglich sind, da ja doch einige Änderungen erfolgt sind oder noch daran gearbeitet wird? Wäre ja möglich, dass nur ein "Bitte retesten!" nicht kommuniziert wurde.

Gruß
Tobsen

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Tobsen84** [comment]
Hab nochmal etwas rumprobiert. Dabei sind mir noch zwei Sachen aufgefallen:

1) Wahrscheinlich ein reines (Datenbank?)-Problem bei uns. In einem unserer aktuellen Projekte wird die Anzahl der Spielleiter mit "1 Spielleiter" dargestellt obwohl kein Spielleiter zugeordnet ist. Auch bei der Schiedsrichterzuweisung eines konreten Spieles in diesem Projekt werden keine Schiedsrichter auf der linken Seite zur Auswahl dargestellt. Bei allen anderen Projekten passt die Anzahl allerdings zur den zugeordneten Personen. Hab da auch etwas rumprobiert mit löschen und wieder hinzufügen. Daher meine Vermutung, dass bei dem einen Projekt vielleicht noch eine "Datenbank-Leiche" vorhanden ist, was man manuell bereinigen müsste?

2) Die Mehrfachzuweisung eines Spielleiters in mehrere Projekte einer Saison führt zu einer Fehlermeldung. Wenn ich also einen Spielleiter bei dem Projekt der 1. Mannschaft zugewiesen habe und danach ihn auch beim Projekt der 2. Mannschaft zuweisen möchte kommt folgende Fehlermeldung:

![Bild1](https://user-images.githubusercontent.com/61277544/100287562-25653180-2f75-11eb-8b46-7c8e883c72a1.PNG)

Wenn ich dann allerdings aus dem Zuordnungsmenü heraus gehe und einen Refresh mache, ist der Schiedsrichter dennoch vorhanden:

![Bild2](https://user-images.githubusercontent.com/61277544/100287643-504f8580-2f75-11eb-97c2-b7fe85e4392c.PNG)

Gehe ich danach wieder in das Zuordnungsmenü wird die Person weiterhin gefunden und könnte theoretisch ausgewählt werden:

![Bild3](https://user-images.githubusercontent.com/61277544/100287719-71b07180-2f75-11eb-9879-a1e487069a72.PNG)

Im Normalfall verschwindet die Person aus dem Auswahlmenü nach der Zuweisung im Projekt, wenn sozusagen die Projektzuordnung normal funktioniert hat (also wenn der Spielleiter noch in keinem weiteren Projekt der Saison vorhanden ist).

Fazit: Zumindest Punkt 2) ist meines Erachtens nicht wirklich korrekt. So ein ähnliches Problem gab es glaub auch schon mal bei der Zuweisung von Spielern in mehreren Projekten einer Saison.

Viele Grüße
Tobsen84

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
