### ISSUE TITLE
Schiedsrichter Anzeige

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1131]
Hier wird die Anzeige des Namens nicht übernommen. Die kann man im Template Referee unter Personen einstellen. 

https://www.union-steinerkirchen.at/index.php/mannschaften/kampfmannschaft/spielplan-kampfmannschaft/teamplan

Hier funktioniert es
https://www.union-steinerkirchen.at/index.php/spielplan-verein/kal/clubplan

**Comment by diddipoeler** [comment]
Ich sehe aber in beiden Anzeigen den Namen des Schiedsrichters !

**Comment by Karntner** [comment]
Ich habe beim Template Refere die Anzeige auf " Vorname Nachnahme gestellt. 
Diese wird nicht übernommen. 

Ist nur eine optische Korrektur. 

https://www.union-steinerkirchen.at/index.php/mannschaften/kampfmannschaft/spielplan-kampfmannschaft/teamplan

**Comment by diddipoeler** [comment]
Im Template teamplan sehe ich keine Einstellung für den Namen des Schiedsrichters.

**Comment by Karntner** [comment]
Ok dann ist das im Template Clubplan automatisch so und hat nichts mit dein Einstellungen im Template Referee zu tun

**Comment by Karntner** [comment]
Vielleicht könnte man die Datumsanzeige hier auf ein Deutsches Format umstellen. 

https://www.union-steinerkirchen.at/index.php/spielplan-verein/kal/referee/0/45/124/243

**Comment by Karntner** [comment]
Ich habe das jetzt mit einem Override gelöst
https://www.union-steinerkirchen.at/index.php/mannschaften/kampfmannschaft/spielplan-kampfmannschaft/teamplan
