### ISSUE TITLE
Joomla 4 - Projekteinstellungen lassen sich nicht speichern

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1132]
Unter Joomla 4 lassen sich die Projekteinstellungen nicht speichern.
Unter Joomla 3 funktioniert das einwandfrei

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Geht leider noch nicht

**Comment by diddipoeler** [comment]
Sende mir mal bitte die Adminzugangsdaten mit allen Berechtigungen zu.

**Comment by svdoldie** [comment]
Du hast Post 😀

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft, danke :-) 👍
