### ISSUE TITLE
Joomla 4 - FE-Ansichten funktionieren nicht

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1133]
Ich habe jetzt mehrere Frontendansichten angelegt,
leider werden nur Fehlermeldungen angezeigt.
Die Fehlermeldungen lauten wie folgt:
500 behavior::tooltip not found.  oder
500 behavior::switcher not found. 

JSM ist auf dem neusten Stand, Joomlaversion Beta ‎4.0.0-beta4-dev

**Comment by diddipoeler** [comment]
Einiges müsste jetzt laufen.

**Comment by svdoldie** [comment]
Ja bestens 👍 
Sieht schon viel besser aus :-)

**Comment by diddipoeler** [comment]
Da kann mal sehen wie empfindlich Jommla 4 ist :-)

**Comment by svdoldie** [comment]
Ich habe noch eine Fehlermeldung gefunden:
Im ewigen Kader erscheint:
500 behavior::framework not found.

**Comment by diddipoeler** [comment]
So, den haben wir auch bereinigt.

**Comment by svdoldie** [comment]
👍

**Comment by svdoldie** [comment]
Einen hab ich noch ;-)
500 JHtml formbehavior2 not found. 
In der FE-Bearbeitung des Vereins

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft 👍
