### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1135]
Hallo @diddipoeler , @svdoldie @sigal 

Könnte ihr bei euren Seiten was testen. 
Bei mir sind die Tooltips transparent und ich bin mir nicht sicher ob das an meinem Template oder an der Komponente liegt. 

Hier der Spielort:
https://www.union-steinerkirchen.at/index.php/admin/ergebnisse/ergebnisseingabe-u15/results

Hier die Schiedsrichterfunktion:
https://www.union-steinerkirchen.at/index.php/mannschaften/kampfmannschaft/spielplan-kampfmannschaft/teamplan

Danke für eure Hilfe

**Comment by diddipoeler** [comment]
Der erste Link ist die Ergebniseingabe. Habe ich kein Zugriff drauf.
Wo soll denn im 2ten Link ein Tooltip erscheinen ?

**Comment by diddipoeler** [comment]
Ah beim Schiedsrichter ?

**Comment by Karntner** [comment]
ja genau

**Comment by diddipoeler** [comment]
Bei mir sieht es tatsächlich anders aus:
https://www.fussballineuropa.de/index.php/component/sportsmanagement/teamplan/0/0/89036:1-bundesliga-2019-20/9:fc-gelsenkirchen-schalke-04-e-v-i/0/1360828:fc-gelsenkirchen-schalke-04-e-v-i

Vielleicht kann man das programmieren. Es gibt da in Joomla 3/4 eine neue Funktion !

**Comment by Karntner** [comment]
Danke fürs testen. 

Dann muss ich bei mir nachsehen. 

Meinst du die Übernagnsversion 3,10?

**Comment by diddipoeler** [comment]
Benutzt du die Originaldateien von JSM oder Overrides ?

**Comment by Karntner** [comment]
Hab nur beim Matchreport ein Override
