### ISSUE TITLE
Tippspiel

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1136]
Irgendwas stimmt beim Tippspiel nicht

Ich muss jeden User extra hinzufügen. 
Bei den aktuellen Tippspielern im Frontend werde nur ich angezeigt. 
Admin Tips kann ich auch nicht eintragen

https://www.union-steinerkirchen.at/index.php

**Comment by Karntner** [comment]
Der Link zum registrieren funktioniert nicht. 

https://www.union-steinerkirchen.at/index.php/tippspiel/tipp-regeln/predictionrules

**Comment by sigal** [comment]
ACL für Tippspiel konfiguriert? (JSM->Optionen->Berechtigungen)

Überprüfen, ob Kontenaktivierung durch Administrator in der Joomla Benutzerverwaltung aktiviert ist. Das überschreibt die Freigabe im Tippspiel.

**Comment by Karntner** [comment]
@sigal Hast du das gemeint?
![image](https://user-images.githubusercontent.com/59525415/89315759-86da5b00-d67b-11ea-9a78-a62fa7bbe452.png)

**Comment by Karntner** [comment]
Kontenaktivierung ist auf Benutzer. 
Und diese Meldung kommt wenn man auf registrieren klickt. 
![image](https://user-images.githubusercontent.com/59525415/89316268-28fa4300-d67c-11ea-8e4f-08bc312ba2a6.png)

**Comment by sigal** [comment]
Bitte ein Update

**Comment by Karntner** [comment]
Super es funktioniert!

Danke @sigal

**Comment by Karntner** [comment]
Hallo. Es klappt alles wunderbar.
Nur einen kleinen Hacken hat es. Ich muss jeden Benutzer manuell zu einer Tippspielgruppe hinzufügen. 
Tipps kann der User aber ohne dem auch abgeben.

**Comment by Karntner** [comment]
Ich Depp. Ich muss ja keine Gruppe angeben.Geht so auch
