### ISSUE TITLE
Joomla 4 - JSM Bilder-Import funktioniert nicht

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1137]
Beim Bilder-Import erhalte ich folgende Meldung z.B.:
0 Archive does not exist at /var/www/vhosts/svdoerpum.de/svdoerpum.de/joomla4/tmp/agegroups.zip 
Mit Joomla 3 klappt alles einwandfrei

**Comment by diddipoeler** [comment]
Jetzt wird wenigstens schon mal eine Fehlermeldung angezeigt.

**Comment by diddipoeler** [comment]
Bitte mit Vorsicht testen.

**Comment by svdoldie** [comment]
Der Import funktioniert soweit 👍 :-)
Nur mit der Auswahl stimmt noch etwas nicht. Wenn man ein Kästchen auswählt,
wird das darüber liegende auch angewählt. Wenn man das abwählen möchte, wird das darüber liegende angewählt

**Comment by diddipoeler** [comment]
Ist bei den Altersgruppen auch mmhhh

**Comment by diddipoeler** [comment]
Bei den Ländern auch !

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
perfekt 👍
