### ISSUE TITLE
Joomla 4 Test

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1140]
Hallo

Wie gehe ich den am besten vor wenn ich meine Seite und vor allem JSM in Joomla 4 testen möchte?

**Comment by svdoldie** [comment]
Ich kann dir nur beschreiben was ich gemacht habe:
1. einen Ordner z.B. jsmtest im Rootverzeichnis deines Servers anlegen
2. eine weitere Datenank anlegen
3. Joomla 4 beta im Ordner jsmtest entpacken
4. Joomla 4 installieren
5. JSM installieren
Danach kannst du alles so mit JSM machen wie unter Joomla 3

**Comment by diddipoeler** [comment]
Ihr könnt aber auch hier: https://joomla40.diddipoeler.de/ testen.

**Comment by Karntner** [comment]
Wie kann ich da testen?

**Comment by diddipoeler** [comment]
Du musst dich registrieren.
Dann schalte ich dich als Admin frei.

**Comment by diddipoeler** [comment]
@Karntner Bist jetzt freigeschaltet.

**Comment by svdoldie** [comment]
Mal was allgemeines.
Wären solche Fragen nicht besser im Forum aufgehoben?

**Comment by diddipoeler** [comment]
Ja hast recht. Kannst ja bitte mal ein Thread zu dem Thema eröffnen, damit alle was davon haben.

**Comment by svdoldie** [comment]
Mach ich. Kann sich dann jeder von dir auf der Testseite freischalten lassen?
Oder soll ich nur meine Schritte darstellen?

**Comment by diddipoeler** [comment]
Es kann sich jeder freischalten lassen.

**Comment by svdoldie** [comment]
erledigt 👍 Bitte kurz mal drüberlesen ;-)

**Comment by diddipoeler** [comment]
Ist OK.
