### ISSUE TITLE
Frontend Ergebnis Eingabe übers Handy

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1142]
Ich weis nicht ob das möglich ist aber bei der Handy Ansicht bei der Frontend Ergebnis Eingabe kann man nichts erkennen und dadurch ordentlich eingeben. 
Könnte man das ev. anpassen?
![Screenshot_20200808-123654_Chrome](https://user-images.githubusercontent.com/59525415/89708079-66104f00-d974-11ea-8cdf-516a70f8ce38.jpg)

**Comment by sigal** [comment]
Kartner verwendet kein JSM mehr. Issue schließen?
