### ISSUE TITLE
Wunsch Modul Matches

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1143]
Könnte man im Modul Matches alle 3 Schiedsrichter anzeigen wenn die eingetragen wurden?
![image](https://user-images.githubusercontent.com/59525415/89708356-ba1c3300-d976-11ea-8aa2-973e84ee9450.png)

So z.B
Schiedsrichter: ......
Assistent 1: ......
Assistent 2: ......

**Comment by Karntner** [comment]
Noch was ist mir aufgefallen in dem Modul!
Da wird irgend ein Schiedsrichter angezeigt. Nicht der Hauptschiedsrichter. 
Ich bin da z.B nur als Assistent eingetragen. Der eigentliche Schiedsrichter wird nicht angezeigt. 
Kann man da die Reihenfolge irgendwo ändern?
![image](https://user-images.githubusercontent.com/59525415/89904497-4cc40880-dbe9-11ea-88ce-9c34370ce25b.png)

**Comment by Karntner** [comment]
Das selbe ist im Template Clubplan und Teamplan. Da muss wahrscheinlich nur die Reihenfolge der Positionen geändert werden. 
Ich weis aber nicht wie das geht.

**Comment by diddipoeler** [comment]
Bitte einmal mit Vorsicht testen.

**Comment by Karntner** [comment]
Schaut gut aus. Im Modul ist noch Vor und Nachnahme vertauscht. Vl kann man das wo einstellen.

**Comment by Karntner** [comment]
Mit einem Modul Override habe ich Vor und Nachnamen vertauscht. Jetzt passt es.

**Comment by Karntner** [comment]
Noch eine Kleinigkeit
Hier ist die Sortierung auch noch falsch.

https://www.union-steinerkirchen.at/index.php/mannschaften/kampfmannschaft/spielplan-kampfmannschaft/teamplan

**Comment by Karntner** [comment]
Super @diddipoeler 👍 Ich denke jetzt passt alles
