### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1145]
Bei mir kommt sehr häufig diese Fehlermeldung. 

Wenn ich z.b Positionen, Personen usw zu einem Projekt hinzufügen möchte.

![image](https://user-images.githubusercontent.com/59525415/89809112-69096c00-db3b-11ea-97d4-9f5ab662395c.png)

**Comment by diddipoeler** [comment]
Bei welchem Projekt erscheint dieser Fehler ?

**Comment by Karntner** [comment]
Bei mir bei jedem

**Comment by Karntner** [comment]
Jetzt funktioniert wieder alles

Danke Diddi
