### ISSUE TITLE
Joomla 4: Fieberkurve + Maps werden nicht angezeigt

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1146]
Unter Joomla 4 wird weder die Fieberkurve, noch die Karte angezeigt.
Müssen dafür noch Plugins installiert oder aktiviert werden?

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Die Fieberkurve wird angezeigt.
Bei der Karte ist es folgendermaßen:
Bei den Vereinsinfos wird sie angezeigt
In der Tabellenansicht nicht
In der Playgroundansicht wird außer dem Copyright usw. gar nichts angezeigt

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Hi. Ich komme leider erst frühestens heute Nachmittag zum testen

**Comment by svdoldie** [comment]
Aktueller Status ist folgender:
Die Fieberkurve geht 👍 
Die Karte wird in der Spielstättenansicht richtig angezeigt 👍 
In der Vereinsinfoansicht nur teilweise, in der Tabellenansicht gar nicht

**Comment by svdoldie** [comment]
In der Vereinsinfoansicht wird die Karte mittlerweile angezeigt,
in der Tabellenansicht noch nicht

**Comment by svdoldie** [comment]
Mittlerweile wird die Karte auch in der Tabellenansicht angezeigt
