### ISSUE TITLE
Joomla 4 - Aktivierung des Bootstrap-Plugin legt Joomla-Backend lahm !!!

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1147]
Das Aktivierung des Bootstrap-Plugin legt das ganze Joomla-Backend lahm.
Auf allen Seiten erscheint folgende Fehlermeldung

Es ist ein Fehler aufgetreten!
0 Call to undefined method Joomla\CMS\Application\AdministratorApplication::isAdmin()

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Alles bestens 👍
