### ISSUE TITLE
Ical Export Icon

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1148]
Ich habe den Ical Export zwar aktiviert aber es wird nicht angezeigt. 
Muss ich da noch wo was einstellen?

https://www.union-steinerkirchen.at/index.php/mannschaften/kampfmannschaft/spielplan-kampfmannschaft/teamplan

**Comment by sigal** [comment]
Seitenelemente einblenden!!!
Template [ Mannschafts-Spielplan Anzeige ]
TAB [Seitenelemente] ->Zeige Bereichsüberschrift -> **JA**

Siehe: [Mit ICAL](https://demo.jsm-help.de/component/sportsmanagement/teamplan/0/0/4730:o-2-liga-mittewest-2020-21/5079:steinerkirchen/0/65589:steinerkirchen)

**Comment by Karntner** [comment]
Danke Sigal

Das versuch ich dann gleich mal

**Comment by Karntner** [comment]
Aber der geht nur einmal und aktualisiert sich nicht oder?

**Comment by sigal** [comment]
Wie meinen?

**Comment by Karntner** [comment]
Wenn ich den z.B in meinen Kalender als Internet Kalender einfüge aktualisiert der den Kalender auf meinem PC oder Handy wahrscheinlich nicht  wenn ich ein Spiel ändere?

**Comment by sigal** [comment]
Automatisch im Kalender nicht. Bei Änderungen ICAL neu importieren

**Comment by Karntner** [comment]
ok. Mein Email Programm importiert den automatisch immer neu. Das ist cool

Besser wäre es mit dem Google Kalender aber den bring ich nicht mehr zum laufen.

**Comment by Karntner** [comment]
I glaub i spinn. Jetzt geht der a wieda.
