### ISSUE TITLE
Spielstätten

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1149]
Warum kommt hier die Meldung das ich die Spielstätte neu anlegen soll?

https://www.union-steinerkirchen.at/index.php/mannschaften/kampfmannschaft/spielplan-und-tabelle-2-mo/resultsranking

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Karntner** [comment]
Hallo

Jetzt kommt eine andere Meldung

![image](https://user-images.githubusercontent.com/59525415/90164970-5344b280-dd98-11ea-94ef-945e8f8a0537.png)

**Comment by Karntner** [comment]
Jetzt scheint die Meldung doch weg zu sein.

**Comment by Karntner** [comment]
Nein doch nicht und die Uhrzeit ist auf Englisch

**Comment by Karntner** [comment]
Ich hab das jetzt ausgeblendet. Eigentlich brauch ich das nicht. Gibt ja sowieso einen Linkt zur Sportstätte
