### ISSUE TITLE
Komponente hängt

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1152]
Ich habe heute ein Github Update gemacht.

Seit dem bleibt die Komponente im Backend hängen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by diddipoeler** [comment]
Ich glaube meine Seite wurde gehackt.

**Comment by Karntner** [comment]
Ich kann kein Update machen. Sobald ich die Komponente anklicke steht alles.

**Comment by Karntner** [comment]
Shit ich komm nicht mal in mein Backend rein

**Comment by Karntner** [comment]
Ich habe jetzt ein Backup meiner Seite reingespielt und die Komponente neu installiert. Jetzt funktioniert es. 
Ein Github Update mache ich vorerst nicht. Sonst habe ich das selbe wieder.

**Comment by Karntner** [comment]
Ah du hast ja schon was geändert. Jetzt funktionier auch mit einem Update wieder alles.

**Comment by Karntner** [comment]
Was halt jetzt noch ist. Ich habe einen Mix aus deutscher und englischer Spracht. Das ist ganz eigenartig seit dem letzten Update

**Comment by svdoldie** [comment]
Moin. Ich hatte ähnliche Probleme. Nach einer Wiederherstellung geht bei mir auch alles wieder :+1:
