### ISSUE TITLE
Hinzufügen von Spielern zu einer Mannschaft

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1153]
Ich kann keine Spieler mehr zu einer Mannschaft hinzufügen!

![image](https://user-images.githubusercontent.com/59525415/90311936-74281780-df00-11ea-8305-bf4bb3017c4b.png)

**Comment by diddipoeler** [comment]
Welcher Spieler zu welcher Mannschaft in welchem Projekt ?

**Comment by Karntner** [comment]
Komischer Weise funktioniert es jetzt wieder obwohl ich nichts verändert habe.
