### ISSUE TITLE
Ligabild

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1154]
Ich weis nicht ob das so beabsichtigt ist aber Ich verstehe bei der Anzeig des Ligabildes das auch das Bild das ich in der Liga hochlade angezeigt wird und nicht das Spielerbild bzw. das Vereinswappen. 

https://www.union-steinerkirchen.at/index.php/de/mannschaften/kampfmannschaft/kader/player/0/452020-21/124:2-mittewest-2020-21/215:steinerkirchen/17:thomas-wieser

https://www.union-steinerkirchen.at/index.php/de/mannschaften/kampfmannschaft/kader/teaminfo/0/452020/124:2-mittewest-2020-21/215:steinerkirchen/0

Korrigiert mich bitte wenn ich mich da irre.

**Comment by diddipoeler** [comment]
Existiert der Fehler noch ?

**Comment by Karntner** [comment]
Ja

https://www.union-steinerkirchen.at/index.php/de/mannschaften/kampfmannschaft/kader/player/0/452020-21/164:2-mittewest-2020-2021/215:steinerkirchen/196:phillipp-mittermair


Oder ist da etwas das Bild des Spielers in der Liga gemeint bei Ligabild?

**Comment by sigal** [comment]
Kartner verwendet kein JSM mehr. Issue schließen?
