### ISSUE TITLE
Gespielte Minuten

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1156]
Hallo

Die gespielten Minuten stimmen nicht. 
Der hat eigentlich 72 Minuten. 

https://www.union-steinerkirchen.at/index.php/de/mannschaften/kampfmannschaft/kader/player/0/452020-21/124:2-mittewest-2020-21/215:steinerkirchen/13:daniel-mittermair

**Comment by svdoldie** [comment]
Hast du im Template overall bei Personendaten Ereignisse für Spielzeitverkürzung etwas eingetragen?
Beim Fußball wären das z.B. gelbrote und rote Karten

**Comment by Karntner** [comment]
Das muss ich mir ansehen

**Comment by Karntner** [comment]
Ja da ist was drinnen. Wie bekomme ich die raus
![image](https://user-images.githubusercontent.com/59525415/90341503-60fc7100-e000-11ea-97ce-25d6d050f312.png)

**Comment by svdoldie** [comment]
Eigentlich nur nochmal drauf klicken

**Comment by Karntner** [comment]
Aso. Wenn die hinterlegt sind dann sind die erst ausgewählt?
Das ist bei mir nicht der Fall

**Comment by svdoldie** [comment]
Beim Anlegen eines Projekts ist keine Option ausgewählt

**Comment by Karntner** [comment]
Dann muss der Fehler wo anders liegen

**Comment by svdoldie** [comment]
Hast du die gelbrote und rote Karte mal ausgewählt?

**Comment by Karntner** [comment]
Nein

**Comment by svdoldie** [comment]
versuch mal bitte

**Comment by Karntner** [comment]
A jetzt gehts. 

Danke

**Comment by svdoldie** [comment]
gerne :+1:

**Comment by Karntner** [comment]
Wozu dient die Funktion?

**Comment by Karntner** [comment]
Du scheinst dich da gut aus zu kennen. Hast du ev. einen Tip wie man ein Spiel einträgt das z.B 95 Minuten gedauert hat?

**Comment by Karntner** [comment]
A ich habs. Ich kann in den Spieldetails die Nachspielzeit eingeben

**Comment by svdoldie** [comment]
Wie da die Zusammenhänge sind kann ich dir leider nicht sagen. Aber ich hatte dieses Problem vor Jahren auch schon mal
