### ISSUE TITLE
Filter Saison fehlt in Projektübersicht

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1157]
In der Projektübersicht fehlt mittlerweile der Filter "Saison" 
In dem Zusammenhang wäre es super, wenn im Bereich "aktuelle Saison" bleiben würde, wenn man da in einem Projekt etwas geändert und gespeichert hätte. Momentan wird man zur Projektübersicht geleitet

**Comment by diddipoeler** [comment]
Der Filter ist doch da. Unter Suchwerkzeuge..

**Comment by svdoldie** [comment]
Oh, tatsächlich 🙈 Sorry
Aber 2. Punkt wäre trotzdem super 😉
