### ISSUE TITLE
Neue Person anlegen - Option Nationalität ist doppelt vorhanden

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1158]
Beim Anlegen einer neuen Person wird die Option Nationalität doppelt angezeigt

**Comment by diddipoeler** [comment]
Da ein Spieler 2 Nationalitäten haben kann, gibt es auch 2 Felder.

**Comment by svdoldie** [comment]
Ah, dann schließ ich hier mal 👍
