### ISSUE TITLE
Joomla 4 - Geburtstagmodul verursacht Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1159]
Das aktivieren des Geburtstagmodul erzeugt folgende Fehlermeldung:
0 Call to undefined method Joomla\Database\Mysqli\MysqliDriver::loadResultArray()

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft 👍
