### ISSUE TITLE
Joomla 4 - Backend - Anzeige Teampersons erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1160]
Die Anzeige im Backend der teampersons erzeugt folgende Fehlermeldung: 
500 behavior::framework not found. 

Zudem passiert nichts wenn man auf Spieler zuordnen klickt

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Solange einem Team noch kein Spieler zugeordnet wurde, funktioniert die Anzeige und man kann auch Spieler zuordnen.
Sobald das passiert ist, treten die Probleme erneut auf

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft 👍
