### ISSUE TITLE
Joomla 4 : Teampersons Position zuweisen erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1163]
Unter Joomla 4 erscheint folgende Fehlermeldung wenn man Personen eine Position zugewiesen hat und die Änderungen speichert:
1364 Field 'published' doesn't have a default value 
Außerdem werden keine Buttons bei "sichtbar im Projekt" angezeigt, dementsprechd kann dort auch keine Auswahl getroffen werden.

**Comment by diddipoeler** [comment]
Wo erscheint der Fehler ?
Bei den Playern oder den Teamplayern ?

**Comment by svdoldie** [comment]
Bei den Teamplayern

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Mach ich am Wochenende. Ich muss erst eine neue Testseite aufbauen

**Comment by svdoldie** [comment]
Läuft :+1:
