### ISSUE TITLE
Nach speichern der Vereinsdetails werden in einigen Modulen nur Placeholder angezeigt

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1164]
Speichert man bei einem Verein die Stammdaten wird anschließend in den Modulen Matches und Kalender nur noch Placeholder angezeigt. Im Modul Tabelle wird bei dem Verein gar kein Logo angezeigt. In den normalen Ansichten werden die gespeicherten Logos angezeigt

**Comment by diddipoeler** [comment]
Beispiel ?

**Comment by svdoldie** [comment]
Die Module sind hier zu sehen https://svdoerpum.de 
Als Beispiel einer Ansicht https://www.svdoerpum.de/verein/clubinfo

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft 👍
