### ISSUE TITLE
Wunsch Modul Matches

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1168]
Könnte man hier anstatt Benutze Mannschaften, Benutze Verein programieren. 
Oder ev. beides?

**Comment by sigal** [comment]
Ist es nicht richtig, dass ein Verein aus mehreren Mannschaften bestehen kann?
Diese Auswahl zieht die zugeordneten Mannschaften aus einem Projekt.
Im Projekt werden nicht Vereine, sondern Mannschaften der Vereine zugeordnet.
Oder irre ich mich?

**Comment by Karntner** [comment]
Ja Ein Verein kann aus mehreren Mannschaften bestehen. 

Bei dem Modul ist es so das man alle Projekte auswählen muss und dann noch alle Mannschaften die angezeigt werden sollen. 
Da übersieht man halt leicht eine Mannschaft

**Comment by Karntner** [comment]
@diddipoeler : du bist ja schon wieder fleissig!
