### ISSUE TITLE
Wunsch Ergebnis abfrage

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1170]
Hallo

Ich weis nicht ob es sowas ähnliches irgendwo gibt. Bisher hab ich nichts gefunden. 
Gibt es ein Template oder ein Modul das offene Ergebnisse anzeigt?

z.B wenn das Spieldatum abgelaufen ist aber noch kein Ergebnis oder Absage eingetragen wurde. 

Wäre hilfreich da ich sehr viele Projekte habe.

**Comment by diddipoeler** [comment]
Wo, im Backend oder Frontend ?

**Comment by Karntner** [comment]
Besser wärs im Backend.

**Comment by Karntner** [comment]
Aber eigentlich egal. Was halt einfacher zum umsetzten ist

**Comment by sigal** [comment]
Kartner verwendet kein JSM mehr. Issue schließen?
