### ISSUE TITLE
Template allprojectrounds

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1171]
Hier werden keine Links angezeigt obwohl ich das eingestellt hätte!
![image](https://user-images.githubusercontent.com/59525415/91062527-1ba5f800-e62d-11ea-9f69-8c482a33425d.png)

https://www.union-steinerkirchen.at/index.php/de/mannschaften/kampfmannschaft/alle-spiele-der-2-mw/allprojectrounds

**Comment by diddipoeler** [comment]
Der Kollege @Karntner findet aber auch alles :-)

**Comment by Karntner** [comment]
Nachdem alles super läuft bis jetzt teste ich natürlich auch nach und nach alles durch.

Vl kann ich meine Seite dadurch noch informativer machen.

**Comment by Karntner** [comment]
Super. Funktioniert. 

Tolles Tool! Nur die Ansicht ist net optimal.

Die Startaufstellung gört meiner Ansicht nach gleich unter dem jeweiligen Spiel.
Bei der Startaufstellung würden die Nummern besser passen anstelle der Zeit der Auswechslung.

Und bei den Wechseln wäre es cool wenn Minute des Wechsels und beide Spieler aufscheinen würden. Z.b Spieler A für Spieler B (45.).

![Screenshot_20200825-095909_Chrome.jpg](https://user-images.githubusercontent.com/59525415/91148346-c8c65200-e6b9-11ea-8fec-00526340503c.jpg)


Sonst wie gesagt eine coole Sache!!!

**Comment by diddipoeler** [comment]
Bitte noch einmal testen und im Projekt die Lieblingsmannschaft markieren.

**Comment by Karntner** [comment]
So schauts jetzt aus

![Screenshot_20200825-100849_Chrome.jpg](https://user-images.githubusercontent.com/59525415/91149150-04ade700-e6bb-11ea-873c-e05fdeefe413.jpg)

**Comment by diddipoeler** [comment]
Jetzt müsste schon mal alles unter dem richtigen Spiel stehen.

**Comment by diddipoeler** [comment]
Jetzt mit Trikotnummer.

**Comment by diddipoeler** [comment]
Wechsel vervollständigt.

**Comment by svdoldie** [comment]
Ich habe auch noch einen Wunsch zu dieser Ansicht ;-)
Es sähe besser aus wenn alle Ergebnisse von allen Spieltagen an der selben Position untereinander angezeigt werden würden.
Momentan sind die Spieltag manchmal leicht versetzt, siehe https://www.svdoerpum.de/senioren/1-herren/ligaspielplan/allprojectrounds

**Comment by diddipoeler** [comment]
Jetzt besser ?

**Comment by svdoldie** [comment]
Perfekt 👍 Danke :-)

**Comment by Karntner** [comment]
> Jetzt müsste schon mal alles unter dem richtigen Spiel stehen.

Leider bei mir nicht. Sonst alles Top!

**Comment by diddipoeler** [comment]
Ah, sorry. Du hast die Version mit einer Spalte.
Das muss ich noch umprogrammieren.

**Comment by diddipoeler** [comment]
Sieht es jetzt besser aus ?

**Comment by Karntner** [comment]
Perfekt. DANKE
