### ISSUE TITLE
Spielplan Import

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1172]
Ich habe da eine CSV Datei zum Spielplan importieren. 
Es klappt ganz gut damit. Nur schaffe ich es nicht das ich das richtige Land eintrage. 

Es wird alles mit Deutschland importiert. 

[spielplan import.zip](https://github.com/diddipoeler/sportsmanagement/files/5124542/spielplan.import.zip)

**Comment by diddipoeler** [comment]
Über welche Funktion startest Du den Import ?

**Comment by Karntner** [comment]
Erweitert
DFB Spielplan import

**Comment by Karntner** [comment]
Eine Ergänzung dazu. 

Alle Vereine, Mannschaften, Spielstätten die noch nicht angelegt sind werden mit Deutschland angelegt. 

Die Vorhandenen werden so übernommen wie ich sie angelegt habe.

**Comment by diddipoeler** [comment]
So, jetzt kannst du auch das Land auswählen.
Bitte noch einmal testen.

**Comment by Karntner** [comment]
Super das erspart jede Menge Arbeit!

Danke
