### ISSUE TITLE
Wunsch- Projekt Mannschaft

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1174]
Wäre es möglich das man bei den Projektmannschaften auch den Filter für die Sportstätte anpasst. Ich habe so viele Sportstätten. 
Da sucht man ewig. 

Wäre es möglich das man da noch einen Tab einbaut bei dem man gleich auf den Verein kommt damit man Vereinsnummer, Logo usw anpassen kann.

**Comment by Karntner** [comment]
Aso Das anpassen der Vereinsnummer kann man über die Übersicht.

**Comment by diddipoeler** [comment]
Meinst du bei den Sportstätten die Änderung der Projektmannschaft ?
![Unbenannt](https://user-images.githubusercontent.com/1028107/93179854-8f23bc80-f736-11ea-8a6a-e4bdad15ead5.png)

**Comment by Karntner** [comment]
Hallo Didi. Ja genau

**Comment by diddipoeler** [comment]
Bitte einmal testen.

**Comment by Karntner** [comment]
Super. Danke
