### ISSUE TITLE
Wunsch - Bilder einfügen

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1175]
Könnte man beim zuordnen der Bilder gleich einen Link bei der Übersicht einbauen?

![image](https://user-images.githubusercontent.com/59525415/91633002-34276100-e9e5-11ea-8ff4-c7b01744bc80.png)

![image](https://user-images.githubusercontent.com/59525415/91633018-4bfee500-e9e5-11ea-8313-d1f40b7f9771.png)

![image](https://user-images.githubusercontent.com/59525415/91633039-76e93900-e9e5-11ea-8b52-7142742313c5.png)

**Comment by diddipoeler** [comment]
Verstehe ich jetzt nicht so ganz.

**Comment by Karntner** [comment]
OK: Ich meinte ob man da drunter gleich einen Link zum Vereinswappen setzen kann damit man direkt rein kann. 
Bei mir wäre das der Link.  https://union-steinerkirchen.at/administrator/index.php?option=com_sportsmanagement&view=club&layout=edit&id=459

Bei den Personen halt der jeweilige wo man das Bild einfügen kann.

**Comment by Karntner** [comment]
Ich hab gerade gemerkt der geht nicht direkt. Da kommt man wieder zu den Tabs. Dann bringt es nichts

**Comment by diddipoeler** [comment]
Das ist ein komplizierter Wunsch.

**Comment by Karntner** [comment]
Muss auch net sein wenn es zu aufwendig ist. Wenn man es einmal drinnen hat gehts eigentlich. 
Mach dir keine Mühe wegen dem

**Comment by diddipoeler** [comment]
Gib mir bitte ein wenig Zeit für diese Herausforderung.

**Comment by Karntner** [comment]
Sicher! Absolut kein Problem!

**Comment by diddipoeler** [comment]
Bitte mit Vorsicht testen.

**Comment by Karntner** [comment]
Leider bleib ich hier hängen. 

![image](https://user-images.githubusercontent.com/59525415/91897621-d6bc3a00-ec9a-11ea-8f8e-22f8a014d35f.png)

**Comment by sigal** [comment]
bei mir gehts (joomla oder sportsmanagement als image-tool)

![#1175](https://user-images.githubusercontent.com/5115688/91903701-f73cc200-eca3-11ea-9881-5e123794f23b.jpg)

**Comment by Karntner** [comment]
Ich habe beide Einstellungen versucht. Bei allen beiden habe ich das selbe Problem.

**Comment by Karntner** [comment]
Aber ich hab auch grad Festgestellt das da bei mir bei den Personen was nicht stimmt.
Wenn ich eine neue Person anlege dann funktioniert es. 
Ich muss mir das genauer ansehen.

**Comment by svdoldie** [comment]
Bei mir werden ebenfalls die Bilder angezeigt, aber bei mir wird auch keine Ordnernavigation angezeigt.
Sowohl bei joomla oder sportsmanagement als image-tool

**Comment by diddipoeler** [comment]
Es gibt auch keine Ordnernavigation, da die Bilder aufgrund ihrer Views bereits in den
richtigen Ordner vorhanden und angezeigt werden.

**Comment by svdoldie** [comment]
ok, dann hab ich da etwas falsch verstanden

**Comment by Karntner** [comment]
Ich habe den Fehler bei mir gefunden. 

Wenn ich mehr als eine Person in der Suche angezeigt habe dann funktioniert es nicht.

Wenn ich nach einer Person Filtere dann funktioniert es.

**Comment by Karntner** [comment]
Die Suchwerkzeuge funktionieren bei mir nicht mehr.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Kartner verwendet kein JSM mehr. Issue schließen?
