### ISSUE TITLE
Wunsch: Ereignisse des Gegners ohne Person im Spielbericht anzeigen

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1176]
Es wäre super, wenn die Ereignisse des Gegners, sich nicht nur ohne Person speichern ließen,
sondern auch im Spielbericht angezeigt werden würden.
![Screen Capture_20200830094818](https://user-images.githubusercontent.com/2417767/91654039-12da7980-eaa6-11ea-9de8-8854616f46e1.png)
![Screen Capture_20200830094833](https://user-images.githubusercontent.com/2417767/91654040-140ba680-eaa6-11ea-8e5b-75805044e92a.png)

**Comment by diddipoeler** [comment]
Meinst Du den Foulelfmeter ?

**Comment by svdoldie** [comment]
Ja genau



Gesendet mit BlueMail

**Comment by Karntner** [comment]
Ja das wäre eine Coole Sache!

**Comment by ortwin20000** [comment]
Bitte noch einmal testen. Ich habe hier letztens Änderungen gemacht.

**Comment by svdoldie** [comment]
Prima, das klappt super 👍 👍 👍 
Das macht vieles einfacher!!!

**Comment by svdoldie** [comment]
Ich mach doch noch mal auf. Keine Ahnung, ob das mit deinen Änderungen zusammenhängt,
aber man kann Einträge nicht mehr löschen

**Comment by svdoldie** [comment]
Kleine Korrektur. Wenn man das Modalfenster schließt und anschließend wieder öffnet,
können die Einträge auch wieder gelöscht werden

**Comment by ortwin20000** [comment]
Ist das im Backend oder Frontend?

**Comment by svdoldie** [comment]
Im Backend

**Comment by ortwin20000** [comment]
Bitte nach dem Pull-Request noch einmal testen.
