### ISSUE TITLE
Wunsch Spielfeld

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1177]
Kann man das so einstellen das der Nachname unter dem Bild angezeigt wird?
So schauts nicht ganz so schön aus!

![image](https://user-images.githubusercontent.com/59525415/91654907-158c9d00-eaad-11ea-9399-f8d2994e5567.png)

**Comment by diddipoeler** [comment]
Bitte mal testen.

**Comment by Karntner** [comment]
Danke @diddipoeler für die rasche Erledigung : Schaut super aus!
