### ISSUE TITLE
Teampersons werden nicht angezeigt

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1178]
Bei mir werden in neuen Projekten die Teampersons nicht angezeigt,
weder im Backend noch in der Kaderansicht im Frontend.
Im Spielbericht werden sie angezeigt. Die Zuordnung folgte zum Teil über den Presseberichtimport, 
als auch über die Zuordnungsfunktion des Backends

**Comment by diddipoeler** [comment]
Vielleicht mal ein Beispiellink zu der Mannschaft und das Jahr/Liga !

**Comment by svdoldie** [comment]
Das Problem hängt wohl mit dem Pressebericht zusammen. Ich habe jetzt mal in einem anderen Projekt eine Person auf dem üblichen Weg zugewiesen. Dann klappt alles reibungslos. Wenn ich dagegen den Pressebericht nutze, um neue Spieler anzulegen, werden anschließend auch auf üblichen Weg zugewiesene Personen nicht im Backend angezeigt. Im Frontend dagegen schon.

Meine Zugangsdaten für meine Seite müsstest du noch haben. Der Link zur Frontendansicht ist https://www.svdoerpum.de/senioren/1-herren/roster

Hier noch ein paar Bilder dazu
![Screen Capture_20200830170135](https://user-images.githubusercontent.com/2417767/91662414-8d28ef00-eae2-11ea-9ac6-237c638656fb.png)
![Screen Capture_20200830170155](https://user-images.githubusercontent.com/2417767/91662416-8e5a1c00-eae2-11ea-89ba-8609384480b5.png)
![Screen Capture_20200830170159](https://user-images.githubusercontent.com/2417767/91662417-8ef2b280-eae2-11ea-8e14-15ca7c8a4529.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Test bestanden!

**Comment by svdoldie** [comment]
Kann ich nicht bestätigen. Bei mir werden in einem Projekt in dem z.B. unsere 1 .Mannschaft vertreten ist, die Personen angezeigt,
im anderen nicht.

**Comment by sigal** [comment]
Wurden diese Personen auf dem üblichen Weg. oder über den Pressebericht zugewiesen?
Mit Pressebericht kann ich leider nicht testen.
Auf üblichen Weg hab ich in 3 Projekte Spieler hinzugefügt und alle werden im BE angezeigt.

**Comment by svdoldie** [comment]
Alle mit dem Pressebericht. Vielleicht ist das der entscheidende Hinweis..

⁣BlueMail for Android herunterladen ​

**Comment by Karntner** [comment]
Hallo

Ich habe jetzt lange keine Zeit gehabt. Ich kann noch immer keine Spieler in den Kader einfügen

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Bei mir ist es immer noch so, dass bei einer Mannschaft, die mehreren Projekten in einer Saison zugewiesen wurden,
in einem Projekt die Spieler im Backend angezeigt werden, im anderen nicht.
In beiden Projekten werden in der Teamübersicht des Projektes die Anzahl der der zugewiesenden Personen richtig angezeigt.
Im Frontend werden in der Kaderansicht bei dem Projekt, in dem die Personen auch im Backend anzeigt werden, alle Personen angezeigt. Im anderen Projekt, wo die Personen im Backend nicht angezeigt werden, nur teilweise. 
Ziemlich kurios..
Link zum vollständigen Kader https://www.svdoerpum.de/index.php/senioren/1-herren/teaminfo/roster/0/8/74:verbandsliga-nord-2020-2021/13:sv-doerpum/1040
Link zum unvollständigen Kader https://www.svdoerpum.de/index.php/senioren/1-herren/teaminfo/roster/0/8/72:kreispokal-2020-2021/13:sv-doerpum/951

**Comment by svdoldie** [comment]
läuft jetzt 👍
