### ISSUE TITLE
Projektmannschaft - Spielerzuweisung - Fehler, wenn Spieler bereits in anderer Mannschaft

### ISSUE THREAD

**Issue by Tobsen84** [diddipoeler/sportsmanagement#1179]
Hallo zusammen,

bei uns steht aktuell der Pokal an, wobei unsere Erste als auch Zweite im selben Pokal spielen (also im selben Projekt). Jetzt wollte ich einen Mannschaftskollegen der Ersten Mannschaft zuordnen, welcher letzte Woche schon für die Zweite im Einsatz war und somit nun bei mehreren Mannschaften in einem Projekt zugewiesen werden soll. Dabei erhalte ich allerdings eine Fehlermeldung (siehe Screenshot). Das hatte letzte Saison noch funktioniert. Bei Neuzuweisung von Kollegen, welche noch keiner Mannschaft zugewiesen wurden, funktioniert es ohne Probleme.

Gruß
Tobsen
![Projektmannschaft - Spieler zuordnen](https://user-images.githubusercontent.com/61277544/91667990-ed328c00-eb08-11ea-9765-242321362458.PNG)

**Comment by diddipoeler** [comment]
Schalte mal bitte in der Konfiguration von Joomla den Debugmodus ein.
Dann starte die Zuordnung noch einmal. Es wird dann auch die Datei mit der Zeile des Fehlers angezeigt.
Ist für mich einfacher.

**Comment by diddipoeler** [comment]
Konnte es nachstellen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by diddipoeler** [comment]
Und bitte hier: https://extensions.joomla.org/extension/sports-management/ einen Kommentar eintragen.

**Comment by Tobsen84** [comment]
Vielen Dank für den Fix. Jetzt funktioniert es wieder. Danke.

PS: Bezüglich einer Bewertung der Komponente werde ich mich demnächst mal in Ruhe mit beschäftigen. :-)
