### ISSUE TITLE
BFV ICalc Datei

Kann man den BFV Ical import auch auf den ÖFB anwenden.

Der bietet auch so was an. 

Bei mir kommt da allerdings immer folgender Fehler:
Es ist ein Fehler aufgetreten!0 Call to undefined function split() 
Zurück zum Kontrollzentrum


Den Link habe ich versucht!

www.ofv.at/datenservice/icalendar/downlo...height=330&width=500



### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1180]

**Comment by Karntner** [comment]
Jetzt funktioniert es. Danke

**Comment by Karntner** [comment]
Sorry @diddipoeler : Ich habe gerade gemerkt das das Datum und die Uhrzeit nicht importiert wird.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Karntner** [comment]
Schaut gut aus. Könnte man das Feld freigeben wenn eine neue Mannschaft angelegt werden muss beim import. 

Ich muss oft nur das Kürzel für eine NW Mannschaft hinzufügen. Z.b U15

**Comment by diddipoeler** [comment]
Oh, welches Feld ?

**Comment by Karntner** [comment]
Wenn ich ein Projekt importiere wäre es cool wenn man den Mannschaftsnamen ändern könnte wenn sowieso eine neue Mannschaft erstellt werden muss. 
Beim Spielort funktioniert das.  Den kann man umschreiben. 

![image](https://user-images.githubusercontent.com/59525415/92108963-7b985d80-ede8-11ea-8486-ccb63ddf3e92.png)

![image](https://user-images.githubusercontent.com/59525415/92109064-a97da200-ede8-11ea-8859-3bb26268f55a.png)

**Comment by Karntner** [comment]
Hab gerade auch noch festgestellt das die Spieltage falsch importiert werden.

**Comment by diddipoeler** [comment]
Für die Spieltage muss ich mir was ausdenken.

**Comment by Karntner** [comment]
Ja weil die werden mitten im Text in einer Klammer ausgeben. Das wird sicher net einfach

**Comment by diddipoeler** [comment]
Bitte einmal die Runden testen.

**Comment by Karntner** [comment]
Schaut gut aus

**Comment by Karntner** [comment]
So ein sch..... Jetzt stimmt die Uhrzeit wieder nicht.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Karntner** [comment]
Danke jetzt dürfte alles passen
