### ISSUE TITLE
Spielbericht - Bereich Informationen - Zuschauerdarstellung fehlerhaft

### ISSUE THREAD

**Issue by Tobsen84** [diddipoeler/sportsmanagement#1181]
Hallo zusammen,

im Spielbericht werden im Bereich "Informationen" der Abschnitt der Zuschauer etwas fehlerhaft dargestellt. Der Doppelpunkt, welcher direkt nach der Bezeichnung "Zuschauer" fett dargestellt werden müsste, ist zum einen nicht fett dargestellt und zum anderen beim eigentlichen Wert dargestellt. Dies sollte sicherlich analog der zu den anderen Angaben dargestellt werden.

![Spielbericht - Informationen - Zuschauer](https://user-images.githubusercontent.com/61277544/92030767-d047c400-ed67-11ea-9ca8-85524d65afa1.PNG)

Gruß
Tobsen

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Tobsen84** [comment]
Vielen Dank für den schnellen Fix. Jetzt passt es und wird analog zu den anderen Angaben dargestellt.
