### ISSUE TITLE
Wunsch Mannschaften

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1183]
Könnte man bei der Mannschaftsübersicht im Backend eine Suche nach Land und Altersgruppe einbauen?

**Comment by diddipoeler** [comment]
Also im View Teams ?

**Comment by Karntner** [comment]
Ja hier

![image](https://user-images.githubusercontent.com/59525415/92222379-397e2300-ee9f-11ea-9b19-7e82e48bb293.png)

**Comment by diddipoeler** [comment]
Bitte einmal testen

**Comment by Karntner** [comment]
Super! Funktioniert. 

Vl könnte man das Dropdownfeld noch ein wenig breiter machen. Sonst schauts super aus. 

Danke
![image](https://user-images.githubusercontent.com/59525415/92226805-97156e00-eea5-11ea-8b3e-9651e65af8d0.png)
