### ISSUE TITLE
New fields for persons/players profile and playgrounds

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#1185]
is it possble add linkedin and instagram fields to player profile?

is it possible add playground size to playground profile?? For soccer, not all playgrounds have the same size

**Comment by diddipoeler** [comment]
Die neuen Felder mache ich am nächsten Wochenende. Bin 6 Tage im Urlaub.
Ok ?

**Comment by diddipoeler** [comment]
Die neuen Felder mache ich am nächsten Wochenende. Bin 6 Tage im Urlaub.
Ok ?

**Comment by diddipoeler** [comment]
Reicht für die Sportplätze ein einfaches Textfeld ?

**Comment by llambion72** [comment]
Yes, it is for write dimensions such as 105x68 or similar.

**Comment by diddipoeler** [comment]
Felder sind jetzt vorhanden.

**Comment by llambion72** [comment]
I'll try it at the end of week. Now i'm migrating my server os/harware... I expect to finish before friday

**Comment by llambion72** [comment]
After a long time disconnected, i come back.
All fields work perfect!!
Thank you!
