### ISSUE TITLE
Teams ranking module

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#1186]
it is possible add an option to show t-shirt image instead of team logo?

**Comment by llambion72** [comment]
I've started to add this

**Comment by diddipoeler** [comment]
Ist das jetzt erledigt ?

**Comment by svdoldie** [comment]
Ich weiß nicht ob das an den Änderungen zum Issue liegt, 
aber bei bei mir stehen alle Teams an 1. Stelle im Modul,
siehe https://www.svdoerpum.de/
Bitte nicht die 1. Herren nehmen, da ist schon die neue Saison konfiguriert

**Comment by sigal** [comment]
Von mir aus ist das jetzt erledigt. Waren ja nur 2 Dateien vertauscht.
Und auch diddis Seite zeigt das Modul mit den richtigen Zahlen der Ränge.
Bei mir auch: https://demo.jsm-help.de/

**Comment by llambion72** [comment]
I don't understand what is the problem. I don't speak german and i use a translator to translate the conversation but it is not clear to me what the problem is

**Comment by sigal** [comment]
![#1186](https://user-images.githubusercontent.com/5115688/93139897-d6339280-f6e1-11ea-941d-11a58b3c1e19.jpg)

I cleaned it up as there were a lot of error messages.
See #1188

**Comment by llambion72** [comment]
Ok, thank you for your response.
