### ISSUE TITLE
Mehrere Fehlermeldungen innerhalb der Projekte

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#1188]
Bei der Auswahl Projekt Einstellungen erscheint folgende Fehlermeldung
![image](https://user-images.githubusercontent.com/9608697/92312289-9e309f00-efbf-11ea-95ab-c0dffc63cea6.png)

Bei der Auswahl der Projekt Mannschaften
![image](https://user-images.githubusercontent.com/9608697/92312308-cae4b680-efbf-11ea-9e17-1552c270076e.png)

Bei der Auswahl "Spiele bearbeiten
![image](https://user-images.githubusercontent.com/9608697/92312331-f1a2ed00-efbf-11ea-9ad0-789beda24cb7.png)

**Comment by diddipoeler** [comment]
Bitte in der Konfiguration von Joomla den Debugmodus einstellen.
Dann die Funktionen einzeln starten. Es werden dann die Dateien mit den
Fehlern und Zeilennummern angezeigt. Die benötige ich.

**Comment by PhantoSGE** [comment]
Projekt Einstellungen 

![image](https://user-images.githubusercontent.com/9608697/92324635-e09bbf80-f043-11ea-9e07-4b28fa28abe0.png)

**Comment by PhantoSGE** [comment]
Spiele bearbeiten

![image](https://user-images.githubusercontent.com/9608697/92324638-f14c3580-f043-11ea-90ae-4eb9d6b75466.png)

**Comment by PhantoSGE** [comment]
Auswahl Mannschaften

![image](https://user-images.githubusercontent.com/9608697/92324645-04f79c00-f044-11ea-833d-f9f0b5558a7c.png)

**Comment by Karntner** [comment]
Ja bei mir ist es das selbe Problem

**Comment by sigal** [comment]
Wie schon oben beschrieben, würde eine Datei beim letzten Pull request von @llambion72 in das falsche Verzeichnis geschrieben.

**Comment by Karntner** [comment]
Sorry @sigal . Ich steh grad voll auf der Leitung. 

Muss ich was tun oder abwarten bis ein update kommt?

**Comment by sigal** [comment]
Ich schreibe gerade einen Pull request. Musst warten bis diddi ihn einpflegt, dann ein GitHub Update machen.
Ok

**Comment by Karntner** [comment]
Danke @sigal : Alles klar!

**Comment by diddipoeler** [comment]
Sorry das es so lange gedauert hat. Bin gerade für 6 Tage im Urlaub.

**Comment by PhantoSGE** [comment]
Sieht gut aus :-)
Danke das du dich in deinem Urlaub drum gekümmert hast und einen schönen, erholsamen Urlaub noch,
