### ISSUE TITLE
Kader

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1189]
Bei mir sind alle Spieler im Kader weg.

Ich kann sie zwar wieder einfügen aber dann ist die Ansicht leer.

![image](https://user-images.githubusercontent.com/59525415/92333468-021d9b00-f086-11ea-8e52-6eed334c823c.png)

![image](https://user-images.githubusercontent.com/59525415/92333474-0ea1f380-f086-11ea-9dd9-3fad298156c8.png)

**Comment by sigal** [comment]
Issue schon eröffnet #1178

**Comment by Karntner** [comment]
Danke dann mach ich den wieder zu
