### ISSUE TITLE
Tippspiel - Fehler nach nochmaligen Speichern von Tipps

### ISSUE THREAD

**Issue by tmplify** [diddipoeler/sportsmanagement#1191]
Nachdem man Tipps vorher einmal gespeichert hat und danach nochmals speichert (weil man evtl. etwas verändert hat) wird einem ein Fehler angezeigt:
Fehler
sportsmanagementModelPredictionEntry::savePredictions 446 Duplicate entry '12-131-20-447' for key 'result'
sportsmanagementModelPredictionEntry::savePredictions 447 1062

Das Problem liegt in der \components\com_sportsmanagement\models\predictionentry.php. In Zeile 442 wird versucht in eine Tabelle zu schreiben, obwohl der Eintrag schon existiert:

		try
		{
			$resultquery = Factory::getDbo()->insertObject('#__sportsmanagement_prediction_result_round', $temp);
		}
		catch (Exception $e)
		{
			$app->enqueueMessage(Text::_(__METHOD__ . ' ' . __LINE__ . ' ' . $e->getMessage()), 'error');
			$app->enqueueMessage(Text::_(__METHOD__ . ' ' . __LINE__ . ' ' . $e->getCode()), 'error');
		}

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by tmplify** [comment]
Hallo Diddi,
danke dir fürs Kümmern. Jetzt wird mir folgendes angezeigt:
Hinweis

DB-Funktion mit Fehlercode 1064 fehlgeschlagen!
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `penalties` = , `yellow_cards` = , `yellow_red_cards` = , `red_cards` = ' at line 3


In Zeile 446 ist der Inhalt von $this->jsmquery folgender:

> UPDATE `jos_sportsmanagement_prediction_result_round`
SET `goals` = 
	, `penalties` =  
	, `yellow_cards` = 
	, `yellow_red_cards` = 
	, `red_cards` = 
	, `modified` = '2020-09-12 11:22:55'
	, `modified_by`=131
WHERE `prediction_id` = 12 AND `user_id` = 131 AND `project_id` = 20 AND `round_id` = 447

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by tmplify** [comment]
Keine Fehlermeldung mehr! Danke dir Diddi!  :-)
