### ISSUE TITLE
Kaderübersicht - Positionsreihenfolge unterschiedlich

### ISSUE THREAD

**Issue by Tobsen84** [diddipoeler/sportsmanagement#1196]
Hallo zusammen,

wir haben aktuell das Problem, dass die Reihenfolge der Positionen (Torwart, Verteidiger usw.) sich bei den einzelnen Kadern unterscheidet. Die Kaderreihenfolge bei unserer 1. Mannschaft und den Alten Herren passt:

![Kader (Alte Herren)](https://user-images.githubusercontent.com/61277544/93932678-d86ca100-fd20-11ea-9814-003264613216.PNG)

Bei der zweiten Mannschaft ist diese allerdings alles andere als passend:

![Kader (2 Mannschaft)](https://user-images.githubusercontent.com/61277544/93932744-efab8e80-fd20-11ea-8110-161e43b556cb.PNG)

In den Stammdaten haben wir die Reihenfolge der Positionen meines Erachtens korrekt definiert. Komisch ist halt, dass es sich von Kader zu Kader unterscheidet.

Kann/Muss man die Reihenfolge der Positionen noch für jedes Projekt separat irgendwo einstellen? Bei der Zuteilung, welche Positionen in dem Projekt verwendet wird, spielt meines Erachtens die Reihenfolge der Zuordnung keine Rolle, da er diese danach eh alphabetisch ordnet.

Wäre super, wenn uns jemand bei dem Problem helfen könnte.

Viele Grüße
Tobsen84

**Comment by svdoldie** [comment]
Ich kann das Problem bestätigen. Allerdings triitt der Fehler nur in der Standardansicht auf, in den anderen beiden Ansichten ist die Reihenfolge korrekt

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Bei mir stimmt es jetzt 👍

**Comment by Tobsen84** [comment]
Jetzt sieht es auch bei mir gut aus. Vielen Dank Diddi :-)

Issue wird geschlossen.
