### ISSUE TITLE
Projekt - Mastertemplate - Trotz Auswahl einer älteren Saison existieren unabhängige Frontend-Templates

### ISSUE THREAD

**Issue by Tobsen84** [diddipoeler/sportsmanagement#1197]
Hallo zusammen,

wir haben bei allen Projekten der aktuellen Saison als Mastertemplate eine Saison aus den vergangenen Jahren definiert:

![Projekte 2020-2021 (Mastertemplate)](https://user-images.githubusercontent.com/61277544/93933479-069eb080-fd22-11ea-837a-a17264115903.PNG)

Gehe ich jetzt z.B. in das Projekt unserer zweiten Mannschaft und gehe in den Frontend Einstellungen, werden mir die einzelnen Templates mit Templatetyp "Master Template" wiedergegeben, was meines Erachtens korrekt ist und sich somit Änderungen an den Templates auch auf die Saison des Mastertemplates auswirken.

![20-21 - Kreisklasse](https://user-images.githubusercontent.com/61277544/93933837-8a589d00-fd22-11ea-9f2e-f65331a7b18e.PNG)

Gehe ist jetzt allerdings in das Projekt unserer ersten Mannschaft und dort in die Frontend Einstellungen, werden mir die einzelnen Templates mit Template "Unabhängiges Template" wiedergegeben. Somit zieht er sich nicht die bereits getätigten Einstellungen aus der entsprechenden Saison und man muss alles neu einstellen.

![20-21 - Kreisoberliga](https://user-images.githubusercontent.com/61277544/93933990-c986ee00-fd22-11ea-9a9b-532d6a04be16.PNG)

Ich muss ehrlich zugeben, dass ich die ganze Logik mit den Mastertemplates sowie den einzelnen Frontend Templates noch nicht wirklich durchdrungen habe. Daher hoffe ich, dass ich hier nicht vollkommenden Müll erzähle. Über etwas Aufklärung wäre ich sehr dankbar und würde zumindest gern verstehen, warum das Verhalten bei den einzelnen Projekten unterschiedlich ist.

**Comment by svdoldie** [comment]
Ich habe mal ein Bild von meinen Projekten hochgeladen, vielleicht wird es damit deutlich.
Es müssen in einem Projekt die Einstellungen in den templates vorgenommen werden,
und diese Templates kann man dann in einem anderen Projekt als Mastertemplate nutzen.
In meinem Fall dienen die Templates aus dem Projekt Kreisliga 2016/17 als Mastertemplates. 
![mastertemplate](https://user-images.githubusercontent.com/2417767/93974136-ad606c80-fd75-11ea-9c8e-79cfdbd27322.png)

**Comment by sigal** [comment]
Hallo,
wenn im Projekt erstmals kein Mastertemplate gewählt wurde, das Projekt gespeichert wurde und später ein Mastertemplate gewählt wurde, Projekt wieder gespeichert, werden wie geschildert die unabhängigen Templates auch angezeigt.

Abhilfe schafft die komplette Löschung aller unabhängigen Templates (in Farbe GRÜN). Geschieht das, werden auch die Mastertemplates (in Farbe ROT) angezeigt und für das Projekt verwendbar.

Alle Mastertemplates können in unabhängige Templates überschrieben werden. Dazu das Wahlfeld "- Master-Design-Vorlage zum Überschreiben wählen -" benutzen und ein Template wählen. Nun kann das Template individuell angepasst werden.
Dieses angepasste Template steht nun nur in diesem Projekt zur Verfügung.

**Vorsicht:** Wird ein Mastertemplate (Schriftfarbe ROT) in einem Projekt geöfnet und verändert, wirkt sich das auf alle Projekte aus, die dieses Mastertemplate verwenden.

**Comment by Tobsen84** [comment]
Hallo zusammen,

vielen Dank für die Infos. Das hilft mir definitiv weiter (um die Logik zu verstehen). Bei dem Projekt der Altherren haben wir bereits beim Import das entspr. Mastertemplate gewählt, bei den Projekten der ersten und zweiten Mannschaft erst im Nachhinein. Mir ist auch nicht bewusst, dass ich bei der zweiten Mannschaft dann die unabhängigen Templates gelöscht hätte. Daher meine Verwunderung, warum das Verhalten anders als bei der ersten Mannschaft ist. Aber am Ende auch egal, da ich nun weiß, wie ich aus unabhängigen Templates die Mastertemplates erzeuge. Vielen Dank dafür.

Ein paar Fragen hätte ich dann allerdings noch:

1) Was passiert denn, wenn man kein Mastertemplate definiert und dann eines der unabhängigen Templates löscht?
2) Was passiert denn, wenn man bei Verwendung eines Mastertemplates zuerst das unabhängige Frontend-Template löscht und danach versucht, dass nun sichtbare Frontend-Mastertemplate zu löschen?

Beide Varianten könnte man natürlich per Variante "Try & Error" probieren aber das wollte ich dann lieber nicht riskieren ;-)

3) Ist es dann z.B. beim nächsten Projekt möglich, die Saison 20/21 als Mastertemplate auszuwählen oder funktioniert das nicht, da hier ja bereits eine andere Saison als Mastertemplate definiert ist?
4) Folgendes Szenario: Wenn ich mir gern ein Standard-Mastertemplate anlegen wöllte, wobei ich dann die ganzen Frontend-Einstellungen einmal mache und dies dann für alle passenden Projekte benutze würde. -> Würde dies funktionieren, wenn ich mir sozuzagen ein Pseudo-Projekt anlege, dort lediglich die Frontendeinstellungen mache und dann das Projekt ausblende, da es ja keine andere Funktion hat?

Sorry für meine vielen (bestimmt teilweise dummen) Fragen. Würde nur gern das ganze System und vorallem die vielen Möglichkeiten verstehen, um die Sachen effektiv anzuwenden.

Vielen Dank im Voraus und nette Grüße
Tobsen84

**Comment by sigal** [comment]
Hallo,
es gibt jetzt schon wieder ein Missverständnis.
Aus unabhängigen Templates kann man kein Mastertemplate erzeugen, sondern die Templates eines Projekts können für andere Projekte als Mastertemplate gewählt werden.

Man kann daher mit einem Projektdesign unendlich viele Projekte mit diesem 1. Design (ich nenn es hier Master) anlegen.

Zu 1) Zurück zu den Projekteinstellungen->Details Mastertemplate -> Projekt auswählen und speichern.

Zu 2) Viel Arbeitszeit vernichtet. Mastertemplate löscht man nur, wenn es nie mehr gebraucht wird.

Zu 3) Saison ist nicht maßgebend. Das auswählen eines Projekts, unabhängig der Saison importiert die Templates dieses Projekts als Mastertemplates.

Zu 4) Dies ist die richtige Vorgangsweise.

Zum Schluss noch folgendes. Jedes neue Projekt importiert schon in JSM integrierte Templates in das Projekt. 
Praktisch sind diese Templates (in Deutsch Designvorlagen) schon in gewissen Sinn Mastertemplates die vom User angepasst und für andere Projekte verwendet werden können.








M

**Comment by Tobsen84** [comment]
Hallo Stony,

da hab ich mich wohl etwas ungenau ausgedrückt. Bzgl. dem Thema "Unabhängige Templates zu Mastertemplates machen" hatte ich mich auf deinen Part:

Abhilfe schafft die komplette Löschung aller unabhängigen Templates (in Farbe GRÜN). Geschieht das, werden auch die Mastertemplates (in Farbe ROT) angezeigt und für das Projekt verwendbar.

bezogen. Das war mir bisher nicht bewusst und hab es bereits ausprobiert und kann es bestätigen ;-)

Eine Frage hätte ich zum Abschluss noch. In den Projekteinstellungen kann man so Sachen definieren wie Spielzeit, allg. Startzeit der Spieltage, Verlängerung möglich, Dauer der Verlängerung usw. Diese Angaben muss ich pro erstelltes Projekt immer neu einstellen oder kann man das auch über Templates etc. mitgeben?

Hintergrund der Frage: Bei uns ist es so, dass z.b. die alten Herren nur 80 Minuten spielen statt 90 Minuten oder halt bei einem Pokal eine Verlängerung möglich ist, was bei einer normalen Liga nicht der Fall ist. Darum wäre es interessant, ob man solche spezifischen Sachen auch aufgrund diverser Voreinstellungen mitgeben kann oder solche Sachen dann pro neues Projekt explizit definiert werden muss?

Viele Grüße
Tobsen84

**Comment by sigal** [comment]
Hallo,

freut mich, dass meine Ausführungen stimmen.

Zur Frage unteschiedliche Spielzeit: 

Die angesprochenen Angaben (Spielzeit etc.) müssen bei jeden (neuen) Projekt in den Projekteinstellungen hinterlegt werden.

Gruß
stony

PS: Für normale Themen wie dieses in Zukunft das Forum benutzen. Danke

**Comment by Tobsen84** [comment]
Hallo,

nochmals vielen Dank für die Infos. Jetzt dürfte ich es soweit verstanden haben. ;-)

PS: Hatte auch erst überlegt, das Thema im Forum zu eröffnen, war mir allerdings nicht sicher, ob vielleicht ein wirkliches Issue vorliegt. Aber geb dir Recht, dass solche Themen erstmal besser im Forum aufgehoben sind.
