### ISSUE TITLE
Backend: Änderung bei einer Teamperson führt zur Nichtanzeige im Kader

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1199]
Ändert man bei einer Teamperson etwas, z.B. das Foto des Spielers,
wird nach dem Speichern der Status "Sichtbar im Projekt" auf Nein gestellt
und die Person wird in der Kaderansicht im Frontend nicht mehr angezeigt.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Der Fehler ist nicht mehr vorhanden :+1:
