### ISSUE TITLE
Spieler einer Projektmannschaft - Bild leeren funktioniert nicht

### ISSUE THREAD

**Issue by Tobsen84** [diddipoeler/sportsmanagement#1200]
Hallo zusammen,

wenn man bei einem Spieler im Menü der Mannschaftszuordnung eines Projektes beim Bild auf "Leeren" klickt wird kein Placeholder ausgewählt sondern dort wo das Bild dargestellt wird, steht dann Preview und das Feld, wo vorher der Pfad angezeigt wurde, ist leer. Siehe:

![Mannschaftsspieler - Bild Leeren](https://user-images.githubusercontent.com/61277544/94193160-485d6180-feb0-11ea-8ef9-511914e190aa.PNG)

Wenn man jetzt versucht zu speichern, wird nix übernommen und der Ursprungszustand ist wieder vorhanden.

PS: Das gleiche Prozedere in den Stammdaten unter "Personen" ausgeführt funktioniert korrekt.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Tobsen84** [comment]
Funktioniert leider noch nicht komplett. Wenn ich jetzt auf "Leeren" klicke wird zwar der Placeholder angezeigt und auch der Pfad steht im Feld drin aber das Speichern wird nicht übernommen. Nach dem Speichern ist weiterhin das Bild des Spielers hinterlegt, welches vor dem Leeren ausgewählt war.

**Comment by diddipoeler** [comment]
Den Fehler kann ich nicht nachvollziehen.
Bei mir läuft es so wie es soll.

**Comment by Tobsen84** [comment]
Hallo Diddi,

das ist ja komisch. Bei mir klappt es aber weiterhin nicht. Hab mal ein PDF mit ein paar Bildern angehangen.

Bild 1: Zum Teamplayer - Reiter "Bild" - navigiert (Pfad des Fotos passt zur Auswahl)
Bild 2: Bild geleert - Pfad des Fotos ist der Platzhalter
Bild 3: Gespeichert - Man befindet sich wieder auf dem Reiter "Details" des Spielers - Bestätigung des Speicherns wird angezeigt
Bild 4: Wieder zum Reiter "Bild" navigiert und man sieht weiterhin das originale Bild

[Teamplayers - Bild leeren.pdf](https://github.com/diddipoeler/sportsmanagement/files/5321338/Teamplayers.-.Bild.leeren.pdf)

**Comment by diddipoeler** [comment]
Bitte mir mal die kompletten SuperAdmin Daten zur Verfügung stellen.
Muss mir das anschauen.

**Comment by Tobsen84** [comment]
Hab dir einen SuperAdmin-Zugang eingerichtet und die Daten per Mail an deine GMX-Adresse (diddipoeler@gmx.de) geschickt.

**Comment by diddipoeler** [comment]
Jetzt funktioniert es.

**Comment by Tobsen84** [comment]
Also ich habe keine Ahnung, was du anders machst als ich aber bei mir funktioniert es weiterhin nicht. Er übernimmt einfach nicht den Placeholder. Bei den Stammdaten (Personen) klappt es.

PS: Was hast du denn geändert, das es jetzt funktionieren sollte.

**Comment by diddipoeler** [comment]
Bei welchem Projekt hast du es versucht, wo es nicht funktionieren sollte ?

**Comment by Tobsen84** [comment]
Bei mehreren. Also aus der aktuellen Saison bei allen drei Ligaprojekten. Klappt bei mir nirgends.

**Comment by diddipoeler** [comment]
Habe jetzt alle Kader in der aktuellen Saison korrigiert.
Müsste jetzt funktionieren. Habe ich gerade getestet.

**Comment by Tobsen84** [comment]
Sorry aber ich bekomm es einfach nicht hin. Bei mir klappt es weiterhin nicht. Hab es eben nochmal bei den drei Ligaprojekten aus der aktuellen Saison probiert.

**Comment by diddipoeler** [comment]
So, welcher Spieler soll welches Bild in welchem Projekt bekommen ?

**Comment by Tobsen84** [comment]
Hier liegt vielleicht noch das Missverständnis. Ich möchte keinem Spieler ein Bild zuweisen. Das funktioniert ohne Probleme. Mir geht's um die Funktion "Leeren". Bei einem Spieler mit hinterlegten Bild klappt diese Funktion nicht und es bleibt nach dem Speichern weiterhin das Bild hinterlegt und nicht der Platzhalter.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
Und hier einen positiven Kommentar hinterlassen:
https://extensions.joomla.org/extension/sports-management/

**Comment by Tobsen84** [comment]
Jetzt funktioniert es. Ein ganz großes Dankeschön für für den schnellen und sehr ausdauernden Support. Ist nicht selbstverständlich. 👍

Kommentar wird zeitnah erledigt :-)
