### ISSUE TITLE
Bild auswählen - DropDown-Auswahl "Alle" zeigt keine Bilder an

### ISSUE THREAD

**Issue by Tobsen84** [diddipoeler/sportsmanagement#1201]
Hallo zusammen,

wenn man beim Bild auswählen im DropDown-Menü, wo man einstellen kann, wieviel Bilder gleichzeitig dargestellt werden, auf "Alle" stellt, stehen keine Bilder zur Auswahl (obwohl es diese gibt). Siehe:

![Bildanzeige - Alle](https://user-images.githubusercontent.com/61277544/94195879-e272d900-feb3-11ea-9fdb-7a367d462714.PNG)

Sobald man hier wenigstens auf "100" begrenzt, werden die entsprechenden Bilder dargestellt:

![Bildanzeige - Begrenzt](https://user-images.githubusercontent.com/61277544/94195972-ff0f1100-feb3-11ea-8766-e84f66e9f66c.PNG)

Dies scheint global so zu sein (ist sicherlich überall das selber Modul). Habe es zumindest in den Stammdaten bei den Vereinen als auch den Personen probiert, aber auch bei den Spielern in einem Projekt.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Tobsen84** [comment]
Funktioniert - Bilder werden nun auch bei "Alle" angezeigt. Vielen Dank.
