### ISSUE TITLE
Presseimport erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1203]
Beim Speichern des Presseimports erscheint folgende Fehlermeldung:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND season_id = 8 AND team_id = 523 AND persontype = 1' at line 3

**Comment by diddipoeler** [comment]
Bitte noch einmal eine Datei zusenden.

**Comment by svdoldie** [comment]
Ich habe dir eine Datei geschickt :+1:

**Comment by svdoldie** [comment]
In einem anderen Projekt bekoome ich beim hochladen des Presseberichts folgende Meldung:
1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3 
Diese Datei schicke ich dir auch

**Comment by diddipoeler** [comment]
Schalte mal bitte den Debug Modus auf der Seite ein.
Starte den Import dann noch einmal und poste hier mal die Fehlermeldung.
Da müsste dann die Datei und Zeilennummer stehen, die den Fehler verursacht.

**Comment by svdoldie** [comment]
Wenn ich den Debug-Modus einschalte, erscheint beim Aufruf von JSM nur folgende Fehlermeldung:
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 100279689 bytes) in /var/www/vhosts/svdoerpum.de/svdoerpum.de/plugins/system/debug/debug.php on line 1247

**Comment by diddipoeler** [comment]
OK, dann wieder ausschalten.

**Comment by Karntner** [comment]
Ich habe da mal eine Frage. Was hat es mit dem Presseimport aufsich?
Wie funktioniert das genau?

**Comment by svdoldie** [comment]
Damit kann man die Aufstellungen, Einwechselungen und Ereignisse (außer Tore) aus dem DFBnet-Spielbericht in das entsprechende Match in JSM importieren

**Comment by Karntner** [comment]
Ok das geht dann in Ö leider nicht.

Aber coole Sache

**Comment by svdoldie** [comment]
Ich habe jetzt nochmal versucht mehrere Pressebericht zu importieren.
Leider bekomme ich immer solche Fehlermeldung, wie im Anhang zu sehen.
Angeblich wurde der Bericht erfolgreich importiert, allerdings werden weder die Auswechselungen, noch die Ereignisse importiert.
Zudem scheint es mittlerweile Probleme mit Umlauten zu geben.
![Screenshot 2021-07-30 084648](https://user-images.githubusercontent.com/2417767/127612455-47d53456-dd54-4943-994f-69a670a7cfbf.png)

**Comment by tdittmann** [comment]
Hab einen PR aufgemacht, der hoffentlich Umlaute, Auswechslungen und Ereignisse fixt :)

**Comment by svdoldie** [comment]
prima, gleich mal ausprobieren 👍 :-)

**Comment by svdoldie** [comment]
Mal ein kleines Ergebnis:
Nach dem Hochladen war nur beim Torwart die Position schon vorgegeben.
Das war ansonsten weder bei den Schiedsrichtern noch bei den anderen Spielern so.
Beim Staff werden Vor und Nachname im Feld Name zusammengesetzt und dem entsprechend nicht in der DB gefunden.
Beim Import erscheinten folgende Meldungen:
danger
sportsmanagementModelMatch::createSeasonPersonAssignment 3967 Duplicate entry '396-9-0-1' for key 'combi'
sportsmanagementModelMatch::createSeasonPersonAssignment 3968 1062
sportsmanagementModelMatch::createSeasonPersonAssignment 3967 Duplicate entry '905-9-0-1' for key 'combi'
sportsmanagementModelMatch::createSeasonTeamPersonAssignment 4196 Duplicate entry '905-9-13-1' for key 'combi'
sportsmanagementModelMatch::createSeasonTeamPersonAssignment 4197 1062
Es ist ein Fehler aufgetreten.
1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND project_position_id = 3' at line 3

Letztendlich wird nur die Startaufstellung gespeichert, die Auswechslungen und Ereignisse nicht.
Wahrscheinlich kommt bricht der Import da vorher ab .

Die Umlaute werden jetzt erkannt 👍

**Comment by tdittmann** [comment]
Danke, muss ich mir dann nochmal anschauen :+1:

**Comment by svdoldie** [comment]
Der Import läuft jetzt zwar durch, aber die Ereignisse werden noch nicht erfasst.
Zu dem kommen immer noch Fehlermeldung zum Abschluss des Imports, siehe Bild
![matchreport](https://user-images.githubusercontent.com/2417767/131254219-b07ddaf0-f67d-4f5a-bbf9-1a920292197e.png)
Die Positionen werden alle nach dem Hochladen erkannt, nachdem ich alle dem Team zugeordneten Personen markiert und nochmal gespeichert habe.

**Comment by tdittmann** [comment]
Danke für die Erinnerung, das hab ich leider vergessen gehabt. Mittlerweile (wenn #1426 gemergt wurde) sollten aber die Fehlermeldungen weg sein, Vor- und Nachname beim Staff korrekt getrennt werden und die Ereignisse gespeichert werden.  

Dann gerne nochmal testen und schauen was (noch) nicht funktioniert :)

**Comment by svdoldie** [comment]
Prima, das du da weitermachst :-)
Ich bekomme jetzt leider beim hochladen folgende Fehlermeldung:
1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 3
Dabei bricht der Vorgang ab

**Comment by tdittmann** [comment]
Da bin ich jetzt verwirrt... kannst du nochmal den aktuellsten Stand ziehen und testen? Bei mir funktioniert es wie gewollt :/

**Comment by svdoldie** [comment]
Ok, das lag wohl daran, das ich das bereits nach dem ersten Merge versucht habe.
Jetzt läuft das hochladen auch wieder 👍 
Die Fehlermeldungen sind mit Joomla 3 weg.
Die Ereignisse werden auch erkannt.
Ein paar Probleme gibt's noch:
1. Der Staff wird jetzt richtig erkannt, aber nicht gespeichert
2. Die vorgegebenen Positionen werden bei den Spieler, die nicht in der Startelf stehen, nicht richtig erkannt. Beim Staff gar nicht.
3. Es gibt noch ein paar Probleme, wenn Spieler dazukommen, aber bisher nicht zum Team zugeordnet waren. Aber da muss ich noch intensiver testen

**Comment by svdoldie** [comment]
zu 2. die Projekt-Positionen werden im Bereich Spieler richtig erkannt. Bei den Auswechslungen werden die gewählten Positionen aber nicht übernommen, sondern die Projekt-Positionen 
zu 3. Wenn Spieler noch nicht der Mannschaft zugeordnet waren, werden sie zwar nach dem importieren der Mannschaft zugeordnet, aber der Zustand "im Kader anzeigen" nicht mit "ja" gespeichert und die Positionen, zwar den Spielern zugeordnet, aber ebenfalls nicht gespeichert. Es gibt nach dem Import bei J4 folgende Fehlermeldung:
![Screenshot 2022-04-01 182318](https://user-images.githubusercontent.com/2417767/161422359-e5ec6092-ce84-4bc0-9c47-f2d726e28469.png)

**Comment by tdittmann** [comment]
Danke, schau ich mir an. Bist du nur unter J4 unterwegs oder auch J3? Ich kann (aktuell) nur unter J3 testen, werde aber demnächst auch eine J4 Installation vorbereiten

**Comment by svdoldie** [comment]
Meine Seite läuft noch mit Joomla 3, ich bin aber dabei bald auf Joomla 4 umzustellen. Mit Joomla 3 sind die gleichen Probelme vorhanden, allerdings kommt da keine solche Fehlermeldung

**Comment by tdittmann** [comment]
Ok, danke 👍   Konnte bisher noch nicht den Fehler finden, es ist mit den vielen Tabellen ein Durcheinander 😞

**Comment by svdoldie** [comment]
Moin. Die Fehlermeldungen erscheinen, wenn beim Import des Presseberichtes neue Personen im Team angelegt werden. Dann wird auch eine Position zugeordnet, aber die entsprechende Person nochmals gespeichert werden. Importiert man dann den Pressebericht erneut, läuft er anstandslos durch 👍
