### ISSUE TITLE
Backend-View: matches Layout: default

### ISSUE THREAD

**Issue by 00Scooby** [diddipoeler/sportsmanagement#1206]
Ereignisse in der 2. Spielhälfte können nicht eingetragen werden.
Bsp: Spielzeit: 2 x 15min. Ereignisse in Minute 17 können nicht eingetragen werden --> Fehler.

**Comment by sigal** [comment]
Welche Sportart?
Welcher Fehler? Welche Fehlermeldung?
Welche Einstellung in den Projekteinstellungen -> TAB Wettbewerb

**Comment by 00Scooby** [comment]
Hi @sigal 

**Sportart:** Floorball
**Fehler:**
![image](https://user-images.githubusercontent.com/72069678/94568111-676f4100-026c-11eb-9f03-3fa6c12e31df.png)

**Einstellungen:**
![image](https://user-images.githubusercontent.com/72069678/94567930-44449180-026c-11eb-97b5-e3a98e406254.png)

**Comment by tmplify** [comment]
Reguläre Spielzeit wäre doch dann 30 Minuten...weil 2 x 15 Minuten....

**Comment by sigal** [comment]
Fehler gefunden!
Reguläre Spielzeit bitte auf 30 Minuten stellen. Das Programm berechnet den Zeitraum der eingegebenen Spielzeiten automatisch!

Reguläre Spielzeit 30 min. 2 Spielhälften = Eine Spielhälfte hat 15 Minuten. Ok!

**Comment by 00Scooby** [comment]
Ja, danke... war ein Denkfehler von mir... Aber die Fehlermeldung könnte da schon spezifischer sein.
Sowas wie **Fehler beim Speichern des Ereignis! (Ereignis nach Regulärer Spielzeit):**
