### ISSUE TITLE
Frontend: Kaderanzeige keine Beschreibung

### ISSUE THREAD

**Issue by LordHelmchen666** [diddipoeler/sportsmanagement#1207]
Bei der Kaderanzeige im Frontend wird die Beschreibung nicht angezeigt.

`print("<pre>".print_r($this->projectteam,true)."</pre>");` zeigt
```
stdClass Object
(
    [project_id] => 2
    [id] => 20
    [season_team_id] => 5
    [picture] => images/com_sportsmanagement/database/placeholders/placeholder_450_2.png
)
```
Scheinbar wird $this->projectteam->notes gar nicht gesetzt.

JSM 3.8.20

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
In dieser Komponente gibt es 2 Beschreibungsfelder einer Person. Einmal in den Stammdaten zur Person und einmal 
in der Liste der zugeordneten Spieler eines Vereins im Projekt. Ich habe das jetzt so programmiert, dass beide Informationen
zusammen angezeigt werden.
Sieht man jetzt hier: https://www.fussballineuropa.de/index.php/component/sportsmanagement/player/0/0/100258:1-bundesliga-2020-21/9:fc-gelsenkirchen-schalke-04-e-v-i/162988:frederik-riis-ronnow

**Comment by LordHelmchen666** [comment]
Ich meinte bei der Kaderanzeige https://www.fussballineuropa.de/index.php/component/sportsmanagement/roster/0/0/100258:1-bundesliga-2020-21/9:fc-gelsenkirchen-schalke-04-e-v-i/1541319:fc-gelsenkirchen-schalke-04-e-v-i
nicht bei der Spieleranzeige.
Aber der Fix ist auch sehr gut. Danke.

**Comment by LordHelmchen666** [comment]
Im Backend sieht es so aus.
![Screenshot_2020-10-08 Sports Management Projektmannschaft bearbeiten EHC Regensburg AH - EHC Regensburg - Administration](https://user-images.githubusercontent.com/43477041/95489004-89687200-0996-11eb-84fb-a7cf388a5347.png)
Aber im Frontend wird die Beschreibung nicht angezeigt. https://www.ehcregensburg.de/alte-herren/kader/roster.html

**Comment by diddipoeler** [comment]
Sorry für die Verwechslung. Kommt davon wenn man mehrere Baustellen gleichzeitig bearbeitet.
Bitte noch einmal testen.
Bitte auch hier einen review verfassen:
https://extensions.joomla.org/extension/sports-management/

**Comment by LordHelmchen666** [comment]
Hallo Diddi,
so klappt es noch nicht. Ich hab dann mal ausprobiert die Abfrage in Zeile 113 ebenfalls zu ändern auf
`$query->select('pt.project_id,pt.id,st.team_id as season_team_id,pt.notes');`
Damit funktioniert es dann.
Danke.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by LordHelmchen666** [comment]
Jetzt funktioniert es. Super.
