### ISSUE TITLE
Link zum Spielbericht. 

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1210]
Könnte man anstelle des Links zum Spielbericht von JSM auch noch einen Link einbauen zum Spielbericht vom Verband?

Das man auswählen kann welchen es anzeigen soll oder auch beide

**Comment by diddipoeler** [comment]
Wie Link zum Verband ?

**Comment by Karntner** [comment]
Der Verband gibt ja auch einen Spielbericht aus. Den Link meinte ich. Hier ein Beispiel: https://www.oefb.at/bewerbe/Spiel/2772541/?WSC-Hertha-1b-vs-Steinerkirchen

**Comment by sigal** [comment]
Dieser Link zum Spielbericht muss dann jedes mal neu eingepflegt werden, da er sich beim Verband pro Runde ändert.

**Comment by Karntner** [comment]
Das wär mir egal

**Comment by diddipoeler** [comment]
In welchem Template denn ?
Results und/oder matchreport ?

**Comment by Karntner** [comment]
Am einfachsten wärs im Matchreport. Dann hat man es in jedem Template

**Comment by Karntner** [comment]
Oder man kann den Pressebericht auch in Österreich hochladen. Das wäre auch eine tolle alternative

**Comment by diddipoeler** [comment]
https://youtu.be/MsRPAfgrmCU

**Comment by sigal** [comment]
Kartner verwendet kein JSM mehr. Issue schließen?
