### ISSUE TITLE
Kader

### ISSUE THREAD

**Issue by Karntner** [diddipoeler/sportsmanagement#1213]
Bei mir werden noch immer keine Spieler im Kader angezeigt. Obwohl welche drinnen sein sollten. 

![image](https://user-images.githubusercontent.com/59525415/97181068-2ac73480-179b-11eb-89a8-88a9806da49f.png)

![image](https://user-images.githubusercontent.com/59525415/97181130-3ca8d780-179b-11eb-9eea-d56eff16c9d2.png)

**Comment by Karntner** [comment]
jetzt werden die Spieler angezeigt

**Comment by Karntner** [comment]
Aber bei einem neuen Spieler den ich hinzufügen möchte kommt folgende Meldung. 

![image](https://user-images.githubusercontent.com/59525415/97346399-adc7b800-188b-11eb-89f9-706eaa471013.png)

**Comment by diddipoeler** [comment]
Sieht doch jetzt gut aus oder ?

**Comment by Karntner** [comment]
Ja super. Danke
