### ISSUE TITLE
Error after update last version

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#1247]
I had installed 3.8.20 and i've updated to last version.
After that, when i press jsm control panel button this error appear
![2021 03 14 - error](https://user-images.githubusercontent.com/20923398/111066330-c9400200-84be-11eb-91b2-f52c4cbf4c8e.png)

Some links are working but i can not access to main jsm control panel.

**Comment by diddipoeler** [comment]
Mach mal bitte ein Github Update.

**Comment by llambion72** [comment]
I've updated to 3.8.22 and now it works perfect!!
