### ISSUE TITLE
PHP-8.0.3 Fehlermeldungen-Report

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#1249]
Bei Aufruf von view rankingalltime im FE (site/models/rankingalltime.php) Zeile 85, 89
Bei Aufruf von view leaguechampionoverview im FE ausgehend wie oben

Bei beiden Aufrufen lautet die Fehlermeldung: property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given

JSM-Version: 3.8.80
PHP-Version 8.0.3
Datenbankversion | 5.5.5-10.1.48-MariaDB-0+deb9u1
Joomla!-Version | Joomla! 3.9.25 Stable [ Amani ] 02-March-2021 15:00 GMT
PHP-Interface für den Webserver | cgi-fcgi

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Danke! Kann als gelöst abgehakt werden.
