### ISSUE TITLE
SQL Error - rosteralltime

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#1251]
Bei Aufruf 'Ewiger Kader' einer Mannschaft ohne Kader erfolgt eine Fehlermeldung:

1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND st.team_id = 117296 AND pr.published = 1 AND tp.published = 1 AND tp.perso' at line 11

Premier League Kanada 2020, Mannschaft Pacific FC: https://www.fussballineuropa.de/index.php/component/sportsmanagement/rosteralltime/0/0/102194:premier-league-kanada-2020/117296:pacific-fc

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Die Fehlermeldung ist weg, doch erfolgt bei mir keine Kaderausgabe. 
Siehe:  https://demo.jsm-help.de/jsm-alle-projekte/oln-alle-runden/ewiger-kader/rosteralltime/0/0/4190:st-oberliga-nord-2019-20/3690:st-lorenzen-kn
 
Laut Ergebnisse sollten 44 Ausgaben vorhanden sein?

**Comment by diddipoeler** [comment]
Könntest Du mir bitte einen Admin-Zugang einrichten ?

**Comment by sigal** [comment]
ist an ploeger.dieterATgmx.de unterwegs
