### ISSUE TITLE
Kaderansicht FE: Bilder werden nicht scaliert

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1252]
In der Kaderansicht Option"Spieler-Visitenkarte" werden die Bilder der Personen nicht scaliert, 
sondern in Originalgröße angezeigt.
siehe https://www.svdoerpum.de/index.php/senioren/1-herren/roster

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Bei den Spielern passt es👍 
Beim Staff noch nicht

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Allles bestens :+1:
