### ISSUE TITLE
Automatisches Update meldet Fehler

### ISSUE THREAD

**Issue by jst71** [diddipoeler/sportsmanagement#1256]
JSM Update meldet verschiedene SQL Fehler: (Duplicate column name):
![grafik](https://user-images.githubusercontent.com/8502569/114719282-34d3f400-9d37-11eb-8f98-1cfa907051ae.png)

**Comment by diddipoeler** [comment]
Bitte ein Github Update machen.

**Comment by jst71** [comment]
Ja, schein ich schief gemergt zu haben.

Aber es gibt noch eine andere Stelle. 
![grafik](https://user-images.githubusercontent.com/8502569/114746453-12020980-9d50-11eb-9ffe-e0c58fea7bd4.png)

Dieses Attribut wurde früher schon einmal ergänzt. Das ist wirklich doppelt:
![grafik](https://user-images.githubusercontent.com/8502569/114746639-44136b80-9d50-11eb-8b94-1d015dacdc41.png)

Ich habe beide Spalten mal händisch entfernt, dann lief das automatische Updte durch!

**Comment by jst71** [comment]
Das Feld ist auch wirklich mit de 1.0.49 eingeführt worden:
![grafik](https://user-images.githubusercontent.com/8502569/114866848-5e9f2080-9df4-11eb-810a-1687527c3206.png)

**Comment by jst71** [comment]
Also in meinen Augen, kann die admin\sql\updates\mysql\3.8.50.sql ersatzlos gestrichen werden, da ausser doppelten attribut nichts passiert:
![grafik](https://user-images.githubusercontent.com/8502569/114868051-cc981780-9df5-11eb-9f9c-4484b3a774a5.png)

Ich erstelle mal ein PR dafür.
