### ISSUE TITLE
DB Fehler in Player Edit Form - Unknown column 'teamname' in 'field list'

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1263]
Beim Aufrufen der Stammdaten für Spieler erscheint eine Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/15192502/122965656-ba53d000-d388-11eb-9154-3b860e84c1bd.png)

Hier wird eine Abfrage auf die season_person_id - Tabelle durchgeführt und dort fehlt diese Spalte.
Nur in der season_team_id - Tabelle existiert dieses Feld.

**Comment by sigal** [comment]
Kann geschlossen werden, siehe Issue #1267
