### ISSUE TITLE
Enhance Tippreminder E-Mail

### ISSUE THREAD

**Issue by jst71** [diddipoeler/sportsmanagement#1266]
During current tournament, tippreminder e-mail lead to confusion by several tippmembers due to misleading content and unclear layout.
![grafik](https://user-images.githubusercontent.com/8502569/124643660-9ff21a00-de91-11eb-9de6-528cae910a1c.png)

E-Mail mentions there are matches without tipps, but tipps are already given and under headline Ergebnis

Enhance content of Tippreminder E-Mail:
- list only matches with missing tipps
- probably avoid sending it, if member provided all predictions already
- Simply layout to have a clear understandabily

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by jst71** [comment]
Bei mir hat sich noch nicht viel gändert... Habe aber auch ein paar Dinge gefunden, die nicht passen:
1.) Bei Spielergebnis wird der Tipp ergänzt: ($body .= $result->tipp_home . '-' . $result->tipp_away;)
![grafik](https://user-images.githubusercontent.com/8502569/137625921-d2dedb29-31d4-47c8-a1fc-0773a7f21911.png)

Wobei sich mir da auch die Frage stellt: Sollen Spiele, die bereits durch sind, wirklich auf eine Tippreminder Liste auftauchen?

2.) Der Tipp in der Tippspalte wird nicth angezeigt, da hier $predictionProject kein objekt ist, sondern die ID. Daher auch der Fehler im Error log:
[Sun Oct 17 13:31:48.844147 2021] [php7:notice] [pid 28936] [client 87.157.67.79:49905] PHP Notice:  Trying to get property 'mode' of non-object in ...administrator/components/com_sportsmanagement/models/predictionmember.php on line 273,

Ich werde mal einen Fixmachen und einen PR erstellen!

**Comment by jst71** [comment]
OK, PR ist da :-)
