### ISSUE TITLE
Error editing persons

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#1267]
When I enter into a person profile next error appear,

 ¡La función DB ha fallado!. Código de error 1054 ( Function DB failed, Error code 1054)
span style=\"_QQ_color: red

Nombre del archivo: /home/u516583145/domains/lenayeazul.com/public_html/administrator/components/com_sportsmanagement/models/fields/seasoncheckbox.php
span style=\"_QQ_color: red

And into person profile, seasons folder don't be filled with any kind of data.

**Comment by sigal** [comment]
Hoffe das hilft weiter:

DB-Funktion mit Fehlercode 1054 fehlgeschlagen!
Unknown column 'teamname' in 'field list'
Dateiname: /var/www/vhosts/stony-sport4u.de/jsm.stony-sport4u.de/administrator/components/com_sportsmanagement/models/fields/seasoncheckbox.php
Zeile: 89

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by llambion72** [comment]
I tested and it works perfectly!
