### ISSUE TITLE
404-Seite nach Speichern von Tipps bei aktiviertem Tipp-Empfang

### ISSUE THREAD

**Issue by Patman29** [diddipoeler/sportsmanagement#1271]
Sobald ein Mitspieler im Tippspiel seine abgegebenen Tipps auch via eMail zugesendet bekommt (Option: Tipp empfang), gibt es nach dem Speichern der Tipps eine 404-Seite als ausgabe.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen!
