### ISSUE TITLE
Rankingmodul zeigt die Tabelle in falscher Reihenfolge

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1272]
Das Rankingmodul zeigt die Tabelle in falscher Reihenfolge an, siehe Bilder.
Ist das ein Bug, oder ist da eine Einstellung verkehrt?
![frontend](https://user-images.githubusercontent.com/2417767/129514418-fd9f3d41-705c-4e05-b113-1571b511117c.jpg)
![modul](https://user-images.githubusercontent.com/2417767/129514422-8313cac2-6b54-4a05-a895-7eb7baf5cbe8.jpg)

**Comment by sigal** [comment]
Hier kann es sich nur eine nicht korrekte Einstellung im Tmplate ranking handeln. Prüfen ob sich nicht ein Leerzeichen beim Kopieren verirrt hat.
Am Programm liegt es hier nicht, da auf eurer Seite eine korrekte Tabelle abrufen läßt: https://www.svdoerpum.de/senioren/1-herren/tabelle/ranking/0/0/42:verbandsliga-nord-2018-2019/0/695:30-spieltag/0/0

Die Einstellungen dieser Tabelle auf die fehlerhafte übertragen,

**Comment by svdoldie** [comment]
Hmm, ich arbeite mit einem Mastertemplate, welches in allen Projekten verwendet wird.
Aber du hast recht, wenn ich die Saison und Projekt aus deinem Link in einem Rankingmodul verwende, 
wird die Tabelle im Modul korrekt angezeigt.
Warum das in den Modulen dieser Saison nicht funktioniert, ist mir ein Rätsel...

**Comment by svdoldie** [comment]
Keine Ahnung warum, aber jetzt sind die Tabelle in den Modulen wieder korrekt
