### ISSUE TITLE
Joomla 4: Ergebnisbearbeitung im Frontend wird nicht angezeigt

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1273]
Die Ergebnisbearbeitung im Frontend wird nicht angezeigt.
Wenn man auf das Symbol klickt, wird man auf die Startseite der Homepage geleitet

**Comment by ortwin20000** [comment]
Ist dieser Punkt noch aktuell? Ich habe es bei mir mit Joomla 4.0.3 ausprobiert und es wir mir die Ergebnisbearbeitung geöffnet.

**Comment by svdoldie** [comment]
Ja, bei mir nach dem klicken auf das Symbol immer noch die Startseite  angezeigt

**Comment by ortwin20000** [comment]
Welche View verwendest du für die Ergebnisbearbeitung?

**Comment by svdoldie** [comment]
Ich habe beide versucht. Gleiches Ergebnis.

**Comment by ortwin20000** [comment]
Kann man sich das irgendwie gemeinsam anschauen?
Ich verwende die Ergebnisanzeige und bin im Frontend angemeldet:
![grafik](https://user-images.githubusercontent.com/15192502/135983524-76e89203-1c6f-4e4e-9e8e-c81577e33203.png)

Nach dem Klick auf den Bearbeiten-Button öffnet sich die Ergebniseingabe:
![grafik](https://user-images.githubusercontent.com/15192502/135983655-e9a5a756-f4cc-4ae4-a289-75aeda3161ba.png)

**Comment by svdoldie** [comment]
Ja, klar. Zur Seite kommst du hier https://www.svdoerpum.de/joomla/administrator/index.php
Die Zugangsdaten kannst du per Mail bekommen

**Comment by ortwin20000** [comment]
Ich habe mir das auf deiner Seite mal angeschaut und festgestellt, dass du als Vorlage für die Ergebniseingabe "DFC-Day" verwendest.
Auf meiner Seite verwende ich "Normal" und damit klappt es bei mir.

![grafik](https://user-images.githubusercontent.com/15192502/136159845-bce9b287-b938-4aba-b58b-bd64307a7a6f.png)

Ich weiß jetzt nicht was DFC-Day macht aber du könntest mal die Vorlage "Normal" ausprobieren und in der Zwischenzeit schau ich mir die Vorlage DFC-Day an. Kann mir jemand sagen, was bei dieser Vorlage anders ist als zur normalen?

**Comment by ortwin20000** [comment]
Mir ist noch eine Idee gekommen und ich habe den Bearbeitungs-Link mit dem Standard-Template von Joomla 4 aufgerufen.
Damit wird mir die Seite zum Bearbeiten angezeigt. 
![grafik](https://user-images.githubusercontent.com/15192502/136165895-adf6bc71-b4a3-4165-8d06-71becbacfb30.png)

Somit dürfte es sich um ein Problem mit deinem vewendeten Template handeln.

**Comment by ortwin20000** [comment]
Jetzt kommen wir der Sache schon näher.
Bei mir werden die Ergebnisse als Tabelle ausgegeben und bei dir als DIV.
Das ist im overall-Template hinterlegt:
![grafik](https://user-images.githubusercontent.com/15192502/136177490-f122c184-964e-47a0-ac89-72cb337bdaaf.png)

**Comment by svdoldie** [comment]
In der Tabellenansicht funktionieren sowohl Normal als auch DFC-Day

**Comment by ortwin20000** [comment]
Die Bootstrap-Ansicht funktioniert bei mir mit Normal und DFC-Day nicht, weil dort row-fluid anstatt row verwendet wird. Das dürfte sich bei Bootstrap5 geändert haben. Dies ist in der Datei derzeit fix eingetragen und nicht über die globalen Optionen steuerbar.

Hier müsste man sowieso die ganze Ansicht (wenn Bootstrap ausgewählt ist) überarbeiten, da einige Funktionen nicht vorhanden sind. Z.B. werden alle Spalten angezeigt, auch wenn z.B. die Uhrzeit oder das Datum nicht gewünscht sind. Zusätzlich fehlen die Spielergebnisse zum Eintragen komplett.
Ich denke mal, dass war ein Versuch für ein Responsive-Design der nicht vollendet wurde.

So sieht es bei mir als Tabellenform aus:
![grafik](https://user-images.githubusercontent.com/15192502/136659345-e2305ec4-55ef-4235-9ffa-5de714ca99eb.png)

Und so wenn ich Bootstrap auswähle:
![grafik](https://user-images.githubusercontent.com/15192502/136659365-d8bf2b89-22e4-47c5-8441-64a41e17206e.png)

Wenn ich nun row-fluid auf row abändere:
![grafik](https://user-images.githubusercontent.com/15192502/136659433-1ed6cb7d-167b-4aac-8f2b-7900603e4520.png)

Spalten die ausgeblendet werden sollten, werden nicht ausgeblendet, Spielergebnisse können nicht direkt eingetragen werden und die Veröffentlichungscheckbox fehlt.

**Comment by svdoldie** [comment]
Ja, das deckt sich mit meinen Versuchen

**Comment by svdoldie** [comment]
Hmm, warum wird der Issue geschlossen? Der Zustand ist doch noch so
