### ISSUE TITLE
Modul: Modul Rangliste

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#1279]
Die Kriterien für die Tabelle werden nicht in das Modul übernommen

Im Menü wird es korrekt angezeigt.
![image](https://user-images.githubusercontent.com/9608697/132990787-294cf573-4473-4afd-809d-ad5e35bffbe4.png)
https://www.rhein-main-player-league.de/ligen/league-two-20/ergebnisse-two-20/resultsranking

Modulansicht:
![image](https://user-images.githubusercontent.com/9608697/132990800-20595d63-7b34-4f62-8d64-68abf389c073.png)

![image](https://user-images.githubusercontent.com/9608697/132990759-4e399397-4939-4758-a3f8-29d0df055585.png)

Vg Sven

**Comment by sigal** [comment]
Siehe https://github.com/diddipoeler/sportsmanagement/issues/1272

**Comment by sigal** [comment]
Wahrscheinlich unterbindet das TAB-Modul mit dem das Ranking-Modul eingebunden wird das korrekte laden.
Das ist eine mühsame Suche, welche js-Dateien sich da in den Haaren liegen.

**Comment by PhantoSGE** [comment]
Dachte ich auch. 
Aber auch wenn ich das Modul einer Position zuweise bekomme ich das gleiche Bild.
Aber nur auf der Startseite.
https://www.rhein-main-player-league.de/

Auf einer Unterseite ist alles ok
https://www.rhein-main-player-league.de/ligen/league-two-20/ergebnisse-two-20/resultsranking

**Comment by sigal** [comment]
Startseite. Auch bei Deaktivierung des TAB-Modul?

**Comment by PhantoSGE** [comment]
Dann funktioniert es. Das habe ich nicht probiert vorher. Danke dir
