### ISSUE TITLE
Vereins Wappen hochladen name wird zu Symbole

### ISSUE THREAD

**Issue by Europekicker** [diddipoeler/sportsmanagement#1284]
Wenn ich einem verrein ein Wappen zuweisen will und dafür ein neues hochlade wird das Bild nach dem einfügen angezeigt aber hochladen geht nicht.
Datei name wird in Symbole umgewandelt.

<img width="1632" alt="screenwappen" src="https://user-images.githubusercontent.com/14942144/134331303-741e7cf6-3088-47be-94ca-2b6f8874fd0b.PNG">

**Comment by ortwin20000** [comment]
In welcher Version von Joomla tritt dieses Phänomen auf?
Welche Zeichencodierung wird verwendet? UTF8, ISO-8859-1, Windows-1252, ....?

**Comment by diddipoeler** [comment]
Die Symbole einfach ignorieren.
