### ISSUE TITLE
J4: Probleme mit behavior.framework und behavior.modal

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1290]
Ich arbeite gerade am Upgrade unserer Verbandsseite auf Joomla 4.
Wir verwenden hier das ClubIcon-Modul auf der Startseite und nach dem Upgrade gab es einen 500 Fehler.
Ursache dürfte das Fehlen von behavior.framework sein.

Dieses wird in der mod_sportsmanagement_clubicons.php aufgerufen:

>if (version_compare(JVERSION, '3.0.0', 'ge'))
>{
>	HTMLHelper::_('behavior.framework', true);
>}
>else
>{
>	HTMLHelper::_('behavior.mootools');
>}

Damit es wieder läuft habe ich den Code so abgeändert:
>if (version_compare(JVERSION, '4.0.0', 'ge'))
>{
>	//HTMLHelper::_('behavior.framework', true);
>}
>else if (version_compare(JVERSION, '3.0.0', 'ge'))
>{
>	HTMLHelper::_('behavior.framework', true);
>}
>else
>{
>	HTMLHelper::_('behavior.mootools');
>}

Mir ist nach einem Durchsuchen des Codes nun aufgefallen, dass an einigen Stellen `HTMLHelper::_('behavior.framework', true);` aufgerufen wird. Müssen die alle korrigiert werden?

z.B. in diversen Views werden behavior.framework und behavior.modal verwendet (\views\allprojects\tmpl\default.php)
Wenn ich sie auskommentiere läuft der View aber welche Nebenwirkungen hat dies dann?

**Comment by ortwin20000** [comment]
Hätte noch das dazu gefunden:
https://joomla.stackexchange.com/questions/22302/joomla-4-alpha-mootools-library

**Comment by ortwin20000** [comment]
Im speziellen Fall von mod_sportsmanagement_clubicons.php wird das behavior.framework benötigt um die Klasse .transition bei den Logos hinzufügen sobald man mit der Maus drüber fährt und das ausgewählte Logo zu vergrößern.

Wenn ich für Joomla 4 die behavior.framework nicht lade funktioniert es nicht mehr.
Als Alternative habe ich das Style .transition im Code umbenannt auf .img-zoom:hover
Damit funktionert es dann auch ohne dem behavior.framework

$style = '
.img-zoom {
width: auto;
    height: ' . $params->get('picture_height', '50') . ';
    -webkit-transition: all .2s ease-in-out;
    -moz-transition: all .2s ease-in-out;
    -o-transition: all .2s ease-in-out;
    -ms-transition: all .2s ease-in-out;
}

.img-zoom:hover {
    -webkit-transform: scale(1.' . $params->get('max_width_after_mouse_over', '10') . ');
    -moz-transform: scale(1.' . $params->get('max_width_after_mouse_over', '10') . ');
    -o-transform: scale(1.' . $params->get('max_width_after_mouse_over', '10') . ');
    transform: scale(1.' . $params->get('max_width_after_mouse_over', '10') . ');
}
';

**Comment by ortwin20000** [comment]
In der View AllProjects hatte ich auch einen Fehler wegen behavior.framework und behavior.modal:
Vorher in der \view\allprojects\tmpl\default.php:
if (version_compare(substr(JVERSION, 0, 3), '4.0', 'ge'))
{
	HTMLHelper::_('behavior.keepalive');
}
elseif (version_compare(substr(JVERSION, 0, 3), '3.0', 'ge'))
{
	HTMLHelper::_('behavior.tooltip');
}
HTMLHelper::_('behavior.framework');
HTMLHelper::_('behavior.modal');

Nachher:
if (version_compare(substr(JVERSION, 0, 3), '4.0', 'ge'))
{
	HTMLHelper::_('behavior.keepalive');
}
elseif (version_compare(substr(JVERSION, 0, 3), '3.0', 'ge'))
{
	HTMLHelper::_('behavior.tooltip');
	HTMLHelper::_('behavior.framework');
	HTMLHelper::_('behavior.modal');
}

Damit dann auch das Bild, welches im Modal angezeigt wird, auch dargestellt wird, musste ich auch in der \helpers\html.php etwas ändern:
Vorher:
$modaltext = '<a href="#' . $target . '" title="' . $text . '" data-toggle="modal" >';
Nachher:
$modaltext = '<a href="#' . $target . '" title="' . $text . '" data-bs-toggle="modal" >';

Soweit ich bei den Änderungen zu Bootstrap 5 gelesen habe, wurden die Klassen data-* auf data-bs-* abgeändert.

**Comment by diddipoeler** [comment]
Kannst du mal bitte dafür einen Merge Request machen?

**Comment by ortwin20000** [comment]
Das werde ich morgen machen.
