### ISSUE TITLE
J4: JGLOBAL_DOWN existiert nicht mehr

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1292]
Nach dem Upgrade auf Joomla 4 ist mir in der Schiedsrichterzuweisung aufgefallen, dass der Button für "Abwärts" den Text JGLOBAL_DOWN beinhaltet. Dieser Eintrag ist in Joomla 4 anscheinend nicht mehr vorhanden.
Entweder ich erstelle ein Sprachen-Override oder ich verwende einen Eintrag aus der Sprachdatei für JSM (COM_SPORTSMANAGEMENT_GLOBAL_DOWN) oder ich verwende zum Beispiel den Joomla 4 Standard JLIB_HTML_MOVE_DOWN und dann für den Button darüber JLIB_HTML_MOVE_UP.

Betrifft die Dateien editlineup_players.php, editlineup_staff.php und editreferees.php

**Comment by diddipoeler** [comment]
Kannst du mal bitte dafür einen Merge Request machen?

**Comment by ortwin20000** [comment]
Hat sich durch den Pull Request von @sigal erledigt.
