### ISSUE TITLE
J4: Backend Hilfetext zeigt nichts an und kann nicht geöffnet werden

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1294]
Wenn man bei den Feldern auf das ?-Icon zeigt, sollte normalerweise der Text "Onlinehilfe" aufscheinen und ein Klick darauf auf das Online-Wiki verweisen.
In Joomla 4 passiert aber nichts und als Text scheint " title= " auf.

Hier tritt wieder der Fehler mit data-toggle auf.
Fehlerbehebung möglich durch Änderung dieser Datei
administrator\components\com_sportsmanagement\views\fieldsets\tmpl\default_editdata.php
Vorher ab Zeile 100:
```
<a href="#<?php echo $var_onlinehelp; ?>"
   title="<?php echo $var_onlinehelp; ?>" class=""
   data-toggle="modal">
	<?php
    $image_attributes['title'] = 'title= "'.Text::_('COM_SPORTSMANAGEMENT_HELP_LINK') . '"';
```
Nachher:
```
<a href="#<?php echo $var_onlinehelp; ?>"
   title="<?php echo $var_onlinehelp; ?>" class=""
   data-bs-toggle="modal">
	<?php
    $image_attributes['title'] = Text::_('COM_SPORTSMANAGEMENT_HELP_LINK');
```

**Comment by diddipoeler** [comment]
Kannst du mal bitte dafür einen Merge Request machen?

**Comment by ortwin20000** [comment]
Ich werde das morgen versuchen hinzubekommen.
