### ISSUE TITLE
J4: Modul Quick-Icon im Backend

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1297]
Da nach dem Update auf Joomla 4 das Quick-Icon-Modul im Backend sich doch stark von den anderen Icons unterscheidet habe ich eine Anpassung für Joomla 4 hinzugefügt.

So sieht es bei mir jetzt aus:
![grafik](https://user-images.githubusercontent.com/15192502/135998266-ccf5e9ac-0306-45dc-9149-921b7d7fdc10.png)

Ich werde dafür ein Pull request erstellen.

**Comment by boxr** [comment]
Nach der Anpassung wird Sport Management Module Quickicon nicht mehr angezeigt, Fehler 0  syntax error, unexpected '?>'
