### ISSUE TITLE
Backend-View: club Layout: edit

### ISSUE THREAD

**Issue by rogru1** [diddipoeler/sportsmanagement#1312]
Joomla 4
Feld Club foundation 
Ubernahme von Datum <1902 (von 01.11.1901 rückwärts wird mit folgenden Fehler nicht übernommen:

Out of range value for column 'founded_timestamp' at row 1

**Comment by ortwin20000** [comment]
Welche PHP Version wird eingesetzt?
32-bit oder 64-bit?
Genauere Infos erhält man mit phpinfo().

**Comment by rogru1** [comment]
PHP Version | 7.4.24
Linux server 4.19.0-0.bpo.6-amd64 #1 SMP Debian 4.19.67-2+deb10u2~bpo9+1 (2019-11-12) x86_64

Datenbank-Server:
Server-Version: 10.5.12-MariaDB-1:10.5.12+maria~stretch - mariadb.org binary distribution

**Comment by ortwin20000** [comment]
Das Problem ist, dass die Spalte founded_timestamp ein INT-Feld ist.
Der maximale Wert ist somit -2147483647 oder 2147483647; Da der Unix-Timestamp vom 01-01-1970 wegrechnet, geht er bei kleineren Werten ins Minus.

Bei meinem Versuch kommt für den 1.10.1900 ein Wert von -2185405200 heraus und das geht sich mit dem Datentyp INT nicht mehr aus und es kommt die Fehlermeldung.

@diddipoeler Meine Lösung wäre den Datentyp von INT auf BIGINT abzuändern:
`ALTER TABLE `kz80i_sportsmanagement_club` MODIFY COLUMN `founded_timestamp` BIGINT; `

**Comment by rogru1** [comment]
Danke an @diddipoeler und @ortwin20000
