### ISSUE TITLE
Zählung für Bälle für Sportart Faustball

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1317]
Ich habe vor einiger Zeit Anpassungen für die Sportart Faustball durchgeführt. Diese würde ich nun gerne einpflegen.

Bei Faustball wird in Sätzen gespielt und dafür habe ich in JSM die Option "Sätze verwenden" in den Projekten aktiviert.
Bei der Ergebnisseingabe sieht das Ganze so aus:
![grafik](https://user-images.githubusercontent.com/15192502/136913055-72da871a-e518-4f7f-bca2-59a5b21bbbc1.png)

Je nach Liga können bis zu 7 Sätze gespielt werden.
Ich nehme an, dass die ursprüngliche Funktion für Tennis gedacht ist. Da ich nun in der Tabelle auch die Punkte pro Satz (Bälle) zählen muss, habe ich hier Änderungen für die Tabellendarstellung durchführen müssen, da die Berechnung mit LEGS und LEGS_DIFF nicht funktionierte.
Vorher:
![grafik](https://user-images.githubusercontent.com/15192502/136913543-94461065-ee9a-47bf-8833-bdf49f927316.png)

Nachher:
![grafik](https://user-images.githubusercontent.com/15192502/136913729-40d61a34-117d-40dd-bb0e-ab3be81ff5ed.png)

Dafür habe ich zwei neue Spalten BALLS und BALLS_DIFF, zwei neue Übersetzungen hinzugefügt und zwei Übersetzungen mit einem Override überschrieben.
Betroffene Dateien sind:
components\com_sportsmanagement\helpers\ranking.php
components\com_sportsmanagement\views\ranking\tmpl\default_rankingheading.php
components\com_sportsmanagement\views\ranking\tmpl\default_rankingrows.php

Neue Texte:
COM_SPORTSMANAGEMENT_BALLS_DIFF="Ball Differenz"
COM_SPORTSMANAGEMENT_BALLS="Bälle"

Überschriebene Texte:
COM_SPORTSMANAGEMENT_SCOREAGAINST="Sätze verloren"
COM_SPORTSMANAGEMENT_SCOREFOR="Sätze gewonnen"

@diddipoeler Kann ich die Änderungen der Dateien mit einem Merge Request zur Verfügung stellen?
@sigal Kannst du die neuen Texte dann einpflegen?

**Comment by sigal** [comment]
Wenn wie von @diddipoeler gewünscht eine Abfrage eingebaut wird,
pflege ich die neuen Texte ein.
