### ISSUE TITLE
Joomla 4: Probleme mit Modalfenster beim Kalendermodul

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1319]
Ich habe ein paar Probleme mit dem Modalfenster des Kalendermoduls. Zwar öffnet sich das Modalfenster,
aber es lässt sich nicht wieder schließen. Zum einem fehlt das entsprechende Symbol, oben rechts des Fensters,
zum anderen lässt auch ein klicken außerhalb des Fensters dieses nicht verschwinden. Außerdem wird bei sehr vielen Spielen,
keine Scrollleiste erzeugt, sondern die Spiele ausserhalb des Fensters angezeigt. Siehe Bild
![Anmerkung 2021-10-12 112042](https://user-images.githubusercontent.com/2417767/136928875-1a152c29-49c7-4d6d-875c-cdada81e7100.jpg)
oder hier https://www.svdoerpum.de/joomla/

**Comment by svdoldie** [comment]
Falls du die Optionen von JSM meinst, das ändert leider nichts

**Comment by svdoldie** [comment]
Das mit der Höhe habe ich gerade per Css hinbekommen. Allerdings bekomme ich mit dem Standardtemplate von Joomla überhaupt kein Modalfenster. Mit den verschiedenen Templates von Joomlart, Joomshaper usw. allerdings schon.

**Comment by ortwin20000** [comment]
Bei mir kommt auch kein Fenster und beim Kalendertag erscheint kein Text beim Drüberfahren. Ich verwende Astroid als Template.

**Comment by ortwin20000** [comment]
Vermutlich geht das Modal nicht auf weil auf in dem Module der Fehler `jQuery is not defined` auftaucht.

**Comment by ortwin20000** [comment]
Ich habe mal meine Änderungen für Joomla 4 für den Kalender hinzugefügt. Bitte nach dem Merge testen.
Der Modal-Body sollte nun scrollbar sein und die zweite doppelte Titel-Zeile sollte nicht mehr aufscheinen.

Das Umschreiben von window.addEvent in addEventListener kann ich noch nicht. Muss mich da erst noch weiter einlesen.

**Comment by svdoldie** [comment]
Ja, das ist noch offen

**Comment by svdoldie** [comment]
Ach ja. Mist, das hatte ich vergessen. Sorry.
Vielleicht ist das mittlerweile gar nicht mehr nötig,
bzw. es wird deaktiviert installiert
