### ISSUE TITLE
Joomla 4: Spielfeldpositionen erzeugen Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1326]
Ruft man die Spielfeldpositionen auf, erhält man folgende Fehlermeldung:
500 jquery::ui not found.

**Comment by ortwin20000** [comment]
Zu dem Fehler `Data truncated for column 'alias' at row 1`
In der Tabelle `sportsmanagement_rosterposition` ist für die Spalte der Typ `enum('HOME_POS', 'AWAY_POS')` hinterlegt.

Beim Speichern wird aber der Alias mit `$data['alias']       = OutputFilter::stringURLSafe($data['name']);` befüllt.

Die Spalte `short_name` verwendet auch den Typ `enum('HOME_POS', 'AWAY_POS')` und ist meiner Meinung nach richtig.

@diddipoeler Meiner Meinung nach gehört die Spalte `alias` als varchar(200) wie die Spalte `name` definiert und in der Datei `administrator\components\com_sportsmanagement\sql\install.mysql.utf8.sql` von
`'alias' enum('HOME_POS','AWAY_POS') NOT NULL default 'HOME_POS',`
auf 
`'alias' varchar(200) NOT NULL default '',`
geändert.

**Comment by ortwin20000** [comment]
Welches Spielfeld ist bei dir ausgewählt?

**Comment by svdoldie** [comment]
Bei allen Positionen spielfeld_578x1050.png

**Comment by diddipoeler** [comment]
Könnt ihr bitte das Speichern noch einmal testen ?

**Comment by ortwin20000** [comment]
> 
> 
> Oh man, irgendwie gestaltet sich das testen schwierig. Jetzt habe ich das in meinem vorherigen Beitrag beschriebene Verhalten nicht mehr. Jetzt werden mir wieder keinerlei Spielfelder angezeigt

Ich werde das mal direkt in deinem Backend testen wenn ich darf.

**Comment by svdoldie** [comment]
Ich habe jetzt auf zwei verschiedenen Servern ein neues Joomla 4 aufgesetzt und JSM installiert. Beides mit den gleichen JSM-Optionen eingerichtet. Testergebnis: Auf einem Server läuft alles reibeungslos, auf dem anderen werden keine Bilder angezeigt.
Kann es mit der PHP-Version zu tun haben? Auf dem Server, wo es nicht geht läuft die Version 7.3.25, auf dem Server, auf dem es geht 7.4.24. Oder generell an der Serverkonfiguration?

**Comment by svdoldie** [comment]
ok, mach ich nachher mal
