### ISSUE TITLE
Wunsch: Joomla 4: Datumsfeld in der Ansicht Matches breiter

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1332]
Das Datumsfeld im Backend bei den Begegnungen könnte gut ein bisschen breiter sein, siehe Bild.
Kleine Info. Scaliert man den Browser auf zum 60% kann man das ganze Datum sehen.
![Anmerkung 2021-10-14 123822](https://user-images.githubusercontent.com/2417767/137306458-25a7cc5e-564c-4bea-860a-4826486a91ca.jpg)

**Comment by ortwin20000** [comment]
Die Idee der Möglichkeit für die Spalten im Backend auszublenden haben wir hier #1337 angesprochen.
Mit der Erweiterung um Templates für das Backend kann ich mir weiterhelfen. Ich habe das bei mir mal mit der View Rounds getestet.

Wenn ich alles beim Alten belassen geht sich bei mir die Tabelle ohne Scrollen nicht aus und das Datumsfeld ist auch zu klein.
Wenn ich nun die Spalten, die ich nicht benötige ausblende
![grafik](https://user-images.githubusercontent.com/15192502/137942462-2656e9ed-c2ca-4da4-b5d1-122fcdd983a0.png)
und zusätzlich in der default_data.php die Klassen und Spaltenbreiten entferne und als default_4_data.php speichere, dann geht sich der Rest bei einer FullHD-Auflösung in Joomla 4 aus:
![grafik](https://user-images.githubusercontent.com/15192502/137942571-5f45675c-5f7f-4c99-a465-396db5eab74d.png)

Vielleicht würde dies auch dein Problem lösen.

**Comment by svdoldie** [comment]
Das sieht super aus :+1:
