### ISSUE TITLE
BE: Austragungsort in View matches auswählbar

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1337]
Beim Fußball ist es ja normalerweise so, dass der Austragungsort der Heimmannschaft standardmässig verwendet wird und nur bei Änderungen dies in den Spieldetails eingetragen wird.

Beim Faustball finden aber an einem Austragungsort mehrere Spiele statt und deswegen müssen wir bei jedem Spiel den Austragsungsort immer eintragen.
![grafik](https://user-images.githubusercontent.com/15192502/137594326-b27989d8-6c4d-4192-89a1-4783c7442d64.png)

Aus diesem Grund hatte ich in meinem Branch den Austragungsort direkt in der matches-View im Backend hinzugefügt und nicht nur wegen dem Austragsungsort immer die Spieldetails einzeln öffnen zu müssen.

Ich würde dies nun gerne in den Standard zurückführen und würde die neue Spalte nur für die Sportart Faustball einblenden.
```
if($this->projectws->sport_type_name == 'COM_SPORTSMANAGEMENT_ST_FAUSTBALL')
{
?>
	<th class="title"><?php echo Text::_('COM_SPORTSMANAGEMENT_ADMIN_MATCH_F_MD_VENUE'); ?></th>
<?php
}
```
bzw.
```
if($this->projectws->sport_type_name == 'COM_SPORTSMANAGEMENT_ST_FAUSTBALL')
{
?>
	<td id="crowd" class="center">
		<?php 
		$append = '';
		$append .= ' onchange="document.getElementById(\'cb' . $i . '\').checked=true" ';
		echo HTMLHelper::_('select.genericlist', $this->playgrounds, 'playground_id' . $row->id,
			'class="form-control form-control-inline" size="1"' . $append, 'value', 'text', $row->playground_id 
		); ?>
		</td>
<?php
}
```
Zusätzlich im model project.php
Anstatt:
```
$query->select('*');
$query->from('#__sportsmanagement_project');
$query->where('id = ' . $project_id);
```
musste ich noch die Sportarten nachladen:
```
$query->select('p.*, st.name AS sport_type_name');
$query->from('#__sportsmanagement_project as p');
$query->join('INNER', '#__sportsmanagement_sports_type AS st ON p.sports_type_id = st.id ');
$query->where('p.id = ' . $project_id);
```
Als letztes noch im model match.php
`$object->playground_id           = $post['playground_id' . $pks[$x]];`

Ist das ok, wenn ich dies auf die Sportart begrenze oder sollen wir hierfür eine Option mit JA/NEIN irgendwo einbauen und für alle Sportarten freigeben?

**Comment by ortwin20000** [comment]
Wenn ich die Option
![grafik](https://user-images.githubusercontent.com/15192502/137632361-99a371a8-c832-4614-89fc-c7b730740714.png)
so setze, werden mir keine Spiele angezeigt.
Da dürfte es sich verkehrt verhalten.

**Comment by sigal** [comment]
> 
> 
> Hab mir das Modul matches angeschaut. Dort gibt es schon eine Einstellung im Tab "Spezielle Einstellungen für die Spielinformationen" wo der Spielort ein-/ausgeblendet werden kann. ![grafik](https://user-images.githubusercontent.com/15192502/137631977-de6e97bf-97ca-4b77-b6d2-047b7f9bca6c.png)
> 
> ![grafik](https://user-images.githubusercontent.com/15192502/137632036-7f33b421-6fa7-4641-801a-43e950a8172f.png) Hier ist mir aufgefallen, dass die Übersetzung für den Spielort nicht durchgeführt wird. Edit: Wird in den Tab-Einstellungen hinterlegt, was für ein Text ausgegeben werden soll ;-)
> 
> Zusätzlich habe ich eigentlich diese Einstellungen im Modul: ![grafik](https://user-images.githubusercontent.com/15192502/137632070-de9fd998-391e-4c4e-8939-98cdb35851e1.png) ![grafik](https://user-images.githubusercontent.com/15192502/137632077-f0bb9b24-f7c3-4553-94f7-095fd29d864f.png) Trotzdem werden mir Spiele angezeigt?

Venue:
in Zeile 605 muß eine neue Sprach-Konstante eingestzt werden
mod_sportsmanagement_matches\mod_sportsmanagement_matches.xml

**Comment by jst71** [comment]
Ich finde solche hard codierten Features immer schwierig:


`if($this->projectws->sport_type_name == 'COM_SPORTSMANAGEMENT_ST_FAUSTBALL')
{
?>
	<th class="title"><?php echo Text::_('COM_SPORTSMANAGEMENT_ADMIN_MATCH_F_MD_VENUE'); ?></th>
<?php
}`

Eigentlich haben wir doch viele gute Konfigurationsmöglicheiten, so dass man es auch als generische Konfiguration umsetzen könnte. 

Bei den Fussballwelt- und -eurapameisterschaften hat mich das auch schon immer gestört, dass man für den Austragungsort immer auf die Details gehen muss.

Wir könnten entweder einen Config Parameter im Projekt ergänzen oder xml Konfiguration des Frontend auch für das Backend umsetzen:

`if ($this->config['show_playground_selector_in_matches_list'])
{
?>
	<th class="title"><?php echo Text::_('COM_SPORTSMANAGEMENT_ADMIN_MATCH_F_MD_VENUE'); ?></th>
<?php
}`

Andernfalls sind wir irgendwann bei
if ( $this->projectws->sport_type_name == 'COM_SPORTSMANAGEMENT_ST_FAUSTBALL'
   || ($this->projectws->sport_type_name == 'COM_SPORTSMANAGEMENT_ST_SOCCER' && LIGA = EM || WM))

**Comment by ortwin20000** [comment]
Ich hätte mal meinen ersten Teil für Templates im Backend hochgeladen. Damit können für die View rounds im Backend die Spalten ein/ausgeblendet werden.
Wenn kein Template gefunden wurde, werden alle Spalten angezeigt.

**Comment by ortwin20000** [comment]
Ist das ein neues Projekt oder ein bestehendes?

**Comment by sigal** [comment]
Hab den Fehler gefunden.
In der backend_rounds.xml fehlt der abschließende tag:
`</fieldset>`
