### ISSUE TITLE
Neuinstallation bricht ab

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1343]
Beim Versuch JSM neu zu installieren erhalte ich momentan folgende Fehlermeldung:
JInstaller: :Install: SQL-Fehler Duplicate column name 'fav_team_send_mail'
Installation der Erweiterung abgebrochen.

Fehler bei der Komponenten-Installation.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
