### ISSUE TITLE
Create an easy way to add (your) page to a list of sites that use JSM

### ISSUE THREAD

**Issue by appukonrad** [diddipoeler/sportsmanagement#1344]
Create an easy way to add (your) page to a list of sites that use JSM. It is important for the creators to see what the pages look like in real life. And this list could also be used, as a reference, for such a free demo ;)

**Comment by diddipoeler** [comment]
Jetzt ja: https://www.fussballineuropa.de/index.php/jsm-benutzer/jsm-weblink-einreichen

**Comment by diddipoeler** [comment]
Ich hoffe das ich eure Wünsche erfüllen konnte.

**Comment by diddipoeler** [comment]
Wie gesagt: Der Server spinnt im Augenblick ein bisschen rum, weil ich Bots aussperren muss, die
meine Webseite lahmlegen. (Applebot)

**Comment by diddipoeler** [comment]
Woher hast du die denn?
