### ISSUE TITLE
Buttons im Teamplan funktionieren nicht

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1345]
Die beiden Buttons "Export to PDF" und "Print Preview" haben bei mir keine Funktion.
Ist das ein Bug, oder liegt da eine falsche Einstellung vor? Siehe Link
https://www.svdoerpum.de/senioren/1-herren/spielplan/teamplan

**Comment by svdoldie** [comment]
Beide Versionen

**Comment by diddipoeler** [comment]
Verstehe ich nicht. Bei mir funktioniert alles:
https://www.fussballineuropa.de/index.php/component/sportsmanagement/teamplan/0/0/106785:1-division-2021-22/70191:fc-helsingor/0/1627256:fc-helsingor

**Comment by ortwin20000** [comment]
Bei @svdoldie erhalte ich diese Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/15192502/138229044-bd130bff-a647-4ab8-b5cd-e37bfb6e4f9a.png)

Und bei @diddipoeler gehen bei mir die Buttons auch nicht.
```
jQuery("#btnPrint").printPreview({ 
  obj2print:'#teamplanoutput' 
}); 
```
Das liegt vermutlich an der fehlenden JQuery. Die Links wenn man auf die Mannschaften klickt gehen hier auch nicht und in der Konsole steht dann:
![grafik](https://user-images.githubusercontent.com/15192502/138229337-693f8c2e-6ed0-460b-8f82-9747337d053d.png)

**Comment by ortwin20000** [comment]
@diddipoeler 
Komisches Verhalten:
Wenn ich die Seite öfters lade wird sie unterschiedlich angezeigt:
![grafik](https://user-images.githubusercontent.com/15192502/138233424-7d2b0b6e-bbe1-4523-81fc-c321ff457a5f.png)
Das passiert bei mir wenn ich Browser die Seite mit STRG+F5 neu lade.
So funktionieren die Buttons und Links nicht und der Fehler mit JQuery wird ausgegeben. 

Wenn ich danach die Seite normal mit F5 lade:
![grafik](https://user-images.githubusercontent.com/15192502/138233681-aed55404-91fb-4bb9-ac59-7091a3c93b20.png)
Und dann funktionieren auch die Buttons.

Das ganze ist so bei mir mit STRG+F5 und F5 reproduzierbar.

**Comment by ortwin20000** [comment]
@svdoldie 
Das zweite Problem mit dem Button für die Vorschau liegt an der verwendeten View. Es gibt die Ansicht die @diddipoeler auf seiner Seite einsetzt (default) und deine Ansicht (sortiert nach Datum).
Default-View:
![grafik](https://user-images.githubusercontent.com/15192502/138236462-64ba9fd3-e3f3-4c7a-be97-9e1aeb682a98.png)

Sortiert nach Datum:
![grafik](https://user-images.githubusercontent.com/15192502/138236535-ae029836-2f89-4367-bb5a-1b12fa1cdb51.png)

Der Vorschau-Button geht aber auf die ID teamplanoutput und die findet er bei deiner Ansicht nicht.

**Comment by svdoldie** [comment]
Ich würde gut finden, wenn die Buttons auf beiden Ansichten funktionieren würden.
Oder das man die Buttons ansonsten ausblenden könnte
