### ISSUE TITLE
Modul Matches: Logos lassen sich nicht richtig konfigurieren

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1376]
Beide Felder zur Abgabe der Höhe bzw. Breite der Logos haben keinen bzw. nur teilweisen Einfluss. Die Breite wird nur bei der Gastmannschaft angepasst. Die Höhe hat irgendwie gar keinen Einfluss auf die Anzeige

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by diddipoeler** [comment]
Nur mal so nebenbei.
Ich glaube, dass ich alle Module überarbeiten muss, damit die Links funktionieren.

**Comment by svdoldie** [comment]
Das funktioniert jetzt :-) 👍 
Soll ich das jetzt hier überhaupt schließen?
