### ISSUE TITLE
Error after update from 3.9.0 to 3.9.20

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#1400]
I've tried to update my JSM version from 3.9.0 to last version. After that, i can not enter on my website and this error is shown
After that I've tried update to 3.9.10 and the same error is shown.
![error](https://user-images.githubusercontent.com/20923398/142861661-f6a4f255-68be-4a3a-b5e9-1555b471263d.png)

**Comment by diddipoeler** [comment]
Im Backend der Komponente unter Installatiostools -> Updates aufrufen.
Die Datei: jsm_update_db_tables.php ausführen.

**Comment by llambion72** [comment]
I did it and now it works!! Thank you!!
