### ISSUE TITLE
Can't be unlocked: Maintenance: Global Check-in

### ISSUE THREAD

**Issue by Rogackis** [diddipoeler/sportsmanagement#1403]
Initial data entry

	1. JSM Panel master data >> Events >> New >> Create new event type

Next…

	2. JSM Panel master data >> Positions >> New >> Create a new position

Next…

	3. Assigning events of position

Next…

	4. Save&Close

Action results in …

	1. System >> Global Check-in 1 >> Maintenance: Global Check-in

Items to check-in: …_sportsmanagement_position_eventtype table 

Can't be unlocked!!!

Why?  :)

Joomla 4.0.4, JSM Version: 3.9.20, Wampserver 3.2.6, PHP 7.4.26

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
