### ISSUE TITLE
J4: Ansicht Tabelle: Tabs werden nicht angezeigt

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1415]
In der Ansicht Tabelle werden die Tabs für Heim-, Auswärts-, Hin- sowie Rückrundentabelle nicht angezeigt

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Läuft. Danke 👍

**Comment by svdoldie** [comment]
Ich muss das noch mal öffnen. Die Tabs werden nur angezeigt, wenn man die Ansicht Tabs in den FE-Einstellungen wählt.
Damit werden in J3 nur die Tabs googlemap, notes usw. eingeschaltet, die verschiedenen Tabellen werden im Bereich "erweiterte Optionen" konfiguriert. Wäre super , wenn das mit J4 genauso gehen würde

**Comment by svdoldie** [comment]
läuft jetzt 👍
