### ISSUE TITLE
Mannschaftsbeschreibung wird nicht im Frontend angezeigt

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1420]
Möchte man weitere Informationen zu einer Mannschaft anzeigen lassen,
öffnet sich zwar der Bereich, aber die im Backend gespeicherten Infos werden nicht angezeigt.
Gilt für beide Joomlaversionen

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
J3: Teaminfo ist nur noch ein leeres Feld, siehe https://www.svdoerpum.de/senioren/1-herren/teaminfo
J4: Mannschaftsbeschreibung wird nicht angezeigt
Eingetragen ist etwas, siehe Bild
![Screenshot 2022-04-03 192418](https://user-images.githubusercontent.com/2417767/161440173-c7bf048a-fa96-4f7b-b5b1-66dc812ca38f.png)

**Comment by svdoldie** [comment]
J3: Ich muss mich korrigieren. Das scheint ein Problem mit meinem Joomla-Template zu sein. Mannschaftsbeschreibung wird aber wie bei J4  nicht angezeigt

**Comment by diddipoeler** [comment]
Mach mal bitte ein Update.
Bei mir sieht es jetzt so aus:
https://www.fussballineuropa.de/index.php/component/sportsmanagement/teaminfo/0/0/55929:bezirksliga-schwerin-ddr-1989-90/57193:bsg-hydraulik-parchim/1753798:bsg-hydraulik-parchim

**Comment by svdoldie** [comment]
läuft 👍
