### ISSUE TITLE
Ergebnis Eingabe Frontend

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1421]
zu der Ergebnis Eingabe im Frontend hätte ich eine Anliegen:

Der Spielplan wird ja normal von der Ligaleitung erstellt, die diesen auch nur ändern soll (z.B. Verlegungen neu terminieren)
Die Ergebniseingabe kann dann ja duch die jeweiligen Kapitäne erfolgen.

Das bei der Frontend Eingabe alle Felder (Heim/Gast/Spieltag) zur Änderung offen sind, finde ich etwas unglücklich.
Auch das man noch alle Ergebnisse (auch rückwirkend) ändern kann.
Vielleicht könnte man im Backend einen Schalter für die Ligaleitung einbauen, die die Ergebnisse nach Spielbericht bestätigt + das Spielergebnis dann im Frontend nicht mehr änderbar ist.

**Comment by StefanKemner** [comment]
Ich habe grade noch festgestellt, das man in den Konfigurations Einstellungen von JSM unter Berechtigungen ganz unten "JSM Ergebnisse - Ergebnisse speichern " für Benutzer erlauben kann, das aber leider nicht funktioniert

**Comment by StefanKemner** [comment]
Im Projekt kann ich ja nur einen Administrator und einen Editor angeben. Mit der Zuweisung der entsprechenden Berechtigungsgruppe scheint es zu funktionieren, das registrierte Benutzer im FE auch Ergebnisse ändern können.
Ja, es sollten auch mehrere sein, die Ergebnisse speichern können.

**Comment by diddipoeler** [comment]
Alles gut. Gebt mir mal ein bisschen Zeit. Ich muss was programmieren.

**Comment by StefanKemner** [comment]
Irgendwie habe ich da noch einen Knoten drin. wenn ich in der Konfiguration einer Benutzergruppe nur "JSM Frontend Ergebnisse - Ergebnisse speichern" erlaube, haben die trotzdem noch Zugriff auf die Paarungen.

**Comment by diddipoeler** [comment]
So bin mit der Programmierung fertig.
Jetzt müsste ich noch eine Dokumentation schreiben oder ein Video drehen.

**Comment by StefanKemner** [comment]
Das sieht schon mal sehr gut aus, nur die Ergebnisfelder offen :-))) Top 
Leider kommt noch eine Fehlermeldung, wenn ich einem Benutzer nur Berechtigung für Ergebnisse im Frontend ändern gebe, eine Ergebnis eingebe und auf speichern klicke:
sportsmanagementModelResults::saveshort 1037 Column 'projectteam1_id' cannot be null
sportsmanagementModelResults::saveshort 1038 1048

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Geht leider noch nicht, Fehlermeldung ist dieselbe.
Ergebnis wird auch nicht gespeichert.

**Comment by StefanKemner** [comment]
Ein Zusatz noch zu der Frontend Ergebnis Eingabe:
Die Eingabe der Zwischenergebnisse, auch mit entsprechender Berechtigung, funktioniert leider nicht, Ergbnisse werden nicht gespeichert:
![grafik](https://user-images.githubusercontent.com/101453485/164968988-e1988275-c1ec-4fc4-812d-e4bfd8339fde.png)
