### ISSUE TITLE
Frontend Ergebnis Eingabe, Spieldetails

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1422]
wenn man bei der Ergebniseingabe auf Spieldetails -> Spielbericht geht, dort etwas eingibt, kommt beim Speichern die Fehlermeldung:
1048 Column 'decision_Info' cannot be null

**Comment by diddipoeler** [comment]
Joomla 3 oder Joomla 4 ?

**Comment by StefanKemner** [comment]
Joomla 4

**Comment by svdoldie** [comment]
Das Update läuft bei mir nicht durch, siehe Bild
![Screenshot 2022-03-30 191513](https://user-images.githubusercontent.com/2417767/160893441-4652691d-8c70-4ff6-9fa5-c2a07b648986.png)

**Comment by svdoldie** [comment]
Bei Joomla 3 sieht's so aus
![Screenshot 2022-03-30 191837](https://user-images.githubusercontent.com/2417767/160893899-fc2d4a83-0cc7-4503-8dd7-46095584c6f1.png)

**Comment by diddipoeler** [comment]
Bitte über Github Update.

**Comment by svdoldie** [comment]
Läuft 👍

**Comment by svdoldie** [comment]
@StefanKemner : Wenn es auch bei dir funktioniert, schließt du bitte den Issue ?
