### ISSUE TITLE
Joomla 4: Datumsanzeige bei Spielen

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1423]
Die Datumsanzeige bei den Spielen zeigt leider nur den Tag an, aber nicht mehr. Einstellungen über das Template backend_matches bringen leider auch keine Verbesserung:
![grafik](https://user-images.githubusercontent.com/101453485/160848334-11668692-640e-419d-aa30-867eba18e51c.png)

**Comment by diddipoeler** [comment]
Wenn es Joomla 4 ist, dann bitte das Menü einklappen.

**Comment by StefanKemner** [comment]
Ist eingeklappt.
Bei den Spieltagen sieht das Datum besser aus:
![grafik](https://user-images.githubusercontent.com/101453485/161378897-2bbfe37c-109b-4ac6-a289-474a17ec6ff3.png)

**Comment by diddipoeler** [comment]
Das hat etwas mit den Bootstrap Funktionalitäten zutun.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
Wenn es Joomla 4 ist, dann bitte das Menü bei den Spielen einklappen.

**Comment by StefanKemner** [comment]
Leider keine Veränderung.
![grafik](https://user-images.githubusercontent.com/101453485/161414701-9f2e5377-042c-4806-b8f3-fc994a7afeca.png)

**Comment by diddipoeler** [comment]
![Datum](https://user-images.githubusercontent.com/1028107/162563980-2e3c68e4-eaa2-4f6a-86c8-07902c9f0c5f.png)
![Uhrzeit](https://user-images.githubusercontent.com/1028107/162563992-3896f709-566b-4965-beea-0d266514fad1.png)
Ich hoffe das ich das jetzt den Wünschen entsprechend umgesetzt habe.
Klick in das Datumsfeld wird der Kalender geöffnet und ein Klick in
das Feld mit der Uhrzeit öffnet eine Uhr zur Einstellung der Anstoßzeit.
Bitte einmal testen.

**Comment by StefanKemner** [comment]
Ja, das ist super 👍 Datum des Spiels sofort zu erkennen.
