### ISSUE TITLE
J4: Seitennavigation + Ansicht Tabellen 

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1427]
Wenn man den Menüeintrag "Tabellenanzeige" im Template "ranking" auf "Tabs anzeigen" auf Tabs stellt, sieht es so aus:
![grafik](https://user-images.githubusercontent.com/101453485/161224996-18ba722e-5e41-4e28-9a3d-c123f22f8cb0.png)

Bei Umstellung "Tabs anzeigen" auf "normal", wird gar keine Navigation angezeigt.

Der Menüeintrag "Ergebnis-Tabellen Anzeige" sieht auch etwas merkwürdig aus:
![grafik](https://user-images.githubusercontent.com/101453485/161224816-4f12cc1e-48a1-49d5-a251-672fe0cde6b1.png)
![grafik](https://user-images.githubusercontent.com/101453485/161224841-8bcd4261-66df-42b0-ae33-9c89034f5b2d.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
"Tabs anzeigen" normal sieht jetzt so aus:
![grafik](https://user-images.githubusercontent.com/101453485/161246756-cb2760cf-ffdf-49c5-a630-b85abc454b92.png)
Allerdings zeigen Änderungen der Einstellungen im Template "ranking" Tabelle anzeigen, Goolge Map anzeigen und Farblegende anzeigen keine Wirkung.
Tabs anzeigen, Tabs -> keine Änderung
Menüeintrag "Ergebnis-Tabellen Anzeige" -> keine Änderung

**Comment by diddipoeler** [comment]
Bei der Einstellung mit Tabs soll auch alles so bleiben wie es angezeigt wird.

**Comment by StefanKemner** [comment]
ok.
Der Menüeintrag "Ergebnis-Tabellen Anzeige" zeigt folgendes Bild, wenn man auf Ergebnisse geht. Das Feld für die Spieltagsauswahl überdeckt da den Tab "Tabellen"
![grafik](https://user-images.githubusercontent.com/101453485/161530919-7514b871-45a5-4941-90c6-4c470c562e8a.png)
