### ISSUE TITLE
J4: Live Ticker für Spiele

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1428]
In den Einstellungen des Moduls liest sich das so, das z.B. auch unregistrierte User etwas posten können.
Das Modul wird mit den Paarungen zwar richtig angezeigt, aber eine Eingabe Möglichkeit (oder Chat Fenster) gibt es da jetzt nicht.

**Comment by sigal** [comment]
Die Chatfunktion musste stillgelegt werden. 
Die verwirrende Erklärung wird demnächst entfernt!
