### ISSUE TITLE
J4: Teampielplan erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1431]
Bei der Anzeige des Teamspielplans wird folgende Fehlermeldung angezeigt:
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') OR pt2.division_id IN () OR m.division_id IN () ) AND r.project_id = 81 ...' at line 13
siehe https://joomla40.svdoerpum.de/index.php/senioren/1-herren/spielplan/teamplan/0/9:2021-2022/81:verbandsliga-nord-2021-2022/0/13:sv-doerpum
Solche Fehlermeldung erscheint bei jedem Projekt.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Noch keine Änderunge

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
Ist das eigentlich eine Liga mit Gruppen ?

**Comment by svdoldie** [comment]
Jetzt ist die Fehlermeldung weg und ein Spielplan wird auch angezeigt. Allerdings nicht nur vom ausgewählten Team sondern alle Spiele

⁣BlueMail for Android herunterladen ​

Am 2. Apr. 2022, 11:49, um 11:49, diddipoeler ***@***.***> schrieb:
>Bitte noch einmal testen.
>Ist das eigentlich eine Liga mit Gruppen ?
>
>--
>Reply to this email directly or view it on GitHub:
>https://github.com/diddipoeler/sportsmanagement/issues/1431#issuecomment-1086604162
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by sigal** [comment]
https://joomla40.svdoerpum.de/index.php/senioren/1-herren/tabelle/teamplan/0/0/81:verbandsliga-nord-2021-2022/13:sv-doerpum/0/1127:sv-doerpum

**Comment by svdoldie** [comment]
Nach erneutem Speichern der Menüpunkte läuft's 👍
