### ISSUE TITLE
J4: Matchreport

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1432]
* Zugeordnete Artikel aus den Spielen werden nicht angezeigt
* Bei Einstellung "Tabs abzeigen" -> Slider verschwindet die Auswahl beim Anklicken

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Die Slider funktionieren bei mir 👍 
Zu den Artikeln. Ich kann gar keine auswählen, obwohl reichlich da sind.
Müssen die in einer bestimmten Kategorie gespeichert werden?

**Comment by StefanKemner** [comment]
In den Projekteinstellungen eine Kategorie zuordnen
![grafik](https://user-images.githubusercontent.com/101453485/161473165-2944a72c-e8fe-4fd1-8b8c-75ba1d71b164.png)
https://jsm-wiki.diddipoeler.de/index.php?title=SM-Frontend:Matchreport

**Comment by svdoldie** [comment]
Danke 👍  Die Artikel kann ich jetzt auswählen, sie werden allerdings nicht angezeigt

**Comment by diddipoeler** [comment]
Oh, da habe ich noch eine Erläuterung vergessen.
Für die Artikel eine Kategorie erstellen. Z.B. JSM-Matchreport
Dann bitte ein Feld anlegen mit der Bezeichnung: **jsmmatchid**

Jetzt den Artikel in der Kategorie anlegen und in das Feld die Match-Id eintragen.

Oder in der Übersicht der Spiele zum Spieltag unter der Überschrift: **Spiel - Artikel** den Artikel zuordnen.

**Comment by svdoldie** [comment]
Ich hab in der Übersicht der Spiele den Artikel zugeordnet, aber angezeigt wird er nicht

**Comment by svdoldie** [comment]
Mit k2 werden die Artikel angezeigt. 👍 
Eine Bitte habe ich noch. Können die Artikel bei beiden Varianten bei der Auswahl so sortiert werden,
dass die neuesten oben stehen?

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Läuft bestens 👍 :-)
