### ISSUE TITLE
J4: Anlegen Statistik

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1433]
Bei Neuanlage einer Statistik kommt eine Fehlermeldung.
Ereignis + Sportart waren vorher zugeordnet:
![grafik](https://user-images.githubusercontent.com/101453485/161414442-81689384-8873-4652-8937-a626018961ee.png)

**Comment by diddipoeler** [comment]
Joomla4 ist da sehr empfindlich.
Da muss ich wieder ein Update programmieren.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Top 👍 Geht.
