### ISSUE TITLE
J4: Buttons mit Mehrfachauswahl

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1434]
Bei Mehrfachauswahlen kann man nicht mehr alle Optionen auswählen.

Bsp.: Projekteinstellungen -> erweitert User
Nur noch die letzten beiden Punkte stehen zur Auswahl, wenn man auf den Button klickt:
![grafik](https://user-images.githubusercontent.com/101453485/161744397-c3c3c5ae-5bcf-4db3-8bd1-910e7308ce5e.png)

**Comment by Europekicker** [comment]
Kann ich bestädigen

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Funktioniert 👍
