### ISSUE TITLE
J4: Ereignisse erfassen/bearbeiten

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1435]
Beim Erfassen eines Ereignisses für ein Spiel kann man den ersten Eintrag speichern, beim Zweiten kommt:
Fehler 500 -> ok -> Internal server Error

Geht man auf "Weitere Ereignisse bearbeiten" kommt folgender Fehler:
![grafik](https://user-images.githubusercontent.com/101453485/161773480-690a7b88-70e6-4439-bb1b-edaf9c5356c2.png)

**Comment by StefanKemner** [comment]
Die Mehrfacheingabe des selben Ereignisses mit dem selben Wert für einen Spieler ist auch nicht möglich.

**Comment by diddipoeler** [comment]
Ist der Fehler jetzt behoben ?

**Comment by StefanKemner** [comment]
Der Fehler "Weitere Ereignisse bearbeiten" ist jetzt weg

Fehler 500 bei der 2. Erfassung ist noch da
Mehrfacheingabe des selben Ereignisses mit dem selben Wert für einen Spieler geht noch nicht

**Comment by StefanKemner** [comment]
Top 👍 Funktioniert einwandfrei
