### ISSUE TITLE
Wish: Darstellung Ereignisse

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1436]
In der Kaderanzeige (roster) wird die Anzahl der Ereignisse angezeigt:
![grafik](https://user-images.githubusercontent.com/101453485/161933398-5c2cc911-f259-49e5-aa51-ae19f6a11b47.png)
Es wäre schön, wenn das bei der Spielerinfo Anzeige (player) auch so wäre. Hier wird wohl eine Summe angezeigt:
![grafik](https://user-images.githubusercontent.com/101453485/161933875-616b7d47-33ad-4b9f-9a1b-443059b23bbc.png)

**Comment by StefanKemner** [comment]
2 Positonen angelegt: Damen + Herren
Herren Ereignis A+B zugeordnet, Damen Ereignis C+B zugeordnet.

Die Ereignis Tabelle zeigt alle Ereignisse korrekt an.
In der Spielerinformation werden jetzt nur die Ereignis Spalten der Herren angezeigt.

**Comment by diddipoeler** [comment]
Dabei geht es um Dart oder ?

**Comment by StefanKemner** [comment]
Richtig.

**Comment by diddipoeler** [comment]
Gibt es irgendeine Internetseite auf der ich mir das einmal anschauen kann?
Kann man sich irgendwo Beispiele anschauen?

**Comment by diddipoeler** [comment]
![gleiche-ereignisse](https://user-images.githubusercontent.com/1028107/162614292-0021853d-d36e-4d20-819a-e77b8a8dc50f.png)
Hoffentlich habe ich schon einmal den Anfang richtig verstanden.
Im Update der Komponente wird ein neues Feld angelegt, mit dem innerhalb des Projektes auch
doppelte Ereignisse zugelassen werden können.

Bitte einmal testen.

**Comment by StefanKemner** [comment]
Feld ist da. Sollte sich das schon irgendwo auswirken ?
Ereignis Eingabe bei einem Spiel bisher nicht.
https://github.com/diddipoeler/sportsmanagement/issues/1435

**Comment by diddipoeler** [comment]
Mann oh Mann was für ein gebastel.
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Sorry für die Mühe, aber Ereignis Eingabe mit doppelten Werten funktioniert top 👍

**Comment by diddipoeler** [comment]
![ereignisse-als-summe](https://user-images.githubusercontent.com/1028107/162724467-eea19473-d883-4e9a-b675-1bf0fd77301e.png)
Und wieder etwas Neues. Hier kann man jetzt einstellen ob die Summe oder die Anzahl des Ereignisses angezeigt werden soll.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Top 👍 Funktioniert super 🥇
