### ISSUE TITLE
J4: Spieldetails bearbeiten Backend

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1438]
Wenn in den Projekteinstellungen "Nutze Sätze" auf Ja steht, hat man in den Spieldetails -> Tordetails ein weiteres Feld: Sätze
![grafik](https://user-images.githubusercontent.com/101453485/162188827-772ea61f-cd2f-42e1-8fc6-560c481dddae.png)
![grafik](https://user-images.githubusercontent.com/101453485/162188911-b5328632-27e8-4a80-82b7-94b93043753f.png)
Die Vorbelegung der Felder Sätze scheint "NULL" oder leer zu sein.
Bei Neuanlage eines Spieles oder bei Spielen ohne Ergebnis werden Änderungen der Spieldetails nicht gespeichert, obwohl angezeigt
![grafik](https://user-images.githubusercontent.com/101453485/162190104-a0c26cc0-e6f2-4e52-859a-4c2c10aedc8c.png)
Übergangslösung besteht darin, in die Sätze-Felder eine "0" einzugeben, dann geht auch die Speicherung:
![grafik](https://user-images.githubusercontent.com/101453485/162190356-11b43282-e710-4793-8e4c-987448f5c62b.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Super 👍 Klappt
