### ISSUE TITLE
J4: Spieler anlegen Doppel

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1440]
Bei der Spieleranlage und der Auswahl "Person-Spielertyp" -> Doppel kommt es zu einer Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/101453485/163156988-f66960aa-0c86-4813-92ad-664ab2790402.png)
![grafik](https://user-images.githubusercontent.com/101453485/163157019-bd24bd1f-6086-410f-84b7-07f64249b594.png)

**Comment by diddipoeler** [comment]
Den Fehler habe ich nicht.
Bitte einmal in Joomla 4 System -> System debuggen auf Ja einstellen.
Dann noch einmal den Spieler anlegen. Dann erscheint auch als Fehlermeldung
der Dateiname mit der Fehlerzeile.

**Comment by StefanKemner** [comment]
![grafik](https://user-images.githubusercontent.com/101453485/163164476-f4f351b7-f26c-4035-97d1-6b35f38313f8.png)
![grafik](https://user-images.githubusercontent.com/101453485/163164498-f5b4ccdc-e97d-42eb-ad2b-0baea58f9776.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
