### ISSUE TITLE
Keine Spielerfotos in der Standard-Kaderanzeige 

### ISSUE THREAD

**Issue by TSVler05** [diddipoeler/sportsmanagement#1444]
Ich habe einem Projekt Mannschaften zugeordnet. Hinter unserer Mannschaft die Spieler hinterlegt. Diesen Spielern Fotos aus dem Ordner "Teamplayers" zugeordnet.
In der "Standard-Ausgabe" der Kaderanzeige werden mir die Spielerfotos nicht mit angezeigt. Er sucht bei dieser Ausgabe wohl im Ordner "Persons".
Ändere ich das Layout der  Kaderanzeige in "Spielerkarte" oder "Spieler Visitenkarte" dann werden mir die hinterlegten Fotos richtig angezeigt.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by ortwin20000** [comment]
Ich habe hierzu einen Pull-Request erstellt.
Bei manchen Templates gab es mehr als zwei Optionen aber aufgrund des Ja/Nein-Schalters konnte nur zwischen zwei ausgewählt werden. Dies habe ich umgestellt. Es kann die Option nun aus einer Liste ausgewählt werden. Zuvor konnte ich nur zwischen Spielerkarte und Visitenkarte umstellen. Die Standard-Ausgabe schien nicht auf.

Wegen dem Spielerbild:
In der Standard-Ausgabe war der Code für das Finden des Fotos im Vergleich zu den anderen beiden Views anders aufgebaut. Ich habe dies mal angepasst.

Bitte nach dem Einspielen des Pull-Request noch einmal testen.

**Comment by TSVler05** [comment]
Super, die Spielerfotos werden nun auch in der Standard-Ausgabe angezeigt. Danke!

**Comment by ortwin20000** [comment]
Super. Dann kann hier wohl zugemacht werden.
