### ISSUE TITLE
J4: Benutzeranmeldung Frontend

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1446]
Wenn sich im Frontend ein Benutzer mit Manager Rechten angemeldet und eine Spielerinformation aufrufen will, kommt folgende Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/101453485/164683663-8af4b1d9-63df-49f0-b766-9087b057c46f.png)
Ist man nicht angemeldet, kann man die Spielerinformationen auch ganz normal aufrufen.

Ist man als Editor oder Administrator (aus den Projekteinstellungen) angemeldet, funktioniert auch alles, bis man im Frontend das Symbol"Bearbeiten/ändern persönlicher Infromation" anklickt. Dann kommt der oben genannte Fehler auch.

**Comment by diddipoeler** [comment]
Bitte einmal den Debug Modus in Joomla einschalten, damit ich den Dateinamen und die Zeile bekomme.
Die Hardcopy bitte hier hinterlegen.

**Comment by StefanKemner** [comment]
![grafik](https://user-images.githubusercontent.com/101453485/164738486-b464f7d2-38cc-431b-9e79-fe2d011c88cf.png)
![grafik](https://user-images.githubusercontent.com/101453485/164738511-9970e7a9-eb86-4a24-ae69-901618691b1b.png)

**Comment by StefanKemner** [comment]
Der Aufruf von Spielerinformationen mit Manager Rechten funktioniert jetzt.

Der Bearbeitungsbutton im Frontend zeigt beim anklicken immer noch denselben Fehler, allerdings eine bei einer anderen Zeile, als vorher:
![grafik](https://user-images.githubusercontent.com/101453485/164886056-542bfccd-de94-44b0-82bb-acf82fb6d4c0.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Beim Aufruf zum ändern kommt jetzt diese Fehlermeldung
![grafik](https://user-images.githubusercontent.com/101453485/164969749-e1c64b2e-a2bd-4583-8856-1fa45785d40f.png)
![grafik](https://user-images.githubusercontent.com/101453485/164970057-0ad5c639-b30e-4ce9-bc94-f2e53cc6c3ae.png)
![grafik](https://user-images.githubusercontent.com/101453485/164970066-1eac75c8-51e7-45ef-b11b-961976517c3c.png)

**Comment by diddipoeler** [comment]
Den Fehler habe ich nicht.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Test mit Super User Rechten im Frontend, Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/101453485/204144363-cb76effd-e42e-403c-9ea3-3593a24d7537.png)

**Comment by StefanKemner** [comment]
Klappt jetzt 👍
