### ISSUE TITLE
J4: Zuordnung Spieler zu einem Projektteam

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1448]
Ordnet man Spieler zu einem Projektteam (Suchen, auswählen + dann speichern) zu, steht der 1. Spieler auf "Sichtbar im Projekt"-> Ja. Bei allen anderen dann auf "Nein".
D.h. man kann diese Spieler dann auch nicht in der Startaufstellung für ein Spiel verwenden.
![grafik](https://user-images.githubusercontent.com/101453485/165041244-1ec068f1-ecdb-4f92-aad9-ec85f7a6acb9.png)

**Comment by sigal** [comment]
Kann ich so nicht bestätigen.

**Comment by StefanKemner** [comment]
Hmm, also ich klicke auf speichern, bleibe in der Suchmaske und suche dann den nächsten Spieler.
Die nachfolgenden Spieler stehen bei mir dann alle auf "Sichtbar im Projekt" "Nein"

**Comment by sigal** [comment]
Bei einzelner Auswahl und speichern kann ich es nun bestätigen.
Wählt man mehrere Personen und speichert, werden alle gewählten Personen mit "Sichtbar im Projekt auf JA! gesetzt.

Die Zuordnung kann man aber leicht mit dem Regler auf "JA" setzen und mit Button "Änderungen übernehmen" bestätigen.

Muss nochmals überarbeitet werden.

**Comment by StefanKemner** [comment]
Das ist richtig.
Wenn man denn als Neueinsteiger darauf kommt, das es daran liegen könnte und man den Zoom im Browser soweit verkleinert, das man das Sichtbar Feld auch sehen kann :-)

**Comment by StefanKemner** [comment]
Funktioniert jetzt 👍
