### ISSUE TITLE
J4: Anzeige Mannschaften bei Sportstätten

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1449]
Mannschaften werden bei den Sportstätten (unter Vereinsmannschaften) nur angezeigt, wenn in den Projekteinstellungen der Mannschaft ein Administrator hinterlegt ist (obwohl kein Pflichtfeld).
![grafik](https://user-images.githubusercontent.com/101453485/165479910-041a08e4-d408-4c27-9d43-a26cf50c00e6.png)
Desweiteren werden Mannschaften (wenn Admin hinterlegt ist) dann mehrfach angezeigt, was vielleicht noch aus bereits abgelaufenen Saisons/Projekten resultieren könnte.

**Comment by svdoldie** [comment]
Kann ich bestätigen, wenn SEO eingeschaltet ist
Ohne SEO: https://joomla40.svdoerpum.de/index.php?option=com_sportsmanagement&view=playground&cfg_which_database=0&s=5:2018-2019&pgid=7&p=42:verbandsliga-nord-2018-2019&Itemid=423
Mit SEO:https://joomla40.svdoerpum.de/verein/sportplatz/playground/0/5:2018-2019/7/42:verbandsliga-nord-2018-2019

**Comment by diddipoeler** [comment]
Kommt die Anzeige aus einem Menüeintrag?

**Comment by diddipoeler** [comment]
> Kann ich bestätigen, wenn SEO eingeschaltet ist Ohne SEO: https://joomla40.svdoerpum.de/index.php?option=com_sportsmanagement&view=playground&cfg_which_database=0&s=5:2018-2019&pgid=7&p=42:verbandsliga-nord-2018-2019&Itemid=423 Mit SEO:https://joomla40.svdoerpum.de/verein/sportplatz/playground/0/5:2018-2019/7/42:verbandsliga-nord-2018-2019

Kommt der Eintrag aus dem Menü ?

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
geht jetzt 👍
