### ISSUE TITLE
J4: Fehler Alle Sportstätten in JSM

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1450]
Beim Aufruf des Menüpunktes "Alle Sportstätten in JSM" kommt folgender Fehler:
![grafik](https://user-images.githubusercontent.com/101453485/165769017-96aaa73b-0144-488d-9c49-c51a1beabae1.png)
![grafik](https://user-images.githubusercontent.com/101453485/165769046-48ab7a40-1a07-44a9-a366-f469d34b5599.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
