### ISSUE TITLE
J4: Spieler Info Aufruf Frontend (player)

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1452]
Wenn ich im Frontend als SuperUser angemeldet bin + mir Spielerinformationen aufrufen möchte, kommt folgende Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/101453485/167083567-a960fcff-70d1-4fef-a5ff-ae45dea34b17.png)
![grafik](https://user-images.githubusercontent.com/101453485/167083641-0a7e385b-7e7e-41f3-8a7f-81d6dccb78f5.png)
Bin ich nicht angemeldet, funktioniert das.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Funktioniert leider noch nicht:
![grafik](https://user-images.githubusercontent.com/101453485/167241865-f562592d-25d1-48b2-98bc-b2c5c4999aad.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Jetzt kommt ein anderer Fehler:
![grafik](https://user-images.githubusercontent.com/101453485/167248729-b834cb07-414e-406e-886b-40feeaa9669d.png)
![grafik](https://user-images.githubusercontent.com/101453485/167248741-42a69c69-372e-4758-9957-fcfefcc8bec6.png)
![grafik](https://user-images.githubusercontent.com/101453485/167248751-2f44638f-a27d-4df7-9a65-ff78ebb86420.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Top 👍 Klappt jetzt 👍
