### ISSUE TITLE
J4: Ereignis Tabellenanzeige

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1454]
Wenn man den Menüpunkt "Ereignis Tabellenanzeige" (eventsranking) aufruft, bei einem Ereignis auf "Zeige vollständige Tabelle" klickt, die Ereignisse jetzt länger als 1 Seite sind:
![grafik](https://user-images.githubusercontent.com/101453485/169063720-6694ba4a-0f76-4aa6-bdbf-f06c5d974a5a.png)
kommt man mit Klick auf die 2. Seite oder dem Pfeil nach rechts wieder zurück auf die Übersichtsseite aller Ereignisse, die jetzt aber alle keine Werte mehr anzeigen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Leider noch keine Veränderung

**Comment by diddipoeler** [comment]
Bei mir läuft es:
https://www.fussballineuropa.de/index.php/component/sportsmanagement/eventsranking/0/304/106847:2-bundesliga-2021-22/0/8:com-sportsmanagement-soccer-e-goal/0/0

**Comment by StefanKemner** [comment]
Gut, dann ist es wohl so.
Das Einzigste was mir aufgefallen ist, das bei mir unten die Seitenauswahl anders aussieht:
![grafik](https://user-images.githubusercontent.com/101453485/169695122-6c7eb7dd-cc50-4416-8875-e2ccf4217fad.png)
![grafik](https://user-images.githubusercontent.com/101453485/169695136-8465e560-7f8c-42d1-a4f1-41fcadc329c8.png)
