### ISSUE TITLE
J4: Ereignis-Tabellenanzeige

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1457]
Bei dem Menüpunkt "Ereignis-Tabellenanzeige" 
![grafik](https://user-images.githubusercontent.com/101453485/169995858-712017da-64fe-4ced-832f-6cadadfd6284.png)
hab ich so meine Probleme:
1. es werden alle Ereignisse angezeigt, die angelegt sind, egal ob veröffentlicht oder nicht. 
Auch werden Ereignisse angezeigt, die einer Position überhaupt nicht zugeordnet sind.
2. Bei dem Menüpunkt kann man eigentlich Ereignisse auswählen, dies hat aber keine Auswirkungen, es werden immer alle angezeigt.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Ist leider immer noch so.
Auch zeigt die Änderung der Reihenfolge der Ereignisse in den Stammdaten keine Wirkung.
Anscheinend werden die Ereignisse im Frontend nach Anlagereihenfolge dargestellt-
