### ISSUE TITLE
J4: Spieler oder Teamzuordnung zur Saison

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1458]
Wenn man Spieler oder Teams zu einer Saison zuordnen möchte und sich mehr als 20 Positionen oder auch alle anzeigen lassen will, springt er immer auf 20 zurück:
![grafik](https://user-images.githubusercontent.com/101453485/170024770-83f5b934-6181-43db-a6f8-9bd6084bc28f.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Bis auf den Auwahlpunkt "Alle" funktioniert es jetzt 👍
