### ISSUE TITLE
Unknown column 'tp.projectteam_id' in 'field list'

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#1460]
When i press on any player link in different modules, this error is shown
![2022 05 30 - JSM](https://user-images.githubusercontent.com/20923398/171025743-897d96e4-d941-4dd3-a232-7bb869f6155f.png)

I'm using last JSM Version 3.16 and last joomla 3 versión.

**Comment by diddipoeler** [comment]
Bitte ein Update der Komponente machen.
