### ISSUE TITLE
J4: Ansicht Fieberkurve: Es wird nur die erste Mannschaft angezeigt

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1461]
In der Ansicht Fieberkurve wird nur die erste ausgewählte Mannschaft angezeigt,
es sei denn denn man legt auch die zweite Mannschaft fest. Eine Änderung der Mannschaften im FE zeigt keine Wirkung.
Siehe https://www.svdoerpum.de/index.php?option=com_sportsmanagement&view=curve&cfg_which_database=0&s=9:2021-2022&p=81:verbandsliga-nord-2021-2022&tid1=13:sv-doerpum&tid2=0&both=1&Itemid=338

**Comment by svdoldie** [comment]
Mittlerweile wird zwar eine 2. Mannschaft angezeigt, allerdings kann man im FE keine Mannschaft wechseln.
Siehe https://www.svdoerpum.de/senioren/1-herren/saisonverlauf/curve/0/18:2022-2023/106:landesliga-schleswig-2022-2023/13:sv-doerpum/0/0

**Comment by StefanKemner** [comment]
Kann ich bestätigen.
Ich kann auch kein wirkliches Muster erkennen, nach welchen Kriterien die 2. Mannschaft ausgewählt wird.

**Comment by svdoldie** [comment]
Bei mir ist ein Muster zu erkennen. Es wird immer der kommende Gegner mit angezeigt.

**Comment by ortwin20000** [comment]
Ich habe einen Pull-Request erstellt.

Die Weiterleitung mit dem Button "Los!" hat die URL umgeschrieben.
Beim ersten Aufruf ist nur die 1. Mannschaft vorausgewählt und die zweite Mannschaft wird irgendwie (Logik hab ich noch nicht verstanden) vorausgewählt.
Die Fieberkurve selber zeigt somit am Anfang nur die 1. Mannschaft an.
Wird nun eine zweite Mannschaft ausgewählt, wird diese mit den Änderungen auch an die Hintergrundlogik übergeben und es sollte die Fieberkurve für zwei Mannschaften angezeigt werden.

Die beiden versteckten Felder habe ich auskommentiert:
```
<input type="hidden" name="tid1" value="<?php echo sportsmanagementModelCurve::$teamid1; ?>"/>
<input type="hidden" name="tid2" value="<?php echo sportsmanagementModelCurve::$teamid2; ?>"/>
```
und die ID der beiden Comobobxen habe ich abgeändert:
```
$team1select[$div->id] = HTMLHelper::_('select.genericlist', $options, 'tid1', 'onchange="" class="inputbox" style="font-size:9px;"', 'value', 'text', $teamid1);
$team2select[$div->id] = HTMLHelper::_('select.genericlist', $options, 'tid2', 'onchange="" class="inputbox" style="font-size:9px;"', 'value', 'text', $teamid2);
```

Bitte nach Einspielen noch einmal testen.

**Comment by svdoldie** [comment]
Funktioniert jetzt einwandfrei 👍
