### ISSUE TITLE
J4: Ereignis Eingabe Frontend Speichern geht nicht

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1462]
Bei "Ereignisse bearbeiten" im Frontend kann man zwar vorhandene Ereignisse löschen, aber leider keine neuen speichern.
Fehlermeldung wird auch nicht angezeigt, Debugger zeigt auch nichts an.
Spieldetails und Startaufstellung speichern funktioniert.
Im Frontend bin ich als Super User angemeldet.

Im Backend funktioniert das tadellos.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Jetzt bekomme ich Fehler 500, Internal Server Error beim Speichern

**Comment by StefanKemner** [comment]
Jetzt kommt Fehler 500, Internal Server Error beim Speichern

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Wir sind auf einem guten Weg 👍 
Das Speichern funktioniert jetzt, nur leider werden die Ereignisse doppelt gespeichert.
Also, 2 Zeilen mit demselben Spieler und dem gleichen Ereigniswert.

**Comment by StefanKemner** [comment]
Korrektur zum ltz. Post: es wird eine 2. Zeile OHNE Ereigniswert angelegt, nur mit Spielernamen

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Leider noch keine Änderung:
Beim speichern eines Ereignisses werden 2 Zeilen angelegt, die 2. Zeile ohne Wert

**Comment by diddipoeler** [comment]
Der Fehler tritt nur in Jommla 4 auf.

**Comment by diddipoeler** [comment]
Der Fehler tritt nur auch bei Jommla 3 auf.

**Comment by StefanKemner** [comment]
Leider noch keine Änderung, 2. Zeile wird immer noch angelegt :-(

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Leider noch keine Änderung.
Komischerweise funktioniert das im Backend..

**Comment by diddipoeler** [comment]
Bei mir funktioniert es im Frontend und Backend. Ich schaue mir das morgen mal auf Ihrer Homepage an. Von meinem Huawei-Tablet gesendet-------- Ursprüngliche Nachricht --------Von: Stefan K ***@***.***>Datum: Do., 2. Feb. 2023, 15:21An: diddipoeler/sportsmanagement ***@***.***>Cc: diddipoeler ***@***.***>, Comment ***@***.***>Betreff: Re: [diddipoeler/sportsmanagement] J4: Ereignis Eingabe Frontend Speichern geht nicht (Issue #1462)

Leider noch keine Änderung.

Komischerweise funktioniert das im Backend..

**Comment by diddipoeler** [comment]
Im Augenblick breche ich mir echt die Ohren, warum es bei mir funktioniert.

**Comment by StefanKemner** [comment]
Wie gesagt, wenn's nicht geht, so lassen.

**Comment by StefanKemner** [comment]
Durch Spielpause über Ostern kann ich leider nicht sagen, ab welcher neuen Version da so ist:

Wenn man die Ereigniseingabe im Frontend aufruft, wird das Heimspiel und der 1. Spieler angezeigt.
Hat man ein Ereignis gespeichert, sind die Felder Mannschaft + Spieler leer:
![grafik](https://user-images.githubusercontent.com/101453485/233775757-3690d1ee-8c40-4239-b284-af31959737f5.png)

Sehr umständlich die Daten jedesmal neu auswählen zu müssen. Vorher blieben Mannschaftsname + Spieler in den Feldern drin.

**Comment by StefanKemner** [comment]
Da ortwin20000 ja hier momentan sehr aktiv ist, wäre es schön, wenn er da mal gucken könnte.
Wir haben jeden Spieltag so einige Ereignisse einzugeben.

Aktueller Stand ist: bei der Ereigniseingabe im Backend wird 1 Zeile angelegt. (was ja auch so sein soll)
Macht man dasselbe im Frontend, legt er zusätzlich eine 2. Zeile an, die man dann manuell wieder löschen muß.

Und wie beim ltz. Post hier schon geschrieben: wenn man ein Ereignis gespeichert hat, wird das Feld  Mannschaft + Spieler gelöscht. Sonst sind die vorherigen Daten drin geblieben, was einfacher war, da ein Spieler mehrere Ereignisse haben kann.
Vielen Dank 👍

**Comment by ortwin20000** [comment]
Ich schau mir das morgen an. Bin heute selber sportlich im Einsatz.

**Comment by ortwin20000** [comment]
Da ich selber noch nichts mit Ereignissen gemacht habe muss ich mir das erst in der Testumgebung einrichten.
Falls notwendig, wäre es auch möglich mir das per Teamviewer oder dergleichen zu zeigen?

**Comment by StefanKemner** [comment]
Ich kann dir auch Zugangsdaten zu meiner Testumgebung schicken, brauche ich nur deine E-Mail Adresse.
Anydesk hätte ich bei Bedarf an zubieten :-))

**Comment by ortwin20000** [comment]
Ich muss das bei mir nachstellen. Anydesk ginge auch.

**Comment by StefanKemner** [comment]
Okay 👍

**Comment by ortwin20000** [comment]
Bei mir funktioniert das nicht wirklich mit den Ereignissen. Bei dem Versuch der Eingabe wird mir das Fenster als neues Fenster geöffnet und die Ereignisse die ich dort eingebe werden mir zwar in der gleichen Maske angezeigt aber wo werden diese danach angezeigt? Im Backend ist es ein Popup.

Was mir jedoch aufgefallen ist:
components\com_sportsmanagement\views\editmatch\tmpl\editevents.php Zeile 191
```
<input id="save-new-event"
                               onclick="save_new_event(<?php echo implode(",", $savenewcomment); ?>)" type="button"
                               class="inputbox button-save-event" value="<?php echo Text::_('JSAVE'); ?>"/>
```
Dort wird in der onclick der Aufruf mit save_new_event durchgeführt.
Jetzt gibt es aber zwei JS-Dateien: diddioeler.js und editmatch.js
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/15192502/88161293-c050-47da-9158-9b543a532b88)
Beide beinhalten eine save_new_event. Einmal mit Parametern und einmal ohne.
Zusätzlich wird in der diddioeler.js jedem Button mit der Klasse "button-save-event" die Funktion save_new_event() angehängt.
```
// neues ereignis speichern  
$(".button-save-event").on('click', function(event){
    save_new_event();
});	
```
Das verursacht Mehrfach-Aufrufe die ich mit dem Debugger feststellen konnte.

Was du mal ausprobieren könntest:
Ersetze in der editevents.php
```
<input id="save-new-event"
                               onclick="save_new_event(<?php echo implode(",", $savenewcomment); ?>)" type="button"
                               class="inputbox button-save-event" value="<?php echo Text::_('JSAVE'); ?>"/>
```
mit
```
 <input id="save-new-event"
                               type="button"
                               class="inputbox button-save-event" value="<?php echo Text::_('JSAVE'); ?>"/>
```
Wird dann noch immer eine zweite Zeile erstellt?

**Comment by StefanKemner** [comment]
Was du mal ausprobieren könntest:
Ersetze in der editevents.php

<input id="save-new-event"
                               onclick="save_new_event(<?php echo implode(",", $savenewcomment); ?>)" type="button"
                               class="inputbox button-save-event" value="<?php echo Text::_('JSAVE'); ?>"/>

mit

 <input id="save-new-event"
                               type="button"
                               class="inputbox button-save-event" value="<?php echo Text::_('JSAVE'); ?>"/>

Wird dann noch immer eine zweite Zeile erstellt?
>> Top das funktioniert 👍 👍 2. Zeile ist weg

**Comment by StefanKemner** [comment]
Nachtrag:
Wenn du in der diddioeler.js noch folgende Anpassung machst ab Zeile 132

jQuery("#ajaxresponse").addClass("ajaxsuccess");
jQuery("#ajaxresponse").text(resp[1]);
jQuery("#notice").val('');
jQuery("#event_time").val('');
jQuery("#event_sum").val('');
jQuery("#teamplayer_id").val('');
jQuery("#team_id").val('');
}
else 
{
jQuery("#ajaxresponse").addClass("ajaxerror");
jQuery("#ajaxresponse").text(resp[1]);
jQuery("#notice").val('');
jQuery("#event_time").val('');
jQuery("#event_sum").val('');	
jQuery("#teamplayer_id").val('');
jQuery("#team_id").val('');
} 
...
Das hat leider noch keine Änderung ergeben.
Aber da kann ich so mit leben, da bei Teamauswahl gleich der 1. Spieler automatisch angezeigt wird.

**Comment by diddipoeler** [comment]
Änderungen eingebaut.

**Comment by StefanKemner** [comment]
Super 👍
