### ISSUE TITLE
PHP 8: Fehler Ergebnisanzeige

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1464]
Bei Aktivierung von PHP 8.16 kommt folgender Fehler beim Aufruf des Menüpunktes Ergebnisanzeige (results)
![grafik](https://user-images.githubusercontent.com/101453485/173365405-07a50485-7162-4a79-9bb8-f8b7b88fc4e0.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Funktioniert leider noch nicht:
![grafik](https://user-images.githubusercontent.com/101453485/173509342-da878e93-4cd9-4cb7-868e-5fe1368f7747.png)

**Comment by diddipoeler** [comment]
Ich bekomme den Fehler nicht.

**Comment by sigal** [comment]
Ich bekomme den Fehler auch nicht.
Test mit folgenden PHP-Versionen.
7.4.30
8.0.20
8.1.7

Joomla! 3.9.10
Joomla! 4.1.5

**Comment by svdoldie** [comment]
Hast du mal ein Update der DB-Einträge von JSM versucht?
![Anmerkung 2022-06-22 111751](https://user-images.githubusercontent.com/2417767/174992776-209c6ca0-de21-4b5f-a9b5-9fa9bb45026a.png)

**Comment by StefanKemner** [comment]
jetzt wirds ganz merkwürdig: wenn ich im Menüpunkt einen festen Spieltag angebe, ist der Fehler weg:
![grafik](https://user-images.githubusercontent.com/101453485/174999241-da038985-3eaf-4215-9040-5403cdd409c6.png)

**Comment by svdoldie** [comment]
Kann ich leider nicht bestätigen, siehe https://joomla40.svdoerpum.de/index.php?option=com_sportsmanagement&view=results&cfg_which_database=0&s=18:2022-2023&p=104:kreispokal&division=0&r=0&Itemid=4606
IF Tönning spielt gegen niemanden. Eingestellt ist PHP 8.1.7

**Comment by sigal** [comment]
svdoldie fährt die Website ohne Suchmaschinen-freundliche URL.

Darum der andere Linkaufbau!

Schick mir die Liga an stony@jsm-help.de.
Ich teste sie mal.

**Comment by sigal** [comment]
versteh ich nicht.
dann siga@live.at

**Comment by StefanKemner** [comment]
Tja, keine Ahnung, was dann das Problem ist.
