### ISSUE TITLE
PHP 8: Fehler Spielerdetails anzeigen 

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1465]
Klickt man auf den Link von einem Spieler für weitere Details (player) kommt folgende Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/101453485/173367781-f625d017-705f-4a48-aa25-d1a593a3a19c.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Funktioniert 🥇
