### ISSUE TITLE
DFBnet-Import: Liga und Saison lassen sich nicht auswählen

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1466]
Beim DFBnet-Import lassen sich Liga und Saison nicht mehr auswählen,
sondern man muss beides neu erstellen lassen.

**Comment by svdoldie** [comment]
![Anmerkung 2022-06-21 084958](https://user-images.githubusercontent.com/2417767/174734921-386635bc-7d42-4936-bac1-023bbc6d3f4e.png)
Hier mal ein Screenshot

**Comment by svdoldie** [comment]
Ein weiteres Problem tritt auf bei PHP8:
8.0.14 : Es ist ein Fehler aufgetreten. 0 Cannot access offset of type string on string 
8.1.7: Es ist ein Fehler aufgetreten. 0 Non-static method sportsmanagementHelper::_addToXml() cannot be called statically
Jeweils mit J4

**Comment by sigal** [comment]
Kann ich bitte eine Importdatei haben?

**Comment by svdoldie** [comment]
Ich habe dir zwei geschickt 👍

**Comment by svdoldie** [comment]
Das Problem scheint nur J4 zu betreffen

**Comment by tdittmann** [comment]
Ist das noch aktuell? Bei mir hat es heute Mittag funktioniert

**Comment by svdoldie** [comment]
Ja, das geht bei mir nach wie vor nicht

**Comment by svdoldie** [comment]
Was die Saison betrifft funktioniert das Auswahlmenü, wenn die Saison, die in der Datei mitgegeben wird, in JSM vorhanden ist.
Für die Liga gilt das leider nicht. Insgesamt führt das dazu, dass man einerseits auf das Format der Saison aus der Importdatei (22/23) festgelegt ist und kein eigenes Format 2022/2023 verwenden kann. Und das Ligen doppelt angelegt werden.

**Comment by ortwin20000** [comment]
Wenn nichts dagegen spricht werde ich die Liga und Saison immer auswählbar machen.

**Comment by ortwin20000** [comment]
Ich habe einen neuen Pull-Request erstellt.
Bitte damit dann noch einmal testen.

**Comment by svdoldie** [comment]
Das klappt jetzt soweit 👍 
Allerdings habe ich bei meinem Versuch die Situation, dass ich mehrere Mannschaften so konfiguriert habe ,
dass sie nicht neu angelegt werden, sondern die bereits in der DB vorhandene.
Beim Import erscheint nun folgende Fehlermeldung:
![image](https://github.com/diddipoeler/sportsmanagement/assets/2417767/3e70267d-5862-48eb-8c23-c96e477101c6)
Der Import bricht dabei ab

**Comment by ortwin20000** [comment]
Du hast in deiner DB unterschiedliche Collations der Tabellen.
utf8_general_ci, utf8mb4_general_ci und utf8mb4_unicode_ci

Und da dürfte es bei einer Abfrage zwischen zwei Tabellen mit unerschiedlicher Collation zu Problemen kommen.
Bei mir ist der Fehler nicht aufgetreten.

Sollten die Tabellen nicht alle der gleichen Collation zugewiesen sein?

**Comment by ortwin20000** [comment]
Mir ist noch aufgefallen, dass die Liga nicht automatisch ausgewählt wird, sofern sie bereits vorhanden sein sollte.
Liegt daran, dass in der Datei administrator\components\com_sportsmanagement\models\leagues.php die Methode getLeagues() am Ende der Name umgeschrieben wird:
`$league->name = Text::_($league->name).' ('.$league->league_level.')';`

Somit kann er die Liga aus der Importdatei nicht mit der Liga aus JSM vergleichen.
Z.B. Importdatei "Kreisklasse A - N2" gegen JSM "Kreisklasse A - N2 (0)"

**Comment by ortwin20000** [comment]
Können wir hier zumachen?

**Comment by svdoldie** [comment]
Ja, läuft jetzt wieder alles :+1: :+1: :+1:
