### ISSUE TITLE
J4: Anlage neue Mannschaft

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1468]
Wenn man unter Stammdaten eine neue Mannschaft anlegen will, erscheinen automatisch auf dem Reiter "Training" alle Trainingszeiten, die man bisher für alle Teams angelegt hat.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Test momentan leider nicht möglich: https://github.com/diddipoeler/sportsmanagement/issues/1516

**Comment by StefanKemner** [comment]
Funktioniert 👍
