### ISSUE TITLE
Position einer Teamperson wird nicht gespeichert

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1471]
Ordnet man einer Person man in einem Projekt eine Position zu oder ändert diese,
wird diese Änderung nicht gespeichert.

**Comment by svdoldie** [comment]
Mittlerweile wird zwar die Änderung gespeichert, aber es kommt beim speichern jetzt folgende Fehlermeldung:
![Uploading Screenshot 2023-03-19 093603.png…]()

**Comment by ortwin20000** [comment]
Ich kann den Fehler nachvollziehen.
Wenn man zum ersten Mal in die Zeile klickt wird die Checkbox aktiviert. Klickt man noch einmal in die Zeile wird sie wieder deaktiviert.
Klickt man zuerst auf die Combobox zur Positionsauswahl wird dadurch die Checkbox aktiviert und beim nächsten Klick der Auswahl der Position wird die Checkbox aber zusätzlich wieder deaktiviert. Beim Speichern kommt dann die Fehlermeldung weil kein Datensatz zum Speichern ausgewählt wurde.
Wenn ich manuell die Checkbox klicke und dann speichere funktioniert es.

Da passt die Logik nicht. Das gleiche Verhalten habe ich auch in anderen Views wie z.B. projectteams, rounds.
In der View matches funktioniert es aber wie gewünscht.

**Comment by diddipoeler** [comment]
Ich schaue mir das mal in Ruhe an.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
ja, ich mach hier auch zu :+1:
