### ISSUE TITLE
FE: Kader wird nicht angezeigt

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1472]
Bei meinen neuen Projekten werden die Personen im Kader nicht angezeigt,
obwohl laut Backend alles richtig gespeichert ist. Siehe Bild
![Anmerkung 2022-06-29 100115](https://user-images.githubusercontent.com/2417767/176384528-dbbb0a18-0871-4678-a291-a469478bcfde.png)
Link zum FE : 
https://www.svdoerpum.de/index.php?option=com_sportsmanagement&view=roster&cfg_which_database=0&s=18&p=104:kreispokal-2022-2023&tid=13:sv-doerpum&ptid=1365&Itemid=137

**Comment by StefanKemner** [comment]
Ist bei mir zur neuen Saison auch so.

**Comment by PhantoSGE** [comment]
Der Fehler besteht leider noch immer

**Comment by PhantoSGE** [comment]
Konnte das Problem bei mir manuell lösen. Aus irgendeinen Grund, den ich nicht nachvollziehen kann, wurden die Teams einer SaisonID hinzugefügt die nicht existiert. Warum eine ID in der Reihenfolge fehlt kann ich nicht beantworten.

**Comment by svdoldie** [comment]
Das wäre ja super, wenn das gelöst werden könnte!!! 👍

**Comment by ortwin20000** [comment]
Wie sind die Schritte um dies nachzuvollziehen?
Bei deinem Link https://www.svdoerpum.de/index.php?option=com_sportsmanagement&view=roster&cfg_which_database=0&s=18&p=104:kreispokal-2022-2023&tid=13:sv-doerpum&ptid=1365&Itemid=137 sehe ich doch alle zugeordneten Spieler.

**Comment by ortwin20000** [comment]
Das erste was mir hier bei Spieler Marvin Hansen aufgefallen ist:
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/15192502/0ad8ae35-a3a9-4bb3-a539-06d6fcc5f322)

Ich hätte das jetzt mal auf JA gesetzt. Angezeigt wird er mir aber trotzdem nicht.
Wäre es möglich, dass ich mir dies auf der Datenbank anschaue was der Unterschied z.B. zwischen Marvin Hansen und Stefan Hansen ist?

**Comment by svdoldie** [comment]
Ich habe dir die Zugangsdaten geschickt 👍

**Comment by ortwin20000** [comment]
Ich komme dem Ganzen schön langsam auf die Spur.
Ich könnte jetzt alle Tabellen die ich mir angeschaut habe auflisten aber ich werde es auf das wesentliche reduzieren:

Tabelle season 
ID: 18 2022/2023 
**ID: 22 gibt es nicht** 

Tabelle season_team_id
ID: 1424 team_id: 13 season_id: 18
ID: 1425 team_id: 21 season_id: 18
**ID: 1521 team_id: 21 season_id: 22**

Tabelle project
Kreispokal ID: 104 mit Saison ID 18
Kreisklasse A ID: 108 mit Saison ID 18

Tabelle project_team
ID: 1365 project_id: 104 team_id: 1424
**Eintrag fehlt ID: 0 project_id: 108 team_id: 1425**
ID: 1545 project_id: 108 team_id: 1521

Tabelle season_team_person_id
id: 1197 person_id: 893 team_id: 13 season_id: 18 project_position_id: 1287 persontype: 1 position_id: 0
id: 1206 person_id: 396 team_id: 21 season_id: 18 project_position_id: 0 persontype: 1 position_id: 39

Also in der Tabelle season_team_id ist für SV Dörpum II ein Eintrag für Saison 2022/2023 mit der ID 1425 enthalten. Es gibt aber auch einen Eintrag mit der ID 1521 für eine Saison mit der ID 22 welches in der Datenbank aber nicht gibt.
In der Tabelle project_team fehlt der Eintrag für die ID 1425 aber es gibt einen Eintrag für die ID 1521 für die Saison mit der ID 22.

Wenn ich nun in der Tabelle season_team_id den Eintrag 1425 ändere indem ich dort die Saison-ID auf einen nicht vorhandene ändere (ich habe sie auf 1800 geändert) und den Eintrag 1521 die Saison auf 18 setze, wird mir der Kader auch angezeigt.

Werden die Daten im System alle über diesen DFB-Import gemacht oder machst du dies manuell?

**Comment by svdoldie** [comment]
Ja, das wird alles über den Import geregelt. Es gibt aber eigentlich immer zwei Wettbewerbe pro Saison an den die Mannschaften teilnehmen (Pokal und Meisterschaft). Das könnte ein Problem sein. Das andere mit den Saison-Id kommt vermutlich daher, das es den Fehler #1466 gibt. Dadurch wird immer eine neue Saison angelegt, da ich keine vorhandene auswählen kann. Nach dem Import ändere ich die dann in den Projekteinstellungen und lösche dann die neu angelegte Saison.
Ich vermute jetzt, dass dwar jetz die Saison richtig zum Projekt passt, aber die gelöschte Saison-ID noch bei den Mannschaften zugeordnet ist.

**Comment by ortwin20000** [comment]
Da ich mit dem DFB Import nichts zu tun habe, bräuchte ich die Importdatei und eine Erklärung dazu. Dann könnte ich versuchen dies nachzustellen.

**Comment by svdoldie** [comment]
Ich habe dir eine Mail mit 4 Ligen geschickt und grob beschrieben, wie der Import abläuft

**Comment by ortwin20000** [comment]
Danke für die Anleitung und Datei.
Ich musste zuerst noch die Sportart Fussball bei mir hinzufügen um die Erweiterung sehen zu können.

Leider erhalte ich aber eine Fehlermeldung beim Versuch des Imports. 
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/15192502/79a75302-74bd-4b9c-a1af-62daf457b80d)

Wie ich mit dem Debugger sehe wird mir die Variable dvbnetspiele nicht richtig befüllt.
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/15192502/d9f5535b-dab7-4fd0-bc58-c49eff795bd7)

obwohl in der Variable $temp Werte enthalten sind
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/15192502/180b8f40-72c0-4f06-ad26-87ebd0ef644f)

Mache ich da noch etwas falsch?

**Comment by svdoldie** [comment]
Ok, dann sind wir mit dem Problem #1466 weiter 👍 
Was die PHP-Warnungen betrifft kann ich dir leider nicht helfen,
davon habe ich keine Ahnung

**Comment by ortwin20000** [comment]
Die Warnungen sind kein Problem. Ich habe bei mir einfach eine Variable `$visible="text";` ganz am Anfang der Datei hinzugefügt. Damit sind die Warnungen dann auch weg gewesen.

Ich habe jetzt auch einen Spieler dem Kader zugewiesen und dieser wird mir auch angezeigt.

Da die Auswahl der Saison nicht möglich war (Saison mit gleichen Namen nicht vorhanden), wurde immer eine neue Saison erstellt und danach im Projekt die Saison geändert. Das verursachte dann die Unstimmigkeit mit der Tabelle season_team_id.
Ich denke, die Ligen- bzw. Saisonauswahl beim Import sollte jederzeit möglich sein und nicht nur wenn ein Eintrag mit gleichen Namen gefunden wurde.
