### ISSUE TITLE
PHP8: JSM Kalendermodul

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1473]
Wenn man unter PHP8 bei dem JSM Kalendermodul mit den Pfeiltasten einen Monat zurück oder vor gehen will, verschwindet der gesamte Kalender.

**Comment by svdoldie** [comment]
Kann ich bestätigen

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Bei mir ist es jetzt so, dass man einmal weiter blättern kann.
Danach verschwindet der Inhalt wieder

**Comment by diddipoeler** [comment]
Ist die Selektion der Mannschaften eingeschaltet?

**Comment by svdoldie** [comment]
Nein, meine Einstellungen sehen so aus
![Screenshot 2022-12-17 085907](https://user-images.githubusercontent.com/2417767/208232075-c6f196d7-5a0d-4596-a079-9f62ec493f56.png)
bei mir ist es übrigens so,
dass man ohne Probleme zurück blättern kann,
vorwärts nur einmal

**Comment by StefanKemner** [comment]
Monatsweise vorwärts/rückwärtsblättern funktioniert bei mir jetzt.

Wenn ich die Doppel Pfeile für Jahreweise blättern benutze, komm ich ein Jahr weiter oder zurück.
Bei nochmaligem Klick verschwindet der Kalender.

**Comment by ortwin20000** [comment]
Wenn ich unter PHP8 das Monat ändere kommt als Fehlermeldung:
Fehler: 0 mktime(): Argument #4 ($month) must be of type ?int, string given

Unter PHP7 funktioniert es bei mir noch.

**Comment by ortwin20000** [comment]
Ich bin jetzt weiter und bei mir liegt es an JEvents.
Wenn ich dies nicht verwende funktioniert es aber wenn ich von JEvents auch die Termine anzeigen lassen möchte, tritt der bekannte Fehler auf, dass der Kalender verschwindet sobald man den vorigen oder nächsten Monat oder Jahr auswählt.

Ursache dürfte folgende Codestelle sein:
`
	static function getEntries($caldates, $params, &$matches)
	{

		if (!self::_checkJEvents())
		{
			return;
		}

		$year  = substr($caldates['start'], 0, 4);
		$month = (substr($caldates['start'], 5, 1) == '0') ? substr($caldates['start'], 6, 1) : substr($caldates['start'], 5, 2);

		self::$xparams = $params;
		/**
		 * Gets calendar data for use in main calendar and module
		 *
		 * @param   int      $year
		 * @param   int      $month
		 * @param   int      $day
		 * @param   boolean  $short      - use true for module which only requires knowledge of if dat has an event
		 * @param   boolean  $veryshort  - use true for module which only requires dates and nothing about events
		 *
		 * @return array - calendar data array
		 */
		$data = self::$jevent->getCalendarData($year, $month, 1);

		$formatted = self::formatEntries($data['dates'], $matches);

		return $formatted;
	}
`
Dort wo der Monat aus caldates extrahiert wird passiert es.
Beim ersten Mal laden wird dort als Datum übergeben:
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/15192502/c89f914b-501e-4b52-a37b-76d6602632a9)

Wenn ich nun im Kalender den nächsten Monat auswähle:
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/15192502/2374a727-e5a2-4425-ba5d-bdd2cc10e6f7)

Somit wird die Variable $month nun mit "6-" befüllt und das wirft später einen Fehler.

Ich hab mir jetzt mal auf die Schnelle so beholfen:
`
		$month = (substr($caldates['start'], 5, 1) == '0') ? substr($caldates['start'], 6, 1) : substr($caldates['start'], 5, 2);
		$month = str_replace('-', '', $month);
`

Oder die JEvents-Einbindung wird im Modul deaktiviert.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Bei mir funktioniert der Close-Button nicht mehr. Das klicken ausserhalb des Modalfenster schließt dieses aber

**Comment by ortwin20000** [comment]
Das ist interessant.
Bei mir funktioniert es aber bei dir nicht.
Grund ist der Code des Modal:
`<button type="button" class="btn btn-default" data-bs-dismiss="modal">Close</button>` funktioniert bei mir aber nicht bei dir.
Wenn ich deinen Code über die Entwicklungswerkzeuge meines Browser auf
`<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>` ändere funktioniert es auch bei dir.

Laut meiner Info muss bei Bootstrap v5 `data-bs-*` verwendet werden. Kann das mit deinem verwendeten Template zusammenhängen?

**Comment by ortwin20000** [comment]
Ich habe jetzt einfach das data-bs-dismiss bzw. data-dismiss mit einem onclick-Event ersetzt. 
Damit funktioniert es bei mir ebenfalls.

**Comment by diddipoeler** [comment]
Bei mir funktioniert der Monat Juli nicht, da der Kalender ausgeblendet ist.

**Comment by svdoldie** [comment]
Bei funktioniert der Close-Button mit meinem Template weiterhin nicht.
Mit einigen anderen Templates geht es einwandfrei, bei anderen kein Modalfenster angezeigt

**Comment by ortwin20000** [comment]
> Bei mir funktioniert der Monat Juli nicht, da der Kalender ausgeblendet ist.
Ich habe den Workaround aus meinem [Kommentar](https://github.com/diddipoeler/sportsmanagement/issues/1473#issuecomment-1539948409) in meinem Pull-Request eingebaut.

@svdoldie 
Wegen dem Close-Button:
Bei mir wird vom Template aus in Joomla 4 bereits bootstrap.modal mitgeladen. In deinem Template konnte ich das nicht sehen. Ich lade daher mit dem WebAssetManager für Joomla 4 die bootstrap.modal nach.

Bitte nach dem Pull-Request noch einmal testen.

**Comment by svdoldie** [comment]
Funktioniert jetzt alles bei mir 👍

**Comment by diddipoeler** [comment]
Wenn ich auf den Juli klicke verschwindet bei immer noch der Kalender.

**Comment by ortwin20000** [comment]
Wie sind deine Moduleinstellungen für den Kalender?

**Comment by diddipoeler** [comment]
Funktioniert.
