### ISSUE TITLE
J4: Anzeige der Sportstätten

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1475]
Bei dem Menüpunkt "Alle Sportstätten in JSM" bleibt die Auswahl "Aktuelle Saison" ohne Wirkung:
![grafik](https://user-images.githubusercontent.com/101453485/178012181-2472ca6d-771e-46aa-bf2c-4cdf70c26134.png)
Es werden alle Sportstätten angezeigt, auch solche, die in der aktuellen Saison nicht mehr vorhanden oder genutzt werden.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Top. funktioniert 👍

**Comment by StefanKemner** [comment]
Jetzt ist es genau andersrum: bei Aktueller Saison "Nein" zeigt er es richtig an.
Kann man aber mit leben:
![grafik](https://user-images.githubusercontent.com/101453485/188401314-4b2aa2db-8c84-4caf-b2db-157fff489eb9.png)
