### ISSUE TITLE
Medien: Bildordner Persons erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1476]
Will man mit J4 über die Medien den Bildordner Persons öffnen, wird er Ordner nicht geöffnet.
Es erscheint nur folgende Fehlermeldung:
Method Joomla\CMS\Response\JsonResponse::__toString() must return a string value

**Comment by ortwin20000** [comment]
Ist das noch aktuell?

**Comment by svdoldie** [comment]
ja, allerdings wird kein Fehlermeldung mehr angezeigt

**Comment by ortwin20000** [comment]
Bei mir werden alle aufgelistet. 
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/15192502/86f7a972-a2c3-43f9-9482-05c148f91724)

In der Webbrowser-Konsole wird auch nichts ausgegeben?

**Comment by svdoldie** [comment]
Kann ich erst später sagen. Hier kann ich die Konsole nicht öffnen

**Comment by svdoldie** [comment]
![image](https://github.com/diddipoeler/sportsmanagement/assets/2417767/c6e36446-ff62-498b-ae46-6a111c7a6e29)
Hilft das?

**Comment by ortwin20000** [comment]
Sieht nach Joomla-Core Geschichte aus. Liegen die Bilder lokal am Server?

**Comment by ortwin20000** [comment]
Ich hab das Problem per Google gesucht und woanders auch so einen ähnlichen Fall gelesen:
https://www.joomshaper.com/forum/question/9423

Kann es sein, dass in dem Ordner eine Datei enthalten ist, die Sonderzeichen, Leerzeichen oder dergleichen beinhaltet und Joomla deswegen den Ordner nicht einlesen kann?

**Comment by svdoldie** [comment]
Ich fasse es nicht. Ich hatte tatsächlich Dateien mit Sonderzeichen drin. Nach umbenennen lässt sich der Ordner einwandfrei laden 👍 
Vielen Dank :-)
Ich mach hier zu
