### ISSUE TITLE
Pressebericht hochladen erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1477]
Beim Hochladen eines Presseberichts erhalte ich die im Bild gezeigte Fehlermeldung.
Laut Backend ist die DB in Ordnung.
![Anmerkung 2022-07-11 072920](https://user-images.githubusercontent.com/2417767/178195249-ffd1c1aa-7559-4d01-a09d-287a27aefb31.png)

**Comment by diddipoeler** [comment]
Schalte mal bitte den Debug Modus ein. Dann sehe ich auch die Programmzeile.

**Comment by svdoldie** [comment]
erledigt 👍

**Comment by svdoldie** [comment]
Ich tippe darauf, das es mit diesem Fehler zu tun hat #1472

**Comment by svdoldie** [comment]
@diddipoeler : Ich habe den Debugmodus erstmal wieder ausgeschaltet. Falls du den zur Fehlerbehebung brauchst, sag einfach kurz bescheid. Dann schalte ich ihn wieder an.

**Comment by tdittmann** [comment]
Schau mal bei deiner Mannschaft alle Spieler an, ob bei denen eine Position gepflegt ist bzw. wähle alle Spieler aus und speichere einfach nochmal. Bei mir lag es daran, dass in der Datenbank es Spieler gab, denen keine Position zugewiesen wurden
