### ISSUE TITLE
J4: Bilder zum Spiel

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1479]
Spieltage -> Spiele bearbeiten -> Bilder zum Spiel hinterlegen
Man kann ein Bild für ein Spiel zwar hochladen und dadurch mit dem Spiel verbinden, dann aber nicht mehr ändern, da ein Speichern Button fehlt.
![grafik](https://user-images.githubusercontent.com/101453485/179344263-dceb5ba2-0bb9-4b37-a7ea-0a3958375948.png)

**Comment by svdoldie** [comment]
Man kann mehrere Bilder hochladen, auch auf einmal. Und man kann sie auch wieder löschen,
das geht allerdings nur einzeln.
