### ISSUE TITLE
Error on edit prediction game profile

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#1480]
User prediction game profile cannot be edited.
If you tried to edit this error appear

500
behavior::tooltip not found.

I've edited edit.php file into predictionuser/tmpl/ directory and remove

HTMLHelper::_('behavior.tooltip');

Searching on internet i found that this call is old fashioned and it must be removed of jsm code. 

but 

appear other error,

0
Call to a member function getXml() on null

I tried to investigate and i found that the call to this function could be the problem

echo $field->renderField(array('hiddenLabel' => true));

All those errors appear when i've migrated to joomla 4

**Comment by llambion72** [comment]
I'm trying to repair this bug. I need to fix several files to repair it.

**Comment by llambion72** [comment]
Fixed on last pull

**Comment by diddipoeler** [comment]
Vielen Dank.
