### ISSUE TITLE
Mod Random Player upgraded

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#1482]
I'm adding new templates to Random player module
![random_player](https://user-images.githubusercontent.com/20923398/181588709-904b73af-34e7-4530-8601-5f5dff41e91a.png)

I've created a sticker template as image below shows.
Border color, sticker color and text color can be modified into configuration 

Now, I'm testing it and soon as possible i will upload it.

**Comment by svdoldie** [comment]
nice :+1:

**Comment by llambion72** [comment]
If you want to see into a funtional web con can enter into www.uvieu.net/prueba
Also, i'm creating new template for playgrounds module and i've fixed a couple of bugs that i've found

**Comment by svdoldie** [comment]
Very good work 👍 Is it possible to implate the template in the birthday modul?

**Comment by llambion72** [comment]
> Very good work 👍 Is it possible to implate the template in the birthday modul?

I'll try to do it.

**Comment by llambion72** [comment]
Birthday modul has 3 templates, list, bootstrap and jsslider.
List is very similar to my template, i can modify this. If you want or i can keep on this template and i can create one new
Bootstrap and jsslider don't work well at least on my websites

**Comment by svdoldie** [comment]
List is ok. :-) 👍

**Comment by llambion72** [comment]
![mod_birthday](https://user-images.githubusercontent.com/20923398/182221214-17a89c80-2f12-44b8-9a9b-6b4b2fb130f1.png)

Something like that? @svdoldie

**Comment by svdoldie** [comment]
Looks very good 👍 👍

**Comment by llambion72** [comment]
I've added following corrections,

Module Birthdays
Add sticker Template

Module Random Player
Fix image properties

Module Team Statistics counter
Add sticker template and fix some bugs

**Comment by svdoldie** [comment]
I have tried the template, but then i get an error :
0
syntax error, unexpected end of file

**Comment by llambion72** [comment]
> I have tried the template, but then i get an error : 0 syntax error, unexpected end of file

Which module?

**Comment by svdoldie** [comment]
I use the birthday-modul with j4, PHP 7.4.. and the new sticker-template

**Comment by llambion72** [comment]
> I use the birthday-modul with j4, PHP 7.4.. and the new sticker-template

I'm using same config. I'll check it again because i can't replicate this bug

**Comment by sigal** [comment]
![module birthday](https://user-images.githubusercontent.com/5115688/183254898-030a52f9-050f-404c-beb8-7e462f9ff647.png)

**Comment by llambion72** [comment]
> ![module birthday](https://user-images.githubusercontent.com/5115688/183254898-030a52f9-050f-404c-beb8-7e462f9ff647.png)

Thank you!! I'll fix it
How can i view this screen?

**Comment by sigal** [comment]
> > ![module birthday](https://user-images.githubusercontent.com/5115688/183254898-030a52f9-050f-404c-beb8-7e462f9ff647.png)
> 
> Thank you!! I'll fix it How can i view this screen?

Please don’t use deprecated PHP short_open_tag in Code!
In the file `default_player_sticker.php` you are using PHP syntax like <?= which requires configuration of php.ini, namely it needs short_open_tag = On, which is On by default on your Server, but in php.ini it states that it is recommended to disable it.

Server PHP.ini Setting:
`short_open_tag = ON` : No error appears
`short_open_tag = OFF` : syntax error unexpected end of file

**Comment by llambion72** [comment]
Ok, i usually use <? open tag, i'm changing all open short tags.

**Comment by sigal** [comment]
Reference
[PHP RFC: Deprecate PHP Short open tags](https://wiki.php.net/rfc/deprecate_php_short_tagsl)

**Comment by llambion72** [comment]
I've uploaded last corrections.

**Comment by svdoldie** [comment]
Thx, looks very good 👍 Could you add an option to switch off the team?

**Comment by llambion72** [comment]
> Thx, looks very good 👍 Could you add an option to switch off the team?

Yes, i'll get on it

**Comment by llambion72** [comment]
> Thx, looks very good 👍 Could you add an option to switch off the team?

I've uploaded today this module with your desired options.

**Comment by svdoldie** [comment]
Works very well 👍 thx!

**Comment by diddipoeler** [comment]
Können wir das schließen?

**Comment by svdoldie** [comment]
Von mir aus schon 👍
