### ISSUE TITLE
J4: Liga im Tippspiel kann nicht veröffentlich werden

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1485]
Unter J4 kann man die liga die getippt werden soll nicht veröffentlich werden, da die Buttons nicht vorhanden sind.
Die Buttons für Modus und Übersicht fehlen auch.
Siehe Bild 
![Tippspiel](https://user-images.githubusercontent.com/2417767/182432707-afc33ce3-8877-4509-9ea1-cbc181a1e876.png)

**Comment by StefanKemner** [comment]
Das hatte ich beim testen auch mal: Klickt mal z.B. bei Status rechts (wo "Status der.. " steht) über "Versteckt" ins weiße. Dann ändert sich der Status. Müßte wohl mal überarbeitet werden.

**Comment by svdoldie** [comment]
So sieht's aus ;-)

**Comment by sigal** [comment]
Bitte einmal testen

**Comment by svdoldie** [comment]
Bei mir ist der Fehler noch vorhanden.

**Comment by sigal** [comment]
versteh ich nicht. stelle nur code online, den ich vorher online getestet habe.

![predictiongame_xml](https://user-images.githubusercontent.com/5115688/183472588-e16c77e6-80a6-4a8a-a5bd-d43bf27a7932.png)

**Comment by svdoldie** [comment]
Hi, das bezweifle ich nicht. Ich überprüfe das nochmal bei mir

**Comment by diddipoeler** [comment]
Können wir das jetzt schließen?

**Comment by svdoldie** [comment]
Bei mir ist der Fehler noch vorhanden. Ich habe extra nochmal die Komponente deinstalliert und anschließend neu installiert

**Comment by boxr** [comment]
Kann unter Sportsmanagement 4 kein neues Tippspiel anlegen, hab dann 3.16 darüber installiert, damit funktioniert es wieder.

**Comment by diddipoeler** [comment]
Könntet ihr das bitte noch einmal testen?

**Comment by boxr** [comment]
Funktioniert jetzt, Super danke :-)

**Comment by svdoldie** [comment]
Bei mir auch 👍 
Nur noch ein kleiner Hinweis. Vielleicht sollte der Schalter beim Zustand veröffentlicht grün sein?

**Comment by diddipoeler** [comment]
Könntet ihr das bitte noch einmal testen?

**Comment by svdoldie** [comment]
Perfekt 👍
