### ISSUE TITLE
J4: Bilder zuordnen erzeugt Fehlermeldungen

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1486]
Beim zuordnen eines Bildes zu Teamperson erscheint folgende Fehlermeldung: 
Method Joomla\CMS\Response\JsonResponse::__toString() must return a string value

Beim zuordnen eines Bildes zu Team erscheint folgende Fehlermeldung: 
Data too long for column 'picture' at row 1

Dieselbe Fehlermeldung kommt beim zuordnen eines Projektbildes

PS:  Falls jemand eine Idee hat, wie man Joomlacontent von J4 zuJ3 konvertieren kann, darf sich gerne bei mir melden ...

**Comment by StefanKemner** [comment]
PHP 8 Problem vielleicht ?

**Comment by svdoldie** [comment]
Nein, ich habe Version 7.4

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Die Fehlermeldung erscheint immer noch. Den Ordner Persons kann ich nicht öffnen, bzw. er wird nicht geladen.
Somit ist auch keine Zuordnung möglich.
Bei den Teams ist eine Bildzuordnung möglich, allerdings erscheint dann z.B. folgender Link:
images/com_sportsmanagement/database/teams/2021-22/erste.jpg#joomlaImage://local-images/com_sportsmanagement/database/teams/2021-22/erste.jpg?width=1377&height=918
kürzt man ihn manuell auf  images/com_sportsmanagement/database/teams/2021-22/erste.jpg 
kann man das auch speichern

**Comment by diddipoeler** [comment]
Der Fehler mit den merkwürdigen Pfad Namen hat sich jetzt durch das Joomla Update auf 4.2.5 selber behoben.

Für Entwickler habe ich noch folgenden Beitrag dazu gefunden:
https://ghsvs.de/programmierer-schnipsel/joomla/319-joomla-4-einleitungs-beitragsbild-komische-pfade

**Comment by svdoldie** [comment]
Ich habe das gerade mal beim aktuellen Github-Stand mit einem Teambild gestestet. Nach dem auswählen wird folgender Link erzeugt: images/com_sportsmanagement/database/teams/2022-23/dritte.jpg#joomlaImage://local-images/com_sportsmanagement/database/teams/2022-23/dritte.jpg?width=890&height=500
Und es kommt folgende Fehlermeldung: Data too long for column 'picture' at row 1
Ein Bearbeiten des erzeugten Links funktioniert  nicht

**Comment by ortwin20000** [comment]
Ich vermute hier das gleiche Problem wie bei #1539.
@diddipoeler Soll ich hier auch die gleiche Bereinigung beim Speichern durchführen?

**Comment by diddipoeler** [comment]
Ja, ist OK.

**Comment by ortwin20000** [comment]
@svdoldie Ist der Punkt erledigt oder gibt es noch Probleme?
