### ISSUE TITLE
J4: Rankingmodul zeigt falsche Reihenfolge

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1489]
Nach Eingabe der ersten Ergebnisse zeigt das Modul leider nicht die richtige Reihenfolge, In der normalen Tabellenansicht ist alles soweit in Ordnung. Zudem werden nicht alle Vereinslogos auf die richtige Größe skaliert. Zusehen ist das Ganze auf meiner Seite https://www.svdoerpum.de im Modul Überblick und dort die 3. Herren
Die normale Tabellenansicht ist hier zu sehen https://www.svdoerpum.de/senioren/3-herren/tabelle/ranking/0/18:2022-2023/109:kreisklasse-c-nord-west-2022-2023/0/0/0/0/0

**Comment by svdoldie** [comment]
Da sich die die Tabelle nach Eingabe von neuen Ergebnissen ändert, hänge ich hier mal ein Bild an
![Screenshot 2022-08-08 105205](https://user-images.githubusercontent.com/2417767/183382194-511c4959-759b-46b1-91ec-55cbaf085f32.png)

**Comment by svdoldie** [comment]
Das Problem mit den Logos betrifft nur Vereine, die neu in meinem Bestand sind und entsprechend die Logos erst nach Umstellung auf J4 gespeichert wurden.

**Comment by svdoldie** [comment]
Ich weiß nicht warum, aber die Reihenfolge wird jetzt richtig angezeigt. Das Problem mit den großen Logos besteht aber weiterhin

**Comment by svdoldie** [comment]
Hat das Problem mit den Logos sonst niemand?

**Comment by ortwin20000** [comment]
Hab mir das auf deiner Seite angeschaut.
Hast du irgendein Plugin im Einsatz das die Bilder nachträglich lädt?
Bei den richtig dargestellten Vereinslogos schaut der HTML-Code so aus:
`<img class="teamlogo" =""="" src="/images/com_sportsmanagement/database/clubs/large/tellingstedt_mtv.png" alt="MTV Tellingsted" width="20">`

Bei den falsch dargestellten schaut es so aus:
`<img class="teamlogo" =""="" src="/images/com_sportsmanagement/database/clubs/large/brunsbuettel_bsc.png" alt="BSC Brunsbütt" loading="lazy" width="150" height="150">`

Ich vermute, du hast ein Plugin aktiv was da dazwischenfunkt und die Bilder umschreibt. Warum das aber nur bei manchen passiert kann ich so nicht sagen.

**Comment by svdoldie** [comment]
Nicht das ich wüsste. Wie oben schon beschrieben, es betrifft ausschließlich Logos, die nach der Umstellung auf J4 hochgeladen und gespeichert wurden

**Comment by ortwin20000** [comment]
Ich habe es nachstellen können. Du verwendest als Media-Tool ja Joomla und beim Hochladen der Bilder wird ja der schon bekannte Text bei Bildern angehängt. Genau das verursacht dann dieses Problem.

Ich schaue mal ob ich den Eintrag nach dem Einfügen bereinigen kann. Ich glaub ich hab das schon mal versucht und bin damals nicht weiter gekommen. Deswegen verwende ich bisher noch immer als Media-Tool "Sports Management".

**Comment by svdoldie** [comment]
Ok, dann hoffe ich mal

**Comment by ortwin20000** [comment]
Ich habe das Modul Ranking angepasst, damit die Vereinswappen bereinigt werden, falls das Joomla eigene MediaTool verwendet wurde und somit die Pfade zu den Vereinswappen mit den zusätzlichen Attributen gespeichert wurden.

Im Backend kann ich das wohl nicht anpassen, da hier von Joomla-Standard das Media-Feld verwendet wird und da läuft nach Eintragung des Pfades zum Vereinswappen noch Javascript-Code der eben die besagten Attribute hinzufügt.

**Comment by svdoldie** [comment]
Sieht gut aus :-) 👍 
Von mir aus kann ich hier zumachen
