### ISSUE TITLE
J4: Mannschaftsspielplan PDF/Druck

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1491]
Wenn man in dem Frontend Template "teamplan" unter Seitenelemente -> "Welches Layout" auf "sortiert nach Datum" stellt, wird im Frontend bei "Export to PDF" und "Print Preview" nur der 1. Spieltag angezeigt:

![grafik](https://user-images.githubusercontent.com/101453485/183871357-eb562531-4905-4825-a360-6b32ae7029d1.png)
![grafik](https://user-images.githubusercontent.com/101453485/183871386-cf0bb6bf-5416-4606-8b57-13bb6f32013f.png)

**Comment by ortwin20000** [comment]
Ich habe Anpassungen im Template components\com_sportsmanagement\views\teamplan\tmpl\default_plan_sorted_by_date.php gemacht. Damit wird bei mir der Export über alle Tage erzeugt.

Ich habe dazu einen Pull-Request erstellt.
Bitte testen.

**Comment by StefanKemner** [comment]
Top, funktioniert 👍 
Wenn ich da noch eine Bitte äußern dürfte:
Könnte man bei der Sortierung nach Datum noch die Spielnummer mit anzeigen lassen ?

Und der bisher fehlende Ereignisbutton ist jetzt auch da:
https://github.com/diddipoeler/sportsmanagement/issues/1544

**Comment by ortwin20000** [comment]
So viele Daten hab ich bei mir nicht zum Testen. Faustball gibt es nicht so viele Spieltage ;-)

![grafik](https://github.com/diddipoeler/sportsmanagement/assets/15192502/67bd2f47-3e9b-4c47-a246-c3b3c4a99946)
Im Code hab ich gesehen, dass html2pdf die Seitegröße als A3 übergeben wird. Vielleicht muss dies auf z.B. A2 geändert werden?
Die Datei findest du dort:
components\com_sportsmanagement\views\teamplan\tmpl\default.php

Kannst du das bei dir mal testen?

**Comment by ortwin20000** [comment]
Wie ich auf der Github-Seite von html2pdf gelesen habe gibt es mit der Version >= 0.10.0 mehrere Probleme und man soll derzeit noch die 0.9.3 verwenden.
Kannst du bitte mal in der Datei components\com_sportsmanagement\views\teamplan\tmpl\default.php folgenden Teil in Zeile 23 austauschen und testen:
`<script src="https://raw.githack.com/eKoopmans/html2pdf/master/dist/html2pdf.bundle.js"></script>`
mit
`<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.3/html2pdf.bundle.min.js" integrity="sha512-YcsIPGdhPK4P/uRW6/sruonlYj+Q7UHWeKfTAkBW+g83NKM+jMJFJ4iAPfSnVp7BKD4dKMHmVSvICUbE/V1sSw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>`

**Comment by diddipoeler** [comment]
Eingebaut.
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Mist, ich glaube, Denkfehler von meiner Seite:

Bei dem Menüpunkt "Mannschafts-Spielplan Anzeige" lasse ich mir alle Mannschaften anzeigen:
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/101453485/03646923-0b99-4935-82cb-11d005c6fce0)
https://owlstl.de/liga/liga-1/spielplan/teamplan/0/2:2022-2023/10:1-liga/0/0

Bei der PDF-Ausgabe scheint das dann zuviel an Daten zu sein.
Die PDF Ausgabe für nur eine Mannschaft (Icon unter dem Mannschaftsnamen->Mannschaftspielplan) funktioniert nämlich.

Ich würde dann hier jetzt zumachen wollen ...
