### ISSUE TITLE
Nextmatch template

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#1492]
I've found some errors on nextmatch template.
Stats not be counted correctly
Total matches not expand when click over any of them
Events not expand when click over any of them

I'm repairing this template and add new stats to improve this template.
![NextMatch](https://user-images.githubusercontent.com/20923398/184936127-9c8ac933-113c-4aef-908c-dd5bc9ccf0c2.png)

1 Add new stats
2 Add vertical tabs instead collapse on matches and events

**Comment by diddipoeler** [comment]
Können wir das jetzt schließen ?
