### ISSUE TITLE
JSM-Modul Spielstätten Terminansicht 

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1495]
Spiele, die z.B. als verlegt in den Spieldetails gekennzeichnet worden sind und noch kein neuer Termin feststeht, werden in der Ansicht trotzdem angezeigt:
![grafik](https://user-images.githubusercontent.com/101453485/186125707-0e1b2d33-387f-40f6-9285-016e42c5fb01.png)

**Comment by sigal** [comment]
https://globalsportsarchive.com/competition/soccer/sky-bet-championship-2022-2023/regular-season/67709/

https://www.weltfussball.at/wettbewerb/aut-bundesliga/

https://www.kicker.de/championship/spieltag/2022-23/4
