### ISSUE TITLE
PHP8: Spiel Historie

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1497]
Klicke ich bei einem beendeten Spiel auf die Spielhistorie, kommt folgender Fehler:
![grafik](https://user-images.githubusercontent.com/101453485/188110076-0310a4de-b77f-40cb-a311-d567877b6d8f.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Anderer Fehler:
![grafik](https://user-images.githubusercontent.com/101453485/188257460-b28408a8-b831-4bfa-a7ee-6b2b3485f72b.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
![grafik](https://user-images.githubusercontent.com/101453485/188267603-a80ed567-a17a-4606-9d94-db545dcfc85b.png)

**Comment by StefanKemner** [comment]
Funktioniert jetzt 👍
