### ISSUE TITLE
PHP 8: Spielberichtsanzeige (matchreport)

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1498]
Wenn man unter PHP 8 den Parameter "Registerkarten für die Anzeige der Ereignisse verwenden" auf "Stattdessen im Ticker anzeigen" stellt ..
![grafik](https://user-images.githubusercontent.com/101453485/188124082-bf681c41-f7ae-4344-835e-bc2a8a0d25ae.png)

.. kommt folgende Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/101453485/188111109-354a2246-fb29-41c9-a0b3-5004c5e2af1f.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Klappt 👍
