### ISSUE TITLE
PHP 8: Ergebniseingabe Frontend, Fehler bei Spielfrei

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1499]
Bei der Ergebniseingabe im Frontend ..
![grafik](https://user-images.githubusercontent.com/101453485/188122987-212c06a4-58ee-4075-b9ac-a67f37ee15c1.png)

.. kommt beim ersten Team was keinen Gegner hat (also spielfrei) folgende Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/101453485/188123166-a65eb687-71fa-4547-be23-6ffeda495a81.png)

![grafik](https://user-images.githubusercontent.com/101453485/188123287-5f3e2317-7d16-4cb4-a575-376d6b885889.png)

**Comment by StefanKemner** [comment]
![grafik](https://user-images.githubusercontent.com/101453485/188257522-9af9e61e-cc31-460d-8d7e-2b9d5b82fe80.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Aufruf funktioniert jetzt.

Jetzt sind leider noch 2 neue Probleme dazu gekommen:
1. bei der Startaufstellung zeigt er mir keine Spieler zum auswählen an:
![grafik](https://user-images.githubusercontent.com/101453485/188268084-7bcccfa6-6930-4bf6-8e50-5b605a700572.png)

2. Wenn ich oben auf "Abbrechen" klicke, kommt folgende Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/101453485/188268181-7ff370ed-43aa-4f3e-a484-c3ceb7073564.png)
![grafik](https://user-images.githubusercontent.com/101453485/188268212-ae0639fc-211e-497f-a81e-cfccf42c6213.png)

**Comment by diddipoeler** [comment]
Problem 2 erledigt.

**Comment by StefanKemner** [comment]
Zusatz: da wohl dasselbe Programm verwendet wird: im Backend sind bei den Startaufstellungen auch keine Spielernamen zu sehen.

**Comment by diddipoeler** [comment]
Verstehe ich jetzt nicht mehr. 
Beim wem werden die Spieler nicht angezeigt? 
Bei der spielfreien Mannschaft?
Bei der nicht spielfreien Mannschaft?
Oder bei beiden?

**Comment by StefanKemner** [comment]
Sorry, generell zeigt er keine Spielernamen mehr an. Heim + Gast.
Konnte ich erst nur nicht sehen.

**Comment by diddipoeler** [comment]
Jetzt sind die Spieler wieder da.

**Comment by StefanKemner** [comment]
Im Frontend leider noch nicht, Github Update hatte ich gemacht, angemeldet als Super User
![grafik](https://user-images.githubusercontent.com/101453485/189887646-4965ad98-aca0-4d35-a695-06cbad20526e.png)

Im Backend sind die Spielernamen bei der Startaufstellung zu sehen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Spielernamen werden jetzt angezeigt 👍 

Allerdings kommt beim Speichern im Frontend jetzt folgender Fehler:
![grafik](https://user-images.githubusercontent.com/101453485/189915198-de310cae-6599-4315-9777-07e3bfcd1fab.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Jetzt kommt beim speichern folgende Meldung:
![grafik](https://user-images.githubusercontent.com/101453485/190099448-88782642-6b0f-499d-86c0-5cbc77c00c7b.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Top 👍 Klappt jetzt
