### ISSUE TITLE
PHP 8: Frontend: Ereignisse bearbeiten, Fehler beim speichern

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1501]
Beim Eingeben von Ereignissen im Frontend ..
![grafik](https://user-images.githubusercontent.com/101453485/190166613-82445e8f-864f-4270-8fb2-cbf1bdf82be4.png)

.. kommt beim Speichern Fehler 500, Internal Server Error
![grafik](https://user-images.githubusercontent.com/101453485/190166769-27602f95-f0c6-4199-bea8-0b3eea804fdb.png)
![grafik](https://user-images.githubusercontent.com/101453485/190166793-365bfa33-506f-4b6f-bb57-07e081671646.png)
Unter PHP 7.4 funktioniert das.

Vielleicht könnte man in dem Zuge auch schauen, warum die Ereignisse noch doppelt angelegt werden:
https://github.com/diddipoeler/sportsmanagement/issues/1462

**Comment by StefanKemner** [comment]
Problem scheint sich nach Update auf Joomla 4.2.5 erledigt zu haben

**Comment by diddipoeler** [comment]
Bitte einmal mit Vorsicht testen.

**Comment by StefanKemner** [comment]
sieht sehr gut aus 👍 Vielen Dank 🥇
