### ISSUE TITLE
J4: Frontend: Spieldetails bearbeiten

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1502]
Wenn man über das Frontend die Spieldetails bearbeitet, z.B. den Spielbericht ..
![grafik](https://user-images.githubusercontent.com/101453485/190331518-267bd9e7-cc67-4a59-b03b-56c4a3bf3fc2.png)
.. und dann speichern will, kommt folgende Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/101453485/190331643-5bffbb41-90f9-4891-b59d-93182342cda3.png)
![grafik](https://user-images.githubusercontent.com/101453485/190346450-e0b399cc-ef39-4a82-975b-8528b20a7225.png)

Gibt man bei Nachspielzeit z.B. eine "0" ein, funktioniert das Speichern auch:
![grafik](https://user-images.githubusercontent.com/101453485/190331806-6f6923bc-c20f-497f-ab28-c2a3ddb979a1.png)

**Comment by StefanKemner** [comment]
Nachtrag: mit PHP 8 dasselbe, aber anderer Fehler:

![grafik](https://user-images.githubusercontent.com/101453485/190340078-7e1f7be1-f6cb-4fe3-8c9c-d27defd4fbf4.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Fehlermeldung ist jetzt weg 👍 

Folgeproblem:
Änderungen in den Spieldetails werden nur gespeichert, wenn im Feld "Nachspielzeit" ein Wert (kann auch "0") steht, sonst leider nicht.
Im Backend funktioniert das speichern allerdings.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Leider keine Änderung bisher:
Gibt man im Feld "Nachspielzeit" eine "0" ein, werden Änderungen gespeichert, sonst leider nicht.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Funktioniert jetzt 👍
