### ISSUE TITLE
J4: Spieldetails bearbeiten, Formatierung + Bilder werden nicht gespeichert

### ISSUE THREAD

**Issue by Stefan6519** [diddipoeler/sportsmanagement#1503]
Bei der Bearbeitung der Spielvorschau und des Spielberichtes ..
![grafik](https://user-images.githubusercontent.com/101453485/190362627-3bda9b2d-10b1-425f-ba93-099fc0ba0dd1.png)

.. wird Text zwar gespeichert, aber keine Formatierungen (z.B. fett) und auch keine Bilder, die man mit Hochladen dort eingefügt hat.
Ich benutze den JCE Editor in Joomla, der sonst überall funktioniert.
Ist im Frontend + im Backend

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Leider noch keine Veränderung, Änderungen werden nicht gespeichert, Frontend + Backend nicht

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Im Backend funktioniert die Speicherung von Formatierungen jetzt 👍

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Im Frontend funktioniert die Speicherung von Formatierungen leider noch nicht.
Aber im Backend soll mir reichen.
Ich schliese das dann mal hier. 
Vielen Dank 👍
