### ISSUE TITLE
PHP 8: Spielvorschau

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1507]
Beim Aufruf der Spielvorschau für ein zukünftiges Spiel kommt folgende Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/101453485/201509046-060a6a6d-f5b4-4296-8024-14b2ff4b21f8.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Top 👍  Funktioniert
