### ISSUE TITLE
J4: Spielplan Kommentarspalte

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1511]
In den Frontend Einstellungen, Template "teamplan"(Mannschaftsspielplan Anzeige) -> Optionen habe ich ein schwerwiegendes Problem bei dem Punkt "Kommentarspalte anzeigen ?":  
![grafik](https://user-images.githubusercontent.com/101453485/202846386-cfc94ed6-5f65-48f6-8c78-b5d452e9689c.png)

Die Zurückstellung auf "Nein" funktioniert nicht, bleibt immer auf "Ja" stehen.
Folgeproblem: im Frontend kommt jetzt eine Fehlermeldung beim Aufruf des Spielplanes:
![grafik](https://user-images.githubusercontent.com/101453485/202846466-7e40f87f-2a04-4ce7-9e92-68d823cccf26.png)

**Comment by diddipoeler** [comment]
Bitte einmal testen.

**Comment by StefanKemner** [comment]
Top 👍 Funktioniert :-))
