### ISSUE TITLE
J4: Modul Matches

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1512]
Bei Aktivierung der Verlinkung von z.B. Spieltagsname:

![grafik](https://user-images.githubusercontent.com/101453485/203827177-9d4987b5-5633-43db-b609-0c80bd6c74e2.png)
.. oder Spielort:
![grafik](https://user-images.githubusercontent.com/101453485/203827240-d68dec6d-9cad-48d9-94dc-de11168b8b22.png)

.. kommt folgende Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/101453485/203827352-edddc193-00a9-4ee3-8fe6-68e3d732b183.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Fehlermeldung kommt jetzt leider auch, wenn ich alle Link Parameter in dem Modul ausschalte:
![grafik](https://user-images.githubusercontent.com/101453485/204145104-dd2a6e08-3272-49f3-956d-8c5dfe8307d7.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
![grafik](https://user-images.githubusercontent.com/101453485/204195386-ac0ca369-9246-4a55-8470-6291cbee8cd3.png)

**Comment by diddipoeler** [comment]
Bitte einmal die Adminzugangsdaten zusenden.
Ich schaue mir das mal genauer an.

**Comment by StefanKemner** [comment]
Müssten angekommen sein

**Comment by ortwin20000** [comment]
Ist das noch offen? Bei mir werden die Spiele angezeigt.
