### ISSUE TITLE
J4: Template results: Spieldatum

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1513]
Wenn man sich bei der Frontend Ergebniseingabe das Spieldatum mit anzeigen lässt ...

![grafik](https://user-images.githubusercontent.com/101453485/204074361-4a267325-3a43-43f7-bb51-8fd90479b1ea.png)
![grafik](https://user-images.githubusercontent.com/101453485/204074368-16824ebb-3929-44a4-9a39-e91e9faaf052.png)

.. funktioniert das Speichern der Ergebnisse leider nicht mehr:
![grafik](https://user-images.githubusercontent.com/101453485/204074497-99995b5e-0623-49e0-bba8-43558e2831e7.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Klappt bestens 👍
