### ISSUE TITLE
J4: Ergebnis Anzeige Kommentarspalte

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1514]
Anscheinend ähnliches Problem, wie hier: https://github.com/diddipoeler/sportsmanagement/issues/1511

Im Template "results" kann man den Paramater nicht mehr auf "nein" stellen ..
![grafik](https://user-images.githubusercontent.com/101453485/204096164-41891af1-9f28-4eac-99b1-027a7462f9b5.png)

.. Fehlermeldung im Frontend:
![grafik](https://user-images.githubusercontent.com/101453485/204096183-6ceecb97-d77d-453d-97c8-509a78b69e3c.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Klappt 👍
