### ISSUE TITLE
J4: Jcomments 4

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1515]
Wenn man in den Templates "results" oder "teamplan" die Kommentarspalte aktiviert ..
![grafik](https://user-images.githubusercontent.com/101453485/204125463-c1a4ffcf-21eb-4963-ae88-83db94065018.png)

,, kommt im Frontend folgendes Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/101453485/204125486-bad30da7-fcb2-4ba7-b807-fa7dcff6e324.png)

Entsprechendes Plugin ist aktiviert und die Jcomments 4 Erweiterung auch installiert

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Top 👍 Fehlermeldung ist weg
