### ISSUE TITLE
J4: Stammdaten Mannschaften: Vereine nicht mehr auswählbar

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1516]
Den Mannschaften sind eigentlich Vereine zugeordnet.
Ich wollte jetzt bei einer Mannschaft in den Stammdaten eine Änderung vornehmen + mußte feststellen, das ich keinen Verein mehr auswählen kann. Sehr unglücklich, da Pflichtfeld:
![grafik](https://user-images.githubusercontent.com/101453485/204147138-f6a911b3-492e-4ea1-abf3-cd2751f1728b.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
geht wieder 👍

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Top 👍 Passt wieder
