### ISSUE TITLE
J4: Trainingszeiten erfassen

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1517]
Das Anlegen einer neuen Zeile funktioniert noch:
![grafik](https://user-images.githubusercontent.com/101453485/204578700-3ca93823-4cec-4c52-bcd1-fb9c3a8a8743.png)

Will man jetzt eine Uhrzeit eintragen und speichern, kommt folgende Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/101453485/204578901-e9bcafed-6fa5-48ef-ab64-d9eb4e5f9cb8.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Klappt 👍
