### ISSUE TITLE
Wish: JSM - Modul Ereignis Rangliste

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1520]
Bei dem entsprechenden Menüpunkt zu dem o.g. Modul.. 
![grafik](https://user-images.githubusercontent.com/101453485/207106884-0fd8d917-5961-4ec8-855a-ab1eddd66558.png)

.. kann man die Sortierung (auf-oder absteigend) in den jeweiligen Ereignisse festlegen:
![grafik](https://user-images.githubusercontent.com/101453485/207107121-00eb43d4-a523-44a9-83cd-cb5bec17bbe1.png)

Bei dem Modul ...
![grafik](https://user-images.githubusercontent.com/101453485/207107245-774edeb4-0bfb-43a2-bc46-d190c3a67629.png)
.. funktioniert das leider nicht.

Der Einstellungspunkt "Rangliste sortieren" zeigt keine Wirkung, es wird immer absteigend sortiert:
![grafik](https://user-images.githubusercontent.com/101453485/207107710-f8d03ca3-814a-4f67-9291-7cd35a5e1053.png)

Wäre prima, wenn man da was machen könnte.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Top, klappt 👍
