### ISSUE TITLE
Modul Vereinsjubiläum zeigt ungewollte Meldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1521]
Beim oben genannten Modul erscheint oberhalb des Vereinsnamens folgende Meldung:
use Joomla\CMS\Log\Log;
Das ist sicher nicht so gewollt ;-)

siehe hier https://www.svdoerpum.de

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Hat sich nicht geändert. Allerdings stimmt auf einmal das Jubiläumsjahr, das war vor Weihnachten noch 2022

**Comment by sigal** [comment]
Bitte noch einmal testen.
