### ISSUE TITLE
Sichtbarkeit im Projekt bei neuen Spielern

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1524]
Ich habe 3 Projekte: Liga 1, Liga 2 + Pokal.
Im Pokal spielen Teams aus der 1. +2. Liga mit.

Wenn ich einem Liga Team in der laufenden Saison einen neuen Spieler zuordne, erscheint dieser auch gleichzeitig im Pokal Projekt bei dem enstsprechenden Team, nur leider als "Nicht sichtbar im Projekt":
![grafik](https://user-images.githubusercontent.com/101453485/213847719-f81532ee-b1ff-472d-8cf2-9bd226ba0367.png)

Das fällt erst auf, wenn man die Startaufstellung machen will + der Spieler nicht da ist.

**Comment by ortwin20000** [comment]
Ich habe wegen #1448 einen Pull-Request gemacht. Kannst du mal testen ob das Problem auch hier noch auftritt?

Falls ja:
Wie kann ich das nachstellen? Was für eine Spielform ist das Pokal-Projekt? "Einfache Liga", "Gruppenliga", "Turniermodus"?

**Comment by StefanKemner** [comment]
Ist jetzt weg, passt 👍
