### ISSUE TITLE
GithubUpdate erzeugt Fehlermeldung nach Joomla-Update auf 4.2.7

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1526]
Nach dem Update auf Joomla 4.2.7 erhalte ich folgende Meldung bei einem JSM-Github-Update
![Screenshot 2023-02-01 194826](https://user-images.githubusercontent.com/2417767/216136054-3e669eed-2240-437f-bce5-b12321d15369.png)

**Comment by sigal** [comment]
Wie hoch ist das PHP memory_limit gesetzt.
Bei mir ging es erst bei 
memory_limit = 256M

**Comment by svdoldie** [comment]
Bei mir vermutlich auch. Das Limit ist vom Provider auf 128M begrenzt

**Comment by svdoldie** [comment]
Ich könnte das Paket bei unserem Provider upgraden lassen. Das nächstgrößere Paket würde memory_limit = 192M beinhalten.
Würde das evtl. auch ausreichen?

**Comment by sigal** [comment]
192M sind ausreichend.
Hab es getestet. 
LG in den Norden.

**Comment by svdoldie** [comment]
Vielen Dank für die Info.  Dann muss ich mal mit meinem Verein sprechen.
LG zurück nach Österreich 😀🍻
