### ISSUE TITLE
PHP 8: Bilder-Import erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1532]
Mit PHP 8 erzeugt der Bilder-Import die Fehlermeldung: Attempt to assign property "id" on null
Es werden keine Bilder importiert. Mit PHP 7 funktioniert der Import einwandfrei

**Comment by diddipoeler** [comment]
Bitte den Debug Modus in Joomla einschalten und dann die Funktion noch einmal ausführen.
Dann wird die fehlerhafte Datei mit Zeilennummer angezeigt.

**Comment by svdoldie** [comment]
![Anmerkung 2023-02-21 105603](https://user-images.githubusercontent.com/2417767/220311576-24b3801a-6172-45b9-967d-a5d40b311a31.png)

**Comment by appukonrad** [comment]
php8 is more strict about using unset variables. There are many unset variables in the code, across modules and components.

**Comment by svdoldie** [comment]
Geht jetzt wieder 👍
