### ISSUE TITLE
J4: Ereignisse in der Mannschafts Spielplan Anzeige

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1544]
Der Ereignis Button wird in der Mannschaftsspielplan Anzeige nicht angezeigt, obwohl aktiviert, Frontend Einstellung "teamplan":
![grafik](https://user-images.githubusercontent.com/101453485/229150269-3b13a882-57ce-4051-a305-b1b3b601f48e.png)

**Comment by ortwin20000** [comment]
Da ich bei mir noch keine Ereignisse verwende musste ich erst mal draufkommen wie Ereignisse überhaupt hinzugefügt werden.

Welches Layout für den Spielplan verwendest du? "Standard" oder "Sortiert nach Datum"?
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/15192502/c54d41d7-4580-40b3-9b69-7a238117b1f9)

Auf jeden Fall werden in beiden Fällen die Ereignisse angezeigt nur wurden bei mir die Icons nicht dargestellt, weil der Platz in der Tabelle zu klein gesetzt war. Kann natürlich auch an dem verwendeten Joomla-Template liegen.

Für beide Layouts hat es bei mir so funktioniert:
<td width='5' class='ko'> ändern auf <td width='3%' class='ko'>

components\com_sportsmanagement\views\teamplan\tmpl\default_plan.php
```
					if ($this->config['show_events'])
					{
						?>
                        <td width='5' class='ko'>
							<?php
							$events = sportsmanagementModelProject::getMatchEvents($match->id, 0, 0, Factory::getApplication()->input->getInt('cfg_which_database', 0));
							$subs   = sportsmanagementModelProject::getMatchSubstitutions($match->id, Factory::getApplication()->input->getInt('cfg_which_database', 0));
```
habe ich abgeändert auf:
```
					if ($this->config['show_events'])
					{
						?>
                        <td width='3%' class='ko'>
							<?php
							$events = sportsmanagementModelProject::getMatchEvents($match->id, 0, 0, Factory::getApplication()->input->getInt('cfg_which_database', 0));
							$subs   = sportsmanagementModelProject::getMatchSubstitutions($match->id, Factory::getApplication()->input->getInt('cfg_which_database', 0));
```

Im Zuge dessen ist mir auch aufgefallen, dass das Layout default_plan.php
`$events = sportsmanagementModelProject::getMatchEvents($match->id, 0, 0, Factory::getApplication()->input->getInt('cfg_which_database', 0));`

und default_plan_sorted_by_date
`$events = sportsmanagementModelProject::getMatchEvents($match->id);`

verwendet um die Ereignisse aus dem System zu laden. Wer also default_plan_sorted_by_date verwendet und eine externe Datenbank wird vermutlich hier ein Problem haben.

**Comment by StefanKemner** [comment]
> Da ich bei mir noch keine Ereignisse verwende musste ich erst mal draufkommen wie Ereignisse überhaupt hinzugefügt werden.
> 
> Welches Layout für den Spielplan verwendest du? "Standard" oder "Sortiert nach Datum"? ![grafik](https://user-images.githubusercontent.com/15192502/237631848-c54d41d7-4580-40b3-9b69-7a238117b1f9.png)
> 
> Auf jeden Fall werden in beiden Fällen die Ereignisse angezeigt nur wurden bei mir die Icons nicht dargestellt, weil der Platz in der Tabelle zu klein gesetzt war. Kann natürlich auch an dem verwendeten Joomla-Template liegen.
> 
> Für beide Layouts hat es bei mir so funktioniert:
> ändern auf
> 
> components\com_sportsmanagement\views\teamplan\tmpl\default_plan.php
> 
> ```
> 					if ($this->config['show_events'])
> 					{
> 						?>
>                         <td width='5' class='ko'>
> 							<?php
> 							$events = sportsmanagementModelProject::getMatchEvents($match->id, 0, 0, Factory::getApplication()->input->getInt('cfg_which_database', 0));
> 							$subs   = sportsmanagementModelProject::getMatchSubstitutions($match->id, Factory::getApplication()->input->getInt('cfg_which_database', 0));
> ```
> 
> habe ich abgeändert auf:
> 
> ```
> 					if ($this->config['show_events'])
> 					{
> 						?>
>                         <td width='3%' class='ko'>
> 							<?php
> 							$events = sportsmanagementModelProject::getMatchEvents($match->id, 0, 0, Factory::getApplication()->input->getInt('cfg_which_database', 0));
> 							$subs   = sportsmanagementModelProject::getMatchSubstitutions($match->id, Factory::getApplication()->input->getInt('cfg_which_database', 0));
> ```
> 
> Im Zuge dessen ist mir auch aufgefallen, dass das Layout default_plan.php `$events = sportsmanagementModelProject::getMatchEvents($match->id, 0, 0, Factory::getApplication()->input->getInt('cfg_which_database', 0));`
> 
> und default_plan_sorted_by_date `$events = sportsmanagementModelProject::getMatchEvents($match->id);`
> 
> verwendet um die Ereignisse aus dem System zu laden. Wer also default_plan_sorted_by_date verwendet und eine externe Datenbank wird vermutlich hier ein Problem haben.

Ich verwende die Standardansicht, weil bei "Sortiert nach der Datum" der "Export to PDF" oder "Print Preview" nur den 1. Spieltag für den Druck anzeigt.

**Comment by StefanKemner** [comment]
Funktioniert jetzt 👍
