### ISSUE TITLE
J4: Teams einer Saison zuweisen

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1545]
Wenn man unter dem Stammdaten Menüpunkt "Saisons" im Backend Teams einer Saison zuweisen will:

![grafik](https://user-images.githubusercontent.com/101453485/230758570-556aa639-0491-4f1d-b5bd-3b86aa074fa3.png)

kommt folgende Fehlermeldung:

![grafik](https://user-images.githubusercontent.com/101453485/230758580-79826d12-0e14-42d8-b112-2a5432375d44.png)

Ist nicht nur bei einer neuen Saison, sondern auch bei der Laufenden

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by ortwin20000** [comment]
In der Datei administrator\components\com_sportsmanagement\views\teams\tmpl\default.php wird die season_id nicht gesetzt:
`<input type="hidden" name="season_id" value="<?php //echo $this->season_id; todo fix undefined $season_id ?>"/>`

Folgenden Workaround habe ich bei mir durchgeführt:
`<input type="hidden" name="season_id" value="<?php if (!isset($this->season_id)) $this->season_id = 0; echo $this->season_id; ?>"/>`

Damit konnte ich die Mannschaften der Saison dann zuweisen.

**Comment by StefanKemner** [comment]
Top 👍  Funtkioniert jetzt
