### ISSUE TITLE
JSM Spielstättenmodul 

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1555]
Bei der Zeitangabe im Spielstättenmodul:
![grafik](https://user-images.githubusercontent.com/101453485/237006253-d357ba0a-842f-4cb9-b64a-6abc60d534c7.png)
![grafik](https://user-images.githubusercontent.com/101453485/237006293-296d8204-0c06-4a8e-885d-581dfed96f6e.png)

.. sieht es jetzt so:
![grafik](https://user-images.githubusercontent.com/101453485/237006338-26540542-5163-4a6f-8e5b-0f24091cdfd6.png)

statt dem %i sollte da eigentclh "00", also 20:00 Uhr stehen.
Geändert wurde da von meiner Seite nichts weiter, Zeiten im Spielplan passen auch.

**Comment by diddipoeler** [comment]
Habe das mal eingebaut.
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Hmm, jetzt fühle ich mich wie zurück in die Zukunft :-)
Alle Spiele sind angesetzt auf Freitag, 20:00 Uhr, im Modul steht jetzt 22:00 Uhr:
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/101453485/194a1ff4-ee19-40ed-84ff-b9fc82de54f1)
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/101453485/1571f7d7-c12f-4843-bb7c-312ca307e4b1)

**Comment by ortwin20000** [comment]
🤔 Vermutlich wird da die Zeitzone nicht korrekt berücksichtigt. Ich weiß jetzt nicht auswendig wie das match-date übergeben wird.

Welche Zeitzone ist bei dir im Projekt hinterlegt?

**Comment by StefanKemner** [comment]
Zeitzone müßte passen:
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/101453485/1f883611-f506-47e5-b63b-0610b68bd179)

Vorher zeigte er ja auch die richtige Uhrzeit an.

**Comment by ortwin20000** [comment]
Ich habe dazu einen Nachtrag im vorigen Kommentar hinzugefügt.

**Comment by StefanKemner** [comment]
Bei mir passt es jetzt wieder 👍
