### ISSUE TITLE
J4: Stammdaten: Person neu anlegen

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1562]
Ich wollte grade in den Stammdaten einen Spieler neu Anlegen:
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/101453485/b1fc3f74-0b0e-4757-9adc-3f6c316566fa)
Oben links mit "Abbrechen" kommt man da auch nicht wieder raus, nur im Browser Seite zurück

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Geht wieder 👍
