### ISSUE TITLE
Backend funktioniert nicht in Joomla 3.10.11 - hier ein Beispiel, Sportmanagement Version : 4.17.00

### ISSUE THREAD

**Issue by robi6666** [diddipoeler/sportsmanagement#1576]
<html>
<body>
<h1 class="page-header" style="margin: 2px 0px 10px; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 28px; color: rgb(51, 51, 51); text-rendering: optimizelegibility; font-size: 26px; padding-bottom: 5px; border-bottom: 1px solid rgb(238, 238, 238); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">An error has occurred.</h1><blockquote style="padding: 0px 0px 0px 15px; margin: 0px 0px 18px; border-left: 5px solid rgb(238, 238, 238); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="label label-inverse" style="display: inline-block; padding: 2px 4px; font-size: 10.998px; font-weight: bold; line-height: 14px; color: rgb(255, 255, 255); vertical-align: baseline; white-space: nowrap; text-shadow: none; background-color: rgb(51, 51, 51); border-radius: 3px;">0</span><span> </span>Call to undefined method Joomla\CMS\Document\HtmlDocument::getWebAssetManager()<br>/home/posavina/public_html/joomla3.posavinasport.com/administrator/components/com_sportsmanagement/views/fieldsets/tmpl/default_editdata.php:21</blockquote><div style="color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Call stack
--
# | Function | Location
1 | () | JROOT/administrator/components/com_sportsmanagement/views/fieldsets/tmpl/default_editdata.php:21
2 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:701
3 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/administrator/components/com_sportsmanagement/views/fieldsets/tmpl/edit_3.php:75
4 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:701
5 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:230
6 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/administrator/components/com_sportsmanagement/libraries/sportsmanagement/view.php:578
7 | sportsmanagementView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:664
8 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_sportsmanagement/controller.php:58
9 | SportsManagementController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:702
10 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_sportsmanagement/sportsmanagement.php:276
11 | require_once() | JROOT/libraries/src/Component/ComponentHelper.php:402
12 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT/libraries/src/Component/ComponentHelper.php:377
13 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:101
14 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:159
15 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:225
16 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/index.php:51

</div>
</body>
</html>

**Comment by ortwin20000** [comment]
Ich werde gleich einen Pull-Request machen.

**Comment by robi6666** [comment]
Funktioniert
