### ISSUE TITLE
Erklärung Live-Ticker

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1583]
Gibt es eine Anleitung oder Erklärung wie der Live-Ticker eingerichtet werden kann und zu bedienen ist?

**Comment by ortwin20000** [comment]
Hab es mir selber im Code angeschaut und ein paar Fehler im Zusammenhang mit Kommentaren und Ereignissen entdeckt. Ich werde dazu später einen Pull-Request machen.

**Comment by sigal** [comment]
> Hab es mir selber im Code angeschaut und ein paar Fehler im Zusammenhang mit Kommentaren und Ereignissen entdeckt. Ich 





> Hab es mir selber im Code angeschaut und ein paar Fehler im Zusammenhang mit Kommentaren und Ereignissen entdeckt. Ich werde dazu später einen Pull-Request machen.

Die Live-Kommentar Funktion musste abgeschaltet werden, da es massive Sicherheitsprobleme gab.

Google Suche bemühen (Turtushout)

Gruss
stony

**Comment by ortwin20000** [comment]
Das hatte ich auch gefunden aber ich hab dazu immer nur die Version 0.11 gefunden.
In dem Modul ist jedoch die Version 0.12 enthalten:
```
Apr 12	0.12
----------------------------------------------------------------------
added:
1) logged user welcome message
2) guests messages mark

fixed:
sql insert bug, js fixes
```

Ich dachte deswegen wäre sie vielleicht noch benutzbar. Es funktioniert ja eh auch ohne Chat-Funktion. Ich denke die vermisst keiner.
