### ISSUE TITLE
J4: Postleitzahlenimport nicht möglich.

### ISSUE THREAD

**Issue by rogru1** [diddipoeler/sportsmanagement#1595]
Sports Management: Länder
Auswahl Land-> PLZ-Import
Der Import bricht mit folgender Fehlermeldung ab

![Bildschirmfoto vom 2023-05-30 14-46-23](https://github.com/diddipoeler/sportsmanagement/assets/89997514/b61356b8-4980-440a-afce-a39448233cbb)

![Bildschirmfoto vom 2023-05-30 14-58-55](https://github.com/diddipoeler/sportsmanagement/assets/89997514/4c8ad24b-464f-4ca9-bf4a-21735dd788d5)

**Comment by ortwin20000** [comment]
Ich teste das gerade bei mir und konnte es mit Deutschland nachstellen.
Mit welchem Land wurde es versucht?

Werde dazu einen Pull-Request erstellen.
Danach bitte noch einmal testen.

**Comment by ortwin20000** [comment]
Mit dem Try-Catch bekomme ich dann noch mehr Einträge aber zumindest werden sie nun auch alle importiert.

![grafik](https://github.com/diddipoeler/sportsmanagement/assets/15192502/66af67ce-49cd-4ad7-887d-2a6f6c8f6a21)
