### ISSUE TITLE
Matchreport

### ISSUE THREAD

**Issue by WaterpoloplayerNo7** [diddipoeler/sportsmanagement#1598]
eine Frage an Euch, warum wird mir der Trainer im Matchreport öfters angezeigt als ich diesen eingegeben habe? 
Was ich meine seht Ihr hier: http://uerdingen-masters.eu/deutsche-meisterschaften/26-deutsche-masters-wasserballmeisterschaft-in-duesseldorf/mannschaft-ak30-39/ergebnisse-und-tabelle/matchreport/0/11/35/465
Vielen Dank schon mal für Eure Hilfe

Gruß
Osterhase

**Comment by ortwin20000** [comment]
Ich habe das gemeinsam mit Osterhase behoben und werde dafür einen Pull-Request am Abend erstellen.

**Comment by ortwin20000** [comment]
Ich bin noch nicht dazu gekommen. Behoben hab ich es bereits bei Osterhase. Bei zwei Dateien müssen Anpassungen durchgeführt werden. Pull-Request kommt noch.

**Comment by svdoldie** [comment]
Bei mir sieht's wieder gut aus 👍
