### ISSUE TITLE
Wish: Notiz/Info zum Spieltag

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1600]
Wir haben öfters mal Informationen zu einem Projekt, z.B.:
"Team XY hat ab sofort eine neue Spielstätte"
" Fehlender Matchreport von Team XY" etc.

Ein Textfeld unter z.B. der Tabellenanzeige wäre da gut, wo man solche Infos anzeigen lassen kann.

Vielleicht geht das auch über "Extrafelder":
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/101453485/1a59790a-20f3-4448-abe6-8c72c5f89ba1)
aber da bin ich irgendwie nicht mit weitergekommen:
Ich hab ein Extrafeld (Textfeld) für die Projekteinstellungen angelegt, aber dann weiß ich nicht weiter..

**Comment by sigal** [comment]
[https://jsm-wiki.diddipoeler.de/index.php?title=SM-Backend:Extrafields](url)

**Comment by StefanKemner** [comment]
Da scheint es mittlerweile auch was für Projekte zu geben:
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/101453485/72707413-194a-437e-9022-1586e1cf3648)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Passt 👍
