### ISSUE TITLE
Trainingszeiten Mannschaft anlegen

### ISSUE THREAD

**Issue by StefanKemner** [diddipoeler/sportsmanagement#1603]
Macht man den Haken in "Erstellen" rein, passiert erstmal nichts:
 
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/101453485/eb00ec54-4a8c-4ab6-bf3f-b31e32330195)

geht man dann auf speichern, kommt folgende Fehlermeldung:
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/101453485/920ab116-cc8e-4ac2-860d-e2d69685757b)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by StefanKemner** [comment]
Top, geht wieder 👍
