### ISSUE TITLE
Fehler 500 bei: Stammdaten > Vereine > Vereinsdetails bearbeiten

### ISSUE THREAD

**Issue by dutschman** [diddipoeler/sportsmanagement#161]
Hallo,
das ist mein erster Issues, ich hoffe der ist so ok. ggf. bitte Verbesserungen beim Melden an mich antworten.

Komponentenversion 1.0.46

Fehlermeldung bei "Vereinsdetails bearbeiten" in Stammdaten > Vereine.
Beispielpfad: /administrator/index.php?option=com_sportsmanagement&view=club&layout=edit&id=10
Fehlermeldung:
"500 - Es ist ein Fehler aufgetreten
DateTime::__construct(): Failed to parse time string (30-11--0001) at position 0 (3): Unexpected character
Zurück zum Kontrollzentrum"

Anzeige in der Übesicht "Vereine"
        Sports Management: Joomla Version: 2.5 !
        sportsmanagementModelClubs::populateState 106 context ->com_sportsmanagement.clubs
        sportsmanagementViewClubs::init 77

        JObject Object
        (
            [_errors:protected] => Array
                (
                )

            [task] => 
            [filter.search] => 
            [filter.state] => 
            [filter.search_nation] => 
            [filter.season] => 
            [list.start] => 0
            [list.limit] => 20
            [list.ordering] => a.name
            [list.direction] => asc
        )

Gruss Sönke
aka Dutschman
www.handball-tgw.de

**Comment by diddipoeler** [comment]
Es kann noch einmal getestet werden.
