### ISSUE TITLE
Unknown column 'l.champions_complete' in 'field list'

### ISSUE THREAD

**Issue by bertderop** [diddipoeler/sportsmanagement#1615]
I have updated Sportsmanagement to version 4.17.00.
On the homepage I have this error : 1054 - Unknown column 'l.champions_complete' in 'field list'

When I open Sportsmanagement in the admin the previous projects aren't visible anymore, but the data is still in the database.
I can only see the currect project.

What could be the problem?

**Comment by diddipoeler** [comment]
Bitte einmal Adminzugangsdaten zusenden. Ich schau mir das im Backend mal an.

**Comment by bertderop** [comment]
Die Details zum Administratorzugriff finden Sie hier. Das Anmelden kann 2-3 Minuten dauern


  *   User : diddipoeler
  *   Pasword : 130823KFC
  *   URL : https://www.kfc-vrasene.be/administrator/
Met vriendelijke groeten,
Bert De Rop
Fiscaal Accountant ITAA
BOEKHOUDKANTOOR PATRICK DE ROP BV
Kerkstraat 120
9120 VRASENE
Tel: 03/775.08.75
Fax: 03/755.15.55
E-mail: ***@***.******@***.***>

Van: diddipoeler ***@***.***>
Verzonden: zondag 13 augustus 2023 9:25
Aan: diddipoeler/sportsmanagement ***@***.***>
CC: Bert De Rop ***@***.***>; Author ***@***.***>
Onderwerp: Re: [diddipoeler/sportsmanagement] Unknown column 'l.champions_complete' in 'field list' (Issue #1615)

U ontvangt niet vaak e-mail van ***@***.*** Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

Bitte einmal Adminzugangsdaten zusenden. Ich schau mir das im Backend mal an.

**Comment by bertderop** [comment]
I have sent them by email

**Comment by diddipoeler** [comment]
Bitte die kompletten Adminrechte zuordnen, damit ich auch installieren kann.

**Comment by bertderop** [comment]
I have changed it

Met vriendelijke groeten,
Bert De Rop
Fiscaal Accountant ITAA
BOEKHOUDKANTOOR PATRICK DE ROP BV
Kerkstraat 120
9120 VRASENE
Tel: 03/775.08.75
Fax: 03/755.15.55
E-mail: ***@***.******@***.***>

Van: diddipoeler ***@***.***>
Verzonden: zondag 13 augustus 2023 11:25
Aan: diddipoeler/sportsmanagement ***@***.***>
CC: Bert De Rop ***@***.***>; Author ***@***.***>
Onderwerp: Re: [diddipoeler/sportsmanagement] Unknown column 'l.champions_complete' in 'field list' (Issue #1615)

U ontvangt niet vaak e-mail van ***@***.*** Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

Bitte die kompletten Adminrechte zuordnen, damit ich auch installieren kann.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by bertderop** [comment]
Resolved !

Thank you very much !!!

Met vriendelijke groeten,
Bert De Rop
Fiscaal Accountant ITAA
BOEKHOUDKANTOOR PATRICK DE ROP BV
Kerkstraat 120
9120 VRASENE
Tel: 03/775.08.75
Fax: 03/755.15.55
E-mail: ***@***.******@***.***>

Van: diddipoeler ***@***.***>
Verzonden: zondag 13 augustus 2023 11:43
Aan: diddipoeler/sportsmanagement ***@***.***>
CC: Bert De Rop ***@***.***>; Author ***@***.***>
Onderwerp: Re: [diddipoeler/sportsmanagement] Unknown column 'l.champions_complete' in 'field list' (Issue #1615)

U ontvangt niet vaak e-mail van ***@***.*** Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

Bitte noch einmal testen.
