### ISSUE TITLE
Adding players to the team does not work

### ISSUE THREAD

**Issue by Tanoke** [diddipoeler/sportsmanagement#1620]
I can't add players to the team. The button where the addition takes place is missing, as shown in the picture. In the past, it has been included in that place.

I used
macOS Catalina 10.15.7
Firefox 118.0.1
Joomla 4.3.4
php 8.2.4
Latest version (12.10.2023) of Sportsmanagement

![AddPlayer](https://github.com/diddipoeler/sportsmanagement/assets/111390359/53ab7f19-d42b-455c-bb59-7d7d53155b36)

**Comment by ortwin20000** [comment]
In my installation the button is available.
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/15192502/beb1e9d0-850e-4d78-9606-d932bac81512)

I used Windows 11
Firefox 119.0b7
Joomla 4.3.4
php 8.2.11
Last version from github

**Comment by diddipoeler** [comment]
Ein github Update machen. Bitte noch einmal testen.

**Comment by Tanoke** [comment]
Thanks, it works fine now.
