### ISSUE TITLE
Joomla 4.4  Fehler 500 bei Modalfenster

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#1623]
![image](https://github.com/diddipoeler/sportsmanagement/assets/2417767/c478ff8c-0b13-4651-9197-66561c822f2b)
Nach Update auf Joomla 4.4 habe ich bei allen Modalfenster im JSM-Backend den im Bild gezeigten Fehler
Im Frontend tritt der Fehler nicht auf

**Comment by ortwin20000** [comment]
Den Fehler hatte ich auch schon. Liegt meiner Meinung nach an älteren Code der nicht mehr gebraucht wird. Mehr kann ich erst am Abend dazu schreiben.

**Comment by diddipoeler** [comment]
Die Frage ist erst einmal, bei welcher Funktion im Backend taucht dieser Fehler auf?

**Comment by ortwin20000** [comment]
Die Methode heißt immer setDocument().

**Comment by diddipoeler** [comment]
Bitte einmal neu installieren!

**Comment by svdoldie** [comment]
Die Modalfenster gehen wieder 👍 
Beim Github-Update kommt jetzt folgende Fehlermeldung:
Es ist ein Fehler aufgetreten.
0 Too few arguments to function Joomla\CMS\MVC\View\AbstractView::setDocument(), 0 passed in /var/www/vhosts/svdoerpum.de/httpdocs/administrator/components/com_sportsmanagement/views/githubinstall/view.html.php on line 43 and exactly 1 expected

**Comment by diddipoeler** [comment]
Deshalb hatte ich ja Neuinstallation geschrieben. 
System -> Installieren -> Erweiterungen -> Von URL installieren -> https://github.com/diddipoeler/sportsmanagement/archive/refs/heads/master.zip

**Comment by svdoldie** [comment]
Hab ich gemacht. Und nach prüfen der Modalfenster, die Github-Update-Funktion getestet

**Comment by svdoldie** [comment]
Nachdem letzten Commit geht jetzt auch das Github-Update 👍 
Vielen Dank für die schnelle Hilfe 👍 👍 👍
