### ISSUE TITLE
Joomla 4.4.1 Texte werden nicht aus Sprachdatei ersetzt

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1645]
Ich habe heute ein Update von Joomla durchgeführt. Soweit keine Probleme mit der Homepage bis das die Texte nicht aus den Sprachdateien mehr geladen werden.
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/15192502/3223631c-e9e3-43aa-9d45-3978b4e11fce)

Woran kann das liegen? Ist nur bei JSM so, bei den anderen Komponenten die ich im Einsatz habe ist alles normal.

**Comment by diddipoeler** [comment]
Habe ich jetzt auch. Was ist das denn jetzt wieder?

**Comment by ortwin20000** [comment]
https://github.com/joomla/joomla-cms/issues/42416

**Comment by ortwin20000** [comment]
Problem ist ein Zeilenumbruch in der Sprachdatei:
`COM_SPORTSMANAGEMENT_SCORESHEET_EXPORT="Spielberichtsbogen exportieren
"
`
muss geändert werden in 
`COM_SPORTSMANAGEMENT_SCORESHEET_EXPORT="Spielberichtsbogen exportieren"`

**Comment by sigal** [comment]
Pull request ist online. 💯 

Zeilenumbruch des Strings kam nicht von mir.

**Comment by sigal** [comment]
Pull request ist online. 💯 

Zeilenumbruch des Strings kam nicht von mir. OK!
