### ISSUE TITLE
Völlig falsche Aufstellungen im Spielbericht - Einstellungsthema?

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1657]
Im Spielbericht wird eine Aufstellung angezeigt. Allerdings stimmen da die Positionen nicht überein. Wie kann man das einstellen?

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/599b322f-8ace-4d03-82dd-0e3b571765c2)

Beispiel hier: 

Kobel ist Torhüter, wird im Mittelfeld angezeigt

**Comment by waiter1987** [comment]
Das geht jetzt. Mir stellt sich aber die Frage, woher JSM die Informationen nimmt, welche Aufstellung genommen werden soll? Es gibt bspw. im 4-4-2 sehr unterschiedliche Aufstellungen
- Ganz klassisch 4 Mittelfeld in einer Reihe
- klassisch auch ist hier die Raute
- 2 offensivere Außenspieler
- 2 defensivere Mittelfeldspieler
Wenn ich das jetzt alles anlege. Woher weiß JSM, welche Aufstellung die richtige ist? Ist wahrscheinlich jetzt eher eine Verständnisfrage

**Comment by diddipoeler** [comment]
Man kann ganz einfach eigene Spielfeldpositionen erstellen. Den gespeicherten Namen dann in die Spieldetails unter dem Reiter Erweitert eintragen.

**Comment by waiter1987** [comment]
das scheint jetzt zu klappen. DANKE
