### ISSUE TITLE
Auswechslungen speichert es nicht

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1658]
Bei einem Spieltag werden die Startaufstellungen gespeichert. Bei Auswechslungen passiert leider nichts. Es lädt und lädt aber wird nicht gespeichert!

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/2228b01a-d545-4dd3-b6f9-3c77d52dd557)

**Comment by ortwin20000** [comment]
Versuch es mal mit Angabe einer Position.

**Comment by waiter1987** [comment]
hat geklappt... wusste nicht, dass das "erwartet" wird. Bei JL hat er  bei Nicht-Angabe die Position aus dem Stamm genommen.
