### ISSUE TITLE
Länderzuordnungen fehlerhaft

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1659]
Es gibt eine falsche Zuordnung bei den Ländern.

Das Land "Vereinigtes Königreich"/United Kingdom besteht aus England, Schottland, Wales und Nordirland fehlt komplett. Wenn man das anlegt mit dem ISO-Code GBR wird die Flagge von England angezeigt. Das ist faktisch falsch!

Da die 4 Mitgliedsländer einzelne Fußballverbände habe, müssten hier die Länder zusätzlich separat aufgelistet werden!

 

Anmerkung:

Hier müsste ggf. mit Abhängigkeiten gearbeitet werden. Die 4 "Länder" gehören zu GB!

**Comment by sigal** [comment]
Wikipedia: Der FIFA-Ländercode ist ein aus drei Buchstaben bestehender [Ländercode](https://de.wikipedia.org/wiki/L%C3%A4ndercode), der von der [FIFA](https://de.wikipedia.org/wiki/FIFA) und den Kontinentalverbänden ([AFC](https://de.wikipedia.org/wiki/Asian_Football_Confederation), [CAF](https://de.wikipedia.org/wiki/Conf%C3%A9d%C3%A9ration_Africaine_de_Football), [CONCACAF](https://de.wikipedia.org/wiki/CONCACAF), [CONMEBOL](https://de.wikipedia.org/wiki/CONMEBOL), [OFC](https://de.wikipedia.org/wiki/Oceania_Football_Confederation) und [UEFA](https://de.wikipedia.org/wiki/UEFA)) als Abkürzung in offiziellen Wettbewerben genutzt wird.

Jedem ist freigestellt, fehlende Länder (inkl. Codes) mit dem JSM-Tool in seine DB einzupflegen.

Siehe auch: [ISO-3166-1-Kodierliste](ISO-3166-1-Kodierliste)

Für andere Sportarten als Fussball, muss jeder User selbst die Zuordnung von Codes vornehmen.

**Comment by waiter1987** [comment]
> Wikipedia: Der FIFA-Ländercode ist ein aus drei Buchstaben bestehender [Ländercode](https://de.wikipedia.org/wiki/L%C3%A4ndercode), der von der [FIFA](https://de.wikipedia.org/wiki/FIFA) und den Kontinentalverbänden ([AFC](https://de.wikipedia.org/wiki/Asian_Football_Confederation), [CAF](https://de.wikipedia.org/wiki/Conf%C3%A9d%C3%A9ration_Africaine_de_Football), [CONCACAF](https://de.wikipedia.org/wiki/CONCACAF), [CONMEBOL](https://de.wikipedia.org/wiki/CONMEBOL), [OFC](https://de.wikipedia.org/wiki/Oceania_Football_Confederation) und [UEFA](https://de.wikipedia.org/wiki/UEFA)) als Abkürzung in offiziellen Wettbewerben genutzt wird.
> 
> Jedem ist freigestellt, fehlende Länder (inkl. Codes) mit dem JSM-Tool in seine DB einzupflegen.
> 
> Siehe auch: [ISO-3166-1-Kodierliste](ISO-3166-1-Kodierliste)
> 
> Für andere Sportarten als Fussball, muss jeder User selbst die Zuordnung von Codes vornehmen.

Leider geht der Link nicht zur Kodierliste.

Wie dem auch sei. 

Das Land England fehlt. Das ist bei importierten Dateien, wo es englische Spieler, Teams usw. gibt jetzt alles nachpflegbar. Wo ich drüber stolpere ist die Flaggenthematik.

Und mein Problem dabei ist auch, dass das "Land" England so als solches nicht existiert. Das Land dazu ist das Vereinigte Königreich (UK). England hat halt nur einen eigenen Fussballverband und daher wird das als einzelne Nationalmannschaft und Nation im Fussball gesehen.

Rein logisch betrachtet ist der ISO-Code für England EN bzw. ENG.

Bspw. ist ja Schottland mit im Stamm von JSM drin
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/c68fa61d-93b5-49ae-9c9c-df195013b28a)


Ich habe das Vereinigte Königreich mal hinzugefügt. Und jetzt wird es komisch.
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/643edaf7-70c0-4911-b89c-e9644a6b9be1)


So sieht es aus, wenn Alpha-2 GB und Alpha-3 GBR ist.
--> das ist die Flagge von England!

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/91073e33-487f-4383-8b78-336cbaaea979)

Wenn ich Alpha-2 und Alpha-3 jeweils nur GB mache, erscheint der "Union Jack". Das wäre die korrekte Flagge für UK!

Es stellt sich mir hieraus die Frage, welchen Code man braucht, um England und Wales nachpflegen zu können. Der von mir angenommene EN bzw. ENG geht nicht. Da gibt es keine Flaggenzuordnung. 

Sicherlich kann ich daher gehen, un die Alpha-Codes so entsprechend pflegen, dass die englische Flagge erscheint. Wie ist das mit Wales?

**Comment by waiter1987** [comment]
Wenn man ISO-3166-1 bei Wikipedia nachschaut, kommt für UK das hier:
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/7481664f-8d20-4d09-af6f-55090476d25d)

**Comment by sigal** [comment]
Ich kenn das Ganze!

Das passt aber zu Schottland wieder nicht. Das ist ja zum Haare raufen.

Schnellkurs: z.B. England (DB)
Alle Flaggen sind (oder werden) im Ordner images/com_sportsmanagement/database/flags/ als ALPHA2-Code gesichert
Für England wurde es von mir als images/com_sportsmanagement/database/flags/en.png abgelegt.

Datenbankeintrag:


![Bildschirmfoto vom 2024-01-11 13-39-30](https://github.com/diddipoeler/sportsmanagement/assets/5115688/85c2e359-d62c-415a-97c8-f30f6f207845)

Man muss sich nur zu helfen wissen.
Wenn es keinen ISO-Code gibt, dann mal die Phantasie fragen und einen Code erfinden, der noch nicht vorhanden ist. (Wichtig ALPHA 2-Code)

**Comment by waiter1987** [comment]
> Ich kenn das Ganze!
> 
> Das passt aber zu Schottland wieder nicht. Das ist ja zum Haare raufen.
> 
> Schnellkurs: z.B. England (DB) Alle Flaggen sind (oder werden) im Ordner images/com_sportsmanagement/database/flags/ als ALPHA2-Code gesichert Für England wurde es von mir als images/com_sportsmanagement/database/flags/en.png abgelegt.
> 
> Datenbankeintrag:
> 
> ![Bildschirmfoto vom 2024-01-11 13-39-30](https://private-user-images.githubusercontent.com/5115688/295920309-85c2e359-d62c-415a-97c8-f30f6f207845.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5Nzg2MDAsIm5iZiI6MTcwNDk3ODMwMCwicGF0aCI6Ii81MTE1Njg4LzI5NTkyMDMwOS04NWMyZTM1OS1kNjJjLTQxNWEtOTdjOC1mMzBmNmYyMDc4NDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMTMwNTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjZlNDQ5MWNmNGQ5NzM4YTJkMjIzMTkzNmFiNTY0ZTI4ZWVmYjAwZDc1NDAxZTM3YzNiMjcxZGFjYjczOGEwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sUA7HSjHO3OO8TNCLA-AG9Rg-hqaLd-0Fgnqo4bYRFI)
> 
> Man muss sich nur zu helfen wissen. Wenn es keinen ISO-Code gibt, dann mal die Phantasie fragen und einen Code erfinden, der noch nicht vorhanden ist. (Wichtig ALPHA 2-Code)

Habe ich genauso gemacht jetzt. 1:1 gleich oder ich habe irgendwas übersehen...

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/a081f742-7918-4645-a782-686396356a1c)
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/9c2fea92-8276-4b21-ab3d-2cb14978468e)


Es ist nur keine Flagge zu sehen :-(

**Comment by ortwin20000** [comment]
Die Flagge existiert auch unter dem von dir eingetragenen Pfad?

**Comment by waiter1987** [comment]
ja 
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/b616e813-1ded-40ed-b623-d36c944c6543)

**Comment by waiter1987** [comment]
nach meinem logischen Verständnis müssten da aber viel mehr PNG-Dateien drin sein - also für jedes Land eine PNG. Sind aber nur 21 PNG...

**Comment by sigal** [comment]
Scheint so, dass die Flaggen nicht importiert wurden!

![Sports-Management-Komponentenverwaltung-JSM-Demo-Site-mit-Joomla-4-Administration](https://github.com/diddipoeler/sportsmanagement/assets/5115688/e964cb95-de74-460c-8e73-0636e3aee548)

Bei Auswahl bitte 2x auf Upload klicken

**Comment by waiter1987** [comment]
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/b7cc95ff-ca7f-4a3b-b398-ceb51541f3a6)

:-(

**Comment by sigal** [comment]
muss für php8 umprogrammiert werden

**Comment by waiter1987** [comment]
Das kann ich sicherlich nicht selber machen oder?

**Comment by ortwin20000** [comment]
Also bei mir mit PHP8 funktioniert der Bilder-Upload.
Tritt der Fehler beim Aufruf der Maske auf oder beim versuchten Hochladen der Flaggen?

**Comment by waiter1987** [comment]
Bei versuchten hochladen. Also beim Betätigen des Buttons "Bilder-Import"

**Comment by waiter1987** [comment]
Ich habe Joomla 5x im Einsatz

**Comment by sigal** [comment]
Bitte mal den Debug_Modus einschalten.
Fehler berichten auf Maximum.
Dann Fehlermeldung posten.

> Unter Joomla 3.x mit php8 funktioniert es, mit Joomla 4.x, 5.x nicht.

Es funktioniert doch ALLES.

**Comment by waiter1987** [comment]
<html>
<body>
<div id="system-message-container" aria-live="polite" style="box-sizing: border-box; color: rgb(33, 37, 41); font-family: Roboto, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(237, 242, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><joomla-alert type="info" close-text="Schließen" dismiss="true" role="alert" style="box-sizing: border-box; --jui-alert-min-width: 250px; --jui-alert-padding: .5rem 1.25rem; --jui-alert-margin: 0 0 1rem 0; --jui-alert-border: 1px solid transparent; --jui-alert-border-radius: .25rem; --jui-alert-animation-duration: .5s; --jui-alert-animation-timing-function: ease-in-out; --jui-alert-button-color-dark: #000; --jui-alert-button-color-light: #fff; --jui-alert-success-color: #234423; --jui-alert-success-background-color: #d9e6d9; --jui-alert-success-border-color: #cadcca; --jui-alert-success-link-color: #122212; --jui-alert-info-color: #0c5460; --jui-alert-info-background-color: #d1ecf1; --jui-alert-info-border-color: #bee5eb; --jui-alert-info-link-color: #062c33; --jui-alert-warning-color: #7d5a29; --jui-alert-warning-background-color: #fcefdc; --jui-alert-warning-border-color: #fbe8cd; --jui-alert-warning-link-color: #573e1c; --jui-alert-danger-color: #712b29; --jui-alert-danger-background-color: #f7dddc; --jui-alert-danger-border-color: #f4cfce; --jui-alert-danger-link-color: #4c1d1b; min-width: 16rem; padding: 0px; margin-top: ; margin-right: ; margin-bottom: 1rem; margin-left: ; border: 1px solid var(--alert-accent-color, var(--template-bg-dark)); border-radius: 0.25rem; animation-duration: var(--jui-alert-animation-duration, .5s); animation-timing-function: var(--jui-alert-animation-timing-function, ease-in-out); display: flex; color: var(--alert-accent-color, var(--template-bg-dark)); background-color: var(--alert-bg-color, var(--white)); width: 1547px; transition: opacity 0.15s linear 0s; position: relative; --alert-accent-color: var(--template-bg-dark-70); --alert-bg-color: var(--body-bg); animation-name: joomla-alert-fade-in;"><div class="alert-heading" style="box-sizing: border-box; color: var(--white); font-size: 1rem; background: var(--alert-accent-color, var(--template-bg-dark)); flex-direction: column; place-content: center; padding: 0.8rem; line-height: normal; display: flex;"><span class="visually-hidden" style="box-sizing: border-box; clip: rect(0px, 0px, 0px, 0px) !important; white-space: nowrap !important; border: 0px !important; width: 1px !important; height: 1px !important; margin: -1px !important; padding: 0px !important; overflow: hidden !important; position: absolute !important;"><br class="Apple-interchange-newline">info</span></div><div class="alert-wrapper" style="box-sizing: border-box; font-size: 1rem; width: 1503.41px;"><div class="alert-message" style="box-sizing: border-box; font-size: 1rem; padding: 0.15rem 0.3rem; margin: 0.5rem; padding-inline-end: 2rem;">JSMModelAdmin::__construct 170 layout default</div></div></joomla-alert></div><div class="row" style="box-sizing: border-box; --gutter-x: 2rem; --gutter-y: 0; margin-top: calc(-1 * var(--gutter-y)); margin-right: calc(-.5 * var(--gutter-x)); margin-left: calc(-.5 * var(--gutter-x)); flex-wrap: wrap; display: flex; color: rgb(33, 37, 41); font-family: Roboto, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(237, 242, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="col-md-12" style="box-sizing: border-box; padding-right: calc(var(--gutter-x) * .5); padding-left: calc(var(--gutter-x) * .5); margin-top: var(--gutter-y); flex: 0 0 auto; width: 1579px; max-width: 100%;"><h1 style="box-sizing: border-box; color: var(--heading-color); margin-top: 0px; margin-bottom: 0.5rem; font-weight: 400; line-height: 1.2; font-size: 1.65rem;">Es ist ein Fehler aufgetreten.</h1><blockquote class="blockquote" style="box-sizing: border-box; margin: 0px 0px 1rem; font-size: 1.25rem;"><span class="badge bg-secondary" style="box-sizing: border-box; --badge-padding-x: .2rem; --badge-padding-y: .3rem; --badge-font-size: .75rem; --badge-font-weight: 700; --badge-color: #fff; --badge-border-radius: .2rem; padding: var(--badge-padding-y) var(--badge-padding-x); font-size: var(--badge-font-size); font-weight: var(--badge-font-weight); color: var(--badge-color); text-align: center; white-space: nowrap; vertical-align: baseline; border-radius: var(--badge-border-radius); line-height: 1; display: inline-block; --bg-opacity: 1; background-color: var(--secondary) !important; margin-bottom: 0px;">1064</span><span> </span>You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ASC ORDER BY folder ASC' at line 3</blockquote><div style="box-sizing: border-box;"><h2 id="caption" style="box-sizing: border-box; color: var(--heading-color); margin-top: 0px; margin-bottom: 0.5rem; font-weight: 700; line-height: 1.2; font-size: 1.5rem;">Call Stack</h2>
# | Function | Location
-- | -- | --
1 | () | JROOT/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php:138
2 | mysqli->prepare() | JROOT/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php:138
3 | Joomla\Database\Mysqli\MysqliStatement->__construct() | JROOT/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php:1020
4 | Joomla\Database\Mysqli\MysqliDriver->prepareStatement() | JROOT/libraries/vendor/joomla/database/src/DatabaseDriver.php:1785
5 | Joomla\Database\DatabaseDriver->setQuery() | JROOT/administrator/components/com_sportsmanagement/models/smimageimports.php:74
6 | sportsmanagementModelsmimageimports->getXMLFolder() | JROOT/administrator/components/com_sportsmanagement/views/smimageimports/view.html.php:41
7 | sportsmanagementViewsmimageimports->init() | JROOT/administrator/components/com_sportsmanagement/libraries/sportsmanagement/view.php:514
8 | sportsmanagementView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:697
9 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_sportsmanagement/controller.php:58
10 | SportsManagementController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
11 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_sportsmanagement/sportsmanagement.php:276
12 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
13 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
14 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
15 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
16 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
17 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
18 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
19 | require_once() | JROOT/administrator/index.php:32

</div></div></div>
</body>
</html>

**Comment by waiter1987** [comment]
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/8c60e53d-2986-4dcd-acef-3a4103769d7d)
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/69d70d5b-d789-418c-92b1-eb8bbff752ef)

**Comment by ortwin20000** [comment]
Das Problem dürfte sein, dass entweder in der Datenbank unter sportsmanagement_pictures keine Einträge vorhanden sind oder das die xml-Dateien dazu fehlen.

**Comment by waiter1987** [comment]
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/caab70e2-3177-457b-ae53-29bd89adeb33)

Die Tabelle ist bei mir mit 92 Datensätzen befüllt. ob da was fehlt, kann ich nicht sagen. Welche XML-Datei müsste denn da sein?

**Comment by ortwin20000** [comment]
Kannst du mal versuchen in der Datei administrator\components\com_sportsmanagement\models\smimageimports.php die Zeile 72 zu ändern?
`->group('folder ASC');`
auf
`->group('folder');`

**Comment by waiter1987** [comment]
Das hat geklappt. Ich habe das fix geändert. Konnte dann die Flaggen importieren.

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/35fd8d5f-f2f4-497a-a298-73127f150b93)

Nur ist die Flagge nach wie vor nicht drin :-( 
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/9edff7b1-1d52-49db-8001-b82c2cf22c63)

**Comment by ortwin20000** [comment]
Deaktviere mal
![grafik](https://github.com/diddipoeler/sportsmanagement/assets/15192502/1dd68457-6b25-4d87-b1ba-c704f2d3b73b)

**Comment by waiter1987** [comment]
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/3032a234-4329-4b1c-95a9-96b2610b4469)

Treffer! 

VIELEN DANK
