### ISSUE TITLE
Player - Spielhistorie Summen falsch

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1662]
Ich habe bei einem Spieler ein Spiel in der Champions League eingetragen. Allerdings wird im Player dies in der Summer nicht angezeigt!

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/4d05feaa-6266-4f9e-ab5e-8041a1dfc132)
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/5e55a2ba-aaac-49ed-af62-3bf076844935)

**Comment by ortwin20000** [comment]
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/c72ddbe2-493b-4438-8f03-43e76f03a992)
Dürfte ein komischer Bug sein. Obwohl das Array für die Liga schon erzeugt wurde, hüpft er hier wieder rein und überschreibt natürlich die alten Werte. Muss ich im Internet suchen ob ich dazu etwas finde.

**Comment by ortwin20000** [comment]
Fehler gefunden:
`if ( !array_key_exists( $player_hist->league_id, $this->LeaguehistoryPlayer ) );`

da ist wohl ein ";" zuviel

`if ( !array_key_exists( $player_hist->league_id, $this->LeaguehistoryPlayer ) )`

**Comment by waiter1987** [comment]
behoben. Vielen Dank
