### ISSUE TITLE
Schiedsrichter-Positionen werden nicht gesetzt, ergo keine Schiedsrichter nutzbar

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1665]
Wenn ich einen Schiedsrichter zu einem Projekt zuordnen möchte, kommt das:
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/beb2f468-1e5d-4cf9-8619-0e2f943954d1)

Bei bereits zugewiesenen (aufgrund des JL-Imports), wähle ich die Position bei Schiedsrichter aus:
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/7225aca4-9e7e-4cd7-a863-a0897813c07e)
und nach dem Speichern sieht es so aus:
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/7db6b8ef-3729-4756-aeef-6e05f274ecb8)

Wenn ich auf den Icon neben dem Namen klicke, kommt das:
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/86c06c74-5594-4e2d-88a8-f0ed8407b49c)

**Comment by waiter1987** [comment]
Gibt es hier eine Lösung? Sieht ja hier wie ein Ansatz aus, was @ortwin20000 Anfang Februar geschrieben hat.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by waiter1987** [comment]
Zuordnung ist schon mal vorhanden. 
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/122f55d6-1032-4151-b1ce-b15e56714905)


Wenn ich das versuche zu speichern, kommt irgendwann ein Time-Out.

Im Spieltag selber fehlen die Namen der Schiedsrichter
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/dda0aa72-b1fb-4a6c-b06b-8cc66176ce0f)


Hier eine Ansicht, wo die Zuordnung noch über JL lief...

**Comment by diddipoeler** [comment]
Ja ja, ich taste mich langsam vorwärts.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
