### ISSUE TITLE
Schiedsrichter im Backend weg

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1666]
Wenn man über die aktuelle Saison die Projekte aufruft, sind die Schiedsrichter da:
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/6fd5176f-e619-4c0b-a8b6-2fccec57ab94)

klickt man eines der Buttons an und geht dann mit dem Zurückbutton zurück zur Übersicht, ist der Button für die Schiedsrichter weg
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/212f9bae-8f21-43de-82fb-69195c31a210)

**Comment by ortwin20000** [comment]
Hab einen Pull-Request dafür gemacht. Betrifft nur >= Joomla 4

**Comment by waiter1987** [comment]
bitte auch gleich J5 mit bedenken. DANKE

**Comment by waiter1987** [comment]
Ist behoben. DANKE
