### ISSUE TITLE
Gleiche Ereignisse werden nicht gespeichert

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1673]
Ich habe die Herausforderung, dass bei nem Spiel die Events mit dem gleichen Zeitstempel und Spieler nicht gespeichert werden!

Betrifft ja bspw.
Tor und Elfmetertor
Tor und Vorlage (bspw. bei Elfmetertor)

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/ea5d3508-7662-4a7f-818e-20e1db02c9f4)

**Comment by ortwin20000** [comment]
Du könntest mal die Einstellung von #1436 versuchen.

**Comment by waiter1987** [comment]
hat geklappt... DANKE
