### ISSUE TITLE
Menüeintrag Ereignistabellen

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1674]
Ich habe vor, mehrere Tabellen als Ereignistabellen anzeigen zu lassen.

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/2a51b0e9-c5a4-4d45-890f-b481f9ed148e)

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/23943de5-164e-47cb-94d5-aff6da1d4a8a)

Allerdings wird nur gelbe Karte angezeigt.
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/ad433972-9ad5-47df-a662-099dbcf1bb80)

Woran liegt das? Was kann ich da noch probieren? Muss im Projekt selber irgendwas noch ausgewählt werden?

**Comment by waiter1987** [comment]
Dank @ortwin20000 haben wir es herausgefunden, dass die Events noch nicht die Sportart Fußball drin hatten. Ist jetzt gemacht und es werden auch alle angezeigt.

ABER:
Ich möchte 2 unterschiedliche Eingrenzungen anzeigen.
Einmal alles, was mit Toren zu tun hat und einmal alles, was ins FairPlay reinkommt...

Es zeigt aber sowohl als auch ALLES an.

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/2c9e96e1-0d51-4d89-a8ba-688e19ff4585)
Das soll die Eingrenzung sein

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/f9f721b4-8957-4fe1-8abc-0e364bf268d4)
Das zeigt es an

**Comment by ortwin20000** [comment]
Ich glaube es liegt an dem SEF. Ohne funktioniert es und mit wird das Array mit den Ereignissen eben als Text "Array" ausgegeben und ist dann mit JInput nicht verfügbar.

So sieht es ohne SEF aus wo das Array "evid" mit den einzelnen Einträgen gefüllt ist:
`index.php?option=com_sportsmanagement&view=eventsranking&cfg_which_database=0&s=399:&p=4617:1-bundesliga-2023-2024&division=0&tid=0&evid[0]=65:eigentor&evid[1]=67:elfmetertor&evid[2]=66:vorlage&evid[3]=61:tor&mid=0&Itemid=2090`
mit SEF:
`/torschuetzen/eventsranking/0/399:/4617:1-bundesliga-2023-2024/0/0/Array/0.html`

![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/8b45543e-f4d8-42ae-a2f4-1dede300e38a)

![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/8ac15b21-e933-4f1e-9ec4-5095f27b3daa)

**Comment by ortwin20000** [comment]
Die SQL-Abfrage dürfte hier nicht korrekt sein aber ob es an deinen importierten Projekten liegt kann ich nicht sagen.
Am Beispiel von "1. Bundesliga 2022/23" und dem Ereignis "Vorlage":
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/76f5d75d-ef52-4472-b26a-76d0be1086d0)

Die SQL-Abfrage lautet hierzu:
```
select SUM(me.event_sum) as p,pl.firstname AS fname,pl.nickname AS nname,pl.lastname AS lname,pl.country,pl.id AS pid,pl.picture,tp.picture AS teamplayerpic,t.id AS tid,t.name AS tname,
CONCAT_WS( ':', pl.id, pl.alias ) AS person_slug,
CONCAT_WS( ':', t.id, t.alias ) AS team_slug,
CONCAT_WS( ':', pt.id, t.alias ) AS projectteam_slug
from kz80i_sportsmanagement_match_event AS me
inner join kz80i_sportsmanagement_season_team_person_id AS tp ON me.teamplayer_id = tp.id
inner join kz80i_sportsmanagement_season_team_id AS st ON st.team_id = tp.team_id and st.season_id = tp.season_id
inner join kz80i_sportsmanagement_project_team AS pt ON pt.team_id = st.id
inner join kz80i_sportsmanagement_project AS p ON pt.project_id = p.id and p.season_id = st.season_id
inner join kz80i_sportsmanagement_team AS t ON t.id = st.team_id
inner join kz80i_sportsmanagement_person AS pl ON tp.person_id = pl.id
where me.event_type_id = 66
and pl.published = 1
and pt.project_id IN (4307)
and p.id IN (4307)
group by me.teamplayer_id
order by p desc;
```
Mit der Abfrage werden aber für den Spieler "Randal Kolo Muani" 17 Vorlagen gezählt. Hier werden aber drei Spiele vom "DFB Pokal 2022/23" mitgezählt.

Wenn ich die Abfrage mit zwei Joins erweitere bekomme ich das richtige Ergebnis:
```
select SUM(me.event_sum) as p,pl.firstname AS fname,pl.nickname AS nname,pl.lastname AS lname,pl.country,pl.id AS pid,pl.picture,tp.picture AS teamplayerpic,t.id AS tid,t.name AS tname,
CONCAT_WS( ':', pl.id, pl.alias ) AS person_slug,
CONCAT_WS( ':', t.id, t.alias ) AS team_slug,
CONCAT_WS( ':', pt.id, t.alias ) AS projectteam_slug
from kz80i_sportsmanagement_match_event AS me
inner join kz80i_sportsmanagement_match AS m ON m.id = me.match_id
inner join kz80i_sportsmanagement_round AS r ON r.id = m.round_id
inner join kz80i_sportsmanagement_season_team_person_id AS tp ON me.teamplayer_id = tp.id
inner join kz80i_sportsmanagement_season_team_id AS st ON st.team_id = tp.team_id and st.season_id = tp.season_id
inner join kz80i_sportsmanagement_project_team AS pt ON pt.team_id = st.id
inner join kz80i_sportsmanagement_project AS p ON pt.project_id = p.id and p.season_id = st.season_id
inner join kz80i_sportsmanagement_team AS t ON t.id = st.team_id
inner join kz80i_sportsmanagement_person AS pl ON tp.person_id = pl.id
where me.event_type_id = 66
and pl.published = 1
and pt.project_id IN (4307)
and p.id IN (4307)
and r.project_id in (4307)
group by me.teamplayer_id
ORDER BY `me`.`match_id` ASC;
```

![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/9828cb24-c7b5-4328-baf9-4a0b8b03c9f5)

**Comment by ortwin20000** [comment]
> Jetzt ist mir aufgefallen, dass in den Eventsranking-Tabellen die Events in der kompletten Saison und nicht im Projekt gezählt werden. Am Beispiel 1. BL Wirtz

Kannst du das bitte noch einmal testen ob es jetzt richtig rechnet.
Ansonsten ist hier nur noch das SEF-Thema offen oder?

**Comment by waiter1987** [comment]
Passt. Danke
