### ISSUE TITLE
Zuordnung im Staff mehr als 1x

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1676]
Ich habe die aktuelle DFB Pokal-Runde mal bestück, auch schon vorab mit den jeweiligen Trainer. Die Auswahl erfolgte jeweils nur der Trainer.

Das Ergebnis habe ich auch z.T. in anderen Projekten 
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/f38d46f4-dbdb-4dbd-8311-da13fc9dee4f)

Es ist aber nur ein Trainer zugeordnet ... hier am Beispiel Hertha BSC 
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/da54d5dc-269c-4d6d-865d-4c246e5879b5)

Ich kann das auch nicht mehr abwählen. Mache ich das und speichere dies, kommt oben, dass dies gespeichert ist, aber es bleibt beim Ursprung mit der Zuordnung.
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/0142d0e4-5b48-415e-8d62-5f62c97e77be)

**Comment by waiter1987** [comment]
Ich habe jetzt folgendes gemacht.
1) Ich ordne den Trainer zu
2) Ich ordne die Spieler zu

Dann ist der Trainer 2x drin. Kann das nicht mehr abwählen! Es werden da auch 2 Spiele in den Statistiken gezählt. Als würde JSM beim Speichern der Spieler die Trainer "nochmal" und damit doppelt speichern!

Wenn ich die Spieler bspw. in 2 Etappen speichere, dann geht der Count beim Trainer hoch.

Getestet habe ich:
Trainer zugewiesen und gespeichert
Torhüter zugewiesen und gespeichert - da war es schon 2 Zuordnungen!
1 Abwehrspieler zugewiesen und gespeichert - da sind es 3 Zuordnungen beim Trainer!

**Comment by waiter1987** [comment]
Ích habe hier mal in der Datenbank geschaut. Was mir hier auffällt ist, dass die Projektposition hier "nur" 3stellig ist. Bei anderen ist sie 5 stellig. Ich lösche die doppelten erstmal raus, um meine Datensätze zu bereinigen. 
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/af1f03c8-2582-4507-b5bf-6c05124b47be)


Ich umgehe das aktuell, in dem ich zuerst die Spieler anlege inkl. Auswechslungen und dann die Trainer nachziehe. Schön und richtig ist das Verhalten aber so oder so nicht...

**Comment by ortwin20000** [comment]
Ich habe mich damit jetzt ein wenig auseinandergesetzt:
In der Maske hat das Feld für den Trainer die Projektposition 101785
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/08816a4b-6d18-4c2c-96c6-6c0c64c315d9)
In der Datenbank steht auch der importierte Joomleague-Eintrag für "Ole Werner" drin:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/b2fb3000-c940-4611-9fd9-63d105853a10)

Wenn ich jetzt Änderungen vornehme und den Eintrag speichern möchte, erzeugt er mir in der Datenbank einen neuen Eintrag mit einer anderen ID für die Projektposition.
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/0e2f101d-9426-4796-bd00-fda989495042)

**Comment by ortwin20000** [comment]
Ich habe jetzt den Fehler gefunden warum er die Einträge nicht löscht:
Es fehlt ein `$db->setQuery($query);` beim Speichern des Mitarbeiterstab.
Dafür mache ich gleich einen Pull-Request.

Was ich jetzt aber noch nicht verstanden habe:
Ich hätte im Code jetzt auch die Projektposition-ID in der Speicherlogik geändert, dass er in deinem Fall die 101785 verwendet. Damit funktioniert es und wird mir auch alles korrekt angezeigt.

Wenn ich aber nach dem Beheben des Fehlers beim Speichern den alten Wert für die Projektposition-ID von 205 beibehalte funktioniert es auch.

@diddipoeler Was ist denn jetzt der richtige Wert der hier eingetragen werden muss?
Ich würde die Logik derzeit mal beibehalten wie es bisher ist. Beim Speichern werden ja jetzt eh alle Einträge gelöscht und neu eingetragen. Wichtig wäre aber hier doch zu wissen welcher Wert hier erwartet wird.
