### ISSUE TITLE
2-Punkte-Regel - Wie darstellen?

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1682]
Da im WIki dazu nichts steht, hab ich im Quellcode geschaut und die Tabelle hier gefunden.
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/e2c6a468-ad07-4c03-bda9-e9d1e7feb403)

Welches Kriterium muss verwendet werden, um die 2 Punkte-Regel anzuwenden?

Ich habe die "OLDNEGPOINTS" probiert. Da hat er aber falsche Minuspunkte. 
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/ddfdcd1b-e472-44b0-a779-dcf18fa392fa)

In dem Beispiel müsste der HSV 7:0 Punkte haben. Statt der 0 sind da aber 29. Wo kommt das her? Wie kann man die 2 Punkte-Regelung richtig darstellen?

Auch bei Diddi wird es nicht korrekt dargestellt:
https://fussballineuropa.de/index.php/component/sportsmanagement/ranking/0/0/11/0/0/0/0/0?Itemid=-1

**Comment by diddipoeler** [comment]
Mach mal bitte ein Update der Komponente und trage im Reiter Wettbewerb, im Projekt, zum Feld Reguläre Punkte das 2,1,2 ein.

**Comment by waiter1987** [comment]
Jetzt hat es alles durchgemischt...

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/0d3c394b-1d11-4f60-a76d-8daba4e87054)


Rechts die korrekte Tabelle, wie sie dargestellt werden müsste. Die Pluspunkte stimmen nicht!
Beispiel 1. FC Köln
17 Siege = 34 Pkt Plus
11 Untenschieden = 11 Pkt Plus
     11 Pkt Minus
2 Niederlagen = 2 Pkt Minus

Macht 45:15
Die Minuspunkte stimmen jetzt. Die Pluspunkte nicht mehr.

Ist hier OLDNEGPOINTS das richtige Parameter?
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/e694be2f-7e7c-4825-a80b-e0f38c4a8246)

**Comment by diddipoeler** [comment]
Mach mal bitte ein Update der Komponente.

**Comment by diddipoeler** [comment]
Sorry, mein Fehler:
Trage im Reiter Wettbewerb, im Projekt, zum Feld Reguläre Punkte das 2,1,0 ein.

**Comment by waiter1987** [comment]
Mit 2,1,2
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/f0e71afa-153a-4e7e-98a7-53e187e93e1f)

**Comment by waiter1987** [comment]
Da haut es hin ... kleines ABER:
Es zählt hier bei Punktgleichheit und gleicher Tordifferenz zuerst der direkte Vergleich. Welches Kennzeichen ist das? In dem Beispiel ist der Meidr. SV vor Eintracht Frankfurt (3:1 und 2:2)

**Comment by waiter1987** [comment]
Nur der Vollständigkeit noch:
Wenn 2,1,0 dann zählt in der Tabelle bei den Negativ-Punkten nur das Unentschieden. Wäre bei Köln 45:11 Punkte.

**Comment by diddipoeler** [comment]
Verstehe ich jetzt gerade nicht. Bei mir rechnet er das richtig:
https://www.fussballineuropa.de/index.php/component/sportsmanagement/ranking/0/0/150925:mitteldeutsche-meisterschaft-gau-thueringen-1928-29-1-klasse-ostthueringen/0/2648040:spiele/0/0/0?Itemid=-1

**Comment by waiter1987** [comment]
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/2734f677-8d7b-4f58-93cd-c10fd373bf2d)
So ist es jetzt gespeichert

Hier das Ergebnis:
https://sport.daniel-frase.de/1-bundesliga-historie/1-bundesliga-1963-1969/1-bundesliga-1963-1964-spieltag/resultsranking/0/331:1963-1964/3831:1-bundesliga-1963-1964/0

**Comment by sigal** [comment]
Eingabe der Sortierkriterien, alle mit Kommas getrennt. Mögliche Werte sind:<p><ul><li><strong>POINTS</strong>: Punkte</li><li><strong>DIFF</strong>: Tordifferenz</li><li><strong>FOR</strong>: geschossene Tore</li><li><strong>AGAINST</strong>: erhaltene Tore</li><li><strong>SCOREPCT</strong>: Prozent Punkte pro Spie</li><li><strong>PLAYED</strong>: gespielte Spiele, mehr Spiele, höher in der Rangliste</li><li><strong>PLAYEDASC</strong>: gespielte Spiele, weniger Spiele, höher in der Rangliste</li><li><strong>WINS</strong>: Siege</li><li><strong>BONUS</strong>: Bonuspunkte</li><li><strong>SCOREAVG</strong>: Durchschnitt geschossener Tore</li><li><strong>WINPCT</strong>: Siegwahrscheinlichkeit in %</li><li><strong>GB</strong>: gameback</li><li><strong>H2H</strong>: Direkter Vergleich zwischen 2 Mannschaften (S/U/V)</li><li><strong>H2H_DIFF</strong>: Direkter Vergleich zwischen 2 Mannschaften (Tordifferenz)</li><li><strong>H2H_FOR</strong>: Direkter Vergleich zwischen 2 Mannschaften (Geschossene Tore)</li><li><strong>H2H_AWAY</strong>: Direkter Vergleich zwischen 2 Mannschaften (Erhaltene Tore)</li><li><strong>LEGS_DIFF</strong>: Legs Differenz</li><li><strong>LEGS_WIN</strong>: Legs Gewonnen</li><li><strong>LEGS_RATIO</strong>: Legs Durchschnitt</li></ul><p> Alle Kriterien - Ende</p></p>

**Welche Spalten anzeigen?**

Verwenden Sie folgende Codes, alle mit Kommata getrennt:<p><ul><li><strong>PLAYED</strong>: gespielte Spiele</li><li><strong>WINS</strong>: Siege</li><li><strong>TIES</strong>: Unentschieden</li><li><strong>LOSSES</strong>: Niederlagen</li><li><strong>WOT</strong>: Gewonnen nach Verlängerung</li><li><strong>WSO</strong>: Gewonnen nach Shoot-Out</li><li><strong>LOT</strong>: Verloren nach Verlängerung</li><li><strong>LSO</strong>: Verloren nach Shoot-Out</li><li><strong>SCOREFOR</strong>: Tore</li><li><strong>SCOREAGAINST</strong>: Gegentore</li><li><strong>SCOREDIFF</strong>: Tordifferenz</li><li><strong>SCOREPCT</strong>: Prozent Tore pro Spiel</li><li><strong>SCOREAVG</strong>: Durchschnitt geschossener Tore</li><li><strong>BONUS</strong>: Bonuspunkte</li><li><strong>WINPCT</strong>: Gewonnen in %</li><li><strong>GB</strong>: gameback</li><li><strong>LEGS</strong>: Legs</li><li><strong>LEGSDIFF</strong>: Legs Differenz</li><li><strong>LEGSRATIO</strong>: Legs Durchschnitt</li><li><strong>NEGPOINTS</strong>: Minuspunkte</li><li><strong>PENALTYPOINTS</strong>: Punkte nach Penaltyentscheidung</li><li><strong>OLDNEGPOINTS</strong>: Alte Darstellung der negativen Punkte</li><li><strong>POINTS_RATIO</strong>: Durchschnitt Punkte</li><li><strong>TADMIN</strong>: Team Administrator</li><li><strong>GFA</strong>: Durchschnittlich erzielte Tore pro Spiel</li><li><strong>GAA</strong>: Durchschnittlich erhaltene Tore pro Spiel</li><li><strong>PPG</strong>: Punkte pro Spiel</li><li><strong>PPP</strong>: Prozentpunkte in der Relation zur max. Punktezahl</li><li><strong>LASTGAMES</strong>: Letzte Spiele</li><li><strong>QUOT</strong>: Quotientenregel</li></ul></p>

Alle Spaltenkriterien - Ende</p>

Unter Joomla 3 wurde dies alles angezeigt. (hat mir und @diddipoeler viele Nächte gekostet)

Dieses Service gab es unter JL nicht. Bei uns soll alles selbstverständlich sein. Und das auch noch kostenlos.

**Comment by sigal** [comment]
Man wird irre bei so vielen falsch vermuteten nicht zutreffenden Bemerkungen. Fakt bei den Negativpunkten ist, dass dies so gezählt wird: 2 Punkte Regelung 2/1/0.
Bei 30 Spielen sind gesamt 60 Punkte zu vergeben.
Bei einer Mannschaft die 20 Spiele gewinnt, 8 Unentschieden und 2 verlorenen Spielen hat schaut es so aus (20 * 2) + (8*1) sind 48 +Punkte.
Negative Punkte ergeben sich aus (2*2) + (8*1) sind 12 Punkte Also ergibt sich daraus 48:12 === Gesamt wieder 60 Punkte.
Wer es noch immer nicht versteht - Auch bei Unentschieden verliert man einen Punkt - aber man gewinnt auch einen. (Bei 3 Punkte Regelung 3/1/0 verliert man 2 Punkte)

Ein Pull request folgt.

**Comment by waiter1987** [comment]
@sigal 
Vielen Dank für die Auflistung. Das fehlte leider bislang im Wiki ;-) Sonst wäre das ein oder andere wahrscheinlich schon selbsterklärend gewesen.

Das mit den Punkten ist sehr gut erklärt und mir zumindest mehr als logisch (vorher schon). Hier lag ja am Anfang das Problem vor, dass es viel mehr als die 60 Punkte waren. Das ist ja nun vorerst behoben. Ich gehe davon aus, dass der Pull Request dann so erfolgt, dass dann die korrekte Darstellung in den Projekteinstellungen 2,1,0 sein wird, oder? Damit wäre das sehr einheitlich.

Was das Thema "Dieses Service gab es unter JL nicht. " ... das stimmt so leider nicht. Diese Auflistung gab es per "Mouse-Over", wenn man auf den Namen "Sortierung der Kriterien" ging. Es spielt aber auch keine Rolle jetzt. Danke fürs Auflistung und übernehmen ins Wiki. 👍👍👍👍

**Comment by sigal** [comment]
Bitte ein Update der Komponente machen

**Comment by waiter1987** [comment]
passt. Ich schließe das Issue
DANKE
