### ISSUE TITLE
Statistiken werden nicht gespeichert

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1683]
Ich habe beim Torhüter 2 Statistiken

Gegentore bzw. "weiße Weste"

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/962eaff7-b808-43cb-85be-22d5bd365605)
Wenn ich hier was eintrage (so wie im Bild) und dann speichere, wird nichts gespeichert! 

Das wäre ja dann hier zu sehen (letztes Spiel!)
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/960cbb2d-781e-4e5f-8c01-47814f124ce8)

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/848aa2c2-e764-4c01-9eaf-02910e1a7101)

**Comment by ortwin20000** [comment]
Ich habe das jetzt bei mir versucht und du musst beim jeweiligen Spieler auch die Checkbox aktivieren. Erst danach werden die Änderungen auch gespeichert.

**Comment by waiter1987** [comment]
okay... den hab ich jetzt das erste mal gesehen... 🙈🙈

Ich kann die Statistik nicht als Menüpunkt auswählen 
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/a1e9daa9-e61f-4627-a238-c86e503c2882)

Da wird nichts angezeigt...

**Comment by waiter1987** [comment]
Statistiken werden gespeichert. Vielen Dank.

Einzig das mit dem Menüpunkt ist noch offen.

**Comment by ortwin20000** [comment]
Wegen dem Menüpunkt:
In der Definition für das Feld hat sich ein Tippfehler eingeschlichten:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/d1680064-9f8a-4388-8c20-0ad6708b289b)

Der Task müsste aber "projectstatsoptions" lauten:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/00c9cfb2-6757-40a4-8288-b9037c686a26)

Zusätzlich noch eine Anpassung in der ajax.php:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/bb16bee5-1a32-4ed2-8934-a267ce1ebca1)

und in der dependsql.php:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/1e95b206-a1cc-469d-a133-c5b8c49ac4ed)

Damit kann ich nun die Statistik im Menüpunkt auswählen:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/eaecb3fb-19d5-4bc9-9fbf-f5f65c6f66a2)

**Comment by diddipoeler** [comment]
Gibt es dazu einen Pull Request ?

**Comment by ortwin20000** [comment]
Hab die Statistik jetzt auch richtig gestellt. Jetzt werden diese auch im Frontend ausgegeben und auch der Titel sieht jetzt richtig aus.
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/90d3209e-1c80-4b97-ad36-a922d0103c21)

Nach dem Merge bitte noch einmal testen.

**Comment by waiter1987** [comment]
> Mehrfache Auswahl von Statistiken habe ich jetzt auch hinzugefügt ![image](https://private-user-images.githubusercontent.com/15192502/308843309-b082e40f-7142-45c8-880e-8a94dd3ada89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMzY3NzUsIm5iZiI6MTcwOTIzNjQ3NSwicGF0aCI6Ii8xNTE5MjUwMi8zMDg4NDMzMDktYjA4MmU0MGYtNzE0Mi00NWM4LTg4MGUtOGE5NGRkM2FkYTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE5NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYjU4M2Q0NWRhNWU1ZTJhMTA2MDBmZTBjN2FkOTQ1NzY5NzQ1ODcxOTQxZGQ2N2NhM2I2MjIwZDNhZjE5NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QvIgy2ujYZUjONUBv1_j9R7ewRk5MgbTber4aX6hvx4)
> 
> ![image](https://private-user-images.githubusercontent.com/15192502/308843343-1dbcc1a3-c86e-4963-8372-56ce900748b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMzY3NzUsIm5iZiI6MTcwOTIzNjQ3NSwicGF0aCI6Ii8xNTE5MjUwMi8zMDg4NDMzNDMtMWRiY2MxYTMtYzg2ZS00OTYzLTgzNzItNTZjZTkwMDc0OGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE5NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYWI0ZDdiZDg3OTFjMWYyODE1OWUzOTFhYTdlYjc1NDBhZGM2NTkwOWMwNjJkYWJmNzc5NDdhYzgxNzUzMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.URjBBK-8M8812kET4xdMMBMO1yPsDnP-T-WiY3hpdpw)

Die Ergebnisse in der Ausgabe stimmt nicht. Pepe Reina bspw. hat in der Saison 2014/2015 bei Bayern München gespielt. Hier ist die Einstellung auf der aktuellen Saison

**Comment by ortwin20000** [comment]
So besser?
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/12f9f1ab-b2c8-4fce-94fc-112420789dca)

Ich hätte ein zusäztliches Join auf die Projektabelle hinzugefügt und deine Where-Bedingung zwischen Projekt und Season_Team_Person_Id über die season_id.
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/2f9fef4d-95f5-459b-8601-7fc4452ed734)

**Comment by ortwin20000** [comment]
Musste einen anderen Weg gehen da mit dieser Abfrage noch andere Projekte der gleichen Saison berücksichtigt wurden:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/1cd97e87-3fc3-40ee-be94-6cd2a9f4e7dd)

Die Änderungen musste ich an mehreren Stellen durchführen aber so sollte es passen:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/104af243-7033-43aa-9317-8e0398af6525)

In der Spielerinfo wurde auch die Gesamtsumme deswegen noch falsch berechnet:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/c1606193-15a8-45af-86a1-b9ee520a8c52)

und auch in der persönlichen Statistik:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/2c88917d-4e9a-4547-8554-eb7d010c8ff2)
