### ISSUE TITLE
Teaminfo zeigt falschen Tabellenplatz 

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1687]
In der Teaminfo wird der falsche Tabellenplatz angezeigt. 

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/0e07bdd1-52d9-4b76-9b55-45f2dd38c2ca)
Hier wird TabPlatz 63 von 64 Mannschaften angezeigt

Tatsächlich ist es TabPlatz 2. 

PullRequest kommt von @ortwin20000

**Comment by ortwin20000** [comment]
Ich konnte es lösen indem ich in der ranking.php die Funktion _cmpfinaltablerank abgeändert habe.
In meiner Entwicklungsumgebung gab es bei der uasort()-Methode immer eine Deprecated-Warnung.
Deswegen habe ich versucht dies zu beheben und konnte damit auch gleich die Platzierung in der TeamInfo richtig stellen.

@diddipoeler
Ich hätte dies im [PHP Online Editor](https://3v4l.org/7RQv7) für PHP7 und PHP8 überprüft.

Vorher war die Platzierung so:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/d1bc93d1-4b06-4218-a4b8-4977989ab956)

Nach der Anpassung:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/bd67cc2b-babc-4a71-a924-6ef9d01835e0)

Ich mache dazu dann einen Pull-Request.

**Comment by ortwin20000** [comment]
Bitte nach einem Update noch einmal testen.

**Comment by waiter1987** [comment]
Nach Update richtiger Tabellenplatz, ABER:
die Tabelle dahinter hat einen Fehler

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/b363019e-5b25-4d12-aa59-09c2beb501ca)

Es wird die richtige Anzahl an Spiele ausgeben. Am Beispiel von Bayer Leverkusen 3 Spielen. Das dahinter haut nicht hin!
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/c0520998-59f2-4826-ba59-bcd7d92370ba)

In dem Fall wäre richtig 
3 Spiele
2 Siege
1 Niederlage

Die Punkte und die Tordifferenz usw. stimmt alles wieder.

Das wird auch in der Teaminfo falsch angzeigt.

**Comment by sigal** [comment]
Ergebnisse von Verlängerung und Elfmeterschießen werden nicht mit gezählt (in der Tabelle S/N) Unentschieden gibt es ja nicht im Pokal...

**Comment by waiter1987** [comment]
Aber ist nicht auch ein Sieg bzw. eine Niederlage nach Verlängerung und Elfmeterschießen ein Sieg bzw. eine Niederlage? 🤷‍♂️

**Comment by sigal** [comment]
> Aber ist nicht auch ein Sieg bzw. eine Niederlage nach Verlängerung und Elfmeterschießen ein Sieg bzw. eine Niederlage? 🤷‍♂️

Ja!
Aber das Programm zählt nicht!

**Comment by waiter1987** [comment]
Müsste aber gezählt werden...

**Comment by diddipoeler** [comment]
Jetzt wird immer gleich sortiert. Saison und dann Projektname.
Bitte noch einmal testen.
