### ISSUE TITLE
Teaminfo Anzahl Spieler zeigt komplett Kadergröße (inkl. Mannschafts- und Vereinsbetreuer!)

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1693]
In der Teaminfo wird oben in der Spalte "Spieler" angegeben. Ausgewiesen werden aber ALLE dem Team hinterlegten Personen.

Das verfälscht die Summe aber auch das Alter (ist dann nicht das Alter der Mannschaft, sondern des kompletten Kaders).

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/b6947f90-41e0-4d97-96d5-d291a42dde91)

Entweder müsste hier oben aus Spieler das Wort in "Kader" getauscht werden oder aber das Ergebnis dürfte nur auf Spieler (Personentyp) angewandt werden. Variante 2 halte ich für sinnvoller!

**Comment by ortwin20000** [comment]
Ich würde hier auch die Filterung auf Persontyp == 1 setzen. Falls wirklich auch der Betreuerstab als Info benötigt wird, sollten wir eine eigene Spalte dafür verwenden.

**Comment by ortwin20000** [comment]
Ich habe das jetzt gefiltert auf Spieler und einen Pull-Request erstellt.

Nur ist mir jetzt aufgefallen, dass es einen Schönheitsfehler gibt. Um so älter die Projekte sind umso älter sind natürlich jetzt auch die Spieler und das Durchschnittsalter geht entsprechend in die Höhe.

![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/71f70fd3-e290-4df0-991f-e30a1a7c59a8)

**Comment by waiter1987** [comment]
Darüber habe ich auch schon nachgedacht. Aber dann wäre die Frage, an was man das sonst fest machen will, als am aktuellen Datum 🤷‍♂️ Wäre ja maximal ein Stichtag dafür extra zu kreieren. Laufende Saison nach dem aktuellen Datum, alles davor nach einem noch zu definierenden Feld... Da kann dann bspw. 30.06. des Jahres stehen...

**Comment by waiter1987** [comment]
Das Ursprungsthema ist behoben. DANKE

Mir ist nur aufgefallen, dass es Projekte gibt, wo die Anzahl der Spieler auf 0 steht.
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/cecdb943-a118-429f-a15c-fd7f4e58638c)
Beispiel Champions League 22/23

Das sieht im Backend anders aus
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/b81f4d3a-b800-4a8e-b8f2-6e80899e7c28)

**Comment by ortwin20000** [comment]
Ich hätte jetzt mal versucht das Alter entsprechend dem letzten Spieltag im Projekt zu berechnen. Schaut eigentlich ganz gut aus aber bei manchen deiner Projekte ist kein Spieltag und auch kein Projektstart definiert. Dort kann er somit das Alter nicht richtig berechnen und macht die alte Logik.
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/bab2cb23-62be-4256-81a1-55edeb2f9951)

**Comment by waiter1987** [comment]
Mir i

> Ich hätte jetzt mal versucht das Alter entsprechend dem letzten Spieltag im Projekt zu berechnen. Schaut eigentlich ganz gut aus aber bei manchen deiner Projekte ist kein Spieltag und auch kein Projektstart definiert. Dort kann er somit das Alter nicht richtig berechnen und macht die alte Logik. ![image](https://private-user-images.githubusercontent.com/15192502/308170943-bab2cb23-62be-4256-81a1-55edeb2f9951.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDk2MzksIm5iZiI6MTcwOTA0OTMzOSwicGF0aCI6Ii8xNTE5MjUwMi8zMDgxNzA5NDMtYmFiMmNiMjMtNjJiZS00MjU2LTgxYTEtNTVlZGViMmY5OTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE1NTUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkOTFlYjdmYTczZjY1ZThlYjEzMTY5M2JkOGQyMjNjNWVhYmZkMGMyMTQyNjgxNzdiNDcxMDhmYmEwYWZlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iCgQ7JRH_qTgxlQ1Aqp4hfj2H7KXRniP5BFJmtOXM8g)

Bei der Champions- und Europa-League muss die Gruppenzuordnung im Spieltag gemacht werden. Dann rechnet das auch...

**Comment by waiter1987** [comment]
Perfekt... Vielen Dank.
