### ISSUE TITLE
Tabelle - vorheriger Tabellenplatz wird nicht angezeigt bei früheren Spieltagen

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1694]
Wenn man nicht im aktuellen Spieltag ist, wird der vorherige Spieltag in der Tabelle nicht angezeigt!

Beispiel 1. BL 23/24 2. Spieltag.

JSM:
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/c21bac34-f482-4035-8aed-ed149c01371b)

Transfermarkt:
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/0c3497fd-c747-4934-bf51-7b71eb66f757)

**Comment by ortwin20000** [comment]
@waiter1987 
Kannst du diese Codeänderung bei dir auch testen? 
Bei mir wird der vorige Tabellenplatz nun korrekt ausgegeben.

**Comment by sigal** [comment]
@waiter1987 Wäre schön, wenn es auch eine Rückantwort gibt!

**Comment by waiter1987** [comment]
Sorry, hatte ich übersehen. Sieht jetzt gut aus. DANKE
