### ISSUE TITLE
Ewige Tabelle - unterschiedliche Mannschaften in der Historie

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1700]
Folgende Tatsache

Es gibt einen Verein "Krefelder Fußballclub Uerdingen 05 e.V.".

Gegründet 1905. Die Fußballmannschaft von dem Verein im Zeitraum 1953-1995 hatte den Namen FC Bayer 05 Uerdingen. Hintergrund für die Namensgebung war klassisches Sponsoring der Bayer AG. Für viele bis hier alles geläufige Geschichte.

Jetzt aber kommt für mich die Herausforderung. Um das Ganze richtig darstellen zu können habe ich dem Verein 2 Mannschaften zugewiesen. 1x Bayer 05 Uerdingen und einmal KFC Uerdingen. KFC Uerdingen war in der Saion 1995/1996 in der Bundesliga aktiv, hat für die Ewige Tabelle also 34 Spiele. Bayer 05 Uerdingen hat insgesam 442 Bundesligaspiele. 

In der Ewige Tabelle stehen ergo jetzt 2 x Teams von Uerdingen, die aber zusammengerechnet werden müssten. 

Analog den Teams wie bspw. MSV Duisburg bzw. Meidricher SV. 

Wie kann man das lösen? Wenn ich lösungsorientiert denke, dann wäre eine Namenseditierung pro Saison/Projekt wahrscheinlich die sinnigste Lösung. Somit bleibt 1 Mannschaft pro Verein, die dann namentlich angepasst werden kann. Geht das schon oder ist das eher ein Thema Wishlist? 

Bei Diddi sind bei den Mannschaften die Vereinsnamen angelegt. 
https://fussballineuropa.de/index.php/component/sportsmanagement/rankingalltime/0/2/3,1,0/0/0/0/0/134895:1-bundesliga-2023-24?Itemid=-1

**Comment by sigal** [comment]
Auch [hier](https://www.weltfussball.at/ewige_tabelle/bundesliga/) wird wie bei @diddipoeler gezählt. 
[Kicker.de](https://www.kicker.at/bundesliga/ewige-tabelle)
[Wikipedia](https://de.wikipedia.org/wiki/Ewige_Tabelle_der_Fu%C3%9Fball-Bundesliga)
Wir wollen ja nicht das Rad neu erfinden, oder irre ich mich.
Weiters ist es irrelevant, welcher Klub welche Sponsoren hat. Und ja, die Mannschaften sollten der Form halber die Namen der Klubs haben.

**Comment by waiter1987** [comment]
> Auch [hier](https://www.weltfussball.at/ewige_tabelle/bundesliga/) wird wie bei @diddipoeler gezählt. [Kicker.de](https://www.kicker.at/bundesliga/ewige-tabelle) [Wikipedia](https://de.wikipedia.org/wiki/Ewige_Tabelle_der_Fu%C3%9Fball-Bundesliga) Wir wollen ja nicht das Rad neu erfinden, oder irre ich mich. Weiters ist es irrelevant, welcher Klub welche Sponsoren hat. Und ja, die Mannschaften sollten der Form halber die Namen der Klubs haben.

Ich wiederspreche ungern. Muss das aber leider tun. Wenn man in die jeweiligen Saisons geht, egal ob nun bei Wikipedia oder Kicker steht der "alte" Name --> 
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/d761b200-c830-456a-bfe8-236ed87dc9f7)

https://de.wikipedia.org/wiki/Fu%C3%9Fball-Bundesliga_1963/64#Abschlusstabelle

Das wird dann aber in der Ewigen Tabelle dem jeweils aktuellen Namen angepasst. 

M.E. wäre es analog der Thematik mit den alten Logos pro Saison/Projekt die Anpassung des jeweiligen Mannschaftsnamens. Das ist in keinster Weise die Neuerfindung des Rades, sondern schlichtweg geschuldet der Namensänderung von Mannschaften. Ist ja auch in anderen Ländern... 
FC Parma - AC Parma usw. --> Alles eine Mannschaft mit z.T. unterschiedlichen Stammvereinen... 🤷‍♂️🤷‍♂️

Das mit dem "Sponsor" ist einzig ein Thema von Uerdingen. 

Und man sieht ja weder bei Kicker noch bei Wiki oder sonst wo bei den Mannschaften den Vereinsnamen ;-) 
Siehe Dortmund
Borussia Dortmund  - Team
Ballspielverein Borussia 09 e.V. Dortmund - Verein

**Comment by sigal** [comment]
Ich krieg die Krise

**Comment by ortwin20000** [comment]
> Wie kann man das lösen? Wenn ich lösungsorientiert denke, dann wäre eine Namenseditierung pro Saison/Projekt wahrscheinlich die sinnigste Lösung. Somit bleibt 1 Mannschaft pro Verein, die dann namentlich angepasst werden kann. Geht das schon oder ist das eher ein Thema Wishlist?

Grundsätzlich sollte das ja unkompliziert umsetzbar sein. In den Projektmannschaften ein neues Feld für den Namen wie es auch bei den Bildern ja schon möglich ist eigene Bilder pro Spieler oder Mannschaft zu hinterlegen. In der Logik müsste dann geprüft werden ob das Feld befüllt ist und falls ja dann diesen Namen in dem Projekt verwenden, ansonsten eben wie bisher. Bei der Ewigen Tabelle bleibt dann wie bisher der Mannschaftsname und somit die gewünschte Funktion umgesetzt. Wäre das so denkbar oder übersehe ich hier etwas?

@sigal Warum ist das ein Problem solch eine Funktion zu unterstützen?

**Comment by diddipoeler** [comment]
Werde mir das in Ruhe erst einmal anschauen.

**Comment by diddipoeler** [comment]
Ich glaube ich habe eine Lösung!

**Comment by waiter1987** [comment]
das wäre super... wie sieht deine Lösung aus?

**Comment by waiter1987** [comment]
Das ist gefixt... man kann da, wo man die Saison auswählt, auch den Teamnamen in der Saison anpassen! DANKE
