### ISSUE TITLE
Schiedsrichteranzeige verursacht fehlerhafte DB-Aufrufe im Model

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1703]
Wenn ich von einem Spielbericht die Daten des Schiedsrichters anzeigen möchte erhalte ich eine Fehlermeldung:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/63743cd8-3ab7-462e-b778-55b824120fd8)

![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/6db852dd-19cb-4961-b2c9-61c3d1c318b2)

Ursache ist das von der View Referee das Model für Referee geladen ist und darin die Funktion getReferee im Person-Model aufgerufen wird. Dort wird aber das "_construct" nicht aufgerufen und somit die self::db und self::query nicht initialisiert wie wenn ich das Model von der Spieleransicht verwende.

@diddipoeler 
Das Person-Model ist das einzige im System wo einige Abfragen mit self::query durchgeführt werden. Ist das noch etwas Altes oder sollte hier die Logik für die DB-Verbindung zusammengefasst werden?

Wenn ich den Code so wie bei den anderen Stellen auf eigene Variablen umbaue funktioniert es natürlich aber ich würde gerne vorher wissen was es damit auf sich hat bevor ich hier Änderungen vornehme.

**Comment by diddipoeler** [comment]
Können wir das jetzt schließen?
