### ISSUE TITLE
Keine Bearbeitung der Ergebnisse im Frontend mehr möglich.

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#1706]
Nach Update auf Sportmanagement 4.18 und Joomla 4.3.4 auf 4.4.2 / 5.0.2 keine Bearbeitung der Ergebnisse im Frontend mehr möglich.

![2024-01-29_16h57_45](https://github.com/diddipoeler/sportsmanagement/assets/5115688/2bf0e237-cdfe-49f3-bce1-ee97dfe29257)

Übernommen vom [Forum](https://www.fussballineuropa.de/index.php/kunena/7-bugreport/4872-keine-ergebiseingabe-im-frontend)

**Comment by ortwin20000** [comment]
Dies liegt an den beiden [Commits](https://github.com/diddipoeler/sportsmanagement/commits/master/site/models/results.php) von @diddipoeler am 13. Dezember wo er die Logik für die Datensätze umgestellt hat.

Dabei wurde aber die Logik von der Funktion getData() vergessen wo die einzelnen Spiele überprüft werden ob der angemeldete Benutzer auch die Berechtigung zum Bearbeiten besitzt.
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/9da6bb0b-dcc4-464a-aab6-e319bcee671b)

Wenn ich den Code wieder ändere auf
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/447c101f-7151-48c3-922c-7651638cedb8)
werden mir die Spiele wieder angezeigt.

**Comment by diddipoeler** [comment]
Sorry.
Bitte noch einmal testen.

**Comment by boxr** [comment]
Super, Funktioniert wieder. Besten Dank :-)
