### ISSUE TITLE
Ewiger Kader keine Einträge

### ISSUE THREAD

**Issue by ortwin20000** [diddipoeler/sportsmanagement#1710]
Wenn ich den Ewigen Kader aufrufe werden mir keine Einträge angezeigt:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/b01ff170-ba2e-437a-8352-4077ff0a2d62)

Dies liegt an dieser Abfrage:
```
function getPlayerPosition()
{
    $this->jsmquery->clear();
    $this->jsmquery->select('po.*');
    $this->jsmquery->from('#__sportsmanagement_position as po');
    $this->jsmquery->where('po.parent_id != 0 ');
    $this->jsmquery->where('po.persontype = 1 ');
```

Wenn ich den Code so abändere:
```
function getPlayerPosition()
{
    $this->jsmquery->clear();
    $this->jsmquery->select('po.*');
    $this->jsmquery->from('#__sportsmanagement_position as po');
    $this->jsmquery->where('po.parent_id = 0 ');
    $this->jsmquery->where('po.persontype = 1 ');
```
werden mir die Einträge angezeigt:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/1e4c3e91-bd4b-4bee-b4d7-b18b17c6fedd)

Ist das ein Fehler von der Abfrage oder in den Einstellungen der Positionen falsch konfiguriert?

**Comment by diddipoeler** [comment]
Gibt es dazu noch einen Pull Request ?

**Comment by ortwin20000** [comment]
Wenn es ein Fehler ist mache ich einen Pull-Request dazu. Komme aber erst nächste Woche dazu. Bin auf der U14 Staatsmeisterschaft Faustball dieses Wochenende.

**Comment by ortwin20000** [comment]
Ich habe hierzu jetzt einen Pull-Request mit meiner vorher erwähnten Code-Änderung erstellt.

**Comment by waiter1987** [comment]
Das wird mittlerweile angezeigt, einzig das Blättern geht nicht - zumindest bei mir nicht
