### ISSUE TITLE
Entscheidung nach Spielende wird nicht gespeichert

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1714]
Ich habe in der Historie gestern ein Spiel gehabt, welches mit 2:0 gewertet wurde. Dies wird nicht gespeichert.

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/add763c0-d70b-4657-ab2b-5fc844a5bf87)
So sieht das nach dem Speichern aus!

Warum steht da 2x "Neuer Spielstand"?

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/02910362-9c80-44a8-95f8-850de31e8e62)
Betrifft in dem Beispiel Bayer 05 Krefeld - Eintracht Frankfurt des 32. Spieltages der Saison 1992/1993.

Bei Diddi auf der Seite sieht das auch so aus, als ob hier einfach das Endergebnis der Wertung gesetzt wurde:
https://fussballineuropa.de/index.php/component/sportsmanagement/matchreport/0/0/41:1-bundesliga-1992-93/21962:krefelder-fussball-club-uerdingen-05_sg-eintracht-frankfurt?Itemid=-1

**Comment by ortwin20000** [comment]
@waiter1987 
Warum steht da 2x "Neuer Spielstand"?
Das ist einmal das Ergebnis für Mannschaft A und einmal das Ergebnis für Mannschaft B.
Das Speichern sollte mit den Codeänderungen nun auch möglich sein.
Bitte mal testen.
