### ISSUE TITLE
Ewige Tabelle - Minuspunkte werden nicht berücksichtigt

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1715]
Es gab in der Vergangenheit immer mal Mannschaften, die aus versch. Gründen mit Minuspunkten bedacht wurden. Dies ist in jeder Ewigen Tabelle auch berücksichtigt, wird nur bei JSM bisher nicht verarbeitet.

Am Beispiel Dynamo Dresden. 

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/9dd94d05-a77c-491b-9594-7b52396d9da3)

33 Siege á 3 Punkte
= 99 Punkte
45 Unentschieden á 1 Punkt 
= 45 Punkte
Gesamtpunkte 144

In der Saison 93/94 wurden 4 Punkte abgezogen:
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/9a10cf63-2e3c-48ab-8803-ff5d5aec8af0)

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/ee337ad6-fb49-45e5-9a14-d13240e8e689)
https://de.wikipedia.org/wiki/Ewige_Tabelle_der_Fu%C3%9Fball-Bundesliga

**Comment by diddipoeler** [comment]
Wir sollten hier das Scheuklappendenken zur Seite legen und nicht nur immer an Fußball denken.
JSM ist nicht nur für Fußball gedacht.
Wie sieht es denn im Handball, Volleyball oder Basketball aus?
Ansonsten muss man noch eine Funktionalität einbauen die abfragt, ob nur die Spiele berücksichtigt werden sollen oder/und
auch die Minus- und Pluspunkte.

**Comment by waiter1987** [comment]
So ein Punktabzug kann doch auch in anderen Sportarten kommen... 🤷‍♂️

Daher wäre eine Abfrage/Funktionalität sehr sinnvoll. Es gibt im Projekte ja die Funktion. Die wird halt nur bei der Abfrage der Ewigen Tabelle nicht berücksichtigt.

**Comment by diddipoeler** [comment]
Bitte einmal testen.

**Comment by waiter1987** [comment]
Nach Update leider noch keine Berücksichtigung

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/91687d70-c517-49eb-98d3-c9a6cbbe81ff)


Dynamo Dresden hat nen Abzug von -4. Ergo müsste 140 Pkt da stehen. 

Siehe Kicker:
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/88933993-e5da-4257-9b27-584c0e3c0cce)

**Comment by diddipoeler** [comment]
Bei mir sieht es richtig aus:
https://www.fussballineuropa.de/index.php/component/sportsmanagement/rankingalltime/0/2/3,1,0/0/0/0/0/134895:1-bundesliga-2023-24?Itemid=-1
Wie wird die ewige Tabelle aufgerufen?
Menüeintrag oder JSM Ajax Menü ?

**Comment by waiter1987** [comment]
über das Menü... JSM Ajax Manü bekomm ich nicht zum laufen --> https://github.com/diddipoeler/sportsmanagement/issues/1675

**Comment by waiter1987** [comment]
https://sport.daniel-frase.de/index.php?option=com_sportsmanagement&view=rankingalltime&l=453&points=3,1,0&Itemid=110

**Comment by sigal** [comment]
Template **rankingalltime**  **[ Ewige Tabelle Anzeige ]** einstellen.

![2024-04-01 13_59_49-Sports Management_ Template   Ewige Tabelle Anzeige   bearbeiten - JSM - Demo Si](https://github.com/diddipoeler/sportsmanagement/assets/5115688/3a30996b-68e8-4ced-ad1f-e920e2e77a6d)

**Comment by waiter1987** [comment]
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/2833a7b1-9647-4352-8e50-643778132399)
Habe das in dem Projekt so gepflegt. Müsste doch passen, oder?

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/5ab6c7e8-3b3a-4542-bc9d-71dccc37bf0e)
Das hab ich eingestellt

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/5ebadce0-11f1-474c-9cf9-7fb9e1469078)
immer noch 144 Punkte.... 

:-( 

Muss in dem Menüpunkt noch was angepasst werden?

**Comment by sigal** [comment]
Bitte ein Update der Komponente machen.
Dann die **Menüs** mit **Ewiger Tabelle** nochmals bearbeiten, notwendige Einstellungen vornehmen und wieder abspeichern.

**Comment by waiter1987** [comment]
PERFEKT! DANKE
