### ISSUE TITLE
Tabelle in Gruppenliga ohne Tabellen-Legende

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1722]
Wenn ich in einer Gruppenliga die Tabelle öffne, dann sind da die farblichen Legenden nicht hinterlegt. 

Hier am Bespiel zu sehen. Links das Plugin Ranking, rechts der Menüpunkt. 
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/4de3b3de-cc74-465b-be72-31c01c3f5d15)

**Comment by diddipoeler** [comment]
Die farbliche Legende wird bei einer Gruppenliga in der Gruppe zum Projekt hinterlegt.
