### ISSUE TITLE
Fehler in deutscher Sprachdatei

### ISSUE THREAD

**Issue by LordHelmchen666** [diddipoeler/sportsmanagement#1725]
JROOT/language/de-DE/de-DE.com_sportsmanagement.ini : error(s) in line(s) 1699
    JROOT/components/com_sportsmanagement/language/de-DE/de-DE.com_sportsmanagement.ini : error(s) in line(s) 1699

`COM_SPORTSMANAGEMENT_OSM_COUNTY=Landkreis oder Stadtkreis"`

Da fehlt ein "

**Comment by sigal** [comment]
Dazu gibt es seit ein paar Stunden einen PR.
Muss von @diddipoeler  noch übernommen werden.

**Comment by sigal** [comment]
Bitte nochmals testen

**Comment by LordHelmchen666** [comment]
Passt. Geht wieder einwandfrei.
