### ISSUE TITLE
Date format / Player match-history view

### ISSUE THREAD

**Issue by Tanoke** [diddipoeler/sportsmanagement#1728]
I can't get the date setting to work on the player's matches in the player screen. Changing the setting does not change the date format. Or will that change be made from somewhere else?

![player-template](https://github.com/diddipoeler/sportsmanagement/assets/111390359/540e0e38-8c6f-48cc-a70f-3a136bce1857)

**Comment by diddipoeler** [comment]
Bitte ein Update machen und danach noch einmal testen.

**Comment by Tanoke** [comment]
I tested it and it works as it should. Thank you!

**Comment by diddipoeler** [comment]
Auf welcher Homepage wird die Komponente denn eingesetzt?

**Comment by Tanoke** [comment]
https://www.rops.fi/

**Comment by diddipoeler** [comment]
Ich hoffe, dass die Komponente genau das ist, was du gesucht hast, um die Spiele
und alles andere auf der Homepage zu präsentieren.
Wenn du noch Daten zu deinem Verein ROPS suchst, kannst du vielleicht hier nachschauen:
https://www.fussballineuropa.de/index.php/component/sportsmanagement/teaminfo/0/0/137181:kakkonen-finnland-2023/3640:rovaniemi-ps/2066056?Itemid=-1
