### ISSUE TITLE
Nach Update kein Zugriff auf Ergebnis-Tabelle

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1731]
Nach dem Update habe ich wieder einen Fehler in der Ergebnis-Tabelle

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/1103d633-2e41-4839-b9d3-2df581ddae33)
https://sport.daniel-frase.de/index.php?option=com_sportsmanagement&view=resultsranking&cfg_which_database=0&s=399:2023-2024&p=4617:1-bundesliga-2023-2024&r=36990:spieltag-26&Itemid=114

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by waiter1987** [comment]
Update gemacht, leider noch immer so :-(

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
