### ISSUE TITLE
Missing strings in language file

### ISSUE THREAD

**Issue by Tanoke** [diddipoeler/sportsmanagement#1735]
On the project editing page, under Favorite team, the language file is missing the strings where I would specify the Finnish translation. Attached is a picture that shows the matter.

![Screenshot](https://github.com/diddipoeler/sportsmanagement/assets/111390359/039c4e5e-6c6f-4587-8d31-0b20eff89865)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Tanoke** [comment]
Works fine! The strings has now been translated into Finnish. Thank you!

**Comment by diddipoeler** [comment]
I would be happy if you would leave a review here.
https://extensions.joomla.org/extension/sports-management/

**Comment by Tanoke** [comment]
> I would be happy if you would leave a review here. https://extensions.joomla.org/extension/sports-management/

Done

**Comment by diddipoeler** [comment]
Besten Dank.
