### ISSUE TITLE
Fehler bei Clubeditierung 

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1738]
Ich möchte meine Clubs aktualisieren. Ein Großteil der Clubs geht, aber bspw. Hertha BSC geht nicht. Da kommt folgendes Fehlerbild:
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/65f8733b-92c2-4d1f-aff0-e3b8965822f3)

Ich finde leider den Fehler nicht, warum Hertha nicht geht und andere wiederum gehen. @ortwin20000 hat Zugriff auf die Daten

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by waiter1987** [comment]
ist leider immer noch so mit dem Fehler

**Comment by sigal** [comment]
Der Fehler erfolgt, da alte Einträge aus einer JL-1,5 Installation in der Datenbank existieren.
Konnte diesen Fehler nachstellen.
Tabelle_sportsmanagement_club: Suchen nach folgenden Einträgen....


![2024-04-23 16_44_29-server1 siegal at_8443 _ localhost _ siegal_j4demo _ z2o57_sportsmanagement_club](https://github.com/diddipoeler/sportsmanagement/assets/5115688/1588bc17-4665-4970-a44e-7e714001269e)


**Folgendes muss geschehen.**


![2024-04-23 16_48_10-server1 siegal at_8443 _ localhost _ siegal_j4demo _ z2o57_sportsmanagement_club](https://github.com/diddipoeler/sportsmanagement/assets/5115688/ea39cfc9-eda4-4b6e-9489-7bf84840da00)


Jetzt lässt sich der Vereinsname im BE von JSM bearbeiten und speichern.

Ergo kein JSM-Bug, sondern Anleitungen eines Upgrades von JL-1.5 auf JL-2.x nicht befolgt.

**Comment by waiter1987** [comment]
DANKE, auch wenn ich NIE auf JL 2.x war...
