### ISSUE TITLE
Wrong day in teamplan

### ISSUE THREAD

**Issue by Tanoke** [diddipoeler/sportsmanagement#1739]
The game dates and time are specified correctly in the match program. Image 1
<img width="1582" alt="1" src="https://github.com/diddipoeler/sportsmanagement/assets/111390359/8e2acf76-7430-4260-906e-7245c098484c">

The days is shown correctly in the results view. Image 2
<img width="932" alt="2" src="https://github.com/diddipoeler/sportsmanagement/assets/111390359/93038f2f-bb2a-49de-a53a-e9c31d537e28">

But the teamplan view for one match has the wrong day. The date shows the next day but the time is correct. Image 3.
<img width="932" alt="3" src="https://github.com/diddipoeler/sportsmanagement/assets/111390359/108a6da1-fb6e-4ce6-904e-4ab3f3c6d6ee">

The match is played at midnight, so could the reason be related to the time zone? The time zone is set to UTC+2.

Is there a bug?

I hope you understood what I meant above.

**Comment by Tanoke** [comment]
Well. I tested that problem even more closely. The server's time zone is UTC+2 and Joomla's time zone is also set to UTC+2. When I change Joomla's time zone to UTC+0 the date in teamplan shows correctly. That is, June 29, 2024 at 10 p.m. Other dates in teamplan are displayed correctly, the change had no effect, i.e. they are still displayed correctly.

I left Joomla's time zone setting UTF+0 in effect for the time being so that the date is displayed correctly to visitors. I hope there is a solution to this and I can restore the time zone setting to the correct one.

**Comment by ortwin20000** [comment]
I did a Pull-Request to fix this issue.
After the merge please try it again.

Same Test-Setup:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/0bf56b4c-d99b-47e1-aebe-be57bff0b1ce)

Before Code-Change:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/5e461548-ec4a-4ba9-ada3-5e7f57660fca)

After Code-Change:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/d95f5568-3387-4773-a428-ddb334103fec)

**Comment by sigal** [comment]
@Tanoke  - Was the problem resolved?

**Comment by Tanoke** [comment]
Yes, the problem is solved
