### ISSUE TITLE
Spielerinformation

### ISSUE THREAD

**Issue by oulxbie** [diddipoeler/sportsmanagement#1740]
Ich habe für Testzwecke "Niclas Füllkrug" in einem fiktiven Spiel gegen Schottland in der 38 Minute eine "Gelbe Karte" verpaßt
und in der 46 Minute ein "Tor" schießen lassen. Dann komme ich auf eine angezeigte Spielzeit von 6 Minuten. Es werden also von 
den 90 Minuten Spielzeit die 38+46 abgezogen. Wenn ich ihn dann noch in der 70 Minute auswechsle komme ich auf die angezeigten
26 Minuten.

<img width="444" alt="Füllkrug" src="https://github.com/diddipoeler/sportsmanagement/assets/130899448/3cbc5099-2bf5-4639-94fa-14dfe894ba25">

**Comment by svdoldie** [comment]
Hast du diese Einstellungen vorgenommen?
![Uploading Screenshot 2024-04-23 154734.png…]()

**Comment by svdoldie** [comment]
![Screenshot 2024-04-23 154734](https://github.com/diddipoeler/sportsmanagement/assets/2417767/a8fba63a-9dd5-4c33-8a40-f2123bf370c4)

**Comment by oulxbie** [comment]
Alles klar! Danke.
