### ISSUE TITLE
Tippspielerinformation

### ISSUE THREAD

**Issue by oulxbie** [diddipoeler/sportsmanagement#1741]
Hallo Community,
sollte hier nicht der Meistertipp angezeigt werden, wenn ausgewählt und in der eigenen Tippspielerinformation?

<img width="459" alt="Meistertipp" src="https://github.com/diddipoeler/sportsmanagement/assets/130899448/ca45e00d-87a5-4b33-b657-392acffe7415">

**Comment by ortwin20000** [comment]
Wenn ich es im Code richtig lese, wird der Meistertipp nicht mehr angezeigt wenn das aktuelle Datum später ist als das Projekt-Startdatum oder es sind keine Mannschaften im Tippspiel für den Meistertipp ausgewählt.

**Comment by oulxbie** [comment]
Trifft aber beides nicht zu.
![snipp7225](https://github.com/diddipoeler/sportsmanagement/assets/130899448/43e3977b-e86c-4f7f-bf71-eea38312fa66)

**Comment by ortwin20000** [comment]
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/413c1f22-ce42-4db3-90b0-78896a21ae4e)
Sollte man hier nicht mehrere Mannschaften zum Tippen auswählen können oder verstehe ich das System falsch?
Vielleicht kann mir das einer erklären wie ein Tippspiel erstellt wird.

Damit der Meistertipp auch in der Tippspieler-Ansicht dargestellt wird, muss die getippte Mannschaft auch in dem Tippspiel-Projekt ausgewählt sein.

**Comment by oulxbie** [comment]
Was ich dann hier machen kann.
![snipp7226](https://github.com/diddipoeler/sportsmanagement/assets/130899448/cda7493a-b2c8-4189-8e07-48166a297678)

**Comment by ortwin20000** [comment]
Tut mir leid. Ich komme nicht mal dazu einen Tippspieler zu erstellen. Da muss ich erst das Tippspiel korrekt einrichten und da scheitere ich derzeit daran.

Kannst du debuggen oder den Code lesen?
In der Datei components\com_sportsmanagement\views\predictionuser\tmpl\default_info.php werden die auszugebenden Daten erzeugt.
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/c4ccc682-3bef-49f5-8061-93f8b7bc01a2)

**Comment by ortwin20000** [comment]
Ich konnte jetzt ein Tippspiel einrichten.
Da das Projekt noch nicht gestartet ist, wird der Meistertipp auch nicht angezeigt. Anscheinend um andere Tippspieler nicht zu viel zu verraten ;-)

Erst wenn das Projekt gestartet ist, also zumindest das Startdatum des Projekts früher ist als der heutige Tag, wird der Meistertipp auch angezeigt.

![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/05838ecd-3685-426c-a67a-47809cc2eac5)

**Comment by oulxbie** [comment]
Das ist in soweit richtig, für die (für alle einsehbare) Rangliste, Sabine und Otmar z.B. haben schon einen Meistertipp abgegeben, welcher aber für mich nicht sichtbar ist. Aber in der eigenen "Mitgliederinformation" sollte mein Tipp für mich doch sichtbar sein.
![snap7225](https://github.com/diddipoeler/sportsmanagement/assets/130899448/4ddf37fc-dadf-42b2-8af4-505199aa2764)
![snap7226](https://github.com/diddipoeler/sportsmanagement/assets/130899448/61057e63-1fc1-450d-b2cb-6dd6b24516a1)

**Comment by oulxbie** [comment]
Was in soweit richtig ist (für die für alle einsehbare) Tipp-Rangliste. Sabine und Otmar haben z.B. schon einen Meistertipp abgegeben, welcher aber für mich nicht sichtbar ist.
<img width="187" alt="snap7225" src="https://github.com/diddipoeler/sportsmanagement/assets/130899448/8d3ca895-3c58-4da5-976d-1188c4856bd4">
Für mich sollte aber in meiner eigenen "Mitgliederinformatin" so wie ja auch in der "Rangliste" mein Tipp doch sichtbar sein, auch vor dem Projektstartdatum?
<img width="187" alt="snap7225" src="https://github.com/diddipoeler/sportsmanagement/assets/130899448/a006a75f-ba47-4afb-9945-863bac34c314">

**Comment by ortwin20000** [comment]
Du könntest mal folgende Code-Anpassung ausprobieren und dann Rückmeldung dazu geben ob das so passen würde. Dann könnte ich auch einen Pull-Request machen:
In der Datei components\com_sportsmanagement\views\predictionusers\tmpl\default_info.php die Zeile 255 so abändern:
`$showChamp                = ($thisTimeDate > $competitionStartTimeDate || $this->actJoomlaUser->id == $this->predictionMember->user_id);`

Damit sollte er prüfen ob der angemeldete Benutzer der gleiche ist wie der Tippspieler und den Meister-Tipp anzeigen.

**Comment by oulxbie** [comment]
Das sieht gut aus!
<img width="476" alt="snap7227" src="https://github.com/diddipoeler/sportsmanagement/assets/130899448/7f6790b1-6f6c-4204-ad7e-939d32106cab">

**Comment by ortwin20000** [comment]
@oulxbie Kann hier zugemacht werden oder ist noch was offen?
