### ISSUE TITLE
Joomla 5.1.0 - Fehler bei Projekt Speichern & Schließen

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#1742]
Joomla 5.1.0 | PHP Version 8.2.18

Dieser Fehler tritt erst seit Update auf Joomla 5.10 auf.

Projekt Speichern & Schließen

Fehler: **Incorrect date value: '3-15-4--20' for column `xxxxxxxxxxxxxx_sportsmanagement_project`.`start_date` at row 1**

![2024-04-25 13_23_22-Sports Management_ Projekt   AUT - BL Meistergruppe 2023_24   bearbeiten - ESV K](https://github.com/diddipoeler/sportsmanagement/assets/5115688/60be721f-3a63-4d91-aeca-4c7b0d29f4e0)

![2024-04-25 13_16_41-Sports Management_ Projekt   AUT - BL Meistergruppe 2023_24   bearbeiten - ESV K](https://github.com/diddipoeler/sportsmanagement/assets/5115688/92aff774-51aa-4a7f-b1bb-61b20360080a)

![2024-04-25 13_23_22-Sports Management_ Projekt   AUT - BL Meistergruppe 2023_24   bearbeiten - ESV K](https://github.com/diddipoeler/sportsmanagement/assets/5115688/deb96f31-255e-4369-83a0-7fd601044d8a)

**Comment by diddipoeler** [comment]
Ich mache mal eine Joomla 5 Seite um das zu testen.

**Comment by waiter1987** [comment]
Das habe ich heute auch gemerkt. Man muss ja bei jedem Spieler die neue Saison hinzufügen. Da wird dann das Geburtsdatum geändert und es geht nicht mehr zu speichern. @diddipoeler konntest du das schon mal testen?

**Comment by ortwin20000** [comment]
Es gibt hierfür einen [Fix](https://github.com/joomla/joomla-cms/commit/963f97dfe936382dbcdc93168504568203c5f735) der in der nächsten Joomla-Version drin ist.

Ich habe diesen bei mir ausprobiert und damit kann ich das Datum wieder speichern.

**Comment by ortwin20000** [comment]
Ich habe es heute mit Joomla 5.1.1 noch einmal probiert und auch da klappt es bei mir wieder so wie es soll.

**Comment by sigal** [comment]
Da kein JSM Fehler, schließe ich.
