### ISSUE TITLE
Tippspiele

### ISSUE THREAD

**Issue by boxr** [diddipoeler/sportsmanagement#1750]
Beim Versuch ein Tippspiel zu erstellen erhalte ich diese Fehlermeldung,

Too few arguments to function Joomla\CMS\MVC\View\AbstractView::setDocument(), 0 passed in /administrator/components/com_sportsmanagement/views/predictionproject/view.html.php on line 73 and exactly 1 expected

**Comment by ortwin20000** [comment]
Ich habe zwar keine Erfahrung mit den Tippspielen aber Ich hätte dies in Joomla 5.1 mal versucht und ich komme gar nicht zu diesen Link PredictionProject.

So bin ich vorgegangen:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/db7f1582-c827-40a2-9d5e-6c4f7a4ad6ef)

Neues Tippspiel anlegen:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/81b0a963-1afc-4979-848e-1d81f83994d4)

Name und Projekte ausgewählt:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/fce84cd0-251e-4fdc-ab9d-cf13958eae17)

![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/1207807d-b324-448c-a06e-b70b1d17119a)

Wie kommst du zur Fehlermeldung?

**Comment by boxr** [comment]
Ich gehe bis dahin den gleichen weg, 2x Filteroptionen, wenn ich dann das Projekt anklicke erscheint die Fehlermeldung

![2024-06-09_08h09_49](https://github.com/diddipoeler/sportsmanagement/assets/7561511/32faff55-ca92-4152-9c7d-7d56bf071e4c)

**Comment by waiter1987** [comment]
> Ich habe zwar keine Erfahrung mit den Tippspielen aber Ich hätte dies in Joomla 5.1 mal versucht und ich komme gar nicht zu diesen Link PredictionProject.
> 
> So bin ich vorgegangen: ![image](https://private-user-images.githubusercontent.com/15192502/337907514-db7f1582-c827-40a2-9d5e-6c4f7a4ad6ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NjA2ODksIm5iZiI6MTcxNzk2MDM4OSwicGF0aCI6Ii8xNTE5MjUwMi8zMzc5MDc1MTQtZGI3ZjE1ODItYzgyNy00MGEyLTlkNWUtNmM0ZjdhNGFkNmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE5MTMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NjhiYmJjYmQ1NDM0YWMzZDc4YzFmNWU4YTc4ZTA2ZjFhMTE5YmVlZDg0OGU3ODZkNWE4NmZlNjM3MDY5YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lP-53TMQMOJYt7tC3xRfA4Oe7mgKIezkjgK7B10qa-8)
> 
> Neues Tippspiel anlegen: ![image](https://private-user-images.githubusercontent.com/15192502/337907888-81b0a963-1afc-4979-848e-1d81f83994d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NjA2ODksIm5iZiI6MTcxNzk2MDM4OSwicGF0aCI6Ii8xNTE5MjUwMi8zMzc5MDc4ODgtODFiMGE5NjMtMWFmYy00OTc5LTg0OGUtMWQ4MWY4Mzk5NGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE5MTMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MTU5YTJlZTVmN2NiNzYzMjhiMGMxNjRkMTNmZjQ4YWQzZDU5OGY4NTdjNTI5M2NmYjMxNGJlZjlmNzc5N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.stfS5T0N_yNjBOcw7CoHaeFyyive47uf2SxCI2VMh3M)
> 
> Name und Projekte ausgewählt: ![image](https://private-user-images.githubusercontent.com/15192502/337908180-fce84cd0-251e-4fdc-ab9d-cf13958eae17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NjA2ODksIm5iZiI6MTcxNzk2MDM4OSwicGF0aCI6Ii8xNTE5MjUwMi8zMzc5MDgxODAtZmNlODRjZDAtMjUxZS00ZmRjLWFiOWQtY2YxMzk1OGVhZTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE5MTMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlODBhMjYxZmI0OWZmZGZlOGY4YTQyOGI5NTFkZjNhM2E5YzMyMmQwMzlkZWM3ZTFiZGZhZDUyYTE4YTNjMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Ur7vzbc8Ndw2xy7Th0CZpWPIZ0bcKwBo_Gjh0w_T2I)
> 
> ![image](https://private-user-images.githubusercontent.com/15192502/337908421-1207807d-b324-448c-a06e-b70b1d17119a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NjA2ODksIm5iZiI6MTcxNzk2MDM4OSwicGF0aCI6Ii8xNTE5MjUwMi8zMzc5MDg0MjEtMTIwNzgwN2QtYjMyNC00NDhjLWEwNmUtYjcwYjFkMTcxMTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE5MTMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwOGI5MWEyMGJlZWEwZTBkYjI1MjdjODMxOWZkNjkzY2ExYTYwNDJjMWYzYmM1MmI1ZjQ3MGUzMjVhZmVjMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.srsi-_aKb5Js9e_tas8eA6VbjC0rj5gnQI91-rNsJm0)
> 
> Wie kommst du zur Fehlermeldung?

Wenn ich das so mache, sieht das so aus 
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/3df52ff1-152b-4e1a-8b2c-14a72d49ef64)

Ich kann aber das Projekt zumindest editieren 🤷‍♂️

**Comment by waiter1987** [comment]
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/cedff3c2-2bf2-467e-b55f-fc027bddff36)
Das kommt im Frontend... da soll was fehlen?

**Comment by ortwin20000** [comment]
@boxr
Ich konnte es bei mir nachstellen und wenn ich in der Datei administrator\components\com_sportsmanagement\views\predictionproject\view.html.php die Zeile 73 auskommentiere, funktioniert es bei mir.

![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/806f100b-89ba-4ccf-b240-e1a82aed26aa)

**Comment by boxr** [comment]
Funktioniert bei auch. 
Danke für die schnelle Hilfe 👍

**Comment by ortwin20000** [comment]
> ![image](https://private-user-images.githubusercontent.com/22858604/338004410-cedff3c2-2bf2-467e-b55f-fc027bddff36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMjUyOTQsIm5iZiI6MTcxODAyNDk5NCwicGF0aCI6Ii8yMjg1ODYwNC8zMzgwMDQ0MTAtY2VkZmYzYzItMmJmMi00NjdlLWI1NWYtZmMwMjdiZGRmZjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDEzMDk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMzMzNGUyODAzMmNkY2UxN2JlNThlODM4MWZkNDJkMTIyOWYyODQ4ODYzMzU3NWY0MDIyMTZlYzU0ZmQ3NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Msw47ExlEN1FloWW5KaDP9AcbWlTLHN4kJnOWl_zcv4) Das kommt im Frontend... da soll was fehlen?

Im Backend habe ich bei dem Tippspiel die Templates ausgewählt:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/c9da0f77-7a65-4b36-8cac-a4b9cb6462fa)

Dort musste ich dann den Filter auf Alle und das entsprechende Tippspiel setzen:
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/656e5879-1dd2-4724-8df9-62c0df7b02c8)

Dann werden mir diese angezeigt.

**Comment by ortwin20000** [comment]
@boxr Kann hier zugemacht werden oder ist noch was offen?

**Comment by boxr** [comment]
Bitte zumachen

 

Von: Andreas Haunold ***@***.***> 
Gesendet: Mittwoch, 12. Juni 2024 10:09
An: diddipoeler/sportsmanagement ***@***.***>
Cc: boxr ***@***.***>; Mention ***@***.***>
Betreff: Re: [diddipoeler/sportsmanagement] Tippspiele (Issue #1750)

 

@boxr <https://github.com/boxr>  Kann hier zugemacht werden oder ist noch was offen?
