### ISSUE TITLE
Anlegen neues Projekt - Name des Projektes nach Auswahl Saison weg

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1753]
Wenn ich ein neues Projekt erstelle, gehe ich chronologisch von oben nach unten
Name
Liga auswählen
Saison auswählen

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/ac6be1cf-acd2-467d-a0dc-1f5c12e93dcc)

Wenn ich die Saison ausgewählt habe, ist der Name weg. 
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/096ed354-bfa9-46ac-af12-314c9fadefb0)

**Comment by ortwin20000** [comment]
Ich habe hierzu einen Pull-Request gemacht und die Javascript-Funktion angepasst.
Ursprünglich wurde der Projektname bei Änderung der Saison neu gesetzt.
Meine Änderung ändert den Projektnamen nur wenn JSM auch den alten Saison-Namen findet.
z.B.: 
"1. Bundesliga 2022/23" wird bei Änderung der Saison "2022/23" auf "2023/24" so auf "1. Bundesliga 2023/24" gesetzt.
"1. Bundesliga" wird bei Änderung der Saison nicht geändert.

**Comment by waiter1987** [comment]
Hat leider nicht geklappt. Name ist nach wie vor weg, wenn ich die Saison anpasse.

**Comment by ortwin20000** [comment]
Ein Update hast du gemacht? Bei mir funktioniert es so wie ich geschrieben habe.

**Comment by waiter1987** [comment]
jetzt klappt es... DANKE
