### ISSUE TITLE
Player picture are not shown

### ISSUE THREAD

**Issue by Tanoke** [diddipoeler/sportsmanagement#1760]
I updated the component to the latest version ( b0b8b9e ). The players' pictures are no longer visible. They are now replaced by a placeholder_150.png image. I couldn't find a place in the settings where I could switch to the specified images.

**Comment by diddipoeler** [comment]
Ich glaube, dass ich etwas verkehrt gemacht habe.
Kannst du mal bitte den Link zu dem Fehler hier posten?
Oder gibt es den Fehler noch in anderen Ansichten?

**Comment by Tanoke** [comment]
Here is the link to the roster. The pictures of the players are not shown in the player presentation. This applies to all projects.

https://www.rops.fi/miehet/edustusjoukkue/joukkue-2024/roster/0/47:2024/184:miesten-ykkonen-2024/94:rops

**Comment by diddipoeler** [comment]
Kannst du mir mal bitte einen Adminzugang zusenden, damit ich mir das im Backend anschaue?

**Comment by Tanoke** [comment]
Username and password have been sent to your email.

**Comment by diddipoeler** [comment]
Everything is okay again now. The player pictures are now displayed again.
Please use the template roster.
Then persons options, set **Player preview image in the statistics** to yes
Then staff settings, set **Show thumbnails of bar staff in statistics?** to yes

**Comment by Tanoke** [comment]
I guess I phrased the problem poorly. The team roster images are displayed correctly, but the player image behind the player link is not displayed correctly. https://www.rops.fi/miehet/edustusjoukkue/joukkue-2024/player/0/472024/184:miesten-ykkoenen-2024/94:rops/739:tino-korhonen

**Comment by diddipoeler** [comment]
We have detected suspicious activity from your IP address. Your access to this site is temporarily suspended. If you are the administrator of this site and have blocked your own IP address on accident please visit https://www.rops.fi/administrator/index.php?admintools_rescue=you@example.com where you@example.com is the email address of your (Super User) account. This URL will only send you an email if the IP address from which you are accessing it is being blocked by Admin Tools. If you are not blocked no email will be sent; you don't need an email with instructions to unblock your IP if your IP is not blocked.

**Comment by Tanoke** [comment]
The username was expired. Now try to log in to the site again

**Comment by diddipoeler** [comment]
Habe den Fehler gefunden. 
Bitte noch einmal testen.

**Comment by Tanoke** [comment]
Thank you, Player images are now displayed correctly.
