### ISSUE TITLE
Wechsel und Ereignisse nach regulärem Spielende nicht möglich

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1761]
Wenn ein Spiel in die Verlängerung geht, sind in der Verlängerung selber weder Auswechslungen noch Events (Tor, Karten etc.) mehr möglich. 

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/44bb55c8-c7de-49e4-8b3a-df54b78bf9bd)

![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/528e6add-3477-429e-b892-303bf64387be)

Eingabe:
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/a79bb694-c8aa-4207-9b22-6e878805e8c8)
Nach Speichern:
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/63a2fb45-5adf-4b3c-8e7c-9efbacc0d52a)

Durch die Verlängerung wird beim Spieler korrekterweise die 120 Minuten ausgewiesen
![image](https://github.com/diddipoeler/sportsmanagement/assets/22858604/71e20471-3a41-4a5a-8603-b3c32e3a9e72)

**Comment by ortwin20000** [comment]
Liegt an dieser Abfrage. Im Projekt sind 90 Minuten reguläre Spielzeit eingetragen und ein Ereignis in der 102. Minute wird dann nicht akzeptiert.
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/af14341a-e2a3-4d8b-9338-03e72753caea)

Die Variable useeventtime wird aus der Sportart gezogen.
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/0513e9be-0ac3-465f-ba94-1fb4a8c7a9a1)

Es wird keine Nachspielzeit bzw. Verlängerung in der Prüfung mitberücksichtigt.
![image](https://github.com/diddipoeler/sportsmanagement/assets/15192502/38e957bc-68b6-4735-af4d-2cab62299bdd)

Die Frage ist halt wie wir es zukünftig haben möchten. 
Was ist wenn in der 94. Nachspielzeit ein Ereignis fällt und danach Verlängerung ist und hier ebenfalls in der nun neuen 94. Minute ein Ereignis fällt? Wie wird so etwas erfasst?

Die Prüfung einfach rausschmeißen und nur kontrollieren ob eine Zeit eingetragen wurde? Oder die Nachspielzeit und die Verlängerung zu der regulären Spielzeit addieren und dagegen prüfen? Oder muss die Ereigniserfassung noch um den Teil erweitert werden ob es sich um die reguläre Spielzeit handelt oder um die Verlängerung?

**Comment by diddipoeler** [comment]
Habe ich erst einmal ausgeschaltet.

**Comment by waiter1987** [comment]
DANKE, ich teste das bei der nächste Verlängerung (vll heute Abend ;-) ) bzw. suche ich in der Vergangenheit was, wo ne Verlängerung war und wo ich das noch nicht gepflegt habe.

**Comment by waiter1987** [comment]
perfekt. DANKE
