### ISSUE TITLE
Schiedsrichterzuordnungen nach Update weg oder nur woanders?

### ISSUE THREAD

**Issue by waiter1987** [diddipoeler/sportsmanagement#1777]
Hallo, 

nach dem Update ist im Spieltag die Schiedsrichterzuordnung verschwunden. 
![image](https://github.com/user-attachments/assets/e6c8f65e-415b-448b-a776-79e76da9071f)

Bei vergangenen Spielen sehe ich im Frontend noch die Zuordnung der Schiedsrichter, aber nicht mehr im Backend.

Oder sind die jetzt woanders?

Danke fürs Feedback.

**Comment by sigal** [comment]
Ist nicht verschwunden, sondern im Template backend_matches
des Projektes einzustellen,

Es wäre schön wenn  solche Fragen in Zukunft im Forum gestellt würden,

**Comment by waiter1987** [comment]
Ich gelobe Besserung
