### ISSUE TITLE
Unable to add substitutions

### ISSUE THREAD

**Issue by bertderop** [diddipoeler/sportsmanagement#1779]
I've updated Sportsmanagement to version 4.22.00 but now i can't add substitions anymore.
The tabs "Substitutions" and "Staff" are missing.

![sportsmanagement](https://github.com/user-attachments/assets/6ca9d8d6-d1fd-4b81-821a-395de4573c34)

**Comment by diddipoeler** [comment]
Bitte ein Github Update durchführen.


Gesendet: Mittwoch, 6. November 2024 um 07:44
Von: bertderop ***@***.***>
An: diddipoeler/sportsmanagement ***@***.***>
CC: Subscribed ***@***.***>
Betreff: [diddipoeler/sportsmanagement] Unable to add substitutions (Issue #1779)

 
I've updated Sportsmanagement to version 4.22.00 but now i can't add substitions anymore.The tabs "Substitutions" and "Staff" are missing.
sportsmanagement.png (view on web)

**Comment by bertderop** [comment]
Hallo Dieter,

Wenn ich während des Github-Updates auf den blauen „Update installieren“-Button klicke, passiert nichts...

***@***.***

Met vriendelijke groeten,
Bert De Rop
Fiscaal Accountant ITAA
BOEKHOUDKANTOOR PATRICK DE ROP BV
Kerkstraat 120
9120 VRASENE
Tel: 03/775.08.75
Fax: 03/755.15.55
E-mail: ***@***.******@***.***>

Van: diddipoeler ***@***.***>
Verzonden: woensdag 6 november 2024 11:26
Aan: diddipoeler/sportsmanagement ***@***.***>
CC: Bert De Rop ***@***.***>; Author ***@***.***>
Onderwerp: Re: [diddipoeler/sportsmanagement] Unable to add substitutions (Issue #1779)

U ontvangt niet vaak e-mail van ***@***.*** Ontdek waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>
Bitte ein Github Update durchführen. <br> <br> <br> Gesendet: Mittwoch, 6. November 2024 um 07:44 <br> Von: bertderop ***@***.***&gt; <br> An: diddipoeler/sportsmanagement ***@***.***&gt; <br> CC: Subscribed ***@***.***&gt; <br> Betreff: [diddipoeler/sportsmanagement] Unable to add substitutions (Issue #1779) <br> <br>   <br> I&#39;ve updated Sportsmanagement to version 4.22.00 but now i can&#39;t add substitions anymore.The tabs &quot;Substitutions&quot; and &quot;Staff&quot; are missing. <br> sportsmanagement.png (view on web) <br> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

**Comment by diddipoeler** [comment]
Bitte mal für mich einen Admin User mit allen Rechten einrichten.
Ich schaue mir das gerne mal im Backend an.

**Comment by bertderop** [comment]
Die Details zum Administratorzugriff finden Sie hier. Das Anmelden kann 2-3 Minuten dauern

  *   User : diddipoeler
  *   Pasword : 130823KFC
  *   URL : https://www.kfc-vrasene.be/administrator/


Met vriendelijke groeten,
Bert De Rop
Fiscaal Accountant ITAA
BOEKHOUDKANTOOR PATRICK DE ROP BV
Kerkstraat 120
9120 VRASENE
Tel: 03/775.08.75
Fax: 03/755.15.55
E-mail: ***@***.******@***.***>

Van: diddipoeler ***@***.***>
Verzonden: woensdag 6 november 2024 14:50
Aan: diddipoeler/sportsmanagement ***@***.***>
CC: Bert De Rop ***@***.***>; Author ***@***.***>
Onderwerp: Re: [diddipoeler/sportsmanagement] Unable to add substitutions (Issue #1779)


Bitte mal für mich einen Admin User mit allen Rechten einrichten.
Ich schaue mir das gerne mal im Backend an.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
Meine Empfehlung: PHP Version auf 8 einstellen und ein Update der Seite auf Joomla 4 vornehmen.

**Comment by bertderop** [comment]
Vielen dank !

Met vriendelijke groeten,
Bert De Rop
Fiscaal Accountant ITAA
BOEKHOUDKANTOOR PATRICK DE ROP BV
Kerkstraat 120
9120 VRASENE
Tel: 03/775.08.75
Fax: 03/755.15.55
E-mail: ***@***.******@***.***>

Van: diddipoeler ***@***.***>
Verzonden: donderdag 7 november 2024 9:32
Aan: diddipoeler/sportsmanagement ***@***.***>
CC: Bert De Rop ***@***.***>; Author ***@***.***>
Onderwerp: Re: [diddipoeler/sportsmanagement] Unable to add substitutions (Issue #1779)


Bitte noch einmal testen.
Meine Empfehlung: PHP Version auf 8 einstellen und ein Update der Seite auf Joomla 4 vornehmen.
