### ISSUE TITLE
Resultsranking defekt

### ISSUE THREAD

**Issue by boindil** [diddipoeler/sportsmanagement#268]
Folgende Fehler treten auf:
- COM_SPORTSMANAGEMENT_MASTER_TEMPLATE_MISSING: resultsranking
- COM_SPORTSMANAGEMENT_ADMIN_MATCHES_CHANGE_NOTALLOWED
  >> Die Admingruppe wurde im Projekt gesetzt, sollte also funktionieren.

Wenn ich das Template unter resultsranking/tmpl editiere, passiert garnix. Welches Template wird dann bitte genutzt.

Insgesamt sehr schönes Plugin, aber hier besteht offensichtlich noch ein etwas größeres Problem :(

**Comment by diddipoeler** [comment]
Bitte mehr Details.
Wann tritt der Fehler mit dem Template auf ? Im frontend oder backend ?
Kommt die Fehlermeldung auch im frontend ?
Welches Plugin ? Oder meinst du die Komponente ?

**Comment by diddipoeler** [comment]
Die Fehlermeldung: •COM_SPORTSMANAGEMENT_MASTER_TEMPLATE_MISSING resultsranking
erscheint jetzt nicht mehr. Für diese Ansicht bitte die Template Einstelllungen: ranking und results
im Backend benutzen.

**Comment by boindil** [comment]
Hi,
ja stimmt, etwas mehr Details wären vllt sinnvoll gewesen ...
Heute Nacht hab ich da nicht mehr so viel gedacht.

Ich habe im Frontend einen Menülink zur "Ergebnis-Tabelle" gesetzt und diesen aufgerufen. Anschließend traten die Fehler auf.

Ein Einkommentieren der entsprechenden Zeilen 670 und 672 unter `site/models/results.php` zeigte mir, dass selbst wenn die Editorgruppe auf Super Users gesetzt ist diese immer 0 ist beim Funktionsaufruf.

Entsprechend kam die Fehlermeldung `COM_SPORTSMANAGEMENT_ADMIN_MATCHES_CHANGE_NOTALLOWED` zustande. Wenn ich mich selbst als Editor gesetzt habe, trat die Meldung nicht mehr auf, aber das Edit-Symbol wurde dennoch nicht angezeigt.

> Für diese Ansicht bitte die Template Einstelllungen: ranking und results im Backend benutzen.

Magst du das etwas mehr ausführen? Ich habe das System erst heute Nacht installiert und bin mir jetzt nicht ganz sicher, wie du das meinst.

Vielen Dank schonmal für die schnelle Reaktion :+1:

**Comment by diddipoeler** [comment]
ich meine die templates: results und ranking zu deinem projekt. diese bitte im backend
richtig konfigurieren. der view reultsranking zieht sich dann automatisch beide einstellungen.

**Comment by sigal** [comment]
Meiner Meinung nach kann dieser Issue geschlossen werden, da ich nach intensiven testen keinen Fehler mehr entdecken konnte. :radio:

**Comment by boindil** [comment]
Habe mal zumindest eine kleine Änderung eingebracht, die auch das Editierensymbol wieder einblendet. Funktionieren tut das Editierensymbol zumindest unter Joomla 2.5 im Frontend dennoch nicht.

Zugegebenermaßen bin ich aber wieder zurück zu JoomLeague gegangen. Das ist zwar unter Joomla 2.5 auch äußerst verbuggt, da konnte ich allerdings um die Probleme so weit herumschiffen/-programmieren, dass es für die gewünschten Zwecke nutzbar ist.

**Comment by diddipoeler** [comment]
danke für deine ehrliche antwort. jetzt erst hatte ich, durch deine antwort, erfahren, dass
du joomla 2.5 verwendest. leider hätte ich auch nicht gedacht, dass du dich von einem kleinen
bug abschrecken lässt mit einer neuen komponente zu arbeiten. ich kann jede hilfe bei der
weiterentwicklung/programmierung benötigen und hoffe, das du dich noch einmal meldest.

**Comment by boindil** [comment]
Hi,
Problem an der Ganzen geschichte ist, dass das System zur Mitte dieses Monats lauffähig sein musste. Es gab bereits viele Daten mit Joomleague und daher sollte das genutzt werden. Eigentlich wurde gewünscht, dass die Funktion zum Editieren im Frontend funktioniert, allerdings ging das bei Joomleague nicht, sodass ich gehofft hatte, dass das mit dieser Komponente geht.

Joomla 2.5 war zunächst Voraussetzung, da es kein fertiges JoomLeague für Joomla 3 gibt ...

Aus deinem Kommentar lese ich raus, dass die Komponente unter Joomla 3 besser laufen sollte?

**Comment by diddipoeler** [comment]
die komponente läuft unter joomla 3 besser, weil ich die prio auf joomla 3 gesetzt habe.
sollte etwas unter joomla 2.5 nicht laufen bitte reporten. dann kann ich das anpassen.
du kannst aber mal als test die jl tabellen importieren und die neue komponente testen.
ich würde mich freuen, wenn ich dich als neues mitglied begrüßen könnte.

**Comment by diddipoeler** [comment]
gibt es hier neue erkenntnisse ?
läuft alles zu deiner zufriedenheit ?

**Comment by diddipoeler** [comment]
gibt es hier neue erkenntnisse ?
 läuft alles zu deiner zufriedenheit ?
