### ISSUE TITLE
Backend-View: teampersons Layout: default

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#273]
Zuordnung von Spieler:
Falsches Modalfenster für Spielerzuordnung. Es wird die Auswahl für die Zuordnung des Betreuerstabes geöffnet.

Also Auswahl nur für Personen, die eine Mitarbeiterposition zugeordnet wurde. (Peronenverwaltung->Allgemeine Anforderung->Position)

Detto bei Mannschaftsstab verwalten. Hier wird einen beim Klick auf Button -Spieler zuordnen- die Auswahl von Spielern präsentiert.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by teddyfresco** [comment]
A question about players assignment: if I already assigned a player(s) to team xyz in the same project, is it correct that he shows up when I'm assigning players to team abc?

**Comment by diddipoeler** [comment]
ja. das habe ich so eingebaut, damit man einen spieler mehreren mannschaften in der selben
saison zuordnen kann. der spieler kann auch innerhalb der saison einen verein wechseln.
