### ISSUE TITLE
Backend-View: matches Layout: default

### ISSUE THREAD

**Issue by diddipoeler** [diddipoeler/sportsmanagement#275]
Wenn das Spieldatum leer ist, dann wird 30-11--1 angezeigt.

**Comment by svdoldie** [comment]
das passt zu http://mantisbugtracker.fussballineuropa.de/view.php?id=258

**Comment by teddyfresco** [comment]
Bug confirmed in latest version

**Comment by diddipoeler** [comment]
Please try again .

**Comment by teddyfresco** [comment]
Matchday view seems corrected, like this:
http://awesomescreenshot.com/0d661ru3fa
match layout, instead, is still showing  30-11--1
