### ISSUE TITLE
Translation issue with utf-8 characters

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#276]
There is an issue with italian accented characters like à, è, ò...
You can see it on
http://www.awesomescreenshot.com/image/1155546/8334eb83efd17cbb51df804589e792b1
Tested on 
J3.4.4 
Version database	5.5.39
Collation database	utf8_general_ci
Version PHP	5.6.16
3.5.1
Version database	5.5.40-36.1-log
Collation database	utf8_general_ci
Collation connection database	utf8mb4_general_ci
Version PHP	5.5.31
There's also a missing language item, the github link, which by the way leads to a blank lightbox.
The other github link on JSM control panel leads to 404 error.

**Comment by diddipoeler** [comment]
did you save the file as utf-8 ?

**Comment by diddipoeler** [comment]
for the github utility, please insert your username and password from the github account in the
configuration of jsm.

**Comment by teddyfresco** [comment]
I just installed from URL the last JSM, italian has been included for the
last 2 days.
Il 11/apr/2016 14:39, "diddipoeler" <notifications@github.com> ha scritto:

**Comment by teddyfresco** [comment]
diddi, regarding github account there's only a github username field (without password), which I filled in  and now I can see the correct lightbox, but with the usual translation glitch:
http://awesomescreenshot.com/0795s6y441

**Comment by sigal** [comment]
Sorry, this error is undermined me.
Faultless italian language files are included in the GitHub tomorrow.
Best Regards
stony

**Comment by teddyfresco** [comment]
Sigal, thank you for the update, now it works.
Just for info, because I am reviewing my italian translation and there are a lot of errors I'm correcting, how often do you update translations? Should I alert you once in a while?

**Comment by diddipoeler** [comment]
hello teddyfresco
all associations from italy are online. have fun.

**Comment by sigal** [comment]
Hi teddyfresco, 
please let me know if you've made an update of the language files. I make then a weekly update on GitHub.

**Comment by teddyfresco** [comment]
Of course I'll do sigal, thank you!!
