### ISSUE TITLE
Cannot create a new project after importing Joomleague tables

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#277]
After importing Joomleague tables, when I go to projects page and hit the New button, I get a blank page.
Tested on 
J3.4.4 
Version database 5.5.39
Collation database utf8_general_ci
Version PHP 5.6.16
J3.5.1
Version database 5.5.40-36.1-log
Collation database utf8_general_ci
Collation connection database utf8mb4_general_ci
Version PHP 5.5.31
If I create test projects on JSM, then import JL tables, the test projects are removed.

**Comment by diddipoeler** [comment]
please go to the configuration of joomla. tab server. set errorreporting to maximum. save.
go to the Project page and hit the new button. which message will display ?

**Comment by diddipoeler** [comment]
if you Import the old jl tables, all jsm tables will truncate.

**Comment by teddyfresco** [comment]
With maximum error reporting it works! it give this notices but the page is displayed and it's possible to save data.
`Notice: Undefined variable: user in /home/public_html/mydir/administrator/components/com_sportsmanagement/views/project/view.html.php on line 116

Notice: Trying to get property of non-object in /home/public_html/mydir/administrator/components/com_sportsmanagement/views/project/view.html.php on line 116

Notice: Undefined variable: user in /home/public_html/mydir/administrator/components/com_sportsmanagement/views/project/view.html.php on line 117

Notice: Trying to get property of non-object in /home/public_html/mydir/administrator/components/com_sportsmanagement/views/project/view.html.php on line 117

Notice: Undefined variable: user in /home/public_html/mydir/administrator/components/com_sportsmanagement/views/project/view.html.php on line 118

Notice: Trying to get property of non-object in /home/public_html/mydir/administrator/components/com_sportsmanagement/views/project/view.html.php on line 118`

**Comment by diddipoeler** [comment]
please make an update.

**Comment by teddyfresco** [comment]
Update done, errors disappeared!
May I suggest an improvement?
As of now, if you want to add teams, you can't until you set on the project's "Abfrage Altersgruppe" tab, on the "Sport" tab the correct Sport Type, otherwise teams are not listed in the teams assignment page.
Wouldn't it be better to put that sport type selector on a more prominent tab?
Or am I doing anything wrong? :-)
