### ISSUE TITLE
Backend-View: club Layout: edit

### ISSUE THREAD

**Issue by diddipoeler** [diddipoeler/sportsmanagement#279]
Wenn das Gründungsdatum und das Auflösungsdatum  leer ist, dann wird 30-11--1 angezeigt.

**Comment by smileysit** [comment]
is it possible to download the component for beta testing (english)

**Comment by diddipoeler** [comment]
yes you can download the component for beta testing.

**Comment by diddipoeler** [comment]
änderungen sind im github.
