### ISSUE TITLE
Error jcomments

### ISSUE THREAD

**Issue by sk-plehanovec** [diddipoeler/sportsmanagement#281]
Warning: require_once(/components/com_sportsmanagement/jcomments.class.php): failed to open stream: No such file or directory in /components/com_sportsmanagement/views/teamplan/tmpl/default_plan.php on line 44
Fatal error: require_once(): Failed opening required '/components/com_sportsmanagement/jcomments.class.php' (include_path='/home/admin/web/fhr-sdv.ru/public_html/administrator/components/com_sportsmanagement/libraries:.:/usr/share/pear:/usr/share/php') in /components/com_sportsmanagement/views/teamplan/tmpl/default_plan.php on line 44

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
