### ISSUE TITLE
Matchreport tabs without CSS Layout: matchreport

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#283]
As previously stated on
http://www.fussballineuropa.de/index.php?option=com_kunena&view=topic&Itemid=142&catid=264&id=4466&limitstart=12#11600
tabs and slider views (set on "tabs zeigen" in matchreport template settings) keep not loading the CSS, the page show only the match report text.

**Comment by teddyfresco** [comment]
I've found another user with the same problem:
http://rwo.textildepot24.de/index.php/1-herren/spielplan/matchreport/0/16/72-15-16-kreisoberliga-herren/8240-fv-rot-weiss-93-olbersdorf_vfb-weisswasser-1909

**Comment by diddipoeler** [comment]
please update the component.

**Comment by sk-plehanovec** [comment]
default_events_tabs.php
ERROR
JPane

**Comment by sk-plehanovec** [comment]
matchreport/view.html.php
Line 80-85 file not found

**Comment by teddyfresco** [comment]
Tried locally, but menu items don't work any more with latest version just installed, give out this error:
`Error: 1146 - Table 'abc_defg.#___round' doesn't exist SQL=SELECT CONCAT_WS( ':', id, alias ) AS value,name AS text,id, name, round_date_first, round_date_last, roundcode FROM #___round WHERE project_id = 143 AND published = 1 ORDER BY roundcode `

**Comment by teddyfresco** [comment]
Tried again, switching templates and browsers, but still no CSS :-(

**Comment by diddipoeler** [comment]
please call me the internet address.

**Comment by teddyfresco** [comment]
Diddi, I've sent to your email the link and admin access to test site

**Comment by diddipoeler** [comment]
please install the component: eXtplorer  on your site.

**Comment by diddipoeler** [comment]
now, you can test then tabs in the ranking. i enable the System - jQuery Easy plugin.

**Comment by teddyfresco** [comment]
Diddi, I disabled the jquery easy just for testing purposes, and now that is enabled I checked on different browsers but it still doesn't load the CSS.
Should I activate some advanced feature of jquery easy?
I have installed extplorer, just in case you'd need it...

**Comment by diddipoeler** [comment]
here is your ranking: http://mittelcom.it/sanlu/index.php/sm
it work´s.

**Comment by teddyfresco** [comment]
Diddi, I do agree and thank you for your work, it works, but I was talking about matchreport view, the link I've sent you by email, that still doesn't work.

**Comment by diddipoeler** [comment]
please make an update for the component :-)

**Comment by teddyfresco** [comment]
Update done 3 minutes ago, downloaded from 
https://github.com/diddipoeler/sportsmanagement/archive/master.zip
but the problem goes on, tabs and slider mode not working
it's really a mistery

**Comment by diddipoeler** [comment]
please set the errorreporting in the joomla configuration to Maximum.

**Comment by teddyfresco** [comment]
Done, it shows this on top of the page
`Notice: Undefined index: show_project_sporttype_picture in /home5/mittelco/public_html/test/components/com_sportsmanagement/views/globalviews/tmpl/default_projectheading.php on line 51

Notice: Undefined index: show_project_kunena_link in /home5/mittelco/public_html/test/components/com_sportsmanagement/views/globalviews/tmpl/default_projectheading.php on line 52

Notice: Undefined index: show_project_picture in /home5/mittelco/public_html/test/components/com_sportsmanagement/views/globalviews/tmpl/default_projectheading.php on line 53

Notice: Undefined index: show_project_staffel_id in /home5/mittelco/public_html/test/components/com_sportsmanagement/views/globalviews/tmpl/default_projectheading.php on line 54

Notice: Undefined index: show_project_country in /home5/mittelco/public_html/test/components/com_sportsmanagement/views/globalviews/tmpl/default_projectheading.php on line 63

Notice: Undefined index: show_project_sporttype_picture in /home5/mittelco/public_html/test/components/com_sportsmanagement/views/globalviews/tmpl/default_projectheading.php on line 88

Notice: Undefined index: show_project_picture in /home5/mittelco/public_html/test/components/com_sportsmanagement/views/globalviews/tmpl/default_projectheading.php on line 106

Notice: Undefined index: show_project_text in /home5/mittelco/public_html/test/components/com_sportsmanagement/views/globalviews/tmpl/default_projectheading.php on line 137

Notice: Undefined index: show_project_staffel_id in /home5/mittelco/public_html/test/components/com_sportsmanagement/views/globalviews/tmpl/default_projectheading.php on line 152
 	
Notice: Undefined index: show_project_kunena_link in /home5/mittelco/public_html/test/components/com_sportsmanagement/views/globalviews/tmpl/default_projectheading.php on line 177`

and this on bottom:
` Parse error: syntax error, unexpected '<<' (T_SL) in /home5/mittelco/public_html/test/components/com_sportsmanagement/views/matchreport/tmpl/default_events_tabs.php on line 334`

**Comment by diddipoeler** [comment]
please make an update for the component :-)

**Comment by teddyfresco** [comment]
Yahoooo! Now it's ok. Great Diddi!!
At least with default Joomla template and Yootheme template.
Just for future reference, Rockettheme and Gavick templates have some issues with slider and tabs.
By the way,
- players are still shown duplicated n times
- events/stats are still an issue for imported leagues
