### ISSUE TITLE
Spieler abwählen beim Import funktioniert nicht richtig

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#284]
Wenn man eine Spielerliste per DFBnet-Import einlesen möchte und dabei einzelne Spieler abwählt, werden Sie trotzdem angelegt, allerdings ohne Namen.
Desweiteren wäre es toll, wenn beim importieren die Altersklasse und die aktuelle Saison gesetzt werden könnten.

**Comment by svdoldie** [comment]
Ich habe das gerade nochmal probiert. Wenn man erst  "alle neu" anwählt und anschließend "alle neu" wieder abwählt, werden keine Spieler importiert, obwohl man vorher per "Person neu erstellen" eine oder mehrere angewählt hat.

**Comment by tdittmann** [comment]
Ich habe gerade mal versucht eine Spielerliste zu importieren, aber ich glaube da stimmt noch etwas mehr nicht:
![image](https://user-images.githubusercontent.com/22032251/51440277-ba39dc80-1cc5-11e9-836b-0950b6d22815.png)

Kannst du das bestätigen?

**Comment by svdoldie** [comment]
Anscheinend haben die im DFBnet auch etwas geändert.
Ich hab ne alte, die hat Tabulatoren.
Die aktuelle hat Semikolons als Trenner

**Comment by diddipoeler** [comment]
Bitte einmal mit vorsicht testen.

**Comment by diddipoeler** [comment]
Bei mir werden alle geladen.
Bitte mal die Liste zusenden.

**Comment by svdoldie** [comment]
Sorry, hatte mich mit der Liste vertan.
Mit der aktuellen kommt folgende Fehlermeldung beim hochladen:

× 
Hinweis

Spielerliste

× 

Welches Land? DEU

Welche Art von Datei? playerfile

Datei? /var/www/vhosts/svdoldie.stony-sport4u.de/httpdocs/tmp/joomleague_import.csv

Personen Daten generiert

× 
Fehler

Fehler: Load of the importfile failed:!

Fehler: Input is not proper UTF-8, indicate encoding ! Bytes: 0xFC 0x68 0x6C 0x5D !

Fehler: Something is wrong inside the import file!

**Comment by svdoldie** [comment]
Ich schicke dir trotzdem meine Liste ;-)

**Comment by svdoldie** [comment]
Nachdem ich meine Liste ebenfalls konvertiert habe wird sie ohne Probleme hochgeladen und importiert.
Allerdings nur die ersten 99 Personen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Sind weiterhin 99 Personen, die importiert werden, wenn ich den Haken bei "Alle neu" setze.
Lass ich den weg und starte den Import direkt, werden auch diese 99 Personen importiert,
nur das so auch noch eine Person ohne jegliche Daten angelegt wird.

**Comment by svdoldie** [comment]
Das Ab- oder Auswählen funktioniert mittlerweile einwandfrei und es werden auch alle Personen (mehr als 99) importiert 👍
