### ISSUE TITLE
Positionen zuordnen klappt nicht

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#287]
Wenn man Positionen zu einem Projekt zuordnen möchte kommt folgende Fehlermeldung:
Es ist ein Fehler aufgetreten!
 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY parent_id ASC,name ASC' at line 7 SQL=SELECT	id AS value, name AS text, sports_type_id AS type, parent_id AS parentID FROM #__sportsmanagement_position WHERE published=1 AND sports_type_id= ORDER BY parent_id ASC,name ASC

**Comment by svdoldie** [comment]
Das Problem existiert nur, wenn man über die aktuelle Saison direkt in die Postionen eines Projekts geht.

**Comment by teddyfresco** [comment]
svdoldie, please check this bug, I cannot replicate locally on php 5.6.20, and online on 5.5.36, both using Joomla 3.6.2. It seems to be solved.

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by teddyfresco** [comment]
Same as before, I can't reproduce

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by svdoldie** [comment]
existiert bei mir immer noch

**Comment by diddipoeler** [comment]
update der komponente gemacht ?

**Comment by svdoldie** [comment]
ja, der Fehler tritt bei mir sowohl auf meiner Hauptseite, als auch auf der Testseite auf

**Comment by diddipoeler** [comment]
Hat dein Projekt auch eine Sportart ?

**Comment by svdoldie** [comment]
Ja, alle Projekte haben die Sportart Fußball

**Comment by diddipoeler** [comment]
Kannst Du mir mal bitte die Zugangsdaten von deinem Testserver zusenden ?
Ich habe den Fehler auf der Testseite: http://joomla3.fussballineuropa.de/index.php nicht !

**Comment by svdoldie** [comment]
Schick ich dir per Whatsapp

**Comment by diddipoeler** [comment]
Ich habe mich gerade auf Deiner Testseite angemeldet und der 1. Bundesliga 2011/12 eine
Position zugeordnet. Alles ohne Fehler.

**Comment by svdoldie** [comment]
so geht es auch. Das Problem existiert nur, wenn man über die aktuelle Saison direkt in die Postionen eines Projekts geht.

**Comment by svdoldie** [comment]
Und auch nur, wenn vorher noch kein Projekt ausgewählt wurde

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by svdoldie** [comment]
Sieht jetzt anders aus. Jetzt kommt folgende Meldung:
1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3 SQL=SELECT * FROM #__sportsmanagement_project WHERE id =

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :-)
