### ISSUE TITLE
alle Module: Selektion von Projekt nicht möglich

### ISSUE THREAD

**Issue by Bastian007** [diddipoeler/sportsmanagement#295]
Alle Module von JSM die in den Optionen einen Selektion über das Projekt haben, ist im Feld für Projekte keine Auswahl möglich. Es gibt keine Dropdown Liste mit gültigen Projekten, selbst wenn eine Saison in einem anderen DropDownfeld bereits ausgewählt wurde.

Login daten zur Reproduktion / Besichtigung zu unserer Seite liegen vor.

**Comment by diddipoeler** [comment]
dieser fehler tritt aber nur bei dir auf.
oder gibt es noch andere user die das bestätigen können ?

**Comment by teddyfresco** [comment]
Bastian007, deine php und Joomla version? 
Bei mir alle funktionieren...

**Comment by Bastian007** [comment]
J 3.5.1 / PHP 5.5.30-1

Habe jetzt mal eine frisches Joomla aufgesetzt und nur JSM installiert und händisch 
Sportart, Liga, Saison, Projekt angelegt. Da bekomme ich die Aswahl des Projektes in den Modulen angezeigt.

Also muss es wohl mit meienr Datenkonstellation (aus JL importiert) zusammenhängen.

Habe nun beide Installation hinsichtlich Tabelleneinträge von
prefix_sportsmanagement_sports_type
prefix_sportsmanagement_league
prefix__sportsmanagement_season
prefix__sportsmanagement_project
verglichen, mir ist aber nichts besonderes aufgefallen.

Wie genau wird denn die auswählbaren Projekte per SQL ermittelt in den Modulen?
Wie gesagt kann ich eine Saison auswählen. Auch sonst im Backend zur Komponente findet er zur Saison die passenden Projekte.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
