### ISSUE TITLE
Season view not showing assigned persons and teams

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#296]
After importing JL db, Joomla 3.5.1 and JSM last version (usual testbed), php 5.5.31
If click on season icons to assign new persons I get this error:
` 1066 Not unique table/alias: 'p' SQL=SELECT p.*,p.*,t.id as value, t.name as text FROM #__sportsmanagement_person as p,#__sportsmanagement_person as p,#__sportsmanagement_team as t INNER JOIN #__sportsmanagement_season_team_id AS st on st.team_id = t.id WHERE p.id NOT IN ( SELECT stp.person_id FROM #__sportsmanagement_season_person_id AS stp WHERE stp.season_id = 11) AND p.id NOT IN ( SELECT stp.person_id FROM #__sportsmanagement_season_person_id AS stp WHERE stp.season_id = 11) AND st.season_id = 11 ORDER BY p.lastname asc,p.lastname asc LIMIT 0, 20`

to assign new teams I get an empty list, either on already used seasons or on a new one.

I've also found out that on "Season" view, only the "alt" and not the "title" of the img tag is translated, the title still shows up like this
COM_SPORTSMANAGEMENT_ADMIN_SEASONS_ASSIGN_PERSON

Diddi, if you want you already have admin access data to my testbed

**Comment by diddipoeler** [comment]
please update the component.

**Comment by teddyfresco** [comment]
It works now, without glitches, I also tried assigning teams and players, but there's still a message on project's teams view.
Teams show up correctly but there's this "Sie können keine Mannschaften ändern. Ordnen Sie zusätzliche Mannschaften der Saison zu." on top.
I can't understand if it's an error or I can just ignore it...

**Comment by teddyfresco** [comment]
Looks ok now!
