### ISSUE TITLE
Backend-View: template Layout: edit

### ISSUE THREAD

**Issue by littlehouston** [diddipoeler/sportsmanagement#302]
Die Anzeige der Spieler im Player Template enthält einen Teil "Persönliche Statistik". Dort wird ein Spielerbild ausgegeben und der Vereinsname vor der Mannschaftsbezeichnung angezeigt. Auf beides würde ich gerne verzichten. Eien Möglichkeit, dies im Backend zu- bzw. abzuwählen wäre hilfreich.

**Comment by diddipoeler** [comment]
die erweiterungen wurden eingebaut und können getestet werden.

**Comment by sigal** [comment]
I am angry. My work was back for the fish!

**Comment by diddipoeler** [comment]
Verstehe ich jetzt nicht so ganz ?

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
