### ISSUE TITLE
Assign team to project not working

### ISSUE THREAD

**Issue by BNils** [diddipoeler/sportsmanagement#309]
Hallo,

immer wenn ich ein Team zu einem Project hinzufügen möchte, ist links die Liste leer.

Nur das aller erste Team konnte man sehen, aber danach war die linke liste immer nur leer.

**Comment by diddipoeler** [comment]
die mannschaft eines vereines muss die selbe sportart haben wie das projekt.
und die mannschaft muss auch der saison zugeordnet sein.

**Comment by diddipoeler** [comment]
Gibt es hierzu auch ein Feedback, damit ich den issue schließen kann ?

**Comment by teddyfresco** [comment]
Es funktioniert wie du gesasgt hat bei mir, aber es gibt immer das:
"Sie können keine Mannschaften ändern. Ordnen Sie zusätzliche Mannschaften der Saison zu." in admin. Ich habe schon viele Mannschaften zugeordnet...

**Comment by diddipoeler** [comment]
diese information kommt nur, wenn keine mannschaft mehr der saison zugeordnet wurde
und alle mannschaften dem projekt zugeordnet wurden.

**Comment by BNils** [comment]
Hat bei mir irgendwann dann auch hingehauen. Danke
