### ISSUE TITLE
EM 2016 - Gruppen Tabellen

### ISSUE THREAD

**Issue by BNils** [diddipoeler/sportsmanagement#310]
Hallo,

Joomla 2.5.28 + joomleague-2-komplettpaket

Ein letztes Problem. Ich bekomme es nicht hin, bei der Tabellenansicht die einzelnen Gruppen einzelne zu zeigen. Ich habe nur eine Tabelle, wo alle Mannschaften drin sind.

Ich habe schon mit dem Projekttyp gespielt usw. aber leider bekomme ich es nicht hin.

Kann mir da einer helfen?

**Comment by diddipoeler** [comment]
Im backend das Projekt auswählen. Template Ranking auswählen. Reiter
Gruppeneinstellungen. Die Standardeinstellung auf Gruppe 1 setzen.

**Comment by diddipoeler** [comment]
Gibt es hierzu auch ein Feedback, damit ich den issue schließen kann ?

**Comment by BNils** [comment]
Hat geklappt, danke
