### ISSUE TITLE
Turnierbaum lässt sich nicht erstellen ...

### ISSUE THREAD

**Issue by BNils** [diddipoeler/sportsmanagement#311]
Hallo,

ich habe Problem damit, den turnierbaum zu erstellen. Zu erst habe ich auf neu gedrückt und es stand da, das erfolgreich ein treeto erstellt wurde. aber angezeigt wurde er nicht. In der Datenbank habe ich dann gesehen, das der treeto erstellt wurde, aber keine Projekt id drin war. Die habe ich dann auf mein Projekt angepasst, siehe da ich sehe auf einmal den treeto im Menü.

Dann wollte ich einen neuen Knoten erstellen, dann kommt aber immer nur die Fehlermeldung: Fehler beim Erstellen von Treeto

Kann mir da einer helfen?

**Comment by diddipoeler** [comment]
Das muss ich leider auch noch umprogrammieren. Es ist im Augenblick nicht gerade einfach sich um alle Probleme in der Komponente zu kümmern. Bitte etwas Geduld.

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by diddipoeler** [comment]
gibt es schon testergebnisse ?
