### ISSUE TITLE
Default time for matches is 30-11--1 and produces error in displaying match reports

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#312]
Hi, a longstanding bug, the data shown as 30-11--1 by default, when data is not set for matches (or other, I suspect) gives out this error on matchreport page
ERROR: 0

DateTime::__construct(): Failed to parse time string (-001-11-30T05:00:00+00:00) at position 7 (-): Double timezone specification
My J is 3.51, JSM is last version, php 5.6

**Comment by diddipoeler** [comment]
Please try again .

**Comment by teddyfresco** [comment]
No error anymore, but
30-11--1 default date is still displayed in JSM main extension options, 
in persons' pages: birthdays and death days,
in players pages: injuries, suspensions.. dates
and many more, tell me if I have to start a new bug and close this one please.

**Comment by diddipoeler** [comment]
Please try again .

**Comment by teddyfresco** [comment]
Now the component does not set any default date in this view, it leaves it blank
http://awesomescreenshot.com/0af61eoza6
If I go to edit match, I see that 30-11--1.
In this case, the match report view does show a blank page.
If I only set a date, it is correctly visible.

**Comment by teddyfresco** [comment]
Bug ist immer noch da, wenn ich einen anderen Termin als Standard festgelegt , das Matchreport wird angezeigt, sonst nicht

**Comment by diddipoeler** [comment]
bei mir wird der matchreport immer angezeigt.
ich kann den fehler leider nicht nachstellen.

**Comment by teddyfresco** [comment]
Hast du Spiele ohne Datum erstellt?
Wenn ich Spiele ohne Datum erstelle (Standard Datum 30-11--1 gesetzt ist) das spielbericht (matchreport) in Frontend zeigt weiße Seite mit "0 Error:0"
Als ich das Datum in diesem Spiel ändern, erscheint das Spielbericht korrekt

**Comment by diddipoeler** [comment]
mach mal bitte ein update der komponente.

**Comment by teddyfresco** [comment]
Ich habe eine neue Liga mit 2 teams und 1 Spiel, mit standard Datum 30-11--1 am frontend ich behomme das:
Error: 0
DateTime::__construct(): Failed to parse time string (-001-11-30T00:01:15+00:00) at position 7 (-): Double timezone specification

**Comment by diddipoeler** [comment]
bitte noch einmal testen.
