### ISSUE TITLE
adding new persons "save and new" leads back to persons admin main page

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#313]
when adding new persons
"save and new" does not lead to "create new person", instead it goes back to persons admin main page
Tested on Joomla 3.51, last JSM clean installation, php 5.5 and 5.6

**Comment by diddipoeler** [comment]
Please try again .

**Comment by teddyfresco** [comment]
the error seem solved, but when creating a new person for the first time, "save" button behaves like "save and new", you hit save and it leads to a new, empty, person page. Hitting save on a previously created person saves correctly remaining on that page.
Hitting "save and close" on a previously created person goes back to persons management page but locks that person (minor hindrance but maybe revealing for you)

**Comment by diddipoeler** [comment]
please try again.

**Comment by teddyfresco** [comment]
Solved
