### ISSUE TITLE
adding new clubs "save and new" leads back to clubs admin main page

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#314]
when adding new clubs
"save and new" does not lead to "create new person", instead it goes back to clubs admin main page
Tested on Joomla 3.51, last JSM clean installation, php 5.5 and 5.6

**Comment by diddipoeler** [comment]
Please try again .

**Comment by teddyfresco** [comment]
It seems ok now

**Comment by teddyfresco** [comment]
Checks for mandatory fields aren't done: I can create new clubs without name, short name or sport (empty leagues are possible), seems like #324

**Comment by diddipoeler** [comment]
please try again.

**Comment by teddyfresco** [comment]
Solved
