### ISSUE TITLE
In new menu items many items show only the lang key

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#315]
Adding a new menu item in admin there are a lot of items that show only the lang key (see picture below)
Testing on Joomla 3.51 set on italian language, last JSM clean installation, php 5.5 and 5.6
![menuitems](https://cloud.githubusercontent.com/assets/18396229/16612135/a3fc99f8-4365-11e6-870a-410018d71ef3.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by teddyfresco** [comment]
Great diddi, now they look ok!
