### ISSUE TITLE
adding a new person, only language keys are shown

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#316]
when adding a new person, only language keys are shown instead of positions names, and it's impossible to select the one you want (see picture below)
Testing on Joomla 3.51 set on italian language, last JSM clean installation, php 5.5 and 5.6
![newperson](https://cloud.githubusercontent.com/assets/18396229/16612689/8c62c4e0-4368-11e6-91b8-67ad262461a7.png)

**Comment by teddyfresco** [comment]
Same situation now, only the sidebar isn't responsive anymore, you have to go down with cursor keys.

**Comment by teddyfresco** [comment]
If I add new master positions, they are correctly displayed, still I think there's something wrong, since the translations should be displayed (they are correctly shown in the positions layout), and the scroll bar behaves strangely...

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by svdoldie** [comment]
existiert noch
![person](https://cloud.githubusercontent.com/assets/2417767/18264863/f5bd2f90-7412-11e6-9d2d-b1abac9510a0.PNG)

**Comment by diddipoeler** [comment]
den fehler habe ich garnicht :-(

**Comment by teddyfresco** [comment]
Ich habe es noch, in dieser layout
also in mannschaft zuordnung:
http://awesomescreenshot.com/0ed649mt70
un also wie hier (soll ich den bug auch in github öffnen?)
http://mantisbugtracker.fussballineuropa.de/view.php?id=157

**Comment by sigal** [comment]
das sind fehlende Sprachschlüssel!
werde sie nachtragen!

**Comment by diddipoeler** [comment]
das ist ein bug von mir.
einen augenblick geduld.

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :-)
