### ISSUE TITLE
Adding new menu item "display player info" shows sql error

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#318]
Adding a new menu item "display player info", when clicking on menu type choice, gives out either a blank page, or this message:
`1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND p.published = 1 AND stp.persontype = 1 GROUP BY p.id ORDER BY text' at line 6 SQL=SELECT CONCAT_WS(':', p.id, p.alias) AS value,CONCAT(p.lastname, ', ', p.firstname, ' (', p.birthday, ')') AS text FROM #__sportsmanagement_person AS p INNER JOIN #__sportsmanagement_season_team_person_id AS stp ON stp.person_id = p.id INNER JOIN #__sportsmanagement_season_team_id AS st ON st.team_id = stp.team_id INNER JOIN #__sportsmanagement_project_team pt ON pt.team_id = st.id WHERE pt.project_id = AND p.published = 1 AND stp.persontype = 1 GROUP BY p.id ORDER BY text`

**Comment by teddyfresco** [comment]
After your 6/7 modifications, the menu item admin page shows up, and it's possible to select year and project and players are listed, but when you try to select them, the selection is not taken.

**Comment by diddipoeler** [comment]
please try again.

**Comment by teddyfresco** [comment]
No more SQL error now, but player's stats and career are shown 4 times and calculated, so the only tournament I've created counts for 4 as a total.

**Comment by teddyfresco** [comment]
Seems ok now
