### ISSUE TITLE
Tippabgabe ohne Projektauswahl

### ISSUE THREAD

**Issue by ako87** [diddipoeler/sportsmanagement#319]
Bei der vorherigen Version (ich glaub 1.0.50) konnte man durch den Menüeintrag "Tippabgabe" direkt die Tipps abgegeben. Nun muss man immer zunächst ein Projekt auswählen, bevor die Tipps eingegeben werden können. Auch wenn nur ein Projekt besteht.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
