### ISSUE TITLE
Error view on create a new League

### ISSUE THREAD

**Issue by vieri** [diddipoeler/sportsmanagement#323]
When I push a green button to creat a new league, a blank screen with a plain form and this error appears:

Fatal error: Call to undefined function curl_init() in /var/www/html/joomla/components/com_sportsmanagement/helpers/countries.php on line 283

![jsm](https://cloud.githubusercontent.com/assets/1792732/16989645/48892b50-4e95-11e6-8a84-b2cb917defb4.png)

**Comment by diddipoeler** [comment]
which php version ?

**Comment by diddipoeler** [comment]
please try again.

**Comment by vieri** [comment]
PHP 5.6.23

**Comment by diddipoeler** [comment]
please try again.

**Comment by vieri** [comment]
Reinstall the component ?

**Comment by diddipoeler** [comment]
yes or make an update !

**Comment by vieri** [comment]
How I can update the component withou reinstall ?

**Comment by vieri** [comment]
Now it's working !
