### ISSUE TITLE
Creation of new leagues Backend-View: leagues Layout: default 

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#324]
Creation of new league leads to a blank page, whether I hit "save", "save and close" or "save and new".
Despite this leagues are created, so it's a minor bug, but checks for mandatory fields aren't done: I can create new leagues without name, short name or sport (empty leagues are possible).

**Comment by diddipoeler** [comment]
please try again.

**Comment by teddyfresco** [comment]
It works ok now, still no check is done on sport type, despite being marked as mandatory. Is it ok? Please tell me so I can close the bug

**Comment by diddipoeler** [comment]
please try again.

**Comment by teddyfresco** [comment]
Corrected!
