### ISSUE TITLE
Assigning persons to a team doesn't work

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#325]
Project created, teams assigned, I go to assign persons and assign all the 5 persons I've created. When I hit save and close no player is visible, despite them being counted (5) beside the icon on their team in teams page.
Trying again to assign persons is useless, they are disappeared.
When I create new games, they are nowhere to be seen, so it seems consistently a bug.
I'm on last version and J3.6, php 5.5.34

**Comment by teddyfresco** [comment]
Still, assigned team members aren't displayed or selectable neither on match views nor in team view, can you reproduce this bug?

**Comment by teddyfresco** [comment]
Tried also through season assignment: it seemed to work, there is an increased counter beside team page's icon, but the actual team page doesn't show anything, nor does the match page to assign events.

**Comment by diddipoeler** [comment]
please try again.

**Comment by teddyfresco** [comment]
Diddi, now it's difficult because I've reinstalled (dumping db tables) 2 times and behaviour is different.
- First time, created season, league (without country set), clubs, teams, persons, projects, then went to assign but the result was the same blank page. Then went to assign the league to a country, according to "Der Liga ist kein Land zugeordnet!", went back to person assignment and suddenly, after a couple of seconds, players appeared!! So went to see if a second time the process worked
- Second install, after db dump and reinstall, repeated the whole process without country set on league and , it was expected, no players assignment was visible, but...
even after assigning the league to a country the thing worked, this time I also had to assign clubs to  the same country!!
So, my thought is that it works, but maybe you have to set mandatory the country selection before saving clubs and leagues... but what happens on leagues with teams from several countries?

**Comment by teddyfresco** [comment]
It seems it was my fault, I did not assign positions correctly on project settings.
