### ISSUE TITLE
Check on mandatory club assignment not done on team creation

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#327]
At least I suppose it should be mandatory, theres'an asterisk beside.
This check is not done!
More, the sport type is not mandatory, and there's not even an asterisk, is it correct?

**Comment by diddipoeler** [comment]
please try again.

**Comment by teddyfresco** [comment]
It's still possible to create a team without sport type and club assignment

**Comment by diddipoeler** [comment]
please try again.

**Comment by teddyfresco** [comment]
I confirm, you've done it!!!!!!
