### ISSUE TITLE
Check on mandatory sport type assignment not done on person creation

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#328]
Creating a person, a check on mandatory sport type assignment is not done, saving is possible without sport type.

**Comment by diddipoeler** [comment]
please try again.

**Comment by teddyfresco** [comment]
It's still possible to create a team without sport type assignment

**Comment by diddipoeler** [comment]
please try again.

**Comment by teddyfresco** [comment]
I confirm, you've done it!!!!!!
