### ISSUE TITLE
Impossible to add events to a match

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#335]
In a newly created project (last dev version, J3.6), when people try to add events to a match, there's this error displayed:
"Bitte weisen Sie dem Projekt zunächst Ereignisse zu den Positionen zu"
But there's no way to assign events to positions anywhere (at least I don't know any, please specify one if there is)

**Comment by teddyfresco** [comment]
As you notice on #344 I've found a new way (maybe it was my fault and not a bug, but still it seems not fully working) adding events to a match.
So now players and events show up correctly, but when I hit save
http://awesomescreenshot.com/0df639j453
a loading circle goes on and on and events are not added.
So a good evolution, but still no events...

**Comment by diddipoeler** [comment]
please try again

**Comment by teddyfresco** [comment]
Tried twice, on my 5.5 and 5.6 environments (Joomla3.6.2).
Now there's a problem related with #344 
 - if I try to add events to positions, they are duplicated after save, with events assigned only to the new item. I have to unpublish the old one, because it is also impossible to remove (should I add a new issue telling you positions cannot be removed? they look like, but if you go to another page and come back to positions, it reappears!!), in this case it allows to go on.

- when I add events now they seem to be saved on the popup like this (only lang keys are displayed, not translations, just a note), without info on value and time:
http://awesomescreenshot.com/0c363fwj0d
but when I close it and try to check if  they have been recorded, they don't show up, it seems they are not saved even if I click save on matches layout.
I'd gladly check on matchreport frontend page, but matchrep menu item does not save the selection to the match and it's impossible to see it on the online site.

Little request: it would be nice to remove the mandatory time for events, in many cases people don't remember or don't want (or don't have time to do it :-) to report the timing. Now if I try to save without time I get:
COM_SPORTSMANAGEMENT_ADMIN_MATCH_CTRL_ERROR_SAVED_EVENT: COM_SPORTSMANAGEMENT_ADMIN_MATCH_MODEL_EVENT_NO_TIME

**Comment by teddyfresco** [comment]
Looking at substitutions (they work!) for comparison, it seems the events popup lacks a "save" button on top, could it be the key for a solution?
And events have only numbers in them, making difficult to distinguish...
![events](https://cloud.githubusercontent.com/assets/18396229/18187255/5d705608-70a8-11e6-839a-c65af0bb5112.jpg)

**Comment by svdoldie** [comment]
Speichern kann man die Ereignisse mit dem Button ganz auf der rechten Seite. 
Allerdings werden die gespeicherten Ereignisse nicht mehr angezeigt, wenn man später etwas korrigieren möchte

**Comment by teddyfresco** [comment]
svdoldie, please, look at the image above:
do you see the second arrow, below? It indicates an event (the one marked on the left by a "1", other details are left out) saved with the "Save" button you probably meant.
You can see that button on the image attached
![rightevents](https://cloud.githubusercontent.com/assets/18396229/18196921/acfe2956-70f4-11e6-90b6-692f1d419477.png)
Once I've added my events, what should I do? Hitting again that save button adds other events, closing the modal windows does not store events: they don't show up the next time I open that modal page.

**Comment by svdoldie** [comment]
Ja, das ist richtig. Wenn man das Fenster erneut öffnet, werden die Ereignisse nicht mehr angezeigt. Sie sind aber gespeichert worden, jedenfalls werden sie in der Kaderanzeige dargestellt. Merkwürdigerweise aber nicht in der Spieleransicht.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :+1:
