### ISSUE TITLE
JSM - Module Matches

### ISSUE THREAD

**Issue by shortbrother** [diddipoeler/sportsmanagement#337]
Das JSM - Module Matches zeigt bei allen möglichen Einstellungen nur das erste oder letzte Spiel an, egal ob bereits gespielt oder nicht.

**Comment by svdoldie** [comment]
Bei mir werden keine Icons angezeigt, obwohl eine Auswahl gespeichert ist

**Comment by svdoldie** [comment]
Irgendwie werden für die Icons falsche Links erzeugt, deshalb werden die wahrscheinlich auch nicht angezeigt. Ein Beispiel:  http://svdoerpum.de/modules/mod_sportsmanagement_matches/assets/images/var/…de/modules/mod_sportsmanagement_matches/assets/images/white_grey/house.png

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by svdoldie** [comment]
Das Modul zeigt jetzt die richtigen Spiele an! :-)
Aber das Problem mit den Symbolen existiert noch

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft!!! :-)
