### ISSUE TITLE
Backend-View: template Layout: edit

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#341]
Joomla 3.6.2 - JSM Version aus GitHub
Beim Speichern eines Templates wird ein neues Objekt in der DB erstellt.
Änderungen die im Template gemacht wurden, sind in diesem Objekt nicht vorhanden.
Scheint so, als ob eine Kopie des geöffneten Template erstellt wird.

Das heißt, momentan können keine Änderungen in den Templates vorgenommen werden. Es wird nur die DB vergrößert.

![Image of stony's screenshot]http://jsm.stony-sport4u.de/images/screenshots/templates.png)

JS-File wird nicht eingebunden!
Siehe:
Google Chrome Console:
![Image2 of stony's screenshot]https://www.diigo.com/file/image/spdpaddzdcpdeeabazcdsrdadb/template.jpg)

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :-)
