### ISSUE TITLE
Adding events to master positions adds events to a duplicated (new) position

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#344]
Hi, I wen to add events to already existent master positions, and hit save and close. 
The original position was still there, unchanged and without events.
An almost exact copy (with higher ID and without secondary position) was added, this one with events assigned.
Obviously when adding positions to players it was impossible to distinguish (eg both displayed as "midfielder" in the list) between the two, so I unpublished the old one, and it seems to be working, but I suspect it is not the correct behaviour, especially if you look at #335 new comment

**Comment by teddyfresco** [comment]
This bug could be overcome by adding totally new positions and removing ones set on db by the extension on installation, so I wonder if default positions could be removed by default...
In any case it's a bug, replicated locally on php 5.6.20, and online on 5.5.36, both using Joomla 3.6.2, and installing a fresh JSM on empty db.

**Comment by diddipoeler** [comment]
Ich habe den Bug nach 2 Tagen intensiver Suche gefunden.
Eigentlich ganz einfach.
Vielleicht schaffe ich es heute Abend die Änderungen hochzuladen.

**Comment by teddyfresco** [comment]
Super! Sag mir Bescheid

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by teddyfresco** [comment]
Tested and it works!
I could close the issue, but there's still a glitch: positions are locked, when you see them in positions layout, after saving them.
Should I close it anyway and start a new issue?

**Comment by svdoldie** [comment]
läuft :-)
