### ISSUE TITLE
Backend-View: template Layout: Player

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#348]
Der Todestag lässt sich nicht abstellen, oder ich

**Comment by diddipoeler** [comment]
wie soll ich das verstehen ?

**Comment by svdoldie** [comment]
oh, da fehlt das ... bin blind ;-)

**Comment by diddipoeler** [comment]
wie meinst du das abstellen ?

**Comment by svdoldie** [comment]
Es wird immer der Todestag mit angezeigt. Das kann man nicht abschalten
http://svdoerpum.de/junioren/c-jugend/player/0/1/5-c-junioren-kreisklasse-2016-17/63-sv-doerpum-09/388-kim-luca-prochnow

**Comment by diddipoeler** [comment]
im player-template kannst du das jetzt einstellen.

**Comment by svdoldie** [comment]
läuft :-)
