### ISSUE TITLE
Projects don't show up in projects view

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#355]
Tried to create a new project, it seems successful, but the projects layout is empty.
Then tried with another, same name: an error came out saying the project already exist, so it seems they are saved but do not appear.

**Comment by sigal** [comment]
That's not exactly correct.
Go to Templates and click on the column 'template file' (Sort)
Now all the templates are shown.  :boom:

**Comment by teddyfresco** [comment]
Sigal, I was talking about projects layout, does it have anything to do with templates?
I mean, this view:
index.php?option=com_sportsmanagement&view=projects
In any way, going back to the site from home, I can see the project I created.
Reinstalled the whole thing, and now everything works ok.
