### ISSUE TITLE
save and new on new teams leads to a blank page

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#356]
When I hit save and new on creating a new team I've been greeted by a blank page, but actually teams get added.

**Comment by teddyfresco** [comment]
Tested now, and it seems not even the other save buttons work...
All lead to a blank page, they save the team correctly, but without season for some reason.
Even getting back in does not allow to save the season.

**Comment by sigal** [comment]
Wait until diddi accepts the change.

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by teddyfresco** [comment]
Bug erledigt
