### ISSUE TITLE
Frontend-View: template Layout: Matchreport

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#358]
Die Timeline wird nicht angezeigt, obwohl  sie eingeschaltet ist und auch Ereignisse gespeichert sind. Zudem werden einige Inhalte nicht angezeigt, wenn Tabs als anzeigeformat gewählt worden ist.
siehe : http://svdoerpum.de/component/sportsmanagement/matchreport/0/0/1-kreisliga-2016-17/7-sv-doerpum_tsv-rantrum-ii

**Comment by teddyfresco** [comment]
I can confirm, I tried with all possible layout on a bootstrap joomla template, but events are nowhere to be seen in frontend.
As well as in backend, then maybe linked with #335

**Comment by svdoldie** [comment]
Außerdem werden im Matchreport die Ereignisse nicht angezeigt und die Aufstellung im Spielfeld wird nicht vollständig angezeigt.

**Comment by PhantoSGE** [comment]
Es ist nicht möglich das Spielfeld auszuschalten.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Aktueller Stand:
+ Spielfeld lässt sich abschalten
+ Timeline wird angezeigt
- Torhüter werden in der Aufstellung nicht angezeigt
- ich bekomme es noch nicht hin die Spieler ins Spielfeld zu bringen

**Comment by diddipoeler** [comment]
Ich habe die Spieler im Spielfeld:
http://www.fussballineuropa.de/index.php/component/sportsmanagement/matchreport/0/0/13-1-bundesliga-1999-00/23825-fc-gelsenkirchen-schalke-04-e-v-i_dsc-arminia-bielefeld-1905-e-v-i

**Comment by svdoldie** [comment]
bei alten Projekten werden sie mir auch angezeigt, allerdings nicht in aktuellen

**Comment by svdoldie** [comment]
scheint jetzt alles zu laufen 👍
