### ISSUE TITLE
Kalendermodul zeigt Spiele nur an, wenn sie einmal gespeichert worden sind

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#359]
Kalendermodul zeigt Spiele nur an, wenn sie einmal gespeichert worden sind.
Das reine angeben der Projekte reicht nicht aus.

**Comment by diddipoeler** [comment]
ich hatte vergessen dir mitzuteien, dass ich den timestamp neu eingeführt habe.
mach mal bitte ein update der komponente.
danach in der standardansicht der komponente den button updates anklicken.
dann den button: jsm_update_timestamp.php anklicken.
jetzt die Projekte und spiele aktualisieren.

**Comment by svdoldie** [comment]
Hab ich alles in der Reihenfolge gemacht, gebracht hat es allerdings nichts. 
Es wird auch kein Datum in der Spalte "ausgeführt am" angezeigt

**Comment by svdoldie** [comment]
läuft jetzt :-)
