### ISSUE TITLE
Modul Trainingszeiten - Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#360]
Das Trainingsmodul erzeugt folgende Fehlermeldung: 
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':sv-doerpum ORDER BY dayofweek ASC' at line 3 SQL=SELECT * FROM #__sportsmanagement_team_trainingdata WHERE team_id = 13:sv-doerpum ORDER BY dayofweek ASC

Evtl. hängt es damit zusammen, das nach Auswahl der Saison und des Projekts keine Teams angezeigt werden. Erst nach Speichern der Einstellungen werden die Teams angezeigt. Nach Auswahl eines Teams und nochmaligen Speichern erscheint im Frontend das die Fehlermeldung.

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :-)
