### ISSUE TITLE
Substitutions Backend-View: matches Layout: default

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#361]
Something is wrong with substitutions:
1 A player can enter the field more than one time, look at the image:
![sports managementsubst](https://cloud.githubusercontent.com/assets/18396229/18247466/fed21b04-7372-11e6-99e9-e43fb1c04ff1.png)
When I save, in backend only one substitution is correctly shown
http://awesomescreenshot.com/0d6648hw3e
But
a- in backend matches view, starting from 2 players and after making 2 substitutions, 4 players are listed
http://awesomescreenshot.com/09f648i217
b- in frontend, look at this image
http://awesomescreenshot.com/06f648imd1
two substitutions with player "eee" are listed

**Comment by svdoldie** [comment]
Momentan werden die Auswechselungen gar nicht gespeichert, es läuft dauerhaft dieses kleine Rädchen

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :+1:
