### ISSUE TITLE
View Playground erzeugt weiße Seite

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#362]
DIe Ansicht Playground erzeugt eine weiße Seite, mit folgender Fehlermeldung:
Fatal error: Using $this when not in object context in /var/www/vhosts/svdoldie.stony-sport4u.de/httpdocs/administrator/components/com_sportsmanagement/models/teams.php on line 253

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by teddyfresco** [comment]
Jestzt getestet am Frontend: bekomme eine weisse Seite. Ist ok im Backend

**Comment by svdoldie** [comment]
Fehler existiert noch

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by teddyfresco** [comment]
jetzt es sieht ok aus

**Comment by sigal** [comment]
läuft :smile:
