### ISSUE TITLE
Tipps während des laufenden Spiels noch änderbar

### ISSUE THREAD

**Issue by mignetic** [diddipoeler/sportsmanagement#363]
Die Tipps können bei mir noch geändert werden, während das Spiel läuft.

**Comment by mignetic** [comment]
Es ist immer noch der Fall, dass die Spiele geändert werden können, obwohl das Spiel bereits läuft.
Auch die Tipps werden nicht angezeigt.

**Comment by mignetic** [comment]
Brauche dringend Hilfe!!!

**Comment by svdoldie** [comment]
welche Zeit ist in deiner Joomla-Konfiguration eingestellt?

**Comment by mignetic** [comment]
Koordinierte weltzeit.

Da Berlin für 2 Std. Verspätung im Tippspiel sorgt

 

 

 

Mit freundlichen Grüßen

Miguel Gonzales-Tounsi

 

miguel.gonzales@arcor.de

 

Von: svdoldie [mailto:notifications@github.com] 
Gesendet: Freitag, 9. September 2016 23:39
An: diddipoeler/sportsmanagement <sportsmanagement@noreply.github.com>
Cc: mignetic <miguel.gonzales@arcor.de>; Author <author@noreply.github.com>
Betreff: Re: [diddipoeler/sportsmanagement] Tipps während des laufenden Spiels noch änderbar (#363)

 

welche Zeit ist in deiner Joomla-Konfiguration eingestellt?

**Comment by mignetic** [comment]
Ich kann dir ja mal meine Daten für den Admin-Bereich geben…

 

 

 

Mit freundlichen Grüßen

Miguel Gonzales-Tounsi

 

miguel.gonzales@arcor.de

 

Von: svdoldie [mailto:notifications@github.com] 
Gesendet: Freitag, 9. September 2016 23:39
An: diddipoeler/sportsmanagement <sportsmanagement@noreply.github.com>
Cc: mignetic <miguel.gonzales@arcor.de>; Author <author@noreply.github.com>
Betreff: Re: [diddipoeler/sportsmanagement] Tipps während des laufenden Spiels noch änderbar (#363)

 

welche Zeit ist in deiner Joomla-Konfiguration eingestellt?

**Comment by svdoldie** [comment]
Meine Mailadresse ist svdoldie@gmx.de

**Comment by mignetic** [comment]
Das liegt an der Serverzeit! Stelle ich die Server-Zeit auf Berlin ein geht die Anstoss-Zeit 2 Std nach hinten.

**Comment by mignetic** [comment]
Erledigt, läuft jetzt, nachdem ich in der index.php
(setlocale(LC_ALL, 'de_DE');
date_default_timezone_set('Europe/Berlin');
eingegeben habe.
