### ISSUE TITLE
Tippspiel Erinnerung wird nicht versendet

### ISSUE THREAD

**Issue by mignetic** [diddipoeler/sportsmanagement#365]
Es wird keine Erinnerung versendet, Fehler: Message Body empty

**Comment by diddipoeler** [comment]
Geh mal bitte in die Konfiguration der Komponente und speicher die Einstellungen.

**Comment by mignetic** [comment]
Wo mache ich das? Habe grad echt nen Blackout...

**Comment by mignetic** [comment]
So, danke, habs hinbekommen... Es geht, vielen Dank!!!
