### ISSUE TITLE
View Playground - kleine Fehler

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#366]
In der Ansicht Playground gibte es noch ein paar kleinere Fehler:
- bei der Anzeige der Spiele werden nur die aus dem 1. Projekt angezeigt.
- Google Maps erzeugt nur ein graues Feld, obwohl bei der Ansicht Clubinfo die Karte angezeigt wird.
  das gleiche gild übrigens auch für die Ansicht Ranking

siehe http://svdoerpum.de/verein/playground/0/1/1-kreisliga-2016-17/7-a-platz-doerpum
und http://svdoerpum.de/senioren/1-herren/tabelle
und http://svdoerpum.de/verein
![playground](https://cloud.githubusercontent.com/assets/2417767/18301427/8fac3d94-74d1-11e6-8f7b-c3b87f0eaffb.PNG)

**Comment by sigal** [comment]
playground: das stimmt so nicht->http://jsm.stony-sport4u.de/index.php?option=com_sportsmanagement&view=playground&cfg_which_database=0&s=0&p=3:st-oberliga-nord-2009-10&pgid=73:sportzentrum-stadion-knittelfeld&Itemid=942

Google Maps: wie wäre es, das plugin google maps zu konfigurieren? ->http://jsm.stony-sport4u.de/index.php?option=com_sportsmanagement&view=ranking&cfg_which_database=0&s=25:2015-16&p=923:st-oberliga-nord-2015-16&type=0&Itemid=961

und http://jsm.stony-sport4u.de/index.php?option=com_sportsmanagement&view=clubinfo&cfg_which_database=0&s=0&p=987:st-oberliga-nord-2016-17&cid=17:esv-knittelfeld&Itemid=1529

lass mich aber eines besseren belehren. :open_mouth:

**Comment by svdoldie** [comment]
Hmm, kann ich versuchen. Ich dachte nur, wenn in einer Ansicht geht, müsste es auch in den anderen gehen... ;-)

**Comment by svdoldie** [comment]
Ich bin wohl zu blöd. Kannst du mir bitte mal die wichtigsten Punkte nennen...

**Comment by sigal** [comment]
Einstellung Plugin "System - Google Maps": TAB KML (GeoXML) settings:
KML renderer->GeoXML wählen
KML Sidebar width: Würde ich zwischen 100 - 150 wählen

Zur Anzeige von verschieden Saisonen (Projekten) in der Playgroundansicht müssen in den Projekten in der Ansicht Projektmannschaften explizit jeder Mannschaft eine Sportstätte zugewiesen werden.

Warum ist das so? Nur so wird garantiert das jeder Mannschaft eine Sportstätte pro Saison zugewiesen wird. Das hat nichts mit der Zuweisung einer Sportstätte zum Verein zu tun. (vermutlich hast du schon in JL2 der Projektmannschaft keine Sportstätte zugewiesen, und beim Import werden die Einstellungen von JL2 übernommen). Muß gestehen, dass auch ich nicht immer den Projektmannschaften ihre Sportstätte zugewiesen habe.

Wenn man bedenkt, dass ein Verein die eigene Sportstätte renoviert oder neu baut, muss die Mannschaft auf einer fremden Sportstätte seine Spiele austragen. Würde nun jeder Mannschaft automatisch die Vereinssportstätte zugewiesen, würde bei der Spielevorschau immer eine falsche Sportstätte aufscheinen. Auch bei älteren Projekten würde z.B. eine "falsche" Sportstätte aufscheinen, wenn der Verein eine neue Sportstätte gebaut, oder übersiedelt wäre.

Also in Zukunft immer bei den Projektmannschaften eine Sportstätte zuweisen!

Es besteht aber noch die Möglichkeit, im Projekt unter "Spiele bearbeiten", jeder Heimmannschaft einen anderen Sportplatz zuzuweisen.

Merke! Wenn kein Sportstätte zugewiesen, wird auch kein Map angezeigt!

So, nun hab ich meinen Aufsatz für heute beendet.
Und mit Blödheit hat deine Fragestellung nichts zu tun!

**Comment by svdoldie** [comment]
Danke Stony. Aber in den Projekten sind unseren Mannschaften jeweils eine Sportstätte zugewiesen. Und die Einstellungen für das Google-Maps-Plugin hatte ich auch schon so eingestellt. Trotzdem wird bei mir ausschließlich in der Vereinsinfo-Ansicht die Karte dargestellt, sonst nur ein graues Fenster.

**Comment by diddipoeler** [comment]
schau mal bitte in den stammdaten der spielstätten.
sind die Latitude und Longitude generiert ?
wenn da nichts oder 255 steht, zeigt er auch keine karte.

**Comment by svdoldie** [comment]
Ist auch alles vorhanden , die Karte wird bei den Sportstätten im Backend auch angezeigt

**Comment by sigal** [comment]
Auch mit nochmaligen speichern probiert? (Sportstätten)

**Comment by svdoldie** [comment]
Klar ;-) Bringt aber leider auch nichts

**Comment by sigal** [comment]
So Hauke. Plugin System - Google Maps deinstallieren und neu installieren.
Keine Einstellungen ändern, außer die von mir geposteten.

Sehe im Seitenquelltext eurer Seite falsch konfiguriertes Plugin!

Dass es funktioniert siehst du hier: http://jsm.stony-sport4u.de/index.php?option=com_sportsmanagement&view=playground&cfg_which_database=0&s=0&p=1014:kreisklasse-b-nord-2013-2014&pgid=481:a-platz-doerpum&Itemid=885

Oder: http://jsm.stony-sport4u.de/index.php?option=com_sportsmanagement&view=ranking&cfg_which_database=0&s=0&p=1014:kreisklasse-b-nord-2013-2014&type=0&r=0&from=0&to=0&division=0&Itemid=885

No Fake!

Auf ein Neues!

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft 👍 
vielleicht könnte man bei den ausgetragenden Spielen noch das Ergebnis mit anzeigen lassen,
ist aber kein muss

**Comment by svdoldie** [comment]
und unter optionen kann hat man die Möglichkeit sich ein Anfahrtsformular anzeigen zu lassen.
Dies Möglichkeit existiert nicht, oder wird nicht dargestellt

**Comment by diddipoeler** [comment]
So, jetzt mit Ergebnisse.

**Comment by svdoldie** [comment]
Läuft 👍
