### ISSUE TITLE
Import Pressebericht erzeugt weiße Seite

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#367]
Wenn man einen Pressebericht hochladen möchte erscheint eine Weiße Seite mit folgender Fehlermeldung:

Notice: Use of undefined constant Spielberichtsnummer - assumed 'Spielberichtsnummer' in /var/www/vhosts/svdoerpum.de/svdoerpum.de/administrator/components/com_sportsmanagement/models/match.php on line 2673

Warning: Creating default object from empty value in /var/www/vhosts/svdoerpum.de/svdoerpum.de/administrator/components/com_sportsmanagement/models/match.php on line 2758

Catchable fatal error: Object of class JDatabaseDriverMysqli could not be converted to string in /var/www/vhosts/svdoerpum.de/svdoerpum.de/administrator/components/com_sportsmanagement/models/match.php on line 2782

**Comment by tdit** [comment]
Habe bei mir auch mal einen Import versucht. Die Meldung "Spielnummer ist identisch" wird angezeigt, darunter eine Tabelle mit den folgenden Spalten:

`Spielnummer	Vorname	Nachname	In der Datenbank ?	Projektteam zugeordnet ?	Projektposition
Staff Position	Vorname	Nachname	In der Datenbank ?	Projektteam zugeordnet ?	Projektposition
Spieler	Minute	R�ckennummer	f�r Nummer	f�r Spieler	Projektposition
Spieler	Minute	Karte	R�ckennummer	Grund	In der Datenbank ?	Event` 

Wenn ich anschließend auf den Save-Button klicke kommt bei mir folgende Fehlermeldung:

`Layout „savepressebericht_3“ nicht gefunden!`

**Comment by diddipoeler** [comment]
Kannst du bitte mal eine Datei mit einem Pressebericht hier anhängen ?
Ich arbeite nämlich nicht mit den Presseberichten.

**Comment by tdit** [comment]
Natürlich: 

Spielberichtsnummer;Bearbeitungsstatus;Bearbeiter;Hinweise-Fehler;Liganame;Spieltag;Spielnummer;Spieltyp;Spieldatum;Anstoﬂzeit;Stadion;Ort;Schiedsrichter;Assistent-1;Assistent-2;Vierter-Offizieller;Heimmannschaft;H-Trainer;H-Trainerassistent;H-Arzt;H-Masseur;H-Zeugwart;H-Mannschaftsverantwortlicher;H-Erster-Offizieller;H-Zweiter-Offizieller;H-Doping-Beauftragter;H-S1-Nr;H-S1-Spieler;H-S1-Hinweis;H-S1-Status;H-S2-Nr;H-S2-Spieler;H-S2-Hinweis;H-S2-Status;H-S3-Nr;H-S3-Spieler;H-S3-Hinweis;H-S3-Status;H-S4-Nr;H-S4-Spieler;H-S4-Hinweis;H-S4-Status;H-S5-Nr;H-S5-Spieler;H-S5-Hinweis;H-S5-Status;H-S6-Nr;H-S6-Spieler;H-S6-Hinweis;H-S6-Status;H-S7-Nr;H-S7-Spieler;H-S7-Hinweis;H-S7-Status;H-S8-Nr;H-S8-Spieler;H-S8-Hinweis;H-S8-Status;H-S9-Nr;H-S9-Spieler;H-S9-Hinweis;H-S9-Status;H-S10-Nr;H-S10-Spieler;H-S10-Hinweis;H-S10-Status;H-S11-Nr;H-S11-Spieler;H-S11-Hinweis;H-S11-Status;H-A1-Nr;H-A1-Spieler;H-A1-Hinweis;H-A1-Status;H-A2-Nr;H-A2-Spieler;H-A2-Hinweis;H-A2-Status;H-A3-Nr;H-A3-Spieler;H-A3-Hinweis;H-A3-Status;H-A4-Nr;H-A4-Spieler;H-A4-Hinweis;H-A4-Status;H-A5-Nr;H-A5-Spieler;H-A5-Hinweis;H-A5-Status;H-A6-Nr;H-A6-Spieler;H-A6-Hinweis;H-A6-Status;H-A7-Nr;H-A7-Spieler;H-A7-Hinweis;H-A7-Status;Gastmannschaft;G-Trainer;G-Trainerassistent;G-Arzt;G-Masseur;G-Zeugwart;G-Mannschaftsverantwortlicher;G-Erster-Offizieller;G-Zweiter-Offizieller;G-Doping-Beauftragter;G-S1-Nr;G-S1-Spieler;G-S1-Hinweis;G-S1-Status;G-S2-Nr;G-S2-Spieler;G-S2-Hinweis;G-S2-Status;G-S3-Nr;G-S3-Spieler;G-S3-Hinweis;G-S3-Status;G-S4-Nr;G-S4-Spieler;G-S4-Hinweis;G-S4-Status;G-S5-Nr;G-S5-Spieler;G-S5-Hinweis;G-S5-Status;G-S6-Nr;G-S6-Spieler;G-S6-Hinweis;G-S6-Status;G-S7-Nr;G-S7-Spieler;G-S7-Hinweis;G-S7-Status;G-S8-Nr;G-S8-Spieler;G-S8-Hinweis;G-S8-Status;G-S9-Nr;G-S9-Spieler;G-S9-Hinweis;G-S9-Status;G-S10-Nr;G-S10-Spieler;G-S10-Hinweis;G-S10-Status;G-S11-Nr;G-S11-Spieler;G-S11-Hinweis;G-S11-Status;G-A1-Nr;G-A1-Spieler;G-A1-Hinweis;G-A1-Status;G-A2-Nr;G-A2-Spieler;G-A2-Hinweis;G-A2-Status;G-A3-Nr;G-A3-Spieler;G-A3-Hinweis;G-A3-Status;G-A4-Nr;G-A4-Spieler;G-A4-Hinweis;G-A4-Status;G-A5-Nr;G-A5-Spieler;G-A5-Hinweis;G-A5-Status;G-A6-Nr;G-A6-Spieler;G-A6-Hinweis;G-A6-Status;G-A7-Nr;G-A7-Spieler;G-A7-Hinweis;G-A7-Status;Kontrollname-1;Kontrollergebnis-1;Kontrollname-2;Kontrollergebnis-2;Kontrollname-3;Kontrollergebnis-3;Kontrollname-4;Kontrollergebnis-4;Spielbeginn;Spielende;Nachspielzeit-1.HZ;Nachspielzeit-2.HZ;Halbzeitergebnis;Endergebnis;H-S1-Ausw-Zeit;H-S1-Ausw-Nr;H-S1-Ausw-Spieler;H-S1-Ausw-F¸r Nr;H-S1-Ausw-f¸r-Spieler;H-S2-Ausw-Zeit;H-S2-Ausw-Nr;H-S2-Ausw-Spieler;H-S2-Ausw-F¸r Nr;H-S2-Ausw-f¸r-Spieler;H-S3-Ausw-Zeit;H-S3-Ausw-Nr;H-S3-Ausw-Spieler;H-S3-Ausw-F¸r Nr;H-S3-Ausw-f¸r-Spieler;H-S4-Ausw-Zeit;H-S4-Ausw-Nr;H-S4-Ausw-Spieler;H-S4-Ausw-F¸r Nr;H-S4-Ausw-f¸r-Spieler;H-S1-Gelb-Zeit;H-S1-Gelb-Nr;H-S1-Gelb-Spieler;H-S1-Gelb-Grund;H-S2-Gelb-Zeit;H-S2-Gelb-Nr;H-S2-Gelb-Spieler;H-S2-Gelb-Grund;H-S3-Gelb-Zeit;H-S3-Gelb-Nr;H-S3-Gelb-Spieler;H-S3-Gelb-Grund;H-S4-Gelb-Zeit;H-S4-Gelb-Nr;H-S4-Gelb-Spieler;H-S4-Gelb-Grund;G-S1-Ausw-Zeit;G-S1-Ausw-Nr;G-S1-Ausw-Spieler;G-S1-Ausw-F¸r Nr;G-S1-Ausw-f¸r-Spieler;G-S2-Ausw-Zeit;G-S2-Ausw-Nr;G-S2-Ausw-Spieler;G-S2-Ausw-F¸r Nr;G-S2-Ausw-f¸r-Spieler;G-S3-Ausw-Zeit;G-S3-Ausw-Nr;G-S3-Ausw-Spieler;G-S3-Ausw-F¸r Nr;G-S3-Ausw-f¸r-Spieler;G-S4-Ausw-Zeit;G-S4-Ausw-Nr;G-S4-Ausw-Spieler;G-S4-Ausw-F¸r Nr;G-S4-Ausw-f¸r-Spieler;G-S1-Gelb-Zeit;G-S1-Gelb-Nr;G-S1-Gelb-Spieler;G-S1-Gelb-Grund;G-S2-Gelb-Zeit;G-S2-Gelb-Nr;G-S2-Gelb-Spieler;G-S2-Gelb-Grund;Vorkommnisse;Faires-Verhalten;
"350639113.00.00";"Pr¸ferfreigabe";"35011527/04.12.2016 18:03";;"Kreisliga B";"15";"113";"Meisterschaft";"04.12.2016";"14:00";"Dahenfeld Kunstrasen";"Neckarsulm";"Karl-Heinz M¸hleck (Lauda-Kˆnigshofen)";;;;"SC Dahenfeld";"Wˆhr, Matthias";"Seitz,Werner";;"Kruck,J¸rgen";;"Lohmann,Ralf";;;;"1";"Roth, Patrick";"TW";"VS/A";"2";"Weiﬂ, Gerrit";;"VS/A";"3";"Korb, Christopher";;"VS/A";"4";"Halter, Jonas";;"VS/A";"5";"Wˆhr, Matthias";;"VS/A";"6";"Kˆrner, Timo";;"VS/A";"7";"H‰uﬂler, Christoph";;"VS/A";"9";"Z¸rn, Dennis";;"VS/A";"10";"Leitz, Dennis";;"VS/A";"11";"Seidl, Robin";;"VS/A";"14";"Roth, Marco";"C";"VS/A";"25";"Habla, Sebastian";"ETW";"VS/A";"8";"K¸hner, Jacob";;"VS/A";"12";"G¸ls¸n, Muharrem";;"VS/A";"13";"Roder, Lennart";;"VS/A";"15";"Schiemer, Tim";;"VS/A";;;;;;;;;"FC Mˆckm¸hl";"Hofmann, Michael";;;;;"Saud Kapur";;;;"23";"Ott, Bernhard";"TW";"VS/A";"2";"Heimerdinger, Steve";;"VS/A";"4";"Reile, Siegfried";;"VS/A";"5";"Ott, Ralf";;"VS/A";"6";"Elert, Stefan";;"VS/A";"7";"Baidin, Dimitri";;"VS/A";"8";"Adelmann, Dennis";;"VS/A";"9";"Marwan, Ahmed";;"VS/A";"10";"Kapur, Saud";;"VS/A";"14";"Mohr, Alexander";"C";"VS/A";"17";"Braun, Eduard";;"VS/A";"3";"Meisler, Waldemar";;"VS/A";"11";"Emert, Andy";;"VS/A";"12";"Emert, Benjamin";;"VS/A";"13";"Demiri, Ljutfi";;"VS/A";"16";"Fuchs, Martin";;"VS/A";;;;;;;;;"Schuhe";"i.O.";"Spielfeld";"i.O.";"Spielerp‰sse";"i.O.";"Trikotwerbung";"i.O.";"14:00";"15:51";"2";"4";"1:2";"1:3";"56";"12";"G¸ls¸n";"7";"H‰uﬂler";"70";"8";"K¸hner";"3";"Korb";;;;;;;;;;;"14";"14";"Roth";"Unsportlichkeit";"36";"6";"Kˆrner";"Foulspiel";"55";"3";"Korb";"Foulspiel";"61";"2";"Weiﬂ";"Unsportlichkeit";"72";"11";"Emert";"9";"Marwan";"77";"13";"Demiri";"5";"Ott";"90";"12";"Emert";"7";"Baidin";;;;;;"50";"5";"Ott";"Unsportlichkeit";"72";"17";"Braun";"Foulspiel";;"Nein";
"350639113.00.00";"Pr¸ferfreigabe";"35011527/04.12.2016 18:03";;"Kreisliga B";"15";"113";"Meisterschaft";"04.12.2016";"14:00";"Dahenfeld Kunstrasen";"Neckarsulm";"Karl-Heinz M¸hleck (Lauda-Kˆnigshofen)";;;;"SC Dahenfeld";"Wˆhr, Matthias";"Seitz,Werner";;"Kruck,J¸rgen";;"Lohmann,Ralf";;;;"1";"Roth, Patrick";"TW";"VS/A";"2";"Weiﬂ, Gerrit";;"VS/A";"3";"Korb, Christopher";;"VS/A";"4";"Halter, Jonas";;"VS/A";"5";"Wˆhr, Matthias";;"VS/A";"6";"Kˆrner, Timo";;"VS/A";"7";"H‰uﬂler, Christoph";;"VS/A";"9";"Z¸rn, Dennis";;"VS/A";"10";"Leitz, Dennis";;"VS/A";"11";"Seidl, Robin";;"VS/A";"14";"Roth, Marco";"C";"VS/A";"25";"Habla, Sebastian";"ETW";"VS/A";"8";"K¸hner, Jacob";;"VS/A";"12";"G¸ls¸n, Muharrem";;"VS/A";"13";"Roder, Lennart";;"VS/A";"15";"Schiemer, Tim";;"VS/A";;;;;;;;;"FC Mˆckm¸hl";"Hofmann, Michael";;;;;"Saud Kapur";;;;"23";"Ott, Bernhard";"TW";"VS/A";"2";"Heimerdinger, Steve";;"VS/A";"4";"Reile, Siegfried";;"VS/A";"5";"Ott, Ralf";;"VS/A";"6";"Elert, Stefan";;"VS/A";"7";"Baidin, Dimitri";;"VS/A";"8";"Adelmann, Dennis";;"VS/A";"9";"Marwan, Ahmed";;"VS/A";"10";"Kapur, Saud";;"VS/A";"14";"Mohr, Alexander";"C";"VS/A";"17";"Braun, Eduard";;"VS/A";"3";"Meisler, Waldemar";;"VS/A";"11";"Emert, Andy";;"VS/A";"12";"Emert, Benjamin";;"VS/A";"13";"Demiri, Ljutfi";;"VS/A";"16";"Fuchs, Martin";;"VS/A";;;;;;;;;"Schuhe";"i.O.";"Spielfeld";"i.O.";"Spielerp‰sse";"i.O.";"Trikotwerbung";"i.O.";"14:00";"15:51";"2";"4";"1:2";"1:3";"56";"12";"G¸ls¸n";"7";"H‰uﬂler";"70";"8";"K¸hner";"3";"Korb";;;;;;;;;;;"14";"14";"Roth";"Unsportlichkeit";"36";"6";"Kˆrner";"Foulspiel";"55";"3";"Korb";"Foulspiel";"61";"2";"Weiﬂ";"Unsportlichkeit";"72";"11";"Emert";"9";"Marwan";"77";"13";"Demiri";"5";"Ott";"90";"12";"Emert";"7";"Baidin";;;;;;"50";"5";"Ott";"Unsportlichkeit";"72";"17";"Braun";"Foulspiel";;"Nein";

**Comment by svdoldie** [comment]
aktuell tritt folgende Fehlermeldung auf: 
1146 Table 'sk13-121152-1_svdoerpumde.#__sportsmanagement' doesn't exist

**Comment by diddipoeler** [comment]
Kannst Du mir mal bitte eine Datei per Mail zusenden ?

**Comment by svdoldie** [comment]
Ist unterwegs ;-)

**Comment by svdoldie** [comment]
ich habe es gerade nochmal versucht.
Wenn man den Pressebericht hochlädt,
läuft er in einen Time-out Fehler
![bildschirmfoto-4](https://user-images.githubusercontent.com/2417767/36666248-5047953e-1aea-11e8-9d9a-8912ba75f76f.png)

**Comment by diddipoeler** [comment]
Da muss ich noch einiges programmieren !

**Comment by svdoldie** [comment]
Sieht doch schon vielversprechend aus :-)

**Comment by diddipoeler** [comment]
Da stehen sogar die Torschützen:
http://www.kicker.de/news/fussball/amateure/schleswig-holstein-vl-nord-west-fb-1/2017-18/19/4168854/spielschema_sc-weiche-flensburg-08-iii-53216_sv-doerpum-14392.html

**Comment by svdoldie** [comment]
Das ist richtig. Bei Fussball.de gibt's die auch, aber eben nicht in der Exportdatei

**Comment by svdoldie** [comment]
Es gibt auch eine Pressebericht.pdf,
da stehen auch die Torschützen mit drauf.
Wenn man die vorher in eine excel-Datei umwandelt, 
eignet die sich evtl auch zum import
[Pressebericht2-040067008.pdf](https://github.com/diddipoeler/sportsmanagement/files/1768448/Pressebericht2-040067008.pdf)
[Pressebericht2-040067008.xlsx](https://github.com/diddipoeler/sportsmanagement/files/1768452/Pressebericht2-040067008.xlsx)

**Comment by diddipoeler** [comment]
Leider kann ich in der Datei des Presseberichtes nicht erkennen, wer in
der Startaufstellung steht.

**Comment by svdoldie** [comment]
in der Exceltabelle?

**Comment by appukonrad** [comment]
maybe it could be interesting
unofficial-fussball-de-api
https://github.com/mauricewipf/unofficial-fussball-de-api

**Comment by diddipoeler** [comment]
Im Pressebericht !

**Comment by svdoldie** [comment]
Verstehe ich jetzt nicht. 
Ging vor kurzem noch, sogar mit richtiger Positionszuordnung

**Comment by tdittmann** [comment]
Wenn ich mir den Pressebericht von mir anschaue, kann man an der Spaltenüberschrift sehen, welcher Spieler in der Startaufstellung ist und welcher Auswechselspieler ist.

![2019-01-04 20_08_06-pressebericht - excel](https://user-images.githubusercontent.com/22032251/50705889-7eafd900-105c-11e9-88b4-30d5e04574f4.png)

**Comment by svdoldie** [comment]
Moin. Ich hab mal ein bisschen getestet. Sieht schon super aus :+1: 
Die Auswechselungen werden allerdings noch nicht gespeichert.
Bei den Ereignissen frage ich mich ob man die nicht automatisch zuweisen kann,
da Ereignis und die dazugehörige Person schon ausgelesen werden.
Zum anderen eignet sich der Import prima um Spieler einer Mannschaft zuzuordnen,
wenn sie dieser noch nicht zugehören. Dabei wäre es aber schön, wenn auch die gewählte Position aus der Startaufstellung übernommen wird.

**Comment by tdittmann** [comment]
Morgen, sehr gut ;) 
Genau die Auswechslungen hab ich noch nicht gemacht, das schau ich mir als nächstes an.
Die Ereignisse automatisch zuordnen? Du meinst, wenn im Spielbericht "Gelbe-Karte" steht und wir ein solches Ereignis auch haben, dann das automatisch auswählen? Könnte man sich anschauen :wink: 
Die Spieler werden doch aktuell schon einem Team zugeordnet oder? Und die Position ist leider aus dem Pressebericht nicht korrekt auszulesen oder? Außer der erste Spieler ist immer TW, die nächsten 4 Abwehr, die nächsten 4 Mittelfeld und die letzten 2 Stürmer... wobei hier das System mit 4-4-2 dann vorgegeben ist :(

**Comment by svdoldie** [comment]
Mit den Spielern verhält es sich folgendermaßen: Sind dem Team eines Projektes noch keine Spieler zugeordnet, bzw. im Pressebericht ist einer, der noch nicht  dem Team zugeordnet wurde, werden diese bzw. derjenige beim Import dem Team zugeordnet. Sehr gute Sache :+1: Wenn diese Spieler in der Startaufstellung stehen und "neu" sind, könnte man ihnen die gewählte Position beim zuordnen des Team gleich mit übergeben. Ich hoffe nun ist es verständlicher

**Comment by svdoldie** [comment]
Noch ein kleiner Nachtrag: die Spieler, die nicht in der Startaufstellung stehen werden auch dem Team zugewiesen, sofern sie noch nicht vorhanden waren

**Comment by tdittmann** [comment]
Habs verstanden, ich schau mal bei Zeit danach :) 
Hab vorerst einen PR aufgemacht für die Auswechslungen. Ein Problem ist mir dabei noch aufgefallen: wenn ein Spieler bspw. D'Allesandrini oder ähnliches heißt (das ' ist hier wichtig) wird die Auswechslung nicht verarbeitet. Da muss ich noch schauen warum das so ist.

**Comment by svdoldie** [comment]
Nein, nicht ganz. Die Person soll die an dieser Stelle ausgewählte Position für das Projekt erhalten

**Comment by svdoldie** [comment]
Staff klappt jetzt auch :+1:

**Comment by tdittmann** [comment]
Schiedsrichter sollten nun auch funktionieren

**Comment by svdoldie** [comment]
Schiedsrichter importieren klappt  :+1:

**Comment by svdoldie** [comment]
Nochmal zum Anlegen von Spielern einer Mannschaft durch den Pressebericht.
Ich habe nochmal eine neue Testinstallation angelegt, nur das ich diemal vor Import eines Presseberichts die Positionen in der richtigen Reihenfolge gespeichert habe. 
Keine Spieler +Staff sind dem Team zugeordnet. Die zugeorneten Positionen sind Torhüter, Abwehrspieler, Mittelfeldspieler, Angreifer, Trainer und Co-Trainer. Nach dem ersten Import eines Pressebericht sieht es folgendermaßen aus: Die Personen werden alle dem Projektteam zugeordnet, und die Positionen stimmen auch, bis auf die Abwehrspieler, die sind den Mittelfeldspielern zugordnet.
Allerdings muss man dann noch in der Kaderübersicht alle Spieler speichern, damit die Positionen "richtig" zugeordnet werden. Im Spielbericht ist alles richtig gespeichert!!!

**Comment by svdoldie** [comment]
Importiert man dann den nächsten Pressebericht, werden alle neuen Spieler angelegt.
das kann man im Spielbericht(Frontend) überprüfen. Allerdings wird nun keinen Spieler mehr in der Kaderübersicht (Backend) angzeigt, Im Frontend schon. Da aber die Positionen im Backend zwar zugeordnet werden, nun aber nicht mehr gespeichert werden können, sind sie in der Kaderanzeige (Frontend) ohne Position angezeigt. Zudem werden die als Abwehrspieler zugeordneten Spieler aus dem Pressebericht erneut als Mittelfeldspieler angelegt. Beim Staff gibt es diese ganze Problematik nicht!!!

**Comment by tdittmann** [comment]
Jetzt konnte ich es nachstellen. Ich habe immer mit meinem ersten Projekt getestet, da waren zufällig die Position-IDs identisch mit den Projekt-Position-IDs... ich glaub da hab ich etwas durcheinander gebracht. Das muss ich mir dann nochmal genauer anschauen.

**Comment by svdoldie** [comment]
Geht einwandfrei mit den Schiedsrichtern :+1:

**Comment by tdittmann** [comment]
Perfekt, dann schau ich mir die Tage nochmals Spieler + Staff an

**Comment by svdoldie** [comment]
Hört sich gut an :+1:  :-)

**Comment by tdittmann** [comment]
Spieler + Staff bitte nochmal testen, sobald der PR gemergt wurde.

**Comment by diddipoeler** [comment]
PR wurde gemerged.

**Comment by svdoldie** [comment]
Situation nach dem ersten Import:
Alle Spieler sowie Staff werden inkl. Position der Mannschaft richtig zugeordnet !!!  👍
Im Spielbericht wird der Staff allerdings mit den falschen Positionen angezeigt, das führt in meinem Fall dazu, dass der Trainer gar nicht angezeigt wird.
Siehe Spielbericht https://svdoldie.stony-sport4u.de/index.php?option=com_sportsmanagement&view=matchreport&cfg_which_database=0&s=1&p=1:verbandsliga-nord-18-19&mid=7:sv-doerpum_tus-collegia-juebek&Itemid=115
und Kader https://svdoldie.stony-sport4u.de/index.php?option=com_sportsmanagement&view=roster&cfg_which_database=0&s=1:18-19&p=1:verbandsliga-nord-18-19&tid=13:sv-doerpum&Itemid=272

Nun werde ich den 2. Pressebericht importieren...

**Comment by svdoldie** [comment]
Nach dem 2. Import sieht es genauso aus wie nach dem ersten 👍
Kader ist im Backend weiterhin sichtbar und es wird nichts doppelt angelegt.
Die Importmaske sieht jetzt auch übersichtlicher aus, aber das ist vielleicht auch Geschmacksache ;-)
Wie oben erwähnt ist damit nur noch die Zuordnung des Staffs im Spielbericht noch nicht in Ordnung

**Comment by tdittmann** [comment]
Werden alle Staffs mit der falschen Position gespeichert?

**Comment by svdoldie** [comment]
Die Staffs werden nur !!! im Spielbericht falsch angezeigt. In der Anzeige im Backend, sowie in der Kaderanzeige im Frontend ist alles korrekt!!! Siehe obige Links, wobei der Trainer gar nicht angezeigt wird.

Das mit den Einwechselungen hatte ich dann auch. Ich hatte bisher vermutet, ich hatte das beim ersten Spiel (= 1. Import) einfach vergessen

**Comment by tdittmann** [comment]
Sorry, hatte ich falsch gelesen.
Für die Einwechslungen habe ich bereits einen Fix

**Comment by tdittmann** [comment]
Wenn du die automatische Zuweisung meinst, dann natürlich gerne 👍 

- [ ] Spielbericht-View: Staffs werden falsch angezeigt
- [ ] Automatische Selektierung eines Ereignisses im Pressebericht

**Comment by svdoldie** [comment]
die meinte ich ;-) 
Übrigens tolle Arbeit !!! :+1:

**Comment by tdittmann** [comment]
Automatische Selektierung sollte nun auch funktionieren. Zusätzlich werden auch Rote Karten eingearbeitet, die hatten noch gefehlt 👍

**Comment by tdittmann** [comment]
Wie heißen deine Ereignisse?
Das Modal ist mir auch aufgefallen, aber da hab ich eigentlich nichts dran gemacht :(

**Comment by svdoldie** [comment]
Die Ereignisse haben die Standardnamen von JSM.

**Comment by tdittmann** [comment]
Kannst du mal in der Tabelle #__sportsmanagement_eventtype schauen, was genau in der Spalte "name" drin steht? Von dort hole ich eigentlich die Event-IDs heraus. Steht bei dir dort "Gelbe Karte", "Gelb-Rote Karte" und "Rote Karte"? Oder wird das bei dir anders geschrieben?

**Comment by diddipoeler** [comment]
Eigentlich stehen dort die Platzhalter.
COM_SPORTSMANAGEMENT_SOCCER_E_YELLOW_CARD
COM_SPORTSMANAGEMENT_SOCCER_E_YELLOW-RED_CARD
COM_SPORTSMANAGEMENT_SOCCER_E_RED_CARD

**Comment by svdoldie** [comment]
Genauso sieht es bei mir aus

**Comment by svdoldie** [comment]
Super !!! :+1:  Ereignisse und Modalfenster auch.
Nur noch ein kleiner Schönheitsfehler:
in der Spalte Karte stehen die Namen der Variablen, nicht die Übersetzung

**Comment by tdittmann** [comment]
Sollte nach Merge des PRs auch erledigt sein 👍

**Comment by svdoldie** [comment]
super !!! :+1: 
Von mir aus kann der Issue geschlossen werden !!!
Evtl. könnten noch die Debuginfos entfernt werden

**Comment by tdittmann** [comment]
Das ist noch das kleinste Problem ;)
Hab es auch öfters getestet, sollte noch was auffallen können wir ja einen neuen Issue aufmachen 👍

**Comment by svdoldie** [comment]
Ok, dann warte ich den Request noch ab und mach hier zu.
Vielen Dank nochmal, ich denke das erleichtert die Arbeit ungemein !!! :+1:

**Comment by svdoldie** [comment]
Sehr gut!!! Vielen Dank auch noch mal an Diddi, der hier und allem anderen die ganze Vorarbeit geleistet hat und leistet. Ganz großes Kino Männer :+1: :+1: :+1:
