### ISSUE TITLE
Tippspiel Erinnerung fehlerhaft

### ISSUE THREAD

**Issue by mignetic** [diddipoeler/sportsmanagement#370]
Nun funktioniert die Erinnerung, allerdings erhalten alle Tipper von jedem anderen Tipper eine Kopie der Erinnerung.

**Comment by mignetic** [comment]
Es wäre toll, wenn man nur einmal absenden muss und alle erhalten dann die Erinnerung.
Wäre toll.
Danke.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by mignetic** [comment]
Scheint jetzt zu funktionieren! Danke!

**Comment by mignetic** [comment]
Aber jetzt geht die ganze Seite nicht mehr...

**Comment by mignetic** [comment]
Angezeigt wird: Class 'sportsmanagementModelPrediction' not found

**Comment by mignetic** [comment]
Brauche dringend Hilfe! Sonst können die Tippspieler nicht mehr tippen!!!

**Comment by mignetic** [comment]
Soo, die Erinnerung funzt so, wie sie soll. Allerdings ist dann die komplette Site down!
Installiere ich JSM erneut, funzt die Site wieder, aber die Erinnerung nicht mehr.

**Comment by diddipoeler** [comment]
Bitte ein Update der Komponente machen und noch einmal testen.

**Comment by mignetic** [comment]
Funtioniert! Danke!
