### ISSUE TITLE
Edit matches funktioniert nich

### ISSUE THREAD

**Issue by dogsfun** [diddipoeler/sportsmanagement#373]
Started today with testing JSM because i need a version for Joomla 3.
I'm using Joomleague for several years now for a darts competition.

http://dartclub.cafekuntjod.nl/

Unfortunately both JSM and Joomleague don't have a stable version yet.

After 10 minutes i allready had the first problem.
After creating matchdays i wanted to edit the matches and got this message:

1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE catid =0' at line 2 SQL=SELECT c.id as value,c.title as text WHERE catid =0

A bug or am i missing something?
Thanks for your help.

**Comment by diddipoeler** [comment]
mach mal bitte ein update der komponente.

**Comment by dogsfun** [comment]
This problem seems to be gone, and now i see i forgot to assign teams to the project.
In projects i push the button 'Assign', but get a white field with only the title.

**Comment by diddipoeler** [comment]
kann man sich das einmal im backend direkt anschauen ?
wenn es keine probleme bereitet, könntest du mir die zugangsdaten (admin) zusenden ?

**Comment by dogsfun** [comment]
Woher sende ich dass?

**Comment by diddipoeler** [comment]
diddipoeler@gmx.de

**Comment by diddipoeler** [comment]
bitte noch einmal testen. man musste nur einmal die
optionen aufrufen und speichern.

**Comment by dogsfun** [comment]
Looks OK now. 

After assigning the teams next errormessage is there.
'You can not change teams. Assign additional teams of the season.'

Not sure if it is an error or just a warning.

Thanks for your help.
I'll go on with testing

**Comment by diddipoeler** [comment]
es handelt sich hierbei um eine warnung, da man eine mannschaft nur einmal
einer saison zuordnen kann.
