### ISSUE TITLE
Module Matches shows allready played games despite settings not to show.

### ISSUE THREAD

**Issue by dogsfun** [diddipoeler/sportsmanagement#374]
Checked all settings several times but cannot find another setting to show only upcoming games or show a message.

![matches](https://cloud.githubusercontent.com/assets/22560467/19051673/13d2e036-89b4-11e6-8bcb-f5cbe19840d3.jpg)

**Comment by diddipoeler** [comment]
bitte ein update der komponente machen.

**Comment by dogsfun** [comment]
Allready gone further with Joomleague. Running with Joomla 3 on a live site and no problems for the purposes i need it for.
http://toeere.allesoverkerkrade.nl/

Not good for your component if you need 5 months to answer a question.

Good luck

**Comment by diddipoeler** [comment]
ich kommentiere den letzten eintrag nicht.
