### ISSUE TITLE
Clubplan doesn't schow team full name

### ISSUE THREAD

**Issue by dogsfun** [diddipoeler/sportsmanagement#375]
The clubplan only show the short name.

I'm trying to change things through frontend settings but this and the the other settings don't have any effect in the frontend.

Looked at the xml and it seems there are things missing in that file. Made changes in the xml but they don.t have any effect.

![clubplan](https://cloud.githubusercontent.com/assets/22560467/19086223/87ba2c34-8a6d-11e6-8588-dc68ab4affc0.jpg)

I don't know wat 'teamart' is. Were can i delete that?

**Comment by sigal** [comment]
hallo @dogsfun,
settings must be made in the template club plan of each project.
Here you can set the format of the team names.

See: ![Cubplan settings](http://www.awesomescreenshot.com/image/1675203/e2abed87e157a4e05d1394dd92c8d3bc)

[An online]http://jsm.stony-sport4u.de/index.php?option=com_sportsmanagement&view=clubplan&cfg_which_database=0&s=0&p=987:st-oberliga-nord-2016-17&cid=17:esv-knittelfeld&Itemid=1123)

regards

**Comment by dogsfun** [comment]
I found the problem.
In the menu item the project was not selected.

Because i am going to work with more projects i left that open.

So, with 1 project it is OK.
I'm going to test it now with more projects and leave the option for selecting a project in the menu item open.

I'll be back

**Comment by dogsfun** [comment]
There is a little work to on this one.

I now have 2 projects. Ik want to see all the matches of the club.
When i don't select a project, the output is like above picture.

If i select 1 project, it shows all matches from all projects, no matter what project i choose.

So, the output is now ok but created a little strange.

Good luck and thanks for your help.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by diddipoeler** [comment]
please try again.
