### ISSUE TITLE
Frontend: Warning: Creating default object from empty value in /components/com_sportsmanagement/views/predictionresults/view.html.php on line 89

### ISSUE THREAD

**Issue by boxr** [diddipoeler/sportsmanagement#379]

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by boxr** [comment]
Fehlermeldung ist weg, aber die Spielpaarungen werden verschoben dargestellt und unter der Tabelle befindet sich ein Semikolon, zu hier zu sehen http://jsm.tippen-bl.de/index.php/tippergebnisse

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by boxr** [comment]
Funktioniert, Danke 👍
