### ISSUE TITLE
Datenübernahme von JoomLeague funktioniert nicht

### ISSUE THREAD

**Issue by tdit** [diddipoeler/sportsmanagement#380]
Ich versuche aktuell JoomLeague mit Sportsmanagement abzulösen und damit gleichzeitig von J2.5 auf J3.5 umzusteigen, doch leider funktioniert es nicht. Weder auf Joomla 2.5, noch unter 3.6 funktioniert der Import meiner alten Daten. 
Ich habe unter J2.5 Sportsmanagement installiert und will nun den Import starten. Ich bekomme schon vorher eine Fehlermeldung:
`Warning: mysqli_query(): Empty query in /www/htdocs/w006a525/dev/libraries/joomla/database/database/mysqli.php on line 382

Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in /www/htdocs/w006a525/dev/libraries/joomla/database/database/mysqli.php on line 263`.
Beim Klick auf Import steht die Laufzeit usw. dran, jedoch geht der Import nicht weiter.

Unter J3.5 habe ich die DB-Tabellen aus 2.5 importiert und den Import gestartet. Dort kommt nun immer wieder der Timer mit "In 5 Sekunden startet der nächste Schritt", doch in der Datenbank ist nichts vorhanden.

Was genau mache ich falsch bzw. wie könnte der Import funktionieren, damit ich die Daten behalten kann?

**Comment by diddipoeler** [comment]
ist das eine installation auf einem localhost ?
wenn nein, dann sende mir mal bitte einen admin zugang.
am besten auf dem server mit joomla 3.x.

und noch vielleicht für mich als info:
warum möchtest du denn gerne auf meine komponente wechseln ?

**Comment by tdit** [comment]
Der Import hat nun funktioniert, ich habe nochmals die alten Daten frisch rüberkopiert. Ging wohl etwas beim ersten Import der Daten in die DB schief.

Der Hauptgrund ist sicherlich J3.x, da ich endlich darauf upgraden möchte. Und zusätzlich sind viele nützliche Funktionen (DFBnet Import, Pressebericht Import, ...) vorhanden, die ich in meiner aktuellen JoomLeague Version (das Komplettpaket von dir) nur mit unschönen Modifikationen zum Laufen bekommen habe.
