### ISSUE TITLE
Ewige Tabelle: Anzeigefehler

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#391]
Anzeige: 0 - Class 'JSMRankingTeam' not found

Aufruf von Zeile 97 der view.php zu model rankingalltime.php zeile 847 ?

**Comment by sigal** [comment]
kann nach meiner kleinen Zugabe #392 als bereinigt geschlossen werden.

**Comment by diddipoeler** [comment]
läuft noch nicht unter joomla 3

**Comment by sigal** [comment]
:thumbsup: - kann jetzt geschlossen werden :thumbsup:
