### ISSUE TITLE
Teaminfo zeigt falsche Daten

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#397]
In der Historie der gespielte Saisons werden nicht die Daten des jeweiligen Teams angezeigt,
sonder die vom Tabellenführer. Ausnahme die Daten, die den Kader betreffen sind korrekt.
Siehe http://svdoerpum.de/jsmtest/index.php?option=com_sportsmanagement&view=teaminfo&cfg_which_database=0&s=1:2016-17&p=1:kreisliga-2016-17&tid=13:sv-doerpum&Itemid=1911

**Comment by diddipoeler** [comment]
bei mir zeigt er das richtig an:
http://www.fussballineuropa.de/index.php?option=com_sportsmanagement&view=teaminfo&cfg_which_database=0&s=0&p=49497:j-league-japan-2014&tid=4279:gamba-osaka&ptid=807010:gamba-osaka

**Comment by sigal** [comment]
das stimmt nur bedingt. das ganze würde besser in issue 393 passen
bei aufruf der teaminfo aus einer normalen tabelle oder result passt die anzeige der teaminfo.

doch bei aufruf der teaminfo aus einer ewigen tabelle wird auch auch auf deiner seite ein falsches ergebnis der teaminfo angezeigt.

Siehe ewige tabele 1. bundesliga deutschland- daraus die teaminfo für bayern münchen:

http://www.fussballineuropa.de/index.php?option=com_sportsmanagement&view=teaminfo&cfg_which_database=0&s=0&p=3:1-bundesliga-2009-10&tid=8:fussball-club-bayern-muenchen

Die mannschaft hat immer den ersten platz

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :-)
