### ISSUE TITLE
Backend-View: positions Layout

### ISSUE THREAD

**Issue by diddipoeler** [diddipoeler/sportsmanagement#398]
Zukünfitg wäre es wünschenswert, wenn der User selber entscheiden kann, ob die Standardpositionen hinzugefügt werden sollen.
Die Komponente sollte nicht die Positionen von alleine Anlegen, wenn es nicht gewünscht ist und bereits Positionen
angelegt wurden.

**Comment by sigal** [comment]
Einen kleinen Tipp hab ich, wenn die Positionen schon angelegt wurden - also unter Sportart Fußball - kann man die Sportart unter Optionen wieder löschen (deaktivieren und speichern). Hat keinen Einfluss auf die Ausführung der Komponente, da schon alles angelegt wurde. Nun kann man nicht benötigte Positionen und Ereignisse löschen
Jetzt werden bei einen Update der Komponente die fehlenden Positionen und Ereignisse nicht wieder neu angelegt.
