### ISSUE TITLE
Automatische Saisonzuordnung der Personen

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#402]
Es wäre schön wenn beim DFBnet-Import die Personen gleich der aktuellen Saison zugeordnet werden würden

**Comment by diddipoeler** [comment]
Meinst du den DFB-Net PLayerimport ?

**Comment by svdoldie** [comment]
Ja genau. Ich dachte an eine Option, in der man die aktuelle Saison wählen kann, bevor der Import gestartet wird. Optimal wäre eine Abgleichung  bzw. Zuordnung der Altersgruppe

**Comment by diddipoeler** [comment]
Kannst Du mir bitte noch eine Spielerdatei zum Test zusenden ?

**Comment by svdoldie** [comment]
Ist unterwegs ;-)

**Comment by diddipoeler** [comment]
Bitte einmal mit vorsicht testen.

**Comment by svdoldie** [comment]
Die Zuordnung der Saison klappt anscheinend perfekt :+1: 
Soll die Zuordnung der Altersgruppe auch schon funktionieren?

**Comment by diddipoeler** [comment]
Wo soll ich das denn mit der Altersgruppenzuordnung einbauen ?

**Comment by svdoldie** [comment]
Auch im DBFplayerimport. So könnte man zu Beginn jeder Saison bei Jugendspieler die Altersgruppe anpassen. Anschließend ist die Zuordnung zu den Teams ein Kinderspiel, da man nach der Altersgruppe filtern kann.

**Comment by diddipoeler** [comment]
Also muss zu jedem Spieler, bei Anzeige der Spieler im 2ten Bild, ein Pulldown Menü
mit der Altersgruppe erscheinen. Dann kann man dort die Altersgruppe zuordnen.
Habe ich das so richtig verstanden ?

**Comment by svdoldie** [comment]
Ich dachte eher, das man das Infofeld der Spielerliste nutzt, da steht die aktuelle Altersgruppe vom DFB schon drinnen

**Comment by diddipoeler** [comment]
Dann benötige ich mal die komplette Altersgruppenliste vom DFB.
Den Import kannst Du jetzt schon einmal mit der Zuordnung der Altersgruppe testen.

**Comment by svdoldie** [comment]
![altersklassen](https://user-images.githubusercontent.com/2417767/27036977-e191fb22-4f86-11e7-927d-25dee9872a4a.png)

**Comment by svdoldie** [comment]
Das setzen der Altersklasse klapt tadellos :+1:

**Comment by diddipoeler** [comment]
Mach mal bitte ein Update der Komponente.
Danach bitte testen.

**Comment by svdoldie** [comment]
Sieht prima aus !!! :+1:
