### ISSUE TITLE
Anzeige Todestag lässt sich nicht abschalten

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#403]
In der normalen Kaderansicht wird der voreingestellte Todestag mit angezeigt und das lässt sich auch nicht abschalten

**Comment by diddipoeler** [comment]
ist der view: **roster** gemeint ?

**Comment by svdoldie** [comment]
genau

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by diddipoeler** [comment]
ist das jetzt erledigt ?

**Comment by svdoldie** [comment]
Ja, ist erledigt :+1:
