### ISSUE TITLE
Ansicht Mannschaftsinformation verrutscht.

### ISSUE THREAD

**Issue by diddipoeler** [diddipoeler/sportsmanagement#404]
In der Mannschaftsinformation sind die erweiterten Optionen verrutscht.

**Comment by svdoldie** [comment]
Gilt auch für die Ansicht Clubinfo

**Comment by sigal** [comment]
In meinem Template greift die Class row nicht.
Class=row-fluid hingegen zeigt Wirkung. 

Mein Template ist auf Fluid eingestellt. Muss das noch mit anderen Einstellungen testen.
