### ISSUE TITLE
Ansicht ranking ohne Reiter

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#405]
Es wäre schön, wenn man keine anderen Ansichten der Tabelle, wie Hin- und Rückrunde usw. haben möchte, das die Tabelle ganz ohne Reiter angezeigt wird.

**Comment by diddipoeler** [comment]
bitte noch einmal testen.
in den erweierten optionen, template ranking, alle tabellen auf nein stellen.

**Comment by diddipoeler** [comment]
können wir das jetzt schließen ?

**Comment by svdoldie** [comment]
Meiner Meinung nach ja, zumindest funktionierts bei mir
