### ISSUE TITLE
Personen löschen funktioniert nicht

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#406]
Das Löschen von Personen die einem Team zugeordnet sind funktioniert nicht

**Comment by svdoldie** [comment]
Hier mal die Debug-Infos:
Hinweis

sportsmanagementModelteamperson::delete 251 project_team_id
81

sportsmanagementModelteamperson::delete 252 team_id
81

sportsmanagementModelteamperson::delete 253 pid
8

sportsmanagementModelteamperson::delete 254 persontype
1

sportsmanagementModelteamperson::delete 256 $pks
Array
(
    [0] => 370
)

sportsmanagementModelteamperson::delete 257 post
Array
(
    [filter_search] => 
    [limit] => 30
    [limitstart] => 0
    [cid] => Array
        (
            [0] => 370
        )

    [market_value370] => 0
    [jerseynumber370] => 
    [project_position_id370] => 0
    [position_id370] => 
    [person_id370] => 358
    [order] => Array
        (
            [0] => 0
        )

    [project_team_id] => 81
    [team_id] => 81
    [pid] => 8
    [persontype] => 1
    [search_mode] => 
    [task] => teampersons.delete
    [boxchecked] => 1
    [filter_order] => ppl.lastname
    [filter_order_Dir] => 
    [30b2a79363ee324714a32ebe9249830b] => 1
)

**Comment by diddipoeler** [comment]
Es gibt jetzt keine Löschfunktion mehr, sondern nur noch Papierkorb oder Archiv.

**Comment by svdoldie** [comment]
Aber das Leeren den Papierkorbs sollte möglich sein,
und damit das entgültige Löschen. 
Meiner Meinung nach ;-)

**Comment by diddipoeler** [comment]
Bitte noch einmal das löschen testen.

**Comment by svdoldie** [comment]
geht wieder  :-)
