### ISSUE TITLE
Optionale Funktionen in der Komponente

### ISSUE THREAD

**Issue by diddipoeler** [diddipoeler/sportsmanagement#407]
Sportarten - muss
 Saisons - muss
 Ligen - muss
 Positionen - optional
 (können alle selbst angelegt und gelöscht werden)
 Schiedsrichter - optional
 Vereine - muss
 Mannschaften - muss
 Spielfeldpositionen - optional
 (können alle selbst angelegt und gelöscht werden)
 Personen - optional
 muss wenn Statistik, Geburtstage o.ä. gewünscht ist!
 Ereignisse - optional
 muss wenn Statistik gewünscht ist!
 Int. Verbände - optional
 Länder - optional
 Landesverbände - optional
 Altersgruppen - optional
 Sportstätten - optional
 Alle Sonderfunktionen - optional

**Comment by sigal** [comment]
Obwohl ich persönlich mit dem keine Freude habe, kann dieser issue geschlossen werden.
Denn fragen wie: wo finde ich ..., oder wo kann man das einstellen werden folgen.
