### ISSUE TITLE
JSM Google Maps im SEO Mode

### ISSUE THREAD

**Issue by diddipoeler** [diddipoeler/sportsmanagement#415]
SEO in der Joomla! Konfiguration abschalten.
Suchmaschinen-freundliche URL auf NEIN stellen
Momentan wird in JSM Google Maps nur mit oben gezeigter Konfiguration angezeigt.

**Comment by sigal** [comment]
Bei eingeschalteter Seo und Ansicht ranking keine Map. http://jsm.stony-sport4u.de/bundesliga-2016-17/tabelle-bundesliga-2016-17.html
Bei resultsranking erfolgt Anzeige. http://jsm.stony-sport4u.de/bundesliga-2016-17.html

**Comment by sigal** [comment]
Map wird jetzt angezeigt, doch gibt es jetzt folgende Consolenmeldungen:

RetiredVersion 	Warning 	

You may have supplied a retired version in your script element. The versions 3.0 - 3.25 have been retired, and you might be receiving **3.26** instead. Please update your application to use one of the available versions.

See Versioning | Google Maps JavaScript API.


SensorNotRequired 	Warning 	

The sensor parameter is no longer required for the Google Maps JavaScript API. It won't prevent the Google Maps JavaScript API from working correctly, but we recommend that you remove the sensor parameter from the script element.

**Comment by sigal** [comment]
ist in ordnung!
