### ISSUE TITLE
Frontend - edit match: Spieler werden nicht angezeigt

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#419]
Es ist übers Frontend nicht möglich Aufstellung, Auswechselungen oder Ereignisse einzutragen,
da keine Spieler angezeigt werden, obwohl sie vorhanden sind.

![editmatch](https://cloud.githubusercontent.com/assets/2417767/24138903/56b13d04-0e1a-11e7-88b6-56f321231eae.png)
![kader](https://cloud.githubusercontent.com/assets/2417767/24138907/5ad31128-0e1a-11e7-82ab-643fc0815cc1.png)

**Comment by svdoldie** [comment]
aktueller Stand:
Spieler und Staff erzeugen Fehlermeldung, siehe Bild
Auswechselungen würden gehen, die möglichen Einwechselspieler werden angzeigt
![fehler 404](https://user-images.githubusercontent.com/2417767/27137094-4d31ae26-511d-11e7-8708-a9d373711060.png)

**Comment by diddipoeler** [comment]
Wie kommt der Fehler noch einmal im Detail zustande ?

**Comment by svdoldie** [comment]
Sobald man auf den Reiter Spieler bzw. Mitarbeiter klickt

**Comment by svdoldie** [comment]
Beim Reiter Trikotnummern passiert das gleiche

**Comment by svdoldie** [comment]
Das ganze kann man nur sehen, wenn man die Ansicht dfc_day gewählt hat.
Bei der normalen Ansicht kann man leider gar nicht eintragen, siehe Bilder
![mtchedit](https://user-images.githubusercontent.com/2417767/27170213-6c86a2a0-51ad-11e7-859f-875acb966497.png)
![matchedit2](https://user-images.githubusercontent.com/2417767/27170231-7bced2fa-51ad-11e7-8d6d-d82be51e7713.png)
