### ISSUE TITLE
Frontend View Ranking - leere Klammern hinter den Teams

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#422]
Wie kann man die leeren Klammern hinter den Teams in der Tabelle wegbekommen?
Siehe http://svdoerpum.de/senioren/1-herren/tabelle

**Comment by diddipoeler** [comment]
Im Projekttemplate Ranking:
Reiter -> Mannschaftsoptionen
Eindeutige Vereinsnummer auf Nein

**Comment by svdoldie** [comment]
Danke !!!
