### ISSUE TITLE
Backend-View: template Layout: edit

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#423]
Template ranking
Kriterium der Sortierreihenfolge H2H erzeugt Fehlerseite im FE
Call to a member function getPoints() on null

**Comment by diddipoeler** [comment]
bitte noch einmal testen-

**Comment by sigal** [comment]
Noch immer gleicher Fehler.
Templateeinstellung: POINTS, H2H
Call to a member function getPoints() on null

**Comment by sigal** [comment]
Läuft!
