### ISSUE TITLE
Frontend-view results - Ergebnis speicherung löscht Datum und Spielnummer

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#426]
Wenn man bei der Ergebnisbearbeitung die Ansicht DFCday gewählt hat,
werden bei Speicherung in den Spielen  wo man ein Ergebnis eingetragen hat, 
das Datum auf 30-11--1 gesetzt und die Spielnummer gelöscht.
![bildschirmfoto zu 2017-04-01_08-32-43](https://cloud.githubusercontent.com/assets/2417767/24576105/fd9dc6a2-16b5-11e7-9b28-d61aec827a44.png)

**Comment by teddyfresco** [comment]
I've made a little search online, maybe these articles could be of some help:
http://stackoverflow.com/questions/4606264/why-0000-00-00-value-convert-to-30-11-1-with-date-d-m-y
http://fabrikar.com/forums/index.php?threads/date-field-value-0000-00-00-displayed-as-30-11-0001.37709/
Maybe they are relative to other issues, maybe not...

**Comment by svdoldie** [comment]
Bringt uns der link von teddyfrisco weiter?

**Comment by teddyfresco** [comment]
I also wonder if dates' problem has got anything to do with this bug:
https://issues.joomla.org/tracker/joomla-cms/11530

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Das Problem existriert noch
