### ISSUE TITLE
 FE Einstellungen: Hitliste

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#430]
Sportstätten werden nicht gezählt

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by sigal** [comment]
Noch kein Erfolg.

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by sigal** [comment]
Perfekt. :+1:
Ist :heavy_check_mark:
