### ISSUE TITLE
Ab 50 Spielen pro Spieltag Speichern nicht möglich

### ISSUE THREAD

**Issue by sesma2003** [diddipoeler/sportsmanagement#433]
Ab 50 Spielen pro Spieltag (wie z.b. bei der Qauli zur Europa League in der ersten Runde) kann ich keine Veränderungen mehr abspeichern, egal was ich eintrage und Speichern möchte, wird nicht übernommen.

So kann ich die Uhrzeiten oder die Mannschaften nicht ändern und abspeichern.

**Comment by diddipoeler** [comment]
Wo kann man diese Situation nachstellen ?
Frontend oder Backend ?

**Comment by sesma2003** [comment]
Im backend, im projekt bei spiele anlegen. Bei meinem projekt in europa
league qualifikation, da sind es ja über 100 mannschaften in der ersten
runde.

Am 16.05.2017 17:55 schrieb "diddipoeler" <notifications@github.com>:

Wo kann man diese Situation nachstellen ?
Frontend oder Backend ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/diddipoeler/sportsmanagement/issues/433#issuecomment-301828122>,
or mute the thread

**Comment by sesma2003** [comment]
Ich kann dir auch einen Zugang zu meinem Backend geben, wenn du es dir mal anschauen willst

**Comment by diddipoeler** [comment]
dann sende mir mal bitte deine backend zu.
mit internetadresse.

**Comment by sesma2003** [comment]
Meinst du den admin Zugang zum backend?

Am 18.05.2017 15:26 schrieb "diddipoeler" <notifications@github.com>:

**Comment by diddipoeler** [comment]
genau den meine ich.

**Comment by sesma2003** [comment]
Wie kann ich dir eine private Nachricht schicken?

Am 18.05.2017 19:38 schrieb "diddipoeler" <notifications@github.com>:

**Comment by diddipoeler** [comment]
Sende die Daten hier hin diddipoeler@gmx.de

**Comment by sesma2003** [comment]
ok, hab ich gemacht.

2017-05-18 20:05 GMT+02:00 diddipoeler <notifications@github.com>:

**Comment by diddipoeler** [comment]
man oh man. ein seltsames verhalten.
habe ich so noch nicht gesehen.
muss ich mir im detail einmal anschauen.

**Comment by sesma2003** [comment]
Alles klar, zugang lass ich dir offen

Am 19.05.2017 08:07 schrieb "diddipoeler" <notifications@github.com>:

**Comment by diddipoeler** [comment]
kannst du mal bitte auf dem server die .htaccess datei löschen ?
da ist mir leider ein fehler unterlaufen.

**Comment by diddipoeler** [comment]
danach eine .htaccess Datei mit folgendem Inhalt erstellen.
php_value memory_limit 1024M
php_value max_input_vars 50000

Die Datei dann wieder hochladen.

**Comment by sesma2003** [comment]
ok, mach ich. nur die zwei punkte einfügen, sonst nichts?

**Comment by diddipoeler** [comment]
ja die beiden punkte einfügen.
die datei befindet sich im hauptverzeichnis deiner seite.

**Comment by sesma2003** [comment]
ok, soll der restliche texte gelöscht oder behalten werden?

**Comment by diddipoeler** [comment]
beibehalten !

**Comment by sesma2003** [comment]
ok, hab ich grad gemacht

**Comment by diddipoeler** [comment]
seite kann ich nicht aufrufen.
bitte einmal die datei: '.htaccess' löschen.
wichtig ist der PUNKT vor der datei.

**Comment by sesma2003** [comment]
ich hab keine htacces mit einem punkt, nur ohne

**Comment by diddipoeler** [comment]
wenn du mit einem ftp programm arbeitest mus du dir alle
dateien anzeigen lassen.
oder gibt es für mich einen zugang ?

**Comment by sesma2003** [comment]
willst du einen ftp zugang? oder für plesk? oder virtuozzo? (bin bei hosteurope)

**Comment by diddipoeler** [comment]
komme ich mit filezilla auf deinen account ?

**Comment by sesma2003** [comment]
müsste gehen, ich benutze das WS_FTP LE

**Comment by diddipoeler** [comment]
dann sende mir bitta mal ganz schnell deinen daten,
wenn du mir vertraust.

**Comment by sesma2003** [comment]
mach ich, ich leg dir mal einen eigenen zugang an

**Comment by sesma2003** [comment]
hab dir mal ne mail mit den daten geschickt

**Comment by diddipoeler** [comment]
so, die seite läuft wieder.
die php einstellungen kann ich leider auf deiner seite nicht durchführen.
wenn du die spiele bearbeiten möchtest, dann stell bitte anzahl der anzuzeigenden
spiele auf 20.

**Comment by sesma2003** [comment]
ok, php muss ich eh noch auf 5.6 updaten. danke

**Comment by diddipoeler** [comment]
mach mal gleich ein update auf php 7.

**Comment by sesma2003** [comment]
ich muss mal schauen, ob host europe das schon anbitet

**Comment by diddipoeler** [comment]
sorry hatte ich übersehen.
bei dir steht im kontrollcenter: PHP 7.0.19

**Comment by diddipoeler** [comment]
nachdem jetzt wieder alles läuft, könntest du vielleicht einen kleinen eintrag auf der homepage
im forum machen. unter dem motto: service am user.

**Comment by diddipoeler** [comment]
ist jetzt alles in ordnung ?
