### ISSUE TITLE
Wappen einfügen nicht möglich

### ISSUE THREAD

**Issue by mignetic** [diddipoeler/sportsmanagement#435]
Vorbereitung für die neue Saison gestartet. Neues Team erstellt, aber Wappen können nicht eingefügt werden. Es gilt für alle Bilder!
Fehlermeldung:        0 Using $this when not in object context
                                         Zurück zum Kontrollzentrum

**Comment by diddipoeler** [comment]
Wie sind die Schritte, bis der Fehler erscheint ?

**Comment by mignetic** [comment]
Stony konnte mir helfen, DANKE!

**Comment by mignetic** [comment]
Das lag an dem Media-Tool. Muss in den Optionen auf Joomla umgestellt werden...

**Comment by sigal** [comment]
Hab das mal eingegrenzt.
Joomla 3.7
Neueste JSM Komponente von GitHub
Sportsmanagement als Mediatool unter Optionen gewählt.

Mannschaft wählen und TAB Bild.
Jetzt auf Datei hochladen.
Der Fehler:
Es ist ein Fehler aufgetreten!

    0 Using $this when not in object context.

Das selbe erscheint auch bei Verein, wo man ein Wappen hochladen will.

**Comment by sigal** [comment]
`'PHP message: PHP Deprecated:  Non-static method ImageSelectSM::check() should not be called statically in /xxxxx/administrator/components/com_sportsmanagement/controllers/imagehandler.php on line 143\nPHP message: PHP Deprecated:  Non-static method ImageSelectSM::sanitize() should not be called statically in xxxx/administrator/components/com_sportsmanagement/controllers/imagehandler.php on line 151\n', referer: https://xxxxx/administrator/index.php?option=com_sportsmanagement&view=imagehandler&layout=upload&type=teams&field=jform[picture]&fieldid=jform_picture&tmpl=component`

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Das Hochladen funktioniert nun auch mit Sportsmanagement als Mediatool.
