### ISSUE TITLE
Personenzuordnung zu Teams funktioniert nicht reibungslos

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#436]
Den Bug gibt's auch schon im Bugtracker. Zur näheren Beschreibung verweise ich auf den Thread im Forum
http://fussballineuropa.de/index.php/forum?view=topic&catid=6&id=4548

**Comment by sigal** [comment]
Liste der zugeordneten Spieler --> Spieler bearbeiten
Tab --> Details: Keine Auswahl im Listenfeld vorhanden. (Trotz zugeordneter Positionen)

**Comment by diddipoeler** [comment]
Hast du mal bitte eine Hardcopy vom Bildschirm ?

**Comment by sigal** [comment]
[sreenshot](https://www.dropbox.com/s/yadoa7u85iybs2n/Teamplayer.jpg?dl=0)

**Comment by svdoldie** [comment]
Das geht bei mir 
![positionen](https://user-images.githubusercontent.com/2417767/27135270-657bdf24-5118-11e7-86dc-96215ce8a2be.png)

**Comment by sigal** [comment]
na, dann lassen wir's so stehn, tschüß und einen schönen tag noch.

**Comment by diddipoeler** [comment]
Wo ist denn der Kommentar von @sigal  ?

**Comment by sigal** [comment]
![teamplayer](https://user-images.githubusercontent.com/5115688/27150292-f0926b4a-5146-11e7-83b1-18bfaf7e5139.jpg)

Liste der zugeordneten Spieler

![listenansicht spieler](https://user-images.githubusercontent.com/5115688/27150796-e68f3626-5148-11e7-94aa-a4cfacb8b836.jpg)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Das mit dem doppelten Status existiert noch

**Comment by diddipoeler** [comment]
Welcher doppelte Status ?

**Comment by svdoldie** [comment]
siehe https://user-images.githubusercontent.com/5115688/27150796-e68f3626-5148-11e7-94aa-a4cfacb8b836.jpg

**Comment by diddipoeler** [comment]
Ich habe mal die Textvariable geändert.
Das Erste ist der Spielerstatus und das Zweite ist der Status des Eintrages.

**Comment by svdoldie** [comment]
ok. Aber die Spalte darunter ist leer.

**Comment by diddipoeler** [comment]
Ja klar. Der Spieler hat auch keine Status im Sinne von, Verletzung, Suspendierung oder
Abwesenheit.
Wenn keine der 3 Fälle eintritt, dann soll ein Standardsymbol angezeigt werden ?

**Comment by svdoldie** [comment]
Nee, für mich nicht. Dann kann hier geschlossen werden
