### ISSUE TITLE
Tototipp funktioniert nicht

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#438]
Egal was man tippt, es wird nur Unentschieden gespeichert.
Zudem sind die Sprachvariablen der Tippauswahl noch nicht übersetzt
![tototipp](https://cloud.githubusercontent.com/assets/2417767/26102485/75658f9c-3a35-11e7-9948-df60ebbe2ea4.png)

**Comment by diddipoeler** [comment]
woher kommt denn die pulldownbox ?

**Comment by svdoldie** [comment]
ja. Die Übersetzung klappt nach dem letzten commit jetzt auch. Nur das richtige speichern geht noch nicht

**Comment by svdoldie** [comment]
geht jetzt :+1:
