### ISSUE TITLE
Filterung nach Altersgruppen in der Personenzuordnung zeigt nichts an

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#449]
Die Filterung nach Altersgruppen in der Personenzuordnung zeigt nichts an,
ob wohl den Personen die Altersgruppe zugeordnet wurde.
![personen](https://user-images.githubusercontent.com/2417767/27072679-7b398cc8-5021-11e7-92af-b3f583174275.png)
![spielerzuordnung](https://user-images.githubusercontent.com/2417767/27072678-7b35ebae-5021-11e7-9e8b-fca88fd9f48c.png)

**Comment by diddipoeler** [comment]
Im Filter steht ja auch **C-Junioren** und nicht **C-Junioren (U14/U15)**.

**Comment by svdoldie** [comment]
Berechtigter Einwand ;-) 

Wenn ich nun aber die zugeordneten Spieler speichern möcht,e erhalte ich folgende Fehlermeldung
![fehlermeldung](https://user-images.githubusercontent.com/2417767/27075438-69ac07f2-502a-11e7-8bb8-4f0d6aa46f73.png)

**Comment by diddipoeler** [comment]
Mach mal bitte ein Update der Komponente und danach einen neuen Test.

**Comment by svdoldie** [comment]
Die Fehlermeldung ist immer wenn eine Person zugeordnet wird,
und der Person in den Stammdaten keine Positionen zugeordnet wurde.

**Comment by svdoldie** [comment]
Ich habe noch ein seltsames Verhalten. 
Wenn ich die Spielerliste importiert habe 
und anschließend in den Stammdaten die Personen aufrufe,
werden keine angezeigt.
Nach Ab- und Wiederanmeldung im Joomlabackend werden sie ordnungsgemäß angezeigt

**Comment by diddipoeler** [comment]
Jetzt werden auch Personen übernommen und angezeigt,
die keine position haben.

**Comment by svdoldie** [comment]
top :+1: 
nun muss nur noch das löschen der Spieler klappen ;-)

**Comment by diddipoeler** [comment]
Das löschen der Spieler würde ich nicht einbauen wollen.
Ich würde das verschieben in den Papierkorb oder in´s Archiv vorschlagen.
Dann hat man immer noch die Möglichkeit, Fehler besser zu suchen.

**Comment by svdoldie** [comment]
Auch ok, solange man die Spieler, die nicht ins Team gehören, dort auch wieder herausgenommen werden können

**Comment by svdoldie** [comment]
Scheint perfekt zu funktionieren :+1:
