### ISSUE TITLE
gespeichertes Favoritenteam lässt sich nicht löschen

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#451]
Man kann ein bereits gespeichertes Favoritenteam nicht aus den Projekteinstellungen entfernen.
Die Auswahl eines anderen Team wird gespeichert

**Comment by diddipoeler** [comment]
Man muss die Strg Taste zum abwählen benutzen.

**Comment by svdoldie** [comment]
Hab ich gemacht, geht bei mir nicht.
Beim erneuten Aufrufen steht das bisherige Team wieder da

**Comment by diddipoeler** [comment]
Strg Taste gedrückt halten und das abzuwählende Team anklicken.
Dann ist es nicht mehr blau hinterlegt.

**Comment by svdoldie** [comment]
Weiß ich. Aber wenn man die Projekteinstellung wieder neu öffnet,
ist das Team bei mir wieder da.

**Comment by diddipoeler** [comment]
OK. Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Läuft :+1:

**Comment by svdoldie** [comment]
Doch nicht, nun wird keine Mannschaft mehr gespeichert

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Jetzt geht's :+1:
