### ISSUE TITLE
Backend-View: projectteams Layout: default

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#455]
**Mannschaften ändern.**
Bei gleichzeitiger Änderung von mehr als einer Mannschaft tritt folgender MySQL Fehler auf:

Zusatz: Die als erste ausgewählte Mannschaft wird geändert. Andere werden nicht übernommen.

![sql_error_team](https://user-images.githubusercontent.com/5115688/27513673-db407eae-596f-11e7-9522-ab913ab2c8c6.jpg)

**Comment by diddipoeler** [comment]
Bei mir kann ich den Fehler nicht nachvollziehen.
Gibt es Admin-Zugangsdaten zur Testseite ?

**Comment by sigal** [comment]
Wie ich sehe, muss ich meine alten Projektleichen aus dem JL-DB Import händisch nacharbeiten.
Muss die Projekte händisch speichern, ansonsten siehe z.B. http://jsm.stony-sport4u.de/index.php/component/sportsmanagement/resultsranking/0/0/2490-W%20-%20Wiener%20Stadtliga%202008/09/63876-29.%20Spieltag/0/0/

Nachträglich:
In den Projekten sind die Mannschaften  nicht abgespeichert. Nach Projektmannschaft bearbeiten und abspeichern können die Mannschaften ohne Fehlermeldung geändert und gespeichert werden.

![projekte_03](https://user-images.githubusercontent.com/5115688/27518896-197682fc-59ea-11e7-947f-70fa8f2e672b.PNG)
![projekte](https://user-images.githubusercontent.com/5115688/27518897-197c27c0-59ea-11e7-8c5c-833faf488668.PNG)
![projekte_02](https://user-images.githubusercontent.com/5115688/27518898-197df76c-59ea-11e7-83c1-05c722d662ad.PNG)
