### ISSUE TITLE
Frontendview results - Fehler bei der Bearbeitung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#456]
1. wandert man mit dem Mauszeiger über das Personensymbol ändert er sich nicht, so dass man nicht erkennt, das man darauf klicken kann...
2. es wird ein Modalfenster wird im Modalfenster angezeigt, siehe Bild 1
3. das Modalfenster ist zu schmal, siehe Bild 1
4. beim speichern kommt folgende Fehlermeldung: 1146 - Table 'sk13-121152-1_svdoerpumde.#__sportsmanagement' doesn't exist

alle  Fehler betreffen die normale Ansicht

wählt man die Ansicht DFC-Day..., siehe Bild 2
![frontend1](https://user-images.githubusercontent.com/2417767/27555341-bb316752-5ab1-11e7-95f0-a7b58d25a4cb.png)
![frontend2](https://user-images.githubusercontent.com/2417767/27555344-beec8386-5ab1-11e7-953c-bfdbc3345590.png)

**Comment by svdoldie** [comment]
Nr. 2 + 3 sind wohl Templateabhängig

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
punkt 1 hat sich erledigt
punkt 2 kann ich nicht testen, da bei mir gar kein Modalfenster angezeigt wird
punkt 3 damit auch nicht
punkt 4 hat sich erledigt

das mit der Anzeige dfcday hat sich auch erledigt

**Comment by diddipoeler** [comment]
Ist das mit dem Modalfenster im Frontend ?

**Comment by svdoldie** [comment]
Ja, im Backend ist alles ok

**Comment by svdoldie** [comment]
Diddi, meiner Meinung nach kann der Issue noch nicht geschlossen werden,
da die Bearbeitung nicht in einem Modalfenster angezeigt.

**Comment by diddipoeler** [comment]
Mach mal bitte ein Update der Komponente.
Im Overall Template jquery modal auf Ja stellen.

**Comment by svdoldie** [comment]
Sieht schon viel besser aus !!!
Ich habe aber noch zwei Probleme.
Zum einen wird die Ereignisbearbeitung noch nicht im Modalfenster angezeigt,
zum anderen reagieren die Reiter im Aufstellungsbereich nicht.
Im Bereich Spieldetails ist alles bestens :+1:

**Comment by diddipoeler** [comment]
Bitte die Ereignisbearbeitung testen.

**Comment by svdoldie** [comment]
Die ist jetzt im Modalfenster :+1: 
Es werden aber keine Ereignisse gespeichert,
das muss ich aber noch zu Hause nochmal intensiver testen.

**Comment by svdoldie** [comment]
Auch an meinem Heim-PC werden keine Ereignisse gespeichert.
Der Speicher-Button scheint quasi ohne Funktion zu sein

**Comment by diddipoeler** [comment]
Meinst Du mit Ereignisse: Gelbe Karte u.s.w. ?

**Comment by svdoldie** [comment]
Ja, genau

**Comment by diddipoeler** [comment]
Bitte die Ereignisse testen.

**Comment by svdoldie** [comment]
Die Ereignisse werden jetzt gespeichert. Angezeigt werden sie im Modalfenster aber erst,
wenn man das Fenster neu geladen hat. Und die Spieler der Mannschaft werden erst geladen,
wenn man vorher die gegnerische Mannschaft ausgewählt hat.

**Comment by diddipoeler** [comment]
Bitte die Spieler der Mannschaften noch einmal testen.

**Comment by svdoldie** [comment]
Bisher keine Änderung.

**Comment by diddipoeler** [comment]
Sieht es jetzt etwas besser aus ?

**Comment by svdoldie** [comment]
![bild1](https://user-images.githubusercontent.com/2417767/37949762-7a778128-3185-11e8-8e8c-ca73b4bfe290.png)
![bild2](https://user-images.githubusercontent.com/2417767/37949763-7a9d37e2-3185-11e8-8e6c-d31bb2d897b1.png)
![bild3](https://user-images.githubusercontent.com/2417767/37949764-7ac5dc42-3185-11e8-95dd-ee5f5ff435fe.png)
Nicht wirklich. Ich hänge mal die Bilder an. Erst wenn ich auf das Pulldown für die Mannschaften klicke und die andere Mannschaft auswähle, erscheint das Pulldown mit den Spielern

**Comment by diddipoeler** [comment]
Im Backend oder Frontend ?

**Comment by svdoldie** [comment]
Im frontend

**Comment by diddipoeler** [comment]
Bei mir tritt das nicht auf. Die Spieler werden sofort angezeigt.

**Comment by svdoldie** [comment]
Hmm, dann hängt es wohl wieder an meiner Seite.

**Comment by diddipoeler** [comment]
Kannst Du das bitte noch einmal testen. Ich habe da
etwas umprogrammiert.

**Comment by svdoldie** [comment]
Keine Änderung auf meiner Hauptseite. Auf den Testseiten geht es

**Comment by diddipoeler** [comment]
Was machen wir dann jetzt mit dem Issue ?

**Comment by svdoldie** [comment]
Zumachen 😉
