### ISSUE TITLE
Beim DFBnet-Import werden die Spiele nicht freigegeben

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#457]
Wenn man einen Spielplan aus dem DFBnet importiert,
ist erst ein manuelles Speichern der Spiele nötig, 
damit sie von den Modulen wie z.b. Matches übernommen werden.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :+1:
