### ISSUE TITLE
Personen zuordnen - Seitennavigation funktioniert nicht

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#458]
Will man einem Team Personen zuordnen, kann man nicht auf fortlaufende Seite navigieren.
Egal was angeklickt wird. man landet stets auf der ersten Seite

**Comment by sigal** [comment]
Unter fortlaufende Seite kann ich mir nichts vorstellen, aber:

Optionen aufrufen, Speichern & Schließen hilft.

Dieses Phänomen tritt auch bei anderen Einstellungen, oder Bearbeitung von Projekten auf, wenn man sich neu anmeldet, oder lange Zeit Online bei einem Projekt oder sonstigen verharrt.

**Comment by svdoldie** [comment]
Man kann die Seiten 2 bis ... nicht anzeigen lassen
![bildschirmfoto zu 2017-07-02 15-36-20](https://user-images.githubusercontent.com/2417767/27770289-3ceceb0c-5f3c-11e7-8076-79500109ac7b.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :+1:
