### ISSUE TITLE
Ergebnispflege frontend

### ISSUE THREAD

**Issue by dei71** [diddipoeler/sportsmanagement#464]
Hallo,

ich habe mehrere Fehler in der Ergebnispflege via Frontend. Ich habe zuvor eine Migration auf Joomla 3.7.2 sowie von joomleague auf jsm durchgeführt.

![unbenannt](https://user-images.githubusercontent.com/3773449/27910497-b747209a-6255-11e7-9725-f36d415b1749.png)

**Comment by diddipoeler** [comment]
Herzlichen Glückwunsch zum Wechsel auf die neue Sportkomponente.
Hoffentlich gefällt sie dir ?
Sind Schiedsrichterpositionen zugeordnet ?
Ich bastel sowieso noch an der Ergebnispflege im Frontend.

**Comment by dei71** [comment]
Ja die Komponente ist spitzenmässig. 

Ich habe keine Schiedsrichter oder Spieler zugeordnet. Es soll ein reines Tippspiel für Freunde werden.

**Comment by diddipoeler** [comment]
Vielleicht sollte ich das nicht vorhanden sein von Schiedsrichtern und /oder Spielern
als Warnung ausgeben und nicht als Fehler.
Habe ich das richtig verstanden ?

**Comment by dei71** [comment]
Hallo diddi,

 

ja wäre eine Möglichkeit. Zudem sind die Ladezeiten des Moduls extrem lang.

 

Lg Dirk

 

Gesendet: Sonntag, 09. Juli 2017 um 18:35 Uhr
Von: diddipoeler <notifications@github.com>
An: diddipoeler/sportsmanagement <sportsmanagement@noreply.github.com>
Cc: dei71 <dibra71@web.de>, Author <author@noreply.github.com>
Betreff: Re: [diddipoeler/sportsmanagement] Ergebnispflege frontend (#464)


Vielleicht sollte ich das nicht vorhanden sein von Schiedsrichtern und /oder Spielern
als Warnung ausgeben und nicht als Fehler.
Habe ich das richtig verstanden ?

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
