### ISSUE TITLE
Modul next matches, last matches

### ISSUE THREAD

**Issue by dei71** [diddipoeler/sportsmanagement#467]
Hallo diddi,

die Anzeige des Moduls bringt folgenden Fehler:

links Ergebnisanzeige, rechts nächste Spiele.

![unbenannt-1](https://user-images.githubusercontent.com/3773449/27947896-056e0854-62f8-11e7-8807-9b350e97c994.png)

**Comment by diddipoeler** [comment]
Kannst du mir mal bitte die Adminzugangsdaten zusenden ?
Ich muss mir das mal im Detail anschauen. Auf meiner Homepage
habe ich den Fehler nicht.

**Comment by diddipoeler** [comment]
Mach mal bitte ein Update der Komponente.

**Comment by dei71** [comment]
Hab ich, 

Du hast eine PN mit den Zugangsdaten.

Gruß
Dirk

**Comment by diddipoeler** [comment]
Bitte ein Update der Komponente machen und dann
noch einmal testen.
