### ISSUE TITLE
DFBnet-Import: Pulldowns öffnen sich nicht

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#472]
Wenn man beim Spielplanimport vorhandene Daten wie z.B. die Saison auswählen möchte,
öffnet sich das Pulldown nicht, siehe Bild
![bildschirmfoto zu 2017-08-01 11-49-22](https://user-images.githubusercontent.com/2417767/28819877-dbb2b0ca-76af-11e7-97dc-189cb01b0d21.png)

**Comment by svdoldie** [comment]
Sorry, mein Fehler :-1:

**Comment by svdoldie** [comment]
Das Problem existiert doch, und zwar wenn das Bootstrap-Plugin aktiviert ist.
Sebst wenn man alle Optionen ausgeschaltet hat, öffnet sich kein Pulldown.
Das gilt auch für den XML-Import

**Comment by sigal** [comment]
Frage: Was ist im Bootstrap-Plugin aktiviert?
Es sollte speziell für deine Seite nur >>Bootstrap bootstrap-tab.js laden?<< aktiviert sein

Hab das ganze auf meiner 007 nachgestellt.
Beim XML-Import hab ich die geschilderten Problem auch mit eingeschalteten Plugin nicht.

Außerdem ist das Plugin doch eigentlich für das FE zuständig.

**Comment by svdoldie** [comment]
Ist bei mir trotzdem im Backend so. Egal ob ich eine oder mehrere der Optionen aktiviere,
oder gar keine aktiviert ist. Sobald das Plugin an sich aktiviert ist, tritt der Fehler auf.
Nach Deaktivierung des Plugins ist öffnen sich die Pulldowns.

**Comment by diddipoeler** [comment]
Also bei mir öffnen sich die Pulldown Menüs.
Sogar in Joomla 4.
