### ISSUE TITLE
Format is not saved in Player Description

### ISSUE THREAD

**Issue by Wishmaster172** [diddipoeler/sportsmanagement#473]
In player description the format (Tables, Linebreaks, etc.) is not saved.

Here are some screenshots:
Bevore saving:
i.imgur.com/6vKzCJJ.png 
i.imgur.com/zIn4uzg.png 

After saving:
i.imgur.com/Xy2RBpX.png 
i.imgur.com/IOC2vAv.png

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
