### ISSUE TITLE
Vereinsspielplan - Einstellungen werden ignoriert

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#474]
In der Ansicht Vereinsspielplan werden quasi alle Templateeinstellungen ignoriert
![bildschirmfoto zu 2017-08-02 10-14-21](https://user-images.githubusercontent.com/2417767/28864037-7c627c1a-776b-11e7-95ab-902b1387dcc2.png)
![bildschirmfoto zu 2017-08-02 10-14-40](https://user-images.githubusercontent.com/2417767/28864038-7c62aa0a-776b-11e7-9af2-960c3dcceb84.png)
![bildschirmfoto zu 2017-08-02 10-14-59](https://user-images.githubusercontent.com/2417767/28864039-7c6316d4-776b-11e7-89bb-23dbd719aeb6.png)

**Comment by sigal** [comment]
Zeige x Tage davor heißt: Zeige Spiele, die x Tage vor dem heutigen Tag  liegen.

Heute 2.8.2017 - Minus 6 Tage nach gezeigter Einstellung = 27.7.2017 (Projektstart 6.8.2017) 

am 27.7.2017 gibt es aber keine Spiele im Projekt und das Programm bricht mit gezeigter Fehlermeldung ab

Folgende Einstellung zeigt das gewünschte Ergebnis, da ja die Einstellung mit Projektstartdatum gewählt ist.
Zeige x Tage davor: 0 = 2.8.2017
Zeige x Tage nach: 6  = 8.8.2017 - zeigt nun das erste Spiel am 8.8.2017 = Projektstart

Diese Einstellungen können aber in den Menüeinstellunger geändert, oder angepasst werden.

**Comment by svdoldie** [comment]
Bei mir ändert sich bei einer Änderung im Backend nichts. Auch bei keiner der anderen Optionen.
Wenn ich den Zeitraum im Frontend ändere dagegen schon.

**Comment by svdoldie** [comment]
@sigal : Ich hab mir das gerade auf deiner Testseite angesehen. Funktioniert bei dir tatsächlich.
Kann es an Konflikten mit anderen Plugins liegen, dass bei mir einige Dinge nicht funktionieren.
Bei wird keine Änderung in den Templateeinstellungen im Frontend übernommen

**Comment by svdoldie** [comment]
Ich habe das jetzt mal auf meiner Testseite auf deinem Server versucht.
Das klappt ohne Probleme, liegt also an meiner Homepage :-(

**Comment by svdoldie** [comment]
Wieder ein Stück schlauer ;-)
Man muss auch ein Projekt auswählen, sonst kann JSM auch keine Templates ziehen 
Peinlich, peinlich, peinlich. Asche auf mein Haupt!!!

**Comment by svdoldie** [comment]
Einen Fehler gibt's aber doch. Die Logos werden nicht angezeigt.

**Comment by diddipoeler** [comment]
bitte noch einmal testen.
