### ISSUE TITLE
Projekt wird nicht im Tippspiel-Link nicht übernommen

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#476]
Legt man eine Link zur Tippeingabe an, wird das angebene Projekt nicht übernommen.

So sieht der Link aus: http://svdoerpum.de/index.php?option=com_sportsmanagement&view=predictionentry&prediction_id=3&cfg_which_database=0&Itemid=1963
Der Link sollte so aussehen : http://svdoerpum.de/index.php?option=com_sportsmanagement&view=predictionranking&cfg_which_database=0&prediction_id=3&pggroup=0&pj=32:1-bundesliga-2017-2018&r=488:1.%20Spieltag&pggrouprank=0&type=0&from=0&to=0&Itemid=1963

**Comment by sigal** [comment]
Da hast du recht.
Trivialer sind aber das nicht Laden von jQuerry und sämtliches ignorieren oder abschalten der Template JS-Dateien.
Auf deiner, wie auch auf meiner  Seite funktionieren die Pulldown-Menüs nicht mehr, oder irre ich mich schon wieder?

Dieses Verhalten wäre als erstes wieder abzustellen. Es kann nicht sein, dass eine Komponente so einen Einfluss auf die Templates hat.

**Comment by svdoldie** [comment]
Nein, egal welche wie alles konfiguriert ist, irgendwetwas funktioniert nicht. Entweder das Menü, oder die Tabs, oder das Pulldown geht nur einmal, dann muss erst wieder die Seite neu geladen werden usw.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Das Problem mit dem Projekt im Link ist behoben.
Aber der Einwand von Stony wegen jquery ist berechtigt, 
und er hat anscheinend auch ne Lösung dafür gefunden.
Vielleicht kannst du seine Lösung dafür ins Git einbauen?

**Comment by diddipoeler** [comment]
Änderungen sind im Github.

**Comment by svdoldie** [comment]
Danke, gleich viel besser :+1:
