### ISSUE TITLE
Kalendermodul - Änderung des Anzeigezeitraum geht nur, wenn man angemeldet ist

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#477]
Das Ändern des Monats oder des Jahres funktioniert nur,
wenn man angemeldet ist.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
Bei mir auf der Seite funktioniert es. Siehst Du ganz unten.

**Comment by svdoldie** [comment]
Bei mir existiert es noch ;-(

**Comment by diddipoeler** [comment]
Also kann ich den Issue jetzt schließen.

**Comment by svdoldie** [comment]
da es auf der Testseite funktioniert, kann hier zu gemacht werden
