### ISSUE TITLE
Bild zuweisen bei Mannschaft geht nicht

### ISSUE THREAD

**Issue by DFCDay** [diddipoeler/sportsmanagement#480]
Sofern ich einer Mannschaft ein Bild zuweisen möchte kommt eine Fehlermeldung:

Using $this when not in object context.

Hochladen des Bildes klappt. Aber auch die anzeige geht nicht.

**Comment by diddipoeler** [comment]
Mach mal bitte ein Update der Komponente.

**Comment by DFCDay** [comment]
Da muss ich jetzt mal blöd Fragen. Wie mache ich das?

Da ich ja nicht installieren kann kann ich die neue Version nicht einfach drüber "bügeln"

**Comment by diddipoeler** [comment]
Wenn die Komponente schon installiert ist, dann einfach den Button: JSM Github Update
anklicken. Es wird dann Aktualisiert.

**Comment by DFCDay** [comment]
Ok. Hoffe ich finde ihn.

**Comment by svdoldie** [comment]
Ganz oben links 😉

**Comment by DFCDay** [comment]
Ich bekomme dann eine Fehlermeldung  wie beim installieren. Das ist alles da bzw. wurde geschrieben:

```
Verzeichnis [ agegroups ] angelegt!
Verzeichnis [ clubs ] angelegt!
Verzeichnis [ clubs/large ] angelegt!
Verzeichnis [ clubs/medium ] angelegt!
Verzeichnis [ clubs/small ] angelegt!
Verzeichnis [ clubs/trikot_home ] angelegt!
Verzeichnis [ clubs/trikot_away ] angelegt!
Verzeichnis [ clubs/trikot ] angelegt!
Verzeichnis [ laender_karten ] angelegt!
Verzeichnis [ events ] angelegt!
Verzeichnis [ leagues ] angelegt!
Verzeichnis [ positions ] angelegt!
Verzeichnis [ divisions ] angelegt!
Verzeichnis [ person_playground ] angelegt!
Verzeichnis [ associations ] angelegt!
Verzeichnis [ flags_associations ] angelegt!
Verzeichnis [ persons ] angelegt!
Verzeichnis [ placeholders ] angelegt!
Verzeichnis [ predictionusers ] angelegt!
Verzeichnis [ playgrounds ] angelegt!
Verzeichnis [ projects ] angelegt!
Verzeichnis [ projectreferees ] angelegt!
Verzeichnis [ projectteams ] angelegt!
Verzeichnis [ projectteams/trikot_home ] angelegt!
Verzeichnis [ projectteams/trikot_away ] angelegt!
Verzeichnis [ rosterground ] angelegt!
Verzeichnis [ matchreport ] angelegt!
Verzeichnis [ seasons ] angelegt!
Verzeichnis [ sport_types ] angelegt!
Verzeichnis [ rounds ] angelegt!
Verzeichnis [ teams ] angelegt!
Verzeichnis [ flags ] angelegt!
Verzeichnis [ teamplayers ] angelegt!
Verzeichnis [ teamstaffs ] angelegt!
Verzeichnis [ venues ] angelegt!
Verzeichnis [ jl_images ] angelegt!
Verzeichnis [ statistics ] `angelegt!
```

Danach

Warnung

JFolder::create: Endlosschleife erkannt
Cannot create destination folder

Dann:

> Sports Management: Update der Komponente erfolgreich abgeschlossen1.0.58
> 
> Modul : mod_sportsmanagement_quickicon installiert!
> 
> Modul : mod_sportsmanagement_rquotes installiert!
> 
> Modul : mod_sportsmanagement_liveticker installiert!
> 
> Modul : mod_sportsmanagement_count_rekord installiert!
> 
> Modul : mod_sportsmanagement_ranking installiert!
> 
> Modul : mod_sportsmanagement_birthday installiert!
> 
> Modul : mod_sportsmanagement_club_birthday installiert!
> 
> Modul : mod_sportsmanagement_clubicons installiert!
> 
> Modul : mod_sportsmanagement_matches installiert!
> 
> Modul : mod_sportsmanagement_matchesslider installiert!
> 
> Modul : mod_sportsmanagement_new_project installiert!
> 
> Modul : mod_sportsmanagement_act_season installiert!
> 
> Modul : mod_sportsmanagement_playgroundplan installiert!
> 
> Modul : mod_sportsmanagement_playground_ticker installiert!
> 
> Modul : mod_sportsmanagement_randomplayer installiert!
> 
> Modul : mod_sportsmanagement_teamplayers installiert!
> 
> Modul : mod_sportsmanagement_teamstats_ranking installiert!
> 
> Modul : mod_sportsmanagement_top_tipper installiert!
> 
> Modul : mod_sportsmanagement_ajax_top_navigation_menu installiert!
> 
> Modul : mod_sportsmanagement_navigation_menu installiert!
> 
> Modul : mod_sportsmanagement_gcalendar installiert!
> 
> Modul : mod_sportsmanagement_calendar installiert!
> 
> Modul : mod_sportsmanagement_trainingsdata installiert!
> 
> Modul : mod_sportsmanagement_sports_type_statistics installiert!
> 
> Imagefolder : agegroups angelegt!
> 
> Imagefolder : clubs angelegt!
> 
> Imagefolder : clubs/large angelegt!
> 
> Imagefolder : clubs/medium angelegt!
> 
> Imagefolder : clubs/small angelegt!
> 
> Imagefolder : clubs/trikot_home angelegt!
> 
> Imagefolder : clubs/trikot_away angelegt!
> 
> Imagefolder : clubs/trikot angelegt!
> 
> Imagefolder : laender_karten angelegt!
> 
> Imagefolder : events angelegt!
> 
> Imagefolder : leagues angelegt!
> 
> Imagefolder : positions angelegt!
> 
> Imagefolder : divisions angelegt!
> 
> Imagefolder : person_playground angelegt!
> 
> Imagefolder : associations angelegt!
> 
> Imagefolder : flags_associations angelegt!
> 
> Imagefolder : persons angelegt!
> 
> Imagefolder : placeholders angelegt!
> 
> Imagefolder : predictionusers angelegt!
> 
> Imagefolder : playgrounds angelegt!
> 
> Imagefolder : projects angelegt!
> 
> Imagefolder : projectreferees angelegt!
> 
> Imagefolder : projectteams angelegt!
> 
> Imagefolder : projectteams/trikot_home angelegt!
> 
> Imagefolder : projectteams/trikot_away angelegt!
> 
> Imagefolder : associations angelegt!
> 
> Imagefolder : rosterground angelegt!
> 
> Imagefolder : matchreport angelegt!
> 
> Imagefolder : seasons angelegt!
> 
> Imagefolder : sport_types angelegt!
> 
> Imagefolder : rounds angelegt!
> 
> Imagefolder : teams angelegt!
> 
> Imagefolder : flags angelegt!
> 
> Imagefolder : teamplayers angelegt!
> 
> Imagefolder : teamstaffs angelegt!
> 
> Imagefolder : venues angelegt!
> 
> Imagefolder : jl_images angelegt!
> 
> Imagefolder : statistics angelegt!

Dann:

Die ZIP-Datei der Komponente [ https://github.com/diddipoeler/sportsmanagement/archive/master.zip ] konnte kopiert werden!Die Komponente [ COMPONENT ] konnte nicht installiert werden!
--

Das Modul [ MOD_SPORTSMANAGEMENT_ACT_SEASON ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_AJAX_TOP_NAVIGATION_MENU ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_BIRTHDAY ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_CALENDAR ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_CLUB_BIRTHDAY ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_CLUBICONS ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_COUNT_REKORD ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_GCALENDAR ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_LIVETICKER ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_MATCHES ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_MATCHESSLIDER ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_NAVIGATION_MENU ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_NEW_PROJECT ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_PLAYGROUND_TICKER ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_PLAYGROUNDPLAN ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_RANDOMPLAYER ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_RANKING ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_RQUOTES ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_SPORTS_TYPE_STATISTICS ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_TEAMPLAYERS ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_TEAMSTATS_RANKING ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_TOP_TIPPER ] wurde installiert!Das Modul [ MOD_SPORTSMANAGEMENT_TRAININGSDATA ] wurde installiert!
--

Als Debuginfo:

1017 | postArray ( ) 
project_id0
project_team_id0
team_id0
club_id0
-- | --


Bekomme deshalb immer noch die selbe Fehlermeldung:

0 Using $this when not in object context

**Comment by diddipoeler** [comment]
Jetzt bin ich mit dem Fehler mit meinem Latein am Ende.
**Warnung
JFolder::create: Endlosschleife erkannt
Cannot create destination folder**

Warum funktioniert das bei mir auf allen Plattformen ?

**Comment by DFCDay** [comment]
Gute Frage. Also wird es wohl in irgendeiner Form mit dem VPS zusammen hängen. Vielleicht was an der php.ini noch ändern? Die Frage ist was für einen Ordner er nicht erstellen kann..

**Comment by sigal** [comment]
Es hat sicher mit dem VPS Server zu tun.
Frage? Hast du denn Server inkl. ISPConfig selbst installiert.

Beim Update der Komponente schau mal in den Folder von /administrator/components/com_sportsmanagement/ inkl. allen darunter an gesiedelten Ordner, ob die Erstellzeit der Dateien mit der Installationszeit übereinstimmen.

Mir ist auf meinen angelegten VIRTUALBOX SERVER aufgefallen, dass trotz Fehlermeldung (übrigens die gleichen wie bei dir) die Dateien in diesen Ordnern alle neu angelegt, bzw. überschrieben werden.

Auch wenn man restrektiv das open_basedir abschaltet, erscheinen diese Fehler, was aber definitiv dann nicht sein darf, oder sollte.

Wie diddi schon geschrieben hat, bin auch ich momentan mit meinen Latein am Ende, da dieser Fehler definitiv nur mit dem ISPConfig Panel zum Vorschein kommt.

Auch der Fehler 0 Using $this when not in object context im Zusammenhang mit dem Zuweisen von einen Bild zu einer Mannschaft erscheint auf allen anderen Plattformen nicht.

Die Frage, was für einen Ordner er nicht erstellen kann, kann ich nur bei einer Erstinstallation von JSM auf dieser Serverform beantworten:

com_sportsmanagement im Ordner /administrator/components
com_sportsmanagement im Ordner /components

Werden diese Ordner manuel erstellt, wird auch die Komponente trotz Fehlermeldung installiert!! Warum auch immer.
Vieleicht mal beim Owner von ISPConfig nachfragen?

**Comment by DFCDay** [comment]
ISPConfig bin ich :D. Habe den Server selber aufgesetzt und ISPConfig als Administrationsoberfläche.
Was mich halt wunder ist, dass alle anderen Komponenten zu gehen scheinen. Also die die ich drauf gespielt habe.
Die Dateien haben nicht das Datum sondern das Datum 14.09. . Dieses ist das Datum an dem ich die Datei con svoldie benutzt habe. Die Backup-Installation. Damit ging es.

Das Datum wurde nur bei den Dateien geändert also z.b. der Sportsmanagement.php.

**Comment by sigal** [comment]
Wenn die Dateien gleichen Datums wie das Update_Datum sind, wurden das Update eingespielt.
So hab ich das doch vorhin geschrieben
Frage? Welche Datei hast du von svdoldie?

**Comment by DFCDay** [comment]
Ich hatte sein AKEBA Backup benutzt um alles einzuspielen da das normale Installieren durch den Fehler ja nicht klappt. Es haben aber nur die Dateien das Update in der ersten Ebene. Alle Ordner den 14.09. Somit nicht das Update-Datum. Update habe ich gestern versucht.

Auch ist der Fehler vom Bild immer noch vorhanden. Somit gehe ich davon aus die die wichtigen Dateien nicht geändert worden sind. Ist echt schon komisch. Vorallem verstehe ich nicht warum alles andere geht.

**Comment by sigal** [comment]
Und das Akeeba Backup hast du von svdoldie erhalten?

Auf meinem ISPConfig Testserver hab ich diese Fehlermeldung nicht.

**Comment by DFCDay** [comment]
Ja. Das bietet er ja an. Hmm

**Comment by svdoldie** [comment]
@DFCDay : Wie kommst du darauf, das ich ein Akeeba Backup anbiete?

**Comment by DFCDay** [comment]
Hmm. War das nicht von Dir. Ah Mist war Stony. Sorry vertan.

**Comment by svdoldie** [comment]
;-)

**Comment by DFCDay** [comment]
Ich werde es mal so versuchen. Ich setzte meinen Server noch mal neu auf. Ob Ubuntu/Debian oder sonstiges dürfte ja normal egal sein. Das setze ich ISPConfig auch noch mal auf und schaue was passiert.

**Comment by DFCDay** [comment]
Tja. Auch nach kompletten neuaufsetzen des Servers das selbe Spielchen. Soweit auch nur das Minimum installiert. Also Apache, php, Mysql. 
Was halt echt komisch ist, ist dass alle anderen Komponenten bis dato gehen. Das gibt es doch gar nicht.

**Comment by sigal** [comment]
Hab mal einen Link. Leider nur auf Englisch. Damit läßt sich herausfinden wo es wirklich hakt.
https://www.rsjoomla.com/support/documentation/general-faq/troubleshooting-extension-installation-errors.html

**Comment by DFCDay** [comment]
So, Es lag irgendwie an ISPConfig. Aber egal was ich eingestellt habe. Es ging nicht. Nun habe ich auf ein anderes Interface gewechselt und es geht direkt und das sogar schneller. Woran es aber an ISP Config gelegen hat kann ich wirklich nicht sagen. SOnst hätte ich gerne geholfen.

**Comment by diddipoeler** [comment]
Kann ich den Issue jetzt schließen ?

**Comment by DFCDay** [comment]
Ah ja. Sorry. Klar kann dicht gemacht werden.
