### ISSUE TITLE
Backend - Mannschaft ändern im Projekt- Es werden nicht alle Mannschaften angezeigt

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#481]
Wenn man in einem Projekt eine Mannschaft gegen eine andere tauschen möchte,
werden in dem Auswahlfeld nicht alle in der Datenbank gespeicherten Mannschaften angezeigt.

**Comment by diddipoeler** [comment]
Wurden auch die Mannschaften der selben Saison wie im Projekt zugeordnet ?

**Comment by svdoldie** [comment]
Jetzt ja ;-) 
Darauf wäre ich nicht gekommen.
Ich schließe das hier mal
