### ISSUE TITLE
Spieltagsübersicht TopTipper Modul Übersichtslink falsch

### ISSUE THREAD

**Issue by dei71** [diddipoeler/sportsmanagement#482]
Der Gesamtübersichtslink für die Spieltagspunkte verweist auf die Gesamtpunkte. Der sollte ebenfalls auf die Spieltagspunkte verweisen.

**Comment by diddipoeler** [comment]
Mach mal bitte ein Update der Komponente.

**Comment by dei71** [comment]
Hallo Diddi,

der link verweist jetzt auch bei der Gesamtpunkteansicht auf die Spieltagspunkte. 

www.tippfreundschaft.de

**Comment by diddipoeler** [comment]
Bitte die Einstellung im Modul überprüfen !

**Comment by dei71** [comment]
![img_0103](https://user-images.githubusercontent.com/3773449/31274354-d9ea2658-aa92-11e7-82d6-c5cf0c120c4a.PNG)
![img_0104](https://user-images.githubusercontent.com/3773449/31274352-d9e44a62-aa92-11e7-8f2d-8dab67f56181.PNG)
![img_0105](https://user-images.githubusercontent.com/3773449/31274353-d9e9690c-aa92-11e7-835e-a2a4e41c6322.PNG)

Einmal Spieltagspunkte und das letzte Gesamtpunkte

**Comment by diddipoeler** [comment]
Was sollen mir die Bilder sagen ?

**Comment by dei71** [comment]
Ich habe im Modul die entsprechenden Werte gesetzt. die oberen 2 Bilder der aktuelle Spieltag und unten alle Spieltage.

**Comment by diddipoeler** [comment]
Sieht doch jetzt alles super aus oder ?

**Comment by dei71** [comment]
Ja aber der link der Spieltagspunkte geht auf die Gesamtpunktübersicht aller Tipper.

**Comment by dei71** [comment]
Super klasse und passt. Vielen Dank Diddi!!!
