### ISSUE TITLE
Fehler Ergebnisseite

### ISSUE THREAD

**Issue by sv1924** [diddipoeler/sportsmanagement#489]
Hallo,

ich habe beim Aufruf der Ergebnisseite (Spielplan) folgende Fehlermeldung, bzw. werde ich immer aufgefordert mich anzumelden. Nachdem ich ein paar mal auf Abbrechen klicke wird die Seite angezeigt.

http://sv-1924.de/spielplan-gesamt

wie kann ich hier ein Bild einfügen?

Gruß Danny

**Comment by sigal** [comment]
momentan greifen vom frontend aus, aufrufe auf backend funtionen zurück.
Bei absicherung des admininistrator folders mittels passwortschutz, gibt es die von dir genannten "fehlermeldungen".
diddi weiss sicher, was ich damit anspreche.

**Comment by diddipoeler** [comment]
Bitte den Passwortschutz für das Verzeichnis administrator/components/com_sportsmanagement aufheben.

**Comment by diddipoeler** [comment]
Ist das jetzt erledigt ?

**Comment by sv1924** [comment]
ja ist erstmal erledigt, Danke
