### ISSUE TITLE
Fatal error: Class 'JSMModelLegacy' not found in .../administrator/components/com_sportsmanagement/models/databasetool.php on line 57

### ISSUE THREAD

**Issue by boxr** [diddipoeler/sportsmanagement#490]
Webseite funktioniert nicht mehr

**Comment by boxr** [comment]
Hallo Diddi,

 

Danke erstmal für die schnelle Reaktion 

habe ein Update durchgeführt, Fehlermeldung ist immer noch, habe erstmal eine vorherige Version der Datei hochgeladen mit der es funktioniert.

 

Im aktuellen File steht: Line 57: class sportsmanagementModeldatabasetool extends JSMModelLegacy

Im alten: Line 57: class sportsmanagementModeldatabasetool extends JModelAdmin

 

Gruß

Siggi

 

Von: diddipoeler [mailto:notifications@github.com] 
Gesendet: Montag, 4. Dezember 2017 14:00
An: diddipoeler/sportsmanagement <sportsmanagement@noreply.github.com>
Cc: boxr <boxr@gmx.net>; Author <author@noreply.github.com>
Betreff: Re: [diddipoeler/sportsmanagement] Fatal error: Class 'JSMModelLegacy' not found in .../administrator/components/com_sportsmanagement/models/databasetool.php on line 57 (#490)

 

Mach mal bitte ein Update der Komponente !

**Comment by diddipoeler** [comment]
Welche Joomla Version ?

**Comment by boxr** [comment]
Joomla 3.8.2

 

Von: diddipoeler [mailto:notifications@github.com] 
Gesendet: Montag, 4. Dezember 2017 14:47
An: diddipoeler/sportsmanagement <sportsmanagement@noreply.github.com>
Cc: boxr <boxr@gmx.net>; Author <author@noreply.github.com>
Betreff: Re: [diddipoeler/sportsmanagement] Fatal error: Class 'JSMModelLegacy' not found in .../administrator/components/com_sportsmanagement/models/databasetool.php on line 57 (#490)

 

Welche Joomla Version ?

**Comment by PhantoSGE** [comment]
Bis zum update der Komponente vor ein paar Minuten hat bei mir noch alles funktioniert.
Nach dem update:
Fatal error: Class 'JSMModelLegacy' not found in /administrator/components/com_sportsmanagement/models/databasetool.php on line 58

**Comment by PhantoSGE** [comment]
Im Backend erhalte ich folgende Fehlermeldung wenn ich JSM Stammdaten auswähle
Fatal error: Call to a member function clear() on string in /administrator/components/com_sportsmanagement/models/databasetool.php on line 861

Gruß

**Comment by diddipoeler** [comment]
Mach mal bitte ein Update der Komponente.

**Comment by diddipoeler** [comment]
http://www.fussballineuropa.de/index.php/forum?view=topic&catid=264&id=4597#12689

**Comment by diddipoeler** [comment]
Kann ich das jetzt schließen ?

**Comment by PhantoSGE** [comment]
Ist bei mir behoben. Danke.
