### ISSUE TITLE
Modul Vereins Icons

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#491]
Wäre es möglich statt dem Vereinslogo auch das Mannschaftsfoto bzw. Mannschaftswappen auszuwählen?

Danke und Gruß

**Comment by diddipoeler** [comment]
Bitte einmal testen.

**Comment by PhantoSGE** [comment]
Super. Funktioniert 👍 
Nur als Hintergrund. Ich habe in der Liga Mannschaften aus einem Verein(gleiches Vereinswappen) aber unterschiedlichen Mannschftswappen.

**Comment by diddipoeler** [comment]
Welche Mannschaftswappen ?

**Comment by PhantoSGE** [comment]
Unter den Stammdaten kann man für Mannschaften ein unterschiedliches Bild zu den Vereinswappen(150/50/21) hinterlegen

**Comment by PhantoSGE** [comment]
Hallo Diddi,
wäre es Möglich statt dem Mannschaftsfoto das Mannschaftsbild zu hinterlegen?
Stammdaten > Mannschaft > Bild
(images/com_sportsmanagement/database/teams/xxx.png)

Gruß

**Comment by diddipoeler** [comment]
Bitte einmal testen.

**Comment by PhantoSGE** [comment]
Funktioniert. Tausend dank
