### ISSUE TITLE
Modul Matches

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#495]
Bei der Anzeige des Modul Matches im Frontend erscheint folgende Fehlermeldung vor den Spielen.
Notice: Undefined property: stdClass::$actplaying in /modules/mod_sportsmanagement_matches/helper.php on line 164

Der Fehler erscheint sobald ich mehr als ein Spiel anzeigen lassen.

Gruß
Sven

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Sieht gut aus.
