### ISSUE TITLE
Ergebnisse lassen sich nicht speichern

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#496]
Wenn man im Backend Ergebnisse speichern möchte, wird folgende Fehlermeldung angezeigt:

Es ist ein Fehler aufgetreten!

1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :+1:
