### ISSUE TITLE
Menü: Ergebnis-Tabellen Anzeige

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#497]
Ich lasse im Menüeintrag Ergebnis-Tabellen Anzeige Results zuerst anzeigen. Sobald ich auf Tabelle klicke ist der Reiter Ergebnisse verschwunden
![mit](https://user-images.githubusercontent.com/9608697/33855318-d92a3648-dec4-11e7-926c-48925c955b8c.PNG)
![ohne](https://user-images.githubusercontent.com/9608697/33855321-dbc896a6-dec4-11e7-9c03-811b15fd2fcf.PNG)

**Comment by diddipoeler** [comment]
Auf welcher Internetseite ?

**Comment by PhantoSGE** [comment]
Ich habe die die Zugangsdaten per PM auf der HP geschickt.

Gruß

**Comment by diddipoeler** [comment]
Da wird 2 mal jQuery geladen.
Wenn ein Template jQuery läd, dann das jQuery plugin ausschalten.

**Comment by PhantoSGE** [comment]
Habe es ausgestellt aber der gleiche Effekt.
Werde mich damit mal beschäftigen. 
Danke für den Hinweis.

Gruß
