### ISSUE TITLE
Fehler bei der Komponenten-Installation

### ISSUE THREAD

**Issue by Bastian007** [diddipoeler/sportsmanagement#500]
Bekomme folgende Fehlermeldung wenn ich versuche die Komponent zu aktualisieren:

> Warnung
> JInstaller: :Install: SQL-Fehler Unknown column 'rankingparams' in '#__sportsmanagement_division'
> Erweiterung „Aktualisierung“: SQL Fehler beim Ausführen der Abfrage: „DB-Funktion mit Fehlercode 1054 fehlgeschlagen!
> Unknown column 'rankingparams' in '#__sportsmanagement_division'
> SQL =
> 
> `ALTER TABLE `#__sportsmanagement_division` CHANGE `rankingparams`  `rankingparams` TEXT NULL DEFAULT NULL ;`
> 
> “

Viele Grüße, Bastian
![2017-12-19_11-22-41](https://user-images.githubusercontent.com/12425311/34163461-16280fc6-e4d7-11e7-8eb0-831b26bbd9b1.jpg)

**Comment by diddipoeler** [comment]
Bitte die Komponente deinstallieren und dann installieren.

**Comment by Bastian007** [comment]
Hat funktioniert. Danke!
