### ISSUE TITLE
Backend-View: jlxmlimports Layout: default

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#508]
Der Versuch, eine JLG aus JL, zu importieren endet in einem Fehler.

![image](https://user-images.githubusercontent.com/9608697/34715573-603d49c6-f52d-11e7-944c-229cfc920248.png)

![image](https://user-images.githubusercontent.com/9608697/34715756-fa9f6134-f52d-11e7-99a3-0b601fa21e06.png)

Gruß
Phanto

**Comment by diddipoeler** [comment]
Bitte einmal die JLG Datei zusenden, oder hier anhängen.

**Comment by PhantoSGE** [comment]
[saison-201718-180109-112352.zip](https://github.com/diddipoeler/sportsmanagement/files/1614723/saison-201718-180109-112352.zip)

**Comment by svdoldie** [comment]
Ich kann den Fehler bestätigen!!!

**Comment by diddipoeler** [comment]
Bitte ein Update der Komponente vornehmen und danach testen.

**Comment by PhantoSGE** [comment]
Perfekt. Funktioniert wieder. Dankeschön
