### ISSUE TITLE
Neu-Installation schlägt fehl

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#511]
Wenn ich JSM auf meiner neu installierten Testseite installieren möchte,
erscheint nur folgende Fehlermeldung:
Warnung

JInstaller: :Install: SQL-Fehler Table 'joomla_1.#__sportsmanagement_person' doesn't exist

Erweiterung „Aktualisierung“: SQL Fehler beim Ausführen der Abfrage: „DB-Funktion mit Fehlercode 1146 fehlgeschlagen!
Table 'joomla_1.#__sportsmanagement_person' doesn't exist
SQL = ALTER TABLE  `#__sportsmanagement_person` ADD  `bank_code_number` VARCHAR( 100 ) NULL DEFAULT  '';
“

**Comment by sigal** [comment]
Kann ich nicht nachvollziehen.
Hab gerade JSM neu auf jungfräüliches Joomla3 u. Joomla4 installiert.

**Comment by svdoldie** [comment]
Hmm. Hab es jetzt auch nochmal propiert.
Funktioniert einwandfrei. 
Dann schließe ich hier mal ;-)
