### ISSUE TITLE
Fehlermeldung bei Aufruf von JSM

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#514]
Ruft man JSM im Backend auf, erscheint nur folgende Fehlermeldung

Es ist ein Fehler aufgetreten!

0 Cannot use assign-op operators with string offsets

**Comment by svdoldie** [comment]
Betrifft nur die Seite Stammdaten

**Comment by diddipoeler** [comment]
Kann ich nicht nachvollziehen.

**Comment by svdoldie** [comment]
Sorry, war mein Fehler.
Ich hatte PHP auf 7.1.12 gestellt.
Mit 7.0.26 ist alles in Ordnung
