### ISSUE TITLE
Spielplansortierung nach Datum erzeugt Anzeigefehler

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#515]
Lässt man die Anzeige des Teamspielplans nach Datum sortieren,
wird der Spielplan nicht mehr angezeigt.
Siehe http://svdoerpum.de/index.php?option=com_sportsmanagement&view=teamplan&cfg_which_database=0&s=2:2017-2018&p=22:verbandsliga-nord-2017-2018&tid=13:sv-doerpum&Itemid=1910

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Der Spielplan wird jetzt zwar angezeigt. Aber nicht nach Datum sortiert.
Und die Anzeige der Team ist "verzerrt"

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Sieht schon besser aus. Aber die Sortierung stimmt noch nicht.
Siehe oben angegeben Link

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
leider keine Änderung

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Top 👍 Läuft :-)
