### ISSUE TITLE
Kaderanzeige erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#516]
Bei der Anzeige des Kaders erscheint nur eine weiße Seite.
Die Fehlermeldung dazu ist:
Fatal error: Using $this when not in object context in /var/www/vhosts/svdoerpum.de/svdoerpum.de/components/com_sportsmanagement/models/roster.php on line 561

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft wieder 👍
