### ISSUE TITLE
Speichern der Personbearbeitung erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#517]
Wenn man bei der Bearbeitung einer Person eines Teams auf speichern klickt,
erscheint folgende Fehlermeldung:
     1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND `persontype`=' at line 3

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Die Fehlermeldung ist weg und die Projektposition wird gespeichert :+1: 
Die Position aus den Stammdaten wird aber nicht gezogen, wenn sie das denn sollte.
Eine Änderung im Pulldown wird nicht gespeichert

**Comment by svdoldie** [comment]
Änderungen in den Reitern Personen-Stammdaten und Erweitert werden ebenso nicht gespeichert

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Personen-Stammdaten ändern funktioniert jetzt, erweitert noch nicht

**Comment by diddipoeler** [comment]
Wie erweitert ?

**Comment by svdoldie** [comment]
Änderungen im Reiter "Erweitert" werden nicht gespeichert

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Fehler ist noch  vorhanden

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :+1:
