### ISSUE TITLE
J4 backend

### ISSUE THREAD

**Issue by appukonrad** [diddipoeler/sportsmanagement#518]
hi, I've prepared backend files for J4.
It uses the standard J4 bootstrap, awesomefont and flexbox + css3

if you are interested, you can continue to work
 ##
![screenshot_20180117_122353](https://user-images.githubusercontent.com/5821245/35040676-5783ea96-fb82-11e7-9b04-729deb9fd66f.png)

**Comment by diddipoeler** [comment]
many thanks. i´m interested.

**Comment by diddipoeler** [comment]
please send a request.
thanks.
