### ISSUE TITLE
Designvorlage  Alle Teams

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#520]
Hallo,
für den Menütyp "Alle Mannschaften in JSM" finde ich im Backend keine Designvorlage die eine Auswirkung auf die Seite hat.
index.php?option=com_sportsmanagement&view=allteams&use_current_season=1

Gruß
Phanto

**Comment by diddipoeler** [comment]
Man benötigt auch keine Designvorlage, da dass nur ein Menüeintrag ist,
der alle Daten anzeigt.
Wenn die Erläuterung für Dich in Ordnung ist, schließe ich den Issue.

**Comment by PhantoSGE** [comment]
Danke, soweit so klar. Allerdings würde ich daran gerne ein paar Veränderungen machen.
Bildgröße, Spalte Internetseite ausblenden ... 

Viele Grüße

**Comment by diddipoeler** [comment]
Ah verstanden.
Setze den Status mal auf Userwunsch.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Funktioniert. Danke
