### ISSUE TITLE
Ereigniss hinzufügen. MatchID fehlt

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#521]
Hallo Diddi,

wenn ich im Backend ein Ereignis hinzufüge wird dem Eintrag in der DB keine MatchID hinzugefügt
![image](https://user-images.githubusercontent.com/9608697/35509205-95092618-04f3-11e8-9603-1d451dbe7b20.png)

![image](https://user-images.githubusercontent.com/9608697/35509230-b17f65d2-04f3-11e8-88df-efcc5faf8e09.png)

Viele Grüße

**Comment by diddipoeler** [comment]
Bitte ein Update der Komponente machen und
danach noch einmal testen.

**Comment by PhantoSGE** [comment]
Danke. Die MatchID wird hinzugefügt.
Folgendes funktioniert im Fenster "Ereignis hinzufügen" noch nicht.
-Ereignis löschen
-Nach dem hinzufügen wird die Liste nicht aktualisiert.

Gruß

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Noch keine Veränderung. Ich kann Ereignisse hinzufügen aber nicht löschen.
Nach dem hinzufügen wird nicht aktualisiert. Sprich der Eintrag steht scheinbar unbearbeitet da. Wenn ich das Fenster schließe und wieder öffne ist es eingetragen,

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Leider keine Veränderung bei mir.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Löschen funktioniert. 
Beim speichern wird es noch nicht direkt angezeigt. Erst nach erneutem öffnen des Fensters

**Comment by diddipoeler** [comment]
Bei mir wird es angezeigt.
Direkt unter der Eingabe der Kommentare.

**Comment by PhantoSGE** [comment]
Es wird als letzter Eintrag in der Eingabemaske angezeigt.
![image](https://user-images.githubusercontent.com/9608697/36379451-eac66a66-157e-11e8-8328-0f6b401c999e.png)
Wenn ich speichere wird der Eintrag aber nicht in die Liste eingetragen, sondern bleibt in der Maske stehen. Ich denke das kommt zur Verwirrung wenn man mehrer Ereignisse einträgt.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Jetzt taucht es unter der Eingabe auf und die Eingabe ist noch gefüllt.
![image](https://user-images.githubusercontent.com/9608697/36381443-de4a5688-1585-11e8-9d4b-a0c41f4ed543.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Nach dem Speichern werden die Eingabefelder geleert. 

Das neu gespeichertere Ereignis wird unter dem Eingabefeldern nur teilweise angezeigt. Ist das so beabsichtigt?
![image](https://user-images.githubusercontent.com/9608697/36384581-11032aaa-1590-11e8-8a2e-4c98932c6d2b.png)

**Comment by diddipoeler** [comment]
So, sieht es jetzt besser aus ?

**Comment by PhantoSGE** [comment]
Super. Danke.
