### ISSUE TITLE
Backend: Eingabe Ereignisse

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#522]
Hallo Diddi,

bei dem Aufruf der Ereignisse im Backend werden Ereignisse anderer Vereine angezeigt.
![image](https://user-images.githubusercontent.com/9608697/35509920-5f4770ae-04f6-11e8-9165-cce28fe5ff62.png)

Gruß

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Kann geschlossen werden. Aktuelle bug in #521
