### ISSUE TITLE
Backend: Template [ Spielberichts Anzeige ] bearbeiten

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#523]
Hallo Diddi,

die Auswahl "Kader am Spielfeld anzeigen" lässt sich im Backend nicht auf Nein stellen.
Sobald man speichert steht es wieder auf Ja.
Generell die Möglichkeit das Spielfeld auszustellen wäre wünschenswert.

Gruß

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Passt. Danke dir.
Gruß
