### ISSUE TITLE
Frontend: Matchreport Anzeige Trikots

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#524]
Hi Diddi,

in o.a. Datei verweist das Shirt auf
'images/com_sportsmanagement/database/teamplayers/shirt.php?text='
und es wird kein Image angezeigt.
![image](https://user-images.githubusercontent.com/9608697/35513474-7f7be758-0503-11e8-986a-81770e628b6f.png)

Leider erklärt sich mir der Inhalt die shirt.php nicht.

Edit: Die PHP funktioniert bei mir solange ich direkten Zugriff zulasse.
//defined( '_JEXEC' ) or die( 'Restricted access' ); (auskommentiert)...

![image](https://user-images.githubusercontent.com/9608697/35513512-9c9fba1c-0503-11e8-9132-f667230709d5.png)

Gruß

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
