### ISSUE TITLE
Menü: Ereignis-Tabellenanzeige

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#528]
Hallo Diddi,

wenn ich den o.a. Menüeintrag zum hinzufügen auswähle, erscheint folgende Fehlermeldung.
![image](https://user-images.githubusercontent.com/9608697/35626707-d14df9c4-0696-11e8-8b59-d6cf93658b68.png)

Gruß
Phanto

**Comment by PhantoSGE** [comment]
Danke. Die Fehlermeldung ist weg,
Allerdings noch folgendes:
-Hilfreich wäre im Backend eine Auswahl der Häufigkeit Auf/Absteigend.
-Ich wähle ein Ereignis aus, es werden aber alle Ereignisse angezeigt.
-Ich wähle ein Ereignis aus, es werden aber alle Ereignisse angezeigt.
-Eine Mehrfachauswahl der Ereignisse wäre auch super.

Gruß
Phanto

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Leider funktioniert es noch nicht komplett.

Sortierung funktioniert leider nicht.
![image](https://user-images.githubusercontent.com/9608697/35674199-23cead4e-0744-11e8-9ae0-fa2e68c0b0e3.png)

Es werden nur 20 Einträge angezeigt mit einem Menü zum blättern. Sobald ich auf die nächste Seite gehe fängt die Platzierung wieder bei 1 an.

Wähle ich kein Ereignis aus werden von allen Ereignissen 5 angezeigt. (top :-))
Allerdings werden manche Ereignisse gar nicht angezeigt wenn ich sie alleine auswähle.

Gruß
Phanto

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Sieht schonmal sehr gut aus. 
Es wird allerdings noch nicht die ausgewählte Saison genommen.
In der Liste sind die Spieler doppelt.

![image](https://user-images.githubusercontent.com/9608697/35681645-510c42a2-075e-11e8-9855-cbb6d24112c1.png)

![image](https://user-images.githubusercontent.com/9608697/35681629-411a434e-075e-11e8-9f2f-c8b2c17ee4bb.png)

![image](https://user-images.githubusercontent.com/9608697/35681674-6f1d5ac4-075e-11e8-91c2-081afe1f6b96.png)


![image](https://user-images.githubusercontent.com/9608697/35681683-77d9a4ec-075e-11e8-9bc7-a0b66b1efcf5.png)


Gruß
Phanto

**Comment by PhantoSGE** [comment]
Ich nochmal.
Schwer zu erklären. Wenn ich kein Ereignis auswähle werden die Top5 angezeigt.
Wenn ich allerdings nur eines der Ereignisse auswähle bekomme ich keine Ausgabe. Nur einen leeren Bereich.
Vielleicht hilft es wenn ich dir die zugangsdaten zukommen lasse.

In der Überschrift ist auch noch ein Fehler
![image](https://user-images.githubusercontent.com/9608697/35683800-5cc2c204-0765-11e8-9674-f4bf2c23c126.png)

Gruß
Phanto
