### ISSUE TITLE
Ereignisse werden nicht in Standardausgabe des Kaders angezeigt

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#529]
Ereignisse werden nicht in Standardausgabe des Kaders angezeigt,
wohl aber in der Spieler-Vistenkarte.

siehe http://svdoerpum.de/jsm/index.php/kader

**Comment by PhantoSGE** [comment]
Ereignisse werden angezeigt, allerdings alle Ereignisse der Projekt in JSM.

**Comment by svdoldie** [comment]
Bei mir ist alles, wie gewünscht.
Es werden die Ereignisse angezeigt, die ich den Positionen zu geordnet habe 👍

**Comment by PhantoSGE** [comment]
So wird es bei mir angezeigt
![image](https://user-images.githubusercontent.com/9608697/35678391-78760b4e-0753-11e8-93de-2062546e3b8d.png)

Allerdings sind es das total beider Saisons.
![image](https://user-images.githubusercontent.com/9608697/35678411-8c45e4a0-0753-11e8-9f1f-8e22e8d092c2.png)

Gruß
Phanto

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Bei mir ist alles korrekt :+1:

**Comment by PhantoSGE** [comment]
Uups, Hab es wohl Übersehen das zu testen.
Sieht aber gut aus bei mir.
