### ISSUE TITLE
Userwunsch: Timeline auf Spielfeld

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#537]
Ich habe folgendes auf der Seite des 1.FFC Oberusrsel gesehen.
Das wäre doch auch etwas für uns ;-)
siehe http://www.ffvoberursel.de/index.php/spielplaene/frauen-i/matchreport/38-fgl-frankfurt-17-18/2688

**Comment by diddipoeler** [comment]
Mal bitte mit vorsicht testen.

**Comment by svdoldie** [comment]
Sieht noch ein bisschen durcheinander aus 
http://svdoerpum.de/jsm/index.php/component/sportsmanagement/matchreport/0/0/1-projekt-1/74-team-1_team-2

**Comment by svdoldie** [comment]
height jeweils auf 47px, dann passt es bei mir

**Comment by diddipoeler** [comment]
OK. Habe ich übernommen.

**Comment by svdoldie** [comment]
Passt 👍  Sieht gut aus :-)

**Comment by svdoldie** [comment]
mit den neuen Symbolen sieht es noch besser aus 👍
