### ISSUE TITLE
Fehlermeldung bei XML Import

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#538]
Bei dem Importieren einer .jlg bekomme ich folgende Fehlermeldung angezeigt.
Kann ich die alten Daten irgendwie im Vorfeld aufbereiten um den Fehler zu vermeiden?

![image](https://user-images.githubusercontent.com/9608697/35736552-bd548e86-0828-11e8-838a-34b60941c568.png)

[saison-201213-180202-142803.zip](https://github.com/diddipoeler/sportsmanagement/files/1689550/saison-201213-180202-142803.zip)

Vielen Dank
Phanto

**Comment by sigal** [comment]
Der Import von schon vorhandenen Peronen in der Datenbank macht auch keinen Sinn.
Daher - skipping import of Teamplayer-ID (Überspringe Import des Teamspielers mit ID 100 etc) da schon in Datenbank vorhanden.

**Comment by PhantoSGE** [comment]
Die geskippten TeamPlayer sind aber nach dem Import nicht vorhanden

**Comment by diddipoeler** [comment]
Gibt es schon neue Erkenntnisse ?

**Comment by diddipoeler** [comment]
Da es hier kein Feedback gibt, wird geschlossen !
