### ISSUE TITLE
Spieler Info Anzeige

### ISSUE THREAD

**Issue by ghin27** [diddipoeler/sportsmanagement#541]
Slider Layout Funktuniert nicht. Fehlermeldung auf der Seite.
Wenn man auf der Spieler Info Seite auf das Bild der Spieler anklickt, es eröffnet sich zwar das große Bild der Spieler in neuen Fenster,
aber es gibt kein zurück Button oder (X) Zeichen für ausschalten der neu eröffneten Seite.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Das Bild wird vergrößert dargestellt allerdings nicht in einem Modalfenster, sondern komplett auf der Seite des Spielerprofils. Siehe http://svdoerpum.de/index.php?option=com_sportsmanagement&view=player&cfg_which_database=0&s=2&p=22:Verbandsliga%20Nord%202017/2018&tid=13:SV%20Dörpum&pid=215:0&Itemid=1899

**Comment by diddipoeler** [comment]
Bei mir nicht.

**Comment by ghin27** [comment]
Der Fehlermeldung erscheint auf der Web-Seite nicht mehr. Danke für dein mühe didipoeler.
Ein bitte habe ich noch, wenn man auf der Spielerinfo Seite auf das Bild der person anklickt, es erscheint auf der gleichen Seite das große Bild der Person.
Gibts die möglichkeit ein zurück Buton oder ein "Zurück" wort zu erstellen?

**Comment by diddipoeler** [comment]
Bei mir nicht, da öffnet sich das Modalfenster !

**Comment by ghin27** [comment]
Bei mir leider im gleichen fenster.

**Comment by svdoldie** [comment]
kann es an den Einstellungen im jquery bzw. bootstrap-Modul liegen?
