### ISSUE TITLE
Personen anlegen

### ISSUE THREAD

**Issue by ghin27** [diddipoeler/sportsmanagement#542]
Nach Daten eingabe der Personen, wenn mann Button Speichern anklickt, anstatt nur zu speichern, macht der JSM Kompenent Speichern und eröffnet neue Personen Daten eingabe Seite.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by ghin27** [comment]
Soll ein Update gemacht werden und danach Testen?

**Comment by diddipoeler** [comment]
Ja bitte.

**Comment by ghin27** [comment]
Habe ganz normal über Stammdaten--> Update (button) update gemacht, bei mir in der Kompenent hat sich nichts geändert

**Comment by svdoldie** [comment]
Der Fehler existiert noch

**Comment by diddipoeler** [comment]
Kannst Du das bitte genauer beschreiben ?
Ich meine das Anlegen einer Person.

**Comment by svdoldie** [comment]
Das Problem liegt beim Button "Speichern". Benutzt man diesen, wird die Person mit den eingegebenen Daten angelegt. Und es wird wieder die Eingabemaske für eine neue Person angezeigt. Quasi wie ein Button "Speichern und neu" Der Button "Speichern und schließen" funktioniert wie er soll

**Comment by diddipoeler** [comment]
Den Fehler kann ich nicht nachvollziehen.

**Comment by ghin27** [comment]
Genau so, wie svdoldie es geschrieben hat.

**Comment by diddipoeler** [comment]
Bei mir tritt der Fehler nicht auf.

**Comment by ghin27** [comment]
Komisch, ich habe bis jetzt ca über 600 personen angelegt bei keinem hat es funktioniert. Ich musste jedesmal "speichen/schließen" anklicken und wieder den Person finden damit ich an den angelegten Person Landesverband vergeben konnte.

**Comment by sigal** [comment]
Bei mir tritt der Fehler jetzt auch nicht auf.
Joomla 3.8.5
PHP 7.0.22 oder 7.1.14
MySQL 5.7.21

**Comment by svdoldie** [comment]
Hmmm. Bei mir zu Hause tritt der Fehler auch nicht auf.
Weder auf der Test- noch auf der Hauptseite

**Comment by diddipoeler** [comment]
Einmal die Komponente deinstallieren.
Den Ordner tmp leeren und den Joomla Cache löschen.
Dann die Komponente neu installieren.

**Comment by ghin27** [comment]
Wenn ich den Kompenent deinstalliere, dann gehen mir die ganze Projekte (personen, Spieltage usw.) alles verloren.

**Comment by diddipoeler** [comment]
Nein, wer hat das gesagt ?

**Comment by ghin27** [comment]
Keiner, das war nur behauptung von mir.

**Comment by svdoldie** [comment]
Die Daten bleiben alle erhalten. Zur Not kannst du ja ein Backup deiner Datenbank per phpmyadmin machen

**Comment by ghin27** [comment]
Ok, zu sicherheit mache ich ein Backup der datenbank phpmyadmin. 
Danke für die Info.

**Comment by sigal** [comment]
Zur Sicherheit vor dem Gebrauch von phpmyadmin ein Backup der Webseite mit Akeeba oder mit EJB - Easy Joomla Backup erstellen.

Glaubt mir - spart manchviel viel Ärger und Aufwand. ;-)

**Comment by ghin27** [comment]
Ich habe, wie Ihr es erwähnt habt, habe ich das Kompenent gelöscht und neu gedownloadet und installiert. Soweit alles Ok (auch kein Installationfehlermeldung aufgetreten). Sogar die angelegte Projekte, Personen, Spieltage waren nicht weg.
Das Problem:
Nach dem neu installieren der Kompenent, musste ich leider feststellen, das an der Stammdaten Basisdaten): Int. Verbänder, Position, Erreignisse, Altersgruppen (Button oder Menüs)
(Persönliche Daten). Personen, Sportstätten, Spielfeldposition (Button oder Menüs) nicht mehr dar waren oder nicht aktiv sind. Die sind einfach verschwunden.
Ich habe das Kompenent eimal über "datei hochladen" installiert wieder deinstalliert und ein über "von URL installieren" installiert.
Leider auch bei der zweiten Installation haben immer nocht die Buttons oder Menüs gefehlt (Menüs die ich oben aufgezählt habe).
PS.: Löschen neu installieren haben wir in der Test Seite durchgeführt

**Comment by sigal** [comment]
Alles in den Optionen freischalten!
 
[http://jsm-wiki.diddipoeler.de/index.php?title=Hauptseite#Basisdaten](url)

Bild im Wiki zum Vergrößern anklicken!

**Comment by ghin27** [comment]
sigal danke jetz ist oder sind Buttons aktiv. Bin leider irgendwie nicht darauf ankegommen.
Entschuldigung.

**Comment by ghin27** [comment]
jetz hatte ich die möglichkeit gehabt, das mit "Speichern" zu testen. Leider erfolglos war ich.
Wenn ich speichern anklicke, es wird zwar gespeichert aber das Kompenent macht auch gleich nach dem speichern neue Personen Daten eingabe seite auf, wie (Speichern&Neu).

**Comment by sigal** [comment]
Hab das jetzt auf 4 Seiten versucht.
Ich kann das nicht nachvollziehen!
Beim Speichern bleibt die Eingabemaske bei der ausgewählten Person.
Welche PHP-Version läuft?
Vielleicht hilft unter Installationstools -> Updates -> jsm_update_db_tables.php

**Comment by svdoldie** [comment]
Das Problem tritt bei mir immer dann auf, wenn ich beim anlegen gleich eine Saisonzuordnung vornehme. Lasse ich die weg, funktioniert alles einwandfrei

**Comment by ghin27** [comment]
Habe eben gerade das ausprobiert was der svdoldie schrieb. Da schliese ich mich an svdoldie an. 
Wenn ich, an ein angelegte Person kein Saison zuordne funktioniert das "Speichern".

**Comment by diddipoeler** [comment]
Aber die Saisons sind richtig zugeordnet ?

**Comment by svdoldie** [comment]
Ich teste gleich noch mal, aber ich bin mir eigentlich sicher, dass das korrekt war

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
nun tritt es auch auf, wenn keine Saison zugeordnet wurde

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft bei mir :+1:

**Comment by ghin27** [comment]
W
ie kann ich Update model.php durchführen?

**Comment by svdoldie** [comment]
Geht immer alles über JSM GitHub update

**Comment by ghin27** [comment]
Danke didipoeler bei mir läufts auch
