### ISSUE TITLE
Zuordnen der Personen an die Mannschaft

### ISSUE THREAD

**Issue by ghin27** [diddipoeler/sportsmanagement#544]
Nach zuweisung der Personen an die Manschaft, wenn mann sortierung nach "PID" oder "Position" anklickt, verscwindet der liste der Personen von der Seite, zeigt nur leere Seite.
Erst wenn man die Sortierung nach Namen anklickt, erscheint der Liste der Peronen wieder.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Test mit Bravour bestanden 👍

**Comment by ghin27** [comment]
Ich kann auch sigal bestätigen. Funktioniert 👍
