### ISSUE TITLE
Frontend Aufstellung bearbeiten: Wort "ajax"

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#551]
Wenn man im Frontend die Aufstellung bearbeitet, erscheint dort das Wort "ajax".
Das scheint an folgender Datei zu liegen: form_editlineup_substitutions.php

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Die Anzeige ist weg, allerdings werden die Auswechslungen nicht gespeichert

**Comment by diddipoeler** [comment]
Kommt da eine Fehlermeldung ?

**Comment by svdoldie** [comment]
Direkt beim speichern leider nicht.
Diese Meldung wird generell angezeigt:
Notice: Undefined variable: this in /var/www/vhosts/svdoerpum.de/svdoerpum.de/administrator/components/com_sportsmanagement/models/match.php on line 1348

**Comment by svdoldie** [comment]
übrigens steht das "Ajax" auch im Backend

**Comment by svdoldie** [comment]
Diddi, könntest du bitte den Reiter "Spieler" an die erste Position setzen?
Es macht meiner Meinung nach Sinn, mit der Eingabe der Startmannschaft zu beginnen, bevor man die Auswechselungen bearbeitet

**Comment by diddipoeler** [comment]
ok !

**Comment by svdoldie** [comment]
Danke, schon erledigt 👍

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Im Backend ist alles ok.
Im Frontend kann ich leider nur das Joomla-Standardtemplate nutzen um überhaupt in den Bereich Aufstellung usw. zu kommen. Und da wird es leider nicht im Modalfenster angezeigt.
Siehe Bild
![bildschirmfoto-3](https://user-images.githubusercontent.com/2417767/36366939-abdf299c-1550-11e8-9c37-71ebf32b071d.png)
