### ISSUE TITLE
Einige Tabellen nach bootstrap div umwandeln

### ISSUE THREAD

**Issue by diddipoeler** [diddipoeler/sportsmanagement#553]
Zur besseren Darstellung einige Tabellen in der Frontendanzeige
in Bootstrap grid umwandeln.

**Comment by appukonrad** [comment]
rewrite the tables to div, or preserve both possibilities?

**Comment by diddipoeler** [comment]
i think both is better.

**Comment by diddipoeler** [comment]
i included this in the overall template.
`
<field name="use_table_or_bootstrap" type="extensionradiobutton" default="1"   class="radio btn-group btn-group-yesno"
			label="COM_SPORTSMANAGEMENT_FES_OVERALL_PARAM_LABEL_TABLE_OR_BOOTSTRAP"
			description="COM_SPORTSMANAGEMENT_FES_OVERALL_PARAM_DESCR_TABLE_OR_BOOTSTRAP">
			<option value="0">COM_SPORTSMANAGEMENT_FES_OVERALL_PARAM_LABEL_BOOTSTRAP</option>
			<option value="1">COM_SPORTSMANAGEMENT_FES_OVERALL_PARAM_LABEL_TABLE</option>
</field>
`

**Comment by appukonrad** [comment]
Note: Usable for J4, default j3 template is not supported (bootstrap 2.3.2 uses the grid class span-number). For J3 must be used bootsrap 3 from the additional templates

**Comment by diddipoeler** [comment]
is this the right code ?

**for j4**
div class="container-fluid"
div class="row-fluid"
div class="col-md-8"
.col-md-8
/div
div class="col-md-4"
.col-md-4
/div
/div
/div


**for j3**
div class="container-fluid"
div class="row-fluid"
div class="span8"
.col-md-8
/div
div class="span4"
.col-md-4
/div
/div
/div

**Comment by appukonrad** [comment]
yes , this is default syntax for Joomla
J3 used very old Bootsrap 2.3.2 , if the booutstra3 is added with an externaly (e.g. in external template) class col- work with J3

**Comment by appukonrad** [comment]
default :
J3  `<div class="span<?php echo round((12 / $this->columns)); ?>">`
J4  `<div class="col-md-<?php echo round((12 / $this->columns)); ?>">`

**Comment by diddipoeler** [comment]
i think we must include a button in the overall template.
the user select in the new button the version of bootstrap 2 or 3, which will
use in the frontend template of joomla.
is this ok ?

**Comment by appukonrad** [comment]
it should work

**Comment by diddipoeler** [comment]
in the overall template is a new button for the bootstrap version.
it works in the teaminfo with the template history leagues.
the user can now switch between different views.
table or bootstrap. is bootstrap then version 2 or version 3.
