### ISSUE TITLE
Backend error if set Associations on global options

### ISSUE THREAD

**Issue by appukonrad** [diddipoeler/sportsmanagement#558]
Clean installation Joomla 3.8.4, clean installation JSM, 5.5.5-10.1.30-MariaDB and 7.2.1

If set on global options "Association" all component return : Cannot use assign-op operators with string offsets

**Comment by appukonrad** [comment]
components/com_sportsmanagement/views/cpanel/view.html.php:197

**Comment by diddipoeler** [comment]
i think this is a php problem.
