### ISSUE TITLE
Ergebnisse - Fehler bei Bearbeitung im Frontend

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#568]
Klickt man im Frontend auf das Notizblockicon, erscheint folgende Fehlermeldung:
0 - syntax error, unexpected '$uri' (T_VARIABLE), expecting ',' or ')'

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft 👍
