### ISSUE TITLE
Frontend: Roster

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#589]
Hallo zusammen,

wenn ich folgende Einstellung übernehmen
Zeige Stabsmitarbeiter?  - Nein
Drop-Down Auswahl - Ja

bleibt das Drop-down auch für Stabsmitarbeiter sichtbar.

Gruß
Phanto

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Super. Funktioniert.
