### ISSUE TITLE
Frontend: Roster

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#590]
Hallo zusammen,

in der Roster Ansicht zeigt der "Tooltip" nicht den richtigen Text an.
Spiele stimmt. Bei der :230 sollte RP davor stehen. Bei High Finish: 1 sollte 180: 1 stehen.

![image](https://user-images.githubusercontent.com/9608697/36314652-ca7dbb06-1335-11e8-9c34-e517849b2b84.png)

Gruß
Phanto

**Comment by diddipoeler** [comment]
Woher kommt RP ?
Woher kommt 180 ?

**Comment by PhantoSGE** [comment]
Das sind eigene Ereignisse.

**Comment by PhantoSGE** [comment]
![image](https://user-images.githubusercontent.com/9608697/36318605-a2314428-1340-11e8-8ba5-b5f250080dff.png)

**Comment by tdittmann** [comment]
Bitte nochmal testen ;)

**Comment by PhantoSGE** [comment]
Leider keine Veränderung

**Comment by tdittmann** [comment]
Ich habe mal ein paar Varianten bei mir ausprobiert, ich kann es leider nicht nachstellen :( 

<img width="181" alt="bildschirmfoto 2018-02-21 um 20 00 30" src="https://user-images.githubusercontent.com/22032251/36499609-1d853238-1742-11e8-9bab-29be3f190fcc.png">

**Comment by PhantoSGE** [comment]
Das sind die festen "Ereignisse". Die scheinen zu funktionieren. Habe bei mir nur die Spiele zum anzeigen.
Der fehlende Text erscheint bei den selbst erstellten Ereignissen.

**Comment by PhantoSGE** [comment]
Kann dir gerne auch Zugangsdaten zukommen lassen wenn du mal schauen willst

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Perfekt Diddi.
