### ISSUE TITLE
Frontend: Ergebnisse

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#600]
Hallo zusammen,

- wenn ich auf das Menü Ergebnisse (Ergebnisse/Tabelle) aufrufe wird der aktuelle Spieltag angezeigt, aber im Dropdown wird "Spieltag 1" angezeigt.
- Vereinswappen werden nicht angezeigt. (auch in der Tabelle nicht)
- (Wunsch) Mannschaftswappen statt Vereinswappen anzeigen. (Ergbnisse & Tabelle)
- Ereignisse: Mit DHTML Registerkarten für die Anzeige von Ereignissen funktioniert nur beim ersten Spiel in der Liste

Gruß
Phanto

**Comment by svdoldie** [comment]
Punkt 1 kann ich bestätigen.
Punkt 2 nicht, das funktioniert einwandfrei
Punkt 4 kann ich auch nicht bestätigen, allerdings lässt sich die Anzeige der Ereignisse nicht wieder schließen, ausser man ruft die ganze Seite neu auf

**Comment by diddipoeler** [comment]
Bitte noch einmal das ein- und ausblenden der Ereignisse testen.

**Comment by svdoldie** [comment]
funktioniert jetzt 👍

**Comment by PhantoSGE** [comment]
Folgendes erscheint bei mir. 
Es sind für alle Spiele die Ereignisse aufgeklappt.
Die "Überschrift" der Ereignisse erscheint nur unter dem ersten Spiel. (1) Dafür mehrfach
Wenn ich durch die Tabs klicke werden Ereignisse eingeblendet, aber die alten nicht ausgeblendet.
Das Ereignis "Punkte" ist bei jedem Spiel vorhanden. Wird aber nicht angezeigt (2) (Auszug aus dem Matchreport des gleichen Spiels)
Die Vereinswappen werden bei mir nicht angezeigt. Nur die Ländericons wenn ich sie auswähle.

![image](https://user-images.githubusercontent.com/9608697/36377316-0b211124-1577-11e8-8268-95d2098e11db.png)
![image](https://user-images.githubusercontent.com/9608697/36377338-22d7de06-1577-11e8-9308-8e804f4d70ed.png)


Gruß
Phanto

**Comment by sigal** [comment]
Probier mal auf deiner testseite das von joomla mitgelieferte protostar template aus.

Auf deiner Seite werden die Vereinswappen geladen, aber das Template blendet sie aus???

**Comment by PhantoSGE** [comment]
Danke, werde es mir gleich mal anschauen. Den Verdacht hatte ich auch schon. Ich dachte ich nutze das gleiche Template wie svdoldie und habe es daher erstmal nicht weiter verfolgt.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Perfekt Diddi. 
Die Wappen werden, wie stony sagt vom Template ausgeblendet.

**Comment by sigal** [comment]
Was mich noch interessieren würde ist, ob System - JSM - Bootstrap Plugin aktiviert ist?

**Comment by PhantoSGE** [comment]
Ich teste es sowohl mit und ohne. 
Ich muss es nur ausstellen, da ich sonst im Backend sonst keiner Bilder laden kann.
