### ISSUE TITLE
Frontend: Matchreport

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#601]
Hallo zusammen,

die Eregnissanzeige funktioniert nicht richtig.
In den Tabs werden alle Ereignisse angezeigt und nur von einer Mannschaft.
Die Schriftgröße ist zu groß auch für die Info Anzeige der JSM Komponente.

![image](https://user-images.githubusercontent.com/9608697/36342122-e81fef66-13f9-11e8-904c-6eef8f7b850a.png)

Gruß
Phanto

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Funktioniert.  :+1:
