### ISSUE TITLE
Backend: Auswahl Mastertemplate

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#602]
Hallo zusammen,

die Auswahl Mastertemplate funktioniert nicht bzw. wird in einem anderen Projekt nicht übernommen.

Gruß
Phanto

**Comment by sigal** [comment]
Kann ich nicht nachvollziehen!

**Comment by PhantoSGE** [comment]
Ich habe zwei Projekte. Wenn ich in zwei Projekten das gleiche Template einstelle wird es nur im ersten übernommen und das zweite nutzt ihn nicht.

**Comment by sigal** [comment]
Welchem Projekt wurde welches Template zugewiesen.

Vorgehen ist folgend:

Wenn alle zwei Projekte (Projekt A + B) ihr eigenes Mastertemplate haben und ich dem Projekt B als Mastertemplate das Projekt A zuweise, das Projekt B speichere und schließe, sind dem Projekt B die Templates vom Projekt A als Mastertemplate zugewiesen.

Aber! es sind noch die alten Templates von Projekt B vorhanden, die per Hand in der Templateansicht gelöscht werden müssen.

In der Anzeige mal die Anzeige (Dropdown)auf alle stellen. Dann erscheinen sicher die Templates mit roter Schrift (Mastertemplate) - alle anderen Templates bis auf die Mastertemplates löschen. Voila.

Ok?

**Comment by PhantoSGE** [comment]
Egal wie ich es auswähle steht bei beiden immer "Unabhängiges Template"

**Comment by sigal** [comment]
Das glaube ich nicht, ohne einen Blick darauf geworfen zu haben.

Verwalte selber mehr als 1600 Projekte und verwende für verschiedene Ligen eigene MasterTemlates und  weise jede Saison bei einem neuen Projekt das Mastertemplate zu.

Und der Vorgang ist immer so, wie ich im vorigen Posting beschrieben habe

**Comment by PhantoSGE** [comment]
Ich weiß es ist nicht selbstverständlich aber könntest du es dir mal anschauen? Ich kapiere es gerade wirklich nicht

**Comment by sigal** [comment]
Ist doch alles in Ordnung  :relaxed:

**Comment by PhantoSGE** [comment]
Ich weiß gar nicht wie ich dir Danken soll......
Weißt du was ich falsch gemacht habe?

**Comment by sigal** [comment]
Im älteren Projekt war ein Template gesperrt.
Nach Aufhebung ging alles so wie oben beschrieben.
Kleiner Fehler - große Wirkung.  :relaxed:

**Comment by PhantoSGE** [comment]
Da hätte ich lange gesucht :-)
Nochmal vielen Dank. Echt klasse wie einem hier geholfen wird.
