### ISSUE TITLE
 Mannschafts-Spielplan Anzeige

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#603]
Hallo zusammen,

wenn ich unter
Spieloptionen - "Zusätzliche Spalte mit Link zum Spielbericht anzeigen" auf Ja stelle wird die Seite nicht mehr im Template angezeigt.

Gruß
Phanto

**Comment by tdittmann** [comment]
Ich hoffe es sieht bei dir ähnlich aus, werde einen Pull Request hierfür aufmachen ;)

<img width="1440" alt="bildschirmfoto 2018-02-17 um 20 35 17" src="https://user-images.githubusercontent.com/22032251/36344933-19c4548a-1422-11e8-8018-4010f5336b70.png">

**Comment by PhantoSGE** [comment]
So sah es bei mir auch aus. Danke

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Super. Sieht gut aus. Danke
