### ISSUE TITLE
Menü Mannschaftsspielplan

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#614]
Hallo zusammen,

beim Aufruf des Menüs erscheint.
1064
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 3

Gruß
Phanto

**Comment by diddipoeler** [comment]
Wurde der Menüeintrag **teamplan** schon angelegt ?

**Comment by PhantoSGE** [comment]
Ich habe den Menüpunkt mit verschiedenen Mannschaften getestet. Es erscheint nicht bei jeder Mannschaft die Fehlermeldung.

**Comment by diddipoeler** [comment]
Mach mal auch bitte ein Update der Komponente.
Nenne mir mal bitte den Link zu der Seite bei dem der Fehler auftritt !

**Comment by PhantoSGE** [comment]
z.b
http://worfelden-fussball.de/index.php/teams/treff-gar-nix/spielplan-tg
Die Fehlermeldung erscheint nicht bei jeder Mannschaft.

**Comment by diddipoeler** [comment]
Mach mal bitte ein Update der Komponente.

**Comment by PhantoSGE** [comment]
Leider keine Veränderung

**Comment by diddipoeler** [comment]
So, dann sende mir mal bitte die Admin Zugangsdaten.

**Comment by PhantoSGE** [comment]
Habe Sie dir auf per PN auf der HP geschickt

**Comment by PhantoSGE** [comment]
Update:
Wenn ich die Ansicht "sortiert nach Datum" auswähle funktioniert die Anzeige. 
Bei "Standard" erhalte ich die Fehlermeldung.

Gruß

**Comment by diddipoeler** [comment]
Ich kann den Fehler nicht nachvollziehen.
