### ISSUE TITLE
Matchreport - missing out_position in_position

### ISSUE THREAD

**Issue by appukonrad** [diddipoeler/sportsmanagement#615]
Notice: Undefined property: stdClass::$out_position in /srv/http/joomla3/public_html/components/com_sportsmanagement/views/matchreport/view.html.php on line 293

and 

stdClass::$in_position on line 322

![screenshot_20180220_153720](https://user-images.githubusercontent.com/5821245/36429899-1c965ef4-1654-11e8-8f89-a91e3245adb9.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by appukonrad** [comment]
it shows - Youth Coach, but I have no one
![screenshot_20180221_065335](https://user-images.githubusercontent.com/5821245/36465159-2b609f5a-16d4-11e8-9bbf-441a0d4e0f4d.png)
*****************************************************************************
![screenshot_20180221_065410](https://user-images.githubusercontent.com/5821245/36465162-2ee95efa-16d4-11e8-8582-b8ce36a535e3.png)

**Comment by sigal** [comment]
Here is my view
![substitution](https://user-images.githubusercontent.com/5115688/36510773-87e2ab20-1764-11e8-8d76-351653f367a9.jpg)
![playerposition](https://user-images.githubusercontent.com/5115688/36510791-981d3776-1764-11e8-8087-7acb51ad787c.jpg)
![playerposition_2](https://user-images.githubusercontent.com/5115688/36510824-b0e76d6c-1764-11e8-829e-ff9b1186b711.jpg)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen !
