### ISSUE TITLE
Player- Spielzeitangabe in den Saisonspielen stimmt nicht

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#620]
Statt der wirklichen Spielzeit wird die Zeit des ersten Ereignisses des Spielers in diesem Spiel angzeigt.
Ist dem Spieler kein Ereignis in dem Spiel zugewiesen, stimmt die Anzeige.
Siehe http://svdoerpum.de/jsm/index.php/kader/player/0/1/1-c-junioren-kreisklasse-a3-17-18/4-sg-doerpum-drelsdorf-9er/16-kim-luca-prochnow

**Comment by diddipoeler** [comment]
Im Overall Template die Events auswählen, die zu einer Spielverkürzung beitragen.

**Comment by svdoldie** [comment]
Nein, es sind da keine Ereignisse ausgewählt.
Ich habe da eh nie etwas eingestellt, weil mir gar nicht bewusst war, wozu der Bereich gut ist ;-)
Auch weil da die Variablen nicht übersetzt sind bzw. komplett zu erkennen

**Comment by diddipoeler** [comment]
So die Variablen werden jetzt übersetzt.
Ereignisse auswählen, die die Spielzeit verkürzen.
Dann noch einmal testen.

**Comment by svdoldie** [comment]
läuft :+1:
