### ISSUE TITLE
new view - birthday module

### ISSUE THREAD

**Issue by appukonrad** [diddipoeler/sportsmanagement#639]
on codepen I inserted (editable) a new look for the birthday module

![birthday-card](https://user-images.githubusercontent.com/5821245/36933296-e0b394de-1ed6-11e8-854f-bfcc6051a27e.png)

https://codepen.io/appukonrad/pen/yvrXjW

https://codepen.io/appukonrad/full/yvrXjW/

**Comment by diddipoeler** [comment]
great.

**Comment by sigal** [comment]
Klick -> Spielerinformationen
1054 - Unknown column 'tp.projectteam_id' in 'field list'

**Comment by appukonrad** [comment]
Deprecated: Function create_function() is deprecated in /srv/http/joomla3/public_html/modules/mod_sportsmanagement_birthday/helper.php on line 46

Notice: Undefined variable: usedname in /srv/http/joomla3/public_html/modules/mod_sportsmanagement_birthday/tmpl/default_player_card.php on line 64

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by appukonrad** [comment]
Warning: array_multisort(): Argument #4 is expected to be an array or a sort flag in /srv/http/joomla3/public_html/modules/mod_sportsmanagement_birthday/helper.php on line 42

**Comment by appukonrad** [comment]
for now I would have turned off fontawesome (version 4 not compatible with version 5), I will look for a way how to use awesome font in general for other modules and views

**Comment by diddipoeler** [comment]
Behoben: Warning: array_multisort():

**Comment by appukonrad** [comment]
no warning, no notice, no error
