### ISSUE TITLE
Teaminfo - Frontend

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#640]
Nach deaktiveren der Anzeige von Historie nach Ligen im Template teaminfo, wird im Frontend bei der Ausgabe der Historie einer Mannschaft, nur die aktuelle Saison ausgegeben.

![template-teaminfo-seitenelemente](https://user-images.githubusercontent.com/5115688/36933560-64d6f112-1edb-11e8-821b-892bc27731ee.png)

![historie](https://user-images.githubusercontent.com/5115688/36933595-24f8d19a-1edc-11e8-905c-86893a68ddc6.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Läuft :+1:
