### ISSUE TITLE
new view - Line-up

### ISSUE THREAD

**Issue by appukonrad** [diddipoeler/sportsmanagement#641]
on codepen I inserted (editable) a new look for the line-UP

![line-up](https://user-images.githubusercontent.com/5821245/36936823-62084eca-1f0a-11e8-8377-ee1d8767e7ab.png)

![linuup-ip6](https://user-images.githubusercontent.com/5821245/36936826-68069570-1f0a-11e8-9760-41601f481dea.png)

https://codepen.io/appukonrad/pen/QQPOBY

https://codepen.io/appukonrad/full/QQPOBY/

**Comment by diddipoeler** [comment]
great.

**Comment by appukonrad** [comment]
must be used with Joomla template with BS4 or JSMFlex enabled

**Comment by appukonrad** [comment]
pagege end 504 error code

PHP message: PHP Notice:  Undefine 2018/03/08 07:26:48 [error] 1856#1856: *133 FastCGI sent in stderr: "/public_html/components/com_sportsmanagement/views/matchreport/tmpl/default.php on line 110

if ( $this->config[**'show_roster**'] )
	{
        $output['COM_SPORTSMANAGEMENT_MATCHREPORT_STARTING_LINE_UP_PLAYER'] = $this->config['**show_roster_card**'];
        $output['COM_SPORTSMANAGEMENT_MATCHREPORT_STARTING_LINE_UP_STAFF'] = 'staff';
        $output['COM_SPORTSMANAGEMENT_MATCHREPORT_SUBSTITUTES'] = 'subst';
	}

**Comment by diddipoeler** [comment]
Das Template roster aufrufen und noch einmal speichern.

**Comment by appukonrad** [comment]
:+1: :smile:
