### ISSUE TITLE
Trikotbilder im falschen Ordner

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#657]
Die Trikotbilder gehören meiner Meinung nach in den Ordner ../clubs/trikot/
und nicht in den Ordner ../clubs/small

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Ich meinte die Trikotbilder, die mit hochgeladen werden bzw. mit installiert werden. Ich weiß jetzt leider nicht in welchem Paket die beim hochladen sein könnten

**Comment by sigal** [comment]
Die waren schon in Joomleague und Joomleague Extendet im falschen Ordner. 
![github03](https://user-images.githubusercontent.com/5115688/37371968-8320d9ec-2711-11e8-82ee-93e925bd2c6a.PNG)

t_0.png - t_987.png
Hab das mal schon in der alten Version moniert.

Ich finde die Ordner trikot, trikot_away und trikot_home auf meinem Server nicht, obwohl JSM sie anzeigt.

![github04](https://user-images.githubusercontent.com/5115688/37372698-05a848bc-2714-11e8-9cdc-3cae00006b99.PNG)
![install01](https://user-images.githubusercontent.com/5115688/37372707-0bf2feb0-2714-11e8-8ee8-59b7e3cc9b53.PNG)

**Comment by diddipoeler** [comment]
So, die Trikots wurden umkopiert.
