### ISSUE TITLE
Wunsch: Ghostplayer 

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#659]
Was ist mit der Idee eines "ghostplayer", der in JSM für jedes Team fest programmiert ist?

Mein Problem ist, dass ich in vielen Projekten nicht alle Namen von Spielern anderer Teams kenne. Dies bedeutet , dass ich nicht in der Lage bin, einem anderen Team ein Ereignis in einem Match eines Projekts zuzuweisen.

Dieser hardcodierte Spieler sollte nur innerhalb des Ereignis-Bereichs eines Matches angezeigt werden, wenn der Admin diesem hartcodierten Spieler eines Teams ein Ereignis für ein Match zuweist. 
Der Name des Spielers könnte "Spieler von [ausgewähltem Team]" sein.

was haltet ihr davon. In JL gab's das übrigens auch ;-)

**Comment by diddipoeler** [comment]
Lege doch für jedes Team einen Ghostplayer an !

**Comment by svdoldie** [comment]
Das ist sicherlich eine Möglichkeit... 
😉

**Comment by PhantoSGE** [comment]
Finde die Idee von svdoldie nicht verkehrt.
Die Idee einfach für jede Mannschaft einen 'Ghostplayer' anlege kann ich nachvollziehen.
Allerdings würde dann dieser Ghostplayer auch in der Mannschafstliste, Statisk etc. auftauche. Oder hab ich da einen Gedankenfehler ......
