### ISSUE TITLE
Templates - Auswahliste

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#660]
Auswahliste zum Überschreiben von Templates ist nicht mehr vorhanden.
Statt Auswahlliste nur Zeichen "**<**"
Zeitpunkt: Zwischen 20.3.2018 und 24.03.2018
![template01](https://user-images.githubusercontent.com/5115688/37866924-5880bed6-2f91-11e8-84f2-8da77607274f.jpg)

![template02](https://user-images.githubusercontent.com/5115688/37866926-669cf016-2f91-11e8-8492-a98c373020f0.jpg)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Noch keine Änderung. Meine. dass eine JS-Datei dafür verantwortlich ist.
Weiters wird auch keine Ausgabe beim GitHub-Update ausgegeben. Soll ich dafür einen neuen Issue aufmachen? Update wird wohl eingespielt (hab ich überprüft), aber wie gesagt keine Meldung, ob das Update eingespielt wurde.
Siehe:
![github_update](https://user-images.githubusercontent.com/5115688/37867476-8f19d588-2f99-11e8-962a-d5d5954b5b18.jpg)

**Comment by diddipoeler** [comment]
Kann ich leider nicht bestätigen.
Läuft bei mir alles reibungslos.

**Comment by sigal** [comment]
Versteh ich nicht. werde das aber noch auf meinem internen Server testen. (github update)

Und die Auswahlliste ist auch vorhanden?

**Comment by diddipoeler** [comment]
Ja.

**Comment by sigal** [comment]
Na bravo! 
ich bin raus.
Weiterhin viel glück diddi!

**Comment by diddipoeler** [comment]
Verstehe ich jetzt nicht ganz.
Wie ich bin raus ?

**Comment by sigal** [comment]
PHP-Version | 5.6.34 - 28 = Ausgabe OK

PHP-Version | 7.0.22 - 28 = Ausgabe OK

PHP-Version | 7.1.15 = Ausgabe wie oben beschrieben

PHP-Version | 7.2.38 = Ausgabe wie oben beschrieben
