### ISSUE TITLE
Frontend: Ergebnis speichern löscht Daten

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#661]
Das speichern eines Ergebnisses löscht in beiden Ansichten die Spielnummer, Datum und die Zeit

**Comment by diddipoeler** [comment]
Verstehe ich jetzt nicht so ganz !

**Comment by svdoldie** [comment]
Wenn ich im Frontend das Ergebnis eines Spiels speichere,
sind danach die oben genannten Daten des Spiels gelöscht

**Comment by svdoldie** [comment]
Geht mir das auch alleine so?

**Comment by PhantoSGE** [comment]
Kann ich Bestätigen

**Comment by svdoldie** [comment]
Ok, ich muss mich korrigieren. In der normalen Ansicht tritt der Fehler nicht auf.
Die Frage ist jetzt, ob man noch die Ansicht DFC_Day braucht, wenn man die Frontendbearbeitung mittlerweile konfigurieren kann

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft jetzt auch in der Ansicht DFC_day :+1:
