### ISSUE TITLE
Spielervisitenkarte zeigt keine Einsätze usw. an

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#662]
Wählt man in der Rosteranzeige die Ansicht Spielervisitenkarte,
werden zwar die die Anzahl der jeweiligen Ereignisse angezeigt,
aber nicht die Einsätze usw. Da werden nur "0" angezeigt.
Siehe http://svdoerpum.de/index.php?option=com_sportsmanagement&view=roster&cfg_which_database=0&tid=13:sv-doerpum&s=2:2017-2018&p=22:verbandsliga-nord-2017-2018&Itemid=1899

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :+1:
