### ISSUE TITLE
Darstellung der Stabsmitarbeiterposition greift nicht bei Personalvisitenkarte

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#663]
Die Einstellung "Darstellung der Stabsmitarbeiterposition" im Template Roster greift nicht in der Darstellung Personalvisitenkarte
Siehe http://svdoerpum.de/index.php?option=com_sportsmanagement&view=roster&cfg_which_database=0&tid=13:sv-doerpum&s=2:2017-2018&p=22:verbandsliga-nord-2017-2018&Itemid=1899

**Comment by diddipoeler** [comment]
Es werden doch die Mitarbeiter angezeigt.

**Comment by svdoldie** [comment]
Darum geht's nicht. Ich hab in dieser Einstellung "Position" gewählt. In der Standardausgabe wird dann z.B. beim Trainer auch nur " Trainer" angezeigt. In der Visitenkarte steht aber "Mitglied von Trainer (Mehrzahl) Trainer"

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Fehler existiert noch

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :+1:
