### ISSUE TITLE
Frontendbearbeitung Person erzeugt 404-Fehler

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#664]
Will man im Frontend eine Person bearbeiten, erscheint eine Seite mit Fehlermeldung 404

**Comment by diddipoeler** [comment]
Soll das im Frontend überhaupt erfolgen ?

**Comment by svdoldie** [comment]
Von mir aus nicht, wird aber angeboten.
Der gleiche Fehler ist auch bei der Bearbeitung eines Teams im Frontend

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Der Fehler existiert noch

**Comment by teddyfresco** [comment]
Ich habe das selbe Fehler, aber auch für Frontendbearbeitung Mannschaft, soll ich eine neue issue offen?

**Comment by diddipoeler** [comment]
Jetzt sieht man schon mal die Reiter.

**Comment by teddyfresco** [comment]
I suppose it means you are working on it right now, right? In any case, now (just reinstalled with h14.45 version) there's no error 404, the page loads (with debug info), the tabs are displayed but without content.
I also see save displayed twice, and neither save nor cancel do seem to work, look at the screenshot:
https://screenshots.firefox.com/yvRaqOBVQ5roCJE2/mittelinfo
I've checked Mannschaft un Verein FEbearbeitung, and they give 404 error, tell me please if you want a new issue about them on github

**Comment by diddipoeler** [comment]
Kann man hier nicht mal in Ruhe programmieren ?

**Comment by teddyfresco** [comment]
Sicher, just wanted to be helpful. Take your time and thanks again.

**Comment by diddipoeler** [comment]
Bitte einmal die Personen- und Vereinsbearbeitung im Frontend testen

**Comment by svdoldie** [comment]
Die Personenbearbeitung funktioniert soweit,
allerdings kommt folgende Meldung:


COM_SPORTSMANAGEMENT_SAVE_SUCCESS

× 
Hinweis


Nicht vorhandenes Mastertemplate: editperson

Projekt-Id des nicht vorhandenen Mastertemplate: 1

Keine Panik! Informieren sie den Administrator der Webseite.
Sind sie selbst der Betreiber der Webseite, überprüfen sie bitte die Einstellungen der Templates vom Projekt (results & ranking).

In welcher Ansicht kann man die Vereinsbearbeitung durchführen?
In der Ansicht Vereinsinfo erscheint kein Bearbeitungssymbol.

**Comment by teddyfresco** [comment]
Hi, I'm on php 7.2.6, and using default template protostar. I'm experiencing a loop when hitting save and close (and cancel) on frontend teams and clubs, it's fairly similar to:
https://github.com/diddipoeler/sportsmanagement/issues/794
When hitting save I get:
The requested page can't be found.

On persons if I hit save it saves correctly and shows COM_SPORTSMANAGEMENT_SAVE_SUCCESS, hitting save and close (and cancel) creates the loop again.

On results it doesn't even enter the edit page, it just refreshes the frontend page.

I've checked templates in admin, I can see editprojectteam, editclub and editperson (no editresults) but they are empty when accessed.

**Comment by diddipoeler** [comment]
Hauke , wie immer.
Im Backend das Projekt und die Templates aufrufen.
Fehlende Templates werden dann automatisch angelegt.

**Comment by svdoldie** [comment]
Schon klar, aber bei mir sind die Templates editclub, editperson und editprojektteam alle blank

**Comment by svdoldie** [comment]
genauso wie matrixedit und rankingallseason

**Comment by teddyfresco** [comment]
I confirm blank templates, like svdoldie, I also add that there's no editresults template.
I also did some further test, on php 7.1.18 and 7.0.30. Joomla is 3.8.12 and template is protostar (default).
On save and close and cancel the club, team and person page enters a loop.
The edit results page still just refreshes.

**Comment by diddipoeler** [comment]
Es gibt im Frontend kein **editresult** Template !

**Comment by diddipoeler** [comment]
> 
> 
> Schon klar, aber bei mir sind die Templates editclub, editperson und editprojektteam alle blank

Das ist noch so. Ich kann leider nicht alles gleichzeitig !

**Comment by diddipoeler** [comment]
> 
> 
> genauso wie matrixedit und rankingallseason

Das ist noch so. Ich kann leider nicht alles gleichzeitig !

**Comment by svdoldie** [comment]
> > genauso wie matrixedit und rankingallseason
> 
> Das ist noch so. Ich kann leider nicht alles gleichzeitig !

So war das gar nicht gemeint. Ich hatte es so verstanden, wenn die Templates da sind, 
dass dann auch das Editiersymbol beim Verein zu sehen ist. 
Alles in Ruhe und nacheinander :+1:

**Comment by diddipoeler** [comment]
Das Editirsymbol ist zu sehen, wenn man auch die Berechtigung hat.
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Bei mir nicht, obwohl ich als SuperUser angemeldet bin 
![verein](https://user-images.githubusercontent.com/2417767/45472733-9e756700-b724-11e8-9772-5dc38e1ab9f1.png)

**Comment by sigal** [comment]
Fühl mich schon als komplett unguter Zeitgenosse.  :shipit:

![frontendedit_club](https://user-images.githubusercontent.com/5115688/45500884-0c02b100-b780-11e8-8fb7-161fb5b8024a.jpg)
