### ISSUE TITLE
Modul Spielstätten Terminansicht zeigt falsche Anstoßzeiten

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#665]
Das Modul Spielstätten Terminansicht zeigt um 2 Stunden verspätete Anstoßzeiten.
Sämtliche Zeitangaben stimmen ansonsten in der Komponente oder anderen JSM-Modulen

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :+1:
