### ISSUE TITLE
Menü Ergebnisanzeige

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#666]
Das Menü Ergebnisanzeige führt zu einer Leeren Seite mit Überschrift / Staffel-ID.
Das Menü Ergebnis-Tabellen Anzeige funktioniert.

Debug Fehlermeldung:
Parse error: syntax error, unexpected 'echo' (T_ECHO) in /components/com_sportsmanagement/views/globalviews/tmpl/default_sectionheader.php on line 368

**Comment by PhantoSGE** [comment]
Scheint ein fehlendes Semikolon zu sein

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Danke.
Hätte es gerne selbst geändert, bin leider noch Github noob und will dir da nicht reinpfuschen.

Gruß
