### ISSUE TITLE
Saisonspiele werden nicht angezeigt

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#667]
Die Saisonspiele einer Person werden nur angezeigt,
wenn diese Person nicht einer weiteren Saison zugeordnet ist.

**Comment by diddipoeler** [comment]
Kannst Du das bitte einmal näher beschreiben ?

**Comment by svdoldie** [comment]
Wenn man sich ein Spielerprofil ansieht, werden nur bei dem Spieler die aktuellen Saisonspiele angezeigt, der keiner anderen Saison zu geordnet ist

**Comment by sigal** [comment]
Zum Grübeln? [http://jsm.stony-sport4u.de/index.php?option=com_sportsmanagement&view=player&cfg_which_database=0&s=85&p=3240:st-oberliga-nord-2017-18&tid=3661:esv-knittelfeld&pid=634:christian-zachorjansky&Itemid=2579](url)

**Comment by svdoldie** [comment]
Ich kann den Link hier zu Hause nicht sehen. Aber ich vermute bei dir geht es ohne Probleme ...

**Comment by diddipoeler** [comment]
Ich komme leider auch nicht an dem Link.

**Comment by sigal** [comment]
Und ich komme mit dem PC nicht mehr auf http://fussballineuropa.de. (IP Sperre?)

Mit Smartphone geht es, aber kein einloggen möglich. (E-Mail oder IP Sperre?)
![screenshot_2018-04-01-21-42-34](https://user-images.githubusercontent.com/5115688/38177358-5f27f716-3600-11e8-9697-b19a4869c4c9.jpg)

**Comment by diddipoeler** [comment]
Sorry, jetzt müsste es gehen.

**Comment by diddipoeler** [comment]
Also bei mir sieht es so aus: http://www.fussballineuropa.de/index.php/component/sportsmanagement/player/0/0/73400-1-bundesliga-2017-18/9-fc-gelsenkirchen-schalke-04-e-v-i/218-ralf-faehrmann

**Comment by svdoldie** [comment]
Keine Ahnung warum das bei mir so. Ist wohl eines der Kuriositäten auf meiner Seite.
Wobei sich das auf meiner Testseite genauso verhält.
Wenn sonst keiner das Problem hat, kann hier geschlossen werden

**Comment by diddipoeler** [comment]
Jetzt habe ich das Problem auch.

**Comment by svdoldie** [comment]
da bin ich beruhigt ;-)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Perfekt :+1:
