### ISSUE TITLE
Frontend: Ansicht Player erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#668]
Nach Update auf die Version 1.0.62 erscheint bei der Ansicht Player folgende Fehlermeldung 
1054 - Unknown column 'tp.projectteam_id' in 'field list'

**Comment by svdoldie** [comment]
Hmmm, anscheinend wieder nur auf meiner Hauptseite :-1:

**Comment by svdoldie** [comment]
Und auch da nur wenn ich im Frontend angemeldet bin.

**Comment by svdoldie** [comment]
Fragt mich nicht warum, aber es geht auch auf meiner Hauptseite wieder.
dafür machen die Module Top-Tipper, Kalender und Geburtstag wieder Probleme.
Irgendetwas ist da grundsätzlich nicht in Ordnung :-1:

**Comment by diddipoeler** [comment]
Wo ist etwas nicht in Ordnung ?
Bei deiner Bootstrap Version ? Template ? An der Komponente ? Jquery Version ?
oder oder oder !

**Comment by svdoldie** [comment]
Wenn ich das genau wüsste. Es ist ja ständig etwas anderes.

**Comment by svdoldie** [comment]
Ich schließe hier mal
