### ISSUE TITLE
Frontend von JSM nach Update in englischer Sprache

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#671]
Nach dem ich heute morgen das Update auf den aktuellen Stand gemacht habe,
werden alle Ansichten von JSM in englischer Sprache angezeigt.
Ich habe das auf drei verschiedenen Seiten gemacht, überall das gleiche Ergebnis

**Comment by sigal** [comment]
sorry. falsche datei erwischt

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Bei mir ist wieder alles i.O.
