### ISSUE TITLE
Menü: Mannschaftsinfo Anzeige

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#673]
Folgender Fehler wenn das Menü aufgerufen wird.

Catchable fatal error: Object of class stdClass could not be converted to string in /components/com_sportsmanagement/views/globalviews/tmpl/default_sectionheader.php on line 367

Gruß
Phanto

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
läuft wieder
