### ISSUE TITLE
Wunsch: Fusion in Clubinfo abschalten

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#675]
Ich würde es gut finden,
wenn man die Fusionfunktion abschalten könnte.

**Comment by diddipoeler** [comment]
Wie abschalten ?

**Comment by svdoldie** [comment]
Na, in den Clubinfo wird ein Balken angezeigt, der evtl. Fusionen darstellen kann.
Den würde ich gerne abgeschaltet können

**Comment by diddipoeler** [comment]
Bitte einmal testen.

**Comment by svdoldie** [comment]
Läuft👍
