### ISSUE TITLE
Saison Teams oder Personen zuweisen erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#677]
Will man einer Saison Teams oder Personen zuweisen,
folgt eine 404-Fehlermeldung

**Comment by diddipoeler** [comment]
Bitte den genauen Fehlertext posten.

**Comment by svdoldie** [comment]
404
View nicht gefunden [Name, Typ, Präfix]: seasons, html, sportsmanagementView

Ist aber merkwürdigerweise nur auf meiner Testseite so,
auf der Hauptseite läuft es tadellos

**Comment by svdoldie** [comment]
Ich schließe hier mal, mittlerweile läuft es auch auf meiner Testseite
