### ISSUE TITLE
pergame Statistik

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#679]
Hallo zusammen,

ich habe einen Statistikwert "average" als Typ "Basic" erstellt.
Einen weiteren Wert "average per game" als Typ "pergame".
Nun habe ich im Spielbericht 2 Spiele angelegt und den average eingegeben (60 + 70).
Nun zeigt mir das "average per game" aber den Wert 13,75 an. (sollte 130/2 = 65 sein).

Hab ich hier einen Denkfehler oder stimmt da etwas nicht?

Gruß
Phanto

**Comment by svdoldie** [comment]
Existiert der Fehler noch?

**Comment by PhantoSGE** [comment]
Ja, existiert noch.

**Comment by svdoldie** [comment]
Ich frage nach, weil Diddi den Statistikteil letztens in Arbeit hatte

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Danke. Jetzt passt es
