### ISSUE TITLE
Matchreport / Ereignisoptionen

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#680]
Hi zusammen,
Reiter Ereignisoptionen:
Der Name des Ereignisses wird im Frontend nicht angezeigt.
Wenn ich im Matchreport "Ereignis-Minute anzeigen" auf Nein stelle wird im Frontend die Überschrift "Zeit" nicht ausgeblendet.
"Registerkarten für die Anzeige der Ereignisse verwenden" Einstellung Ja hat keinen Effekt.

Gruß
Phanto

**Comment by svdoldie** [comment]
hast du bitte mal einen Link, damit man sich das mal anschauen kann?

**Comment by PhantoSGE** [comment]
Ich schließe das hier mal. Kann das selbst nicht mehr nachvollziehen.
