### ISSUE TITLE
Frontend: Fehlermeldung bei Personenansicht

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#682]
Will man eine Person anzeigen lassen,
erscheint nur folgende Fehlermeldung:
Class 'sportsmanagementModelProject' not found

siehe http://svdoerpum.de/index.php?option=com_sportsmanagement&view=player&cfg_which_database=0&s=2&p=22:verbandsliga-nord-2017-2018&tid=13:SV%20D%C3%B6rpum&pid=313:hauke-prochnow&Itemid=1899

**Comment by svdoldie** [comment]
Die gleiche Fehlermeldung kommt beim Matchreport

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :+1:
