### ISSUE TITLE
Frontendbearbeitung erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#684]
Wenn man im Frontend die Ergebnisse bearbeiten will,
erscheint folgende Fehlermeldung:
Class 'sportsmanagementModelMatch' not found
Das gilt nicht für die Ansicht DFC-Day, die aber meiner Meinung mittlerweile hinfällig ist,
da man die normale Ansicht konfigurieren kann

**Comment by svdoldie** [comment]
Ergebnisbearbeitung funktioniert jetzt, aber beim bearbeiten der Aufstellung oder der Ereignisse ersccheint folgende Meldung:
Class 'sportsmanagementModelProject' not found

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Die Ansichten werden wieder angezeigt, ich kann nur leider nichts speichern.
Es scheint als ob die entsprechenden Buttons ohne Funktion sind

**Comment by svdoldie** [comment]
Startaufstellung und Betreuer funktioniert. Auswechslungen und Ereignisse werden nicht gespeichert

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :+1:
