### ISSUE TITLE
Geburtagsmodul zeigt doppelte Anzahl an Personen an

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#685]
Wählt man in den Einstellungen die Anzeige "Spieler und Mitarbeiter" und Spielerkarte anzeigen, sowie als Anzahl "3",werden jeweils drei Spieler und drei Mitarbeiter angezeigt. Schaltet man die Spielerkarte ab, werden insgesamt drei Personen angezeigt.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :-)
