### ISSUE TITLE
Can't assign teams and persons

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#686]
I've created a new project and i've tried to add teams to this project.
When I press assign button, new screen appears but left listbox is empty

On the head of the avaliable teams shows,
Assign team to the project [$ s] 

I've activated debug info and shows,

sportsmanagementModelProjectteams::populateState 88 context -> com_sportsmanagement.projectteams
sportsmanagementModelProjectteams::populateState 89 identifier -> pteams
sportsmanagementView::display 212 state ->

Joomla\CMS\Object\CMSObject Object
(
    [_errors:protected] => Array
        (
        )

    [task] => 
    [filter.search] => 
    [filter.search_nation] => 
    [filter.state] => 
    [list.limit] => 20
    [list.start] => 0
    [list.ordering] => t.name
    [list.direction] => 
)

sportsmanagementView::display 214 sortDirection ->

sportsmanagementView::display 217 sortColumn ->

t.name

sportsmanagementView::display 219 request_url ->

http://llambion.com/web/administrator/index.php?option=com_sportsmanagement&view=projectteams&tmpl=component&layout=editlist&type=0&issueview=&issuelayout=&pid=10

Aviso
sportsmanagementViewprojectteams::init 63 Ausfuehrungszeit query

0

sportsmanagementModelDivisions::getDivisions 164

SELECT id AS value,name AS text
FROM josaj_sportsmanagement_division
WHERE project_id = 10
ORDER BY name ASC

sportsmanagementModelDivisions::getDivisions 165 Ausfuehrungszeit query

0

You can not change teams. Assign additional teams of the season.

-------------------------------------------------------------------------------------------------------
Also When I tried to assign players to any team, new screen appears but there aren't any player on the list

**Comment by sigal** [comment]
You have to assign a season to the team.
The same is true for players.
Then you can assign the team or person in the project

watch this video: http://jsm-wiki.diddipoeler.de/index.php?title=SM-Starthilfen:Installation

**Comment by llambion72** [comment]
I've assigned current season to selected players and teams but lists are empty.
First, 
All current data were imported from joomleague, players, clubs, teams, positions, seasons and so on. About 300 players, 90 teams, 10 seasons and 10 projects were imported from joomleague. 

After that I've created 2018/2019 season and project but i can't add data to this project.
Could it be any missing/wrong field on imported database??

**Comment by llambion72** [comment]
I've activated debug mode,
On country list, query executed is,

SELECT t.*,st.name AS sportstype,ag.name AS agename,c.name As clubname,c.country,uc.name AS editor
FROM josaj_sportsmanagement_team AS t
LEFT JOIN josaj_sportsmanagement_sports_type AS st ON st.id = t.sports_type_id
LEFT JOIN josaj_sportsmanagement_agegroup as ag ON ag.id = t.agegroup_id
LEFT JOIN josaj_sportsmanagement_club AS c ON c.id = t.club_id
LEFT JOIN josaj_users AS uc ON uc.id = t.checked_out
ORDER BY t.name ASC

But on team list, country field is empty for all teams, but all clubs have a country selected.

IF i execute team sql query directly on my phpmyadmin, clubs country appear on list

**Comment by llambion72** [comment]
I'm going nuts. I've reinstalled component and imported again all joomleague data. Now, it seems that works ok. 
I believe that some table in database imported wrong data to sportmanagement database

**Comment by svdoldie** [comment]
Ich glaube wir können hier schließen, oder?
