### ISSUE TITLE
Frontend Matchreport: Spielfeld nur für Lieblingsmannschaft geht nur bei Heimspielen

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#688]
Wählt man in den Einstellung, dass das Spielfeld nur für die Lieblingsmannschaft angezeigt werden soll,
funktioniert das nur bei den Heimspielen der Mannschaft. Bei den Auswärtsspielen wird das komplette Spielfeld angezeigt.
Siehe http://svdoerpum.de/index.php?option=com_sportsmanagement&view=matchreport&cfg_which_database=0&s=2&p=22:verbandsliga-nord-2017-2018&mid=1861:TSV%20Büsum_SV%20Dörpum&Itemid=1910

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :+1: 

Wenn du jetzt noch den Pressebericht-Import hinbekommst... ;-)
