### ISSUE TITLE
Module Sports Type Statistic. bug?

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#690]
On the backend, i can no enter in this module config. When press link to enter to this module, browser get blank and  i only can see few lines
![error](https://user-images.githubusercontent.com/20923398/42105791-058d8fc8-7bd2-11e8-8ba1-3e6c6d497c81.jpg)

**Comment by diddipoeler** [comment]
i don´t see this error on my website.

**Comment by llambion72** [comment]
rest of modules works well except this one. I've reinstalled twice but result as the same, on the backend i can no enter in the configuration. 
I've uptated joomla to 3.8.8 version and i can not find the problem

**Comment by diddipoeler** [comment]
can you send me an admin user and passwort ?
and the link to the page ?

**Comment by llambion72** [comment]
After last update this module works perfect!
