### ISSUE TITLE
Frontend Player: Saisonspiele falsches Datumsformat

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#692]
Die Saisonspiele einer Person werden im englischen Datumsformat angezeigt,
obwohl als Sprache deutsch eingestellt ist.
 Siehe http://svdoerpum.de/index.php?option=com_sportsmanagement&view=player&cfg_which_database=0&s=2&p=22:verbandsliga-nord-2017-2018&tid=13:SV%20Dörpum&pid=313:hauke-prochnow&Itemid=1899

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :-)
