### ISSUE TITLE
Top Tipper Modul

### ISSUE THREAD

**Issue by boxr** [diddipoeler/sportsmanagement#695]
erhalte folgende Fehlermeldung,
0 CLASS 'SPORTSMANAGEMENTMODELPREDICTION' NOT FOUND
The page you are looking for was moved, removed, renamed or might never existed.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by boxr** [comment]
funktioniert wieder, danke ;-)
