### ISSUE TITLE
Gespeicherte Ereignisse im Spiel lassen sich nicht löschen

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#697]
Gespeicherte Ereignisse eines Spiel lassen sich nicht löschen.
Weder im Backend, noch im Frontend

**Comment by svdoldie** [comment]
Kleine Einschränkung. Das Problem besteht nicht mehr, wenn man das Fenster erneut geöffnet hat.

**Comment by diddipoeler** [comment]
Stimmt leider.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :+1:
