### ISSUE TITLE
Geburtstagsmodul - SEO erzeugt falschen Link

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#699]
Wenn man bei eingeschalteten SEO und Spielerkarte auf Spielerinformationen klickt,
wird eine falsche Person angezeigt. Bei ausgeschaltetem SEO ist alles korrekt.

**Comment by diddipoeler** [comment]
Bei mir leider nicht.

**Comment by svdoldie** [comment]
hmm, das ist schlecht ;-(

**Comment by diddipoeler** [comment]
Schau mal bitte bei mir auf der Seite ganz unten.

**Comment by svdoldie** [comment]
Ich hätte es dir auch so geglaubt ;-) Fragt sich nur, warum es bei mir nicht geht

**Comment by diddipoeler** [comment]
Link ?

**Comment by svdoldie** [comment]
http://svdoerpum.de/

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
jetzt erhalte ich folgende Fehlermeldung:


Fehler

sportsmanagementModelProject::getProjectStats 1349 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INNER JOIN #__sportsmanagement_position AS pos ON pos.id = ps.position_id WHERE' at line 6

Fehler
Keine Person/Spieler ausgewählt !

**Comment by diddipoeler** [comment]
Installiere mal bitte die extplorer Komponente.

**Comment by svdoldie** [comment]
ich habe profiles installiert

**Comment by diddipoeler** [comment]
Es liegt an der Komponente noch an dem Modul.
Du musst alle Deine Projekte aufrufen und noch einmal speichern.
Die Aliasnamen sind falsch.

**Comment by svdoldie** [comment]
Ok. Ich habe die Seite neu aufgesetzt und die DB-Einträge von JSM wieder eingespielt.
Kann es dadurch noch zu anderen Problemen kommen?

**Comment by svdoldie** [comment]
Ansonsten kann hier geschlossen werden.

**Comment by diddipoeler** [comment]
Ich habe alle deine Aliasnamen bereinigt.

**Comment by svdoldie** [comment]
Hab ich schon bemerkt. Läuft jetzt :-) Danke !!!
