### ISSUE TITLE
Spiele bearbeiten - Spieldetails

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#700]
Hi zusammen,

wenn ich in den Spieldetails, im Reiter Tordetails, die Sätze eintrage werden diese nicht gespeichert.
Sätze ist in den Projekteinstellungen aktiviert.

![image](https://user-images.githubusercontent.com/9608697/42714942-0b2ab252-86f5-11e8-83e7-c9de43acc2f8.png)

Gruß

**Comment by sigal** [comment]
Diese Maske ist für alternative Entscheidungen, die unter dem Reiter Spieldetails erst mal freigeschaltet werden muss.
Frage: Welchen Sinn soll das im Tennis machen? Gibt es da nachträgliche Entscheidungen?

Die Ergebnisse werden doch unter Spiele bearbeiten -> Ergebnis eingetragen

**Comment by diddipoeler** [comment]
In welcher Form wurden denn die Sätze eingegeben ?

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Funktioniert jetzt.
Leider werden einfache Ergebnisse nicht mehr gespeichert im Backend. Im Frontend funktioniert es noch.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Funktioniert wieder. Danke
