### ISSUE TITLE
Ergebnis-Tabellen Anzeige

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#703]
Wenn ich o.a. Menü auswähle bekomme ich den aktuellen Spieltag angezeigt. Unabhängig davon welcher Spieltag aktuell ist wird im Dropdown immer 1. Spieltag angezeigt.
![image](https://user-images.githubusercontent.com/9608697/42812520-3a276502-89be-11e8-8657-dfe4c1772cc0.png)

Um nun an den 1. Spieltag zu kommen muss man einen anderen Spieltag auswählen und dann den 1.

Am 1. Spieltag angekommen erscheint folgende Fehlermeldung.

![image](https://user-images.githubusercontent.com/9608697/42812622-821a6152-89be-11e8-8f18-e8d8eb9c6019.png)

**Comment by diddipoeler** [comment]
Link ?

**Comment by PhantoSGE** [comment]
https://www.rhein-main-player-league.de/ligen/landesliga/resultsranking/0/1/1-landesliga/8-/0/0/0/0

**Comment by PhantoSGE** [comment]
https://www.rhein-main-player-league.de/ligen/landesliga

**Comment by diddipoeler** [comment]
Die Fehlermeldung ist jetzt weg.

**Comment by PhantoSGE** [comment]
Diese erscheint bei mir noch
![image](https://user-images.githubusercontent.com/9608697/42815644-44c27132-89c8-11e8-8526-dffa0455e478.png)

**Comment by diddipoeler** [comment]
Jetzt nicht mehr.

**Comment by PhantoSGE** [comment]
Danke dir.
Kann man das mit dem Dropdown lösen oder eher nicht machbar?

Gruß

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Jetzt wird immer der aktuelle Spieltag im Dropdown angezeigt.
Am besten wäre natürlich wenn dort der aktuell angezeigt Spieltag angezeigt wird. (Duck und weg)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Perfekt. Danke dir
