### ISSUE TITLE
Eregnisse Zeitanzeige

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#704]
Wenn ich "Ereignis-Minute anzeigen" auf Nein stelle werden die Minuten nicht angezeigt.
Ist es Möglich dann auch die Überschrift "Zeit" auszublenden?

z.B. Matchplan

![image](https://user-images.githubusercontent.com/9608697/42824293-d692a8ae-89df-11e8-8e73-db9b1f5faed9.png)

**Comment by PhantoSGE** [comment]
Macht eigentlich keinen Sinn. Ereignisse haben einen Zeitwert. Ich versuche das mal mit den Statistiken zu lösen.

**Comment by PhantoSGE** [comment]
Sorry, Würde mir doch helfen wenn man es ausblenden könnte.

**Comment by diddipoeler** [comment]
Sorry für die Frage: In welcher Anzeige ist das noch mal ?

**Comment by PhantoSGE** [comment]
Das ist aus dem Matchreport

**Comment by diddipoeler** [comment]
Sorry langsam werde ich blind :-)

**Comment by PhantoSGE** [comment]
Das kann ich komplett nachvollziehen :-)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by diddipoeler** [comment]
Frage: Hast Du eigentlich bei der vergleichbaren League-Konponente einen
solchen Support bekommen ?

**Comment by PhantoSGE** [comment]
Der Support ist wirklich unglaublich. Nochmal 1000 Dank dafür. :-)

**Comment by diddipoeler** [comment]
Vielleicht kannst Du mal Deine Erfahrungen im Forum auf meiner Homepage posten :-)
