### ISSUE TITLE
Eregnisse können nicht gespeichert werden

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#705]
Wenn ich ein Eregnis mit der gleichen "Summe/Wert" speichern möchte bekomme ich die Fehlermeldung "Fehler beim Speichern des Ereignis!:"

![image](https://user-images.githubusercontent.com/9608697/42832576-e7120046-89f1-11e8-84b3-f8a706733a9f.png)

**Comment by diddipoeler** [comment]
Das ist so eingebaut. Man kann keine doppelten Einträge erfassen.

**Comment by PhantoSGE** [comment]
Ok, dann muss ich mir was anderes überlegen.
