### ISSUE TITLE
Frontend: Player-Ansicht erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#710]
Player-Ansicht erzeugt folgende Fehlermeldung:

500
Layout „default_Array“ nicht gefunden!

http://svdoerpum.de/index.php/senioren/1-herren/player/0/5/42-verbandsliga-nord-2018-2019/13-sv-doerpum/126-tim-borchardt

**Comment by sigal** [comment]
diesen Fehler kann ich nicht nachvollziehen.

https://www.esv-knittelfeld.at/component/sportsmanagement/player/0/0/3240-st-oberliga-nord-2017-18/3661-esv-knittelfeld/646-michael-kautschitz.html

scheint so, als ob dateien fehlen? (/components/com_sportsmanagement/views/player/tmpl)

template player speichern?

**Comment by svdoldie** [comment]
Template speichern hatte nichts geholfen, das hatte ich auch erst vermutet. Das Problem taucht erst nach dem Update gestern auf

**Comment by sigal** [comment]
Bei mir läüft die letzte Github Version!

**Comment by svdoldie** [comment]
Hmm, ich werden nochmal ne Neuinstallation probieren

**Comment by diddipoeler** [comment]
Keine Angst, da muss ich etwas umprogrammieren. Mal keine
Tabs einstellen.

**Comment by svdoldie** [comment]
Alles klar :+1:

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Der Fehler ist noch vorhanden

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :-)
