### ISSUE TITLE
Events ranking module 

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#713]
In  joomleague there was a useful module named events raking module.
Are there a similar module in Sport Management? It's a useful module to show goals and cards for a team

If not, it's posible to add to this project

**Comment by llambion72** [comment]
I'm working on this module. 
I've almost finished but i have a trouble with sql query.
When i call to sportsmanagementModelEventsRanking::_getEventsRanking function of eventsraking model generate next sql query,
 
SELECT SUM(me.event_sum) as p,pl.firstname AS fname,pl.nickname AS nname,pl.lastname AS lname,pl.country,pl.id AS pid,pl.picture,tp.picture AS teamplayerpic,t.id AS tid,t.name AS tname,CONCAT_WS( ':', pl.id, pl.alias ) AS person_slug,CONCAT_WS( ':', t.id, t.alias ) AS team_slug,CONCAT_WS( ':', pt.id, t.alias ) AS projectteam_slug
FROM josaj_sportsmanagement_match_event AS me 
INNER JOIN josaj_sportsmanagement_season_team_person_id AS tp ON me.teamplayer_id = tp.id
INNER JOIN josaj_sportsmanagement_season_team_id AS st ON st.team_id = tp.team_id
INNER JOIN josaj_sportsmanagement_project_team AS pt ON pt.team_id = st.id
INNER JOIN josaj_sportsmanagement_team AS t ON t.id = st.team_id
INNER JOIN josaj_sportsmanagement_person AS pl ON tp.person_id = pl.id
WHERE me.event_type_id = 1 AND pl.published = 1 AND pt.project_id = 9 AND st.team_id = 1
GROUP BY me.teamplayer_id
ORDER BY p desc LIMIT 30

but this query returns all persons for event type 1 for ALL projects and not for current project (9)
I tried to execute directly over phpmyadmin and result is the same

![eventsranking](https://user-images.githubusercontent.com/20923398/43369997-9f824634-9377-11e8-9516-d00a551f6288.png)

This image shows an example, there are some players that appears twice because they are top in two or more projects

**Comment by diddipoeler** [comment]
Where is the modul ?

**Comment by llambion72** [comment]
In my webserver, I've been working last weekend on it. 
I'll upload source code to github soon

**Comment by llambion72** [comment]
Ok, I've uploaded some spanish translation files via transifex too

**Comment by llambion72** [comment]
This Module is in my branch but i don't know how commit only the module.

**Comment by sigal** [comment]
Modest opinion: The module is not useful in this version!

**Comment by diddipoeler** [comment]
I think it´s work now.
please test it.

**Comment by diddipoeler** [comment]
Now you can see the country flag.

**Comment by sigal** [comment]
Fast perfekt! Die Ausgabe des table ist verrutscht.
https://www.esv-knittelfeld.at/

Wenn keine view (z.B. Tabelle, Result etc.), aus dem Frontend der JSM Komponente geöffnet ist,
werden die Language-Keys nicht übersetzt. Das ist auch im JSM - Modul Geburtstag zu sehen.

Bei https://www.esv-knittelfeld.at/mannschaften/kampfmannschaft/ergebnisse.html

greifen die "Übersetzungen"

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Würde Note römisch 1 vergeben, doch hat das Modul (Events ranking) noch einen kleinen Fehler im Backend.

Nach dem Speichern des Moduls, kann keine Auswahl eines einzelnen Match gewählt werden. 

Ansonsten wie immer eine Top-Arbeit !!

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Perfekt wie immer!!

**Comment by diddipoeler** [comment]
Danke.

**Comment by llambion72** [comment]
I'm traveling. I will test it tomorrow when I return

**Comment by llambion72** [comment]
Thank you for repair my code, it works perfect!!!. If it was my first attempt to create a joomla module.
Thank you for all, this module is very usefull for me
