### ISSUE TITLE
Module Team Statistic Ranking Error??

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#716]
When I activated this module, my website don't work

A white and red error box appear with next message,

0 - SMStatisticSumevents: STATISTIC CLASS NOT DEFINED
![error](https://user-images.githubusercontent.com/20923398/43253763-f77ae26a-90c5-11e8-8f74-59c64b12ccd1.png)

**Comment by diddipoeler** [comment]
Please test it.

**Comment by llambion72** [comment]
I'm traveling. I will test it tomorrow when I return

**Comment by llambion72** [comment]
Now, this error appears,
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND tp.published = 1 GROUP BY pt.id ORDER BY total DESC, tp.id LIMIT 5' at line 7

**Comment by diddipoeler** [comment]
Please test it.
