### ISSUE TITLE
Benutzerzuweisung Tippspiel Backend

### ISSUE THREAD

**Issue by dei71** [diddipoeler/sportsmanagement#718]
Man kann manuell keine Tippspieler für das entsprechende Tippspiel im Backend zuweisen. Bei mir geht es nur über das frontend, indem der Benutzer sich über die Tippspielteilnahme anmeldet.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by dei71** [comment]
Hat sich nichts geändert. Wenn ich auf zuweisen klicke, kann ich die Benutzer auswählen, und auch übertragen. Nach dem speichern wird es aber nicht übernommen.

**Comment by diddipoeler** [comment]
Bei mir funktioniert es. Kannst du vielleicht noch einmal die Schritte aufzeichnen ?

**Comment by dei71** [comment]
Ich habe dir ein Video zugeschickt per tel.

**Comment by dei71** [comment]
Ich habe dir mal einen adminzugang geschickt, falls du selber nachsehen möchtest. 
LG

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by dei71** [comment]
Jetzt funktioniert es perfekt.

Vielen Dank
