### ISSUE TITLE
Alle Runden im Projekt zeigt eine Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#724]
Lässt man sich alle Runden im Projekt anzeigen, 
kommt folgende Fehlermeldung:

Fehler
Sie haben keine Berechtigung für den externen Datenbankzugriff.

![arbeitsflache 1_002](https://user-images.githubusercontent.com/2417767/43567891-726af5e2-9633-11e8-89e1-990282d5208f.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :+1:
