### ISSUE TITLE
Bearbeitung der Details eines Projektteams erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#732]
Die Bearbeitung der Details eines Projektteams erzeugt folgende Fehlermeldung:

Es ist ein Fehler aufgetreten!

0 Cannot use string offset as an array

**Comment by diddipoeler** [comment]
Den Fehler habe ich nicht.
Egal ob Joomla 3 oder Joomla 4.

**Comment by svdoldie** [comment]
oh man ;-(

**Comment by sigal** [comment]
Kann ebenfalls diddi bestätigen.
Keine Fehlermeldung

**Comment by svdoldie** [comment]
Dann muss ich mal schauen

**Comment by svdoldie** [comment]
Ich muss mich noch mal wegen diesem Problem melden.
Dieser Fehler tritt nur bei einem Team auf, ausgerechtet unseres ;-(
Ich habe mir mal den DB-Eintrag unter _sportsmanagement_project_team angesehen,
kann da allerdings nicht verdächtiges finden. Oder suche ich da an der falschen Stelle?

**Comment by sigal** [comment]
nur geraten. Vergleiche mal die Einstellungen Deines Teams unter Mannschaften  - Deine Mannschaft - mit Einstellungen anderer Teams.  :speech_balloon:

**Comment by sigal** [comment]
Wenn bei allen anderen Teams keine Fehlermeldung auftritt, muss es mit deinem Team, bzw. deren Einstellungen, oder dem Datenbankeintrag zu tun haben.
Zum Testen: neues team sv-doerpum anlegen. Team dem Club und der Saison zuweisen.

Unter Projektdaten Mannschaftzen wählen. Mannschften ändern wählen und neu erstellte Mannschaft mit deiner tauschen. Speichern und nochmals testen.

**Comment by diddipoeler** [comment]
Bei mir funktioniert das auch mit Trainingszeiten !

**Comment by svdoldie** [comment]
das ist für mich schlecht ;-(

**Comment by sigal** [comment]
Ich meine, dass dies mit fehlenden Felder in der DB zu tun hat. Der Fehler "0 Cannot use string offset as an array" kann auch auftreten, wenn bei einer Abfrage in der DB,  Felder in der Struktur der DB nicht vorhanden sind.

Wie ich mich erinnere, hattest Du schon mal fehlende Felder in der DB, die wir behoben haben.
Neue JSM Version - aber Alte JSM-DB importiert?

**Comment by svdoldie** [comment]
Hmm. Ich habe meine Seite in der Sommerpause neu aufgesetzt. Dabei habe ich nur den vorherigen DB-Stand importiert und JSM neu installiert. Dabei dürfte der Github-Stand derselbe gewesen sein. Von daher weiß ich jetzt nicht, wie diese fehlenden Felder zustande gekommen sind. Ich habe jetzt alle DB- und Update-Tools von JSM durchlaufen lassen. Ändert allerdings an meinem Problem. Was kann ich noch tun?

**Comment by diddipoeler** [comment]
Hat sich das erledigt?

**Comment by svdoldie** [comment]
Sobald ich diesen Termin in den Stammdaten der Mannschaft lösche,
ist auch die Mannschaft im Projekt wieder zu bearbeiten

**Comment by svdoldie** [comment]
Sobald man einen Termin beim Projektteam anlegt,
erscheint die Fehlermeldung wieder. Allerding wird der Termin gespeichert.
In den Stammdaten des Teams kann man ihn dann bearbeiten und speichern.
Und da kann man auch weitere Termine korrekt anlgen

**Comment by diddipoeler** [comment]
Das habe ich alles nicht. Weder bei Joomla 3 noch bei
Joomla 4.

**Comment by svdoldie** [comment]
Hmm,Mist :-(
Zumindest hat es sich so verbessert, dass ich Trainingszeiten über die Stammdaten anlegen kann.
Von daher kann meinetwegen hier zugemacht werden
