### ISSUE TITLE
Image for positions

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#733]
I've created new positions for my project and I chose any picture for them. But In the frontend, when I show a player profile this image don't be shown  because default.php for players don't use image field data, only use name of position plus .png to show image.
For example,
I create a new position, In spanish (Left Wind) Lateral Izquierdo
I assign any image
and in player view if you search into html code we can see that in position section we can found a Lateral Izquierdo.png but it is not shown because it have a blank spaces and image filename that I've assigned into positions don't be used

**Comment by llambion72** [comment]
I've added in site/models/players.php
$query->select('pos.picture AS position_image');  in line 77 and 138

and Replace
$backimage = 'images/com_sportsmanagement/database/person_playground/' . $this->teamPlayer->position_name . '.png'; 

for 

$backimage = $this->teamPlayer->position_image ;

And now works

**Comment by diddipoeler** [comment]
is in the github.

**Comment by diddipoeler** [comment]
Please test it.

**Comment by llambion72** [comment]
I'm on vacation. I will return on Sunday and i'll test the changes

**Comment by llambion72** [comment]
Now, it works perfectly.
Thank you
