### ISSUE TITLE
Vertex Shape5 Template and Bootstrap

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#734]
I use a Vertex template for my project.
I have a trouble, When I activate load css bootstrap into bootstrap plugins JSM options, many images disappear sush as little images into roster template, all clubs logo in the most of templates.
Any suggestions?

**Comment by sigal** [comment]
Don't enable plugin jsm_bootstrap for Shape5 Templates! 
They use their own customized bootstrap files.

Do not enable -Load Framework bootstrap- in Sports Management: Configuration

**Comment by llambion72** [comment]
Thank you for your advice!!
I'll disable it

**Comment by diddipoeler** [comment]
Können wir das schließen?
