### ISSUE TITLE
Backend-View: matches Layout: default Ereignisse:

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#736]
EREIGNISSE bearbeiten
In der Auswahlliste für Ereignissse werden die  Ereignisse der Spielertypen angezeigt.
Für Tormann, Verteidiger, Mittelfeld, Angreifer.
Also 4 x die gleichen Ereignisse.
Eg.
Torhüter: gelbe Karte, gelb-rote Karte, rote Karte, Tor
Verteidiger: gelbe Karte, gelb-rote Karte, rote Karte, Tor
Mittelfeld: gelbe Karte, gelb-rote Karte, rote Karte, Tor
Angreifer: gelbe Karte, gelb-rote Karte, rote Karte, Tor

Im Listenfeld Ereignisse: 4x gelbe Karte, 4x gelb-rote Karte, 4x rote Karte, 4x Tor

Dadurch werden auch im Matchreport (FE) die Ereignisse für jeden Spielertyp extra ausgegeben.

Zur bildlichen Erläuterung ein Bild
![ereignisse](https://user-images.githubusercontent.com/5115688/44058708-4e6164f4-9f4f-11e8-8b4a-ba1fdb51aeb7.jpg)

Hier haben wir 2x Gelbe Karte (1x Mittelfeld, 1x Angreifer)
3x Tor (1x Verteidiger, 1x Mittelfeld, 1x Angreifer)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Die Auswahlliste der Ereignisse ist wieder in Ordnung!

Die Ausgabe des Matchreport ist noch so wie oben beschrieben (TABS ??)
Auch die Einstellung im Template matchreprt -> Tab Ereignisse -> Registerkarten für die Anzeige der Ereignisse verwenden auf Nein bringt einen Abbruch:
Call to undefined method sportsmanagementHelperRoute::getPlayerRoute()
Soll ich dafür einen eigenen Issue aufmachen?

**Comment by bluesunny62** [comment]
also ich hab´s mal getestet bei mir läuft´s, auch mit der tab anzeige habe ich keine probleme

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by bluesunny62** [comment]
zeigt die ereignisse jeweils unter nur einem reiter an

**Comment by svdoldie** [comment]
Bei mir werden einige Ereignisse in der Timeline doppelt angezeigt
siehe http://svdoerpum.de/senioren/1-herren/spielplan/matchreport/0/5/42-verbandsliga-nord-2018-2019/4058-sv-doerpum_tus-collegia-juebek

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
So weit so gut!
![ereignisse4](https://user-images.githubusercontent.com/5115688/44103252-01e8daba-9fec-11e8-9478-b30f5ac16e2b.jpg)


Bis auf die Einstellung im Template matchreprt -> Tab Ereignisse -> Registerkarten für die Anzeige der Ereignisse verwenden auf Nein bringt einen Abbruch:
Call to undefined method sportsmanagementHelperRoute::getPlayerRoute()

![ereignisse3](https://user-images.githubusercontent.com/5115688/44102997-552ff83a-9feb-11e8-9778-c037f611fa2a.jpg)
![ereignisse2](https://user-images.githubusercontent.com/5115688/44102888-1065cffe-9feb-11e8-86bd-340524f148e0.jpg)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Perfekt!  :+1:
