### ISSUE TITLE
Backend-View: projectpositions Layout: default

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#737]
Nach Abwählen von Positionen/Funktionen wird ein Fehler ausgegeben. (siehe Bild)

> Fehler
sportsmanagementModelProjectpositions::updateprojectpositions You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3

Nach dem Speichern, werden wieder alle freigeben Positionen (unter Positionen) im Projekt gelistet.

![positions-functions](https://user-images.githubusercontent.com/5115688/44269824-f27c5100-a235-11e8-9de4-1fb8bcd9c953.jpg)

Die vor dem Speichern abgewählten Positionen sind im Projekt wieder vorhanden.
![positions-functions02](https://user-images.githubusercontent.com/5115688/44270708-86e7b300-a238-11e8-93a9-41abe0ae9134.jpg)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Funktioniert!
Wie immer.  :clap:  :thumbsup:
