### ISSUE TITLE
Nach update vom 19.08. Fehlermeldung bei JSM !!!

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#742]
Nach dem gestrigen Update erscheint auf allen Seiten wo JSM genutzt wird folgende Fehlermeldung:

0 - syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :-)

**Comment by svdoldie** [comment]
Ich muss den Issue nochmal öffnen.
In der Ergebnis-Anzeige existiert der Fehler noch

**Comment by svdoldie** [comment]
läuft :-)
