### ISSUE TITLE
Spieler zuordnen nicht möglich

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#748]
Momentan ist es nicht möglich Spieler zu einer Mannschaft zuzuordnen.
Es fehlen z.B. die Speicherbuttons, es gibt allerdings noch mehr Darstellungsfehler,
wie bei den Filtern zu sehen ist.
Siehe Bild
![liste der zugeordneten spieler - sv dorpum online - administration - mozilla firefox_003](https://user-images.githubusercontent.com/2417767/44625538-465cf900-a90c-11e8-9f32-34e081b6c307.png)

**Comment by diddipoeler** [comment]
Bitte mit Vorsicht testen !

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :-)
