### ISSUE TITLE
Eingabe Gästeteam nicht möglich

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#751]
Die Eingabe des Gästeteams ist nicht möglich. Der entsprechende Buttom zeigt keine Reaktion. Beim Gastgeber werden zwei Buttons angezeigt, der rechte davon funktioniert.
Der linke, zeigt die Anzahl der Spiele und Staff an.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft soweit :-)
Aber warum sind seit einiger Zeit zwei Buttons nötig?

**Comment by diddipoeler** [comment]
Ein für die Heimmannschaft und einen für die Gästemannschaft.
Da läuft der Update besser.

**Comment by svdoldie** [comment]
ich habe mich falsch ausgedrückt. Ich meinte zwei Symbole pro Team

**Comment by diddipoeler** [comment]
Sollten wir erst einmal so lassen.

**Comment by svdoldie** [comment]
Ok :-)
