### ISSUE TITLE
"All clubs in JSM" the list is empty.

### ISSUE THREAD

**Issue by Rogackis** [diddipoeler/sportsmanagement#752]
I am trying to display on the main page of the site: "All clubs in JSM" unfortunately the list is empty.
[http://www.vaco2015.linuxpl.eu/joomla/index.php](url)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Rogackis** [comment]
keine Änderung :(

**Comment by diddipoeler** [comment]
Vorrausetzung:
Jeder Verein muss eine Mannschaft haben.
Jede Mannschaft muss einer Saison zugeordnet sein.
Jede Mannschaft muss einem Projekt zugeordnet sein.

**Comment by teddyfresco** [comment]
This happens to me as well but only if:
1 I select "current season" on all clubs menu item
2 There's no current season manually set on Options > Backend tab
Please, try to set a season and tell us what happens...
Maybe diddi can add to the menu item a control to check if a season is actually set?

**Comment by Rogackis** [comment]
I have fulfilled the conditions and works 👍
