### ISSUE TITLE
Stammdaten: Teams bearbeiten erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#753]
Wenn man in den Stammdaten eine Mannschaft bearbeiten möchte,
erscheint nur folgende Fehlermeldung:
jform[sports_type_id] has no layout assigned.

**Comment by diddipoeler** [comment]
Teams müssten wieder gehen.

**Comment by svdoldie** [comment]
läuft :-)
