### ISSUE TITLE
Backend: Personen im Projekt lassen sich nicht bearbeiten

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#754]
Will man eine Person in einem Projekt bearbeiten erscheint nur folgende Fehlermeldung:
Es ist ein Fehler aufgetreten!

0 jform[position_id] has no layout assigned.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :-)
