### ISSUE TITLE
Keine eigene Templates im Projekt möglich

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#755]
Momentan kann man keine eigenen Templates im Projekt anlegen,
sondern nur die Mastertemplates bearbeiten.
Siehe Bild
![bildschirmfoto-3](https://user-images.githubusercontent.com/2417767/44671771-b8296580-aa26-11e8-8982-592c3dae8c7b.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Fehler noch vorhanden

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
keine Änderung

**Comment by diddipoeler** [comment]
Ich kann den Fehler nicht nachvollziehen, da bei mir alles läuft.

**Comment by svdoldie** [comment]
Hmm, hängt dann wohl auch mit meiner DB zusammen

**Comment by svdoldie** [comment]
hat ja kein anderer das Problem...
