### ISSUE TITLE
Projekteinstellungen lassen sich nicht speichern

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#756]
Die Projekteinstellungen lassen sich momentan nicht speichern.
Siehe Bild
![bildschirmfoto-2](https://user-images.githubusercontent.com/2417767/44671882-fe7ec480-aa26-11e8-9779-0ec5524670c8.png)

**Comment by sigal** [comment]
Das kann ich nicht bestätigen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :-)
