### ISSUE TITLE
Frontend: View Nextmatch erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#767]
Lässt man sich die Ansicht Nextmatch anzeigen,
erscheint folgende Fehlermeldung:
0 - syntax error, unexpected '('
siehe http://svdoerpum.de/component/sportsmanagement/nextmatch/0/0/42-verbandsliga-nord-2018-2019/4102-sg-leck-achtrup-ladelund_sv-doerpum

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Jetzt kommt folgende Fehlermeldung:
0 - Tabelle „club“ wird nicht unterstützt! Datei nicht gefunden!

**Comment by sigal** [comment]
Bei mir läüft es.

**Comment by svdoldie** [comment]
gibt's doch nicht :-(

**Comment by sigal** [comment]
http://jsm.stony-sport4u.de/d-1-bundesliga/ergebnisse-bl-2018-19/nextmatch-schalke04

Läuft irgendein JSM-Modul bei der Anzeige? Bin noch am Testen, da einige Module Fehler haben und die Seite damit lahmlegt.

**Comment by svdoldie** [comment]
nein, ich habe Module nur auf der Startseite

**Comment by sigal** [comment]
Hab jetzt auf Deine Seite (Link vom 1. Posting) geschaut und dort läuft doch die Anzeige.!!

**Comment by svdoldie** [comment]
Ruf den link bitte mal von meiner Startseite aus dem Matchesmodul auf. Geht es dann bei dir auch?

**Comment by svdoldie** [comment]
Oh man sorry. Ich Idiot. Das ist der Spielbericht http://svdoerpum.de/component/sportsmanagement/matchreport/0/0/42-verbandsliga-nord-2018-2019/4095-mtv-tellingstedt_sv-doerpum

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Läuft 👍
