### ISSUE TITLE
Ready for Joomla4

### ISSUE THREAD

**Issue by iseidler** [diddipoeler/sportsmanagement#773]
Fehlermeldung Backend.
Betreten von "Current Season" nicht möglich.
_500 JHTMNL sliders not found_

<img width="343" alt="j4selectcurrentseason" src="https://user-images.githubusercontent.com/41539065/45100615-0d9dfa80-b12a-11e8-8b2a-3a76db3ee489.png">

<img width="438" alt="j4currentseasonselected" src="https://user-images.githubusercontent.com/41539065/45100647-1c84ad00-b12a-11e8-8422-990f7295f32a.png">

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by iseidler** [comment]
Sehr gut :-)

<img width="468" alt="newcurrentseason" src="https://user-images.githubusercontent.com/41539065/45107616-6a091600-b13a-11e8-882d-20aabf0c4cbf.png">
