### ISSUE TITLE
Ready for Joomla4 (Edit matches)

### ISSUE THREAD

**Issue by iseidler** [diddipoeler/sportsmanagement#774]
Fehler im Backend.
Bearbeitung der Spiele (Edit matches).
1. Das Input Feld für das Datum ist zu klein
2. Nach Ergebniseingabe kann nicht gespeichert werden: _Error
sportsmanagementModelMatch::saveshort 924Column 'result_type' cannot be null_

<img width="367" alt="j4editmatcheserrorsave" src="https://user-images.githubusercontent.com/41539065/45101474-d29cc680-b12b-11e8-8929-9102bb2cadf6.png">

<img width="406" alt="j4editmatchesdatefield" src="https://user-images.githubusercontent.com/41539065/45101465-cd3f7c00-b12b-11e8-8232-579a33030dcb.png">

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by iseidler** [comment]
Fehler unverändert +++

**Comment by iseidler** [comment]
Sorry, war zu hektisch.
Tatsächlich war es eine **neue** Fehlermeldung: 
_sportsmanagementModelMatch::saveshort 924Column **'match_result_type'** cannot be null_
Gefolgt von: _sportsmanagementModelMatch::saveshort 924Column__  **'division_id'** cannot be null__
Dann kehrt Ruhe ein...

**Comment by diddipoeler** [comment]
Tja, Joomla 4 bestraft jeden Programmierfehler sofort :-)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by iseidler** [comment]
Jo, allerbest!
