### ISSUE TITLE
Ready for Joomla4 (Add match)

### ISSUE THREAD

**Issue by iseidler** [diddipoeler/sportsmanagement#775]
Fehlermeldung Backend.
Es können keine Spiele angelegt werden **(Button Mass add match)**
_COM_SPORTSMANAGEMENT_ADMIN_MATCH_CTRL_ERROR_ADD_MATCH__

<img width="475" alt="j4addmatcherror" src="https://user-images.githubusercontent.com/41539065/45104274-05e25400-b132-11e8-89ab-c41ca3cbc1d7.png">

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by iseidler** [comment]
_New data record with ID: 28 was created!_
Betätige "Close and comment"
