### ISSUE TITLE
Ready for Joomla4

### ISSUE THREAD

**Issue by iseidler** [diddipoeler/sportsmanagement#777]
Fehler Backend
Button _New Github Issue_ gibt "An Error has occurred, Class JGitHub not found"
Auch _JSM GitHub Update_ funktioniert nicht.

<img width="508" alt="githupupdate" src="https://user-images.githubusercontent.com/41539065/45148040-a84c1700-b1c6-11e8-90f2-83cbc25e376d.png">

**Comment by diddipoeler** [comment]
Bei mir läuft der Github Udate aber.
Joomla! 4.0.0-alpha3

**Comment by iseidler** [comment]
Nach Änderung der Schreibrechte hat es jetzt auch bei mir geklappt!
Installation auf neuestem GitHub-Stand.
Danke.
