### ISSUE TITLE
Ready for Joomla4 (Display results)

### ISSUE THREAD

**Issue by iseidler** [diddipoeler/sportsmanagement#778]
Fehler Frontend
Seitenaufruf Spielergebnisse (Display results) nicht möglich:

 Notice
: Undefined variable: events in
/Applications/XAMPP/xamppfiles/htdocs/j4alpha44/components/com_sportsmanagement/models/project.php

Notice
No access to result storage

Error
sportsmanagementModelProject::getProjectEvents 1305 'j4alpha5.et.name' isn't in GROUP BY
sportsmanagementModelProject::getMatchEvents 1798 'j4alpha5.me.event_type_id' isn't in GROUP BY
sportsmanagementModelProject::getMatchEvents 1799 1055

0 Argument 1 passed to Joomla\Utilities\ArrayHelper::sortObjects() must be of the type array, boolean given, called in /Applications/XAMPP/xamppfiles/htdocs/j4alpha44/components/com_sportsmanagement/models/project.php on line 1832

**Comment by diddipoeler** [comment]
Bei der Anzeige im Frontend oder bei der Eingabe der Ergebnisse
im Frontend ?

**Comment by sigal** [comment]
Bei der Anzeige Menü Results im Frontend.
Dieser Fehler repliziert sich auch bei der Tabelle, Siehe zum Prüfen: Modul Tabelle oder Link im Menü Results
http://j4.stony-sport4u.de/

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by iseidler** [comment]
Das sieht schon sehr viel besser aus
<img width="172" alt="sc" src="https://user-images.githubusercontent.com/41539065/45204852-c7a77a80-b280-11e8-9834-a3eda89813fc.png">

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by iseidler** [comment]
Bedaure...

http://wp1082365.server-he.de/j400alpha5/

Oder direkt

http://wp1082365.server-he.de/j400alpha5/index.php?option=com_sportsmanagement&view=results&cfg_which_database=0&s=1:bundesliga-18-19&p=1:fussball-bundesliga-18-19&division=0&r=0&Itemid=120

GitGub-Aktualisierung gegen 15:00 Uhr

<img width="321" alt="jsmgithubupdateftp" src="https://user-images.githubusercontent.com/41539065/45221024-72835d00-b2b0-11e8-9cff-3fa7f06c6d49.png">

**Comment by sigal** [comment]
Auf meiner Testseite funktioniert die Anzeige ohne Fehler.
Einschränkung: SEF ausgeschaltet.
Auch GitHub Update von vor 10 Minuten
http://j4.stony-sport4u.de/index.php?option=com_sportsmanagement&view=results&cfg_which_database=0&s=103:2018-19&p=3772:deutschland-1-bundesliga-2018-19&r=0&Itemid=108

**Comment by iseidler** [comment]
Rätselhaft...
SEF ist ebenfalls auf aus. Bei "YES" funktionieren die Links sonst auch nicht _(404 - Seite nicht gefunden)_

**Comment by diddipoeler** [comment]
Eingeschalteter SEF funktioniert garnicht 👎 
Da muss ich auch noch dran.

**Comment by iseidler** [comment]
Die Fehlermeldun verschwindet erst, wenn die Zeile 1791 in der project.php so geändert wird:

$query->group('me.event_type_id,me.id,me.event_time,me.notice,me.event_sum,me.projectteam_id,t.alias, t.id, et.name, t.name, p.picture, tp.picture,p.firstname, p.nickname, p.lastname, p.alias, p.id');

Scheint mir damit enorm "aufgepustet", kann das so richtig sein? Und die Frage, warum das Problem bei Stony nicht auftritt?!

**Comment by sigal** [comment]
Die Warnung vom JInstaller, dass er das XML-Setup file nicht findet hab ich nicht.
Da scheint irgend was faul zu sein.
Obwohl, wir testen doch noch eine Joomla Alpha Version und die ist nach den noch offenen Issues auch noch mit Vorsicht zu geniesen! https://github.com/joomla/joomla-cms/issues
Frage: Welche PHP-Version läuft?
Meinerseits teste ich mich mit V_7.0.31 hoch.
Error Reporting ist auf Maximum.
Und habe keine Hand im Code angelegt!

Mein Server ist immer am letzten Stand. Selbst ist der Mann.

**Comment by iseidler** [comment]
Bin Hosteurope-Kunde, standardmäßig kann PHP 5.6 oder 7.0 gewählt werden, ich nutze die 7.0.
Ab 24.10. wird dann automatisch auf 7.2. umgestellt.
Lokal arbeite ich  mit XAMPP Php 7.1.12-0.
Error-Reporting zum Testen immer Development.
Das, was unter http://wp1082365.server-he.de/j400alpha5/ vom Server kommt, ist ebenfalls frei von Code-Änderungen :)

**Comment by iseidler** [comment]
Neues GitHub-Update 18:12 Ihr  ohne jede Einwände oder Warnungen
Keine Fehlermeldung mehr bei Aufruf der Ergebnis-Seite.
Aber, kleiner Wermutstropfen, bei Bearbeitung als Frontend-Editor (Account testuser, Login und Passwort ebenfalls testuser) Errormeldung nach dem Speichern.
_1048 Column 'result_type' cannot be null._

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by iseidler** [comment]
Fast +++

<img width="371" alt="editresultsfrontend" src="https://user-images.githubusercontent.com/41539065/45239633-323ed180-b2e6-11e8-8e89-4b1353e021b3.png">

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by iseidler** [comment]
### Einen haben wir noch

_Fehler
sportsmanagementModelResults::saveshort 791 Column 'content_id' cannot be null
sportsmanagementModelResults::saveshort 792 1048_

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Läuft  :thumbsup:

**Comment by iseidler** [comment]
Begeistert :)
