### ISSUE TITLE
Ready for Jommla4 (Tippspiel-Templates)

### ISSUE THREAD

**Issue by iseidler** [diddipoeler/sportsmanagement#780]
Sorry, falsche Taste.
Fehler Backend.
Bei Aufruf der Frontend-Tippspiel-Templates: **"Call  to undefined method Joomla\CMS\Factory::getURI()"**.
Egal, welches Template.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by iseidler** [comment]
Tadellos jetzt!
