### ISSUE TITLE
JSM 1.0.65 Installation

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#793]
Ist es noch möglich, die master.zip abzuändern, da bei der Installation (Update und Neuinstalltion) ein Fehler des Modul teamstatistics_counter auftritt. Im Paket sind falsch benannte englische Sprachdateien (
@tdittmann) inkludiert.

Sie wurden von mir schon bereinigt und bei einen GitHub Update inkludiert, sind aber im Master.zip nicht inkludiert. - Leider um 5 Sekunden zu spät erkannt und die neue Version schon online.

![teamstatistics_counter](https://user-images.githubusercontent.com/5115688/45316227-c3a48280-b536-11e8-888d-1976672ce1bc.jpg)

![teamstatistics_counter_2](https://user-images.githubusercontent.com/5115688/45316248-d3bc6200-b536-11e8-90ee-518b2e3d6ea1.jpg)

![teamstatistics_counter_3](https://user-images.githubusercontent.com/5115688/45316261-e040ba80-b536-11e8-89cd-26f4e521d74d.jpg)

**Comment by diddipoeler** [comment]
Ich muss sowieso eine neue Version erstellen !

**Comment by diddipoeler** [comment]
Neue Version ist fertiggestellt.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen !
