### ISSUE TITLE
Saving or closing a project team's page creates loop

### ISSUE THREAD

**Issue by teddyfresco** [diddipoeler/sportsmanagement#794]
On my testbed based on Joomla 3.8.12 Apache 2 and php 7.2.6 I'm experiencing this:
whenever I enter a project team's page on admin, whatever the club, or the project (or if the project has been imported or started from scratch), when I hit "close" or "save and close" the page becomes blank and enters a loop (it's like it loads infinite times)
If I hit "save" it behaves correctly, if I hit "Save & new" or "save as copy" I get this error:
An error has occurred.
    1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 3

**Comment by diddipoeler** [comment]
Joomla 3 oder 4 ?

**Comment by teddyfresco** [comment]
3

Il mer 12 set 2018, 06:14 diddipoeler <notifications@github.com> ha scritto:

**Comment by teddyfresco** [comment]
Hi sigal, if you enter a project team's page, you should see a blank page with infinite refresh when you click on close or save and close button. Save & new or save as copy should show you the error above. Can you reproduce it?

**Comment by sigal** [comment]
In which view? admin site or frontend editing site?

**Comment by teddyfresco** [comment]
admin site

**Comment by sigal** [comment]
I don't have this issue. Tested on Joomla 3.8.12 and Joomla! 4.0.0-alpha4 Alpha [ Amani ] with PHP 7.0.31
Last JSM GitHub update

**Comment by teddyfresco** [comment]
I've just tested on localhost, php 5.6.33, and the issue is the same...

**Comment by sigal** [comment]
You're right. Save & New and Save As Copy cause a MySQL error in "Edit Project team"
Save and Save & close causes no error or infinity loop

**Comment by diddipoeler** [comment]
Bitte noch einmal testen !

**Comment by teddyfresco** [comment]
It works! 
Tested on php 5.6 and 7. 
Now I don't see Save & New and Save As Copy, is it right?
Issue goes on on frontend editing...

**Comment by diddipoeler** [comment]
Bei den Projekteams machen diese Funktionen keine Sinn,
deshalb wurden sie ausgeschaltet.
