### ISSUE TITLE
Backend-View: projectreferees Layout: default (schiedsrichter lassen sich nicht zurordnen)

### ISSUE THREAD

**Issue by Europekicker** [diddipoeler/sportsmanagement#796]
Bei mir lassen sich die Schiedsrichter nicht zuordnen.
<img width="1882" alt="shiribug" src="https://user-images.githubusercontent.com/14942144/45599373-cb5aa000-b9ea-11e8-9d19-5a44243e54af.png">

**Comment by PhantoSGE** [comment]
Nachdem ein Spieler ausgewählt und gespeichert wird, wird er nicht in der Liste angezeigt.
Wenn man ihn erneut auswählt und speichert erscheint folgende Fehlermeldung.
![image](https://user-images.githubusercontent.com/9608697/45611272-2332ee80-ba5f-11e8-9498-ef66826a672f.png)

Gruß

**Comment by diddipoeler** [comment]
@PhantoSGE Immer mit der Ruhe.
Erst wenn ich sage das getestet werden kann, dann kann man auch testen.

**Comment by PhantoSGE** [comment]
Ok. Sorry

**Comment by diddipoeler** [comment]
Bitte einmal testen !

**Comment by Europekicker** [comment]
Funktioniert.
Danke
