### ISSUE TITLE
Backend: Mannschaften können Projekt nicht zugeordnet werden

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#797]
Hallo zusammen,

Mannschaften lassen sich dem Projekt nicht zuordnen.
Keine Reaktion wenn ich einen der Button nutze
![image](https://user-images.githubusercontent.com/9608697/45611076-78bacb80-ba5e-11e8-84ff-ae5b6152d0e2.png)

Gruß

**Comment by sigal** [comment]
Kann ich nicht nachvollziehen, wenn Mannschaften die richtige Saison, sprich die des Projekts zugeordnet sind.
Außerdem ist im angehängten Sreenshot nur die Hälfte der Ansicht vorhanden.

Zuerst den zu zuordneten Mannschaften die Saison zuweisen!

![teams_zuweisen](https://user-images.githubusercontent.com/5115688/45612687-14026f80-ba64-11e8-8af1-2cee1750e1be.jpg)

**Comment by PhantoSGE** [comment]
Die Saison ist ausgewählt.
![image](https://user-images.githubusercontent.com/9608697/45613669-58dbd580-ba67-11e8-82f4-a9b421fbbece.png)

Wenn ich nun zuweisen möchte funktioniert es nicht.
![image](https://user-images.githubusercontent.com/9608697/45613695-65f8c480-ba67-11e8-8b38-670e18286667.png)

Wie man sieht hat es bis vor ein paar Tagen noch funktioniert. 
Leider kann ich nicht sagen seit wann es nicht mehr funktioniert

Gruß

**Comment by Europekicker** [comment]
gleiches problem hier

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Funktioniert wieder
