### ISSUE TITLE
0 - Call to a member function getLeagues() on boolean

### ISSUE THREAD

**Issue by Europekicker** [diddipoeler/sportsmanagement#799]
Wenn ich das Modul alle Ligen in einen Menüeintrag lege werden zwar die Projekte angezeigt aber bei klick auf den link kommt dieser fehler.
<img width="770" alt="frhler" src="https://user-images.githubusercontent.com/14942144/45877161-3a464900-bd9d-11e8-88de-c867b5249d34.png">
<img width="1710" alt="0 - call to a member function getleagues on boolean" src="https://user-images.githubusercontent.com/14942144/45877201-51853680-bd9d-11e8-9b27-2ebd54c12316.png">

**Comment by diddipoeler** [comment]
Bitte noch einmal testen !

**Comment by Europekicker** [comment]
ok funktioniert
