### ISSUE TITLE
upload Spielerbilder und Wappen in Maschaften nicht möglich

### ISSUE THREAD

**Issue by Europekicker** [diddipoeler/sportsmanagement#800]
Bilder können nicht zugeordnet werden es kommt nach auswahl nur der ladekreis ohne das etwas passiert.

Funktionierte bisher ohne probleme
<img width="1050" alt="keinbild" src="https://user-images.githubusercontent.com/14942144/45918576-4576a300-be89-11e8-93a2-8ef4f3f34509.png">

**Comment by diddipoeler** [comment]
Das ist doch die Ansicht der Personen oder nicht ?

**Comment by Europekicker** [comment]
es betrifft eigendlich alles wo ein Bild zum hochladen oder auswählen angeboten wird.
Neue Person erstellen person edit Manschaft erstellen und edit.
Also der fehler muss wo anders liegen habe mir den code slebst noch nicht nageschaut da du besser weist wo was miteinander zusammenspielt.

**Comment by diddipoeler** [comment]
Den Fehler habe ich nicht !
Oder ist das auf Joomla 4 ?

**Comment by sigal** [comment]
Diesen Fehler gibt es nur mit Joomla 4 und Sportsmanagement als Media Tool. Aber auch mit Joomla als Media Tool ist keine Auswahl möglich, da es bei bei Klick auf den root von images/com_sportsmanagement/database/ , einen internal server error gibt.

**Comment by Europekicker** [comment]
Ich nutze joomla 3.8 ich konnte das Problem lösen.
Ich hab joomla als media tool ausgewählt,und abgespeichert.
Dann wieder zurück zum media tool von sportsmanagment  und es ging wieder.

**Comment by diddipoeler** [comment]
Bitte einmal mit Joomla 3 und 4 testen !

**Comment by diddipoeler** [comment]
Bitte einmal mit Joomla 3 und 4 testen !

**Comment by Europekicker** [comment]
leider noch nicht erfolgreich.
habe auch mal versucht die bilder zu löschen die schon im upload ordner sind dabei erhalte ich diesen fehler

0 Using $this when not in object context 

link dazu

administrator/index.php?option=com_sportsmanagement&task=imagehandler.delete&&tmpl=component&type=persons&rm[]=bilddashochgeladenwurde.jpg

wieder in verbindung mit media tool von sportsmanagment

**Comment by diddipoeler** [comment]
Joomla 3 oder 4 ?

**Comment by Europekicker** [comment]
joomla 3

**Comment by diddipoeler** [comment]
Bitte einmal mit Joomla 3 und 4 testen !

**Comment by sigal** [comment]
Media Tool Sports Management: Funktioniert nur bedingt - Bilder lassen sich auswählen, hochladen. Meine subjektive Bewertung: Note 4+ ( Keine Möglichkeit, um einen anderen Ordner auszuwählen, das Löschen der Bilder ohne Abfrage, weiters für User nicht nachvollziehbar, das man auf das Bild klicken muß und dieses dann schon gewählt ist. Meine Anregung - klick auf ein Bild soll das Modalfenster schließen.

Media Tool Joomla: Für mich der der subjektive Favorit. Funktioniert exzellent. Note 2+.

Joomla 4 Test: Auswählen von Bilder (Personen) möglich, aber Speichern und Speichern & Schließen führen auf Neue Person erstellen. Schließen (Close) gibt folgenden Fehler: 

![person_close_error](https://user-images.githubusercontent.com/5115688/45960580-d2059a80-c01c-11e8-93d6-e91de84ed14f.jpg)

Test für andere Ansichten noch nicht abgeschlossen!

**Comment by sigal** [comment]
Warum das Rad neu erfinden, wenn Joomla es schon mitbringt.
Mit dem alten Mediatool war ich schon in der alten Version nicht hellauf begeistert.
Wie schon gesagt meine subjektive Meinung.
Man kann aber auch im Forum nachfragen, wie die User dazu stehen.

**Comment by sigal** [comment]
Das Joomla Tool müßte nur dahin gehend ein klein wenig verfeinert werden, dass man egal von welcher view, immer in den von JSM vordefinierten Image-Ordner startet.
z.B.: view person -> /images/com_sportsmanagement/database/persons
Wäre auch für das Hochladen eigener Bilder vorteilhaft, da man keinen Ordnerwechsel vornehmen muß.

**Comment by svdoldie** [comment]
Sehr gute Idee 👍
Ich benutze übrigens auch ausschließlich das joomla-Tool

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Mit Joomla 3 alles paletti.
Mit Joomla 4 hakt es noch

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Joomla 3 und Joomla Mediatool?

Momentan keine Aus-oder Abwahl von Bilder möglich!

Wird das Tool jetzt eingestellt und nur Sports Management als Media-Tool bevorzugt?

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Notwendige Anpassungen für Media-Tool Joomla
ausgetestet mit 
Joomla 3.9.12
PHP-Version: 7.2.24
------------------------------------
Stammdaten
------------------------------------
Ligen (Pfad Bild)
Int. Verbände (Pfad Flagge + Bild)
Landesverbände (Pfad Flagge + Bild)
Position (Pfad Bild)
Mannschaften (Pfad Bild)
Sportstätten (Pfad Bild)
Sportarten (Pfad Bild)
------------------------------------
Projekt bearbeiten (Pfad Bild)
Projektmannschaft bearbeiten (Pfad Bild + Heimtrikot + Auswärtstrikot)

Subjektiv finde ich das Laden vom Joomla Media-Tool deutlich schneller, als das Media-Tool SportsManagement, aber das habe ich schon mal angemerkt (Neuerfindung des JSM Media-Tool - Joomla hat das doch schon integriert)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Passt! :+1:

**Comment by diddipoeler** [comment]
in joomla 4 ist das aber richtig mist :-(

**Comment by sigal** [comment]
Hab ja auch nur von Joomla 3 gesprochen. :wink:

in Joomla 4 läüft so manches nicht.

**Comment by diddipoeler** [comment]
Was läuft denn in Joomla 4 noch nicht ?

**Comment by sigal** [comment]
Installiert: PHP-Version: 7.2.24

![Joomla 4 - 4 0 0-beta1-dev](https://user-images.githubusercontent.com/5115688/68123605-c5d15980-ff0d-11e9-893c-169387974c86.jpg)

Zu sehen hier: https://j4.stony-sport4u.de/

Hab mal 3 Menüpunkte angelegt. Fehlermeldung sind zu sehen

Im BE: Verein bearbeiten und speichern bringt die Eingabemaske zur Anlegung eines neuen Verein. Detto bei Speichern & Schließen.

Mal für das erste.

**Comment by diddipoeler** [comment]
Nach der Installation von Joomla 4 erhalte ich diesen Fehler:
Error: Call to a member function getPaths() on null: Class 'Joomla\Plugin\System\Debug\Storage\FileStorage' not found

**Comment by diddipoeler** [comment]
you may need to delete the file libraries/autoload_psr4.php to force it to regenerate with the debug plugin

**Comment by diddipoeler** [comment]
Habe auf Joomla 4.0.0 beta 1 dev update gemacht.
jetzt finde ich nichts mehr. kann nichts mehr installieren u.s.w.

**Comment by sigal** [comment]
Du musst nach dem Update auf die Beta die Joomla Datenbank reparieren, da ein paar Tabellen fehlen!

![Repair_joomla_database](https://user-images.githubusercontent.com/5115688/68155098-4ceff300-ff49-11e9-8bbb-4f2f65f91444.jpg)

Dann 

![repair_database](https://user-images.githubusercontent.com/5115688/68155179-74df5680-ff49-11e9-8dc6-831b633dcdfe.jpg)

![Manage_extension](https://user-images.githubusercontent.com/5115688/68155233-90e2f800-ff49-11e9-9264-c21e8f5896e2.jpg)

![Optionen_Beta](https://user-images.githubusercontent.com/5115688/68155270-a7894f00-ff49-11e9-82c8-6fd33fe1ae0c.jpg)

**Comment by svdoldie** [comment]
Beim DFBnet-Import erscheint diese Fehlermeldung:
500 JHtmlBehavior::modal not found.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Die Fehlermeldung ist jetzt weg und der Import wird anscheinend auch durchgeführt.
Allerdings wird das Projekt nicht angezeigt. Ein per XML-Import importiertes Projekt schon.

PS: vielleicht ist es besser, wenn der ursprüngliche Fehler behoben ist, hier zuzumachen und für die anderen Fehler eigene Issues zu speichern

**Comment by diddipoeler** [comment]
alles klar wird gemacht.
