### ISSUE TITLE
Backend: Spiele bearbeiten - Bilder zum Spiel hinterlegen

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#802]
Moin zusammen,

Beim Versuch ein Bild zum Spiel zu hinterlegen erfolgt keine Reaktion
![image](https://user-images.githubusercontent.com/9608697/45933599-81486000-bf90-11e8-900f-ccd97f6b712e.png)
![image](https://user-images.githubusercontent.com/9608697/45933600-8d342200-bf90-11e8-9d52-f0a4863ea488.png)

Gruß

**Comment by sigal** [comment]
So wie es oben angezeigt wird, ist das Bild schon hinterlegt. Der Button "Einfügen" kann von diddi getrost entfernt werden. Das Hochladen des Bildes, oder Bilder hat schon alles im Matchreport des Spieles eingefügt!

**Comment by PhantoSGE** [comment]
Danke dir. Leider wird es im Matchreport nicht angezeigt.

**Comment by PhantoSGE** [comment]
Ok. Dann passt irgendwas bei mir nicht. Danke dir für die mühe.
