### ISSUE TITLE
http://jsm-wiki.diddipoeler.de

### ISSUE THREAD

**Issue by Europekicker** [diddipoeler/sportsmanagement#804]
Hallo weis leider nicht wie es hier im git mit pm oder mit email oder so funktioniert,aber dein wiki wird vollgespammt.

jsm-wiki.diddipoeler.de/index.php?search=google&title=Spezial%3ASuche&go=Seite

ADULT sachen schau mal drüber nicht das du noch zur verantwortung dafür gezogen wirst.

**Comment by sigal** [comment]
Danke @Europekicker für diesen Hinweis!

Irgendwie kommen diese Spammer auf die Diskussionsseite und spammen diese voll.
Hab das mal alles auf dieserSeite gelöscht.
Diddi kannst du diese Diskussionsseite bitte sperren?!

**Comment by Europekicker** [comment]
Das mit anonymus wird nicht viel bringen wegen captcha das Schütz nicht wirklich veraltet,habe selbst ein wiki.
Ich habe die Registrierung komplett abgeschaltet.
Es ausgereifte bots die das problemlos Überwinden.

**Comment by svdoldie** [comment]
Ich habe gerade versucht ein Benutzerkonto zu erstellen, um meine Anleitung für den DFBnet-Import dort online zu stellen. Leider funktioniert das aufgrund der recaptcha-version nicht.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Funktioniert 

Ich habe die Anleitung mal online gestellt. Ich hoffe das ist so in Ordnung

**Comment by diddipoeler** [comment]
Wenn man jetzt auf die Onlinehilfe klickt, erhält man Deine Dokumentation.
Ist das nicht ein tolles Programm, wo man direkt die Hilfe angezeigt bekommt ?

**Comment by svdoldie** [comment]
Jepp, echt top !!! :+1:

**Comment by svdoldie** [comment]
wenn das mit dem Spam behoben ist, kann auch dieser issue geschlossen werden 👍

**Comment by diddipoeler** [comment]
Seite wurde geleert.

**Comment by svdoldie** [comment]
sicher? http://jsm-wiki.diddipoeler.de/index.php?search=google&title=Spezial%3ASuche&go=Seite
oder dauert es ne Zeit bis das wirksam ist?

**Comment by sigal** [comment]
es gibt mehr Seiten die vollgemüllt sind. Leider kann ich die nicht löschen, da keine Berechtigung.
sieh an: http://jsm-wiki.diddipoeler.de/index.php?title=Spezial:Nicht_kategorisierte_Seiten&limit=500&offset=500
Werde den link nach 1 Stunde löschen, da Tante Google das auch indiziert! OK?

**Comment by svdoldie** [comment]
👍

**Comment by diddipoeler** [comment]
Seiten gelöscht.

**Comment by diddipoeler** [comment]
Jau.
Jetzt habe ich erst einmal die Extension: https://www.mediawiki.org/wiki/Extension:SmiteSpam installiert.
So und nu muss ich die ganzen Idioten löschen.

**Comment by diddipoeler** [comment]
So, sieht es jetzt besser aus ?

**Comment by svdoldie** [comment]
sehr gut 👍

**Comment by sigal** [comment]
Hab auch nichts mehr gefunden.
Gestern die Seite [http://jsm-wiki.diddipoeler.de/index.php?title=SM-Joomla-Starthilfen:Joomla_Plugins](url) geleert, da sie auch mit Schrott vollgemüllt war und die relevanten Daten verschwunden waren.
Der Punkt **Joomla 2.5 Hilfe für Entwickler** muss sowieso umbenannt werden.
**Plugins** muss daher neu gefüült werden.
