### ISSUE TITLE
Transfer of JSM to your own org at Transifex

### ISSUE THREAD

**Issue by ot2sen** [diddipoeler/sportsmanagement#806]
Hello Diddi,

As we notified last month we are ending the OpenTranslators effort and would like to transfer back the projects to the original developers.
Could you please check and accept the transfer request made to your organisation 'Joomla Sports Management' in your transifex user account? Thanks

Ole - OpenTranslators

**Comment by sigal** [comment]
Thank you. Can now be closed

**Comment by ot2sen** [comment]
Thanks, and thank you for having been part of the OpenTranslators journey. Appreciated :)
