### ISSUE TITLE
Spielzeit im Spiel wird falsch gerechnet

### ISSUE THREAD

**Issue by Europekicker** [diddipoeler/sportsmanagement#810]
Gabe gerade gesehen wenn ich eine Zeit der erzielten tor eingebe wird die zeit der gesammtspielzeit in der Statistik des Spielers falsch angezeigt.
bei tor 13 min und tor 84 wird als gesammt spielzeit im Spiel der wert als 7 gezeigt.
was sich dann übergreifend auf alle statistiken des Spielers auswirkt.
<img width="880" alt="falsche zeit-1" src="https://user-images.githubusercontent.com/14942144/46146119-3feed380-c262-11e8-91d9-0edf3c2c8c47.png">
<img width="1117" alt="flasche zeit-2" src="https://user-images.githubusercontent.com/14942144/46146121-42512d80-c262-11e8-9084-134c69f17dc4.png">

**Comment by sigal** [comment]
So kann ich das nicht bestätigen. Habe einen Spieler in einem Projekt der 3 Tore im Spiel gescort hat, und die Berechnung stimmt ganz genau. Auch mit 1, 2 Toren und Auswechslung stimmen die Berechnungen.
Möglicherweise falsche Einstellungen?

![berechnung_tore_spielzeit](https://user-images.githubusercontent.com/5115688/46152082-906d2d80-c270-11e8-8f1c-aae66f70ba05.jpg)

**Live hier zu sehen:**

https://www.esv-knittelfeld.at/mannschaften/kampfmannschaft/ergebnisse/player/0/0/3775:st-unterliga-nord-b-2018-19/3690:st-lorenzen-kn/853:michael-vollmann.html

**Comment by svdoldie** [comment]
@Europekicker: Hast du im Temlate "overall" bei Personendaten Ereignisse für Spielzeitverkürzung markiert?
Wenn nicht, mal eins oder mehrere markieren und speichern.

**Comment by Europekicker** [comment]
@svdoldie . Super das war es,aber sollte nicht so kompliziert sein.

**Comment by svdoldie** [comment]
Freut mich das es geklappt hat :-) 
Vielleicht könntest du dafür einen Artikel im Wiki schreiben,
dann haben andere auch etwas davon ;-)

**Comment by svdoldie** [comment]
kann wohl geschlossen werden ;-)

**Comment by diddipoeler** [comment]
Wurde der Artikel denn schon im Wiki verfasst ?

**Comment by svdoldie** [comment]
nee, bisher nicht. Aber der Fehler ist beseitigt 👍
