### ISSUE TITLE
Spielfeldpositionen error 0 Call to a member function set() on null 

### ISSUE THREAD

**Issue by Europekicker** [diddipoeler/sportsmanagement#813]
wollte eben neue Spielfeldpositionen anlegen jedoch scheitert es an diesem fehler

Es ist ein Fehler aufgetreten!
0 Call to a member function set() on null 

administrator/index.php?option=com_sportsmanagement&view=rosterposition&addposition=HOME_POS&layout=edit

sowohl heim als auch auswärts beim anlegen das gleiche, mein logs auf dem server sagen nix aus

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Europekicker** [comment]
Funktioniert wieder
