### ISSUE TITLE
Vereinsinfo bearbeiten im Frontend (erzeug Loop)

### ISSUE THREAD

**Issue by Europekicker** [diddipoeler/sportsmanagement#815]
Wenn ich im frontend einen Verein bearbeite,

**(index.php?option=com_sportsmanagement&view=editclub&cfg_which_database)**

und die daten nicht abspeicher sondern auf abbruch gehe ensteht eine endlosschleife.
Das gleiche passiert bei speichern&schliessen

normal speichern funktioniert ohne probleme.

**Comment by diddipoeler** [comment]
Bei mir funktioniert alles !

**Comment by Europekicker** [comment]
bei besteht der fehler weiter habe auch php 5.6 mal ausprobiert aber egal welches stelle ich im frontend bearneiten kann spieler oder team .... erzeugt bei abrechen die schleife.

in meinen logs habe ich das hier gefunden
2018/10/01 08:50:25 [error] 4047#0: *1350127 open() "/var/www/vhosts/webseite.de/httpdocs/components/com_sportsmanagement/assets/js/tooltipscript.js" failed (2: No such file or directory), client: 95.91.203.73, server: webseite.de, request: "GET /components/com_sportsmanagement/assets/js/tooltipscript.js HTTP/1.1", host: "www.webseite.de", referrer: "http://www.webseite.de/index.php?option=com_sportsmanagement&view=matchreport&cfg_which_database=0&s=1&p=2:kreisliga-b-warndt&mid=55:sv-nassweiler-2_sv-klarenthal-jugend-2&Itemid=113"

**Comment by diddipoeler** [comment]
Der Log-Fehler wurde bereinigt.

**Comment by teddyfresco** [comment]
I experience this with last version, on Joomla 3.8.12 (php 7.2.6 and previous versions).
Same problem on other frontend bearbeitung pages:
"die daten nicht abspeicher sondern auf abbruch gehe ensteht eine endlosschleife.
Das gleiche passiert bei speichern&schliessen"
Frontend results bearbeitung icon still does only refresh page

**Comment by diddipoeler** [comment]
Tritt der Fehler nur in der PHP Version 7.2 auf ?
Oder auch bei PHP Version 7.0 oder/und 7.1 ?

**Comment by teddyfresco** [comment]
For me every php version, can confirm it's there on 5.6 as well

**Comment by Europekicker** [comment]
Habe php 5.6, 7.1 ,7.2 probiert überall gleich 
Server läuft mit nginx ohne apache2

**Comment by diddipoeler** [comment]
Ich kann das einfach nicht nachvollziehen.
Auf der Seite http://joomla30.diddipoeler.de/index.php läuft JSM mit Joomla 3 und PHP 7.1.
Auch auf meiner Homepage habe ich diesen Fehler nicht.

**Comment by teddyfresco** [comment]
I could give you access to my testbed online if you want/have time...in case what email should I send it to? would you need ftp access as well?

**Comment by sigal** [comment]
Habe das auch getestet und muss mich @Europekicker, als auch @teddyfresco anschließen.
Abrechen, Bzw. Speichern & Schließen enden in einer Endlosschleife,
Speichern übernimmt keine getätigten Einträge.

Damit wir nicht von verschiedenen Dingen sprechen: FE - Edit Verein (Club)
Joomla 3.8.12
PHP 7.0.32
Letzte JSM Version aus dem GitHub

![fe-edit-club](https://user-images.githubusercontent.com/5115688/46542615-23d0df00-c8bf-11e8-8c55-6a3fa3ebecb8.jpg)

**Comment by diddipoeler** [comment]
Kann ich nicht nachvollziehen.
@sigal melde dich mal bitte auf der Seite http://joomla30.diddipoeler.de/ an.
Username und Passwort = stony
Dann änder mal bitte einen Verein.
Da wirst Du keine Endlosschleife sehen.

**Comment by teddyfresco** [comment]
Hi Diddi, I've just tested what you asked above, it behaves the same in Firefox and Chrome.
I tried with this club
http://joomla30.diddipoeler.de/index.php/test-tabelle/teaminfo/0/0/2:fusionsliga-17-18/1:sv-ofenerdiek/1:sv-ofenerdiek
You're right, no Endlosschleife. But I can't save anything using save and close.
And I see this notice on the popup window:

Notice: Undefined property: sportsmanagementTableProjectteam::$firstname in /www/htdocs/w0086dfc/joomla30/components/com_sportsmanagement/views/editprojectteam/tmpl/default.php on line 51
Notice: Undefined property: sportsmanagementTableProjectteam::$lastname in /www/htdocs/w0086dfc/joomla30/components/com_sportsmanagement/views/editprojectteam/tmpl/default.php on line 51
Daten für die Person [ - ]

If I hit just "save" I get redirected to this person's edit page:
Daten für die Person [ Buelent - Yildiz ] 

PS
I suppose you already know but if I click on tabs below (Extra felder, erweitert...), they disappear

**Comment by sigal** [comment]
Ist schon richtg @diddipoeler, dass es auf  Deiner Seite keine Endlosschleife gibt.
Habe dies jetzt auch auf anderen Seiten von mir nachvollzogen.
Warum dies auf einzelnen Seiten auftritt hab ich noch nicht eruiert.

Fakt bleibt, wie @teddyfresco im obigen Posting beschrieben hat, dass der Button Speichern nur begrenzt Wirkung zeigt - es werden nur einzelne Felder gespeichert (Datum z.B. wird nicht übernommen)
Speichern & Schließen ist wirkungslos - auch einzelne Felder (z.B. Präsident) werden nicht gespeichert.

Zusammendfassend kann ich noch folgenden Senf abgeben. Die Fehlermeldungen bei der Bearbeitung im FE ist auch  abhängig davon, von welcher view der Verein aufgerufen wird - (Die Anzeige vom Menü Clubinfo enthält keine Fehlermeldung, speichert aber auch keine Daten. )

Tabellen und Results views - Aufruf der Vereine mittels jQuery Auswahl zeigen andere Fehlermeldungen.

Auf einer Seite die über https läuft, wird beim Klick auf Speichern eine leere Form gezeigt. Klickt man auf Abbrechen, ist man wieder auf der Seite "Vereinsinformationen" des Verein.

Sorry, momentan verlier ich den Überblick.

**Comment by sigal** [comment]
Jetzt schon!!!

**Comment by svdoldie** [comment]
Ich habe das gleiche Verhalten mit den Buttons auch beim bearbeiten von Personen und Teams im Frontend

**Comment by diddipoeler** [comment]
Bitte noch einmal testen !

**Comment by svdoldie** [comment]
Den Loop gibt es nicht mehr, allerdings werden auch keine Änderungen gespeichert.
Das gilt für das Bearbeiten von Verein und Team. Bei Personen werden die Änderungen gespeichert

**Comment by diddipoeler** [comment]
Bitte noch einmal testen !

**Comment by svdoldie** [comment]
Die Änderungen der Vereinsinfos werden weiterhin nicht gespeichert.
Bei den Teaminfos erscheint erst gar kein Formular für irgendwelche Änderungen

**Comment by diddipoeler** [comment]
Bitte noch einmal testen !

**Comment by svdoldie** [comment]
Jetzt erscheint das Formular wieder, aber auch bei den Teaminfos werden keine Änderungen gespeichert

**Comment by diddipoeler** [comment]
Bitte noch einmal testen !

**Comment by svdoldie** [comment]
Vereinsinfos und Teaminfos lassen sich jetzt ändern,
bei den Personendaten führt der Link beim Notizblocksymbol zum Formular der Teaminfos

**Comment by diddipoeler** [comment]
Bitte noch einmal testen !

**Comment by svdoldie** [comment]
Jetzt funktioniert alles :-)
