### ISSUE TITLE
Spieler - Position Zuordnung der Startaufstellung (falsche Position)

### ISSUE THREAD

**Issue by Europekicker** [diddipoeler/sportsmanagement#820]
Habe probleme mit der zurordnung der Spieler auf dem Spielfeld.
Die Positionen stehen nicht in der relation der eingabe in der maske.
Stürmer steht zb in de Abwehr obwohl Sturm gewählt  in der Maske , für das Spiel ist die korrekte 
Aufstellung ausgewählt.
**(fehler einstellung oder bug?)**

**Comment by svdoldie** [comment]
Da musst du im Backend die Koordinaten bei den Spielfeldpositionen anpassen.
Ist ein bisschen Frickelarbeit, aber hinzubekommen.

**Comment by diddipoeler** [comment]
Die Positionen  müssen in der richtigen Reihenfolge sortiert sein.

**Comment by Europekicker** [comment]
danke @diddipoeler da war es könnte mann auch selbsrt drauf kommen.
