### ISSUE TITLE
Backend. Spielbericht Statistik

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#822]
**Describe the bug**
Add Statistic to a position but when I try to add a statistic to a game the screen is white.

**To Reproduce**
Assign Statistik to position
Backend: Projekt - Spieltage - Spiele bearbeiten.
add Statistik

**Expected behavior**
Enter Statistic for the choosen game.

**Screenshots**
![image](https://user-images.githubusercontent.com/9608697/47018235-9f9b1900-d154-11e8-8ec2-c5f3171f1c9e.png)
![image](https://user-images.githubusercontent.com/9608697/47018251-a9248100-d154-11e8-9472-327a943c1c52.png)

**Desktop (please complete the following information):**
 - OS: WIndows
 - Browser Chrome
 - Version  69.0.3497.100

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Moin, gestern konnte ich noch Eintragungen machen.
Heute geht das Fenster auf aber es sind keine Felder zum eintragen mehr da.

**Comment by PhantoSGE** [comment]
Im Frontend erscheinen die Namen und die Statistik. Ich kann allerdings die Person nicht wechseln.
Wenn ich eine Eingabe speichern möchte erscheint folgende Fehlermeldung.
1164 - Table 'rmpl_.#__sportsmanagement' doesn't exist

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Backend funktioniert die Eingabe mit einer Fehlermeldung beim öffnen des Fensters.
Aber die Statisitk lässt sich eingeben und speichern.
![image](https://user-images.githubusercontent.com/9608697/52717128-a6218c00-2fa0-11e9-91e4-4eb2928e9067.png)

Im Frontend kann ich den Tab für das 2. Team nicht auswählen.

In der Ergebnisansicht erscheint folgende Fehlermeldung:

Notice: Undefined offset: 7 in /var/www/vhosts/rhein-main-player-league.de/httpdocs/components/com_sportsmanagement/helpers/html.php on line 478

Im Ereignismodul folgendes.
Deprecated: Non-static method modSMEventsrankingHelper::printName() should not be called statically in /var/www/vhosts/rhein-main-player-league.de/httpdocs/modules/mod_sportsmanagement_eventsranking/tmpl/default.php on line 137

Bsp:
https://www.rhein-main-player-league.de/ligen/landesliga/ergebnisse-ll

Gruß
Sven

**Comment by PhantoSGE** [comment]
Im Matchreport ist folgende Fehlermeldung

Notice: Undefined variable: search in /var/www/vhosts/rhein-main-player-league.de/httpdocs/components/com_sportsmanagement/models/matchreport.php on line 219

**Comment by diddipoeler** [comment]
Fehlermeldung bereinigt.

**Comment by diddipoeler** [comment]
Bitte noch einmal das Modul: mod_sportsmanagement_eventsranking testen.

**Comment by PhantoSGE** [comment]
Backend Fehlermeldung ist weg.

Modul:
Deprecated: Non-static method modSMEventsrankingHelper::getData() should not be called statically in /var/www/vhosts/rhein-main-player-league.de/httpdocs/modules/mod_sportsmanagement_eventsranking/mod_sportsmanagement_eventsranking.php on line 75

**Comment by diddipoeler** [comment]
Bitte noch einmal das Modul: mod_sportsmanagement_eventsranking testen.

**Comment by PhantoSGE** [comment]
Die Fehlermeldung ist immernoch vorhanden mit verschiedenen Line angaben

**Comment by PhantoSGE** [comment]
Während dem Speichern einer Statistik erscheint kurz folgende Meldung während das Fenster sich schließt.

![image](https://user-images.githubusercontent.com/9608697/52728485-a8dbab80-2fb7-11e9-8c15-3c3931a832c5.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal das Modul: mod_sportsmanagement_eventsranking testen.

**Comment by PhantoSGE** [comment]
Das Modul sieht wieder iO aus

**Comment by diddipoeler** [comment]
Bitte einmal mit Vorsicht testen !

**Comment by diddipoeler** [comment]
Bitte einmal mit Vorsicht testen !

**Comment by PhantoSGE** [comment]
Backend:
Eingaben ohne Probleme.
Fehlermeldung (Bei eingeschalteter Fehlermeldung Maximum) noch vorhanden
![image](https://user-images.githubusercontent.com/9608697/52776513-07e60280-3042-11e9-9acb-d90cb6451b37.png)


Frontend Statisitk eingabe.
In den Tabs steht "home" & "away".
Beim Speichern einer Statisitk folgende Fehlermeldung
![image](https://user-images.githubusercontent.com/9608697/52776571-3237c000-3042-11e9-896b-6cb052db2d16.png)

Frontend Eingabe Ereignisse ist der Spieler nicht vorhanden.
![image](https://user-images.githubusercontent.com/9608697/52776761-935f9380-3042-11e9-9d4f-d8f4f5a43ba2.png)


(Backend Ansicht)
![image](https://user-images.githubusercontent.com/9608697/52776736-85aa0e00-3042-11e9-9936-1a0069805268.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Backend Fehlermeldung wie gehabt.

Frontend Statistik Fehlermeldung beim speichern.
![image](https://user-images.githubusercontent.com/9608697/52784418-5650cc80-3055-11e9-9035-d9bc6d03a65a.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Die Fehlermeldung im Backend erscheint immernoch, aber scheint keine Auswirkung zu haben.

Frontend Statistik funktioniert :+1: 

Bei den Ereignissen noch keine Verändernung 

Gruß
Sven

**Comment by diddipoeler** [comment]
Welche Fehlermeldung im Backend und wo ?

**Comment by PhantoSGE** [comment]
In dem modal Fenster nach dem speichern. 

https://user-images.githubusercontent.com/9608697/52776513-07e60280-3042-11e9-9acb-d90cb6451b37.png

**Comment by sigal** [comment]
Schon Update gemacht? Sollte doch so aussehen: 
![save_stats](https://user-images.githubusercontent.com/5115688

/52819347-62ff1000-30a9-11e9-88c8-217bec98d31f.jpg)

**Comment by diddipoeler** [comment]
> 
> 
> In dem modal Fenster nach dem speichern.
> 
> https://user-images.githubusercontent.com/9608697/52776513-07e60280-3042-11e9-9acb-d90cb6451b37.png

Ich habe mal Maximum eingestellt.
Da kommt kein Fehler.

**Comment by PhantoSGE** [comment]
Die Fehlermeldung erscheint nach dem Speichern der Statistik.

![image](https://user-images.githubusercontent.com/9608697/52844372-b2265e80-3104-11e9-99f1-fde8ad79a32e.png)

**Comment by PhantoSGE** [comment]
Aber nur auf Maximum

**Comment by diddipoeler** [comment]
Ich habe das jetzt 15 mal auf deiner Seite ausprobiert.
Ich sehe das nicht !

**Comment by PhantoSGE** [comment]
Interessant. 
Ich denke das Issue kann dann geschlossen werden, Statistik Eingabe funktioniert. FE & BE 

Vielen Danke nochmal für die Arbeit :+1:
