### ISSUE TITLE
Postionen im Spielbericht und aufstelleung

### ISSUE THREAD

**Issue by Europekicker** [diddipoeler/sportsmanagement#824]
Wo kann ich diesen wert ändern das es so ausieht
Torwart
Verteidiger
Mittelfeldspieler
Stürmer

bei mir ist es vertauscht 
![positionen](https://user-images.githubusercontent.com/14942144/47613969-57ef8800-da98-11e8-8036-e5b894983d6c.jpg)

**Comment by svdoldie** [comment]
Du musst die Position in den Stammdaten sortieren
