### ISSUE TITLE
Ergebnis bearbeiten im Frontend - keine Spiele

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#829]
**Describe the bug**
Bei dem Versuch Ergebnisse im Frontend einzugeben werden keine Spiele angezeigt

**To Reproduce**
1. Menü Ergebnisanzeige
2. Button Ergebnisse eingeben/ändern
3. Es werden keine Spiele angezeigt

**Expected behavior**
Spiele des ausgewählten Spieltages zum eingeben der Ergebnisse

**Screenshots**
![image](https://user-images.githubusercontent.com/9608697/48825808-d45c4a80-ed68-11e8-8181-386ec41b9f0c.png)

![image](https://user-images.githubusercontent.com/9608697/48825784-c1e21100-ed68-11e8-86ea-f3470adcb0cb.png)

**Desktop (please complete the following information):**
 - OS: Windows 7/10
 - Browser: Chrome
 - Version 70.0.3538.102 

Grüße

**Comment by JackomoLXX** [comment]
Bei mir genau das gleiche seit update auf 1.0.67.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by diddipoeler** [comment]
> Bei mir genau das gleiche seit update auf 1.0.67.

Und, wie bist Du auf die Komponente aufmerksam geworden ?

**Comment by JackomoLXX** [comment]
Sorry, stehe gerade auf dem Schlauch. Verstehe die Frage nicht. 
Meinst du wie ich auf JSM gekommen bin?
Oder wie ich auf den Fehler gekommen bin?

**Comment by diddipoeler** [comment]
Genau.
Wie bist Du auf JSM gekommen ?

**Comment by JackomoLXX** [comment]
Hatte schon Joomleague 2, und bin mit Beginn dieser Saison auf JSM aus neuigier gewechselt.

**Comment by diddipoeler** [comment]
Und wie sieht das Gesamtergebnis von JSM aus Deiner Sicht aus ?

**Comment by JackomoLXX** [comment]
Ich finde es Top.

**Comment by diddipoeler** [comment]
Vielleicht kannst Du mir bitte noch sagen, auf welcher Seite es eingesetzt wird ?

**Comment by JackomoLXX** [comment]
Wird auf keiner Seite im klassischen Sinne eingesetzt. Habe einen PI mit Joomla für mich zum eperimentieren, auf dem ich mit ein paar Freunden und Famileinmitgliedern die BuLi tippe.
