### ISSUE TITLE
Update Error Message

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#830]
**Describe the bug**

Warnung
Copy file failed

Warning: Illegal string offset 'Komponente:' in /var/www/vhosts/rhein-main-player-league.de/httpdocs/administrator/components/com_sportsmanagement/models/githubinstall.php on line 83

Warning: Illegal string offset 'Komponente:' in /var/www/vhosts/rhein-main-player-league.de/httpdocs/administrator/components/com_sportsmanagement/models/githubinstall.php on line 136

Warning: Illegal string offset 'Module:' in /var/www/vhosts/rhein-main-player-league.de/httpdocs/administrator/components/com_sportsmanagement/models/githubinstall.php on line 149

Warning: Invalid argument supplied for foreach() in /var/www/vhosts/rhein-main-player-league.de/httpdocs/administrator/components/com_sportsmanagement/views/githubinstall/tmpl/default.php on line 64

**To Reproduce**
1. JSM
2. JSM GitHub update

**Screenshots**
![image](https://user-images.githubusercontent.com/9608697/49383345-cddeb300-f718-11e8-821f-df971e800206.png)

**Comment by sigal** [comment]
Dieses Verhalten konnte ich auf keiner meiner Seiten feststellen. Auch nicht auf einer Joomla4-Alpha6 nicht.

Welche PHP-Version ist im Einsatz?
Wann wurde **vor** dem letzten Versuch aktualisiert?

Nachtrag: Scheint lt. Bild so, dass die Datei aus dem GitHub nicht kopiert werden konnte. Nochmals versuchen?

**Comment by diddipoeler** [comment]
Den Fehler kann ich nicht nachvollziehen !

**Comment by PhantoSGE** [comment]
Der Fehler tritt mit PHP 7.2.13 & 7.1.25 auf.
Bei PHP 7.0.33 & 5.6.39 erscheint folgendes.
![image](https://user-images.githubusercontent.com/9608697/49862154-d2ccf200-fdfd-11e8-9d6b-28780b9e96c4.png)

**Comment by sigal** [comment]
Wie diddi schon sagt, ist der Fehler so nicht nachvollziehbar.
Weder mit PHP 7.1.x , 7.2.13.
Habe lokal auch schon PHP 7.3 am laufen. Auch dort ist der Fehler nicht vorhanden.

Auf welchen Server läüft deine Seite?
Eine Einsicht auf die phpinfo() wäre vorteilhaft.
Stimmt der tmp-Pfad der Joomla Installation.
Ist der PHP-tmp Ordner des Server gesetzt.

Mal den tmp Ordner von Joomla leeren. Unterordner inklusive. Dann nochmals das GitHub Update in JSM ausführen. Prüfen, ob jetzt im tmp Ordner die Dateien **master.zip, sportsmanagement.xml, sowie der Ordner sportsmanagement-master** erstellt wurden.

Sind diese vorhanden, gibt es keinen Schreibzugriff auf die Joomla Ordner. (Copy file failed)

Also alles mal in Ruhe prüfen.

**Comment by PhantoSGE** [comment]
Moin sigal,

Auf welchen Server läüft deine Seite? _server4you_
Eine Einsicht auf die phpinfo() wäre vorteilhaft.  http://www.rhein-main-player-league.de/phpinfo.php

Ist der PHP-tmp Ordner des Server gesetzt. 
![image](https://user-images.githubusercontent.com/9608697/49937257-7be71b80-fed6-11e8-8d8f-912c7542e113.png)

Stimmt der tmp-Pfad der Joomla Installation. 
![image](https://user-images.githubusercontent.com/9608697/49937197-4a6e5000-fed6-11e8-89f5-dd441e794c73.png)

tmp Ordner habe ich geleert und Github Update nochmal ausgeführt. Gleiches Ergebnis :-(

Gruß

**Comment by sigal** [comment]
Hallo PhantoSGE,

habe mir das angesehen. 

Das Problem scheint entweder ein Schreibproblem in der Ordnerstruktur von Joomla (Schreibrechte rechte Joomla -> System -> Systeminformationen Tab Verzeichnisrechte prüfen) , oder Apache hat keine Schreibrechte in httpdocs Ordnern (Benutzerrechte prüfen).

Die Fehlermeldung deutet eindeutig darauf hin. Die Dateien in /tmp/sportsmanagement-master können von Apache nicht in ihre angestammten Verzeichnisse kopiert werden. (Warnung Copy file failed).

Was mir noch aufgefallen ist:
PHP hat keinen Schreibzugriff auf den session.save_path - Dieser muß für jede Domain einzeln, oder global gesetzt werden. Serververwaltung Domain -> PHP-Einstellungen -> open_basedir `{WEBSPACEROOT}{/}{:}{TMP}{/}{:}{/}var{/}lib{/}php{/}sessions{/}`

Und wenn du selber Serveradministrator bist, sollte das upload_tmp_dir in der eigenen php.ini gesetzt werden.

Überprüfen kann man das auch in Joomla -> Erweiterungen -> Warnungen 

Zuletzt kannst ja mal unter Joomla -> Erweiterungen -> Installieren -> Aus Verzeichnis installieren nach tmp/sportsmanagement-master/ einfügen und Überprüfen und installieren klicken.

Für deinen Server: `/var/www/vhosts/rhein-main-player-league.de/httpdocs/tmp/sportsmanagement-master/`

Funzt das nicht ist, bestehen die von mir beschriebenen Probleme am Server.

JSM ist dafür nicht verantwortlich.

PS: Die phpinfo wieder löschen, oder nicht mehr öffentlich zugänglich machen!

**Comment by PhantoSGE** [comment]
1000 das du dir das so ausführlich angeschaut hast.
Ich werde mir deine angesprochenen Punkte mal genauer anschauen.

Vielen Dank nochmal

**Comment by PhantoSGE** [comment]
Hallo sigal,

ich habe jetzt verschiedene Einstellungen probiert und getestet.
Leider habe ich bei JSM keinen Erfolg. Andere Erweiterungen lassen sich ohne Probleme aktualisieren und installieren.
Könnt du/ihr mir evtl. eine Hinweis geben wo ich eine Lösung für das Problem erhalten kann?

> Das Problem scheint entweder ein Schreibproblem in der Ordnerstruktur von Joomla (Schreibrechte Joomla -> System -> Systeminformationen Tab Verzeichnisrechte prüfen) , oder Apache hat keine Schreibrechte in httpdocs Ordnern (Benutzerrechte prüfen).

**_Alle Beschreibbar außer configuration.php_**

> Die Fehlermeldung deutet eindeutig darauf hin. Die Dateien in /tmp/sportsmanagement-master können von Apache nicht in ihre angestammten Verzeichnisse kopiert werden. (Warnung Copy file failed).

**_Dieses Problem konnte ich nicht beheben. Die Fehlermeldung erscheint immernoch. Die Rechte sind Plesk typisch vergeben (psaserv & psacln) www-run ist Mitglied der Grp_**

> Was mir noch aufgefallen ist:
> PHP hat keinen Schreibzugriff auf den session.save_path - Dieser muß für jede Domain einzeln, oder global gesetzt werden. Serververwaltung Domain -> PHP-Einstellungen -> open_basedir {WEBSPACEROOT}{/}{:}{TMP}{/}{:}{/}var{/}lib{/}php{/}sessions{/}

**_ist auf Standard: {WEBSPACEROOT}{/}{:}{TMP}. Habe es aber auch schon mit {WEBSPACEROOT}{/}{:}{TMP}{/}{:}{/}var{/}lib{/}php5{/}sessions{/} probiert._** 

> Und wenn du selber Serveradministrator bist, sollte das upload_tmp_dir in der eigenen php.ini gesetzt werden.



> Überprüfen kann man das auch in Joomla -> Erweiterungen -> Warnungen

**_ist in der eigenen php.ini gesetzt allerdings mit Fehlermeldung_**

![image](https://user-images.githubusercontent.com/9608697/50771491-1561dd00-128b-11e9-9625-7a99f7496441.png)


Gruß
Phanto

**Comment by sigal** [comment]
Grundsätzlich noch eine Frage.
Welcher Serversoftware wird verwendet? Debian, Ubuntu, Centos

Es macht mich stutzig, da der session.save_path auf `/var/lib**/php5**/sessions` lautet. Diesen gibt es normalerweise nicht auf einen Debian-, oder Ubuntuserver.
Mal per ssh nachprüfen, ob es diesen Ordner gibt. Standard: `/var/lib/php/sessions`

> ist auf Standard: {WEBSPACEROOT}{/}{:}{TMP}. Habe es aber auch schon mit {WEBSPACEROOT}{/}{:}{TMP}{/}{:}{/}var{/}lib{/}php5{/}sessions{/} probiert.

Schon mit `{WEBSPACEROOT}{/}{:}{TMP}{/}{:}{/}var{/}lib{/}php{/}sessions{/}` probiert?

> ist in der eigenen php.ini gesetzt allerdings mit Fehlermeldung

Gibt es den Ordner `/var/www/vhosts/rhein-main-player-league.de/tmp` ??? Und wenn ja, mit Schreibrechten und den richtigen Benutzerrechten? Wenn das Verzeichnung unter ssh mit root-Rechten angelegt wurde, funktioniert das nicht!!!

**Comment by PhantoSGE** [comment]
OS ist ‪Debian 8.11. 
Es existiert nur der Ordner php5. in var/lib/
![image](https://user-images.githubusercontent.com/9608697/50818448-44c62780-1327-11e9-86e2-b2187405c834.png)

Den Ordner /var/www/vhosts/rhein-main-player-league.de/tmp gibt es so wirklich nicht. Irgendwann sieht man den Wald nicht mehr vor lauter Bäumen. Habe das jetzt mal geändert und die Fehlermeldung ist weg. Sorry dass ich das übersehen habe.

Gruß
Phanto

**Comment by sigal** [comment]
Asche auf mein Haupt. Den Ordner /var/lib/php5 gibt es tatsächlich in Debian8.

Da ich selber auch einen Server betreibe mit Plesk als Verwaltung, kann ich mir diesen Fehler nicht erklären. Alle Domains wo JSM läüft, sind ohne dieser Fehlermeldung, egal welche PHP-Version läuft.

In Plesk hat man doch die Möglichkeit, eigene Domainabhängige Konfigurationsanweisungen für PHP zu erstellen. Diese am Besten als admin

![plesk-php](https://user-images.githubusercontent.com/5115688/50901684-39532900-1419-11e9-8d34-0818d6ba892d.jpg)

Ich habe für eine meiner Domains obige Einstellungen getroffen.

Für Deinen Server (Domain): `upload_tmp_dir=/var/www/vhosts/rhein-main-player-league.de/httpdocs/tmp`

Damit erübrigt sich auch die Bearbeitung der php.ini

Bei mir schaut die phpinfo so aus:

![php--info](https://user-images.githubusercontent.com/5115688/50902049-2725ba80-141a-11e9-9e8d-e9bec4b8f231.jpg)

Zum Abschluß betreffend der Fehlermeldung. Bei einem virtuellen Server mit ISPConfig als Hosting-Panel hatte ich das auch einmal. Nach überprüfen der Dateien von JSM hab ich festgestellt, das alle Dateien am Stand der Aktualisierungszeit waren. Nicht zu verwechseln mit den Ordnern. Vorhandene werden nicht neu angelegt.
