### ISSUE TITLE
Projektschiedsrichter werden nicht angezeigt

### ISSUE THREAD

**Issue by tdittmann** [diddipoeler/sportsmanagement#833]
**Describe the bug**
Wenn man in einem Projekt die Spielleiter anzeigen lassen möchte, bleibt die Liste immer leer.

**To Reproduce**
Projekt auswählen und auf "Spielleiter" klicken (es muss natürlich ein Spielleiter vorhanden sein).

**Expected behavior**
Alle Projektschiedsrichter sollen angezeigt werden

Nach kurzer Analyse ergab sich ein kleiner Fehler in folgender Datei: admin/models/projectreferees.php Zeile 145. Dort sollte statt
`$query->join('INNER','#__sportsmanagement_project_referee AS pref on pref.person_id = tp.id');`

folgendes stehen:
`$query->join('INNER', '#__sportsmanagement_project_referee AS pref on pref.person_id = tp.person_id');`

Der Join sollte über die PersonenID gehen und nicht über die Assignment-ID. Kann den Fehler jemand reproduzieren?

**Comment by diddipoeler** [comment]
Bei mir werden Sie angezeigt:
http://www.fussballineuropa.de/index.php/component/sportsmanagement/referees/0/0/81934:1-bundesliga-2018-19?division=0&r=0

**Comment by tdittmann** [comment]
Auch im Backend?

**Comment by svdoldie** [comment]
Bei mir werden die Schiedsrichter sowohl im Backend, als auch im Frontend angezeigt

**Comment by tdittmann** [comment]
Ok, danke 👍 Dann muss ich bei mir mal schauen ob ich nicht irgendwie einen Datenschiefstand oder ähnliches habe. Solange schließe ich das Ticket hier ;)

**Comment by tdittmann** [comment]
Habe es gerade nochmal getestet: war wohl bei mir irgendwas falsch 👍
