### ISSUE TITLE
DFBnet Import mit neuen Exporten nicht möglich.

### ISSUE THREAD

**Issue by Sumpfeimer** [diddipoeler/sportsmanagement#834]
Wäherend der alte Export eines Spielplans aus dem DFBnet funktioniert bekomme ich bei dem neuen Import die Fehlermeldung:

Falsches Dateiformat

...\administrator\components\com_sportsmanagement\models\jlxmlimport.php on line 206

Notice: Undefined variable: xmlImportTitle in ...\administrator\components\com_sportsmanagement\views\jlxmlimports\tmpl\form.php on line 164

Hier die beiden Dateien
https://www.file-upload.net/download-13453550/spielplan-alt.csv.html
https://www.file-upload.net/download-13453549/spielplan-neu.csv.html

Soweit ich feststellen konnte ist der "Alte" Export -> Unicode (UTF-16) der "Neue" -> Unicode (UTF-8)

Speicher ich den "Neuen" über ein Tabellenkalkulationsprogramm als CSV mit Unicode (UTF-16) ab funktioniert auch der Import.

Leider habe ich nur diesen einen Alten Export kann es also leider nicht weitergehend reproduzieren. Aber für mich sieht es so aus als wenn der DFB mal wieder etwas an seinem Export geändert hat.

Vielleicht kann das jemand mit älteren Exporten mal nachvollziehen.

**Comment by diddipoeler** [comment]
Bitte mal die beiden Dateien an folgende EMAIL senden:
diddipoeler@arcor.de

**Comment by Sumpfeimer** [comment]
Weiterer Fehler beim Import statt der Anstoßzeit wird die Uhrzeit importiert wann das Spiel aus DFBnet exportiert wurde. 

Es wird die 2.Spalte "Uhrzeit" als Anstoßzeit genommen es muss aber die 17.Spalte "Uhrzeit_17" genommen werden.

**Comment by diddipoeler** [comment]
Bitte einmal die Dateien zusenden.

**Comment by diddipoeler** [comment]
Ich benötige immer noch die Dateien.

**Comment by diddipoeler** [comment]
Bitte einmal die alte Datei zusenden.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Sumpfeimer** [comment]
Scheint behoben.Danke wieder mal Super. Mach dicht hier.

**Comment by svdoldie** [comment]
Bei mir funktioniert das nicht ganz richtig. Da stimmen die Anzahl der Spietage und Spiele nicht.
Beispiel: Der Import hat 30 Spieltage und 240 Spiele, angelegt werden aber nach import 31 Spieltage und 239 Spiele. Ich vermute den Fehler bei verlegten Spielen.

**Comment by diddipoeler** [comment]
Bitte mal die zu importierende Datei zumailen.

**Comment by svdoldie** [comment]
du hast Post :-)

**Comment by Sumpfeimer** [comment]
Stimmt gar nicht bemerkt es gibt einen Spieltag Null ohne angelegte Spiele. Verlegte Spiele tauchten bei mir aber vorher auch schon auf. Das Problem ist sicherlich wie soll die Importierroutine wissen welches Spiel verlegt ist. Dazu müsste die Routine die Spielnummern vergleichen. Tauchen die doppelt oder mehrfach auf. Ist verlegt worden. Weiß leider nicht ob das System vom DFBnet den Zusatz "verlegt auf..." im Feld **Spielstätte** anlegt oder ob das der Ansetzer da einträgt. SVOLDIE stehen die Verlegungsdaten auch bei Dir in dem Feld **Spielstätte** und zwar so:

Verlegt auf Di, 28.08.2018

**Comment by svdoldie** [comment]
Hi. Setze mal den Spielstatus im DFBnet-Export auf Aktuelle mit spielfrei und NICHT auf alle.
Das müsste besser passen

**Comment by Sumpfeimer** [comment]
> Hi. Setze mal den Spielstatus im DFBnet-Export auf Aktuelle mit spielfrei und NICHT auf alle.
Das müsste besser passen

Ah jetzt ja eine Insel
Danke

**Comment by diddipoeler** [comment]
> 
> 
> Sorry Übersehen gibt ja auch noch Datumsfelder für die Verlegungsdaten.
> 
> Bei unser Damen ist das noch krasser. JSM sagt 64 Spiele und der Export hat 97. Der Export hat aber mit verlegten Spielen 64 mit Spielort (wobei da die mit dem Verlegt auf mitgezählt sind). Im Export sind aber lauter Geisterspiele die nur einen Mannschaft haben und keinen Gegner. Die Spielnummer samt Datum gibt es aber noch einmal im Export. Da soll eine Importroutine mal ordentlich mit arbeiten.
> Datei schicke ich dir zu Diddi.

Bitte mal die Datei an diddipoeler@gmx.de zusenden !

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Die Anzahl der Spieltage stimmt jetzt.
Aber das letzte Spiel des Exports wird nicht importiert

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Perfekt 👍

**Comment by svdoldie** [comment]
kann geschlossen werden, denke ich

**Comment by Sumpfeimer** [comment]
Teste das gleich nochmal und mach sonst erstmal wieder dicht.
Danke für Eure Hilfe.

**Comment by Sumpfeimer** [comment]
8 Importe. Konnte nichts feststellen. Stimmen wohl alle. 
Super Danke. 

Mach dicht.

**Comment by svdoldie** [comment]
Nur ne kleine Frage. Ist der Import auch schon für Joomla 4 programiert?

**Comment by Sumpfeimer** [comment]
Bitte mal mit neuen Exporten testen. So wie es aussieht haben die Eumels vom DFB jetzt wieder UTF 16. Horstbirnen die.
[spielplaene.zip](https://github.com/diddipoeler/sportsmanagement/files/2922333/spielplaene.zip)

**Comment by diddipoeler** [comment]
Jetzt müsste man beide Versionen importieren können.
Ich habe für die Datei noch ein Encoding eingebaut.

**Comment by Sumpfeimer** [comment]
Vielen Dank. Super mach zu hier.
