### ISSUE TITLE
JSM - Modul Spielstätten Terminansicht funktioniert im Backend nicht richtig

### ISSUE THREAD

**Issue by Sumpfeimer** [diddipoeler/sportsmanagement#835]
Beim Aufrufen des Moduls im Modulmanager öffnet das Modul zeigt aber keine Einstellmöglichkeiten. Es erscheint eine nahezu weiße Seite mit lediglich dem Namen des Moduls und dem Feld für den Titel.

Alle Buttons und das Template des Joomla-Backends werden nicht dargestellt.

Meldung:

> Fatal error: Class 'FormField' not found in C:\xampp\htdocs\h\administrator\components\com_sportsmanagement\models\fields\playgrounds.php on line 51 

![screenshot](https://user-images.githubusercontent.com/46286363/50597206-dd335680-0ea6-11e9-9dc7-8d963f9624ff.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Sumpfeimer** [comment]
Backend funktioniert. Modul hat allerdings ein anderes Problem mit der Darstellung.
Wurde schon einmal hier beschrieben. https://github.com/diddipoeler/sportsmanagement/issues/591

1. Anscheinend hat die Einstellung im Backend des Moduls unter TAB "Erweitert" ->"Tabellendarstellung" keine Auswirkung auf die Darstellung im Frontend. Es wird immer Farblich abwechselnd dargestellt.

2. Ist die Darstellung der abwechselnden Balken nicht passend zu den eigentlichen Tabellenfeldern. (siehe https://github.com/diddipoeler/sportsmanagement/issues/591)

Ich habe es mit den beiden Standard-Templates Beez und Protostar ausprobiert immer der gleiche Versatz. 

Dieser Versatz ist mal mehr oder weniger groß. Je mehr "Anzeigemerkmale" man hinzuschaltet (z.B. Vereinslogos usw) um so schlimmer wird der Versatz.

Ursache ist meiner Ansicht nach die:

.../modules/mod_sportsmanagement_playgroundplan/css/mod_sportsmanagement_playgroundplan.css

hier steht:

> #jlplaygroundplanis0 {
	background: #445566;
	height: 120px;
}
#jlplaygroundplanis1 {
	background: #556677;
	height: 120px;
}

dieses müsste meiner Ansicht nach aber:

> #jlplaygroundplanis0 {
	background: #445566;
	height: _**auto**_;
}
#jlplaygroundplanis1 {
	background: #556677;
	height: **_auto_**;
}

heißen.

`Als Wunsch auf Dauer wäre da sicherlich noch zwei Eingabefelder im Modul für die beiden Farben die sich dort abwechseln sollen. Je nach Template ist dunkles grau nicht immer angesagt. Ich kann das auch anders lösen aber mit Sicherheit nicht jeder. ;)`



![vereinsspielplan sc rapid lubeck 3](https://user-images.githubusercontent.com/46286363/50605533-d4e91480-0ec2-11e9-9b67-b674300924a3.png)

**Comment by Sumpfeimer** [comment]
Funktioniert im Backend und im Frontend zumindest mit den beiden Standard-Templates und dem Master Bootstrap Template perfekt. Lösung bei der wechselnden Tabelle mit Farbgebung vom Template ist auch Super. Kann denke ich  geschlossen werden.
