### ISSUE TITLE
Menülinkerstellung muss zwischengespeichert werden

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#839]

**Comment by diddipoeler** [comment]
Häh ?

**Comment by svdoldie** [comment]
Will man einen Menülink anlegen, muss man nach der Angabe der Saison auf speichern klicken, 
damit die Projektauswahl gefüllt wird und anschließend wieder speichern, damit z.B. die Mannschaftauswahl gefüllt wird.
Dieses Problem scheint auf dem ersten Blick bei allen Ansichten vorhanden zu sein.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft 👍
