### ISSUE TITLE
Installationfehler?

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#841]
![erweiterungen installieren - jsmtest - administration - google chrome_006](https://user-images.githubusercontent.com/2417767/50783253-98466000-12aa-11e9-9577-b4c23510d126.png)

fehlt da etwas?

**Comment by sigal** [comment]
Sind die monierten Dateien im Ordner `images/database/com_sportsmanagement/placeholders` vorhanden.
Wenn ja, war der Server schneller als der Kopiervorgang. ;-)

**Comment by svdoldie** [comment]
Die Dateien sind alle da :+1:
