### ISSUE TITLE
mod_sportsmanagement_eventsranking.php

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#845]
Der Eintrag
use Joomla\CMS\MVC\Model\BaseDatabaseModel;
ist doppelt und erzeigt eine Fehlermeldung.
Fatal error: Cannot use Joomla\CMS\MVC\Model\BaseDatabaseModel as BaseDatabaseModel because the name is already in use in /var/www/vhosts/httpdocs/modules/mod_sportsmanagement_eventsranking/mod_sportsmanagement_eventsranking.php on line 18

![image](https://user-images.githubusercontent.com/9608697/50963111-159ceb00-14cc-11e9-8f32-166d839f21dd.png)

Gruß
Phanto

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Funktioniert
