### ISSUE TITLE
Mehrere gleiche Buttons

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#849]
In der Ansicht Schiedrichter im Projekt gibt es jeweils zwei Buttons Löschen sowie Freigeben.
![grafik](https://user-images.githubusercontent.com/2417767/51076256-6eb87a80-1696-11e9-82d1-30600eda8560.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :+1:
