### ISSUE TITLE
Darstellungsfehler im JSM Modul Matches

### ISSUE THREAD

**Issue by Sumpfeimer** [diddipoeler/sportsmanagement#851]
Die Anzeige der Spiel-Überschriften "UPCOMING", "NOW PLAYING", "LIVE ON AIR" stimmen nicht mit dem jeweiligen zeitlichen Ist-Zustand des angezeigten Spiels überein.

Es werde  z.B. Spiele aus der Vergangenheit als "LIVE ON AIR" gekennzeichnet, und Spiele die in der Zukunft liegen statt als "UPCOMING" als "NOW PLAYING".

SVOLDIE konnte dieses Verhalten bereits nachbilden,

Siehe; http://fussballineuropa.de/index.php/forum/sports-management/4669-jsm-modul-matches#13340

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Funktioniert soweit, bis auf "Live on Air", wenn das Spiel aktuell läuft

**Comment by Sumpfeimer** [comment]
> Funktioniert soweit, bis auf "Live on Air", wenn das Spiel aktuell läuft

Hast Du UPCOMING? Habe ich nicht. Da wird garnichts angezeigt. LAST MATCHES funktioniert.

Komisch ist auch das das Modul mir ein Spiel das gerade läuft als LAST MATCHES anzeigt.

**Comment by Sumpfeimer** [comment]
Noch was trotz aktivierter Anzeige für Spielort fehlt dieser.

**Comment by svdoldie** [comment]
@Sumpfeimer : bei mir wird UPCOMING angezeigt, https://svdoldie.stony-sport4u.de/

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Bei mir keine Änderung. Das Symbol für die Anzeige des Spielortes erscheint zwar, aber der Spielort nicht.
Live on Air geht auch nicht bei mir

**Comment by diddipoeler** [comment]
Bei mir siehst du den Spielort direkt auf der Homepage !

**Comment by svdoldie** [comment]
ja, habe ich schon gesehen. Bei mir geht's leider weder auf der Haupt- noch auf der Testseite

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Live on Air funktioniert jetzt bei mir

**Comment by svdoldie** [comment]
Kleiner Hinweis noch. Damit Live on Air angezeigt wird, muss ein Ergebnis für dieses Spiel gespeichert sein !!! Ob das so sein soll, kann ich nicht sagen ;-)

**Comment by diddipoeler** [comment]
Bei mir ist das nicht der Fall !

**Comment by Sumpfeimer** [comment]
Hab ein komplett neue Installation (nur Joomla 3.9.1 und JSM) aufgesetzt. UPCOMING oder LAST MATCHES usw funktioniert. Spielort leider nicht. Rein zum Verständnis sollten nicht beides in einer Darstellung gehen?

Sprich wenn ich einstelle das 6 Spiele angezeigt werden. 14 Tage bei Vergangenen Spielen einstelle und 30 Tage bei den zukünftigen. Sollen dann nicht 2 aus der Vergangenheit und 4 aus der Zukunft. Vielleicht noch ein heutiges usw. angezeigt werden. Wenn das so gemacht werden soll wie SVOLDIE das auf seiner Testseite macht jeweils ein eigenes Modul stellt sich eine Frage. Wozu gibt es z.B. den Button **"Sollen anstehende Spiele zuerst angezeigt werden?"** und warum gibt es zwei Reiter und nicht nur einen indem ein Umschalter abfragt vergangene oder zukünftige Spiele anzeigen?

**Comment by Sumpfeimer** [comment]
@diddipoeler teste mal bitte auf Fussballineuropa das Modul und switche mal mit den Buttons weiter bis zum Ende deines letzten dargestellten Spiels. Dann ist das Modul leer und auch die Buttons weg.  Besser wäre doch der Weiter-Button verschwindet beim Erreichen des letzten Spiels. oder?

Zudem zeigt das Modul beim zuerst angezeigten Spiel, links den Button "nächstes Spiel an" mit richtiger Pfeilrichtung. Schaltet wohl aber zurück und das Modul ist dann leer.

**Comment by svdoldie** [comment]
Hmm, ich kann jetzt  nicht mehr nachvollziehen wie das mit dem Ergebnis zustande kam. 
Jetzt tritt das Problem nicht mehr auf!!!

**Comment by diddipoeler** [comment]
Jetzt wird schon einmal nur das ausgewählte Team mit Richtungspfeilen angelegt.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Sumpfeimer** [comment]
@diddipoeler sieht ja schon besser aus zumindest bei Dir. Ich bekomm das irgendwie nicht zum laufen. Teste nachher nochmal weiter, muss mir das auch mal auf dem Server aufsetzen. Da mit ihr das gegebenfalls selber ansehen könnt. Danke ertsmal. Berichte später mehr.

**Comment by svdoldie** [comment]
Bei mir sind keinerlei Richtungspfeile zu sehen. Gibt's da irgendwo evtl. einen Zusammenhang mit den Plugins bzw. Jquery?

**Comment by sigal** [comment]
@diddipoeler teste mal bitte auf Fussballineuropa das Modul und klicke den Stadionlink (egal welches Stadion).

**Comment by diddipoeler** [comment]
@sigal Ah, jetzt verstanden :-)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
Ihr haltet mich ganz schön auf trap :-)

**Comment by svdoldie** [comment]
Bei mir hat sich nichts geändert. Keine Pfeile und kein Spielort

**Comment by Sumpfeimer** [comment]
Pfeile habe ich aber genauso wie bei dir SVOLDIE alles untereinander. Komplett neu Installiert. JQuery-Plugin habe ich an. Ich setze jetzt erstmal Server auf.

**Comment by Sumpfeimer** [comment]
Bei den verschiedenen Templates des Moduls werden die Kopfzeilen mal nur bei der ersten Spielpaarung angezeigt oder bei allen gibt es die Kopfzeile. Es hat nichts mit tabellenlosen Templates zu tun. Beide Tabellenlosen zeigen es anders.

**Comment by diddipoeler** [comment]
Bitte Admindaten zusenden !

**Comment by svdoldie** [comment]
Geben diese Fehlermeldungen einen Aufschluss darüber,
warum bei mir kein Spielort angezeigt wird?

Notice: Undefined property: stdClass::$pg_name in /var/www/vhosts/svdoldie.stony-sport4u.de/httpdocs/modules/mod_sportsmanagement_matches/connectors/sportsmanagement.php on line 607

Notice: Undefined property: stdClass::$pg_shortname in /var/www/vhosts/svdoldie.stony-sport4u.de/httpdocs/modules/mod_sportsmanagement_matches/connectors/sportsmanagement.php on line 608

**Comment by Sumpfeimer** [comment]
@diddipoeler scheint ja ein schwerwiegenderes Problem zu sein hab Dir den Phoca Commander installiert, falls es Dir hilft kannst Du auch FTP Zugang bekommen.

Versuch gerade noch eine Installation mit [Git-FTP](https://git-ftp.github.io/) mal schauen ob ich das zum laufen bekomme.

**Comment by diddipoeler** [comment]
> 
> 
> Geben diese Fehlermeldungen einen Aufschluss darüber,
> warum bei mir kein Spielort angezeigt wird?
> 
> Notice: Undefined property: stdClass::$pg_name in /var/www/vhosts/svdoldie.stony-sport4u.de/httpdocs/modules/mod_sportsmanagement_matches/connectors/sportsmanagement.php on line 607
> 
> Notice: Undefined property: stdClass::$pg_shortname in /var/www/vhosts/svdoldie.stony-sport4u.de/httpdocs/modules/mod_sportsmanagement_matches/connectors/sportsmanagement.php on line 608

Wo ist denn der spielort hinterlegt ?
Verein, Team oder Projektteam ?

**Comment by Sumpfeimer** [comment]
> 

> Wo ist denn der spielort hinterlegt ?
> Verein, Team oder Projektteam ?

Im Projekt > einzelnen Spiel >Spieldetails > Austragungsort

**Comment by svdoldie** [comment]
Bei allen drei. Im Quellcode wird der Spielort auch angezeigt:
<table class="table">
    <tr class="sectiontableentry2">   
      <td colspan="3">
      <span style="white-space:nowrap;"><img src="https://svdoldie.stony-sport4u.de/modules/mod_sportsmanagement_matches/assets/images/colored/house.png" alt="Spielort:" title="Spielort:" height="16" width="16" /> <a href="/index.php?option=com_sportsmanagement&amp;view=playground&amp;cfg_which_database=0&amp;s=1:18-19&amp;p=1&amp;pgid=4" title="Spielort:"><acronym title=""></acronym></a></span>  <span style="white-space:nowrap;"><img src="https://svdoldie.stony-sport4u.de/modules/mod_sportsmanagement_matches/assets/images/colored/date.png" alt="Datum" title="Datum" height="16" width="16" /> Sa, 09. Mär. 2019</span>  <span style="white-space:nowrap;"><img src="https://svdoldie.stony-sport4u.de/modules/mod_sportsmanagement_matches/assets/images/colored/time.png" alt="Beginn" title="Beginn" height="16" width="16" /> 14.00</span> 
      </td>
    </tr>

**Comment by svdoldie** [comment]
sch... Internetexplorer :-( ich kann den Code nicht einfügen, aber der Link zum Spielort ist da vorhanden
href="/index.php?option=com_sportsmanagement&amp;view=playground&amp;cfg_which_database=0&amp;s=1:18-19&amp;p=1&amp;pgid=4"

**Comment by Sumpfeimer** [comment]
> Bei allen drei. Im Quellcode wird der Spielort auch angezeigt:

Die Spielorte nützen doch aber bei der Anzeige doch nichts oder? Sollte nicht der aus dem Projekt>Spiel angezeigt werden? Was ist wenn z.B. Das Spiel von dem üblichen Rasenplatz eurer Mannschaft auf den gegnerischen Kunstrasen verlegt wird weil euer Platz nicht bespielbar ist.

**Comment by svdoldie** [comment]
Ja, so sollte es sein. Ich habe auf Diddis Frage geantwortet, weil ich dachte, es hängt evtl. mit einer fehlenden Zuordnung zusammmen

**Comment by diddipoeler** [comment]
@svdoldie mach mal bitte ein update der komponente.
dann schalte bitte die debug-anzeige im frontend ein.
dann kopiere bitte die stdClass Objecte hier rein.

**Comment by svdoldie** [comment]
Notice: Undefined property: stdClass::$pg_name in /var/www/vhosts/svdoldie.stony-sport4u.de/httpdocs/modules/mod_sportsmanagement_matches/connectors/sportsmanagement.php on line 611

Notice: Undefined property: stdClass::$pg_shortname in /var/www/vhosts/svdoldie.stony-sport4u.de/httpdocs/modules/mod_sportsmanagement_matches/connectors/sportsmanagement.php on line 612

Notice: Undefined index: resultpenalty in /var/www/vhosts/svdoldie.stony-sport4u.de/httpdocs/modules/mod_sportsmanagement_matches/tmpl/default/match.php on line 58

Notice: Undefined index: resultovertime in /var/www/vhosts/svdoldie.stony-sport4u.de/httpdocs/modules/mod_sportsmanagement_matches/tmpl/default/match.php on line 62

**Comment by diddipoeler** [comment]
Das meine ich nicht.
Sende mir mal bitte die Adminzugangsdaten von **svdoldie.stony-sport4u.de** zu !

**Comment by svdoldie** [comment]
du hast Post

**Comment by diddipoeler** [comment]
Habe keine Post.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :+1: 
kann meinetwegen geschlossen werden

**Comment by Sumpfeimer** [comment]
Fast alles perfekt Switchen läuft, Überschrift läuft, Spielort läuft.

Mir ist nur noch eines aufgefallen Navigationspfeil zurück bei ausgewählt keinem Iconsatz ist nur ein leerer Button ohne <<

Siehe jsmtest.scrapid.de

**Comment by Sumpfeimer** [comment]
> Das Zeichen: << bereitet Probleme.
> Auch wenn man nur eins eingibt: <
Das doof und wenn Du

 «
&#171;
&laquo;

und

»

&#187;
&raquo;

benutzt

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Sumpfeimer** [comment]
Super läuft. Die Nervensäge gibt erstmal Ruhe und ist zufrieden.
Vielen Dank Ich mach dicht hier.

**Comment by svdoldie** [comment]
Gar nicht Nervensäge. Ganz im Gegenteil, du bist einer der wenigen, denen geholfen wird und der dann auch anderen hilft. siehe Forum !!! Vielen Dank !!!
