### ISSUE TITLE
Darstellung Ergebnisse/Matrix mit Karte

### ISSUE THREAD

**Issue by diddipoeler** [diddipoeler/sportsmanagement#866]

**Comment by diddipoeler** [comment]
Kann getestet werden.

**Comment by svdoldie** [comment]
Die Karte wird bei mir angezeigt. 
Allerdings kommt folgende Meldung:
Hinweis


Nicht vorhandenes Mastertemplate: resultsmatrix

Projekt-Id des nicht vorhandenen Mastertemplate: 3

Keine Panik! Informieren sie den Administrator der Webseite.
Sind sie selbst der Betreiber der Webseite, überprüfen sie bitte die Einstellungen der Templates vom Projekt (results & ranking).

das angemahnte Template existiert aber nicht

**Comment by svdoldie** [comment]
Eine kleine Frage zur Karte von OSM.
Was muss ich machen damit ich eine Karte angezeigt bekomme,
und nicht nur ein graues Bild?

**Comment by diddipoeler** [comment]
Wie graues Bild ?

**Comment by svdoldie** [comment]
so wie hier:
http://svdoldie.stony-sport4u.de/index.php?option=com_sportsmanagement&view=resultsranking&cfg_which_database=0&s=2:18-19&p=2:verbandsliga-nord-18-19&r=0&Itemid=389
oder
http://svdoldie.stony-sport4u.de/index.php?option=com_sportsmanagement&view=resultsranking&cfg_which_database=0&s=2:18-19&p=2:verbandsliga-nord-18-19&r=0&Itemid=389

hier geht es komischerweise 
http://svdoldie.stony-sport4u.de/index.php?option=com_sportsmanagement&view=clubinfo&cfg_which_database=0&s=2:18-19&p=2:verbandsliga-nord-18-19&cid=9:sv-doerpum&Itemid=114

**Comment by diddipoeler** [comment]
Es müssen bei allen Vereinen die Felder: Latitude und Longitude gefüllt sein.

**Comment by svdoldie** [comment]
ok. Leider wird das bei der Eingabe der Adressen nicht mehr automatisch generiert.
Zumindest bei mir nicht  :-(

**Comment by diddipoeler** [comment]
Sende mir mal bitte die Admindaten.

**Comment by svdoldie** [comment]
sind unterwegs...

**Comment by diddipoeler** [comment]
Die Zugangsdaten gehen nicht.

**Comment by svdoldie** [comment]
Beim Passwort fehlt ne 6 am Ende. Sorry

**Comment by diddipoeler** [comment]
Auch das geht nicht.

**Comment by svdoldie** [comment]
Ich habe sie dir nochmal geschickt

**Comment by diddipoeler** [comment]
Geht auch nicht.
Wenn Du auf Deine Links oben klickst, kommen nur Fehlermeldungen.
404 - Komponente nicht gefunden

**Comment by svdoldie** [comment]
Dann liegt es daran, dass die Testseite auf Stony's Server liegt.
Mit meinem vorherigen Provider konnte ich auch nicht auf die Seiten kommen.
Melde mich gleich nochmal

**Comment by svdoldie** [comment]
Ich weiß nicht warum, 
aber auf meiner Hauptseite funktioniert alles.
Nicht mal die Meldung mit dem Mastertemplate erscheint.

**Comment by sigal** [comment]
> 
> 
> Nur die Meldung mit dem Mastertemplate erscheint.

Auch auf diddi's und meiner Seite gibt es die gleiche Meldung.

Es muss erst dieses **resultsmatrix** Template erstellt werden

**Comment by diddipoeler** [comment]
Fehler Mastertemplate wird jetzt nicht mehr angezeigt.

**Comment by svdoldie** [comment]
läuft 👍

**Comment by sigal** [comment]
alles paletti 👍
