### ISSUE TITLE
Ergebnisansicht: Auswahl der Anzahl abschalten

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#870]
Ich würde es schöner finden, wenn man die Auswahl zur Anzahl der angezeigten Spiele in den Frontendeinstellungen abschalten könnte.

**Comment by svdoldie** [comment]
zur Klarstellung: das bezieht sich hierauf:
http://www.fussballineuropa.de/index.php/forum/sports-management/4666-grundsaetzliche-funktionen?start=24#13380

**Comment by svdoldie** [comment]
ist ja schon fertig :-) 👍

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
alles bestens 👍
Danke !!!
