### ISSUE TITLE
Ablösung Flash Chart

### ISSUE THREAD

**Issue by diddipoeler** [diddipoeler/sportsmanagement#872]
**Describe alternatives you've considered**

HTML5 und JavaScript:

Webseite: www.chartjs.org ﻿GitHub: github.com/chartjs/Chart.js 

Webseite: apexcharts.com/ 

Webseite:  d3js.org/ ﻿GitHub: github.com/d3/d3

**Comment by diddipoeler** [comment]
Kann mal getestet werden.

**Comment by diddipoeler** [comment]
Ich finde keine Einstellung dafür.

**Comment by PhantoSGE** [comment]
Das ist für diese Art der Darstellung nicht vorgesehen. 
Die Y-Achse beginnt an der X-Achse bei 0.

**Comment by svdoldie** [comment]
Na gut, ist dann so

**Comment by PhantoSGE** [comment]
Ich schau mich bei denen mal im GitHub um, evtl. hat das Thema dort ja schonmal jemand angesprochen.
In Excel funktioniert sowas, warum dann auch nicht hier

**Comment by PhantoSGE** [comment]
Kann hiermit jemand was anfangen?
https://www.chartjs.org/docs/latest/axes/cartesian/linear.html

https://github.com/chartjs/Chart.js/issues/5396

**Comment by diddipoeler** [comment]
ich musste ein bisschen rumbasteln. das ist der korrekte code:
`scales: {
yAxes: [{
ticks: {
beginAtZero:false,
reverse: true,
stepSize:1,
callback: function(value) {if (value == 0) {return "";} else {value = value * 1; return value;}}
}
}]
}`

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
PhantoSGE : Tausend Dank für Deine Unterstützung.

**Comment by PhantoSGE** [comment]
Sieht doch schonmal sehr schick aus.

**Comment by svdoldie** [comment]
Finde ich auch :+1: 
Allerdings würde ich sagen, dass die Anzeige der Zeilen, der Anzahl der Mannschaften entsprechen sollte.
Jetzt wird nur bist zum schlechtesten Platz einer Mannschaft angezeigt

**Comment by diddipoeler** [comment]
@svdoldie hat aber auch immer noch etwas zu bemängeln :-)

**Comment by svdoldie** [comment]
Jeder hat seine Aufgabe 😉

⁣Gesendet mit BlueMail ​

**Comment by diddipoeler** [comment]
Bitte noch einmal testen !

**Comment by PhantoSGE** [comment]
Bei mir funktioniert es 👍

**Comment by svdoldie** [comment]
Bei mir auch :+1:
