### ISSUE TITLE
Altersgruppenzuweisung nach JL-DB-Import wird nicht gespeichert

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#880]
Die Altersgruppenzuweisung nach JL-DB-Import wird nicht gespeichert

**Comment by diddipoeler** [comment]
In den Mannschaften wird es aber gesetzt.

**Comment by diddipoeler** [comment]
In den Projekten von JL gibt es kein Feld mit Mannschaftsart !

**Comment by svdoldie** [comment]
Ich weiß. Deshalb hattest du seinerzeit die Umstellung des vorhanden Infofeldes in die entsprechende Altersgruppe programmiert. Die Angabe kann man auch machen, aber sie wird eben nicht gespeichert

**Comment by diddipoeler** [comment]
Wo im Projekt ?

**Comment by svdoldie** [comment]
Ich Dussel, das war auf die Mannschaften bezogen. Ich habe bei den Projekten geschaut. Sorry !!!!!!!
Ich schließe den Issue
