### ISSUE TITLE
Fehler bei der Installation von JSM

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#881]
Bei der Installation auf einer neuen Testseite bekomme ich nur folgende Fehlermeldung:

Warnung

JInstaller: :Install: SQL-Fehler You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(`id`) , KEY `sports_type_id` (`sports_type_id`), UNIQUE KEY `name` (`name`,' at line 21

Erweiterung „Installieren“: SQL Fehler beim Ausführen der Abfrage: „DB-Funktion mit Fehlercode 1064 fehlgeschlagen!
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(`id`) , KEY `sports_type_id` (`sports_type_id`), UNIQUE KEY `name` (`name`,' at line 21
SQL = CREATE  TABLE IF NOT EXISTS `#__sportsmanagement_eventtype` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(75) NOT NULL DEFAULT '' ,
  `alias` VARCHAR(75) NOT NULL DEFAULT '' ,
  `icon` VARCHAR(128) NOT NULL DEFAULT '' ,
  `parent` INT(11) NOT NULL DEFAULT '0' ,
  `splitt` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
  `direction` CHAR(4) NOT NULL DEFAULT 'DESC' ,
  `double` TINYINT(3) NOT NULL DEFAULT '0' ,
  `sports_type_id` TINYINT(1) NOT NULL DEFAULT '1' ,
  `published` TINYINT(1) NOT NULL DEFAULT '1' ,
  `ordering` INT(11) NOT NULL DEFAULT '0' ,
  `checked_out` INT(11) NOT NULL DEFAULT '0' ,
  `checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' ,
  `modified` DATETIME NULL ,
  `modified_by` INT NULL ,
  `directionspoint` CHAR(4) NOT NULL DEFAULT 'DESC' ,
  `directionscounter` CHAR(4) NOT NULL DEFAULT 'DESC' ,
  `directionspointpos` tinyint(1) NOT NULL DEFAULT '1',
  `directionscounterpos` tinyint(1) NOT NULL DEFAULT '2'
  PRIMARY KEY (`id`) ,
  KEY `sports_type_id` (`sports_type_id`),
  UNIQUE KEY `name` (`name`,`parent`,`sports_type_id`)
  )
ENGINE = MyISAM
DEFAULT CHARSET = utf8;
“
× 
Fehler

Fehler bei der Komponenten-Installation.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :-)
