### ISSUE TITLE
Wunsch: Spielbericht Bilder löschen

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#882]
Im Menü "Spiele bearbeiten" gibt es die Möglichkeit Bilder hochzuladen.
![image](https://user-images.githubusercontent.com/9608697/53340763-08b44980-390a-11e9-9804-3d01ba253dbb.png)

Ist es Möglich einen Button hinzuzufügen um ein geladenes Bild wieder zu löschen?

Gruß´
Sven

**Comment by diddipoeler** [comment]
Unter Inhalte Medien kann man die Bilder löschen.
Ist aber sehr umständlich oder ?

**Comment by PhantoSGE** [comment]
Ja leider ein bisschen umständlich
