### ISSUE TITLE
Ergebnisspeicherung Benutzer in Gruppe nicht möglich

### ISSUE THREAD

**Issue by 8JollyRoger8** [diddipoeler/sportsmanagement#883]
Den Benutzern einer Gruppe die die Freigabe zur Ergebnisspeicherung hat, werden die Paarungen nicht angezeigt.
Benutzer als Editor funktioniert.

![editor gruppe](https://user-images.githubusercontent.com/46683386/53824152-9b409280-3f73-11e9-9246-ac24b9049faa.PNG)

JSM Version 1.0.70

**Comment by diddipoeler** [comment]
Bitte einmal testen.

**Comment by 8JollyRoger8** [comment]
Getestet.
Seite nicht mehr aufrufbar. Auch ohne Login.
![Editor Gruppe 1](https://user-images.githubusercontent.com/46683386/54304999-a2e0e680-45c6-11e9-846e-6040b6803b6f.PNG)

**Comment by 8JollyRoger8** [comment]
sorry falscher Button

**Comment by sigal** [comment]
Bitte welche Seite?

**Comment by 8JollyRoger8** [comment]
https://brandenburger-stadtdartliga.de
Unter Ligamanager - Ergebnisse

**Comment by diddipoeler** [comment]
Sorry, mein Fehler.
Bitte noch einmal testen.

**Comment by 8JollyRoger8** [comment]
Kein Problem,

jetzt funktioniert es auch als Gruppe 👍.
