### ISSUE TITLE
Page layout in "Ranking"

### ISSUE THREAD

**Issue by Rogackis** [diddipoeler/sportsmanagement#884]
Is in the file:
... \ components \ com_sportsmanagement \ views \ ranking \ tmpl \ default.php
is not missing </ div>?

**Comment by Rogackis** [comment]
I wonder if my question is understandable :grimacing:

**Comment by diddipoeler** [comment]
Was soll jetzt die Bemerkung ?

**Comment by Rogackis** [comment]
I wonder if I should describe the problem differently ... (sorry, but my language skills are poor and I use the translator :)

**Comment by Rogackis** [comment]
Perhaps my problems are related to the T4 framework that I used. There is no problem with the S5 Vertex Framework. I close the topic.
