### ISSUE TITLE
Fehlermeldung durch Geburtstagsmodul

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#885]
Ich habe seit gestern folgendes Problem nach einem Github-Update.
Und zwar bekomme ich folgende Fehlermeldung, wenn das Geburtstagsmodul aktiviert ist:
1242 - Subquery returns more than 1 row
Schalte ich das Modul aus, wird die Seite wieder angezeigt.

**Comment by diddipoeler** [comment]
Ich nicht !

**Comment by diddipoeler** [comment]
Welche Einstellungen hast du denn gemacht ?

**Comment by diddipoeler** [comment]
Hast du vielleicht mal den Adminzugang für mich ?

**Comment by diddipoeler** [comment]
Kann es sein, dass du mehrere Projekte angegeben hast ?
Und ein Spieler hat in den Projekten unterschiedliche Positionen ?

**Comment by svdoldie** [comment]
Zugangsdaten sind unterwegs.
Ich habe gar kein Projekt ausgewählt
Das mit den Personen kann möglich sein

**Comment by svdoldie** [comment]
Moin, irgendwie scheint es jetzt gar nicht möglich zu sein Personen anzuzeigen.
Oder ist das eine Frage der Moduleinstellungen?

**Comment by svdoldie** [comment]
Ist ne Frage der Einstellungen ;-)
Aber es ist leider nicht möglich mehrere Projekte auszuwählen

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
läuft :+1:

**Comment by svdoldie** [comment]
Moin. Ich habe noch ne Bitte für dieses Modul.
Bekommt man das hin, es so zu programmieren, dass
das Modul alle gespeicherten Personen aus den Stammdaten anzeigt?
Also ohne Einschränkung auf eine Saison, Projekt usw.

**Comment by svdoldie** [comment]
Hier kann geschlossen werden.
Die Personen werden ohne Angabe einer Saison oder eines Projektes angezeigt :-)
