### ISSUE TITLE
Tabellenmodul nicht mit Datenbank synchronisiert

### ISSUE THREAD

**Issue by alexm863** [diddipoeler/sportsmanagement#892]
**Describe the bug**
Auf meiner Homepage wird das Tabellenmodul (Ligatabelle) nicht mit der Datenbank im JSM synchronisiert, alle Stände im Modul sind auf 0 und in der Front-end Tabelle sind alle eingetragenen Spiele drin. Zum Vergleich habe ich einen Link eingetragen, der genau das Problem sichtbar macht.

**To Reproduce**
1. http://neu.fscbanditos.de/index.php/team/ranking/0/1:2018-2019/2:bedv-c2-liga/0/45:18-spieltag/0/0/2
2. Nicht wundern, wenn es heißt, dass die Seite unsicher ist (bei manchen Browsern wird es angezeigt), dass liegt an der noch fehlenden Verschlüsselung, da die Homepage noch nicht offiziell ist.
3. In der Mitte seht ihr die Tabelle mit eingetragenen Spieltagen und rechts im Modul ist alles 0.

**Expected behavior**
Ich hab alle Punkte so eingestellt, dass das Modul die Daten aus dem Projekt bekommen sollte.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: alle
 - Version -

**Smartphone (please complete the following information):**
 - Device Samsung Galaxy S9 und Tab S4
 - OS: Android 9 und 8
 - Browser Chome
 - Version 73.0.3683.90

**Joomla**
Version 3.9.4
PHP 7.3
Template: Artisteer created0

**Comment by diddipoeler** [comment]
Wenn das Vertrauen besteht, dann bitte mal für mich einen Adminzugang einrichten.

**Comment by alexm863** [comment]
Bitte schick mir mal eine Mailadresse an die alexm863@live.de, wo ich die Zugangsdaten hinschicken soll. Danke schön

**Comment by diddipoeler** [comment]
Hier

Gesendet mit der GMX iPad App

Am 30.03.19 um 21:06 schrieb alexm863

**Comment by diddipoeler** [comment]
Es gibt 2 Module mit der Tabellendarstellung.
Im Modul, wo keine Daten angezeigt werden, wurde eine Gruppe ausgewählt.
Es gibt aber im Projekt keine Zuordnung von Mannschaften und Spiele zu der Gruppe.
Deshalb werden auc keine Daten angezeigt.
