### ISSUE TITLE
Fehlerhaftes Ereignis (Sortierung

### ISSUE THREAD

**Issue by alexm863** [diddipoeler/sportsmanagement#894]
**Describe the bug**
Die Sortierung funktioniert nicht richtig. Egal was im Backend eingestellt ist, ob Tabelle auf- oder absteigend, es bleibt immer die absteigend sortierte Tabelle. Die Tabelle mit "SL" sollte aufsteigend sortiert werden.
Die eingetragenen Ereignisse befinden sich in:
- Projekt: BeDV C2-Liga
- Spieltage
- Spieltag 8 & 9 (jeweils bei FSC Banditos)

**To Reproduce**
1. Go to http://neu.fscbanditos.de/index.php/saison2018-19/highfinish
2. See error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera
 - Version 58.0.3135.132

**Comment by alexm863** [comment]
Ich habe grade festgestellt, dass es ein Problem mit dem Modul ist. Die normale Ereignis-Tabellenansicht funktioniert.
Tabellenansicht: http://neu.fscbanditos.de/index.php/saison2018-19/shortlegs
Modulseite: http://neu.fscbanditos.de/index.php/saison2018-19/highfinish

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Ich denke, der Issue kann geschlossen werden.
Soweit ich sehen kann, benutzt alexm863 kein JSM mehr.
