### ISSUE TITLE
Fehler 0 Cannot use string offset as an array

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#895]
Moin, Unter Projekte > Divisionen > Gruppendetails bearbeiten kommt die Fehlermeldung
"Fehler 0 Cannot use string offset as an array"
![image](https://user-images.githubusercontent.com/9608697/57178257-dd9c2800-6e6d-11e9-9836-e5757114cdf8.png)

Gruß

**Comment by diddipoeler** [comment]
Wo ?

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Funktioniert einwandfrei. Danke
