### ISSUE TITLE
Falsche Darstellung Spielplan bei Gruppenliga

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#896]
Wenn in den Menüeinstellungen keine Gruppe ausgewählt wird ist die Gruppenanzeige falsch.
![image](https://user-images.githubusercontent.com/9608697/57178553-89477700-6e72-11e9-8483-9fb83d25d915.png)
![image](https://user-images.githubusercontent.com/9608697/57178565-be53c980-6e72-11e9-8969-a2ef4a3a687e.png)

So sieht es aus:
![image](https://user-images.githubusercontent.com/9608697/57178557-9b291a00-6e72-11e9-9281-abeac12d160c.png)

So sollte es aussehen:
![image](https://user-images.githubusercontent.com/9608697/57178561-a7ad7280-6e72-11e9-93a2-c9f29138a8fd.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Peferkt. Danke dir
