### ISSUE TITLE
Flash charts

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#897]
I can't show any flash chart on sport management.
I've tried with different browsers and the result is the same.
i have installed lasty version of joomla 3 and last version of sport management.
is it necessary to enable/disable any plugin?

**Comment by llambion72** [comment]
Solved, I've reinstalled joomla again only with sportmanagement component and it works. Now, i'll install one by one all modules and skins to evalutate compatibility...

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Bei mir funktioniert soweit alles. :
Es wäre aber schön wenn man die Anzeige,
ähnlich wie im Template flash anpassen könnte

**Comment by diddipoeler** [comment]
Welche Anzeige ?

**Comment by svdoldie** [comment]
Fieberkurve, Teamstatistik und Statistik

**Comment by diddipoeler** [comment]
Was willst du denn da noch anpassen ?
Es gibt doch jetzt schon viel zu viele Möglichkeiten für die User.

**Comment by svdoldie** [comment]
Ich meine nur die Farben, der Flashanzeige

**Comment by diddipoeler** [comment]
In welcher Ansicht teamstats, stats, curve ?

**Comment by svdoldie** [comment]
Für alle drei AnsichteVorher konnte man den ganzen Flashkram in dem entsprechenden Template konfigurieren. Das scheint alllerdings nach der Umstellung nicht mehr zu greifen

**Comment by diddipoeler** [comment]
Sollte ja auch nicht mehr greifen, da es sich ja nicht mehr um Flash handelt, sonder um Javascript.
Außerdem bin ich vielleicht nicht der einzige, der der Meinung ist, dass die ganzen Einstellungen
die Enduser überfordern. Das liest man ja manchmal in den Kommentaren im Forum.

**Comment by svdoldie** [comment]
Da gebe ich dir durchaus recht. Vielleicht dann zumindest das pink in grau oder etwas anderes tauschen ;-)

**Comment by svdoldie** [comment]
Sieht jetzt richtig gut aus 👍👍👍

**Comment by diddipoeler** [comment]
Tja so bin ich eben :-)

**Comment by svdoldie** [comment]
Wirklich klasse :-) 👍

**Comment by svdoldie** [comment]
Von mir aus kann dieser Issue zugemacht werden
