### ISSUE TITLE
Language menus

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#898]
I've updated sportmanagement 1.0.64 to 1.0.73 and joomla menu backend sportmanagement are now in german and menu type options when i try to create a new menu item are in german too.
Before update were in spanish and someone in english.
I've translated 90% of sport management into spanish via trasifex but menu options are in german.

**Comment by sigal** [comment]
Please install your prefered language by clicking the Transifex Icon.
![Bildschirmfoto vom 2019-06-11 20-58-43](https://user-images.githubusercontent.com/5115688/59299322-af8bde00-8c8c-11e9-9b4b-f728aac16581.png)

**Comment by llambion72** [comment]
I did it but sportmanagements menu items didn`t change. they stayed in german
![error menus02](https://user-images.githubusercontent.com/20923398/59299671-86b81880-8c8d-11e9-9045-db65e45e156b.png)
![error menus](https://user-images.githubusercontent.com/20923398/59299681-8e77bd00-8c8d-11e9-9387-4016104bae2e.png)

**Comment by sigal** [comment]
Which language is installed in Joomla and which language is standard in your Joomla installation?

JSM is currently delivered with German and English as standard translations. Other languages, according to diddi, are supplied directly by Transifex and can be installed in addition to the installed standard Joomla language.

**Comment by llambion72** [comment]
I've installed joomla in spanish and this is default language for my website

**Comment by llambion72** [comment]
I have no trouble with english language but i don't speak german and it's very difficult for me understand some options

**Comment by sigal** [comment]
The language file in Spanish, which is also relevant for menu entries, was only translated to ~ 37%.

The file is called on Transifex: admin-com_sportsmanagement.sys.ini

And on the server, the file is in the admin/language/es-ES/es-es/es-ES.com_sportsmanagement.sys.ini folder

**Comment by llambion72** [comment]
I Will translate this file tomorrow and i Will try to update again

**Comment by llambion72** [comment]
I've downloaded this file for translation and almost all streams that are no disabled has been translated by me many months before now. Rest of uncomment lines, i've translated this morning. 
Even though the file marks only 36.6% of the translated sentences, the rest are phrases that appear deactivated in the file and that is why I have not translated them.
I've translated about 80% of working phrases, but i don't have translated disabled lines
I updated my site via transifex and joomla menus and joomla items menu description for sport management stay in german

For spanish translations, there aren´t any reviewer to approve translated streams on transifex team. If you don't have a spanish translation reviewer, I offer myself with a reviewer to complete the translation into Spanish

**Comment by sigal** [comment]
You are unlocked as a reviewer. 
Have fun translating and testing.

**Comment by llambion72** [comment]
Ok, thank you!!!

**Comment by llambion72** [comment]
When I update the language in the component through the button of transifex some icons of some files are not shown as is the case of,
admin-com_sportsmanagement.ini
admin-com_sportsmanagement.sys.ini
mod_sportsmanagement_calendar.ini

On the other hand I would like to know what it means that the update has been erroneous. Is it because he could not download the file? or because the file is wrong?
This case happens to me in several files that are completely translated however I get an error when updating

**Comment by sigal** [comment]
Are all files, or just individual affected?
A snapshot of the error messages would also be helpful.
With kind regards
stony

**Comment by sigal** [comment]
Hello, I see that only 100% translated files will be installed.

In addition, the adoption of the plugin language files must still be implemented. I hope I could help right now.
Maybe diddi can screw down the 100% to about 75%.

**Comment by llambion72** [comment]
![transifex_01](https://user-images.githubusercontent.com/20923398/59617538-cd42c280-9126-11e9-9dc8-9fd531b9fb84.png)
![transifex_02](https://user-images.githubusercontent.com/20923398/59617552-d338a380-9126-11e9-9897-98ae231c89ac.png)

**Comment by llambion72** [comment]
It could be interesting to be able to install languages that are not 100% translated so that you can check the translations little by little.
On the first image, two first files don't show status image.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen !

**Comment by sigal** [comment]
![error_spanish_translation](https://user-images.githubusercontent.com/5115688/59781362-f052ab00-92bb-11e9-9201-b85c4a88c9ce.png)

Plugin - Übersetzungen werden nicht installiert.

**Comment by diddipoeler** [comment]
Mit den Plugins muss ich noch programmieren.
Wichtig war der Test, das die restlichen Sprachdateien übernommen werden.
Egal wie viel Prozent fertig ist.

**Comment by sigal** [comment]
https://github.com/diddipoeler/sportsmanagement/issues/898#issuecomment-502715876
