### ISSUE TITLE
Error in teamplayers module

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#899]
After update 1.0.64 to 1.0.73 module teamplayers shows next error

![team_players](https://user-images.githubusercontent.com/20923398/59287711-7fcfdc80-8c72-11e9-82aa-55f913c8d848.png)

if i disable this module, my web loads perfectly...

**Comment by diddipoeler** [comment]
Bitte noch einmal testen !

**Comment by llambion72** [comment]
Now, it works perfect!!
Thank you for all
