### ISSUE TITLE
Random player module

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#900]
after update 1.0.64 to 1.0.73 random player module shows 'no items' ever. 
I've selected in the backend random player module, season, proyect and favorite team but none player appear. 
I have assigned 25 players to my favorite team for this season and project.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen !

**Comment by llambion72** [comment]
Now, it works perfectly...
Thank you for everything!!
