### ISSUE TITLE
Mannschaftschnellzuordnung erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#905]
Nutzt man in einem Projekt die Mannschaftschnellzuordnung, so wird folgende Fehlermeldung erzeugt:
1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND season_id = 12' at line 3

Die Mannschaft wird nicht zugeordnet

**Comment by svdoldie** [comment]
Noch ne kleine Idee dazu. Es wäre gut wenn die Altersgruppe auch angezeigt werden würde.
Das hilft bei Namensgleichheit die richtige Mannschaft auszuwählen

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Perfekt, sogar mit Logo :
