### ISSUE TITLE
Spielerliste hochladen erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#910]
Beim Hochladen einer Spielerliste per DFBNet-Import erfolgt folgende Fehlermeldung:
Fehler
Fehler: Load of the importfile failed:!
Fehler: Input is not proper UTF-8, indicate encoding ! Bytes: 0xFC 0x73 0x65 0x6B !
Fehler: Something is wrong inside the import file!

In der Liste ist ein Spieler mit einem Umlaut im Namen.
Listen ohne solche Namen werden einwandfrei hochgeladen und lassen sich importieren.
@diddipoeler : Ich habe dir die Liste per Mail zugesandt

**Comment by svdoldie** [comment]
Die Liste wird vom DFB-Net leider nicht im UTF-8 Format geliefert.
Nach Umstellung des Formats lässt sich die Spielerliste hochladen und importieren.
Wenn keine Programmierung des Imports im DFB-Net-Format möglich bzw. zu Aufwendig ist,
würde ich den Issue schließen

**Comment by svdoldie** [comment]
Dasselbe gilt hier https://github.com/diddipoeler/sportsmanagement/issues/931

**Comment by diddipoeler** [comment]
Könntest du mir bitte noch einmal eine Liste zusenden ?

**Comment by svdoldie** [comment]
Hab dir ne Mail geschickt 👍

**Comment by diddipoeler** [comment]
Bitte einmal testen.

**Comment by svdoldie** [comment]
Die Spielerliste wird jetzt anstandslos hochgeladen und importiert.Magst du in diesem Zusammenhang dies auch nochmal ansehen https://github.com/diddipoeler/sportsmanagement/issues/284
Ich habe übrigens  auch noch mal einen Spielplan importiert. Da werden jetzt die Umlaute aber nicht mehr richtig übernommen.

**Comment by diddipoeler** [comment]
Bitte einmal testen.

**Comment by svdoldie** [comment]
Beim Spielplan werden die Umlaute wieder richtig gesetzt 👍
