### ISSUE TITLE
Error in predicction game

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#911]
When i try to edit my prediction game profile on the frontend, 

if press this icon,
![error02](https://user-images.githubusercontent.com/20923398/62124705-32afd480-b2cb-11e9-8d3a-2e71c38c68f4.jpg)

this error appear,
![error](https://user-images.githubusercontent.com/20923398/62123956-5b36cf00-b2c9-11e9-974b-6ffe17c41682.jpg)

**Comment by diddipoeler** [comment]
Den Fehler habe ich nicht !

**Comment by llambion72** [comment]
I have installed 1.0.74 version. 
I'll try to find this error. On previous versions i believe that this error didn't occurs

**Comment by llambion72** [comment]
I've tried to disable all frontend options one by one and i can't find where option provoke this error. With all options disabled this error ever appear.

**Comment by llambion72** [comment]
I've downloaded JSM and updated all component files manually and now it works again. There was some files that had different size.
I believe that last update didn't finish correctly.

**Comment by diddipoeler** [comment]
Kann ich das jetzt schließen ?

**Comment by llambion72** [comment]
Yes
