### ISSUE TITLE
Create new project -> 0 Class 'jsmGCalendarDBUtil' not found 

### ISSUE THREAD

**Issue by vieri** [diddipoeler/sportsmanagement#917]
When I create a new project I got this error:

0 Class 'jsmGCalendarDBUtil' not found

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by vieri** [comment]
Solved.

This error is happens to when we try to enter in google calendar from sidebar left menu, but when I try to access a google calendar from the dropdown main menu this works well. After when I enter in Google calendars, if I try to enter to manage calendars I got another time this error, I think there are something wrong on the urls ...

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
