### ISSUE TITLE
Users possible bug

### ISSUE THREAD

**Issue by llambion72** [diddipoeler/sportsmanagement#918]
I have 3.9.3 joomla installed.
When I've installed JSM component, i can't any edit user profile in joomla backend.

![error_01](https://user-images.githubusercontent.com/20923398/62412578-30b87f00-b605-11e9-8c99-e65e2a5005a9.jpg)

Sometimes this message "Class 'SportmanagementHelper'" not found appear instead image error

If i uninstall JSM can edit a user profile normally.

**Comment by sigal** [comment]
Joomla 3.9.3 is out of date and is a security risk on a public server!
Please install the latest Joomla Release (3.9.10).

With Joomla 3.9.10 and JSM 1.0.75 there are not the described problems!

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
> 
> 
> Bitte noch einmal testen.

Mit Joomla 3.9.3 teste ich nicht!

**Comment by llambion72** [comment]
I've upgraded JSM to last version and I downloaded your recent modify files and I updated my installation. Now It seems that works ok.
It works on Joomla 3.9.3 and 3.9.10
