### ISSUE TITLE
Bearbeitung der Ereignisse im Frontend nicht möglich

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#925]
Speichern von Ereignissen im Frontend nicht möglich.

Siehe Forumsbeitrag: http://fussballineuropa.de/index.php/forum/sports-management/4713-ereignisbearbeitung-frontend-und-pixelfehler#13779

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Alles perfekt!
