### ISSUE TITLE
Sports Management: Projektmannschaften - Vereinsdetails

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#929]
Backend - Projekt - Mannschaften
Scheinbar wird die View zur Bearbeitung eines Vereins nicht in das Modalfenster geladen?
Modalfenster ist leer.
Joomla 3.9.12 NEUINSTALLATION
JSM 2.0.00 - NEUINSTALLATION mit GitHub-Update von heute 14:30
PHP - 7.2.23

![Modalfenster-Club edit](https://user-images.githubusercontent.com/5115688/67287735-ed6efd80-f4db-11e9-8be6-cca152b443c1.jpg)

**Comment by diddipoeler** [comment]
Merkwürdig, bei mir ja.

**Comment by sigal** [comment]
Hab ich mir's doch gedacht. Geh jetzt den Umweg über Stammdaten - Vereine.

**Comment by diddipoeler** [comment]
Aber woran kann es denn liegen ?

**Comment by sigal** [comment]
Momentan keine Ahnung.
Ältere per Upgrade zu Version 2.0.00 bestehende Installationen haben diese Eigenheit nicht.

Auf gleichen Serversystemen und einer Neuinstallation von Joomla und JSM beobachte ich dieses Problem.
Muß mal die Dateien einer alten (Upgrade) und  einer neuen Installatioon prüfen.
