### ISSUE TITLE
Joomla 4: 500 JHtmlBehavior::framework not found. 

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#931]
Diese Fehlermeldung erscheint bei den Frontendeinstellungen eines Projekts

**Comment by diddipoeler** [comment]
Welches Template hast du denn aufgerufen ?

**Comment by svdoldie** [comment]
Die Meldung kommt bereits, wenn man die Template-Auswahl anzeigen lassen möchte

**Comment by diddipoeler** [comment]
man oh man. joomla 4 ist aber empfindlich.
dauert noch etwas, bis alles im backend mit joomla 3 und 4 läuft :-)

**Comment by diddipoeler** [comment]
Kannst Du mal bitte den dfbnet import testen ?

**Comment by svdoldie** [comment]
Grundsätzlich funktioniert der Import :-)
nur bei einzelnen Sportplätzen scheint es Probleme zu geben:
Fehler in Funktion: _importPlayground
Playgroundname: Sportplatz Lunden
Field 'notes' doesn't have a default value

Und folgende Meldung kommt ,wenn ein Team schon existiert:
Created new projectteam data: _getTeamName2 1150#Error in _getTeamName2# team_id -> 35
- Team ID : 33
Created new projectteam data: _getTeamName2 1150#Error in _getTeamName2# team_id -> 36
- Team ID : 34

**Comment by diddipoeler** [comment]
Created new projectteam data 
Musste ich umprogrammieren :-)
Sieht jetzt bessser aus.

**Comment by diddipoeler** [comment]
Neue Version installieren und dann bitte testen.

**Comment by svdoldie** [comment]
Sieht schon viel besser :-)
Einen Fehler gibt's aber noch:
Fehler in Funktion: _importPlayground
Playgroundname: Sportplatz Viöl B-Platz KR+FL
Data too long for column 'short_name' at row 1

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
Fehler ist noch vorhanden
Ich glaube das Feld ist zu klein, oder?

**Comment by diddipoeler** [comment]
Bei mir ist der Fehler nicht vorhanden.
Läuft alles.

**Comment by svdoldie** [comment]
Ich habe dir die Datei mal geschickt, die den Fehler erzeugt

**Comment by diddipoeler** [comment]
Kein Wunder. 
Die Datei ist nicht im UTF8 codiert.

**Comment by svdoldie** [comment]
So kommen die aus dem dfbnet😏

**Comment by svdoldie** [comment]
Ich hab es jetzt noch mal auf deiner Joomla 4-Testseite probiert.
Diseser Fehler existiert leider noch:

Fehler in Funktion: _importPlayground
Playgroundname: Sportplatz Viöl B-Platz KR+FL
Data too long for column 'short_name' at row 1

**Comment by svdoldie** [comment]
Merkwürdig, ich habe dieselbe Datei auf einer neuen Testseite probiert und diesmal lief alles gut...

**Comment by svdoldie** [comment]
Fehler existiert nicht mehr :+1:
