### ISSUE TITLE
LMO-Import doesn't work

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#934]
Seit Version 2.3.00 ist es nicht mehr möglich, einen Import durch zuführen.

**Comment by sigal** [comment]
Die Fehlermeldungen Schritt für Schritt im Bild:

![LMO-Import-Schritt2](https://user-images.githubusercontent.com/5115688/68937903-950ae300-079d-11ea-802c-5402779fb88c.jpg)

![LMO-Import-Schritt3](https://user-images.githubusercontent.com/5115688/68937968-afdd5780-079d-11ea-8313-c75c1de7c33a.jpg)

![LMO-Import-Schritt3-02](https://user-images.githubusercontent.com/5115688/68937996-ba97ec80-079d-11ea-81c3-2d41a1809d3d.jpg)

![LMO-Import-Schritt3-03](https://user-images.githubusercontent.com/5115688/68938019-c84d7200-079d-11ea-9726-f0b97ddce8cd.jpg)

![LMO-Import-Schritt3-04](https://user-images.githubusercontent.com/5115688/68938049-d7342480-079d-11ea-92de-07a819da7a19.jpg)

**Comment by diddipoeler** [comment]
Hast Du bitte noch die LMO-Datei für mich ?

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Die 1. Datei ist vom Rechner, die 2. Ist direkt vom Server – aus dem tmp-Ordner

 

Von: diddipoeler <notifications@github.com> 
Gesendet: Freitag, 15. November 2019 12:29
An: diddipoeler/sportsmanagement <sportsmanagement@noreply.github.com>
Cc: stony <stony@sport4u.at>; State change <state_change@noreply.github.com>
Betreff: Re: [diddipoeler/sportsmanagement] LMO-Import doesn't work (#934)

 

Hast Du bitte noch die LMO-Datei für mich ?

**Comment by sigal** [comment]
Sind noch immer Fehler vorhanden.

Die neu zu anlegenden Vereine wurden beim Ersten Versuch angelgt, Teams nicht.

Beim 2. Versuch siehe screenshots

![2-LMO-Import-Schritt3](https://user-images.githubusercontent.com/5115688/68944217-a0fea100-07ad-11ea-9313-01139480f7d0.jpg)

![2-LMO-Import-Schritt3-04](https://user-images.githubusercontent.com/5115688/68944236-ab209f80-07ad-11ea-91a2-98a9346ba14d.jpg)

**Comment by sigal** [comment]
So soll es aussehen.

![3-LMO-Import-Schritt3-04](https://user-images.githubusercontent.com/5115688/68960346-475b9e00-07d0-11ea-9a85-2df2091bf796.jpg)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Es funktioniert wieder.

Jedoch hätte ich weitere Vorschläge zum Umsetzen.

Beim Import (LMO, XML, DFB etc.)
Auswahl der Sportart, Altersgruppe vor dem Import.

Dadurch könnte bei Neuanlage von neuen Vereinen und Mannschaften das schon automatisch eingepflegt werden. Momentan müssen bei Importen Sportart und Altersgruppe händisch bei den Mannschaften eingepflegt werden.

**Comment by diddipoeler** [comment]
Gute Idee.
Ich versuche das mal umzusetzen.

**Comment by sigal** [comment]
Den Import haste **super umgesetztt!!!**

Wen noch einige Kleinigkeiten bei Anlage des Projekts beim Import umgesetzt werden, kannst du diesen Issue schließen.

Beim LMO-Import und Anlage des Projekts:
Automatisches festlegen der Altersgruppe (Kann man jetzt schon beim Import festlegen)
Auswahl und festlegen eines Template.
Festlegen des Placeholder-Bildes für ein neues Projekt. Momentan wird nur der Ordner festgelegt.

![4-LMO-Import-Anlage Projekt](https://user-images.githubusercontent.com/5115688/69014215-466d6c80-0988-11ea-9c49-046bf24ac821.jpg)

![4-LMO-Import-Anlage Projekt-Bild](https://user-images.githubusercontent.com/5115688/69014224-58e7a600-0988-11ea-98a8-aae012766628.jpg)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Ist praktisch perfekt.
Import funktioniert perfekt, auch die Umsetzung Altersgruppe, Sportart, Bild, Projekt-Startdatum, Projekt-Aktueller Spieltag.

Einzig die Auswahl der Templates im LMO-Import (Schritt 1) kann entfernt werden, da Du dies schon beim Zuordnung der Haupdaten inkludiert hast (Schritt 2 -XML-Import).

**Das Projekt mit allen Zuordnungen ist perfekt!!!**

![4-LMO-Import-Schritt1](https://user-images.githubusercontent.com/5115688/69064503-97c83b00-0a1e-11ea-906e-0225d5f005b8.jpg)

![4-XML-Import-Schritt2](https://user-images.githubusercontent.com/5115688/69064571-add5fb80-0a1e-11ea-9cf7-15dc204a12bd.jpg)

**Comment by sigal** [comment]
Bitte ändere auch den Ausgabenamen der Exportroutine auf deinen Komponentennamen.
DU HAST ES VERDIENT!

**Comment by svdoldie** [comment]
Erneut tolle Arbeit Diddi 👍👍👍

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Eine super Arbeit diddi!
Kannst diesen Issue nun schließen
