### ISSUE TITLE
Backend-View: matches Layout: default

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#942]
PHP: 7.2.25
TAB Spieldetails ->Entscheidung nach Spielende
Momentan keine Auswahl möglich.

![spieldetails](https://user-images.githubusercontent.com/5115688/70265468-c1ad8b80-179a-11ea-8804-2b7ca33ec903.jpg)

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by sigal** [comment]
Funktioniert erst bedingt. Das einblenden sollte bei Klick auf -Ja- erfolgen.
Momentan erst bei einmal Klick auf Speichern.

![spieldetails02](https://user-images.githubusercontent.com/5115688/70329141-f8d37980-183a-11ea-9830-6b833d597441.jpg)

![spieldetails03](https://user-images.githubusercontent.com/5115688/70329163-038e0e80-183b-11ea-8131-915a0c0afa0d.jpg)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Exzellent :ok_hand:
Kann nun geschlossen werden
