### ISSUE TITLE
Frontend-Matchreport - Bilder Spielfeld

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#943]
PHP: 7.2.25
Nach kompletten löschen des Inhalt der matchreport.css im GitHub, werden beide Spielfeld-Bilder nicht mehr geladen.
Es fehlt das Laden der Bilddateien:

`#timeline-top {
    background-image: url("/images/com_sportsmanagement/database/matchreport/spielfeld_top.png");
    background-repeat: no-repeat;
    background-size: 100% 46px;
    height: 47px;
	
}

#timeline-bottom {
    background-image: url("/images/com_sportsmanagement/database/matchreport/spielfeld_bottom.png");
    background-repeat: no-repeat;
    background-size: 100% 46px;
    height: 47px; 
	vertical-align: baseline;

}
`

Siehe z.B. auch auf Seite (Zeitlinie): http://fussballineuropa.de/index.php/component/sportsmanagement/matchreport/0/0/89037:2-bundesliga-2019-20/16512584:vfl-osnabrueck-1899-e-v-i_hamburger-sv-e-v

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by sigal** [comment]
:ok_hand:
Kann geschlossen werden!
