### ISSUE TITLE
Joomla 4: Positionen lassen sich nicht einem Projekt zuweisen

### ISSUE THREAD

**Issue by svdoldie** [diddipoeler/sportsmanagement#944]
Will man unter Joomla 4 einem Projekt Positionen zuweisen,
geht das nicht, weil die Felder zum an bzw. abwählen nicht angezeigt werden.
Die Positionen sind in den Stammdaten vorhanden, siehe Bilder
![Bildschirmfoto vom 2019-12-07 07-56-21](https://user-images.githubusercontent.com/2417767/70370430-93799a00-18c7-11ea-8f4d-1819bb6b4c40.png)
![Bildschirmfoto vom 2019-12-07 07-57-15](https://user-images.githubusercontent.com/2417767/70370431-95dbf400-18c7-11ea-8dbf-7bac8bc05711.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by svdoldie** [comment]
geht wieder +1
