### ISSUE TITLE
Backend-View: rounds Layout: default

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#946]
Bilder sagen meist mehr als Worte:

![Backend-View_rounds Layout_ default](https://user-images.githubusercontent.com/5115688/70457941-65f04480-1ab1-11ea-86fa-10c9f51eae77.jpg)

![Backend-View_rounds Layout_ default-2](https://user-images.githubusercontent.com/5115688/70458091-ab147680-1ab1-11ea-8e86-d073bad9640a.jpg)

![Backend-View_rounds Layout_ default-3](https://user-images.githubusercontent.com/5115688/70458204-e7e06d80-1ab1-11ea-9d44-7653bca2407e.jpg)

![Backend-View_rounds Layout_ default-4](https://user-images.githubusercontent.com/5115688/70458221-f464c600-1ab1-11ea-8bb2-e19193ae5222.jpg)

**Comment by diddipoeler** [comment]
bitte noch einmal testen.

**Comment by sigal** [comment]
Perfekt! : :thumbsup:

Kann geschlossen werden
