### ISSUE TITLE
Ewige Tabelle -  Eigene Wertungsdaten verwenden fehlerhaft

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#947]
Bin gerade dabei, einige Ligen ohne vorhandene Spieltage (Nur Tabellen vorhanden) in Projekten anzulegen. 

Nun ist mir bei der ewigen Tabelle einer Liga aufgefallen (drei Projekte nur mit eigenenWetungsdaten), dass die Berechnung einer dieser Projekte in der Ewigen Tabelle aufscheint, die anderen aber negiert werden. Offenbar bricht die Routine zur Berechnung dieser eigenen Wertungsdaten nach einem Projekt ab. Hab aber diesbezüglich keine Fehlermeldung parat, wo man ansetzen könnte.

Bei einer anderen Liga ist mir aufgefallen, dass negative Startpunkte auch nicht berücksichtigt werden.

Wäre toll. wenn du mal kurz drüberschauen könntest.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Leider keine Änderung

**Comment by diddipoeler** [comment]
Wie ist der Link zu der ewigen Tabelle, wo der Fehler auftritt ?

**Comment by sigal** [comment]
Hier die ewige Tabelle: https://demo.jsm-help.de/jsm-alle-projekte/rankingalltime/0/236/3,1,0/0/0/0/0/4190:st-oberliga-nord-2019-20

Z.B. zum Vergleich Rang 49 ewige Tabelle (Pöls): 26 Spiele

In der Vereinsinfo scheinen 3 Saisonen auf (Oberliga Nord). Gesamt müssten es nach Adam Riese 78 Spiele sein. Saison 1998/99, 1997/98, 1996/97. Gezählt wird nur Saison 1998/99,

Vereinsinfo Pöls: https://demo.jsm-help.de/jsm-alle-projekte/teaminfo/0/0/4408:st-oberliga-nord-1998-99/3705:poels

Fazit: Von Projekten mit eigenen Wertungsdaten wird nur ein Projekt in die ewige Tabelle aufgenommen.

**Comment by diddipoeler** [comment]
Kannst du mir mal bitte die Admindaten zusenden ?

**Comment by sigal** [comment]
Du hast eine PN auf deiner Seite.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Perfekt. Die restlichen Projekte werden mitgezählt. 👍

**Comment by sigal** [comment]
Muss nochmals öffnen.
Projektmodel-Fehler: Projekt wird benötigt
Siehe: Screenshot deiner Seite

![#947-1](https://user-images.githubusercontent.com/5115688/76702753-aec92200-66cc-11ea-901e-15a670672e53.jpg)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Wenn eine Mannschaft gewählt wird, die nicht im Projekt vorhanden ist, gibt es eine Fehlermeldung.

![#947-2](https://user-images.githubusercontent.com/5115688/76705024-328b0a80-66dd-11ea-97bb-072f40499a2c.jpg)

![#947-3](https://user-images.githubusercontent.com/5115688/76705025-3880eb80-66dd-11ea-82e9-db851c1d661a.jpg)

**Comment by diddipoeler** [comment]
Man sollte hier überhaupt keine Verlinkung vornehmen.
Es handelt sich schließlich nur um eine ewige Tabelle.
Oder wie siehst du das ?

**Comment by sigal** [comment]
Seh ich auch so.
OK. Verlinkungen entfernen dann kannst das Issue schließen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Ok. Danke 👍 
Ich schließe
