### ISSUE TITLE
Backend-View: XML-Editor

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#952]
Der XML-Editor zeigt beim Start folgende Fehlermeldung:
Class 'Factory' not found

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Noch nicht. Bei click auf die erste xml 

Table smextxmleditor not supported. File not found.

**Comment by diddipoeler** [comment]
Benötigen wir das Tool überhaupt ?

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Läuft :+1:

**Comment by sigal** [comment]
Ee wäre vielleicht doch besser, das Tool zu entfernen.
