### ISSUE TITLE
Update JSM from Version to Version

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#954]
Beim Update von einer Version zur nächsten, kann es passieren (wenn der Inhalt des Joomla tmp Verzeichnis nicht gelöscht wurde, das die neue Versionn angezeigt wird, aber die Dateien nicht erneuert werden.

Bei einer Neuinstallation wird im tmp Verzeichnis die Zip-Datei master.zip geschrieben und entpackt.
Nach der Installation wird die master.zip nicht gelöscht.
Bei einem Update durch Joomla! wird die master.zip nicht neu geschrieben - nur die Entpackung der alten Datei erfolgt. 
Es wird nur die Versionsnummer angepasst.

Deswegen muss nach erfolgreicher Installation die master.zip durch die Installationsroutine gelöscht werden. Besser wäre noch das entzippte Verzeichnis (sportsmanagement-master) gleich mit zu löschen.

**Comment by diddipoeler** [comment]
Warum geschlossen ?

**Comment by diddipoeler** [comment]
Bitte einmal testen !

**Comment by sigal** [comment]
Verzeichnisse und Dateien im tmp-Ordner werden gelöscht (JSM GitHub Update)
Eine Kleinigkeit noch:

![githubinstall](https://user-images.githubusercontent.com/5115688/71475993-27fa5c80-27e3-11ea-8746-96855d152449.jpg)

Erweiterungsinstallation über Joomla! muß ich noch nachstellen!!

**Comment by diddipoeler** [comment]
Bitte einmal testen !

**Comment by sigal** [comment]
So soll es sein!
