### ISSUE TITLE
Frontend: view staff

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#957]
Bei Aufruf der Mitarbeiter gibt es einen 500er
Matchreport -> Link auf  Trainer (staff)

**Comment by diddipoeler** [comment]
Bei mir nicht:
http://www.fussballineuropa.de/index.php/component/sportsmanagement/staff/0/0/89036:1-bundesliga-2019-20/9:fc-gelsenkirchen-schalke-04-e-v-i/4659:david-wagner

**Comment by sigal** [comment]
Na gut.
