### ISSUE TITLE
Notice: Undefined variable: defaults in com_sportsmanagement/router.php on line 132

### ISSUE THREAD

**Issue by jst71** [diddipoeler/sportsmanagement#958]
Beim öffnen der Seite https://tipps.stelteronline.de/spielplan/allprojects erscheint der Fehler oben.

Es wird vorher in Zeile $defaults = sportsmanagementHelperRoute::$views[$segments[0]]; offensichtlich kein $defaults gesetzt.

Fehlt mir eine Extension?

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by jst71** [comment]
OK!
