### ISSUE TITLE
0 - Class 'Registry' not found (teamplan)

### ISSUE THREAD

**Issue by jst71** [diddipoeler/sportsmanagement#959]
Bei Aufruf https://tipps.stelteronline.de/spielplan/teamplan/0/0/6:wm2018/1:deutschland/0/121:deutschland erscheint oben stehende Fehlermeldung.

**Comment by jst71** [comment]
Ich habe es bereits behoben, es fehlte der link
 use Joomla\Registry\Registry;
in com_sportsmanagement\views\teamplan\tmpl\default_plan.php

Werde dafür einen Pull Request erstellen, sobald mein GIT aktualisiert ist.

**Comment by diddipoeler** [comment]
Erledigt.
