### ISSUE TITLE
0 - Class 'JCommentsModel' not found

### ISSUE THREAD

**Issue by jst71** [diddipoeler/sportsmanagement#960]
Nach dem Fix #959 zeigt sich das nächste Problem auf: https://tipps.stelteronline.de/spielplan/teamplan/0/0/6:wm2018/1:deutschland/0/121:deutschland

Fehlt mir die Komponente? Wie kann ich sie nachinstallieren?

**Comment by diddipoeler** [comment]
Ja, dir fehlt die Komponente !

**Comment by jst71** [comment]
Wie kann ich sie den nnachrüsten? Bei https://tipps.stelteronline.de/administrator/index.php?option=com_sportsmanagement&view=extensions
erscheint bei mir:
Warning: count(): Parameter must be an array or an object that implements Countable in com_sportsmanagement/libraries/sportsmanagement/view.php on line 94

**Comment by jst71** [comment]
Ach, das nutzt jetzt wirklich JComments? In den Projektsettings steht noch Kunena Brigde? Kann man das umschalten oder muss meine vorhandene eigene Kunena Bridge portieren?

**Comment by diddipoeler** [comment]
Das verstehe ich jetzt irgendwie nicht !

**Comment by jst71** [comment]
Ok, ich habe unter https://tipps.stelteronline.de/administrator/index.php?option=com_sportsmanagement&view=project&layout=edit&id=6 den aus Joomleague übernommenen Kunena link gefunden:
![grafik](https://user-images.githubusercontent.com/8502569/71621613-a171c080-2bd0-11ea-98da-22637375c10e.png)
und hatte beim JSM Plugin - Sportsmanagement Comments gedacht, dass es diesen Zugriff auf das Kunena board nutzen würde.
Oder gibt es diese Felder in aktuellen JSM Projekten gar nicht mehr?
Ich würde auf jeden Fall wenn nichts dagegen spricht das "JSM Plugin - Sportsmanagement Comments" so konfigurierbar machen, dass es alternativ auch auf Kunena zugreifen kann.

**Comment by sigal** [comment]
Das steht aber im Plugin, dass JComments installiert sein muß. 

Der Zugriff auf das Kunena-Boord wird doch im Projekt gesteuert. 

Für einen eigenen Zugriff mittels Plugin soll ein eigenes Plugin bevorzugt werden.

Ein Plugin für 2 verschiedene Komponenten (JComments, Kunena-Forum) stiftet nur Verwirrung.

Für das erste sollte im Template >

teamplan | Mannschafts-Spielplan Anzeige< folgendes ausgeschaltet sein:

![issue-960](https://user-images.githubusercontent.com/5115688/71623441-e996e000-2bdc-11ea-9d31-a8f137d5cf94.jpg)

**Comment by jst71** [comment]
Danke für die Erklärung, aber die Frage bleibt, wie ich meine Kunena Kommentare dann auf das Template bekomme. Ich habe die über denselben Schalter und JL2.0 aktiviert:
![grafik](https://user-images.githubusercontent.com/8502569/71625265-22d44d80-2be7-11ea-9c36-02d82bb3e751.png)
Hier erfolgte die Kommentarverbeitung dann über Kunena und nicht über JComments mit dem Zugriff auf die Projekteinstellungen:
![grafik](https://user-images.githubusercontent.com/8502569/71625297-544d1900-2be7-11ea-8fdc-345ce2f5d0a9.png)

Daher war meine Idee in der JSM Kommentarkomponente abzufragen, welche Kommentarkomponente vohanden ist, bzw. genutzt werden soll und es dann für die Darstellung im teamplan Template transparent zu haben (ansonsten müsste ich da den code für beide Kommtarkomponenten integrieren)

Können wir uns dazu sonst per direktem Chat einmal abgleichen?

**Comment by jst71** [comment]
Ich habe mir das nun noch einmal angesehen. Ich denke, ich werde die Darstellung der Comments analog zu der Pagenav implementierung machen:
Statt nur "sportsmanagementModelPagination::pagenav(...)" gibt es dann auch 
"sportsmanagementModelComments::ShowCommentIcon(...)" wohin ich den existierenden code verschieben würde.
Dadurch kann man den code in den Templates, wo man die Kommentierung verwenden möchte extrem schlank halten und auf zuviel Copy and Paste verzichten.
Zusätzlich kann ich in dem Helper "sportsmanagementModelComments" die Abfrage rgänzen, ob man Kommentare mit JComment oder Kunena konfiguriert hat.
Wenn nichts dagegen spricht würde ich das für meinen Fork mal implementieren und sobal es fertig ist, als Pull Request anbieten.

**Comment by diddipoeler** [comment]
Kann jede Unterstützung gebrauchen.
