### ISSUE TITLE
Backend: Spieler zuordnen

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#961]
Beim Versuch einer Mannschaft Spieler zuzuordnen erscheint folgender Fehler
404 View nicht gefunden [Name, Typ, Präfix]: persons, html, sportsmanagementView

**Comment by PhantoSGE** [comment]
![zuordnen1](https://user-images.githubusercontent.com/9608697/71619472-cf510800-2bc4-11ea-96da-6f4c2baa4b11.PNG)
![zuordnen2](https://user-images.githubusercontent.com/9608697/71619475-d11acb80-2bc4-11ea-8d16-e808345a6d91.PNG)

Mannschaften hinzufügen funktioniert.
![zuordnen3](https://user-images.githubusercontent.com/9608697/71619480-d9730680-2bc4-11ea-8dab-d470f548222c.PNG)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Die Liste erscheint nun. Nachdem man Spieler hinzugefügt hat und die Änderungen übernehmen möchte erscheint folgende Meldung
![zuordnen4](https://user-images.githubusercontent.com/9608697/71622883-10531780-2bd9-11ea-92b0-5c1dae325817.JPG)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
0 Call to a member function load() on boolean

**Comment by diddipoeler** [comment]
Da ich das nicht so nachvollziehen kann, bitte unter Konfiguration System "System debuggen" 
auf ja stellen. Dann bekommt man auch die Datei mit Zeilennummer und muss nicht immer
so lange suchen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Sieht gut aus. Mach ich in der Zukunft.
Guten Rutsch
