### ISSUE TITLE
Joomleagueimport Tippspiel

### ISSUE THREAD

**Issue by diddipoeler** [diddipoeler/sportsmanagement#965]

**Comment by jst71** [comment]
Als Reminder: Bei der Portierung können nicht alle id Fehler der Tabellen 100% identisch übernommen werden. In diesem Beispiel wird die id des matches in der match Tabelle von 291 auf 290 verschoben.
![grafik](https://user-images.githubusercontent.com/8502569/71780061-23415f80-2fbe-11ea-9bc1-a5bcebf405d5.png)
Dabei wird die original id 291 in der neuen 290er Zeile unter import_id erhalten.
In weiteren Portierungsschritten müssen nun alle matchid in allen Tabellen auf die import id umgesetzt werden.
Dieses Issue dient dazu, dass für die predicition tabellen nach zu ziehen.
1.) match ids of `rg7om_joomleague_prediction_result` (`id`, `prediction_id`, `user_id`, `project_id`, `match_id`, `tipp`, `tipp_home`, `tipp_away`,
![grafik](https://user-images.githubusercontent.com/8502569/71780115-e9248d80-2fbe-11ea-971e-cb2b08762be6.png)
2.) champ tipps
3.) Favorite team

**Comment by jst71** [comment]
Weiteres Issue:
4.) die team_id der joomleague_project_team tabelle wird nicht richtig übernommen:
JL:
![grafik](https://user-images.githubusercontent.com/8502569/71815441-c73f0f80-307f-11ea-9439-cfc5270b5206.png)
JSM (id und team_id sind überall gleich!):
![grafik](https://user-images.githubusercontent.com/8502569/71815500-f3f32700-307f-11ea-9f2c-8895b1dcc8d1.png)

**Comment by sigal** [comment]
Kann ich bei meinen 1700 importierten  jl-projekten nicht nachvollziehen.

**Comment by jst71** [comment]
Ich hatte das auch nur als Reminder eingestellt, ich will mir das bei mir eh selber ansehen (evtl mit diddis Hilfe). Ich denke, die Portierung bei mir hatte ein paar Besonderheiten
1.) Die Ids waren vorher nicht fortlaufend, sodern hatten "Lücken", wodurch die Notwendigkeit zur import_id erst aufkam
2.) Ich habe 6 Turniere in der DB, wodurch die project_team tabelle mappen muss (bei einem Projekt sind die team_id wohl gleich id)
3.) Die Portierung der JL=>JSM Tabellen war soweit fehlerfrei, das Problem bezieht sich auf das Tippspiel. (predicition tables)

**Comment by jst71** [comment]
Der Import braucht wohl viel RAM:
![grafik](https://user-images.githubusercontent.com/8502569/72221287-789ae500-3559-11ea-9373-6756bc1a7b41.png)
Vielleicht war es deshalb bei mir zu knapp. Ich bleibe bei diesem Thema jetzt dran.

**Comment by jst71** [comment]
(4) hat sich erledigt. Die Abfrage match -> projectteam_id -> team_id geht nun über die season id:
// Select some fields
$query->select(' t1.name AS home,t2.name AS away ');
$query->from('#__sportsmanagement_match AS m');
$query->join('LEFT',' #__sportsmanagement_project_team as pt1 ON pt1.id = m.projectteam1_id ');
$query->join('LEFT',' #__sportsmanagement_season_team_id as st1 ON st1.id = pt1.team_id ');
$query->join('LEFT',' #__sportsmanagement_team as t1 ON st1.team_id = t1.id ');
...
Habe die sportsmanagementModelComments::getForumSubjectFromMatchID($match_id) angepasst

**Comment by jst71** [comment]
Hallo Diddi, ich denke hier kann auch zu. Die alten Tippspiele werden jetzt sauber importiert
