### ISSUE TITLE
default templates aktualisieren (= add new settings)

### ISSUE THREAD

**Issue by jst71** [diddipoeler/sportsmanagement#966]
Funktion schaffen, um neue template setting mit ihren default werten in den bestehenden Template Konfigurationen zu ergänzen. (vermeidung von variable not defined Fehlern)

![grafik](https://user-images.githubusercontent.com/8502569/71780012-5df6c800-2fbd-11ea-907b-f38aead49691.png)

**Comment by jst71** [comment]
Feature ist mit dem commit implementiert. Werde noch ein wenig testen, bevor ich einen PR stelle.

**Comment by sigal** [comment]
Eine winzige Anmerkung: 
Die Englische Übersetzung bitte auf https://www.transifex.com/jsm/
Ansonsten wird wieder alles überschrieben.
Danke für die Mühe. :thumbsup:

**Comment by jst71** [comment]
Habe mich da nun angemeldet (jst71), komm abr irgendwie nicht klar. Benötige ich noch weitere Rechte oder wo kann ich die Texte auswählen, bzw. neue anlegen?
Danke!

**Comment by sigal** [comment]
Mit welchen usernamen? jst71 ist in Transifex nicht zu finden.

![#966](https://user-images.githubusercontent.com/5115688/72003966-be4e6980-324a-11ea-8d26-eb7807365804.jpg)

Hätte dich dann als Reviewer für Englisch freigeschaltet.

Neue Texte werden nur in den deutschen language-files neu angelegt und mittels PR auf diddis GitHub-Projekt angelegt.
Diese Dateien werden automatisch von Transifex abgerufen und zur Übersetzung in andere Sprachen bereitgestellt. z.B. in de-DE.com_sportsmanagement.ini
COM_SPORTSMANAGEMENT_ADMIN_TEMPLATES_UPDATE="Neue Parameter ergänzen"
COM_SPORTSMANAGEMENT_ADMIN_TEMPLATES_UPDATE_SUCCESS="Neue Parameter wurden erfolgreich aus defaults ergänzt"

wird in allen anderen Sprachen als nicht übersetzt geführt.
COM_SPORTSMANAGEMENT_ADMIN_TEMPLATES_UPDATE=""
COM_SPORTSMANAGEMENT_ADMIN_TEMPLATES_UPDATE_SUCCESS=""

**Comment by jst71** [comment]
Sehe jetzt das:
![grafik](https://user-images.githubusercontent.com/8502569/72020906-1b5b1700-326d-11ea-9573-e44b39c4931b.png)
"As a translator", nicht als reviewer?

**Comment by sigal** [comment]
Jetzt schon. Gestern noch nicht.

![#966-2](https://user-images.githubusercontent.com/5115688/72055232-bfbf7680-32ca-11ea-8b1e-f5b728adebcc.jpg)

**Comment by jst71** [comment]
Habe das feature nun getestet und es generiert denselben DB config string, als wenn man selber die Templates editiert und neu abspeichert. Daher habe ich einen PR gestellt.

Werde dann nachdem der PR durch ist, die englische Übersetzung in transifex einpflegen! Der Zugang funktioniert => Danke sigal!

**Comment by jst71** [comment]
Ich hatte das so verstanden, dass sie erst einmal nicht stören, nur durch den Sprachflow wieder mit den Deutschen überschrieben werden.
Inzwischen sind die neuen Texte bei Transifex auch da, so dass ich sie da eintragen werden, dann passt wieder alles. Beim nächsten Mal werde ich die englischen Texte auch nicht mehr in den commit mit aufnehmen.

**Comment by diddipoeler** [comment]
Kann ich hier schließen ?

**Comment by jst71** [comment]
Aus meiner Sicht, ja.
