### ISSUE TITLE
Frontend: Spielerinformation

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#969]
Wenn ich aus der Kaderansicht einen Spieler auswähle erscheint diese Fehlermeldung.
Dies habe ich nur bei einer neu angelegten HP. Auf einer älteren funktioniert es einwandfrei.

![image](https://user-images.githubusercontent.com/9608697/71828280-5bba6980-30a2-11ea-80fa-60813ae4000e.png)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
Lieder immernoch eine Fehlermeldung
![image](https://user-images.githubusercontent.com/9608697/71881941-ab954100-3133-11ea-8f2a-afb6ca3faefa.png)

**Comment by diddipoeler** [comment]
Den Fehler habe ich nicht.

**Comment by sigal** [comment]
Bei einer neu eingerichteten Seite gibt es den Fehler doch.
Bei bestehehenden alten Seiten (also per Update auf heutigen Stand gebracht) gibt es diesen Fehler nicht.
Einen weiteren Fehler gibt es bei neu eingerichteten Seiten beim Resultsranking Hier fehlt eindeutig eine Datei, die im aktuellen GitHub abhanden gekommen ist.  ( /components/com_sportsmanagement/views/globalviews/tmpl/default_selectround.php )

Man kann das auf einer jetzt extra dafür eingerichteten Seite nachvollziehen (PHP 7.3.13)

Für das resultsranking den passenden Menueintrag wählen: https://test.jsm-help.de/

Player bitte auswählen: https://test.jsm-help.de/index.php/ranking/roster/0/0/1:deutschland-2-bundesliga-2019-20/16:vfb-stuttgart/1:vfb-stuttgart

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.
Und sorry Jungs. Bin gerade ein bisschen überarbeitet :-)

**Comment by sigal** [comment]
Ok! jetzt läuft es auch auf einer "Neuen Seite". :clap:

**Comment by PhantoSGE** [comment]
Super, sieht gut aus
