### ISSUE TITLE
Frontend resultsranking

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#970]
Das Modul Resultsranking erzeigt folgenden fehler.

![image](https://user-images.githubusercontent.com/9608697/71984488-3ad05080-3229-11ea-828b-893b5e07c85e.png)

Gruß
Sven

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by PhantoSGE** [comment]
sieht gut aus 
Danke dir
