### ISSUE TITLE
Frontend: results /resultsranking

### ISSUE THREAD

**Issue by PhantoSGE** [diddipoeler/sportsmanagement#971]
Moin zusammen,

bei beiden Ansichten wird der Spielort doppelt angezeigt.
![image](https://user-images.githubusercontent.com/9608697/72148167-704b7a00-33a0-11ea-879c-9cd99ca28f54.png)

Gruß
Sven

**Comment by jst71** [comment]
Es ist tatsächlich so, dass in den tem,plates der SPielort zweimal aufgerufen wird:
![grafik](https://user-images.githubusercontent.com/8502569/72218298-f8b15280-3539-11ea-891c-12214c1b07ff.png)
2.)
![grafik](https://user-images.githubusercontent.com/8502569/72218307-0961c880-353a-11ea-80b6-95cf56d0b37d.png)

Interessanterweise steht bei dem zweiten Aufruf "", allerdings ist der code identisch, so dass nirgendwo festgestellt wird, ob der Spielort sich vom "normalen" unterscheidet.

Ich werde das zweite korrigiern, dass es auf das "Eine Warnung anzeigen.." der config reagiert.
![grafik](https://user-images.githubusercontent.com/8502569/72218409-bdfbea00-353a-11ea-9432-fc6a24d0d6d2.png)

@diddipoeler : DIe Frage ist, wie die Warnung aussehen soll?

**Comment by diddipoeler** [comment]
Warnung vielleicht so: Austragungsort des Spiels stimmt nicht mit Vereinsstammdaten überein.

**Comment by jst71** [comment]
Es bleibt die Frage, an welcher Position es angezeigt werden soll? Vor oder nach der Spielpaarung
![grafik](https://user-images.githubusercontent.com/8502569/72363905-ee3bb800-36f5-11ea-943e-6809b42ff348.png)

Oder vorne der Ort, hinten die Warnung?
![grafik](https://user-images.githubusercontent.com/8502569/72364187-5f7b6b00-36f6-11ea-81c2-ef7552abc15a.png)

**Comment by PhantoSGE** [comment]
Mit persönlich würde es besser gefallen wenn der Ort hinten und die Warnung vorne steht.

**Comment by jst71** [comment]
Ich wollte das jetzt mal fixen, dabei ist mir aufgefallen, dass das feature irgenwas ganz anders macht: 
sobald Spieort nicht Heimspielort ist, wird angeboten, einen neuen Spielort zu erstellen und das führt aber in den Modifigkationsdialog des eingestellten Spielorts:
![grafik](https://user-images.githubusercontent.com/8502569/74634264-c364d980-5163-11ea-85b3-32d94991c6f0.png)
Ich würde das also mal wie oben besprochen auf die Warnung umbauen und die Positionen konfigurierbar machen.

**Comment by jst71** [comment]
Habe es jetzt so umgesetzt, dass die Warnung umschaltbar ist vom Tooltip (wie bisher) und der Möglichkeit die Wwarnung vor der SPielstätte anzuzeigen:
![grafik](https://user-images.githubusercontent.com/8502569/74640883-98cd4d80-5170-11ea-84c1-7bc3beed9a24.png)
1.)
![grafik](https://user-images.githubusercontent.com/8502569/74641101-04afb600-5171-11ea-87d8-8155f20b6856.png)

2.)
![grafik](https://user-images.githubusercontent.com/8502569/74640934-b39fc200-5170-11ea-8f26-b0e18044c99d.png)

Das doppelte Vorkommen habe ich auch beseitigt. @PhantoSGE : Kannst DU das bitte mal testen ?

**Comment by PhantoSGE** [comment]
Sieht gut aus. Danke
