### ISSUE TITLE
Backend : Projektteams

### ISSUE THREAD

**Issue by sigal** [diddipoeler/sportsmanagement#987]
Code wird seit 5 Tagen im Backend der Ansicht der Projektmannschaften angezeigt.

![projektmannschaften01](https://user-images.githubusercontent.com/5115688/74280001-34e3f880-4d1c-11ea-8fc7-ee53deec83cf.jpg)

Die Änderung im GitHub sollte doch in der default.php erfolgen? die default_teams.php erzeugt jetzt die Quelltextanzeige.

![projektmannschaften02](https://user-images.githubusercontent.com/5115688/74280508-f69b0900-4d1c-11ea-9a7d-369783f1788f.jpg)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Bis hier ist jetzt alles in Ordnung.

Nächstes Issue in dieser Ansicht: Ubernahme der Bilder.

![projektmannschaften03](https://user-images.githubusercontent.com/5115688/74359709-0cafd480-4dc4-11ea-9f63-1fd4662ee1be.jpg)

![projektmannschaften04](https://user-images.githubusercontent.com/5115688/74359721-15a0a600-4dc4-11ea-8d75-9be3a22cbff7.jpg)

**Comment by sigal** [comment]
Keine Änderung
