### ISSUE TITLE
Geburtstagsmodul - Monat wird in Englisch ausgegeben

### ISSUE THREAD

**Issue by Tobsen84** [diddipoeler/sportsmanagement#992]
Moin zusammen,

beim Geburtstagsmodul wird der Monat in der englischen Sprache ausgegeben.

![Geburtstagsmodul - Monat (Englisch)](https://user-images.githubusercontent.com/61277544/74933055-7a22bd00-53e3-11ea-9f25-fe182e00bd7e.PNG)

Viele Grüße
Tobsen84

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Mit diesem Fix haben alle Spieler den selben Geburtstag, die in einem bestimmten Zeitraum angezeigt werden. siehe https://demo.jsm-help.de/  (Llink der Spieler zum Überprüfen klicken)
Vorschlag: default.php nicht ändern.
in mod_sportsmanagement_birthday.php : Zeile 21 - 23 einfügen
`$lang = Factory::getLanguage();`
`$locales = $lang->getLocale();`
`setlocale (LC_ALL, $locales[0]);`

Zeile 51 `$language = Factory::getLanguage();` auskommentieren oder löschen
Zeile 52 `$language->load('com_sportsmanagement', JPATH_ADMINISTRATOR, null, true);`
ändern in `$lang->load('com_sportsmanagement', JPATH_ADMINISTRATOR, null, true);`

Voraussetzung: am Server sind die passenden locales installiert.
Auf einen Debian Server mit `sudo locale -a` überprüfen, welche installiert sind.
Fehlende locale mit `sudo dpkg-reconfigure locales` installieren.

Während der Laufzeit hilft der Code nicht, wenn z.B. de_DE.UTF8 , de_DE.UTF-8 am Server nicht installiert sind. (Mußte dies auf meinem auch nachinstallieren :ghost:)

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Bitte die original default.php auf GitHub schieben. wie oben beschrieben.
Mit dieser und den getätigten Änderungen funktioniert es. Jetzt auf meinem Server zu sehen.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by sigal** [comment]
Alles OK von meiner Seite
Den pr der englischen übersetzung ziehe ich jetzt zurück, da Fehler von #994 erst behoben werden müssen.

**Comment by Tobsen84** [comment]
Hallo zusammen,

von meiner Seite passt es auch was den englischen Monat betrifft. Was mir allerdings gerade noch aufgefallen ist (ich hoffe es ist okay, wenn ich das in diesem Issue mit aufnehme), es scheint die Einstellung für die Anordnung, wenn am selben Tag mehrere Personen Geburstag haben, vertauscht zu sein. Gemäß unserer Einstellung soll der Jüngste zuerst angezeigt werden aber es wird zuerst der Älteste angezeigt. Wenn ich die Einstellung umstelle, ändert sich auch die Reihenfolge. Siehe folgende Screenshots...
![Geburtstagsmodul - Einstellung (Jüngster)](https://user-images.githubusercontent.com/61277544/75611682-fa040200-5b1c-11ea-9f25-872b43835729.PNG)

![Geburtstagsmodul - Frontenddarstellung](https://user-images.githubusercontent.com/61277544/75611685-05572d80-5b1d-11ea-9b94-444efc89470b.PNG)

Viele Grüße
Tobsen84

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Tobsen84** [comment]
Leider fehlgeschlagen. Jetzt wird die komplette Geburtstagsliste aufgrund des Alters sortiert und das Datum ingnoriert. Die Sortierung aufgrund des Alters soll ja nur stattfinden, wenn Personen am selben Tag Geburtstag haben.

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Tobsen84** [comment]
Jetzt passt es perfekt. Vielen Dank. Von meiner Seite kann das Ticket geschlossen werden.

Gruß
Tobsen84
