### ISSUE TITLE
DFBNET import spielplan 1 upload ok 2 versuch ergibt fehler

### ISSUE THREAD

**Issue by Europekicker** [diddipoeler/sportsmanagement#996]
Beim importieren des Spielplanes als export von DFBNET ist der erste versuch erfolgreich.

Beim importieren einer 2 liste andere Liga erscheint folgender fehler

0 Call to a member function getTable() on bool 

im einsatz Plesk PHP 7.3 mit nginx joomla 3.9.15

tmp dir ist

upload_tmp_dir=/var/www/vhosts/xxxx.de/httpdocs/tmp
open_base
{WEBSPACEROOT}{/}{:}{TMP}{/}{:}{/}var{/}lib{/}php{/}sessions{/}

fehler logs sind eher unaufällig

> 2020/03/03 09:02:10 [error] 21496#0: *1794499 FastCGI sent in stderr: "lextdfbnetplayerimport.php on line 1549PHP message: upload_tmp_dir 'Spielleitung' in /var/www/vhosts/xxxxxx/httpdocs/administrator/components/com_sportsmanagement/models/jlextdfbnetplayerimport.php on line 1590PHP message: PHP Warning:  Illegal string offset 'Assistent 1' in /var/www/vhosts/xxxxxxxx/httpdocs/administrator/components/com_sportsmanagement/models/jlextdfbnetplayerimport.php on line 1591PHP message: PHP Warning:  Illegal string offset 'Assistent 2' in /var/www/vhosts/xxxx/httpdocs/administrator/components/com_sportsmanagement/models/jlextdfbnetplayerimport.php on line 1592" while reading response header from upstream, client: xxxxxxxx, server: xxxxx, request: "POST /administrator/index.php?option=com_sportsmanagement&view=jlextdfbnetplayerimport HTTP/2.0", upstream: "fastcgi://unix:///var/www/vhosts/system/xxxxxx/php-fpm.sock:", host: "xxxxxxx", referrer: "https://xxxxxx/administrator/index.php?option=com_sportsmanagement&view=jlextdfbnetplayerimport"

**Comment by diddipoeler** [comment]
Bitte mal den Debug-Modus einschalten, dann wird
auch die Datei und die Zeile angezeigt in der der Fehler ist.

**Comment by Europekicker** [comment]
es werde 2 meldungen angezeigt einmal 

0 Call to a member function getTable() on bool
/var/www/vhosts/europekicker.de/httpdocs/administrator/components/com_sportsmanagement/models/jlxmlimport.php:2995  

Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/vhosts/europekicker.de/httpdocs/administrator/components/com_sportsmanagement/libraries/sportsmanagement/view.php on line 94

**Comment by diddipoeler** [comment]
Bitte noch einmal testen.

**Comment by Europekicker** [comment]
Alles super funktioniert nun
wie immer schneller bugfix von dir danke
